### ISSUE TITLE
Browser/Device regression testing for 3.0 - Part 1: B2B Focus

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#10012]
Based off of [Test matrix](https://cxwiki.sap.com/display/spar/Test+Matrix)

**Device/Browser assignments**
Use password 1234

Device | OS | Browser | admin login | Team Tester | Done
-|-|-|-|-|-
Phone | iOS | Safari | admin@unitA.sap |@mirkosoft |
Phone | Android | Chrome | admin@unitB.sap | |
Tablet | iOS | Safari | admin@unitC.sap | |
Desktop | Mac | Safari | admin@unitD.sap | @dydome Michał Dydo|
Desktop | Mac | Chrome | admin@unitE.sap | not needed we all use chrome already| 
Desktop | Mac | Firefox | admin@unitF.sap |Weizheng |  
Desktop | Windows | Edge | admin@unitG.sap | @mszczepaniak | 
Desktop | Windows | Chrome | admin@unitH.sap | @dydome Michał Dydo | 
Desktop | Windows | Firefox | admin@unitI.sap |@Matejk00 |
Phone(small)* | iOS | Safari | admin@unitJ.sap |  |
Tablet(mini)* | iOS | Safari | admin@unitK.sap | |
Tablet | Android | Chrome | PEND | | 

\* Stretch - IF someone has a small phone 

**For each device:**

Testing URLs: 

- B2B testing on CCV2 https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

Admin tasks: 
- sign in as admin
- create a unit
- edit a unit
- create a sub unit
- create a buyer and assign to a unit
- edit the buyer
- create a cost center
- create a budget
- assign a budget to a cost center
- add an address to a unit
- add another address
- delete first one
- create an approver
- assign to a unit and a user
- create a spending permission
- assign spending permission to users
- create a user group and assign things to it
- delete an address
- delete a user group
- disable a unit you created (not a high level one)

Buyer tasks:
- Log in as your buyer
- Spend too much money so that it requires approval
- Check out using account, choosing cost center etc.
- Repeat
- Buy something else using credit card, and set scheduled replenishment
- Check that the order shows up in scheduled replenishment list (but is not yet placed)

Approver task:
- Log in as approver and see something to approve
- Approver 1, reject the other

Buyer
- Log back in as buyer to check approvals/rejections
- Check order details to see b2b purchase details

**Comment by Xymmer** [comment]
Since we all habitually use Chrome, not high priority to test officially Chrome (only one left)

**Comment by hackergil** [comment]
Reopening to test RC4

**Comment by WeizhengSap** [comment]
[Test On Fireforx]: I cannot create a unit with name as "test" and id "test". Nothing happens. There is no error message. Change the name to "test unit" and id "test_unit", it works.
![Screen Shot 2020-12-16 at 4 23 38 PM](https://user-images.githubusercontent.com/44440575/102408337-6c19da80-3fbb-11eb-8744-6b335b006c66.png)

**Comment by WeizhengSap** [comment]
[Test On Fireforx]: When create a user, the unit dropdown list is empty. Only after click "save", then I can select a unit.
![Screen Shot 2020-12-16 at 4 30 48 PM](https://user-images.githubusercontent.com/44440575/102408850-31647200-3fbc-11eb-8af2-a1619f1f284b.png)

after clicking "save" button:
![Screen Shot 2020-12-16 at 4 30 59 PM](https://user-images.githubusercontent.com/44440575/102408883-3a554380-3fbc-11eb-865d-cacd27dd6b7b.png)

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] Can't assign newly created budget to a cost center: after entering the budget's cost center section the list is empty.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] can't create address for a unit: clicking "save" does nothing.
UPDATE: It creates an address but doesn't close the form either no message (added succesfuly) appears. In effect we have multiple same addresses added (because of clicking "save" many times)
UPDATE: No orders to approve when logged in as approver.

**Comment by dydome** [comment]
> [Iphone 7 @ safari] Can't assign newly created budget to a cost center: after entering the budget's cost center section the list is empty.

The same on Windows/Chrome

**Comment by dydome** [comment]
[Windows/Chrome and Mac/Safari] Cannot create Unit with: name: test, id: 123, selected approval process and selected parent business unit. No error on page. In console error:
`{
   "errors" : [ {
      "message" : "Expected: class de.hybris.platform.b2b.model.B2BUnitModel but got: class de.hybris.platform.b2b.model.B2BUserGroupModel",
      "type" : "ClassMismatchError"
   } ]
}`

**Comment by dydome** [comment]
[Windows/Chrome] Cannot place order with replanish order option (no error on page)

![image](https://user-images.githubusercontent.com/18736434/102488228-046f9800-406c-11eb-8b5f-ad71adf49e27.png)

![image](https://user-images.githubusercontent.com/18736434/102488242-09cce280-406c-11eb-8ebd-95d7bd232fb1.png)

![image](https://user-images.githubusercontent.com/18736434/102488254-0d606980-406c-11eb-8c5f-703cb7021653.png)

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] no message after setting a password for a user.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] what are the rules for purchase limits edition? Can't edit or change type.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] Was able to purchase things for $1503.99 (one time) while purchase limit is set to ~800 $ per week.
UPDATE: using cost center with a smaller budget and purchase limit as well.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] There is "quotes" entry in the menu however it returns 404 page.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] Replenishement Order Confirmation title exceeds screen width.

**Comment by mirkosoft** [comment]
[Iphone 7 @ safari] Main menu sometimes acts buggy but not sure how to repro yet.

**Comment by dydome** [comment]
opened:
#10469
#10470
#10471 
#10472

**Comment by dydome** [comment]
> [Iphone 7 @ safari] Was able to purchase things for $1503.99 (one time) while purchase limit is set to ~800 $ per week.
> UPDATE: using cost center with a smaller budget and purchase limit as well.

Had the same problems on windows and mac.
