### ISSUE TITLE
Provide JSON i18n files for storefinder library

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#10016]
**Is your feature request related to a problem? Please describe.**
At the moment, the separated store finder library does only offer a js file with it's i18n values in it.

**Describe the solution you'd like**
To be able to use lazy loading as described here: https://sap.github.io/spartacus-docs/i18n/#lazy-loading, it would be great to also have a json i18n asset file as it is available for the core app

**Describe alternatives you've considered**
As an alternative, I could copy the js file into my project, but I would prefer to have all i18n assets in the json format, also regarding giving them to the client to translate it..

**Comment by Xymmer** [comment]
will be done with #9186, closing as duplicate
