### ISSUE TITLE
Smartedit testing for 3.0

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#10013]
Test smartedit with
- [x] Electronics
- [x] Apparel
- [x] Powertools

**Comment by giancorderoortiz** [comment]
Please include screenshots for future reference.

**Comment by WeizhengSap** [comment]
I found some minor issues:

1. The preview image of powertools-spa is the electroncs-spa one
![Screen Shot 2020-11-27 at 1 40 36 PM](https://user-images.githubusercontent.com/44440575/100618942-79ac4080-32ea-11eb-93bc-39e0e6c219c2.png)

2. after making a component invisible, the page is auto-rendered (component is invisible); but after making a component visible, the page is not auto-rendered. We have to refresh the page to make the component visible again.
![Screen Shot 2020-11-27 at 1 33 07 PM](https://user-images.githubusercontent.com/44440575/100619124-b24c1a00-32ea-11eb-8f56-49a19d615654.png)
 
3. There are two toggle switches in "product references component": "display product prices" and "display product titles". Enable them or not does not change the component display
![Screen Shot 2020-11-27 at 1 36 53 PM](https://user-images.githubusercontent.com/44440575/100619377-09ea8580-32eb-11eb-8527-bd745478e059.png)

I tested add/edit component. It works well. So, the auto-render in SPA works.
a). update image
![Screen Shot 2020-11-27 at 1 44 47 PM](https://user-images.githubusercontent.com/44440575/100619505-3c947e00-32eb-11eb-883a-cc0b74acd3b9.png)
b). add a new component
![Screen Shot 2020-11-27 at 1 46 13 PM](https://user-images.githubusercontent.com/44440575/100619553-52a23e80-32eb-11eb-9e26-2127856eeade.png)

**Comment by WeizhengSap** [comment]
Tested apparal-uk site, meet the same issues. Others work well.

![Screen Shot 2020-12-01 at 8 47 48 AM](https://user-images.githubusercontent.com/44440575/100749057-24d3fd00-33b2-11eb-803e-ba443ac79993.png)
