### ISSUE TITLE
[Edge Windows] B2B users icon missing on my company page

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/spartacus#10034]
Users icon is missing on the my company page.

**Version**
- Edge 86.0.622

**To Reproduce**
1. Click on My Account
2. Click on My Company
3. See the missing icon

![users icon missing](https://user-images.githubusercontent.com/4272069/100443193-8130d700-30a9-11eb-9aef-2a030bd96590.png)

**Comment by tobi-or-not-tobi** [comment]
@mszczepaniak 
- was this a one time only error or something that you could reproduce? 
- can you open https://api.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/medias/users.svg?context=bWFzdGVyfGltYWdlc3w0MTJ8aW1hZ2Uvc3ZnK3htbHxoY2MvaDExLzg3OTczMTk2OTIzMTgvdXNlcnMuc3ZnfGY1ODVmMDhmODU4MTE1MDhjZmU2MzYyZTYyMjJhNTNhMTVkNDdkOTZjZGYyM2U5NjQ4OWEyYzI5MGIzODI5ZmE and does it show the icon correctly in edge
- if you drop the CSS filter that is applied to the img, do you see the image then? (you can toggle the filter by dev tools, selecting the img element)

FYI, I'm not able to reproduce in Microsoft Edge on Mac. That's fine as it's a different browser.

**Comment by mszczepaniak** [comment]
> @mszczepaniak
> 
> * was this a one time only error or something that you could reproduce?
> * can you open https://api.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/medias/users.svg?context=bWFzdGVyfGltYWdlc3w0MTJ8aW1hZ2Uvc3ZnK3htbHxoY2MvaDExLzg3OTczMTk2OTIzMTgvdXNlcnMuc3ZnfGY1ODVmMDhmODU4MTE1MDhjZmU2MzYyZTYyMjJhNTNhMTVkNDdkOTZjZGYyM2U5NjQ4OWEyYzI5MGIzODI5ZmE and does it show the icon correctly in edge
> * if you drop the CSS filter that is applied to the img, do you see the image then? (you can toggle the filter by dev tools, selecting the img element)
> 
> FYI, I'm not able to reproduce in Microsoft Edge on Mac. That's fine as it's a different browser.

1. One time, I see it now
2. Yes, I can see it on Edge.

We can close this issue.
