### ISSUE TITLE
'Item does not exist' message after create or edit unit (404 error)

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10036]
Note: There are 5 issues so far "item does not exist"
#10056 #10057 #10036 #10040 #10068

**Describe the bug**
After creating unit, the red message appears "item does not exist". It should be

**Tell us the version of Spartacus**
- test env https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/ (see https://github.com/SAP/spartacus/issues/10012)

**To Reproduce**
1. sign in as `admin@unitH.sap` `1234`
2. create a unit
3. Bug: red message appears "item does not exist" 

**Expected behavior**
No error message appears. The details of the brand-new unit are presented.

**Screenshots**
BEFORE ADDDING:
![obraz](https://user-images.githubusercontent.com/4001059/100446447-1f736b80-30af-11eb-9251-30ff1d0ae8ca.png)

AFTER ADDING:
![obraz](https://user-images.githubusercontent.com/4001059/100446468-28fcd380-30af-11eb-801a-7e5b0808654e.png)
![obraz](https://user-images.githubusercontent.com/4001059/100446590-5f3a5300-30af-11eb-853b-2d35382e23c4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version 87.0.4280.66

**Additional context**
- Similar issue appears after editing an unit.
- no error appears after full-refreshing the page

**Comment by mirkosoft** [comment]
I had the same issue with Firefox windows, here are more details on request/response:
```
-----------------------  create a subunit (was thinking creating a unit; it seems I cant create unit becuase parent is required) + screenshot
{"uid":"12366","name":"test miro","approvalProcess":{"code":"accApproval"},"parentOrgUnit":{"uid":"unitI"}}
{
   "active" : true,
   "approvalProcess" : {
      "code" : "accApproval",
      "name" : "Escalation Approval with Merchant Check"
   },
   "name" : "test miro",
   "parentOrgUnit" : {
      "active" : true,
      "name" : "unitI",
      "uid" : "unitI"
   },
   "uid" : "12366"
}
GET /occ/v2/powertools-spa/users/current/orgUnits/12366?lang=en&curr=USD HTTP/1.1
Host: api.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: application/json, text/plain, */*
Accept-Language: pl,en-US;q=0.7,en;q=0.3
Accept-Encoding: gzip, deflate, br
Authorization: bearer IZ5LdbGjh7BlsRWjoa0pJZKRo00
X-Anonymous-Consents: %5B%7B%22templateCode%22%3A%22MARKETING_NEWSLETTER%22%2C%22templateVersion%22%3A0%2C%22consentState%22%3A%22GIVEN%22%7D%2C%7B%22templateCode%22%3A%22PROFILE%22%2C%22templateVersion%22%3A0%2C%22consentState%22%3A%22GIVEN%22%7D%2C%7B%22templateCode%22%3A%22STORE_USER_INFORMATION%22%2C%22templateVersion%22%3A0%2C%22consentState%22%3A%22GIVEN%22%7D%5D
Origin: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud
Connection: keep-alive
Referer: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/organization/units/12366

{
   "errors" : [ {
      "message" : "Organizational unit with id [12366] was not found",
      "type" : "NotFoundError"
   } ]
}
```
