### ISSUE TITLE
Browser/Device regression testing for 3.0 - Part 2: A sampling of other features

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10030]
Based off of [Test matrix](https://cxwiki.sap.com/display/spar/Test+Matrix)

**Device/Browser assignments**
Device | OS | Browser | Tester | Done?
-|-|-|-|-
Phone | iOS | Safari | @hackergil | ✅ 
Phone | Android | Chrome | @hackergil | ✅ 
Tablet | iOS | Safari | | 
Desktop | Mac | Safari | Weizheng | ✅ 
Desktop | Mac | Chrome | Not needed - we all use Chrome | ✅ 
Desktop | Mac | Firefox | @hackergil  | ✅ 
Desktop | Windows | Edge | @hackergil | ✅ 
Desktop | Windows | Chrome | @plabadie| ✅  
Desktop | Windows | Firefox | @Zeyber | ✅
Phone(small)* | iOS | Safari | | 
Tablet(mini)* | iOS | Safari | | 
Tablet | Android | Chrome | | 

\* Stretch - IF someone has a small phone

**For each device, happy path check of some but not all features:**

B2C testing on CCV2 https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/

* Language/currency change
* PLPs (product search and facets)
* PDPs
* Registration/login
* Change password
* Checkout
* Add a review
* My account
  - Address book
* Product quantity change. (PDP, cart page)

* Apparel (locally, variants)
* Checkout as guest (after core tests have been done)
* Express checkout (after core tests have been done)
* Store locator (after core tests have been done)

**Comment by giancorderoortiz** [comment]
Some bugs found with iPad pro: 
https://github.com/SAP/spartacus/issues/10147
https://github.com/SAP/spartacus/issues/10146
https://github.com/SAP/spartacus/issues/10145

**Comment by Xymmer** [comment]
Android tablet was not a must do

**Comment by hackergil** [comment]
Reopening to test RC4
