### ISSUE TITLE
Missing validation error message under Unit in Create User form

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10038]
**Describe the bug**
When leaving field `Unit` empty in the Create User form, the dropdown gets only the red border, but no text message. Should have a message.

**Tell us the version of Spartacus**
- test env https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/ (see #10012)

**To Reproduce**
1. sign in as `admin@unitH.sap` `1234`
2. Go to https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/organization/users/create
3. Don't fill `Unit` filed and click `Save` button
4. Defect: no validation error message under the `Unit` field

**Expected behavior**
Message saying `This field is required`

**Screenshots**
![obraz](https://user-images.githubusercontent.com/4001059/100447996-df61b800-30b1-11eb-8645-8cdf03e0cb8a.png)

**Desktop (please complete the following information):**
-    OS: Windows 10
-    Browser Chrome
-    Version 87.0.4280.66

**Comment by mirkosoft** [comment]
The same on firefox windows
