### ISSUE TITLE
Creating a B2B user that already exists disables the form

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10041]
To repro:

- in my company, create a new user
- try to create a new user again, and type the same email address as for the previously created user

<img width="1675" alt="Screen Shot 2020-11-27 at 13 20 34" src="https://user-images.githubusercontent.com/11561723/100449122-a9bdce80-30b3-11eb-8856-6d44a4972f1c.png">

The following happens when clicked on the "Save":

- The error message appears saying "Already Exists". It's not clear what does already exist. The email? (yes, it's the email, I checked in the network tab of the 409 request). Maybe the unit assigned to the new user already has the same user? Or maybe something else? I suggest to change the error message to say e.g. "The email address already exists". (see the screenshot below)
- The form is now disabled. I couldn't change the first / last name, nor the email.

<img width="1642" alt="Screen Shot 2020-11-27 at 13 20 41" src="https://user-images.githubusercontent.com/11561723/100449132-ade9ec00-30b3-11eb-96f2-6bfb693c0705.png">

- Clicking on the "Save" again, causes a bunch of empty error messages to appear in the UI:
<img width="1516" alt="Screen Shot 2020-11-27 at 13 20 48" src="https://user-images.githubusercontent.com/11561723/100449446-39637d00-30b4-11eb-91b8-aa9ec68fc9f5.png">

**Comment by Pucek9** [comment]
It's related to #9351 (we set to 3.1 for general future fix) and #10129 (fixing for 3.0)

**Comment by Xymmer** [comment]
let's retest this one after #10129

**Comment by Pucek9** [comment]
QA steps:
- [ ] Create duplicated budget (code)
- [ ] Update existing budget with other existing code *
- [ ] Create duplicated cost center (code)
- [ ] Update existing cost center with other existing code
- [ ] Create duplicated permission (code)
- [ ] Update existing permission with other existing code *
- [ ] Create duplicated unit (code)
- [ ] Update existing unit with other existing code
- [ ] Create duplicated user (email) -> redirect to user list
- [ ] Update existing user with other existing email 
- [ ] Create duplicated user group (code) 
- [ ] Update existing user group with other existing code

Expecting result: See personalized notification + unfreeze form

\* We can't recognize that it's validation error or duplicated id, so displaying "Server validation error".
Another way for see this response is e.g. change mustBePositive validator to returns null, and try create budget with negative amount

**Comment by giancorderoortiz** [comment]
This issue is now fixed. 
Tested with myCompany components throughout. 
![Screen Shot 2020-12-14 at 11 17 15 AM](https://user-images.githubusercontent.com/46171897/102107036-47790380-3dff-11eb-9622-25c395081dbf.png)
![Screen Shot 2020-12-14 at 11 20 08 AM](https://user-images.githubusercontent.com/46171897/102107040-48119a00-3dff-11eb-97ba-f2f9c80a97c7.png)

![Screen Shot 2020-12-14 at 11 27 34 AM](https://user-images.githubusercontent.com/46171897/102107146-65deff00-3dff-11eb-989a-e63e2d7213d7.png)
