### ISSUE TITLE
Creating a user - entering a valid email throws an error 

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10043]
Related to #10041 

Attempting to create a user with e.g. _yyy@yyy.yyy_ shows an empty UI message.
Checking the network tab, I can see that this email is invalid for some reason (the xxx@xxx.xxx is a valid email address which I used a couple of times for various users without any problems).

<img width="1652" alt="Screen Shot 2020-11-27 at 13 43 20" src="https://user-images.githubusercontent.com/11561723/100450918-cb6c8500-30b6-11eb-828d-fd608815aaf4.png">

**Comment by Pucek9** [comment]
There is no country code like '.xxx' so backend validator doesn't allow for that. We don't have frontend validator uses current domain names: https://www.worldstandards.eu/other/tlds/

**Comment by tobi-or-not-tobi** [comment]
Very low priority. Customers are not going to add email addresses that won't exists. The backend is validating against real email addresses, and an error is nicely returned. If we could resolve the error in the messagebox, we're good to go.

**Comment by Xymmer** [comment]
let's update our general valdiator, and make sure b2b uses it as well

**Comment by giancorderoortiz** [comment]
An error message is thrown here. 
Why is that specific address invalid? I don't know. It seems to be a backend configuration issue. 
Re-open if necessary. 

An error message is thrown with a readable message, and that suffices for now.  
Retest done with 3.0 demo server. 

![Screen Shot 2021-06-06 at 10 51 45 AM](https://user-images.githubusercontent.com/46171897/120929056-75a41580-c6b5-11eb-9561-94215ac28c3a.png)
![Screen Shot 2021-06-06 at 10 50 15 AM](https://user-images.githubusercontent.com/46171897/120929057-789f0600-c6b5-11eb-95a8-355d99c9ccaf.png)
