### ISSUE TITLE
[iPad Pro] hover-mark left when clicking navigation menu link

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#10048]
**Describe the bug**

**Tell us the version of Spartacus**
- test env https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/ (see #10012)

**To Reproduce**
1. Login as any admin user using iPad or relative device
2. Hover My account menu and click my Company

**Expected behavior**
No hover on element lying beneath navigation menu

**Screenshots**
![C7A3A53D-5D3C-47DF-9962-FE82749BAA5B](https://user-images.githubusercontent.com/10993491/100453099-ac6ff200-30ba-11eb-8888-820f81c049fd.png)

**Tablet:**
 - iPad Pro
 - iOS: 14.2
 - Browser: Safari

**Comment by tobi-or-not-tobi** [comment]
This is actually standard web behaviour, when you hover elements. In a single page application, when you navigate, the page elements change dynamically. When new elements are added,  underneath the mouse, a hover effect automatically appears. 

I'd say: 
1. This is not ipad specific, it also happens on desktop
2. This is not really a bug, at least not something that we can fix. It's standard behaviour, but UX team might have a teak on this. 

Closing as it's a won't fix.
