### ISSUE TITLE
"This item does not exist" prompt on new unit creation appears when it shouldn't

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10056]
Note: There are 5 issues so far "item does not exist"
#10056 #10057 #10036 #10040 #10068

**Describe the bug**
The "This item does not exist" prompt on new unit appears on unit creation when no issue actually occurs.

**Tell us the version of Spartacus**
- Library version: 3.0-rc.1

**To Reproduce**
1. Create a new unit from the Units menu.
2. Should see the prompt.

**Expected behavior**
The prompt should not appear.

**Screenshots**

![image](https://user-images.githubusercontent.com/11735817/100458507-353f5b80-30c4-11eb-894b-a9c0a4c7c113.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari

**Comment by giancorderoortiz** [comment]
This issue also happens when session times out and attempt to create/edit unit is made. 
https://github.com/SAP/spartacus/issues/10234
