### ISSUE TITLE
grey quantity box in order details sometimes

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10058]
When you first create an order (i was using powertools) and then look at it, the quantity box in entry details is grey. Reload and it's gone.
![image](https://user-images.githubusercontent.com/4998145/100458852-74ed4f80-3092-11eb-9520-0f5f8fb9f46a.png)

**Comment by dydome** [comment]
@Xymmer I tried to repro this issue few times on powertools but without success. May you try it once again by yourself?

**Comment by dydome** [comment]
Closing this ticket as the problem does not exist anymore.
