### ISSUE TITLE
Shipping Method Selection Goes into Infinite Loop

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10069]
**Steps to Reproduce:**

1. Navigate to Spartacus Powertools deployed in CCV2 with RC1. 
2. Navigate as a b2b user. 
3. Add items to cart and proceed to checkout. 
4. In Delivery method page quickly click or double click between options a few times. (Steps here to be refined). 

**Expected Results :**
4. No infinite loop. Delivery method is updated only upon click or double click

**Actual Results:** 
4. Circular check box keeps flicking back and forth between Standard and Premium Delivery in an infinite loop. 
4.a. It's very hard to get out of this loop and proceed with checkout. 

![Screen Shot 2020-11-27 at 11 49 35 AM](https://user-images.githubusercontent.com/46171897/100471405-35c9f900-30a8-11eb-983a-f5d81dda9d20.png)
![Screen Shot 2020-11-27 at 11 50 28 AM](https://user-images.githubusercontent.com/46171897/100471406-35c9f900-30a8-11eb-92c8-63d97a2c9f4e.png)

**Comment by Xymmer** [comment]
to dev: try to repro and if so reliably, investigate a fix. might not block 3.0 release but we'll see.

**Comment by Zeyber** [comment]
https://github.com/SAP/spartacus/commit/9539164d64b3291a2b2f1a315b0620d2e5d9172e
This was the previous fix for the infinite spinner which made another request upon failure but it looks like now the response doesn't contain the flag (success = true) that terminated the subscription and therefore this subscribable is probably what is responsible for continuing the loop.

**Comment by giancorderoortiz** [comment]
Here a little movie with the loop. Using ccv2 RC2. 
[ccv2_rc2_delivery_mode_loop.mov.zip](https://github.com/SAP/spartacus/files/5637862/ccv2_rc2_delivery_mode_loop.mov.zip)

**Comment by giancorderoortiz** [comment]
![ccv2_rc2_loop 2020-12-03 12_37_40](https://user-images.githubusercontent.com/46171897/101066446-6ad0c280-3564-11eb-8035-cca35c2ba541.gif)

**Comment by plabadie** [comment]
For tests, 
- Changing back and forth the delivery mode eventually created an infinite loop.
- The issue can be reproduced quite consistently, but is even easier to reproduce with a "slow 3g" network speed.
- Perform some regression tests about the delivery mode in the checkout since the bug fix required some refactoring of the delivery mode component internals.

**Comment by giancorderoortiz** [comment]
issue fixed 👍
