### ISSUE TITLE
Install Spartacus 3.0 RC1 in CCV2 with 2005 Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10077]
Priority must be given to 2005 given this is the most likely CX version used by Spartacus customers. 
2011 just came out and it will take time before it's rolled out by partners and clients. 

Temporarily, there should be 2 CCV2 environments here: 
1. CCV2 with 2005 (most important) + Spartacus 3.0 RC1. 
2. CCV2 with 2011 + Spartacus 3.0 RC1.

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/7648

**Comment by Xymmer** [comment]
we couldn't get it to work quickly, so we used 2011
