### ISSUE TITLE
Can't see full purchase limit type in the purchase limit form.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10073]
Describe the bug
When creating a purchase limit, the user can't see the full label for the "Type" dropdown list.  
The "Type" label is also not visible in the form after the selection is made.

This is especially a problem if the list has different types that start with the same words.  The user can't tell them apart and doesn't know which one he's selecting.  

**Tell us the version of Spartacus**

test env https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/ (see #10012)

**Steps to reproduce:**

I used Safari on IOS 14.2 / iPhone6s and also Safari on MAC desktop.

* sign in as admin@unitJ.sap 1234
* create a Purchase Limit via Home -> Organization -> Purchase Limits
* Issue: the user can't tell the elements of the "Type" dropdown list because the labels are truncated.

Expected behavior
The use can see the full label of the choices in the dropdown list and in the form after the selection.

**Screenshot:**

![Image from iOS (3)](https://user-images.githubusercontent.com/7065346/100485320-90298080-30cd-11eb-963b-698f1f53b13f.png)
![Image from iOS (2)](https://user-images.githubusercontent.com/7065346/100485321-90c21700-30cd-11eb-9969-e54199b9d8ec.png)

**Comment by Pucek9** [comment]
It's how it looks on Android 8.1 device
![image](https://user-images.githubusercontent.com/8040837/100738510-f405bf00-33d5-11eb-9ebc-a1cf551dd0ef.png)
