### ISSUE TITLE
RC. Validate Functionality and Integration with Gigya

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10080]
Does Spartacus 3.0 RC1 integrates with Gygia?
2005 backend?
2011 backend?

Please provide happy path screenshots for future reference.
Test with CCV2 or Linux Server? TBD

**Comment by Xymmer** [comment]
gigya not officially released and up to them to test for the moment

**Comment by marlass** [comment]
Closing as obsolete ticket
