### ISSUE TITLE
Update Angular Version in Doc. From 9 to 10.

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10087]
Update throughout all documentation. 
Applicable for 3.0. 
2.0 as well?

**Comment by psmul** [comment]
also noticed that SSR documentation with Angular versions is pretty old. Will use this ticket to provide doc update on providing manual steps for SSR.

**Comment by psmul** [comment]
Closing as duplication of:
[#100017](https://github.com/SAP/spartacus/issues/10017)
