### ISSUE TITLE
Add B2B vs B2C Section to Build Libraries Doc Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10083]
Add a new section detailing differences between b2b and b2c here: 
https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries/

**Comment by gladius-mtl** [comment]
I think this is no longer needed. The doc has the following notes regarding b2c and b2b:

- Spartacus does not support B2C and B2B storefronts running together in a single storefront application. If you install Organization - Adminstration or Organization - Order Approval, the B2C storefront will load but it will not work properly.

- If you select a feature that is for B2B storefronts, the schematics automatically add any required B2B configurations if they are missing.
