### ISSUE TITLE
Doc Verification via Actual Installation of Spartacus and Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10094]
Install Spartacus and the backend following the docs after updating them.

Depends on #10082 #10083, #10084, #10085, #10086, #10087, #10088, #10089, #10091, #10090, #10092, #10093, #10007

**Comment by gladius-mtl** [comment]
Anyone can pick up this ticket. There is still a large number of doc reviews to be completed, which only the writer can do.
