### ISSUE TITLE
Input Returned in Response

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10118]
https://github.tools.sap/cx-commerce/spasec/issues/51
Found with 3.0 RC1

**Comment by giancorderoortiz** [comment]
Please refrain from closing this ticket until assessment from architect and internal security expert has been given.

**Comment by Xymmer** [comment]
Not showstopper but let's investigated in the future
We're not sure if related to Spartacus

**Comment by giancorderoortiz** [comment]
confirm this still is happening with 3.3
