### ISSUE TITLE
While create item with existing ID in system, I dont get any error

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#10129]
- form is freezing if we have error #9351
- we dont have backend errors handling for forms - <s>architecture / some other problems, It looks so easy to do but Tobias would like to use local messages instead of global messages #9791</s>
TODO: handle that error in standard interceptor and display in global message
- we dont have frontend validation for already existing ID's - that is possible, needs to fetch list of all items (to get their ids) from backend <s>(decision required)</s>
Decision: Don't touch now
- other #9325

**Comment by Xymmer** [comment]
after this fix, retest #10041 (frozen form if dupe email)

**Comment by Xymmer** [comment]
this is serious enough to require fixing before 3.0
a few other issues were created that are related to this same "no error displayed" message, i closed them as dupes

**Comment by Pucek9** [comment]
Backend errors have no consistancy here for all cases. For the same problem, I'm getting different codes/types:

Cost center create - 400 (bad request) 
```
  {
    "errors" : [ {
      "message" : "[de.hybris.platform.servicelayer.interceptor.impl.UniqueAttributesInterceptor@3e8861b1]:ambiguous unique keys {code=NorthAmericaBurritos} for model B2BCostCenterModel (<unsaved>) - found 1 item(s) using the same keys",
      "type" : "ModelSavingError"
    } ]
  }
```

Cost center edit - 400 (bad request) 
```
{
   "errors" : [ {
      "message" : "[de.hybris.platform.servicelayer.interceptor.impl.UniqueAttributesInterceptor@3e8861b1]:ambiguous unique keys {code=edited-entity-7v2pkgvjf} for model B2BCostCenterModel (8796127242002@35) - found 1 item(s) using the same keys",
      "type" : "ModelSavingError"
   } ]
}
```
Permission create - 400 (bad request) 
```
  {
    "errors" : [ {
      "message" : "Approval Permission with code: test2 already exists.",
      "type" : "DuplicateUidError"
    } ]
  }
```
Permission edit - 400 (bad request)
```
{
   "errors" : [ {
      "message" : "Model saving error.",
      "type" : "ModelSavingError"
   } ]
}
```
Budget create - 409 (conflict)
```
  {
    "errors" : [ {
      "message" : "Budget with code [BurritoPurchases1] already exists",
      "type" : "AlreadyExistsError"
    } ]
  }
```
Budget edit - 400 (bad request)
```
{
   "errors" : [ {
      "message" : "Model saving error.",
      "type" : "ModelSavingError"
   } ]
}
```
User create & edit - 409 (conflict)
```
  {
    "errors" : [ {
      "message" : "User already exists",
      "type" : "AlreadyExistsError"
    } ]
  }
```
User group create & edit - 409 (conflict)
```
  {
    "errors" : [ {
      "message" : "Member Permission with the same id already exists",
      "type" : "AlreadyExistsError"
    } ]
  }
```
Unit create - 409 (conflict)
```
  {
    "errors" : [ {
      "message" : "Organizational unit with uid [TU22] already exists",
      "type" : "AlreadyExistsError"
    } ]
  }
```
Unit edit - 400 (bad request)
```
{
   "errors" : [ {
      "message" : "[de.hybris.platform.servicelayer.interceptor.impl.UniqueAttributesInterceptor@3e8861b1]:ambiguous unique keys {uid=TU} for model B2BUnitModel (8796125986821@15) - found 1 item(s) using the same keys",
      "type" : "ModelSavingError"
   } ]
}
```

**Comment by giancorderoortiz** [comment]
Backend tickets added by @Pucek9 for further review. 
https://cxjira.sap.com/browse/CLC-2371 
https://cxjira.sap.com/browse/CLC-2372 
https://cxjira.sap.com/browse/CLC-2373 
https://cxjira.sap.com/browse/CLC-2374 
https://cxjira.sap.com/browse/CLC-2375

**Comment by giancorderoortiz** [comment]
Related to this C5 issue https://cxjira.sap.com/browse/C5-25. 
For 2005, 2011, I don't see a backend fix that would improve error response message and codes. 
A workaround is needed for now. 
@zebercut @Xymmer fyi further discussion is needed with backend teams in this case.
