### ISSUE TITLE
[Android][Chrome] I must click link (text) to open address details

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#10126]
Device: Doogee S80, Android 8.1, Chrome 86.0.4240.198

When I click on row, I can see class has been changed (row is grey), so I thought that something doesn't work, but when tap on text directly I'm able to see details

It's not consistent with other lists, where it's enough to press on row

**Comment by Matejk00** [comment]
Problem does not exists anymore. Tested on:
Doogee S80, Android 8.1, Chrome 86.0.4240.198
Phone - Samsung Galaxy J3 (2016) | Android 5.1.1 | Chrome 87
Tablet - Samsung Galaxy Tab A10 | Android 10 | Chrome 87
