### ISSUE TITLE
[Android][Chrome] I don't see selected option if typed text previously

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#10127]
Device: Doogee S80, Android 8.1, Chrome 86.0.4240.198

In our forms, e.g Unit/Address -> Country field, when I select item from existing list, it's displayed propely. But when I start typing e.g "Pol" and choose Poland, then select seems as selected for validators, but I can't see selected item. After that every change give the same resutt - select looks like unchosen (but it is)
![image](https://user-images.githubusercontent.com/8040837/103002976-367f6f00-4530-11eb-8173-47b6f205b37c.png)

**Comment by Xymmer** [comment]
could be a problem in all forms

**Comment by Pucek9** [comment]
Re-check after https://github.com/SAP/spartacus/pull/10352

**Comment by Pucek9** [comment]
It seems as ng-select library issue (already resolved -> https://github.com/ng-select/ng-select/issues/1735)
So it's enough to bump this package

**Comment by wangzixi-diablo** [comment]
Test in develop branch first, Samsung C7 Pro Android device, Chrome:

![image](https://user-images.githubusercontent.com/58975336/102992785-da7c1100-4556-11eb-81f5-8da833ae2ea5.png)
![image](https://user-images.githubusercontent.com/58975336/102992791-dfd95b80-4556-11eb-9719-94a1b4a15bd4.png)

**Comment by wangzixi-diablo** [comment]
split view still does not look well when device is rotated to display horizontally:

![image](https://user-images.githubusercontent.com/58975336/102993965-1c0dbb80-4559-11eb-84c3-82423defdc88.png)

**Comment by wangzixi-diablo** [comment]
retest in b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD:

![image](https://user-images.githubusercontent.com/58975336/102995260-a8b97900-455b-11eb-84cd-881cc491f1c3.png)

**Comment by Pucek9** [comment]
before change

  | android 8 |   | android 8.1 |  
-- | -- | -- | -- | --
  | chrome | firefox | chrome | firefox
type and select | v | v | value is not displayed | list not hiding

after change


  | android 8 |   | android 8.1 |  
-- | -- | -- | -- | --
  | chrome | firefox | chrome | firefox
type and select | v | v | v | list not hiding

for list is not hiding on firefox I will create issue direclty on ng-select repo
