### ISSUE TITLE
Create METHOD migration for PageMetaService

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10139]
Create ONLY a method migration for `PageMetaService` (constructor is coming once the feature is supported)

- Method `getMetaResolver` now returns type `Observable<PageMetaResolver> ` instead of `PageMetaResolver`.

**Comment by Xymmer** [comment]
after chatting with Louis, we agreed this could be fixed in next patch, similar to #10136

**Comment by bgambocjaviniar** [comment]
PR: GH-10191

3.0.x PR: GH-10194
