### ISSUE TITLE
Add RoutingParamService to Public API

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10137]
`RoutingParamService` is not part of the public API. Since it is used in `RoutingService` which is exported, `RoutingParamService` should be exported as well. If it is not exported, it makes extending `RoutingService` more difficult.

In doubt as @tobi-or-not-tobi  for opinion.

**Comment by Xymmer** [comment]
after chatting with Louis, it's strongly preferable that this be fixed for 3.0
