### ISSUE TITLE
Add methods migrations for AuthActions

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10136]
`AuthActions` was changes for 3.0 as described in `3_0.md`. Add methods migration for the changes mentioned bellow so that schematics will mark the deprecated usages with ac comment.

```
`AuthActions` now only contains `Login` and `Logout` action class and `LOGIN`, `LOGOUT` variables with action type.
Actions related to client token (`LoadClientToken...`) are now available under `ClientAuthActions` export. 
Constant `LOGOUT_CUSTOMER_SUPPORT_AGENT` is available in `AsmActions` export. 
Actions related to user token were removed (`LOAD_USER_TOKEN`, `LOAD_USER_TOKEN_FAIL`, `LOAD_USER_TOKEN_SUCCESS`, `REFRESH_USER_TOKEN`, `REFRESH_USER_TOKEN_FAIL`, `REFRESH_USER_TOKEN_SUCCESS`, `REVOKE_USER_TOKEN`, `REVOKE_USER_TOKEN_FAIL`, `REVOKE_USER_TOKEN_SUCCESS`, `LoadUserToken`, `LoadUserTokenFail`, `LoadUserTokenSuccess`, `RefreshUserToken`, `RefreshUserTokenSuccess`, `RefreshUserTokenFail`, `RevokeUserToken`, `RevokeUserTokenSuccess` and `RevokeUserTokenFail`).
Instead initialize user token load, refresh or revoke with methods exposed in `AuthService` and `OAuthLibWrapperService`.
```

**Comment by Xymmer** [comment]
after chatting with Louis, we agreed this could be fixed in next patch, similar to #10139

**Comment by LTiger14** [comment]
A migration file exists. The problem in testing might have arose from a wrong setup in the test app.

**Comment by bgambocjaviniar** [comment]
closing as migration was already done, but I did check the following below

1 - test passes
2 - I re-verified what was in the method-deprecation and found that there's nothing unusual from how we tackle *-group.actions.migration.ts files. Can be compared to cms-group.actions.migration.ts
