### ISSUE TITLE
On mobile, the X to close the search filters is beneath the address bar

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10142]
**Describe the bug**
On mobile, the X to close the search filters is beneath the address bar and is difficult to reach.  Users could get stuck.

**Tell us the version of Spartacus**

test env https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (see #10030)

**Steps to reproduce:**

I used Safari on iPhone 6s/ iOS 14.2

* search for a word with like "camera"
* Tap "Filter By"
* Bug: the X to close the search filters is beneath the address bar and is difficult to reach.

Expected behavior
Link to close the filters overlay is not obstructed by the address bar.

**Error screenshot:**

![Image from iOS (4)](https://user-images.githubusercontent.com/7065346/100673031-c286e800-3330-11eb-8e4e-d17ae75e1856.png)

**Comment by giancorderoortiz** [comment]
No longer see issue after fix in Safari iPhone 7, nor chrome mobile breakpoint.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-03 at 8 33 00 AM](https://user-images.githubusercontent.com/46171897/101024604-55e33780-3542-11eb-985e-ae8099bc26f5.png)

**Comment by giancorderoortiz** [comment]
![iphone7-filter](https://user-images.githubusercontent.com/46171897/101026101-77ddb980-3544-11eb-92ab-35ef1548482a.jpg)
