### ISSUE TITLE
Storefinder not Usable on CCV2 (fix ccv2 deployment after rc.2)

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10146]
(Perhaps a misconfiguration issue) 

**Steps to reproduce:** 
1. Navigate to ccv2 Spartacus 3.0 RC1 Electronics storefront
2. On the header, click on Store finder. 

**Expected Results:** 
2. Organized layout. 

**Actual Results:** 
2. Large icons placed, at what it seems, randomly. SAP logo is very large. SLR banner too large as well. 
2.a. Search bar for looking for stores not found. 
2.b. Header is at the bottom, near the footer. 

![Screen Shot 2020-11-30 at 1 14 12 PM](https://user-images.githubusercontent.com/46171897/100730470-15e05100-3398-11eb-8cd4-380c47a1ca32.png)
![Screen Shot 2020-11-30 at 1 14 21 PM](https://user-images.githubusercontent.com/46171897/100730473-1678e780-3398-11eb-9a44-dc273c6560aa.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-01 at 5 48 08 AM](https://user-images.githubusercontent.com/46171897/100731052-e0883300-3398-11eb-8703-517111d21d1c.png)

**Comment by giancorderoortiz** [comment]
Linux dev server RC1 deployment: 
http://spartacus-dev2.eastus.cloudapp.azure.com:4100/electronics-spa/en/USD/store-finder

![Screen Shot 2020-11-30 at 1 23 35 PM](https://user-images.githubusercontent.com/46171897/100731184-0b728700-3399-11eb-895d-ed756bcd00c6.png)

**Comment by Xymmer** [comment]
caused by schematics not adding the right config

this ticket: update ccv2 so we can check storefinder
create a new ticket: fix the schematics

**Comment by LTiger14** [comment]
After some research we don't have to update schematics. 

Simply running `ng add @spartacus/misc` will let you add the required modules and configurations for Storefinder. This will be documented.

**Comment by LTiger14** [comment]
Store-finder is now on ccv2. Please re-test.

**Comment by giancorderoortiz** [comment]
Working now. 

![Screen Shot 2020-12-03 at 7 54 22 AM](https://user-images.githubusercontent.com/46171897/101020839-1534ef80-353d-11eb-8a40-9b0158a068e5.png)
![Screen Shot 2020-12-03 at 7 54 02 AM](https://user-images.githubusercontent.com/46171897/101020858-1a923a00-353d-11eb-88a3-91dda695f22c.png)

**Comment by giancorderoortiz** [comment]
B2B store: 
![Screen Shot 2020-12-03 at 7 55 54 AM](https://user-images.githubusercontent.com/46171897/101020927-2f6ecd80-353d-11eb-8bbf-a8ba481c1481.png)
