### ISSUE TITLE
Negative Order Balances. iPad. No Session Timeout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10145]
Hardware: 
iPad Pro. 12.3.1. 
Browser: Safari

**Steps to Reproduce:** 
1. Using iPad Pro, open safari and navigate to ccv2 Spartacus 3.0 RC1 Electronics storefront. 
2. Login. 
3. Add items to cart. 
4. Stop any operations on the storefront for 10 minutes +. 
5. Return to ccv2 Spartacus electronics storefront. 
6. Complete checkout. 
7. Wait one minute. 
8. Visit Order History and see the order history details for the purchase completed in Step 6. 

**Expected Results:** 
8.a. Final balance is greater than 0. 
8.b. Order is either 'In Progress' or 'Completed' status.  

**Actual Results:** 
8.a Balance is less than 0. Amount similar to that of discount offered. 
8.b. 'Order is cancelled'

What was noticed was that the session is left in some sort of limbo state. 
It's urgent to attempt to reproduce with other mobile devices and browsers.

**Comment by giancorderoortiz** [comment]
![negative-balance1](https://user-images.githubusercontent.com/46171897/100731640-a4090700-3399-11eb-91da-2052b1f1e9ab.png)
![negative-balance2](https://user-images.githubusercontent.com/46171897/100731642-a4a19d80-3399-11eb-988b-643b60786fd4.png)
![negativebalance3](https://user-images.githubusercontent.com/46171897/100731645-a53a3400-3399-11eb-80ff-71449fe402c9.png)

**Comment by giancorderoortiz** [comment]
![cancelledOrder](https://user-images.githubusercontent.com/46171897/100735369-192b0b00-339f-11eb-9a20-e41cf8d89baa.png)

**Comment by Xymmer** [comment]
negative value related to promotions is a known issue related to backend
why the order was cancelled following this procedure is a good question

**Comment by Xymmer** [comment]
Let's try to repro the cancelled order problem, then talk to Stingrays about what could have happened, is it Spartacus, backend, both? i.e. how was GC able to "create" an order that was cancelled right away?

**Comment by plabadie** [comment]
Unable to repro using CCV2 instance.  Attempted to repro using:
* Safari on Mac
* Safari in iPad mini ios 14
* Safari on iPhone 6 ios 12

**Comment by giancorderoortiz** [comment]
Unable to reproduce. 
Closing for now. 
Will check with final RC
