### ISSUE TITLE
In smartedit: Page is not auto-rendered after making a component visible

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#10153]
steps to test:
1. in smartedit, go to homepage of any spa sites. Edit a component to make it invisible. The page is auto-rendered, so you should be able to see the component is gone.
2. In the same slot, make this component visible again.
![Screen Shot 2020-12-01 at 8 47 48 AM](https://user-images.githubusercontent.com/44440575/100749564-d1ae7a00-33b2-11eb-8749-e003726923e9.png)

The result is, the page is not auto-rendered. So the component is not displayed again.

The expected result is component can be displayed after page auto-rendered.

**Comment by WeizhengSap** [comment]
It needs investigation to see whether this issue is caused by SPA or smartedit.

**Comment by Xymmer** [comment]
spike the issue if it's backend related, let bill know; otherwise fix if possible

**Comment by bgambocjaviniar** [comment]
PR: GH-10962

use dev2

pre-req:
- change data-smartedit-allow-origin value to spartacus-dev2.eastus.cloudapp.azure.com:9002
- start app in ssl `yarn start --ssl` 


QA:
- go to /smartedit from https://spartacus-dev2.eastus.cloudapp.azure.com:9002/smartedit
- choose SPA apparel or electronics (any is fine)
- using basic edit or advanced, change the visibility of a cms component in a slot as shown in https://github.com/SAP/spartacus/issues/10153#issue-754414755

Note:
When changing the visibility to `ON/OFF`, there's a slight delay before the image shows up/hides

**Comment by bgambocjaviniar** [comment]
closing as the fix was included in the initiative of moving smartedit into it's own feature-lib
https://github.com/SAP/spartacus/issues/10570
