### ISSUE TITLE
Page not found on refresh after changing language or currency 

### ISSUE THREAD

**Issue by Parthlakhani** [SAP/spartacus#10157]
**Describe the bug**
Refreshing after changing currency or language leads to the page not found error

**Tell us the version of Spartacus**
test env - https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ 
check #10030 

**Steps to reproduce the behavior:**
1. Change the currency or language
2. Hit refresh
3. Bug: Page not found

**Expected behavior**
Page reloads with the same content without any error.

**Screenshots**
![Screen Shot 2020-12-01 at 11 07 06 AM](https://user-images.githubusercontent.com/72991814/100767052-4ee3ea00-33c7-11eb-827d-f493c67ab5ee.png)

The issue was found while testing on iPad mini using Xcode simulator, but the same behavior is observed on the desktop also.

**Additional context**
The issue is with the regeneration of URL on refresh, as `en/USD/` is added after URL instead of replacing whenever currency/language is changed or page is reloaded

**Original URL**: https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
**URL after changing the language**: https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/zh/USD/zh/USD/
**URL after refreshing the page**: https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/zh/USD/zh/USD

**Comment by Xymmer** [comment]
try to repro, if you can, let's fix

**Comment by dunqan** [comment]
Looks like deployment misconfiguration.

It should be either automatic multisite configuration mechanism used (so baseSites and configuration should be guessed from the route via backend configuration) or we should configure all available languages.

The deployed spartacus has only one language configured ('en'), so any route starting with zh/... is interpretted as a content page (thus fallbacking to en/USD + /zh/... as a content page)

```
                    context: {
                        urlParameters: ["baseSite", "language", "currency"],
                        baseSite: ["electronics-spa", "apparel-uk-spa"],
                        language: ["en"],
                        currency: ["USD", "GBP"]
                    },
```

**Comment by Platonn** [comment]
I can confirm what @dunqan said. Here's the `main.js` of the test environment https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ :
![obraz](https://user-images.githubusercontent.com/4001059/100874855-790bd980-34a5-11eb-8548-b2383a3426f3.png)

**Comment by giancorderoortiz** [comment]
Able to reproduce with iPad pro as well

**Comment by Platonn** [comment]
Closed ticket, because it was a deployment misconfiguration, not the actual bug.

**Comment by giancorderoortiz** [comment]
To retest with RC2. Actually important the use case described here works.

**Comment by giancorderoortiz** [comment]
This issue continues to be broken with RC2. 
If config issue, please fix and redeploy. 
URL after language change from EN to DE and reload : electronics-spa/en/USD/de/USD/de/USD

**Comment by giancorderoortiz** [comment]
Testing with RC2 in Linux server dev2 actually works. However, I cannot validate in mobile devices. 
http://spartacus-dev2.eastus.cloudapp.azure.com:4100/electronics-spa/en/USD/
URL after language change from EN to DE and reload: electronics-spa/de/USD/

**Comment by giancorderoortiz** [comment]
Able to verify in CCV2 in mobile. This works.
