### ISSUE TITLE
Feature: Display price range for products containing bulk pricing on product search page.

### ISSUE THREAD

**Issue by ren-tham** [SAP/spartacus#10163]
**Is your feature request related to a problem? Please describe.**
Please read (#10158)

**Describe the solution you'd like**
When searching for products, if an item contains different bulk prices, the search result should display that product's lowest and highest price.

**Additional context**
<ins>API investigation: </ins> https://cxwiki.sap.com/display/spar/Bulk+pricing+-+OCC+testing
The following link indicates where to retrieve bulk pricing information for specific products.

<ins>Expected look and feel: </ins>

<img width="233" alt="bulk-search" src="https://user-images.githubusercontent.com/71661414/100776586-b81d2a80-33d2-11eb-9c3c-a9e4546858cf.PNG">

**Comment by Xymmer** [comment]
closed as we have https://jira.tools.sap/browse/CXSPA-316 now
