### ISSUE TITLE
Using same password while changing the password should show error

### ISSUE THREAD

**Issue by Parthlakhani** [SAP/spartacus#10169]
**Describe the bug**
While changing the password, even if we use the same password there is no error message.

**Tell us the version of Spartacus**
- Issue was found while testing on https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (for #10030) but the same issue is there in 2.x

**To Reproduce**
1. Go to change password
2. try changing the password with the existing password only
3. Bug: Password is updated successfully without any error message

**Expected behavior**
Should display error message saying something like `Can not use the same password`

**Comment by Xymmer** [comment]
there's no business logic to know what previous password is, so we don't detect it. it's as designed
