### ISSUE TITLE
Using already registered email ID does not throw any error

### ISSUE THREAD

**Issue by Parthlakhani** [SAP/spartacus#10164]
**Describe the bug**
Registering with the same email ID multiple time works, instead of throwing an error

**Version of Spartacus**
- Issue was found while testing on https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (for #10030) but same issue is there in 2.x

**To Reproduce**
1. Register the new user
2. Register again using the same email ID with a different password
3. Bug: There should be an error for using the same email ID again

**Expected behavior**
An error message on click of `Register` saying something like `Account already exists with provided email ID`

**Additional context**
After registering for the second time, the user can log in with the old password only.

**Comment by Xymmer** [comment]
dupe of existing ticket where we don't display an error in this scenario
