### ISSUE TITLE
Minor styling issue on Shipping address list view

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10171]
**Describe the bug**
Minor styling issue with padding on Shipping address list view. Only happens in tablet view. Can be replicated using chrome dev tools.

**Tell us the version of Spartacus**
- Library version: 3.0-RC1 #10012

**To Reproduce**
1. My Company Home > Units > Any existing unit with Shipping Addresses > Shipping Address
2. Observe the layout issue 

**Expected behavior**
List item should have proper padding around all sides

**Screenshots**
![Simulator Screen Shot - iPad Pro (9 7-inch) - 2020-11-30 at 11 51 06](https://user-images.githubusercontent.com/15215400/100793504-d179a300-33e1-11eb-9a7d-fead8a628d98.png)

**Desktop (please complete the following information):**
 - OS: iOS on iPad Mini using Xcode simulation
 - Browser Sarafi
 - Version latest 
Can also be replicated using chrome dev tools

**Comment by tobi-or-not-tobi** [comment]
Duplicates #10045 and #10071

**Comment by giancorderoortiz** [comment]
Was also happening on mobile breakpoint
![Screen Shot 2020-12-08 at 5 24 17 AM](https://user-images.githubusercontent.com/46171897/101471773-b0e7a680-3915-11eb-9424-1c054c04b8c1.png)

**Comment by giancorderoortiz** [comment]
Issue is fixed. Tested with develop branch Dec 7, 2020. 

![Screen Shot 2020-12-08 at 5 26 40 AM](https://user-images.githubusercontent.com/46171897/101472096-1d62a580-3916-11eb-8961-3e2b3482a115.png)
![Screen Shot 2020-12-08 at 5 27 13 AM](https://user-images.githubusercontent.com/46171897/101472099-1dfb3c00-3916-11eb-8c84-cccc589763da.png)
