### ISSUE TITLE
Missing fields in the response when no translated

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10192]
So far found in:
- cost center list `/occ/v2/powertools-spa/costcentersall` (`name`, `unit`)
- budgets `/occ/v2/powertools-spa/users/current/budgets` (`name`, `unit.name`)
- users `/occ/v2/powertools-spa/users/current/orgCustomers` (`orgUnit.name`)
- user groups `/occ/v2/powertools-spa/users/current/orgUnitUserGroups` (`orgUnit.name`)
- purchase limits `/occ/v2/powertools-spa/users/current/orderApprovalPermissions` (`orgUnit.name`)

related to #10076

**Comment by Xymmer** [comment]
wei will update sample data as workaround
wei will create CLC ticket to fix in backend for future

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/153

After build and initialize the system, you should be able to see, e.g. costCenter name, in other language:
![Screen Shot 2020-12-03 at 8 39 34 AM](https://user-images.githubusercontent.com/44440575/101034978-a067b280-3548-11eb-8c1d-9b83152ebc75.png)

**Comment by WeizhengSap** [comment]
Ticket `CLC-2364` was created.

**Comment by bgambocjaviniar** [comment]
All works as shown in the screenshot below 

<img width="1176" alt="1costcen" src="https://user-images.githubusercontent.com/29099466/101817671-b5b48200-3af0-11eb-81c3-032c93991729.png">
<img width="1177" alt="2budg" src="https://user-images.githubusercontent.com/29099466/101817673-b6e5af00-3af0-11eb-9221-c22966372b70.png">
<img width="1229" alt="3use" src="https://user-images.githubusercontent.com/29099466/101817677-b77e4580-3af0-11eb-9944-18be67911ad0.png">
<img width="1298" alt="4usergroups" src="https://user-images.githubusercontent.com/29099466/101817678-b816dc00-3af0-11eb-98ae-7eb3bf44314c.png">
<img width="1301" alt="5perm" src="https://user-images.githubusercontent.com/29099466/101817680-b8af7280-3af0-11eb-9aff-bb1a738058b5.png">
