### ISSUE TITLE
Customer Support Ticket

### ISSUE THREAD

**Issue by fernandadasneves** [SAP/spartacus#10200]
I cannot see in code or in the road map nothing about the Support Ticket functionality.
Can you please advise how Spartacus works when a customer wants to open a ticket to Customer Service Module?

Version: Spartacus 3.0.0-next.6

Desktop:

OS: Windows
Browser: Chrome, Edge
Version: last version

Smartphone:

Device: Android / IOS actual versions
OS: Actual Version
Browser chrome / safari
Version Actual versions

**Comment by fernandadasneves** [comment]
Hello,

Any answer?

thank you

**Comment by fernandadasneves** [comment]
Hello,

Any answer?

thank you

**Comment by Xymmer** [comment]
hey @fernandadasneves, that's more of a roadmap question... all Accelerator features are on our long-term roadmap, but this one doesn't have a specific quarter yet. The APIs must be added for the functionality that exists first. Keep an eye on https://roadmaps.sap.com/board?q=sap%20commerce%20cloud&range=CURRENT-LAST#Q4%202020
