### ISSUE TITLE
[hold until fix implemented] Test Spartacus ssr deployment without workaround and update doc

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10205]
We wrote this ssr workaround for deployment to cloud: https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/

The deployment service has since been updated to handle SSR with Angular 9 and later, so this workaround shouldn't be necessary.

 - [ ] 1. Deploy SSR-enabled Spartacus to an environment without doing the manual steps, and see if it works
 - [ ] 2. Update the doc:
    - so it says "2.0 and later"
    - that "the workaround is no longer required starting December 2020, as long as your deployment is using the updated application defintion."

For the second doc point, consult with Yi Ji about how to word that. Everyone is supposed to get the appdef automatically but sometimes they purposely might not.

You can use team spartacus environment.

When updating the workaround doc, update v2 and v3 of the documentation.

**Comment by LTiger14** [comment]
The fix is not released yet. To retry after MT2012 is out.
