### ISSUE TITLE
RC2. B2B. No Redirection to Login After Attempt to Disable User and Session Timeout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10235]
**Steps to Reproduce:**

1. Setup 2005 backend. (any patch would do). Set session validity to 2 minutes. (120 secs)
2. Deploy Spartacus 3.0 RC2 and enable b2b libraries.
3. Navigate to powertools page.
4. Login as admin (i.e. linda.wolf).
5. Navigate to organization page
6. Select users. 
7. Click on any user and attempt to disable, but do not confirm. 
8. Wait session validity + 1 minute (that means do not touch the computer or move the mouse -> go get coffee)
9. Confirm disabling user. 

**Expected Results:** 
9. Session has timed out.
9.a. User is redirected to login
9.b. After admin login, user is redirected to users page he/she was previously editing.
9.c. All relevant user data is loaded.

**Actual Results:** 
9. Error message indicating session has expired is displayed. 
9.a Clicking around page produces no action. Page seems stale. 
9.b. Eventually a login page is shown. 
9.c. After successful login, similar behaviour is seen as in #10234

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-04 at 5 10 37 PM](https://user-images.githubusercontent.com/46171897/101220760-3fc59c00-3654-11eb-9380-7bae1e25db5c.png)
![Screen Shot 2020-12-04 at 5 11 17 PM](https://user-images.githubusercontent.com/46171897/101220761-3fc59c00-3654-11eb-9b5f-fb3ecc612980.png)

**Comment by Xymmer** [comment]
Might be partially fixed by #9790, retest

**Comment by giancorderoortiz** [comment]
It appears to be fixed. 
Further testing will be done here: http://cx-qa16181492.eastus.cloudapp.azure.com:4202/powertools-spa/en/USD
(latest develop branch on Dec 7, 2020)

**Comment by giancorderoortiz** [comment]
Retest trials. 9 out 10 I see expected results here. 
1 time, I get stale elements in page and there is no redirection. Nevertheless after re-login, the page does load appropriately so the final end effect to the user is not completely negative. 

Will close this ticket for now. 

@hackergil, @dunqan please make sure this fix is in 3.0 RC3.
