### ISSUE TITLE
Enable/Disable E2E test for my company is broken

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10231]
Enable/Disable E2E Test for my company entities has broken and should be fixed.

![image](https://user-images.githubusercontent.com/11735817/101175087-05083780-3645-11eb-91d8-cfbd61a287c4.png)

Also
- should avoid ignoring case sensitivity for hard coded translations
- other my-company e2e tests should be adapted to new translations

**Comment by Platonn** [comment]
May be related to https://github.com/SAP/spartacus/issues/10263 ?

**Comment by giancorderoortiz** [comment]
b2b e2e run : 
smoke: https://dashboard.cypress.io/projects/k3nmep/runs/7490

b2b all: https://dashboard.cypress.io/projects/k3nmep/runs/7491

frontend: localhost (mac OS)
backend: dev0. 
Develop branch Dec 8, 10 am EST.
