### ISSUE TITLE
RC2. B2B. Unable to Reload Unit Data After Session Timeout and Re-login

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10234]
**Steps to Reproduce:** 

1. Setup 2005 backend. (any patch would do). Set session validity to 2 minutes. (120 secs)
2. Deploy Spartacus 3.0 RC2 and enable b2b libraries. 
3. Navigate to powertools page. 
4. Login as admin (i.e. linda.wolf). 
5. Navigate to organization page
6. Navigate to Units. 
7. Edit any unit, but do not save changes. 
8. Wait session validity + 1 minute (that means do not touch the computer or move the mouse -> go get coffee)
9. Save changes to unit. 

**Expected Results:** 
9. Session has timed out. 
9.a. User is redirected to login
9.b. After admin login, user is redirected to unit page he/she was previously editing. 
9.c. All relevant unit data is loaded. 

**Actual Results:** 
9. Session has timed out. 
9.a. User is redirected to login
9.b. After admin login, user is redirected to unit page he/she was previously editing. 
9.c. All relevant unit data is not  loaded. Page unit data is empty.  👎

**Comment by giancorderoortiz** [comment]
This server can be used for testing: 
http://spartacus-dev2.eastus.cloudapp.azure.com:4200/powertools-spa/en/USD
Has 3.0 RC2 deployed.
Backend is 2005.2, session timeout set to 2 minutes (120 secs)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-04 at 12 58 32 PM](https://user-images.githubusercontent.com/46171897/101218931-f3795c80-3651-11eb-9665-798cc5a8ea47.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-04 at 4 58 59 PM](https://user-images.githubusercontent.com/46171897/101219449-1c015680-3652-11eb-8d12-32ab5d6c42f5.png)
![Screen Shot 2020-12-04 at 4 59 27 PM](https://user-images.githubusercontent.com/46171897/101219456-1c99ed00-3652-11eb-9f1c-87149e539851.png)

**Comment by giancorderoortiz** [comment]
Also applies to users: 
![Screen Shot 2020-12-04 at 12 58 32 PM](https://user-images.githubusercontent.com/46171897/101219551-31768080-3652-11eb-86a7-903fd7f9426b.png)

**Comment by giancorderoortiz** [comment]
Somewhat different error condition found upon session timeout in https://github.com/SAP/spartacus/issues/10235

**Comment by Xymmer** [comment]
Might be partially fixed by #9790, retest

**Comment by giancorderoortiz** [comment]
It appears to be fixed.
Further testing will be done here: http://cx-qa16181492.eastus.cloudapp.azure.com:4202/powertools-spa/en/USD
(latest develop branch on Dec 7, 2020)

**Comment by giancorderoortiz** [comment]
This issue is now fixed. 
@hackergil, @dunqan please make sure this fix is in 3.0 RC3.
