### ISSUE TITLE
Events - UI events

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10245]
The UI events usually refer to the DOM UI events such as:
 - mouse click
 - keyboard "key up"
 - interaction event (includes both mouse click and keyboard "key up" events)

The payload for these kind events highly depends on its type. But in most cases, the most useful payload for customers could be the Spartacus (CMS) component information, e.g. `UID`, component name, etc.

The UI events are useful for various analytical tools, namely TMS (e.g. GTM, Adobe tag manager, etc.).
They also provide more context about the end users' behaviour and usage of Spartacus.

**Comment by tobi-or-not-tobi** [comment]
We could also consider keyboard users as well.

**Comment by znikola** [comment]
Closing as it was a parent ticket
