### ISSUE TITLE
ASM: customerId might be empty for some users on emulation

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10244]
There might be the case that user doesn't have `customerId`. In such case we should show appropriate error and abort emulation process.

**Comment by marlass** [comment]
Based on: https://stackoverflow.com/questions/65125866/assisted-service-module-not-running-in-spartacus-b2b-with-sap-commerce-cloud-200/65139689?noredirect=1#comment115226761_65139689

**Comment by psmul** [comment]
QA steps:
- start ASM session for properly set agent
- create/find customer with empty customerId field in backoffice
- try to start session with above customer

Expected result:
- global message error should appear informing about lack of customerId
- session shouldn't start

**Comment by dydome** [comment]
Tested with custom with and without customerId. It works as intended.
