### ISSUE TITLE
[Ignore these files] SonarC. Low Security Rating. New Code. No Tests

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10248]
This issue affects our Security Rating in SonarCloud. It's visible to CX. 
Our Security vulnerability rating is A, which is great. 
However, we have 7 security hotspots that require attention. This yields a rating of "E" for security hotspots. 
(Almost a failed letter grade 'F')

The issue here seems easy to fix. 
New code in the following files do not have tests. 
Please address by actually providing tests (if feaseable), or by causing Sonar to bypass scanning these translation files. 

Files affected: 

- projects/assets/src/translations/en/common.ts
- projects/assets/src/translations/en/my-account.ts
- feature-libs/organization/administration/assets/translations/en/user.i18n.ts
- projects/assets/src/translations/en/user.ts

URL: 
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=security_review_rating&view=list

Individual Links: 
[users.ts](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=security_review_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fassets%2Fsrc%2Ftranslations%2Fen%2Fuser.ts)

[common.ts](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=security_review_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fassets%2Fsrc%2Ftranslations%2Fen%2Fcommon.ts)

[my-account.ts](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=security_review_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fassets%2Fsrc%2Ftranslations%2Fen%2Fmy-account.ts)

[user.l18n.ts](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=security_review_rating&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Forganization%2Fadministration%2Fassets%2Ftranslations%2Fen%2Fuser.i18n.ts)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-07 at 7 44 56 AM](https://user-images.githubusercontent.com/46171897/101353276-4e34d300-3861-11eb-820f-cd68f8e4622d.png)
![Screen Shot 2020-12-07 at 7 51 45 AM](https://user-images.githubusercontent.com/46171897/101353279-4ecd6980-3861-11eb-859e-ee645c744d9e.png)
![Screen Shot 2020-12-07 at 7 53 09 AM](https://user-images.githubusercontent.com/46171897/101353281-4ecd6980-3861-11eb-93b3-78559ef36d6c.png)

**Comment by Xymmer** [comment]
false positive, turn off sonar validation of translation files
add translations regex to exclude list of sonarcloud?
also see #10277

**Comment by giancorderoortiz** [comment]
Confirm if issue still appears in SonarC

**Comment by giancorderoortiz** [comment]
Out of scope for now.
