### ISSUE TITLE
fix b2b-replenishment-checkout-flow.e2e-spec.ts for accessibility

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#10240]
Adjust the newly added tabbing accessibility with the replenishment checkout e2e. 

- under the `reviewB2bReviewOrderPage` function for `verifyTabbingOrder` of b2b-checkout.ts, we need to have another config for when it is replenishment as there are more elements when the radiobox is checked for it

<img width="493" alt="Screen Shot 2020-12-07 at 4 13 47 AM" src="https://user-images.githubusercontent.com/29099466/101332151-ebccda00-3842-11eb-9ab8-fba185a61bf0.png">

**Comment by LTiger14** [comment]
Handled in #10264

**Comment by bgambocjaviniar** [comment]
closing because it's handled with above
