### ISSUE TITLE
skip new b2b tests until they pass

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10271]
In https://github.com/SAP/spartacus/pull/10249 we've enabled all b2b regression tests in the Jenkins regression pipeline. But [some of them were broken](https://dashboard.cypress.io/projects/k3nmep/runs/7452/test-results?browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D). So to bring back the Jenkins pipeline to green, we need to temporarily skip the tests which are not working and fix them in the following tickets with 3.0 milestone:
  -  https://github.com/SAP/spartacus/issues/10263
  -  https://github.com/SAP/spartacus/issues/10264

**Comment by giancorderoortiz** [comment]
@hackergil fyi
