### ISSUE TITLE
[Ignore files] SonarC. Reliability Rating. Use forEach Instead of Map. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10277]
This issue affects our overall Reliability Rating in Sonar Cloud.
Visible to CX.

Reliability Rating:
C

Link
[storefinder/test.ts](https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Fstorefinder%2Ftest.ts)

Files: 
feature-libs/storefinder/test.ts

Issue:
Consider using "forEach" instead of "map" as its return value is not being used here.  (line 35)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-08 at 4 13 33 PM](https://user-images.githubusercontent.com/46171897/101542155-5fb8d080-3970-11eb-8e04-5c0eb5217b16.png)

**Comment by Xymmer** [comment]
set this file to ignore (there are other tickets to also ignore test files #10248, maybe there's a regex expression that's used?)
also possibly this test is not named properly for our current system to ignore it? pls check
