### ISSUE TITLE
Migration schematics for moving features to different libraries

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#10287]
It would be good to automate migrations for all symbols that were moved to different libraries, i.e. update customer's code by fixing old imports to new ones.

We already have some logic for migrating storefinder import from `@spartacus/storefrontlib` to `@spartcus/storefinder`, it might be a good start to take a look at this code and come up with some general, configuration driven schematics that will work with any feature.

**Comment by marlass** [comment]
Related to #10770

This one will need additionally migration that will install the missing libraries (not only rename symbol mechanism migration)

**Comment by marlass** [comment]
One thing missing in this PR from the original vision:

- migration that will be run after all other migrations

Migration behavior:

- configure migration with (library name and comment)
- migration will look through all customer files and will look for import statements from the passed library name (eg. for checkout any import starting with "@spartacus/checkout")
- when the import is found we log the message in console (example message: “We found imports from @spartacus/asm library which is not installed. If you are using the ASM feature you can install it by running ng add @spartacus/asm. If you only need to reference some types/const and don’t use the feature you can add it like regular npm package npm i @spartacus/asm. If you are not using ASM library check why you have imports from this library.”)
