### ISSUE TITLE
[epic] Introduce Checkout feature library

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#10286]
As part of the initiative to move features in separate and optional libraries, we like to move Checkout out of the core and component library. As a result, the Checkout feature should be optional, lazily loaded (code split).

Ideally, we introduce this change as an optional change during a minor release, but there's a change that we can only do this with breaking changes.

**Comment by LTiger14** [comment]
I created this sub ticket for creating the library in case the person working on this issue wants to use it #10596. (You can delete it if you don't want it)
