### ISSUE TITLE
Create login event

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#10295]
This task is part of the behavioural events feature - #10294

# Event

This event should fire whenever the user logs in.
Make sure to test does the event fire in the following case:

- a user logs in --> the event should fire here
- the user logs out
- the user logs in again, in the same browser session (there was no refresh)  --> the event should fire again here

An example of how this can implemented can be found in `integration-libs/cds/src/profiletag/services/profile-tag-lifecycle.service.ts`' `loginSuccessful()` method.
There's also a very nice test in `integration-libs/cds/src/profiletag/services/profile-tag-lifecycle.service.spec.ts`

The event should be added to the _core_ lib.

## Payload

The payload should be empty.

**Comment by janwidmer** [comment]
Hey @znikola,

I was also missing the Login event and made it work by subscribing to the `AuthService` `isUserLoggedIn` method.. of course, an event would be nicer.. :-)
