### ISSUE TITLE
Add mapping for languages and locales to improve support for country specific languages

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#10306]
**Is your feature request related to a problem? Please describe.**
Currently, to support country specific locales like `en-GB` or `de-CH`, it's required to define the languages exactly like this. As a consequence, the language also get's written to the URL like this, if the language url mapping is active.

**Describe the solution you'd like**
I would like to be able to keep the two letter language code in the url, e.g. `example.ch/my-site/de/CHF`, but as locale to format the dates / currencies, I would like to use the locale `de-CH`.

As our site only runs for Swiss customers, I don't like to have my URL showing like this `example.ch/my-site/de-CH/CHF` because it's showing redundant information.

This could be done by extending the i18n config with a mapping of languages and locale values and as fallback, if no mapping is available, just use the language as locale directly. 

**Describe alternatives you've considered**
As long as there is no option to add a mapping, I will probably have to write a service which takes the language and programmatically set's the corresponding locale

**Comment by Platonn** [comment]
@janwidmer you can achieve your goal by introducing a new custom site context, however you call it, just for now let's call it `country`. Basically your `country` will be mapped 1:1 from `langauge` and vice versa.
Here's a step-by-step instruction how to add a custom site context that derives from `langauge`: https://sap.github.io/spartacus-docs/automatic-context-configuration/#how-to-add-custom-context . You'll just need to define your custom mapping.

Then you can configure Spartacus to display `country` instead of `langauge` in the URL (configure `context.urlParameters` to `['country', 'currency']`).

At the same time you keep using precise locale as the `langauge` site context (so the precise locale it used to format dates and currencies, as well as to translate static i18n labels).

**Comment by janwidmer** [comment]
@Platonn thanks for that, good idea, will try it

**Comment by janwidmer** [comment]
@Platonn I tried your suggestion and it kinda works. The new "customLanguage" parameter get's appended to the end of the url correctly.
![Custom Parameter](https://user-images.githubusercontent.com/3381820/105335912-e94af780-5bd8-11eb-883b-af97436cdbbd.jpg)

There is a weird behaviour though:
When I am on one language and then switch to another language site via language selectorr, the custom parameter get's appended to the url a second time: `http://localhost:4200/my-site/de_CH/CHF/de/de/`

When I then do a full page reload, the custom parameter get's appended even a third time: `http://localhost:4200/my-site/de_CH/CHF/de/de/de/` (For every reload, it get's appended one more, as of spartacus would not see, that the custom parameter is already present in the url)

Do you have any idea, what could be the problem? I followed the tutorial here https://sap.github.io/spartacus-docs/automatic-context-configuration/#how-to-add-custom-context including adjusting the parameters in the backoffice..

**Comment by janwidmer** [comment]
@Platonn I also tried it with the exact code from the Spartacus Docs and get the same behaviour (just wanted to make sure, I did not screw something up in my code..)

**Comment by Platonn** [comment]
@janwidmer Redirecting suggests me that Spartacus perceives the value of custom context in URL as invalid. So it seems like there is missing the configuration array with all possible correct values of your context. For example:
```ts
context: {
  /* ... */
  custom: ['EN', 'DE', 'JA', 'ZH']
}
```

If you're using automatic mutli-site configuration, you need to pupulate Spartacus config with an array of possible values dyamically -> Can you double check please that you implemented correctly `CustomOccConfigLoaderService` (**using the name of your context**, i.e. `country`, but not `custom`):
```ts
 @Injectable()
 export class CustomOccConfigLoaderService extends OccConfigLoaderService {
   protected getConfigChunks(
     externalConfig: OccLoadedConfig
   ): (I18nConfig | SiteContextConfig)[] {
     const chunks = super.getConfigChunks(externalConfig);
     const contextConfig = (chunks[0] as SiteContextConfig).context;
     
     //  ************************************************************************
     // HERE ------vvvvvv
     contextConfig.custom = contextConfig[LANGUAGE_CONTEXT_ID].map(
       languageToCustom
     );
     //  ************************************************************************
     return chunks;
   }
 }
 ```
 
 AND

that you provide it in your app module:

```ts
@NgModule({
  /* ... */
  providers: [
    {
      provide: ContextServiceMap,
      useFactory: serviceMapFactory,
    },
    {
      provide: OccConfigLoaderService,
      useClass: CustomOccConfigLoaderService, // <---------------------- your custom loader 
    },
  ],
```
?

**Comment by janwidmer** [comment]
@Platonn thanks for the inputs, the custom parameter within the context was missing:
```
context: {
  /* ... */
  custom: ['EN', 'DE', 'JA', 'ZH']
}
```
Adding that now makes it working correctly.

Maybe the tutorial here https://sap.github.io/spartacus-docs/automatic-context-configuration/ could be extended to also contain the above snippet to make it more clear?

**Comment by Platonn** [comment]
@janwidmer thanks for suggestion. Added to https://sap.github.io/spartacus-docs/automatic-context-configuration/#static-context-configuration
