### ISSUE TITLE
Introduce Qualtrics feature library

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#10309]
As part of the initiative to move features in separate and optional libraries, we like to move Qualtrics out of the core and component library. As a result, the Qualtrics feature should be optional, lazily loaded (code split).

Ideally we introduce this change as an optional change during a minor release, but there's a change that we can only do this with breaking changes.

**Comment by bgambocjaviniar** [comment]
As discussed, the new qualtrics component will be put in its own feature-lib, but the OLD core/lib of qualtrics in Spartacus will stay where it is currently situated in until we have a proper mechanism to handle breaking change.

**Comment by bgambocjaviniar** [comment]
sample data pr: https://github.tools.sap/cx-commerce/spartacussampledata/pull/157
pr: GH-10578

- contains deprecation comment in storefrontlib and moved the old qualtrics component to the newly created feature-lib. 

QA: 

- verify feature-lib works as intended. Ex: ng build qualtrics, yarn build:libs, etc
- make sure you can see the qualtrics embedded feedback component in the product details page which is under the `ProductSummarySlot` between `ProductIntroComponent` and `ProductSummaryComponent`. NOTE: the functionality of the component is not implemented in Spartacus, but in Qualtrics.
- make sure when adding changes to the qualtrics embedded feedback component scss that it applies the proper styling to the component's selector

**NOTE** the qualtrics embedded feedback component in the qualtrics tenant is only visible when the contains `Gigashot`, so qualtrics will render things to that component in the plp page of product id 1432722 (Gigashot K80H)

More information on why we needed to create this new qualtrics embedded feedback component https://github.com/SAP/spartacus/issues/9873#issue-745652738
