### ISSUE TITLE
B2B e2e don't run in the pipeline when B2C e2e fail

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10303]
Since https://github.com/SAP/spartacus/pull/10249 was merged, we run sequentially:
`cypress run (... b2c)`
and then
`cypress run (...b2b)`.
(it's becuase b2b tests need a different app start with a flag B2B=true).

Therefore when the first `cypress run (... b2c)` fails (i.e due to some flaky test), it exists with code `1` and the pipeline completes, so the second `cypress run (... b2b)` is not even started and we get no results about b2b.

We should run both of them. And if at least one of them fails, prevent immediate exit. Finally after both cypress runs complete let's exit with code `1`.

```
status=0;
cypress run (... b2c) || status=1;
cypress run (... b2b) || status=1;
exit $status;
```

**Comment by marlass** [comment]
Ideally we should slit them into separate jobs and run the concurrently. Then it won't be needed.

**Comment by Platonn** [comment]
Not needed anymore since we have parallelization in our pipeline
