### ISSUE TITLE
Store Finder Opening Hours to not correctly work when switching language / being shown for Languages other than English

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#10302]
**Describe the bug**
Switching the language via Language Switch does not change the Store Finder Store Opening Hours. Additionally, Store Finder Hours are not displayed for other languages than English.

**Tell us the version of Spartacus**
- Library version: 3.0.0-rc.1

**To Reproduce**
1. Go to https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/de/USD/store-finder/country/BE/sap-brussels-education-center-office
2. Look at the Opening Hours of the store, they are correctly formatted times in AM / PM format
3. Click on the language selector in the header and Choose "Deutsch" (German) as Language
4. Look again at the opening Hours of the store, which did not change to German Time format after changing the language
5. Do a full page reload
6. Look again at the opening Hours of the store, which are not displayed anymore at all

**Expected behavior**
- Switching the Language via Language Selector updates the values on the page, which are language / locale based without a Page reload (In this case the Opening Hours of the Store) (or if that's not possible, trigger a full reload)
- Visiting the Store Detail Page shows the Opening Hours correctly formatted for other languages than English (Does not work for any other languages than english on the demo instance currently)

**Screenshots**
Store Hours for Language English:
![image](https://user-images.githubusercontent.com/3381820/101624571-63a12d00-3a1a-11eb-9a6d-d26e327a9301.png)

Empty Store Hours for Language German (Or any other language than english):
![image](https://user-images.githubusercontent.com/3381820/101624285-04431d00-3a1a-11eb-8908-d08ee51ffb99.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Comment by Parthlakhani** [comment]
Added the fix for loading opening hours for other languages.
Anything within `Find a Store` is not updated on language change, it only updates once we reload the page, do we need to change that?

**Comment by tobi-or-not-tobi** [comment]
> Added the fix for loading opening hours for other languages.
> Anything within `Find a Store` is not updated on language change, it only updates once we reload the page, do we need to change that?

yes we should also clear the storefinder store in case of a language change. Can you take care of that?

**Comment by giancorderoortiz** [comment]
I see this issue is now fixed: 

English: 
![Screen Shot 2021-05-18 at 8 03 48 AM](https://user-images.githubusercontent.com/46171897/118647807-bfcd6180-b7af-11eb-95d2-8938c8c4bc13.png)


German: 
![Screen Shot 2021-05-18 at 8 04 00 AM](https://user-images.githubusercontent.com/46171897/118647823-c4921580-b7af-11eb-835b-6a341d418893.png)

Japanese: 
![Screen Shot 2021-05-18 at 8 04 14 AM](https://user-images.githubusercontent.com/46171897/118647838-c956c980-b7af-11eb-8659-071c8ffb50de.png)
