### ISSUE TITLE
RC2. Added To Cart Dialog not Triggered. Linux Deployment

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10319]
**Steps to Reproduce:** 
1. Deploy Spartacus 3.0 RC2 in Linux server. 
2. Navigate to Electronics storefront. 
3. Search for "camera". 
4. On any of the products listed, click on Add to cart. 
5. Double click to open PLP of product added to cart. 
6. Click on "+" and "Add to Cart" button. 

**Expected Results:** 
6. "Added to Cart" dialog is displayed. 
6.a. Minicart quantity is updated. 

**Actual Results:** 
6. Message saying product has already been added to cart is shown. 
6.a. Minicart quantity is not updated. 

**Linux Deployment:** 
![Screen Shot 2020-12-09 at 1 15 42 PM](https://user-images.githubusercontent.com/46171897/101670143-cdbcd080-3a20-11eb-9ae0-123f870c8b45.png)

**CCV2 Deployment:** 
![Screen Shot 2020-12-09 at 1 15 20 PM](https://user-images.githubusercontent.com/46171897/101670166-d3b2b180-3a20-11eb-8c85-746bdf30d243.png)

**Comment by giancorderoortiz** [comment]
Caused by having b2b enabled (ADD_B2B_LIBS=true). 
Further investigation required.

**Comment by Xymmer** [comment]
not a bug, b2b spartacus doesn't support b2c basesites
