### ISSUE TITLE
Enabling B2B via Installation Script Breaks B2C

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10320]
**Steps to Reproduce:** 

1. Deploy Spartacus in Linux server using installation script. 
1.a. Enable B2B in config.sh ADD_B2B_LIBS=true. 
1.b. Use SPARTACUS_VERSION='3.0.0-rc.0'
1.c. ./run.sh install_npm
1.d. ./run.sh start
2. Navigate to B2C storefronts. Either electronics or apparel. 
3. Add items to cart. 

**Expected Results:** 
3. Items added to cart successfully. 

**Actual Results:** 
3. Cart remains empty. 
3.a. orgUsers API used instead of users. 
3.a. (Sample call actually made: https://cx-qa16181492.eastus.cloudapp.azure.com:9002/occ/v2/electronics-spa/orgUsers/current/carts/00000361/entries?quantity=1&code=443175&qty=1&lang=en&curr=USD)

Note: This compatibility between b2b and b2c was expected for 3.0 within the same deployment.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-09 at 3 01 33 PM](https://user-images.githubusercontent.com/46171897/101681139-b507e700-3a2f-11eb-8beb-691c7da13dbe.png)

![Screen Shot 2020-12-09 at 3 01 18 PM](https://user-images.githubusercontent.com/46171897/101681115-acafac00-3a2f-11eb-99ef-468d47a95d18.png)

**Comment by giancorderoortiz** [comment]
With this setup the b2c storefront cannot be used to checkout items.

**Comment by giancorderoortiz** [comment]
Applies to yarn deployments as well

**Comment by Xymmer** [comment]
Doesn't block release, and in future we'll have just one app that supports both b2c and b2b
