### ISSUE TITLE
[needs reporter input] Eternal loading on SmartEdit on Home page when routing forces login

### ISSUE THREAD

**Issue by cdelafuente72** [SAP/spartacus#10331]
When the autentication id forced at the Home page, the "loading" is permanent at the SmartEdit and can't edit the page.

Spartacus/core": "^3.0.0-next.6";
Angular 10,
Any browser

To reproduce bug:
This occurs only in the Home page (the rest of pages are OK) and if the authentication is forced.
We can skip it by loading on the site through the browser.

Expected behavior
Enter into the Home page throught  smartEdit without frozen

![loading_bug](https://user-images.githubusercontent.com/11504097/101769186-e1326f00-3ae6-11eb-8735-edb681c4e3d1.png)

**Comment by Xymmer** [comment]
Hi @cdelafuente72 
Can you elaborate on repro steps, what does "When the autentication id forced at the Home page" mean?

**Comment by WeizhengSap** [comment]
I tested it with the latest develop branch, it works fine. There is no Perspective Toolbar in the screenshot. Please check this https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/#the-perspective-toolbar-is-missing
