### ISSUE TITLE
Creation on budgets e2e is flaky

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#10334]
Branch off `feature/GH-10263` #10301

Budget creation is sometimes failing due to missing the Unit property on detail/form.

![image](https://user-images.githubusercontent.com/11735817/101787132-0d59ea00-3aff-11eb-86f3-5d09b5d9df3f.png)

**Comment by psmul** [comment]
After many attempts and re-runs, I wasn't able to reproduce this error. This might've been small backend hiccup. After discussion with @Zeyber, closing this issue.
