### ISSUE TITLE
SampleData and SPA: Refactor CMS components and page labels

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#10349]
See https://github.tools.sap/cx-commerce/spartacussampledata/pull/151/
Following changes are needed:

- [DONE] We don't use jspIncludeComponent in Spartacus, instead we use CMSFlexComponent. This means attribute 'flexType' needs to be provided with the component ID 
- [DONE] Have localizations in extra files
- [DONE] Follow convention with regards to comments. Have 
`###### modules/cpq-product-configuration: CPQ configurator ######` as starting comment
- [DONE] Remove some non-used impex, such as ComponentTypeGroup created. (INSERT_UPDATE ContentSlotName... has compTypeGroup(code), in which you can use your new ComponentTypeGroup, but I didn't find they are used.)
- [DONE] Make impex clean and more readable. (I think this kind of comments can be removed. I can get the meaning from component uid
 ```
 ################################################
  ### Configuration Form                       ###
  ################################################
```
- [PREPARED, BUT COMMENTED] Page label is important for Spartacus. If possible, use the path to the page. This is the only one that affects the SPA side! Remove the pageLabel on SPA side in the routing config, and have the pageLabel on impex side like /configure/cpq

**Comment by Uli-Tiger** [comment]
https://github.tools.sap/cx-commerce/spartacussampledata/pull/155

**Comment by Uli-Tiger** [comment]
@ChristophHi I did everything excluding the incompatible page label change. 
Can you review in a first iteration those changes now and then put the ticket back to me. 
in a second iterations i would like to make the incompatible changes page label changes.
