### ISSUE TITLE
Move default routing into library

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10350]

**Comment by Uli-Tiger** [comment]
@Larisa-Staroverova : From the title it's not clear to me what needs to be done. is there a wiki, or a reference task we can link?

**Comment by Uli-Tiger** [comment]
@Larisa-Staroverova : From the title it's not clear to me what needs to be done. is there a wiki, or a reference task we can link?

**Comment by Larisa-Staroverova** [comment]
Hi, Uli, sorry, the e-mail was forgotten.
@ChristophHi did something similar for _**epic/product-configuration**_. 
The following [commit](https://github.com/SAP/spartacus/commit/4d88f03a0552f77aa19a7a96415d784596b32465) could be used as a reference.
