### ISSUE TITLE
[Łukasz] Add Quantity on Attribute Level to simple DDLB component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10365]
Add item-counter component to attribute type.
Change update event that it will be triggered by quantity change as well.
Add quantity to update event.
https://4prsat.axshare.com/#id=lj29ab&p=values_dropdown_qtybox&g=1

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 095220](https://user-images.githubusercontent.com/12393718/103625783-bbf51d00-4f3b-11eb-87a2-20c0c41db646.png)
