### ISSUE TITLE
[Łukasz] Add Quantity on Attribute Level to Bundle CheckboxList component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10369]
Add item-counter component to attribute type.
Change update event that it will be triggered by quantity change as well.
Add quantity to update event.

**Comment by luklus** [comment]
![Uploading Zrzut ekranu 2021-01-05 095541.png…]()

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 095541](https://user-images.githubusercontent.com/12393718/103626265-3aea5580-4f3c-11eb-948e-f615118c7a66.png)
