### ISSUE TITLE
[Łukasz] Add Quantity on Attribute Level to Bundle Radiobutton component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10367]
Add item-counter component to attribute type.
Change update event that it will be triggered by quantity change as well.
Add quantity to update event.
https://4prsat.axshare.com/#id=yi2o3p&p=bundling_single_select_qtybox_no_mandatory&g=1

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 095541](https://user-images.githubusercontent.com/12393718/103628391-383d2f80-4f3f-11eb-9848-b350d081ae79.png)
