### ISSUE TITLE
Add Quantity on Attribute Level to simple Radiobutton component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10364]
Add item-counter component to radio button attribute type.
Change update event that it will be triggered by quantity change as well. 
Add quantity to update event.

https://4prsat.axshare.com/#id=2xv8gs&p=single_select_no_photo&g=1

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 095423](https://user-images.githubusercontent.com/12393718/103626078-01b1e580-4f3c-11eb-9a15-8ec4be836d0f.png)
