### ISSUE TITLE
[Łukasz] Add Quantity on Attribute Level to Bundle DDLB component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10368]
Add item-counter component to attribute type.
Change update event that it will be triggered by quantity change as well.
Add quantity to update event.
https://4prsat.axshare.com/#id=psi27e&p=dropdown_single_select&g=1

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 101624](https://user-images.githubusercontent.com/12393718/103628308-1b086100-4f3f-11eb-96a0-09e6775b331b.png)
