### ISSUE TITLE
Add Quantity on Attribute Level to simple CheckboxList component and propagate it to Update Event

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10366]
Add item-counter component to attribute type.
Change update event that it will be triggered by quantity change as well.
Add quantity to update event.

**Comment by luklus** [comment]
@steinsebastian 
I think that for CheckboxList  we don't need Attribute Level quantity. We have Value level for it. Checkbox is multiselect. I can't see any wireframes and data for it. Ticket to close or explain.

**Comment by AlexanderKuschner** [comment]
CPQ support both cases for Checkboxes: Value level quantity as well as Attribute level quantity. Attribute level quantity for Checkboxes is used very seldom, but is supported by the CPQ modeling.
Use Attribute level quantity when  Attribute.dataType = USER_SELECTION_QTY_ATTRIBUTE_LEVEL 
and  Value level quantity when  Attribute.dataType = USER_SELECTION_QTY_VALUE_LEVEL,

**Comment by luklus** [comment]
ok, so i start implement it

**Comment by luklus** [comment]
Feature ready

https://user-images.githubusercontent.com/12393718/104880371-ba761c80-595f-11eb-9de6-ae8a16f39973.mp4
