### ISSUE TITLE
[Łukasz] Add field to Configuration model indicating attrubute change or value quantity change and make sure its filled.

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10372]
Add field to Configuration model indicating attribute change or value quantity change. 
(Coulde be flags on attribute and / or value level)

**Comment by Uli-Tiger** [comment]
Added field  updateType?: UpdateType; to Configuration. as part of GH-10375. 
However this can be changed, if required. Just added this to be able to proper test GH-10375.

**Comment by luklus** [comment]
- [x] show/hide quantity depend on dataType value
- [x] move quantity to separate component
- [x] add debounce to quantity component
