### ISSUE TITLE
TODO: Cart items refreshing for every value change

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#10379]
Hi everyone.

Is this TODO planned to be solved soon ? We are facing some terrible performance issues within 100+ products baskets. The initial rendering is quite OK, but then, everytime we change a QTY, all the lines are re-renderer so the interaction is very slow.

https://github.com/SAP/spartacus/blob/91db09804fa53c5f2a6d1289c02a3c9fe79f67a5/projects/storefrontlib/src/cms-components/cart/cart-shared/cart-item-list/cart-item-list.component.ts#L32-L39

Thanks a lot !

**Comment by Parthlakhani** [comment]
Tried reproducing the bug with 180 products in the cart, could not reproduce.

**Comment by hackergil** [comment]
Current solution does not work properly
* It caused a bug where the last product is duplicated with a quantity of 0
* On cart-item-list.component, we cannot modify cart item list `this._items` in version > 3.0 since we've activated `strict mode` and it freezes arrays and properties.

**Comment by Zeyber** [comment]
It doesn't look like all cart items are rendering on QTY change anymore. Only the item with the updated QTY which is what's desired.

![image](https://user-images.githubusercontent.com/11735817/115011220-ae422280-9eae-11eb-85af-5d27e96b7816.png)

**Comment by giancorderoortiz** [comment]
@sebastianfdez could you please share with us the average, max, mean cart size in your project? It would help us for testing purposes.

**Comment by giancorderoortiz** [comment]
This issue "appears" to be fixed. 
I recreated a cart with 100+ items in it. 
Upon changing quantities, I do see a delay of less than 5 seconds. The delay is random, but it's there. 
Attaching some screen shots and video-recordings. 
However, I do not see terrible performance as initially described in this ticket. ✅ 

It's necessary to have concrete performance specs and expectations regarding large carts so we can reproduce internally.

**Comment by giancorderoortiz** [comment]
https://user-images.githubusercontent.com/46171897/118637405-c229be80-b7a3-11eb-9df9-2d764254e127.mov

**Comment by giancorderoortiz** [comment]
https://user-images.githubusercontent.com/46171897/118637469-d53c8e80-b7a3-11eb-9cf9-0b7a756ca585.mov

**Comment by giancorderoortiz** [comment]
[ qa_server_profile-20210518T061752.json.zip](https://github.com/SAP/spartacus/files/6500625/qa_server_profile-20210518T061752.json.zip)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-05-18 at 6 20 30 AM](https://user-images.githubusercontent.com/46171897/118637817-32d0db00-b7a4-11eb-8233-f2990885c4ec.png)

![Screen Shot 2021-05-18 at 6 24 47 AM](https://user-images.githubusercontent.com/46171897/118637839-382e2580-b7a4-11eb-8ac3-5254b9dd68fe.png)
