### ISSUE TITLE
[Łukasz] Add Quantity on Value Level to simple CheckboxList component

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10373]
https://4prsat.axshare.com/#id=abtnzz&p=values_multi_select_qtybox&g=1

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-05 154650](https://user-images.githubusercontent.com/12393718/103659931-4a35c700-4f6d-11eb-904b-5eac136bd05b.png)
