### ISSUE TITLE
Take care that for single-valued cstics with qty on value level allowed the correct data is submitted to CPQ.

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10376]
Single value attributes with value quantity will be shown as if they have attribute quantity. 
In the update case the quantity must be part of the value even though it is shown as attribute quantity.

**Comment by Uli-Tiger** [comment]
we documented:
"For single selections (Radio Group, DDLB) we only support quantity on attribute level. Quantities on value level will be ignored."
This is also the current behaviour.
