### ISSUE TITLE
Bulk Pricing Backend Server

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10383]
Deploy Bulk Pricing Backend Server. 

- CX 2005
- This sample data branch https://github.tools.sap/cx-commerce/spartacussampledata/tree/feature/GH-10158

**Comment by ren-tham** [comment]
(Answered before)

sampledata-branch: feature/GH-10158
https://github.tools.sap/cx-commerce/spartacussampledata/tree/feature/GH-10158

I'm not really sure which server version I need. I'll get back to you.

**Comment by hackergil** [comment]
New environment ready. OCC endpoint:

https://spartacus-dev2.eastus.cloudapp.azure.com:9002

**Comment by bgambocjaviniar** [comment]
closing as we were using the server on December 23rd, and he's currently using it for his implementation feature so it was successfully deployed
