### ISSUE TITLE
Collection "@angular/pwa" cannot be resolved

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10386]
**Describe the bug**
When adding Spartacus to a new project using schematics, it failed with and error `Collection "@angular/pwa" cannot be resolved`

**Tell us the version of Spartacus**
- Spartacus 3.0.0-rc.3

**To Reproduce**
1. Create a new project `ng new [projectname] --style=scss
2. `cd [projectname]`
2. Add latest RC (3 at the time of the creation of this bug) `ng add @spartacus/schematics@rc --pwa --ssr`
3. Observe the error `Collection "@angular/pwa`

<img width="560" alt="Screen Shot 2020-12-11 at 2 31 27 PM" src="https://user-images.githubusercontent.com/15215400/101952092-b5ce8380-3bbd-11eb-8b90-22993216a61d.png">

**Expected behavior**
Spartacus should be added without any errors 

**Desktop (please complete the following information):**
- Any terminal window

**Additional context**
This issue was discovered while trying to deploy the latest RC (Spartacus 3.0.0-rc.3) to CCV2. Due to this error, the deployment is blocked

**Comment by LTiger14** [comment]
This is only for RC3 as this command `ng add @spartacus/schematics@3.0.0-rc.2 --pwa --ssr` is successful.

**Comment by LTiger14** [comment]
Upon investigation the error is thrown by this line https://github.com/SAP/spartacus/blob/release/3.0.x/projects/schematics/src/add-pwa/index.ts#L84

Running `yarn add @ angular/cli` before adding Spartacus with PWA does not throw the error.
