### ISSUE TITLE
[do this soon] Schematics Deployment Script Failure. Develop Branch. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#10384]
**Steps to Reproduce:** 
1. Clone Spartacus github repo. 
2. Navigate to scripts/install and copy config.default.sh into config.sh. 
3. Modify config.sh as needed. Make sure develop branch is specified and b2b flag is enabled. 
4. Execute ./run.sh install command. 

**Expected Results:** 
4. Develop branch is deployed successfully. 

**Actual Results:** 
4. Cannot find library /feature-libs/misc

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-11 at 10 21 54 AM](https://user-images.githubusercontent.com/46171897/101936705-e529c400-3bae-11eb-96f1-4463c917bc43.png)
![Screen Shot 2020-12-11 at 10 23 19 AM](https://user-images.githubusercontent.com/46171897/101936706-e529c400-3bae-11eb-8842-120638461fed.png)

**Comment by giancorderoortiz** [comment]
Installation script broken for develop branch of Dec 10, 2020.

**Comment by Platonn** [comment]
Your config.sh looks a bit outdated. The `misc `library was renamed to `storefinder `7 days ago :
https://github.com/SAP/spartacus/pull/10261/files#diff-ec74f283baaf320086e2f3bfee2a7f613bff8d33b3f1797f5671f0d853f57b50R22

Please replace `feature-libs/misc` to `feature-libs/storefinder` in your `config.sh` file

**Comment by marlass** [comment]
And for future reference only copy properties from the `config.default.sh` to `config.sh` properties you need to change. Don't copy everything as it will cause any trouble with the improvements we do in the script.

**Comment by marlass** [comment]
Everything works fine on develop branch.
Please remember to only set properties in `config.sh` that you want to customize (eg. `api prefix`, `port`).
Do not copy blindly everything from the `config.default.sh` file to your `config.sh` file.
