### ISSUE TITLE
Fix flakiness of regressions tests when running in parallel

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10397]
We want to parallelize e2e regression tests.
However when testing the solutio (https://github.com/SAP/spartacus/pull/9458/files) few tests are showing signs of instability (ASM mostly)

**Comment by giancorderoortiz** [comment]
Can you please share a report of the flakiness encountered thus far when running in parallel?

**Comment by hackergil** [comment]
Based on several runs of #9458. Results recorded on cypress dashboard (check tag `flaky` also)

https://dashboard.cypress.io/projects/k3nmep/runs/8980/specs

* There are 7 specs failing on Travis that need to be fixed before merging #9458 
* There are 22 specs marked as `flaky` running on github actions (on a separate build step) that can run and eventually be fixed without blocking merges to develop

**Comment by hackergil** [comment]
After Parallelization change was merged, flaky e2es are running on a separate build and do not interfere with the main build. We'll incorporate them to the stable bucket as we fix them
