### ISSUE TITLE
Avoid dependencies in @spartacus/schematics

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10429]
We dropped @angular/pwa as a dependency in schematics in #10386

We should do it also for localize and express-engine library and install them in created application before executing their schematics.

Also fix comments:
https://github.com/SAP/spartacus/pull/10426#discussion_r543472241
https://github.com/SAP/spartacus/pull/10426#discussion_r543473733

**Comment by giancorderoortiz** [comment]
how to qa?
