### ISSUE TITLE
Empty occ baseUrl breaks auth feature

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10436]
In case when you run spartacus in the same domain as the API we don't have to set occ url as API endpoints can be referenced with relative urls (not the absolute).

Auth endpoints fallback to occ `baseUrl`, so this case should work the same way with relative urls instead of absolute.

**Comment by marlass** [comment]
QA steps:

- have spartacus and backend on the same domain
- remove `occ.baseUrl` option from your config
- check if page still works
- check if you have warning in console about `Authentication might not work etc.`

Part 2:
- set `authentication.OAuthLibConfig.requireHttps` to `false`
- check if auth works and the warning no longer exists

**Comment by artem-zur** [comment]
> In case when you run spartacus in the same domain as the API we don't have to set occ url as API endpoints can be referenced with relative urls (not the absolute).

Dear @marlass, does it mean that it can be applied to SSR mode as well?
