### ISSUE TITLE
Expose separately core SCSS mixins, functions and variables

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10441]
Currently to access core SCSS mixins, function and variables from a separate library, one could import whole styles from `@import "@spartacus/styles"`. But that would add up yet another copy of all core styles (CSS selectors with rules) in the final production application.

Let's expose a separate entry point inside `@spartacus/styles` for only reusable mixins, function and variables that don't produce itself any selectors, when being imported.

**Note:**
Separate lib's styles (i.e. `@spartacus/product-configurator`), which use core mixins, won't compile in a fresh shell up, unless it imports `@import "@spartacus/styles/..."` inside.

That said, in development mode in our storefrontapp referencing `@spartacus/styles` won't work unless we add an alias in our storefrontapp's `extra-webpack.config`:

```js
const path = require('path');
/*...*/

module.exports = {
  /*...*/
  resolve: {
    alias: {
      '@spartacus/styles': path.join(__dirname, 'projects/storefrontstyles'),
    },
  },
};

```

**Comment by KateChuen** [comment]
Talked with Krzysztof, no QA required on this ticket, moving it to Done.
