### ISSUE TITLE
Update Andrew's (P4) Spartacus/addons server to commerce-suite-2105.0.201215001.zip

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10449]
This one: https://portalstg.hana.ondemand.com/subscription/e0b35f0e95024840a55e944477e3aa26/applications/commerce-cloud/environments/p4
Currently named "2011 Commerce Spartacus 2.1 SmartEdit Personalization CDS"

**Comment by LTiger14** [comment]
@xymmer it's done and seems to work perfectly; please try it out. I left 2.1 as this ticket didn't talk about moving to 3.0.
