### ISSUE TITLE
A lot of scss comments duplication in production css file 

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10445]
I tested in SSR PWA setup and found that in final css file there are a lot of SCSS comments.
Two comments that repeats starts with: `CXBASE VARIABLES` and `SPARTA v0.1`

These comments use `/*! */` syntax which scss keeps in production build.
For this type of comments we should not use this syntax and rely on normal comments.

**Comment by tobi-or-not-tobi** [comment]
TIL sass multi-line comments (`/** */`) are actually processed in final (production) CSS. Single comment lines (`//`) are not. 

> The way Sass comments work differs substantially between SCSS and the indented syntax. Both syntaxes support two types of comments: comments defined using /* */ that are (usually) compiled to CSS, and comments defined using // that are not.
(https://sass-lang.com/documentation/syntax/comments)

The _compressed_ mode actually removes the multi-line comments as well, but this is not a feature as part of the angular-CLI. Ideally the angular.json would have an option to enalbe compressed mode. We could consider this as a feature request to the CLI project, but for now it's probably best to change to single line comments. 

There's also a way to include multi-line comments in compressed mode, using the `/*!` syntax. This could be used for license messages, but other than that we should not use it.
