### ISSUE TITLE
CSS is written in single file

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#10454]
Feature libraries have manage their own sources for the style layer. We have a future plan to make the different css files lazily loaded, which is why we already intend to load the styles in their own files. This is currently however not the case. All styles are conctenated in a single css file due to a misconfiguration of the `angular.json` file.

This ticket will change this for the internal sample app (storefrontapp), but we should also consider this in schematic installation. However, given that this will be a breaking change, we might progress with the lazy loading story and will do that instead in schematics installation.

**Comment by KateChuen** [comment]
Talked with Krzysztof, no need to QA this ticket. so moving it to Done.
