### ISSUE TITLE
Guest checkout - create a user in the end fails with no user feedback when email not unique

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10460]
**Describe the bug**
When a user goes through guest checkout with an email that is already used by a registered user, the optional registration process at the end of checkout doesn't work, but there is no message and no feedback.  It looks like the form submit button is broken.

**Tell us the version of Spartacus**

test env https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/ (see #10030)

**Steps to reproduce:**

I used Chrome on Windows desktop.

* Complete guest checkout with an email that is already used by a registered user
* On the order confirmation page, enter a password and submit the optional registration
* Bug: nothing happens when the user submits his registration

**Expected behavior**
In the dev tools, in the network pane, we see there is an error returned by the backend.  The user should be given feedback about the error.

**Comment by hackergil** [comment]
Same happens on mac with firefox and iphone safari (large)

**Comment by Xymmer** [comment]
not critical as user already exists, however let's look into if this is a backend issue

**Comment by bgambocjaviniar** [comment]
PR: GH-10599
Maintenance PR: GH-10888

QA:
- enable guest checkout
- checkout using a guest email that already exist (that is already registered in the system)
- go through the whole checkout-flow until you have reached order-confirmation page
- try to create an account by adding a password to register the email

it should throw a global message error

**Comment by Zeyber** [comment]
QA: Error is visible.
![image](https://user-images.githubusercontent.com/11735817/106107923-d63fa680-6147-11eb-854a-81f023763af6.png)
