### ISSUE TITLE
Assign/Unassign Approvers works in random order

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#10468]
Assign/Unassign Approvers works in random order. 

![assign](https://user-images.githubusercontent.com/6958810/102488300-2406c080-406c-11eb-937a-f9ef308f546b.gif)

**Environment:**
RC.4 deployed on ccv2: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/organization/users/995c9658-ac2f-4f17-aa54-eccde4376acb/approvers/assign

**Tested on:** 
Windows Firefox 81.0.2

**Steps to reproduce:**
1. Go to My Company Users
2. Select user and click Approvers and then click "Manage" (you need to ensure that have approvers defined)
3. Play with Assign/Unassign buttons, they are working like on attached image.

**Expected result:**
Clicking on specific Assign/Unassign button should not affect other users assignment.

**Comment by Pucek9** [comment]
As I can see, it works exactly the same as the other features (eg. user assign user groups) which have proper behavior. 
![image](https://user-images.githubusercontent.com/8040837/102536890-85e61b00-40aa-11eb-87ef-b28ae56b39f7.png)
It seems as the reason can be that we are loading user list, while we have other user list in the background

Update: The order of 2 last actions is different, but not sure that it's important
