### ISSUE TITLE
Migration of page resolvers

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#10467]
There has been a number of changes to page resolvers in the 3.x releases. We like to make those changes final in 4.0 and introduce migrations for all the changes. 

Cleanup deprecated constructors and logic for:

- [x] `BasePageMetaResolver`
- [x] `ContentPageMetaResolver`
- [x] `SearchPageMetaResolver`
- [x] `CategoryPageMetaResolver`
- [x] `ProductPageMetaResolver`
- [x] `CartPageMetaResolver`
- [x] `CheckoutPageMetaResolver`
- [x] `OrganizationPageMetaResolver`
- [x] `PageMetaService`
- [x] `RoutingService`

Refactoring of resolverMethods:
- [x] Drop `PageMetaService.resolverMethods`
- [x] Consider  renaming `CmsPageTitleModule` to `CmsPageModule` or `PageModule` now that it hosts the PageMeta configuration
- [x] Drop the default robots meta in the seo-meta service.
- [x] Disable description, image and robots resolvers to optimise resolving logic.
- [x] Enable canonical Url configuration in the `defaultPageMetaConfig`. 

Sample Data
- [ ] Add page description and robots to cart page
- [ ] Add page description and robots to checkout page
- [ ] Add page description and robots to organization page

**Comment by Platonn** [comment]
We can also reuse methods of `BasePageMetaResolver` in:
- `CartPageMetaResolver`: `resolveTitle()`
- `OrganizationPageMetaResolver`: `resolveTitle()`, `resolveRobots()` and `breadcrumbs$`
