### ISSUE TITLE
[Firefox] Unit shipping address - form data is not clearing after submit

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#10464]
**Tell us the version of Spartacus**
- RC.4 on CCV2: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

**Describe the bug**
User is able to add new shipping address, however after form submit form data is not clearing, and there is no redirect to recent created address details, or to shipping address list.

Also seems that headings are mixed up. When I'm on "Create address" page I can see "Edit address" heading.
![Screenshot 2020-12-17 111555](https://user-images.githubusercontent.com/6958810/102474726-46431300-4059-11eb-8ba9-b627ef855ba8.png)

**To Reproduce**
1. Login to B2B
2. Go to MyCompany Organization homepage and then select units
3. Select some unit from the list
4. Go to shipping addresses and click "Create"
5. Fill shipping form with required data and click "Save".

**Expected behavior**
After save user is redirected to newly created unit details.
Heading for "Create" address page should be "Create address" not "Edit address".

**Desktop (please complete the following information):**
 - Windows
 - Firefox
 - 81.0.2 (64-bit)

**Comment by Pucek9** [comment]
Started from https://github.com/SAP/spartacus/commit/35d184b09491244efc7365e2211be9042a35e704
