### ISSUE TITLE
Browser/Device regression testing for 3.0 -> cannot place order with replenish order option

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#10471]
**Describe the bug**
Cannot place an order with replanish order option (no error on the page).

**Tell us the version of Spartacus**
Library version: 3.0

**To Reproduce**
1. Add some products to the cart
2. Follow the steps in the checkout
3. On the last step select 'replenish order'
4. Try to place an order

**Expected behavior**
Error message or success checkout.

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/102492249-b493cf80-4071-11eb-9b3f-253d5f918f17.png)
![image](https://user-images.githubusercontent.com/18736434/102492276-bcec0a80-4071-11eb-89a3-8368521d1a0c.png)
![image](https://user-images.githubusercontent.com/18736434/102492283-bfe6fb00-4071-11eb-82ef-6bdcabd37845.png)

**Desktop (please complete the following information):**
OS: Windows
Browser Chrome
Version 87.0.4280.88

**Comment by Xymmer** [comment]
just tried it, it works
like trying to check out as non-buyer like admin
