### ISSUE TITLE
Browser/Device regression testing for 3.0 -> cannot create unit with selected approval process

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#10470]
**Describe the bug**
Cannot create Unit with: name: test, id: 123, selected approval process, and selected parent business unit.
No error on page. In console error:
{ "errors" : [ { "message" : "Expected: class de.hybris.platform.b2b.model.B2BUnitModel but got: class de.hybris.platform.b2b.model.B2BUserGroupModel", "type" : "ClassMismatchError" } ] }

**Tell us the version of Spartacus**
Library version: 3.0

**To Reproduce**
1. Go to MyCompany
2. Go to Units
3. Add unit
4. Enter test name 123 id select parent business unit and approval process.

**Expected behavior**
Error message or working feature

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/102492005-523acf00-4071-11eb-9df5-ac7ce8668bfb.png)

**Desktop (please complete the following information):**
OS: Windows
Browser Chrome
Version 87.0.4280.88
and
OS: Mac
Browser: Safari
Version 14.0.2

**Comment by Xymmer** [comment]
can't repro, close

**Comment by dydome** [comment]
@Xymmer I have a video created 1 minute ago with repro. But cannot add here.

**Comment by Xymmer** [comment]
which server?

**Comment by Xymmer** [comment]
watch the video and retried and was able to create with same unit set, will keep this one closed unless we see it again and can repro on another computer.
