### ISSUE TITLE
Enhance overview attribute model with product code and type (enum with general and bundle as values) and adapt normalizer

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10479]
Update overview attribute model with:
- product code
- attribute type (general/bundle)

Fill new model fields in normaliser with information from CPQ.
Normalizer to enhance: cpq-configurator-overview-normalizer.ts

**Comment by kacperknapik** [comment]
So far the PR consists of:
- [x] added 2 properties to `AttributeOverview` interface (`productCode` and `type`)
- [x] added type enum (used above) (`general` and `bundle`)

Things left to do:
- [ ] update normalizer
