### ISSUE TITLE
No redirect after changing the password for a user

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10485]
As title said - after successfully changed password (`PATCH` request) no message is displayed. Not a blocker but for sure an UX issue.

**Comment by Pucek9** [comment]
Probably you mean mobile view. 
![image](https://user-images.githubusercontent.com/8040837/104030608-f4128f00-51cb-11eb-8d6e-5d7120694b4e.png)
I think there is another issue, we should be redirected back
