### ISSUE TITLE
There is "quotes" entry in the menu however it returns 404 page. [related to sample data]

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10487]
As title says, related to #10012

**Comment by Xymmer** [comment]
check if our sample data removes this menu item, but i think we did it and maybe our test server doesn't have the right sample data

**Comment by Pucek9** [comment]
@mirkosoft 
Still needed?

**Comment by Pucek9** [comment]
Ticket not related to organization

**Comment by Xymmer** [comment]
this was removed
