### ISSUE TITLE
Misleading text in checkout totals for a cart with gross pricing

### ISSUE THREAD

**Issue by enginvolkan** [SAP/spartacus#10489]
**Describe the bug**
My cart has gross pricing activated in backend (taxes are already included in the totals). In checkout, in order summary section, the tax is displayed as follows:
**"The order total does not include tax of $4.24."** which is misleading.

**Tell us the version of Spartacus**
- Library version: [e.g. 3.0rc0]

**Expected behavior**
The text should be **"The order total includes tax of $4.24."** .

**Screenshots**
Screenshot added
![GrossPricingTaxDisplay](https://user-images.githubusercontent.com/41514117/102527492-2c123080-406b-11eb-892a-09f7eaf45ad5.JPG)

**Desktop (please complete the following information):**
Windows, Chrome 87.0.4280.88

**Comment by Xymmer** [comment]
to developer: can we detect if gross is being used and use alternate text?

**Comment by dydome** [comment]
@Xymmer I did some analysis of this and what I have got. If I understand correctly this sentence 

> My cart has gross pricing activated in backend

we are talking about cart response field net: boolean which was set by @enginvolkan  to false

In `order-summary.component.html` we have section in the end:
`<div class="cx-summary-row" *ngIf="!cart.net">
    {{ 'orderCost.grossTax' | cxTranslate }}
    {{ cart.totalTax?.formattedValue }}.
  </div>`
  
We can add additional condition to check if totalPrice is the same as totalPriceWithTax and additionally check if totalTax exist and is bigger than 0. Than we can show **"The order total does not include tax of $4.24."**

May you please @enginvolkan confirm that this is what you need?

**Comment by enginvolkan** [comment]
Hi @dydome,

> we are talking about cart response field net: boolean which was set by @enginvolkan to false

that is correct
> May you please @enginvolkan confirm that this is what you need?

I think it is just enough to check cart.net as in order-summary-component.html. My point was about orderCost.grossTax text block. The text should be "**The order total includes tax of $4.24**." instead of "**..does not include..**". 

You can additionally consider introducing another text for the case where tax is zero (regardless of having a net or gross tax) in order to avoid saying something like "The order total includes (or does not include) tax of $0." which is not a wrong statement but maybe it can be written in a better way like "Estimated tax is zero" without using any include / exclude statement. Just a suggestion...

Thanks
