### ISSUE TITLE
Add price to configuration page attribute types

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#10482]
Cases:
- [x] Single select, quantity on attribute level only, price formula will be shown on attribute level. Value prices are shown on value level. https://4prsat.axshare.com/#id=yi2o3p&p=bundling_single-select_mandatory&g=1

- [x] DDLB Single select, quantity on attribute level only, price formula will be shown on attribute level. Value prices are shown on value level. https://4prsat.axshare.com/#id=7tjc75&p=bundling_dropdown&g=1

- [x] Multi select, quantity on attribute level, price will be shown with formula on value level, quantity stepper is shown on attribute level. https://4prsat.axshare.com/#id=o4cebm&p=bundling_multi-select_attribute&g=1

- [x] Multi select, quantity on value level, price will be shown with formula on value level, quantity stepper is shown on value level as well.  https://4prsat.axshare.com/#id=68anbn&p=bundling_multi-select_value&g=1
######################################################################################
1. Price calculation formula should look like this:
```
[quantity] x [valuePrice] = [valuePriceTotal]
3 x $60 = $180
```
2.  It could be possible that the **quantity** is **null**, than only valuePriceTotal should be displayed:
For the overview page, read the quantity from the data model
NB: For the configuration page get the right **quantity**, inject` feature-libs/product-configurator/rulebased/cpq/cpq-configurator-utilities.service.ts`  and call **prepareQuantity** method
```
[valuePriceTotal]
$60
```
3. It could be possible that the **valuePrice** is _not defined_, than only valuePriceTotal should be displayed:
```
[qunatity]
3
```
4.  Neither quantity nor valuePrice are defined, then nothing should be display

For the configuration the corresponding data could be read from **configurator.model.ts**:
```
export interface Value {
  ...
  quantity?: number;
  valuePrice?: PriceDetails;
  valuePriceTotal?: PriceDetails;
 ...
}
```
For the overview the corresponding data could be read from **configurator.model.ts**:
```
export interface AttributeOverview {
  ...
  quantity?: number;
  valuePrice?: PriceDetails;
  valuePriceTotal?: PriceDetails;
}
```

**Comment by kacperknapik** [comment]
We'll go with price only for now. There is a problem with quantity - rerendering of the page is causing problems with `configurator-price` component. Quantity handling (also the calculation) will be done later. Either in this ticket or another one

**Comment by kacperknapik** [comment]
Waiting for #10808
