### ISSUE TITLE
Enable ASM feature lib schematics.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#10490]
Depends on schematics update for the new storefront app module structure.

Schematics were disabled until then.  First, re-enable schematics by adding back [this liine](https://github.com/SAP/spartacus/pull/10431/commits/092171b4bd1e310674fdc5650f42d403eef4cbbf)
```
 "schematics": "./schematics/collection.json",
```
[acceptance criteria to refine]: Here are the use cases we need to cover:

Install a storefront from scratch with schematics:
[TODO: steps]

Install ASM in an existing app
[TODO: steps]

Tip: see readme of storefinder lib

**Comment by giancorderoortiz** [comment]
This implies using the installation script run.sh correct?

**Comment by plabadie** [comment]
Closing. Duplicate of GH-10744

**Comment by plabadie** [comment]
Closing. Duplicate of GH-10744
