### ISSUE TITLE
Category code in product search page

### ISSUE THREAD

**Issue by fernandadasneves** [SAP/spartacus#10522]
When selecting the product category, the breadcrumb for it appears with a code and not the name of the category.
The product page appears correctly.

Spartacus Version: 3.0.0

1. Go to Menu Navigation
2. Click on any category
3. See the breadcrumb with the category code 

Expected behavior:
It should appear as the product page the name of the category.

Screenshots:
Category page:
![image](https://user-images.githubusercontent.com/75036418/102872483-0789d000-4440-11eb-8bbb-10cf37de2145.png)

Product page:
![image](https://user-images.githubusercontent.com/75036418/102872530-17a1af80-4440-11eb-81bd-bdea36ffcfb7.png)

Desktop:
OS: Windows
Browser: Chrome, Edge
Version: last version

Smartphone:
Device: Android / IOS actual versions
OS: Actual Version
Browser chrome / safari
Version Actual versions

**Additional context**

**Comment by fernandadasneves** [comment]
hello,

any answer?

**Comment by fernandadasneves** [comment]
hello,

any answer?

**Comment by fernandadasneves** [comment]
hello,

any answer?

**Comment by fernandadasneves** [comment]
hello,

any answer?

**Comment by Xymmer** [comment]
to dev, please investigate. if it's backend, let me know and assign to me

**Comment by dydome** [comment]
Hi @fernandadasneves, in spartacus breadcrumbs component is using `page meta resolvers`, but it depands on which page you are currently. For ProductPage there is `product-page-meta.resolver.ts` which resolveBreadcrumbs using product API response with categories field:
`
  resolveBreadcrumbs(): Observable<BreadcrumbMeta[]> {
    return combineLatest([
      this.product$.pipe(),
      this.translation.translate('common.home'),
    ]).pipe(
      map(([p, label]: [Product, string]) => {
        const breadcrumbs = [];
        breadcrumbs.push({ label: label, link: '/' });
        for (const { name, code, url } of p.categories || []) {
          breadcrumbs.push({
            label: name || code,
            link: url,
          });
        }
        return breadcrumbs;
      })
    );
  }
`

as you can see label depends on name or code (maybe in your case name was missing).

But for category page, there is `category-page-meta.resolver.ts` which resolveBreadcrumbData using breadcrumbs field in search API response:

`
resolveBreadcrumbData(
    page: ProductSearchPage,
    label: string
  ): BreadcrumbMeta[] {
    const breadcrumbs: BreadcrumbMeta[] = [];
    breadcrumbs.push({ label: label, link: '/' });

    for (const br of page.breadcrumbs) {
      if (br.facetCode === 'category' || br.facetCode === 'allCategories') {
        breadcrumbs.push({
          label: br.facetValueName,
          link: `/c/${br.facetValueCode}`,
        });
      }
      if (br.facetCode === 'brand') {
        breadcrumbs.push({
          label: br.facetValueName,
          link: `/Brands/${br.facetValueName}/c/${br.facetValueCode}`,
        });
      }
    }
    return breadcrumbs;
  }
`

If it was not enough for you please try to provide us example using demo version of Spartacus:
https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/

**Comment by dydome** [comment]
As there was no contact for a long time, as a possible solution was provided, I will close this ticket.
