### ISSUE TITLE
getAddressCardContent method returning formattedAddress with gap between comas if address2 is empty

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#10524]
**Describe the bug**
OrderOverviewComponent with getAddressCardContent method returning formattedAddress with gap between comas when field 'address2' is empty (very common situation).

**Tell us the version of Spartacus**
- Library version: 3.0.0

**To Reproduce**
1. Go to 'OrderHistory' page
2. Click on order without address2 field data
3. Scroll down to order overview
4. See section 'Ship To'
5. Check 2 line of data

**Expected behavior**
If field 'address2' is empty, formattedAddress should avoid showing this part.

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/102882834-512de700-444f-11eb-9349-113c3ad1b336.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 87.0.4280.88

**Comment by bgambocjaviniar** [comment]
PR: GH-10595

QA: 
- add item to cart
- proceed to checkout
- create 2 addresses (leaving`address 2` blank and one with value for `address 2`)
- checkout twice with each newly created address
- verify in the order confirmation page under `Ship to` that it displays the formatted date properly as shown in the issue above

**Comment by giancorderoortiz** [comment]
Unnecessary commas removed as desired. 
![Screen Shot 2021-06-22 at 7 36 30 AM](https://user-images.githubusercontent.com/46171897/122918074-bb571400-d32c-11eb-9f0c-33d9b9dd0b1f.png)
