### ISSUE TITLE
Flickering on PDP and PLP due to SSR - version 1.4.4

### ISSUE THREAD

**Issue by Abi1234-git** [SAP/spartacus#10551]
**Describe the bug**
Hi Team,
We are having issues in our PLP and PDP pages where the page flickers when transition happens from SSR to CSR. We noticed this issue is reported in https://github.com/SAP/spartacus/issues/9960 and fix is available in Spartacus 3 version.
But in my project we are using the Spartacus 1.4.4 version. Please let us know if there is any solution/patch to fix this issue.

**Tell us the version of Spartacus**
1.4.4

**Expected behavior**
Flickering should not happen in PLP and PDP pages when transition happens from SSR to CSR.

**Comment by dunqan** [comment]
Hi @Abi1234-git. you are right, we fixed this and a couple of other flickering related issues in Spartacus 3.x, also backported fixes to 2.1.x, so upgrade to at least 2.1.x is advised. 

If you are unable to do it, you can take a look at this change, addressing PLP
https://github.com/SAP/spartacus/commit/0ba3f5814e0a54696e89877c315c9be1beac82a1#diff-e20603ba48425a78cb7a8943da13c3a380a85079c1169caccfd805c7225eaea1R101
`ProductListComponentService` in 1.4.4 have similar logic, there is a possibility to override it with similar fix (replace `combineLatest` + `pluck` with `using` operator).

As for PDP, the most important is a small tweak here:
https://github.com/SAP/spartacus/commit/0ba3f5814e0a54696e89877c315c9be1beac82a1#diff-d85cca24448ab8be9033909076c814477468eed3187d88518d53d05e1e10e59fR74
which could also be applied to 1.4.4 version.
