### ISSUE TITLE
Multivalued bundle items (list) not rendered correctly.

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10573]
See the bug on Jira board: https://cxjira.sap.com/browse/TIGER-7149
For example consider product CONF_CAMERA_BUNDLE. 
Attribute Memory Card (part of Main Components) should have 3 values. See the json extract below.
However only the first one  is vsualized, the other 2 are missing.

{
	"values": [
		{
			"imageOff": "",
			"imageOn": "",
			"imageOffAltText": "",
			"imageOnAltText": "",
			"paV_ID": 8714,
			"productSystemId": "SANDISK_EXTREME_PRO_128GB_SDXC",
			"selected": true,
			"valueDisplay": "SanDisk Extreme Pro 128GB SDXC",
			"quantity": "2",
			"description": "",
			"price": "100.00",
			"relativePrice": null,
			"isRelativePriceBigger": null,
			"recurringPrice": null,
			"valueCode": "SDEP128",
			"unit": null,
			"pricePeriod": null
		},
		{
			"imageOff": "",
			"imageOn": "",
			"imageOffAltText": "",
			"imageOnAltText": "",
			"paV_ID": 8715,
			"productSystemId": "SANDISK_ULTRA_64GB_SDHC",
			"selected": false,
			"valueDisplay": "SanDisk Ultra 64GB SDHC",
			"quantity": "0",
			"description": "",
			"price": "20.00",
			"relativePrice": null,
			"isRelativePriceBigger": null,
			"recurringPrice": null,
			"valueCode": "SDULTRA64",
			"unit": null,
			"pricePeriod": null
		},
		{
			"imageOff": "",
			"imageOn": "",
			"imageOffAltText": "",
			"imageOnAltText": "",
			"paV_ID": 8716,
			"productSystemId": "PANASONIC_AU-XP0512GB",
			"selected": false,
			"valueDisplay": "Panasonic AU-XP0512GB",
			"quantity": "0",
			"description": "",
			"price": "200.00",
			"relativePrice": null,
			"isRelativePriceBigger": null,
			"recurringPrice": null,
			"valueCode": "PANAAU-XP",
			"unit": null,
			"pricePeriod": null
		}
	]
}

**Comment by ChristophHi** [comment]
Hi @Uli-Tiger, could you check this one? I assume it can be closed

**Comment by Uli-Tiger** [comment]
closing a this has been solved already
