### ISSUE TITLE
Use "Country/Region" instead of "Country" label

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10571]
For SAP GLOB.192 which have the following requirements:
Use “Country/Region” instead of “Country” as field label in storefront and Backoffice.

This task:
- check if our label for "Country" are in Spartacus or from backend
- if in Spartacus, change to "Country/Region"
- if in backend, add note here and close issue

This goes for:
- checkout: shipping and payment addresses
- manage addresses

Also check if "country" is referenced anywhere else, and change to country/region as necessary.

See C5-27 for more details

**Comment by bgambocjaviniar** [comment]
PR: GH-10601
