### ISSUE TITLE
Sample Spartacus storefront is down

### ISSUE THREAD

**Issue by onuradsay** [SAP/spartacus#10586]
**Describe the bug**
There is a link to demo website on Readme.md file. After clicking this link, I'm getting a white screen.

**To Reproduce**
1. Go to https://spartacus-demo.eastus.cloudapp.azure.com/
2. There is only a white screen

**Expected behavior**
A demo website should be available

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: Chrome
 - Version: 87.0.4280.88

**Comment by Xymmer** [comment]
try https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/
as we're using same ports for different sites, the path is needed
