### ISSUE TITLE
Issues with certain reference items (probably because of slash in id)

### ISSUE THREAD

**Issue by MichaelBoeser** [SAP/spartacus#10591]
https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/USD/

logon as cpq03/welcome
Configure Camera Bundle.
For Lenses, Attributes:
TAMRON_18-200MM_F/3.5-6.3_DI_II_VC
TAMRON_SP_15-30MM_F/2.8_DI_VC_USD
CANON_RF_24-105MM_F/4L_IS_USM
no product data is returned.

e.g. the following call (with encoded '/' ) returns 404:
https://api.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com//occ/v2/powertools-spa/products/CANON_RF_24-105MM_F%2F4L_IS_USM?fields=DEFAULT,averageRating,images(FULL),classifications,manufacturer,numberOfReviews,categories(FULL),baseOptions,baseProduct,variantOptions,variantType&lang=en&curr=USD

I also checked on CPQ_SEL hybris instance, e.g. search for TAMROD, click on the product, you also get an error.

I copied the system Ids from callidus system. They contain a slash, which is probably the root cause.

**Comment by giancorderoortiz** [comment]
@MichaelBoeser  Please add screenshots of the issue you're describing.

**Comment by MichaelBoeser** [comment]
Hi, slashes in product ids are not supported. We removed them from the id in our test products. I will close the issue.
