### ISSUE TITLE
Create script for dependencies management

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10608]
He have a lot of inconsistency in dependencies listed in each library and between versions of them.

We can automate that process.
- we keep all dependencies in root package.json
- we specify automatically all peerDependencies in libraries based on imports and we get the version from root package.json
- schematics and migrations then are based on each lib package.json, so everything is listed
- updates of packages in root will be populated in all relevant places

**Comment by giancorderoortiz** [comment]
how to qa?
