### ISSUE TITLE
Missing product information in the "add to cart" dialog

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10620]
After adding to cart a product with multi-d variants:
http://localhost:4200/powertools-spa/en/USD/product/26038000_1/Direct%20Attach%20Waterproof%20Insulated%206%22%20Steel%20Toe%20Black%20%207%20M
it's information is missing:
![image](https://user-images.githubusercontent.com/788092/103914111-a33a6200-5109-11eb-95dc-d0d35f1a8135.png)

This is how it looks in the gen1 variant (along with variants related info (although title contains it as well in this case):
![image](https://user-images.githubusercontent.com/788092/103915031-efd26d00-510a-11eb-9538-61651daa82ba.png)

**Comment by dydome** [comment]
@mirkosoft it looks like. In this task, there is no FE action required. The product section is using cart-item component which is already fixed in #10621
