### ISSUE TITLE
Missing product information on the cart page

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10621]
The multi-d variants related information is missing next to the base information about products added to cart:
![image](https://user-images.githubusercontent.com/788092/103916637-f5c94d80-510c-11eb-8c04-9cf6fe51bb6b.png)

This is how it looks in the gen1 variant page:
![image](https://user-images.githubusercontent.com/788092/103916931-52c50380-510d-11eb-95dd-43d4e7f967ff.png)

Let's add them below the product id as it's added for gen1 (above).

**Comment by dydome** [comment]
@mirkosoft Required fields in Cart response for product object: 
- variantMatrix
- categories
- multidimensional
