### ISSUE TITLE
[V1] do not repeat value name on overview for multivalued attributes

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10636]
- open: http://cpqteamserver.mo.sap.corp:4200/electronics-spa/en/USD/
- search and configure digital camera
- in group Options, select all 4 additional options.
- navigate to overview page
ISSUE: Attribute name "Additional Options" is repeated for every value.
expected: According to this slack discussion, this is neither desired by our UID, nor by our PO.  Attribute name "Additional Options" should only be visible once.
https://sap-cx.slack.com/archives/CMSL1MGUR/p1610109125009100

**Comment by JayEmKay-8** [comment]
Also, the value names in the multiselect should be spaced closer together than the attribute names, the way is was in Accelerator. I'm attaching a screenshot from Accelerator for illustration.
![image](https://user-images.githubusercontent.com/54537803/104040685-422d8f80-51d8-11eb-99a3-fc62aefb34cf.png)

**Comment by Larisa-Staroverova** [comment]
This task should be solved by #11220. Plz, retest it as soon as possible.

**Comment by Larisa-Staroverova** [comment]
@JayEmKay-8, could you please retest?
Depending on the attribute type, the attribute name appears only once for multiselected values, for instance:
**Desktop:**
![image](https://user-images.githubusercontent.com/61147963/116965230-8f64ce00-acad-11eb-863d-c234d0125b8b.png)
![image](https://user-images.githubusercontent.com/61147963/116965273-af948d00-acad-11eb-8b75-fc69fb3595f7.png)
**Mobile:**
![image](https://user-images.githubusercontent.com/61147963/116965322-caff9800-acad-11eb-8f49-ef6bbadcc869.png)
For bundle attribute type the attribute name appears _**after every value**_
![image](https://user-images.githubusercontent.com/61147963/116965398-fc786380-acad-11eb-8794-cccfaed94a0b.png)

**Comment by JayEmKay-8** [comment]
I retested on the team server, it all looks fine.
