### ISSUE TITLE
Unable to edit budget

### ISSUE THREAD

**Issue by ymirek** [SAP/spartacus#10631]
**Describe the bug**
When trying to edit a budget from my-company it fails with this console error:

```
core.js:4442 ERROR TypeError: Cannot read property 'pattern' of undefined
    at isValidFormat (spartacus-storefront.js:13452)
    at spartacus-storefront.js:16933
    at forms.js:1190
    at Array.map (<anonymous>)
    at M (forms.js:1190)
    at forms.js:1144
    at forms.js:1190
    at Array.map (<anonymous>)
    at M (forms.js:1190)
    at forms.js:1144
```

**Tell us the version of Spartacus**
- Library version: 3.0.0

**To Reproduce**
1. Powertools storefront
2. Log in as linda.wolf@rustic-hw.com
2. Go to My Company 
2. Click on Budgets
3. Select any budget
4. Click on 'Edit'
3. Button is grayed out. Console error logged.

**Expected behavior**
Budget Form opened

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chome, Firefox
 - Version: Chrome: 87.0, Fx: 84.02

**Comment by ymirek** [comment]
![image](https://user-images.githubusercontent.com/1064461/104012058-73459a00-51af-11eb-87cd-1aeceb40c84c.png)

**Comment by Xymmer** [comment]
to dev: repro first to see if it's still happening

**Comment by ren-tham** [comment]
Unsuccessful at recreating bug. Tried both on chrome and firefox running latest version of develop as of this date. Closing issue.

Setup used: 
OS: Windows
Chrome: 87.0.4280.141 
Firefox: 84.0.2
