### ISSUE TITLE
Unable to access product/ID routes

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#10637]
When building Spartacus in production mode and serving it using either pm2 or nginx, routings like /product/123 are not accessible.

It seems that routing configuration from app.module.ts is not being propagated correctly.

**Comment by tobi-or-not-tobi** [comment]
Isn't this because of a lack of a rewrite rule? If there' no rewrite rule available, then there's no matching filesystem _route_.

Perhaps use `pm2 serve --spa`.

**Comment by hackergil** [comment]
`pm2 serve --spa` works. Thanks Tobi.
