### ISSUE TITLE
SSR rendering exceeded timeout, fallbacking to CSR for (all routes)

### ISSUE THREAD

**Issue by j-caroco** [SAP/spartacus#10638]
**Describe the bug**
Hello Spartans, I created a new angular project and ran the following command:
`ng add @spartacus/schematics --baseUrl https://spartacus-demo.eastus.cloudapp.azure.com:8443/ --baseSite=electronics-spa --ssr` , from https://sap.github.io/spartacus-docs/schematics/ .

![image](https://user-images.githubusercontent.com/69797431/104039388-39d05700-51ce-11eb-9b07-3a8750b61ce0.png)

After, I ran the command `npm run dev:ssr`, opened http://localhost:4200 and found the following problem:

![image](https://user-images.githubusercontent.com/69797431/104039509-5f5d6080-51ce-11eb-985c-952f0daac20f.png)

The app is running as Client Side Rendering instead of Server Side Rendering. On my main project, I get the same warning per route.

![image](https://user-images.githubusercontent.com/69797431/104040438-8d8f7000-51cf-11eb-9468-36eafba1f9fd.png)

**Tell us the version of Spartacus**
- Library version: v3.0.0
- node:  v12.18.4
- npm: v6.14.6
- angular/cli: v10.1.4

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Browser: All browsers

**Comment by plabadie** [comment]
I can repro with local Spartacus 3.0 installed via schematics.

App logs:

```
$ yarn serve:ssr
yarn run v1.22.5
$ node dist/mystore-ssr/server/main.js
Node Express server listening on http://localhost:4000
SSR rendering exceeded timeout, fallbacking to CSR for /
```

Home page source:
```
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>MystoreSsr</title>
  <base href="/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/x-icon" href="favicon.ico">
  <meta name="occ-backend-base-url" content="https://localhost:9002" />
<link rel="stylesheet" href="styles.8f40ba48bbc130edcc42.css"></head>
<body>
  <app-root></app-root>
<script src="runtime.f8acce36d38b4573bc3e.js" defer></script><script src="polyfills.6deb0458455058a2c80b.js" defer></script><script src="main.8ca76b8ce48dc591425d.js" defer></script></body>
</html>
```

**Comment by dunqan** [comment]
it's a side effect of a new of SSR optimization feature available in Spartacus 3.0 and up. 

It is possible to either extend the timeout in `server.ts` (passing a second parameter to `NgExpressEngineDecorator.get` method) or set it to 0, so it won't be fallbacking to CSR at all. Here is an example:

```
const ngExpressEngine = NgExpressEngineDecorator.get(engine, { timeout: 0 });
```

You can use API documentation to get a list of available options:
https://sap.github.io/spartacus/interfaces/SsrOptimizationOptions.html

Additionally, an extended documentation regarding this feature and best practices is on its way

**Comment by timothy2005** [comment]
I encountered same issue, but changing timeout does **not** help!

The root cause is: the certificate of Commerce Cloud is invalid, as it is self-assigned.
Because I am using local commerce, with URL: localhost://9002

And the workaround is:

Add below config to package.json

```
"scripts": {
    "dev:ssr": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 ng run mystore:serve-ssr",
},
[...]
"devDependencies": {
    [...]
    "cross-env": "^7.0.0"
}
```

Then run following to start Spartacus
`yarn dev:ssr`

**Comment by dunqan** [comment]
Hi @timothy2005 , yes, you are right, this can also be a reason.

In case there is no proper SSL certificate on the backend, rendering is either not finished or will time out because all requests will fail, thus resulting in CSR fallback if SSR optimization is enabled (or SSR render fail otherwise).
