### ISSUE TITLE
CheckBoxListProduct mobile styling looks odd

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10657]
**repro**
- reduce browser window to simulate mobile device with small screen (or simualte via dev tools, see screenshot)
- configure 'Configurable Camera Bundle'
- go to group 'Accessories'
**issue**: screen looks broken. text is not readable
![image](https://user-images.githubusercontent.com/53090888/104224020-ac4a6c80-5444-11eb-926b-d58823d1f51f.png)

**Comment by Uli-Tiger** [comment]
@luklus looks better now, but still there is some space missing on left hand side. ![image](https://user-images.githubusercontent.com/53090888/104348627-3c022080-5502-11eb-8918-edab5abd0220.png)

generally also the buttons are not centered on the mobile. you can see this in the first group

![image](https://user-images.githubusercontent.com/53090888/104349517-4f61bb80-5503-11eb-8182-741279cdcef7.png)

the buttons of the product card component are not aligned with the other buttons (previous / next / addtoCart)

**Comment by luklus** [comment]
fixed 
![Zrzut ekranu 2021-01-13 090200](https://user-images.githubusercontent.com/12393718/104423192-1581cb00-557e-11eb-9d9a-25c3ac2d4c3e.png)
