### ISSUE TITLE
CheckBoxListProduct quantity is reset to 1 after deselecting and re-selecting

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10655]
**repro**
- configure 'Configurable Camera Bundle'
- go to group 'Accessories'
- add any tripod
- increase quantity e.g.: '2'
- remove the Tripod
- re-add the same tripod

**issue**: Quantity is still '2'.
**expected**: quantity shall be 1

see also: https://4prsat.axshare.com/#id=68anbn&p=bundling_multi-select_qtybox&g=1

`If a user removes a bundle item that has a quantity entered greater than '1' and subsequently RE-selects (restores) the same bundle item, the default value of '1' shall appear in the quantity box (A). The previously entered quantity value is not restored.`

**Comment by luklus** [comment]
@Uli-Tiger on develop we don't have deployed yest changes from #10372 task, i implement there dataType. It determines whether the product has quantity options turned on or off. In the case you are writing about, the Tripod has value dataType = 'N/A', so quantity should not be available, hence probably this error occurs (#10372 fix it). BTW: all quantity values come from response, so on the front we only assign them to a specific product

**Comment by Uli-Tiger** [comment]
ok - will retest after #10372 is merged/deployed
