### ISSUE TITLE
UI Types - handle deselect when attribute is required (quantity actions included)

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10656]
**repro**
- configure 'Configurable Camera Bundle'
- add any 'Memory Card'
- right now you are not allowed to remove it, as the attribute is mandatory and you only add one option so far. consequently remove button and minus sign of quantity input are disabled. 
- enter the quantity field and enter '0' or press backsapace to remove quantity. 

**issue**: the memory card is deselected

**expected**: quantity shall remain 1 (or whatever is currently entred)

**Comment by luklus** [comment]
fixed in #10372 
now when user set 0, item is removed

**Comment by Uli-Tiger** [comment]
ok - will retest after #10372 is merged/deployed

**Comment by Uli-Tiger** [comment]
issue still exists as described after deploying  #10372

**Comment by luklus** [comment]
https://user-images.githubusercontent.com/12393718/104730134-c41e3b00-5739-11eb-900d-84773276a422.mp4

**Comment by Uli-Tiger** [comment]
The memory card attribute is mandatory, indicated by the **red asterisk**. The behaviour within the video would be expected/ok for **non**-mandatory attributes.

**Comment by luklus** [comment]
TODO:

- [x] set minimum quantity to 1 when attribute is required
- [x] set minimum quantity to 0 when attribute in no required
- [x] can't remove selection when attribute is required
- [x] can remove selection when attribute in no required

Components

- [x] Checkbox Product
- [x] Radiobutton Product
- [x] Checkbox List

**Comment by luklus** [comment]
Example, when attribute is required, then no required:

https://user-images.githubusercontent.com/12393718/105002208-312f1a80-5a31-11eb-8684-fd27c603a846.mp4
