### ISSUE TITLE
Quantity Input (all bundle Ui types) - not able to enter 2 (or more) digits amount

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10652]
This issue occurs quantity inputs of all bundle types (dropdownProduct, radioGroupProduct and checkBoxListproduct). 

**repro:**
- configure 'Configurable Camera Bundle'
- go to group 'Accessories'
- add any 'Tripod'
- click into quantity input and try to type in eg: '25'

**Issue**: this results typically in value '2', because a request is fired as soon as you type and you loose the focus.

ideally there should be some delay before firing the change event, so that you can enter a also several digits.

similar issue happens, if i use backspace to delete the current input. before i can enter a new quantity the whole stepper disappears, as  item is considered deselected.

**Comment by luklus** [comment]
fixed in #10372
debounce added to quantity component

**Comment by Uli-Tiger** [comment]
ok - will retest after #10372 is merged/deployed
