### ISSUE TITLE
Exception mapping changing for 2105 - update our interpretation of OCC response messages

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#10658]
Certain messages returned by OCC were updated for 2105.
Summary: Exception messages no longer specifically mention types or classes.

For backwards compatibility, you can set 2105 to pass through messages like 2011 or earlier.
Must use 2105 server with messages setting set to new messages.

The goal of this ticket is to update our message handling so that there are no problems with before using either messaging configuration.

e.g.
![image](https://user-images.githubusercontent.com/4998145/107638048-0d7c8000-6c3d-11eb-8ec9-13267ef885eb.png)

More info: https://cxjira.sap.com/browse/C5-25

**Comment by giancorderoortiz** [comment]
@bgambocjaviniar fyi

**Comment by LTiger14** [comment]
Investigated with @bgambocjaviniar and found that the message text does not affect Spartacus as we aren't relying on it.
