### ISSUE TITLE
Spartacus Demo Site does not work

### ISSUE THREAD

**Issue by Horus360** [SAP/spartacus#10692]
Hi Team,

I was going through the spartacus document on the github repo. In one of the Points there is a URL which redirects to the **sample Spartacus Storefront**. The URL provided is as follows 

> https://spartacus-demo.eastus.cloudapp.azure.com/

On opening the website it displays an empty page. On checking the browser console it displays the below provided error 

> Error: Cannot get base site config! Current url (https://spartacus-demo.eastus.cloudapp.azure.com/) doesn't match with any of url patterns of any base site.

Do you guys have the correct URL?

**Comment by Xymmer** [comment]
we're looking into fixing this, but for now https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/ works
it's because we're trying to use same domain for different sites
