### ISSUE TITLE
Simplify the HTML structure

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10702]
Look through all new UI components (***.html** files) and coreesponding styling (***.scss** files) and scrutinize  / simplify the DOM structure and styling where it's possible 

New/changed components:
- [x] single select dropdown bundle: No simplification needed
- [x] single select bundle
- [x] multi select bundle
- [x] attribute quantity
- [x] product card

**Comment by schuppell** [comment]
In Multi select Bundle:
Line 5-18.
Should not be part of the DOM, when it is not needed (no attribute qty only value qty and no price which will displayed)

**Comment by schuppell** [comment]
In Single select bundle:
Line 13-16.
Should not be part of the DOM, when it is not needed.

**Comment by schuppell** [comment]
In Single select Bundle SCCS.
It expects a specific class inside the quantity component.
Change .cx-quantity to cx-configurator-attribute-quantity. See multi select bundle

**Comment by schuppell** [comment]
Some component styling is wrapped in an  &:not(:empty)  wrapper.
This is not needed and could be removed
