### ISSUE TITLE
[needs triage] Module not found: Error: Can't resolve '@spartacus/core/src/site-context/services/site-context-params.service'

### ISSUE THREAD

**Issue by adriankremer** [SAP/spartacus#10707]
The documentation says that if one want's to use the StatePersistenceService, one has to use the SiteContextParamsService Injectable to set the current SiteContext. https://sap.github.io/spartacus-docs/state-persistence/

Importing the SiteContextParamsService results in errors, since it is not exported.

```
import { Component, ViewEncapsulation } from '@angular/core';
import { BASE_SITE_CONTEXT_ID } from '@spartacus/core';
import { SiteContextParamsService } from '@spartacus/core/src/site-context/services/site-context-params.service';

@Component({
	selector: 'app-root',
	templateUrl: './app.component.html',
	styleUrls: ['./app.component.scss'],
	encapsulation: ViewEncapsulation.None,
})
export class AppComponent {
	constructor(siteContextParamsService: SiteContextParamsService) {
		siteContextParamsService.getValues([BASE_SITE_CONTEXT_ID]);
	}
}
```

Am I doing something wrong?
(by the way thanks for spartacus)

**Comment by marlass** [comment]
`SiteContextParamsService` was added to public API in 3.2.0 release, so there shouldn't be problems now with referencing it.
