### ISSUE TITLE
Qty for simple checkbox: '0' should deselect

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#10709]
1) According to wireframes a selected checkbox should be deselected if value is set to '0':
![Screenshot 2021-01-14 at 16 49 45](https://user-images.githubusercontent.com/54309425/104614854-eb68ff80-5688-11eb-936d-bbb9704ebf16.png)

This is not working: Decrease to 0 not possible. Although manually entering 0 will lead to 1.

**Comment by luklus** [comment]
fixed


https://user-images.githubusercontent.com/12393718/104729938-7efa0900-5739-11eb-8ac4-07b798203394.mp4
