### ISSUE TITLE
Category code in product search page

### ISSUE THREAD

**Issue by fernandadasneves** [SAP/spartacus#10714]
When selecting the product category, the breadcrumb for it appears with a code and not the name of the category.
The product page appears correctly.

Spartacus Version: 3.0.0

Go to Menu Navigation
Click on any category
See the breadcrumb with the category code
Expected behavior:
It should appear as the product page the name of the category.

Screenshots:
Category page:
image
![image](https://user-images.githubusercontent.com/75036418/104716085-b2339c80-5727-11eb-9051-10db09fd00f3.png)

Product page:
image
![image](https://user-images.githubusercontent.com/75036418/104716073-ae077f00-5727-11eb-95ef-ed2608785211.png)

Desktop:
OS: Windows
Browser: Chrome, Edge
Version: last version

Smartphone:
Device: Android / IOS actual versions
OS: Actual Version
Browser chrome / safari
Version Actual versions

**Comment by fernandadasneves** [comment]
hello,

any feedback?

**Comment by Xymmer** [comment]
hi @fernandadasneves , could you post the results of the occ api call? i.e. is the code or the text being returned?

**Comment by fernandadasneves** [comment]
Hi Xymmer,  thank you for the feedback.
we tried in Spartacus demo store and it displays the same:
I've clicked in "Sanders" and in the up of the screen appears the category number also:
![image](https://user-images.githubusercontent.com/75036418/105061712-1cc34000-5a7a-11eb-9ac7-5ec59276473e.png)

please see the link below:
https://spartacus-demo.eastus.cloudapp.azure.com:444/powertools-spa/en/USD/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Sanders/c/1596

**Comment by Xymmer** [comment]
upon investigation, the occ call is not returning the brand name. we're requesting a fix for backend (https://cxjira.sap.com/browse/CLC-2482).

more info:
in b2c we get this:
![image](https://user-images.githubusercontent.com/4998145/105499681-d7785b80-5c8f-11eb-825f-b69594dbd0de.png)
but for b2b products we get this:
![image](https://user-images.githubusercontent.com/4998145/105499723-e3fcb400-5c8f-11eb-9429-c81a2896245c.png)

**Comment by robertobarreto** [comment]
Hi, we have opened a issue in SAP "128535/2021 Category code in product search page". It has been addressed to the internal SAP Dev team and we are waiting for their feedback.

**Comment by giancorderoortiz** [comment]
We no longer see this issue in demo server. 
Spartacus 3.0. 
Same link as above: https://spartacus-demo.eastus.cloudapp.azure.com:444/powertools-spa/en/USD/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Sanders/c/1596

![Screen Shot 2021-06-06 at 11 17 46 AM](https://user-images.githubusercontent.com/46171897/120929916-fca6bd00-c6b8-11eb-8232-8213dd860786.png)

Re-open issue if necessary
