### ISSUE TITLE
improve coverage for new and modified ui components

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10713]
to measure coverage run
ng test product-configurator --code-coverage
you will find the deatiled report here:
spartacus/coverage/product-configurator/lcov-report/index.html
the following ui componets need for tests:
* product-configurator/rulebased/components/attribute/types/checkbox-list (methods added for quantity change are not covered)
* product-configurator/rulebased/components/attribute/types/drop-down  (methods added for quantity change are not covered)
* product-configurator/rulebased/components/attribute/types/multi-selection-bundle 
* product-configurator/rulebased/components/attribute/types/radio-button  (methods added for quantity change are not covered)
* product-configurator/rulebased/components/attribute/types/single-selection-bundle
* product-configurator/rulebased/components/attribute/types/single-selection-bundle-dropdown

especially the code regarding quantity handling across  the different components looks quite similar. in some case it might be worth to refactor this to reduce duplication and write tests only once. But this might not be worth/possible in all cases. Haven't checked it in detail.
![image](https://user-images.githubusercontent.com/53090888/104713984-e6f22480-5724-11eb-9729-0b4197267cf2.png)

**Comment by luklus** [comment]
Add some test. Actual state: 98.88% Statements 92.3% Branches 98.47% Functions 98.92% Lines 2644/2673

![Zrzut ekranu 2021-01-19 123330](https://user-images.githubusercontent.com/12393718/105029405-9e9f7300-5a52-11eb-9a89-f773bb0678bb.png)
