### ISSUE TITLE
Handle deprecation of getBaseEndpoint from OccEndpointsService

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10728]
**Must be done in 4.0**

In 3.2 `getBaseEndpoint` from `OccEndpointsService` was deprecated in favor of `getBaseUrl`.

The `getBaseUrl` can be used instead of `getBaseEndpoint` with the same parameters and will return the same value.

### Acceptance

- Usages of `getBaseEndpoint` are replaced with `getBaseUrl`
- Behaviors remain the same
- Delete the `getBaseEndpoint` function

**Comment by ren-tham** [comment]
Similar deprecation already under review: https://github.com/SAP/spartacus/pull/12213/files

Will be adding my contributions on top of this branch.

**Comment by ren-tham** [comment]
PR: (#12215)

Related to: (#12213)
