### ISSUE TITLE
[Wait until checkout library is merged] Replace usage of getEndpoint with configurable endpoints

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10727]
**Must be done for 4.0**

As part of 3.2 the `getEndpoint` method in `OccEndpointsService` was deprecated. 

For 4.0 the usage of this method should be removed. The `getEndpoint` is usually used in places where the url strings are hard codded rather than using configurable endpoints.

The `getEndpoint` method should be replaced with `buildUrl` and configurable endpoints.

### Acceptance

- No more usage of `getEndpoint` from `OccEndpointsService`
- The usages have been replaced with `buildUrl` from `OccEndpointsService` and the usage of configurable endpoints
- If no configurable endpoints exist for some of those URLs, create them
- Delete `getEndpoint` method

**Comment by LTiger14** [comment]
This might conflict with the checkout library initiative. Make sure to coordinate with @plabadie.

**Comment by saad-mo** [comment]
The majority of the changes for this ticket are related to checkout. It's best to wait on this until checkout lib is merged. 

![Screen Shot 2021-05-11 at 2 47 31 PM](https://user-images.githubusercontent.com/15215400/118005209-cbcca580-b30f-11eb-82d4-08c410ea11ba.png)
