### ISSUE TITLE
Foundation for migration mechanism for 4.0

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#10721]
Let's created the schematics update mechanism for Spartacus 4.0 version so the current development can be extended with migration part of DoD.

As a reference, the previous foundation task is here:
https://github.com/SAP/spartacus/issues/9495

**Comment by mirkosoft** [comment]
As greed with @marlass let's put it on hold until being close to releasing 4.0. To handle DoD let's follow the below approach:
- you don't see config file -> you create it
- before 4.0 we create the general migration.json files and configure versions
Example of actual PR with migration DoD handled: https://github.com/SAP/spartacus/pull/10688/files (see files under `projects/schematics`)

**Comment by marlass** [comment]
Basic configs copied and doc for migration info also already present.
