### ISSUE TITLE
Handle deprecation of getUrl

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#10729]
**Must be done for 4.0**

In 3.2 the `getUrl` method from `OccEndpointsService` was deprecated and replaced by `buildUrl`.

Find and replace all usages of `getUrl` in the project. Since there are many, this ticket can be split into sub-tasks.

### Acceptance
- [x] All `getUrl` method from `OccEndpointsService` is replaced with `buildUrl`
- [x] Delete the `getUrl` method
- [x] Update the schematics automated migration for `OccEndpointsService`

**Comment by saad-mo** [comment]
All three tasks are now merged into a single PR - #12282
