### ISSUE TITLE
Improve styling for quantity

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10763]
Define mixin for the qunatity and reuse it.
Check that the styling everywhere the same is.

**Comment by Uli-Tiger** [comment]
@Larisa-Staroverova : there is an issue with styling of quantity on attribute level for mobile screen sizes. There is some padding missing.
![image](https://user-images.githubusercontent.com/53090888/105826521-250f0400-5fc1-11eb-8d9f-1fb4915d2ad4.png)
