### ISSUE TITLE
In case the corresponding commerce product is not found, still show product id retuned from CPQ on the UI.

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10773]
**repo**
- configure camera bundle
- go to attribute lenses

**issues**
2 lenses are displayed, but it should be 5. However 3 lenses are not found in commerce (404). In such a case it is expected, that we still display the product id, the placeholder for the image, price & quantity , but no description and  no link to catalogue.
![image](https://user-images.githubusercontent.com/53090888/105052416-2647aa80-5a70-11eb-9f6c-ed63481e066c.png)

**these lenses are expected**
```{
	"values": [
		{
			"paV_ID": 8717,
			"productSystemId": "CANON_RF_24-105MM_F/4L_IS_USM",
			"selected": true,
			"valueDisplay": "Canon RF 24-105mm f/4L IS USM",
			"quantity": "1",
			"description": "",
			"price": "1500.00",
		},
		{
			"paV_ID": 8718,
			"productSystemId": "SIGMA_85MM_F1.4_DG_HSM",
			"selected": false,
			"valueDisplay": "Sigma 85mm F1.4 DG HSM",
			"quantity": "1",
			"description": "",
			"price": "800.00",
		},
		{
			"paV_ID": 8719,
			"productSystemId": "TAMRON_SP_15-30MM_F/2.8_DI_VC_USD",
			"selected": false,
			"valueDisplay": "Tamron SP 15-30mm F/2.8 Di VC USD",
			"quantity": "1",
			"description": "",
			"price": "750.00",
		},
		{
			"paV_ID": 8720,
			"productSystemId": "TAMRON_18-200MM_F/3.5-6.3_DI_II_VC",
			"selected": false,
			"valueDisplay": "Tamron 18-200mm F/3.5-6.3 Di II VC",
			"quantity": "1",
			"description": "",
			"price": "750.00",
		},
		{
			"paV_ID": 8721,
			"productSystemId": "NIKON_AF-P_DX_NIKKOR_70-300MM_1:4.5-6.3",
			"selected": false,
			"valueDisplay": "Nikon AF-P DX NIKKOR 70-300mm 1:4.5-6.3 G ED VR",
			"quantity": "1",
			"description": "",
			"price": "700.00",
		}
	]
}`''

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-21 120024](https://user-images.githubusercontent.com/12393718/105342160-4eeeb200-5be0-11eb-9e97-9c7522d43319.png)

**Comment by Uli-Tiger** [comment]
@luklus : Can you remove the link to the product details in commerce, in case the product is not found in commerce?

**Comment by Uli-Tiger** [comment]
should not be a link, only text
![image](https://user-images.githubusercontent.com/53090888/105489540-ab6ed180-5cb3-11eb-8113-b6cb773b8a72.png)

**Comment by luklus** [comment]
FIXED: No more link for no found commerce product
