### ISSUE TITLE
Attribute Price on OV is missing currency sign and quantity

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10772]
**repro**
- configure camera bundle
- add for exmaple memory card 'SanDisk Extreme Pro 128GB SDXC' with quantity 2
- go to overview

**issue**
only the price value diplayed, but not quantity/currenxy
it should be something like:  2 x 37,99€ = 75,98€

check with @AlexanderKuschner which fields contain the formatted prices.
![image](https://user-images.githubusercontent.com/53090888/105048051-65bfc800-5a6b-11eb-8ed0-f5292c70d930.png)

PS: Guess the corresponding dev task was done before, we updated the concept how to populate and format prices, so that's why its now not working. Anyways we need to fix/Update it.

**Comment by kacperknapik** [comment]
Closed in #10482
