### ISSUE TITLE
[Major] Cart integration does not work in ASM scenario

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#10787]
The product configurator scenarios don't work in the ASM scenario for 2 reasons:

- SPA: In case user is logged in, the actual cart user is not properly sent to the backend (for that we need to make use of  userIdService.getUserId()
- Commerce backend: Some security related access checks fail, because they don't allow the agent user to retrieve a configuration. That's valid for the Variant Configurator only.

How to reproduce: Login as asagent, start a session for and end-user. The addToCart process fails with a 400'er exception from the backend.

If this is fixed, the ASM scenario works fine for the textfield configurator

**Comment by Platonn** [comment]
If the AS agent doesn't add any _configurable_ product to cart, is he able to see the cart page and successfully checkout in the name of the normal user?
If he tries to add any product to cart and occ call fails, will he be able to checkout successfully with other remaining products?

**Comment by ChristophHi** [comment]
> If the AS agent doesn't add any _configurable_ product to cart, is he able to see the cart page and successfully checkout in the name of the normal user?

Yes, of course. The issue is only for configurable products
