### ISSUE TITLE
MultiCartStatePersistenceService isn't extensibility

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#10793]
I want to extend MultiCartStatePersistenceService and replace initSync method, but I can't because injected SiteContextParamsService doesn't have public export

And I need public export for SiteContextUrlSerializer because I need fix  problem with working basesites getting from backend and isn't in context config 

- Library version: 3.0

**Comment by alvteren** [comment]
@tobi-or-not-tobi can you help? it is very important

**Comment by alvteren** [comment]
If I copy service in my project, I have issue with next services SiteContextRoutesHandler, because it doesn't have public export

**Comment by Xymmer** [comment]
Can we fix in 3.1? and definitely for 3.2.

**Comment by marlass** [comment]
I'll backport it to 3.2 and to latest 2.x version. I think we can skip 3.1
