### ISSUE TITLE
Calculation number of issues on Overview Page is wrong

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10829]
The **Resolve issues banner** is displayed at the Overview page and in the cart.
For detailed analysis have a look at the implementation in the component: `feature-libs/product-configurator/common/components/configurator-issues-notification`

**Comment by Uli-Tiger** [comment]
needs some more analysis:
I see in OV-Normalizer, that the whole list of incomplete attributes is returned and it's length is used to set the total NumberOfIssues. Not sure what the UI component is displaying, though.
