### ISSUE TITLE
Quantity value should be fixed for required attribute for simple & bundle radio buttons / ddlb

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10827]
The quantity value should be set to **1** for the required bundle radio buttons (**DONE**) / ddlb without any value selected

The quantity value should be set to **zero** for the not required simple radio buttons (**DONE**) / ddlb without any value selected

![image](https://user-images.githubusercontent.com/61147963/105480348-ec5fe980-5ca5-11eb-9a23-ee71cbd387e3.png)

**Comment by luklus** [comment]
FIXED

![Zrzut ekranu 2021-01-22 123839](https://user-images.githubusercontent.com/12393718/105486493-dd316980-5cae-11eb-9a40-8078e19f1a89.png)
