### ISSUE TITLE
it shoul be possible to set quantity to zero by entering zero or clicking on "-" for not required attribute for simple & bundle ddlb

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10830]
After testing on CCV2 landscape came to the conclusion that it does not for for bundle drop-down list: 
Search for **ONA The Camps Bay** product 
Go to **DDLB Bundle** group
Search for **DDLB_BND_QA_NR** attribute
Select any value and try to deselect a value by entering zero or clicking '-' : 
![image](https://user-images.githubusercontent.com/61147963/105703426-7f4e8d00-5f0d-11eb-80fd-4fa3a4806fbe.png)

**Comment by luklus** [comment]
FIXED

![Zrzut ekranu 2021-01-22 120111](https://user-images.githubusercontent.com/12393718/105483094-98570400-5ca9-11eb-9613-e2e8fac90326.png)

![Zrzut ekranu 2021-01-22 120131](https://user-images.githubusercontent.com/12393718/105483098-98ef9a80-5ca9-11eb-942c-1c5693be0403.png)
