### ISSUE TITLE
Implement term pairs for buttons: select/deselect and add/remove

### ISSUE THREAD

**Issue by JayEmKay-8** [SAP/spartacus#10836]
Current implementation: 
- for single-select, buttons show select/remove
- for multi-select, buttons show add/remove

**Desired behavior:** 
- for single-select, buttons show **select/deselect** 
   (Note that for mandatory attributes, no "deselect" button appears as the value can only be deselected by choosing a different value. This is dealt with in the following issue: https://github.com/SAP/spartacus/issues/10838).
- for multi-select, buttons show **add/remove**.

Note that this was communicated incorrectly at one point and therefore not implemented in the desired way. Also, wires/visuals were inconsistent in this respect.

We have now confirmed and re-confirmed the desired behavior as described above with our UX designer.
See correct wire: https://4prsat.axshare.com/#id=a8e46l&p=bundling_single-select_w_retract&g=1
Wire for mandatory single-select where there is no "deselect" button: https://4prsat.axshare.com/#id=yi2o3p&p=bundling_single-select_mandatory&g=1

**Comment by luklus** [comment]
FIXED

![Zrzut ekranu 2021-01-22 142244](https://user-images.githubusercontent.com/12393718/105496121-59cb4480-5cbd-11eb-9c99-f5d558795a7a.png)

![Zrzut ekranu 2021-01-22 142300](https://user-images.githubusercontent.com/12393718/105496130-5c2d9e80-5cbd-11eb-8688-4383198ec99f.png)
