### ISSUE TITLE
Do not show "deselect" button for single-select mandatory attribute value

### ISSUE THREAD

**Issue by JayEmKay-8** [SAP/spartacus#10838]
For single-select mandatory attributes, no "deselect" button should appear after selecting the value as the value can only be deselected by choosing a different value.
See wire: https://4prsat.axshare.com/#id=yi2o3p&p=bundling_single-select_mandatory&g=1

**Comment by luklus** [comment]
FIXED

![Zrzut ekranu 2021-01-22 142300](https://user-images.githubusercontent.com/12393718/105496176-69e32400-5cbd-11eb-9e0c-3201c1454fab.png)
