### ISSUE TITLE
Overviewpage: Attribute with more than on value should be style as one Big box

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10837]
**steps**
* configure camera bundle
* select 2 or more memory cards.
* go to overview

**issue**
There is a grey boxes around each memory card. Instead it should be one big box. see the attached compare between wires/actual.

![image](https://user-images.githubusercontent.com/53090888/105485649-87a88d00-5cad-11eb-8905-0ed7b71d57fe.png)

So the grey box groups a single attribute with all of its values.Between several attributes there should be still this white space.

This should be achieved via styling. could be a bit tricky. Only do if there is simple styling solution, otherwise we will tackle this later.

**Comment by luklus** [comment]
![Zrzut ekranu 2021-01-26 131434](https://user-images.githubusercontent.com/12393718/105846010-dae74c00-5fdb-11eb-9f18-8c301bc99291.png)
