### ISSUE TITLE
Quantity should be displayed at attribute level for simple / bundle DDLB

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10831]

**Comment by luklus** [comment]
i think this components are prepared: http://localhost:4200/powertools-spa/en/USD/configure/cpq/product/entityKey/ONA_THE_CAMPS_BAY

![Zrzut ekranu 2021-01-22 114724](https://user-images.githubusercontent.com/12393718/105481689-aefc5b80-5ca7-11eb-9754-53dabd896d9f.png)
![Zrzut ekranu 2021-01-22 114747](https://user-images.githubusercontent.com/12393718/105481690-af94f200-5ca7-11eb-8d6d-deba521838df.png)

**Comment by Larisa-Staroverova** [comment]
Great!
