### ISSUE TITLE
[V1] Spacing between attributes on Overview page is to small compared to wires.

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#10841]
make some changes to the configuration, so that some attributes with values are displayed within one overview group.

**issue**
the spacing between the attributes is  to small. it is the same as between values. but as per wires it should be greater so that it is visualized which values belong to which attribute. see screenshot.

![image](https://user-images.githubusercontent.com/53090888/105487493-7f9e1c80-5cb0-11eb-9166-07e923046c86.png)

**Comment by ChristophHi** [comment]
@Uli-Tiger I cannot really link this to the current state. This is relevant only after we omit the attribute for each value, right? So does not make sense to fix this on its own
![Screen Shot 2021-01-29 at 08 02 18](https://user-images.githubusercontent.com/33626130/106242913-bae8a000-6208-11eb-8438-18f1273f3a0a.png)

**Comment by Uli-Tiger** [comment]
As you can see on your screenshot, there is a deviation from the wire frames. Independently from whether the attribute name is repeated for each value or not, there is some space missing before each attribute name to group it together with the corresponding value.
I agree though, that the issue will be even more recognizable in case the attribute name is not repeated. It might be more efficient to fix both things together, so I'm fine with postponing this until the repetition of the attribute name is fixed.

**Comment by ChristophHi** [comment]
> there is some space missing before each attribute name to group it together with the corresponding value.

No, the space is missing _after_ the attribute name if you consider the current situation. Note that attribute name comes after value.
But agree that it makes sense to do both fixes together

**Comment by Larisa-Staroverova** [comment]
This task should be solved by #11220. Plz, retest it as soon as possible.

**Comment by Larisa-Staroverova** [comment]
@Uli-Tiger, could you please retest beacuse according to the current state it looks the following way:
![image](https://user-images.githubusercontent.com/61147963/116964838-c38bbf00-acac-11eb-8a8f-ed58d7cf0bdf.png)
Do you miss more space? The space between the attributes is equal to the next group is larger

**Comment by Uli-Tiger** [comment]
yes actual state looks fine
