### ISSUE TITLE
Refactor: counter-item

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10842]
The thing is that the PO wishes that the **readonly** state of the item-counter should be greyed out:
![image](https://user-images.githubusercontent.com/61147963/105488837-90e82880-5cb2-11eb-9cb7-a416b1cea884.png)

And not like now:
![image](https://user-images.githubusercontent.com/61147963/105488704-567e8b80-5cb2-11eb-87cd-de5dfa288d57.png)

**Comment by schuppell** [comment]
Readonly should only be used when the component should be rendered as label. In our case we need to disable the component. The component offers a FormControl as input parameter. You can bind the disable attribute on the FormControl of the component in the configurator-attribute-quantity.component.
