### ISSUE TITLE
Update Search Box for Screen Readers Support 

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10886]
## This ticket is not part of the Headings and Labels effort, but some improvements will be made to the search box under #11151 

Related to [General Issues #5]( https://cxwiki.sap.com/display/spar/Analysis+for+Screen+Readers+Support)
Master Ticket #7423

**Issue:**
The search box needs more verbal feedback to describe events and controls.

**Current Narration**
- [x] No vocalization indicating suggestions are being loaded as user types. (look at walmart.com example) 
- [x] The "Search" icon is vocalized as an "empty group" with no details of how to use it and with which keys.
- [x] The "Reset" icon vocalized as an "empty group" with no details of how to use it and with which keys.

**Remediation Technique**
- [x] aria-autocomplete=”list”
- ![image](https://user-images.githubusercontent.com/15215400/105890906-90fb6780-5fd5-11eb-9688-ec6541c3b23b.png)

**Expectation**
![image](https://user-images.githubusercontent.com/15215400/105890949-9fe21a00-5fd5-11eb-96bc-9f40928b2d9b.png)

**Spike Todos:** 
- [ ] Investigate code changes to enable Screen Readers Support. note all the pages that needs updating 
- [ ] Validate breaking/non-breaking changes 
- [ ] Plan for a sprint

**Comment by developpeurweb** [comment]
The search box part of this ticket was done in PRs 12952 and 12984 so closing.
