### ISSUE TITLE
"Deselect" buttons disappeared for bundle radio button product

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#10881]
As you could see in the screenshot, the deselect button has disappeared:
![image](https://user-images.githubusercontent.com/61147963/105855574-85656c00-5fe8-11eb-9a09-07661f238779.png)

Go to **ONA The Camps Bay** product
Go to **RB Bundle** group
Select any value for **RB_BND_NQ_R**

**Comment by luklus** [comment]
@Larisa-Staroverova 
https://github.com/SAP/spartacus/issues/10836
https://github.com/SAP/spartacus/issues/10838

**Comment by ChristophHi** [comment]
Hi @Larisa-Staroverova, could you check this one? I assume it can be closed

**Comment by Larisa-Staroverova** [comment]
This behavour is correct, I will close this issue
