### ISSUE TITLE
[Master] Page Titled

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10884]
## What is Page Titled
**In a nutshell:** Descriptive page titles identify the current location **without requiring users to read** or interpret page content.

## Overview
- Success Criterion [2.4.2 A: Page Titled](https://www.w3.org/WAI/WCAG21/quickref/#page-titled)
- Related to [General Issues #3]( https://cxwiki.sap.com/display/spar/Analysis+for+Screen+Readers+Support)
- **MASTER** Ticket #11672
- [**Github label:**](https://github.com/SAP/spartacus/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y-sr%2Fpage-titled) `a11y-sr/page-titled`

## Implementation
- [x] #13539
- [x] #13556

**Comment by developpeurweb** [comment]
all tickets done
