### ISSUE TITLE
Add canonical url to pages

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#10903]
The `SeoMetaService` generates specific meta tags to the DOM that can be used by crawlers to index the page. So far, canonical URLs have not been implemented. With this ticket we create canonical URLs in the `SeoMetaService` and introduce page meta providers for some of the pages to provide the canonical page

**Comment by tobi-or-not-tobi** [comment]
QA:
- enable the canonical URL
- load a page
- confirm that the canonical URL is created on SSR
- or enable it for CSR
- test various options: 
  -  enable/disable `forceHttps`
  -  enable/disable `forceWww`
  -  enable/disable `removeQueryParams`
  -  enable/disable `forceTrailingSlash`
- test different pages
- test variant pages

**Comment by KateChuen** [comment]
Tested on develop branch (local), pointing to 2011 backend (dev 9 server). 
- Tested with CSR disabled
- Tested with CSR enabled
- - Tested with forceHttps, forceWww, removeQueryParams, forceTrailingSlash false
![Screen Shot 2021-09-29 at 10 50 18 AM](https://user-images.githubusercontent.com/45409515/135298147-3c05d362-60f7-4216-afb9-950b8e0bc3b3.png)

- - Tested with forceHttps, forceWww, removeQueryParams, forceTrailingSlash true
![Screen Shot 2021-09-29 at 10 50 47 AM](https://user-images.githubusercontent.com/45409515/135298128-1dcf5267-bafc-44ff-802d-16c9543a574b.png)

- Tested different pages
![Screen Shot 2021-09-29 at 10 42 35 AM](https://user-images.githubusercontent.com/45409515/135300046-e1a3b541-574d-4efc-bdf9-6dae9991a31d.png)
![Screen Shot 2021-09-29 at 10 30 46 AM](https://user-images.githubusercontent.com/45409515/135300050-3ebf6d23-9469-491b-8ec6-b8b5d8f612a4.png)
![Screen Shot 2021-09-29 at 10 30 21 AM](https://user-images.githubusercontent.com/45409515/135300051-2cd5654e-755f-4e57-a26e-410ff955ed1a.png)
![Screen Shot 2021-09-29 at 10 30 05 AM](https://user-images.githubusercontent.com/45409515/135300053-433ed371-a64e-465e-a6f5-a8bd9f64303b.png)
![Screen Shot 2021-09-29 at 10 29 48 AM](https://user-images.githubusercontent.com/45409515/135300054-c91b0902-d3eb-48ec-8b30-0dcc984db1ce.png)
![Screen Shot 2021-09-29 at 10 29 23 AM](https://user-images.githubusercontent.com/45409515/135300055-60420284-55a1-4f3e-801e-302623902b62.png)
![Screen Shot 2021-09-29 at 10 44 35 AM](https://user-images.githubusercontent.com/45409515/135300139-29e30590-0e4e-4ff3-bea1-e85ed6685d78.png)
![Screen Shot 2021-09-29 at 10 43 37 AM](https://user-images.githubusercontent.com/45409515/135300141-29917879-5f86-4469-be9a-6b1c778a4294.png)

**Comment by KateChuen** [comment]
Tested on ssr on dev9 server
![Screen Shot 2021-09-30 at 9 52 21 AM](https://user-images.githubusercontent.com/45409515/135468388-786b6788-f734-4d0d-8e83-c93f84c973fe.png)
