### ISSUE TITLE
Spartacus 3 infinite loop in checkout

### ISSUE THREAD

**Issue by micaelr95** [SAP/spartacus#10909]
**Describe the bug**
During checkout, Spartacus stays in an infinite loop and deletes the cart. The cart component also breaks and just stays blank screen. It's also not possible to proceed to the next step in the checkout.

**Tell us the version of Spartacus**
- Library version: 3.0.1

**To Reproduce**
1. Add a product to the cart
2. Go to the cart and start the checkout process
3. Press the back button until you are back in the cart
4. Refresh the page
5. Start checkout again

**Expected behavior**
Do the complete checkout and finish the order

**Screenshots**

![Screenshot 2021-01-27 at 18 02 03](https://user-images.githubusercontent.com/12500655/106033552-c5505000-60c9-11eb-8159-74146c029fdb.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sur
 - Browser: Chrome, Safari
 - Version 88

**Additional context**
This issue was tested with B2B in the demo Spartacus API

During my testing I checked Redux Dev Tools and noticed that the cart is deleted before completing the checkout, and most of the times is deleted in the first step of the checkout and the products are deleted and the cart component breaks and I need to clean the local storage to make the cart work again

**Comment by Xymmer** [comment]
to dev: try to repro first

**Comment by dydome** [comment]
@Xymmer @micaelr95 I tried to repro this issue couple of times but without success. I used MacOS with Chrome and also on Windows with Chrome, also used the latest develop version. As was suggested I also verify Redux Dev Tool I recognizes remove cart action only on the last step - placing order.

@micaelr95 may you please verify it once again?

**Comment by micaelr95** [comment]
I can't replicate the bug again so I'm going to close this issue for now. Thanks for your time @dydome
