### ISSUE TITLE
Adjust types in WindowRef

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10906]
To make users more aware that `nativeWindow` will be undefined in `SSR` we need to adjust types in `WindowRef` and add tsdoc comment better describing when `nativeWindow` can be safely accessed.

**Comment by marlass** [comment]
QA steps:
- everything works as previously
- `WindowRef.isBrowser` returns true in browser and false in SSR

**Comment by KateChuen** [comment]
Agreed with Marcin that no QA needed on this ticket in the end. Moving it to Done.
