### ISSUE TITLE
Clean up constructors after #10945

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#10946]
https://github.com/SAP/spartacus/issues/10945 added dependencies to existing components. Let's drop the deprecated versions in next Major and make the previously-optional dependencies required in classes:
- ProductListItemComponent
- ProductGridItemComponent
- CartItemComponent

Some new components were added in https://github.com/SAP/spartacus/issues/10945, but they could not claim a new class `CartItemContext` as required (because customers may have not provided it in their custom cart item component). But in Major we cas make `CartItemContext` a required dependency, in components:
- ConfiguratorIssuesNotificationComponent
- ConfiguratorCartEntryInfoComponent

**Comment by bgambocjaviniar** [comment]
PR: GH-12355
