### ISSUE TITLE
Redirects after login not working correctly with 401 on cms requests.

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#10977]
### Problem

When `access_token` expires before navigation first request that will fail will be request for cms page.
In this case after user will complete login, he won't be redirected to expected page. It won't be registered by guards, because for them to kick in we need to first load cms page.

### Steps to reproduce

1. Login
2. Go to any page eg. address_book
3. Temper with your access_token in local storage
4. Refresh page
5. Login
6. Redirect will happen to homepage instead of previous page (eg. address_book)

**Comment by marlass** [comment]
Few things already found:
- `handleExpiredToken` can emit empty object without `access_token`. It shouldn't emit incorrect values. The stream can be closed instead. This causes one more 401 call.
- cms page requests can be done without `Authorization` header (should we don't catch these requests with auth interceptor?)

**Comment by marlass** [comment]
Problem with interceptors also seems responsible for https://stackoverflow.com/questions/65905877/spartacus-3-session-expired-error-on-logout this bug. We request page `not-found` with token and that causes extra error message and redirect to login page.

**Comment by Platonn** [comment]
The fix requires breaking changes, so will be implemented in 4.0 only.
