### ISSUE TITLE
Multiple load user data

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#10980]
**Describe the bug**
I use method `get()` of UserService in few components and after login I have few calling method `load()`

**Tell us the version of Spartacus**
- Library version: 3.0

**Screenshots**
![image](https://user-images.githubusercontent.com/17045072/106643361-ad317280-659a-11eb-9a7d-4613aa34d34a.png)

**Comment by Xymmer** [comment]
check if this is still happening, close if not

**Comment by Xymmer** [comment]
moved this one to https://jira.tools.sap/browse/CXSPA-302
but keeping this ticket open to update when resolved

**Comment by Xymmer** [comment]
note that we could not repro. closing but let me know if you can repro in latest releases.
