### ISSUE TITLE
Update Navigation to support Screen Readers

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#10991]
### This ticket is Not Part of the Headings and Lables effort, but a deeper dive into overall improvements for the Navigation 

Related to General Issues #3
Master Ticket #7423

**Issue:**
is reflected as H5s in the SR Rotor and Elements List Dialog, this skips many heading levels. Review the navigation approach for Accessibility.

**Current Narration:**
- Indication of how many items are contained in the menus are flawed, in all 3 menus says it contains 2 items, when in reality only the first menu "Brands" contains 2 items, while Digital Cameras has 3 items and Accessories has 9 items.
- There is no mention that the menu is collapsed and which keys are needed for interaction
- Way too many repetitive and unidentified nav landmarks
- ![image](https://user-images.githubusercontent.com/15215400/106805865-d864a200-662c-11eb-8786-60300422097e.png)
- ![image](https://user-images.githubusercontent.com/15215400/106805949-f3cfad00-662c-11eb-965c-b46b2a434f88.png)

**Remediation Technique:**
- There are many ways to tackle navigation structure, but it's clear a refactoring is needed in order to have a clean count of elements. TBD
- A standalone HTML structure is suggested in order to test the desired narration before refactoring. TBD
- `<ul> <li> <a>` structure
- role="navigation" aria-label="name"
- aria-haspopup="true"
- aria-expanded="false"
- role="group"
- aria-labelledby

**Comment by developpeurweb** [comment]
Closing. This ticket has been broken down into 3 tickets so it can be tackled at different stages or releases if needed:

- #13511 
- #13560 
- #13561
