### ISSUE TITLE
Conflict Information not Shown upon Product Mis-Configuration

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11004]
**Background:**

- Selecting invalid/mistaken configuration options of a configurable product creates a conflict that is clearly indicated by a warning icon. 

- The problem is that it's not clearly shown what this conflict is. User has to navigate to "Overview" tab, where conflict detail information is shown. 

- In desktop mode, this is somewhat acceptable. However in mobile, this would cause navigation to become more difficult as user struggles to understand what the error is. 

**Steps to Reproduce:** 
1. Navigate to Electronics storefront.
2. Search for Home Theater product (/electronics-spa/en/USD/product/CONF_HOME_THEATER_ML/Home%20Theater%20System)
3. In PDP, click on Configure button below Add to Cart button
4. Configure at will in "General" configuration menu. Click on Next
5. Inside Video System configuration menu, In Projector tab, select "No Projector" and "Lamp" light source.  (Causes a conflict)
6. Click on next to continue configuration

**Expected Results:**
5. User is shown error message indicating clearly what is the source of conflict. (Notice this is available in API response)
6. Continuing configuration must not be allowed until conflict is solved. 

**Actual Results:** 
5. "Resolve conflict" menu option not available in mobile mode. 
5.a. In desktop mode, a "Resolve conflict" menu option is shown. Warning icons with "Conflict Detected" are shown in configuration sections where selected options are not allowed"
6. Next button is available. Even though there is conflict. User is able to move on and continue configuring product. Is this a flow error? At the end, user won't be able to Add to Cart. 

---

Frontend: localhost, Chrome Iphone X @ 100% view.
Backend: CX 2005.6

**Comment by giancorderoortiz** [comment]
May be an improvement. Left at the discretion of PO @Xymmer

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-02-04 at 12 12 04 PM](https://user-images.githubusercontent.com/46171897/106929325-3b644080-66e2-11eb-8989-71065b8b4028.png)

**Comment by giancorderoortiz** [comment]
**Overview tab when there is a conflict:** 
![Screen Shot 2021-02-04 at 12 16 22 PM](https://user-images.githubusercontent.com/46171897/106929896-eecd3500-66e2-11eb-90ef-e66cf23d32c5.png)

**Description of Conflict:** 
![Screen Shot 2021-02-04 at 12 16 32 PM](https://user-images.githubusercontent.com/46171897/106929922-f7be0680-66e2-11eb-987a-e084b9b17613.png)

**Comment by giancorderoortiz** [comment]
Desktop mode:
![Screen Shot 2021-02-04 at 12 26 01 PM](https://user-images.githubusercontent.com/46171897/106932020-348afd00-66e5-11eb-8227-7b690089ce9e.png)

**Comment by Larisa-Staroverova** [comment]
As discussed in our call a couple weeks ago, this conflict solve solution is MVP.
Here is the list of the BIs that are planned to implement to round up the conflict solver solution:
https://cxjira.sap.com/browse/TIGER-6558 - Navigation
https://cxjira.sap.com/browse/TIGER-6778 - Resolve issue
https://cxjira.sap.com/browse/TIGER-6679 - Stack messages
https://cxjira.sap.com/browse/TIGER-6559 - Retract

**Comment by Larisa-Staroverova** [comment]
@giancorderoortiz, I would close this bug, please see comments above. If you need more info regarding the road map, namely when it is planned to implement other conflict solver BIs, please contact our PO - Jutta Knell.

**Comment by giancorderoortiz** [comment]
I'll consult internally. @Platonn
