### ISSUE TITLE
Product Configurator - Mobile View - Labels Edge Issue

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11002]
**Steps to Reproduce:** 

1. Navigate to Electronics storefront and change browser to mobile view
2. Look for Digital Camera Configurable product.  (electronics-spa/en/USD/product/CONF_CAMERA_SL/Digital%20Camera)
3. Click on Configure button
4. Edit configuration at will
5. View edited configuration in overview tab. 

Expected Results: 
5. Edges surrounding labels are shown completely

Actual Results: 
5. Not all edges visible. Box seems too big for label. 

---
Frontend: localhost, Chrome Iphone X @ 100% view. 
Backend: CX 2005.6

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-02-04 at 11 09 55 AM](https://user-images.githubusercontent.com/46171897/106922788-66976180-66db-11eb-886c-64b5cea3d0db.png)
![Screen Shot 2021-02-04 at 11 10 07 AM](https://user-images.githubusercontent.com/46171897/106922794-672ff800-66db-11eb-8954-39a684cb7eef.png)

**Comment by giancorderoortiz** [comment]
@developpeurweb fyi

**Comment by Larisa-Staroverova** [comment]
Here is the screenshot for tablet and as you can see the edges are shown completely:
![image](https://user-images.githubusercontent.com/61147963/108989810-4c2b2500-7696-11eb-9a68-9ae825cb5112.png)

**Comment by Larisa-Staroverova** [comment]
Our UI desinger is Anthony Reid. We follow all wireframes that we get from him

**Comment by giancorderoortiz** [comment]
Will check with Anthony

**Comment by developpeurweb** [comment]
> @developpeurweb fyi

Thanks @giancorderoortiz Noted. Btw I see buttons at the top again, this will be an issue for gesture navigation and Screen Readers on mobile.
@vekterdude can you pls leave your comments here regarding edges or contact the team directly.
@Manurod2018 the screenshot posted above seems different than those you sent me before in Zeplin, also the "**Overview**" tab is missing from mockups, let's pls align on this matter.

![Screen Shot 2021-02-24 at 4 17 28 PM](https://user-images.githubusercontent.com/15113219/109069212-e99a4f00-76be-11eb-84e2-655e0b36b302.png)

**Comment by vekterdude** [comment]
No issue. On mobile there is very little space for margins so we eliminated them and run the horizontal rules right to the edges. This is common practice in mobile.

**Comment by giancorderoortiz** [comment]
Closing per Anthony's comments.
