### ISSUE TITLE
Unable to Checkout Camera Configurable Product

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11003]
**Steps to Reproduce:** 

1. Navigate to Electronics storefront.
2. Look for Digital Camera Configurable product and double click. (electronics-spa/en/USD/product/CONF_CAMERA_SL/Digital%20Camera)
3. From PDP, click on configure
4. Modify configuration as needed. 
5. Click on Add to Cart at bottom of Configuration tab. 
6. Change to Overview tab. 
7. Click on Add to Cart at bottom of Overview tab. 

**Expected Results:** 

5. Camera product is added to cart (from Configuration tab)
7. Camera product is added to cart (from Overview tab)

**Actual Results:** 
5. Product not added to the cart. "Add to Cart" button remains enabled even though it doesn't work. 
7. Same as 5. 

----
Frontend: localhost, Chrome desktop mode
Backend: CX 2005.6

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-02-04 at 11 36 17 AM](https://user-images.githubusercontent.com/46171897/106925899-8419fa80-66de-11eb-86bc-5400617c6c74.png)

**Comment by ChristophHi** [comment]
That's a known backend issue due to co-deployment of selective carts and product configurators. Will be fixed with SAP ticket https://cxjira.sap.com/browse/TIGER-6667.

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
We will fix this issue with a commerce patch for 2105

**Comment by ChristophHi** [comment]
Let's close as covered by https://cxjira.sap.com/browse/TIGER-6667.
This is a pure commerce backend issue
