### ISSUE TITLE
Implement adapter for add to cart

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#11021]
- implement new occ service for CPQ add to cart
- call new occ service in adapter
- create new structure for add to cart parameter
- create new serialiser and map structure to occ model
  - We cannot reuse the vc, cause this would introduce breaking changes, because we would have to move the classes and models

**Comment by Uli-Tiger** [comment]
AddToCartParameters is declared in \feature-libs\product-configurator\rulebased\core\model\configurator.model.ts hence i see no reason not to re-use it.
