### ISSUE TITLE
Check Saved Carts Works with ASM

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11047]
TBD.

@plabadie

**Comment by ren-tham** [comment]
Background info: Currently dev3 doesn't contain asagent users. May need to reinitialize dev3.

**Comment by giancorderoortiz** [comment]
Fixed
![Screen Shot 2021-03-12 at 11 17 34 AM](https://user-images.githubusercontent.com/46171897/110970955-44bb7b00-8328-11eb-9ee5-a3468ea97423.png)

**Comment by giancorderoortiz** [comment]
Verification of functionality can proceed now.

**Comment by ren-tham** [comment]
Performed manual test signed in as 'asagent'. Performed checkout and tested saved cart features. All working fine.
