### ISSUE TITLE
Session Management and Saved Carts

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11049]
Confirm: 

1. Saved carts feature only available for registered users. 
2.Saved carts available only during valid user session. If timeout, redirect to login, and subsequently save cart.

**Comment by ren-tham** [comment]
Manual/Smoke Test performed to confirm concerns.

Check 1: 
Tested as a guest: 
- On cart page, Saving cart redirects to login page.
- Visiting '/powertools-spa/en/USD/my-account/saved-carts' as guest redirect to login page.

As logged in user: 
- All feature available.

Check 2: 
- While on saved carts listing page, on session timeout, redirected to login page. Cannot access listing page until logged in again.

Saved Carts working as expected with Session Management.
