### ISSUE TITLE
Saved Carts Feature Development with CX 2011

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11048]
Use cx 2011 backend for feature development. 

Deploy server if necessary (check with Brian).

**Comment by bgambocjaviniar** [comment]
closing as it's not a use case for us as we have been using 2011 and testing with it out of the box as we're using dev3-azure.

<img width="907" alt="Screen Shot 2021-03-16 at 2 12 59 PM" src="https://user-images.githubusercontent.com/29099466/111359392-d34e3600-8661-11eb-9dd9-570affa1cca7.png">

Can also see there's no problems with the checks
