### ISSUE TITLE
Flaky B2B users (and groups) e2e tests

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#11042]
Have a look at [the cypress dashboard](https://dashboard.cypress.io/projects/k3nmep/analytics/top-failures?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%7B%22label%22%3A%22B2B%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22B2B%22%7D%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222021-02-01%22%2C%22endDate%22%3A%222021-02-08%22%7D&viewBy=TEST_CASE)

**Comment by hackergil** [comment]
We tested this today and it's still failing across the board unfortunately

**Comment by giancorderoortiz** [comment]
Appears fixed on 3.4 release branch. 
Ran 5+ times. 

![Screen Shot 2021-06-14 at 7 51 34 AM](https://user-images.githubusercontent.com/46171897/121888249-c20ad900-cce5-11eb-89a4-78d982b635ee.png)
