### ISSUE TITLE
[Bundles UI] View Bundles in Cart

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#11082]
Note: Ticket to be expanded on after #8927

**Comment by Platonn** [comment]
It would be good to integrate new features in the cart item components via outlets (existing ones outlets or adding a new one in a conservative way). I'd be happy to discuss outlets needed for this feature.

Work related to outlets:
https://github.com/SAP/spartacus/issues/11009 (done)
https://github.com/SAP/spartacus/issues/11144 (in progress by the Team Tiger)
