### ISSUE TITLE
Add new cart-item-action outlet and change existing behaviour for action buttons to use new outlet

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#11144]
To add the included bundle line items for a cart entry we need an additional outlet, in the cart entry, to add the bundle component where the UI designer wanted them to be.

Suggestion would be: Wrap the action buttons for the cart entry (save for later, etc.) with a new outlet. 
Suggested outlet name: CartOutlets.ITEM_ACTIONS

This would enable us to add our bundle items where desired from UX perspective and would help us to decouple action logic from the cart i.e. cart should not know all optional actions.

Currently action buttons have been plugged into the cart item via custom @Input options - which is not ideal, i.e. cart item needs to know about the optional features (actions) plugged in. See current options:
@Input() options: CartItemComponentOptions = {
    isSaveForLater: false,
    optionalBtn: null,
  };

Going forward, by introducing the ITEM_ACTIONS outlet, we should use it also for plugging in the existing action buttons (save for later, etc.). Then we could deprecate the input options.

**Comment by Platonn** [comment]
Ideally, if possible, we should build a hybrid solution:
- customers can still use the old `options` input for saveForLater and other buttons (we only deprecate it)
- customers eaisly can opt in into using outlet for plugging those features instead of `options` input
- CPQ bundles use the outlet from the beginning

Long term plan: In 4.0 or 5.0 we'll drop the `options` input.

**Comment by schuppell** [comment]
No longer needed for CPQ integration. Therefor closed

**Comment by schuppell** [comment]
We have plans for more generic extensibility of the nested components than arbitraty outlets but there is long way before we get there (before we implement this mechanism and apply in the cart components) so for now we add outlets - when we need them
