### ISSUE TITLE
chore: Update to Angular 11

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#11153]
This is a draft ticket which has been created during the work on #9068 in order to not forget the below won't be updated automatically:
- [x] https://github.com/SAP/spartacus/blob/develop/tools/build-lib/augmented-types/index.ts - `@angular-devkit/build-ng-packagr:build` should be changed to `@angular-devkit/build-angular:ng-packagr`, related to https://github.com/SAP/spartacus/issues/9068

For updating to ng11 run:
`ng update @angular/core @angular/cli`

More details: https://update.angular.io/?l=3&v=10.2-11.0

**Comment by dunqan** [comment]
Fixed by #12058
