### ISSUE TITLE
Use the pagination and sort object from the get all carts endpoint for the Saved Cart 'History' page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11157]
Currently, when requesting all carts in the `GET /carts` endpoint, we only receive carts without the pagination and sorts object.

This ticket is to fix `saved-cart-list.component.ts` to support pagination and sorting when the backend fixes this issue.

Follow the following jira ticket for more information https://cxjira.sap.com/browse/CLC-2544

**Comment by Xymmer** [comment]
https://jira.tools.sap/browse/CXSPA-315
