### ISSUE TITLE
Update Headings to improve Screen Reader support on Electronics Storefront

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#11151]
Update Headings to improve support for Screen Reader across the B2C electronics storefront
master ticket: #11192

- [x] [Check Full Implementation details ](https://cxwiki.sap.com/display/spar/Headings+and+Labels)
- [x] Update Markup with proper headings as outlined the in the implementation details (asterix or praetorians)
- [x] Fix SCSS (praetorians) 
- [x] Fix Unit tests (asterix)
- [x] Fix e2e test (asterix)

**Comment by developpeurweb** [comment]
For historic purposes and later QA reference.

:x: **BEFORE**

**_VoiceOver_**
![VO-before1](https://user-images.githubusercontent.com/15113219/114076781-0f497500-9875-11eb-8037-3de939efd8b8.jpg)
![VO-before2](https://user-images.githubusercontent.com/15113219/114076786-107aa200-9875-11eb-9bfa-7e2ca27f5c03.jpg)

**_NVDA_**
<img width="960" alt="NVDA-before1a" src="https://user-images.githubusercontent.com/15113219/114076853-25573580-9875-11eb-9aeb-9afe2cd84ee2.png">
<img width="960" alt="NVDA-before1b" src="https://user-images.githubusercontent.com/15113219/114076847-24260880-9875-11eb-8d8c-ce0337ce39ef.png">
<img width="960" alt="NVDA-before2" src="https://user-images.githubusercontent.com/15113219/114076856-25efcc00-9875-11eb-8a2d-6916807b095c.png">

**_JAWS_**

<img width="960" alt="JAWS before1" src="https://user-images.githubusercontent.com/15113219/114076934-3dc75000-9875-11eb-99db-23d0c3531dcb.png">
<img width="960" alt="JAWS-before2" src="https://user-images.githubusercontent.com/15113219/114076937-3ef87d00-9875-11eb-914f-75a87cf5f4b8.png">

---

:white_check_mark: **AFTER** 

**_VoiceOver_**
![VO-after1](https://user-images.githubusercontent.com/15113219/114076999-4f105c80-9875-11eb-8e56-4514418a8857.jpg)
![VO-after2](https://user-images.githubusercontent.com/15113219/114077004-4fa8f300-9875-11eb-8b1b-77352adb8b16.jpg)

**_NVDA_**
<img width="960" alt="NVDA-after1" src="https://user-images.githubusercontent.com/15113219/114077082-69e2d100-9875-11eb-875c-21eab20260ba.png">
<img width="960" alt="NVDA-after2" src="https://user-images.githubusercontent.com/15113219/114077078-694a3a80-9875-11eb-9249-2389fffc7ec0.png">


**_JAWS_**
<img width="960" alt="JAWS-after1" src="https://user-images.githubusercontent.com/15113219/114077377-bcbc8880-9875-11eb-8864-cf920c06e9cc.png">
<img width="960" alt="JAWS-after2" src="https://user-images.githubusercontent.com/15113219/114077383-bd551f00-9875-11eb-849b-0aec45692421.png">

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

![Screen Shot 2022-03-23 at 1 54 58 PM](https://user-images.githubusercontent.com/45409515/159766552-15c6629a-8bf1-466a-8b65-d14cc2dbadfc.png)
![Screen Shot 2022-03-23 at 1 55 30 PM](https://user-images.githubusercontent.com/45409515/159766550-7db2e8fc-0f69-4c20-87a0-0025b37e51db.png)
![Screen Shot 2022-03-23 at 1 54 30 PM](https://user-images.githubusercontent.com/45409515/159766558-e2802c93-c88e-4f20-8071-531e013ee192.png)
![Screen Shot 2022-03-23 at 1 53 57 PM](https://user-images.githubusercontent.com/45409515/159766559-4a9d1ecb-ff7e-4282-a1a4-9d8e72c4a76b.png)
![Screen Shot 2022-03-23 at 1 53 25 PM](https://user-images.githubusercontent.com/45409515/159766562-58772ebb-f633-48df-bdb3-2c83c6955738.png)
