### ISSUE TITLE
[MASTER] Viewport-aware e2e tests

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#11163]
We currently test a lot of functionalities in both desktop and mobile, but we don't do that for everything. However we should test everything in both viewports.

The way we do it currently is to create 2 e2e files (one for desktop and one for mobile). These tests share a lot of code (~90% I would say). That causes us to create some helper functions that only require us to navigate between more and more files just to debug single test.

Better approach would be to write single test that conditionally executes some code depending on viewport.
(eg. `cy.onMobile(() => cy.clickHamburger()`).

Thanks to that we could remove all the helpers files and keep the core test in one file. Maintenance of the tests becames simpler (you won't forget to copy the code to mobile test). Simpler setup in CI (always run all viewports, or just run single). Instead of splitting tests to live in `regression` or in `mobile` directory.

### Next mobile e2e that require change (grouped for separate PRs) - add yourself to the group if you are working on it:

Picked up by @hackergil (#11341):
- [x] checkout-as-persistent-user-mobile.flaky-e2e-spec.ts
- [x] checkout-flow.e2e-spec.ts
- [x] checkout-flow-mobile.e2e-spec.ts
- [x] checkout-as-guest.e2e-spec.ts
- [x] express-checkout.flaky-e2e-spec.ts
- [x] apparel-checkout-flow.e2e-spec.ts
- [x] apparel-checkout-as-guest.e2e-spec.ts

Picked up by @hackergil (#7520):
- [x] coupon-mobile.flaky-e2e-spec.ts
- [x] my-coupons-mobile.flaky-e2e-spec.ts

Picked up by @psmul (#11332):
- [x] address-book-mobile.e2e-spec.ts
- [x] payment-methods-mobile.e2e-spec.ts

Picked up by @mirkosoft (#11487 ) :
- [x] order-history-no-orders-flow-mobile.e2e-spec.ts
- [x] order-history-orders-flow-mobile.flaky-e2e-spec.ts

Picked up by @marlass (#11306):
- [x] update-email-mobile.e2e-spec.ts
- [x] close-account-mobile.e2e-spec.ts

Picked up by @marlass (#11315):
- [x] update-password-mobile.e2e-spec.ts
- [x] update-profile-mobile.e2e-spec.ts

Picked up by @psmul (#11417):
- [x] my-interests-mobile.e2e-spec.ts
- [x] notification-preference-mobile.e2e-spec.ts

Picked up by @mszczepaniak (#11434):
- [x] stock-notification-mobile.e2e-spec.ts
- [x] consent-management-mobile.e2e-spec.ts

Picked up by @psmul (#11500): 
- [x] save-for-later-mobile.flaky-e2e-spec.ts - please check #11404 

Picked up by @plabadie :
- [x]  asm-mobile.flaky-e2e-spec.ts (#11520)

Picked up by @hackergil (#10960):
- [x] cart-mobile.flaky-e2e-spec.ts

Picked up by *Team Tiger: #11199*:
- [ ] product-configuration-mobile.flaky-e2e-spec.ts

### How to do it:
- make desktop test working (if flaky)
- try to run dektop in both viewports (viewportContext)
- apply mobile fixes from the mobile test in desktop test (with cy.onMobile, cy.onDesktop methods)
- inline helper methods in tests if they are only used in this particular test
- remove mobile e2e

### Example PRs:
https://github.com/SAP/spartacus/pull/11174
https://github.com/SAP/spartacus/pull/11170
https://github.com/SAP/spartacus/pull/11165
https://github.com/SAP/spartacus/pull/11164

**Comment by giancorderoortiz** [comment]
Other than test product-configuration-mobile.flaky-e2e-spec, is there any other test pending this re-arrangement?

**Comment by hackergil** [comment]
@giancorderoortiz Yes. We have about 3 mobile-specific tests and about 30 specs that don't have this.
