### ISSUE TITLE
User entity is not successfully saved in httpsession after login powertools(B2B), which causes adding product to cart failure

### ISSUE THREAD

**Issue by timothy2005** [SAP/spartacus#11209]
**Describe the bug**
User entity is not successfully saved in httpsession after login powertools(B2B), which causes adding product to cart failure

**Tell us the version of Spartacus**
Commerce Cloud version: 2011
Spartacus version: 3.0

**To Reproduce**

After finish following installation

<<Installing SAP Commerce Cloud 2011 for use with Spartacus>>
https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2011/

Login powertools store with a buyer user:
http://localhost:4200/powertools-spa/en/USD/

The authorization is successful, see below:

```
Request URL: https://localhost:9002/authorizationserver/oauth/token
Request Method: POST
Status Code: 200 
Remote Address: [::1]:9002
Referrer Policy: strict-origin-when-cross-origin
```
<img width="1440" alt="auth_success" src="https://user-images.githubusercontent.com/10347577/108610005-1b848a80-740d-11eb-9fb6-3726bb2cb5a6.png">

But the user page got 401, user info is not saved, nor displayed
```
Request URL: https://localhost:9002/occ/v2/powertools-spa/users/current?lang=en&curr=USD
Request Method: GET
Status Code: 401 
Remote Address: [::1]:9002
Referrer Policy: strict-origin-when-cross-origin
```
<img width="1095" alt="userinfo_missing" src="https://user-images.githubusercontent.com/10347577/108610023-3d7e0d00-740d-11eb-8563-c81e0d1e7709.png">
<img width="1443" alt="user_page_failure" src="https://user-images.githubusercontent.com/10347577/108610027-4242c100-740d-11eb-9e3b-81e2ab463a75.png">

which caused adding product to cart failure, got 401
```
Request URL: https://localhost:9002/occ/v2/powertools-spa/users/current/carts/00001002/entries?code=3881030&qty=1&lang=en&curr=USD
Request Method: POST
Status Code: 401 
Remote Address: [::1]:9002
Referrer Policy: strict-origin-when-cross-origin
```
<img width="1308" alt="fails to add to cart" src="https://user-images.githubusercontent.com/10347577/108609987-f7c14480-740c-11eb-976c-56c3eb5bb44d.png">

This issue only happens on B2B stores(powertools), does not happen in B2C stores(electronics, apparel-uk)

**Comment by LTiger14** [comment]
Hi Timothy, it seems like it's possibly caused by pointing to the wrong APIs (B2C rather than B2B). Could you check in your `app.module.ts` if you are using the `B2CStorefrontModule` or the `B2bStorefrontModule`.

**Comment by timothy2005** [comment]
Hi @LTiger14 , yes, you are right, I am using **B2c**StorefrontModule rather than **B2b**StorefrontModule.
Thanks for correcting me, I will close this ticket.
