### ISSUE TITLE
[Waiting for #7727] Deprecation for NavigationUiComponent

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#11223]
Clean up for #7727 :

In `navigation-ui.component.ts`:
- [ ] Remove optional mark `?` from HamburgerMenuService in constructor.
- [ ] Remove hamburger service condition from close() method. 
```
close() {
  this.clear();
  this.hamburgerMenuService.toggle(true);
}
```

**Comment by Zeyber** [comment]
Bug fix was never merged so there is currently no deprecated code to clean up for 4.0.

**Comment by Xymmer** [comment]
7727 is in progress

**Comment by marlass** [comment]
This deprecations were done with other ticket: #12477
