### ISSUE TITLE
Selected Options not Saved upon Return to Configuration

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11244]
**Setup**
3.1.0.RC2 Server Links
CCV2 (CX 2011.1):
-- b2c - https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
-- b2b - https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

 Linux (CX 2005.6):
-- b2c - http://spartacus-dev2.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
-- b2b - http://spartacus-dev2.eastus.cloudapp.azure.com:5200/powertools-spa/en/USD/

**Steps to Reproduce:**

1. Navigate to B2C Storefront (CCV2)
2. Search for HOME
3. From product listing page, select Home Theatre product.
4. Click on Configure button. 
5. Select at least one configuration value for each available configuration type in all navigation menus. 
6. Complete custom configuration. Do not click Add to Cart. 
7. Navigate back and forth between configuration menus. 

**Expected Results:** 
7. Configuration values are kept throughout while navigating back and forth. 

**Actual Results:** 
7. Some configuration selected values are cleared/removed. 

---

Specific Case 1:  
- Light Source. 
- First configuration journey: Selected as LED

![light_source_selected](https://user-images.githubusercontent.com/46171897/109053878-32e0a380-76ab-11eb-8172-d6eb85603516.png)

- Second configuration journey: none selected. 

![light_source_no_selection](https://user-images.githubusercontent.com/46171897/109053897-396f1b00-76ab-11eb-8f1d-a118d5605d32.png)

---

Specific Case 2: 

- Rear Speakers
- First configuration journey: Selected as Phillip

![rear_speakers_selected](https://user-images.githubusercontent.com/46171897/109054979-97503280-76ac-11eb-9259-d1bb9c68378e.png)

- Second configuration journey: None selected. 
![rear_speakers_no_selection](https://user-images.githubusercontent.com/46171897/109055017-a6cf7b80-76ac-11eb-93b1-7a513cd4eed4.png)

**Comment by Larisa-Staroverova** [comment]
Please, add steps to reproduce

**Comment by giancorderoortiz** [comment]
Note, there is some randomness to this behaviour. Somewhat difficult to reproduce exactly.

**Comment by giancorderoortiz** [comment]
There is also a level of intermittence that makes reproducing this error consistently very difficult.

**Comment by developpeurweb** [comment]
Pls see video: https://video.sap.com/media/t/1_ghzw77ig
After having the configured product in the cart, if the user has a change of mind, and goes back to change options, some of them will not stick. See `from 10:47 to 11:33` **e.g. Flat Panel TV**
(See previous steps before 10:47 in the video for initial configuration).

**Comment by ChristophHi** [comment]
Hi @giancorderoortiz, our configurator mock implementation is not multi-node enabled (only used for demo and CI purposes). Therefore SPA needs to address the same ccv2 node on each browser interaction. Please change the setup according to #7104 :
On SPA side, have backend.occ.useWithCredentials set to true.
On commerce side, ensure property corsfilter.commercewebservices.allowCredentials = true.

Then please try again, and if you face issues, let me know

**Comment by giancorderoortiz** [comment]
@tobi-or-not-tobi please advise.

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
See  above, this is a configuration issue

**Comment by ChristophHi** [comment]
I assume that this is due to missing session stickiness. See #7104.
Our mock configurator (which we use for testing here) requires sticky sessions. 

Also for productive configurators, sticky sessions are highly recommended. Sessions being non-sticky will not result in errors, but in bad performance.
Please re-test on a system where session stickiness is deployed. Note that in the commerce backend, the respective setting can be 
`corsfilter.ycommercewebservices.allowCredentials = true`
or
`corsfilter.commercewebservices.allowCredentials = true`
depending on which web service extension is used!
