### ISSUE TITLE
Able to Land in Configuration without Content (Intermittent)

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11245]
**Setup**
3.1.0.RC2 Server Links
CCV2 (CX 2011.1):
-- b2c - https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
-- b2b - https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

 Linux (CX 2005.6):
-- b2c - http://spartacus-dev2.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
-- b2b - http://spartacus-dev2.eastus.cloudapp.azure.com:5200/powertools-spa/en/USD/

**Steps** to Reproduce: **

1. Navigate to B2C Storefront (CCV2)
2. Search for HOME
3. From product listing page, select Home Theatre product.
4. Click on Configure button.
5. Select at least one configuration value for each available configuration type in all navigation menus.
6. Complete custom configuration. Do not click Add to Cart.
7. Navigate back and forth between configuration menus or between "Previous" and "Next" Buttons

Expected Results: 
7. An empty configuration page is never shown.

Actual Results: 
7. Intermittently/Randomly we can see a page with no configuration options. 

![Screen Shot 2021-02-24 at 2 42 50 PM](https://user-images.githubusercontent.com/46171897/109057827-3b87a880-76b0-11eb-91ac-75dd0f0e85fb.png)
![Screen Shot 2021-02-24 at 2 47 03 PM](https://user-images.githubusercontent.com/46171897/109057829-3b87a880-76b0-11eb-9164-ff32de66b1cd.png)
![Screen Shot 2021-02-24 at 2 47 13 PM](https://user-images.githubusercontent.com/46171897/109057830-3b87a880-76b0-11eb-9685-0225145b4c38.png)

**Comment by Larisa-Staroverova** [comment]
It is not clear what you mean. Could you plz add more info?

**Comment by Larisa-Staroverova** [comment]
If I understand you correctly and you mean a configuration without any set values within it. Then it is possible to have a configuration without any default values within it.

**Comment by giancorderoortiz** [comment]
Also see video from @developpeurweb at minute 6:00. 
https://video.sap.com/media/t/1_ghzw77ig

**Comment by vekterdude** [comment]
Hi Giancarlo! I think I understand the issue now. i will raise this with Tigers this morning.

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by ChristophHi** [comment]
Closing, as this is a configuration issue (see my remarks in #11256). SPA needs to establish sticky sessions in **case the mock configurator is used**.
Note that customer are using VC or CPQ configurator and are not affected by these issues.
