### ISSUE TITLE
Clicking on Next Adds Config Product to Cart 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11243]
**Setup**
3.1.0.RC2 Server Links
CCV2 (CX 2011.1):
-- b2c - https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
-- b2b - https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

 Linux (CX 2005.6):
-- b2c - http://spartacus-dev2.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
-- b2b - http://spartacus-dev2.eastus.cloudapp.azure.com:5200/powertools-spa/en/USD/

TBD. 

Further investigation required

**Comment by Larisa-Staroverova** [comment]
Please, add steps to reproduce

**Comment by developpeurweb** [comment]
- If I hit the “Next” button, at all steps, without choosing any options, the product (Home Theater) gets added to the cart anyway.
- To reproduce, please go to timestamp `from 0:30 to 1:00` on this video: https://video.sap.com/media/t/1_ghzw77ig

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
We will fix it with #12071

**Comment by Larisa-Staroverova** [comment]
Was fixed #11991
