### ISSUE TITLE
Empty Product Config Page After Conflict. Firefox

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11255]
**Steps to Reproduce using Firefox Browser:** 

1. Navigate to Spartacus B2C storefront. 
1.a. Use CCV2 instance https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD
2. Search for Home Theater product. 
3. Click on configuration button.
4.  Cause a conflict.  For example, in Projector tab, Select first "Digital Light", then a light source. Immediately after, select "No Projector". See image below. 
5. Click on next button. 

**Expected Results:** 
5. Next phase of product configuration options is displayed.

**Actual Results:** 
5. No product configuration options displayed.

**Comment by giancorderoortiz** [comment]
Conflict: 
![Screen Shot 2021-02-24 at 7 06 34 AM](https://user-images.githubusercontent.com/46171897/108999069-cb593280-766f-11eb-828c-622dbfaaae8f.png)

**Comment by giancorderoortiz** [comment]
Empty configuration: 
![Screen Shot 2021-02-24 at 6 59 45 AM](https://user-images.githubusercontent.com/46171897/108999112-d9a74e80-766f-11eb-954b-5d3da69ab36e.png)

**Comment by giancorderoortiz** [comment]
Using Firefox v85.0. Mac OS 10.15.7

**Comment by Larisa-Staroverova** [comment]
As far as I see, the order of the CSM slots is wrong:
![image](https://user-images.githubusercontent.com/61147963/108999459-9dd9ac80-76a2-11eb-848e-907ddb6ac7ae.png)

**Comment by Larisa-Staroverova** [comment]
The slot **ConfiguratorPrevNext** should come after **ConfiguratorForm**

**Comment by Larisa-Staroverova** [comment]
In [spaartacussampledata ](https://github.tools.sap/cx-commerce/spartacussampledata/blob/af87b33933607cb18d5062a439a78d5f38066d70/resources/spartacussampledata/import/contentCatalogs/electronicsContentCatalog/cms-responsive-content.impex)the order of the slots is correct:
```
....
;VariantConfigContentSlot;ConfiguratorGroupTitle
;VariantConfigContentSlot;ConfiguratorForm
;VariantConfigContentSlot;ConfiguratorPrevNext
...
```

**Comment by giancorderoortiz** [comment]
Same issue seen in Safari
![Screen Shot 2021-02-24 at 7 53 50 AM](https://user-images.githubusercontent.com/46171897/109003511-89cb8600-7675-11eb-8417-1a5404a0203a.png)

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
We will look into this after 3.3 release phase

**Comment by ChristophHi** [comment]
I assume that this is due to missing session stickiness. See #7104.
Our mock configurator (which we use for testing here) requires sticky sessions.

Also for productive configurators, sticky sessions are highly recommended. Sessions being non-sticky will not result in errors, but in bad performance.
Please re-test on a system where session stickiness is deployed. Note that in the commerce backend, the respective setting can be
corsfilter.ycommercewebservices.allowCredentials = true
or
corsfilter.commercewebservices.allowCredentials = true
depending on which web service extension is used!
