### ISSUE TITLE
JS error "'clearCheckoutDeliveryDetails' of undefined" while creating or editing address in address book

### ISSUE THREAD

**Issue by SPeterFront** [SAP/spartacus#11302]
While creating a new address or editing an existing one on the address book page, a js error gets thrown.

- Library version: [2.1.4]

1. Go to 'Address Book Page' in "My Account section"
2. Edit existing address or add new one and click on "Update/Add Address" 
3. Take a look at the browser console
4. See error "TypeError: Cannot read property 'clearCheckoutDeliveryDetails' of undefined"

Expected behavior:
No js error pops up

![Auswahl_061](https://user-images.githubusercontent.com/79840530/109485181-a9055180-7a81-11eb-8ebe-fd87ebec0c6d.png)

Reproduced on Chrome 88.0.4324

**Comment by bit172** [comment]
Closing this issue as it is no longer reproducible. This issue was fixed in #11894.
