### ISSUE TITLE
[Master] Non-Text Content

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#11316]
## What is Non-Text Content
**In a nutshell:** Provide a text alternative to describe an object that is not text.
E.g. Photos, Images, graphics, images-of-text or icons.

## Overview
- Success Criterion 1.1.1:  [Non-text Content](https://www.w3.org/TR/UNDERSTANDING-WCAG20/text-equiv-all.html)
-  **MASTER** Ticket #11672
- [**Github label**](https://github.com/SAP/spartacus/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y-sr%2Fnon-text-content): `a11y-sr/non-text-content`
- **Related topic in Team Blamed:**  #2374

## Implementation 

- [x] #11317
- [x] #11319
- [x] #13430 
- [x] #13438
- [x] #13523

**Comment by developpeurweb** [comment]
All tickets for this master have been finished. Closing.
