### ISSUE TITLE
Missing EXIT button for Product Configurator in Mobile and Desktop

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#11320]
**Describe the bug**
Missing EXIT button for Product Configurator in Mobile and Desktop

**Tell us the version of Spartacus**
- Library version: 3.1

**To Reproduce**
Current layout screenshots
![Screen Shot 2021-03-01 at 3 43 31 PM](https://user-images.githubusercontent.com/15113219/109560075-740cf500-7aa9-11eb-9eec-2931417cc268.png)
![Screen Shot 2021-03-01 at 3 39 51 PM](https://user-images.githubusercontent.com/15113219/109560128-7c653000-7aa9-11eb-92a9-4161e6791621.png)

**Expected behaviour**
As per Zeplin's mockups

![Screen Shot 2021-03-01 at 4 09 39 PM](https://user-images.githubusercontent.com/15113219/109559901-458f1a00-7aa9-11eb-8367-a3cca825a9be.png)
![Screen Shot 2021-03-01 at 3 39 09 PM](https://user-images.githubusercontent.com/15113219/109559936-52137280-7aa9-11eb-8eb2-3354e7104b9e.png)

**Additional context**
In both versions, this creates difficult exit scenarios for users who want to quit the configuration process, if they change their minds or got there by accident or curiosity, especially keyboard-only users and those navigating with gestures on mobile.

FYI @Manurod2018 @vekterdude

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
This is still in the discussion with UID
