### ISSUE TITLE
Complete the unit test for saved cart listing page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11325]
related to this PR https://github.com/SAP/spartacus/pull/11230 after the PR gets merged

- [x] feature-libs/cart/saved-cart/core/connectors/saved-cart.connector.ts
- [x] feature-libs/cart/saved-cart/core/services/saved-cart.service.ts
- [x] feature-libs/cart/saved-cart/core/store/actions/saved-cart.action.ts
- [x] feature-libs/cart/saved-cart/core/store/effects/saved-cart.effect.ts
- [x] feature-libs/cart/saved-cart/occ/adapters/occ-saved-cart.adapter.ts
- [x] projects/core/src/cart/store/actions/cart.action.ts
- [x] projects/core/src/cart/store/reducers/multi-cart.reducer.ts
- [x] projects/core/src/cart/store/selectors/multi-cart.selector.ts
- [x] projects/core/src/cart/facade/multi-cart.service.ts
- [x] feature-libs/cart/saved-cart/components/list/saved-cart-list.component.ts

can do it together with https://github.com/SAP/spartacus/issues/11327 to avoid conflicts

-----
feature-libs/cart/saved-cart/**/core
feature-libs/cart/saved-cart/**/occ

were done in this PR https://github.com/SAP/spartacus/pull/11409

**Comment by ren-tham** [comment]
PR(#11440 )
