### ISSUE TITLE
Complete the unit test for saving cart

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#11331]
related to this PR #11268 after the PR gets merged

- [x] feature-libs/cart/saved-cart/components/add-to-saved-cart/add-to-saved-cart.component.ts
- [x] feature-libs/cart/saved-cart/components/saved-cart-form-dialog/saved-cart-form-launch-dialog.service.ts
- [x] feature-libs/cart/saved-cart/components/saved-cart-form-dialog/saved-cart-form-dialog.component.ts
- [x] feature-libs/cart/saved-cart/core/connectors/saved-cart.connector.ts
- [x] feature-libs/cart/saved-cart/core/services/saved-cart.service.ts
- [x] feature-libs/cart/saved-cart/core/store/actions/saved-cart.action.ts
- [x] feature-libs/cart/saved-cart/core/store/effects/saved-cart.effect.ts
- [x] feature-libs/cart/saved-cart/occ/adapters/occ-saved-cart.adapter.ts

-----
feature-libs/cart/saved-cart/**/core
feature-libs/cart/saved-cart/**/occ

were done in this PR https://github.com/SAP/spartacus/pull/11409

**Comment by bgambocjaviniar** [comment]
PR: GH-11432
