### ISSUE TITLE
Make Language and Currency service customisable

### ISSUE THREAD

**Issue by j-caroco** [SAP/spartacus#11345]
**Is your feature request related to a problem? Please describe.**
I'm trying to change where Spartacus saves the language and currency from sessionStorage to localStorage. The problem is both effects files (languages.effect.ts and currencies.effect.ts) are using sessionStorage. The services aren't provided in root and the effects are using the sessionStorage directly (this could be done in the service so we could change the implementation). Also on another note, I think the place where the initialize method is called is not the best (context-service-provider.ts).

**Describe the solution you'd like**
Make language and currency service provided in root. Remove the direct usage of sessionStorage from both effect files and allow to chose where language and currency are stored.

**Describe alternatives you've considered**
I've tried adding a custom context (https://sap.github.io/spartacus-docs/automatic-context-configuration/) and also provided custom language and currency services but no luck switching those both services for a custom implementation.

**Comment by LTiger14** [comment]
Thank you for reporting this. It will be handled as part of #10440.
