### ISSUE TITLE
Check source code for terms

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#11340]
See https://cxwiki.sap.com/x/uKXmI
For next major

**Comment by ren-tham** [comment]
Checked codebase for insensitive terms: https://jam4.sapjam.com/groups/fpVjPTHoZVTjFIbqxZSK6s/documents/ByaMKkEZ5I14zEfZqzvs9d/slide_viewer

Insensitive terms present in codebase:

- blacklist
- whitelist 

Currently, used as CSS class names. Changing names is a breaking fix.

**Comment by ren-tham** [comment]
Pr: (#12172 )

**Comment by ren-tham** [comment]
PR Corrections.
