### ISSUE TITLE
Store Finder Opening Hours do not Work in SSR Context

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#11366]
**Describe the bug**
With ticket #10302, the storefinder opening hours where fixed to work for languages other than english. In the fix, the code `this.winRef?.sessionStorage?.getItem('language')` was used to get the current language. The problem with this line is, that sessionStorage is not available in SSR context. Therefore, for the initial page reload on the storefinder store page, the opening Hours are again being displayed with "-".

**Tell us the version of Spartacus**
- Library version: 3.1.0

**To Reproduce**
1. Use a fresh instance of Spartacus
2. Start it in SSR Mode
3. Open the Store Finder Detail page in an ingcognito window (where you have never selected a language via Language Dropdown)
4. See the opening hours not being displayed, but just "-"

**Expected behavior**
The Opening Hours are also displayed for the initial Request in SSR mode

**Screenshots**
![image](https://user-images.githubusercontent.com/3381820/109920368-7abe8680-7cba-11eb-8ada-dbc27a2e6205.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

Please also see ticket #11367, which is kinda related..

**Comment by giancorderoortiz** [comment]
Issue fixed. 
![Screen Shot 2021-05-18 at 7 51 17 AM](https://user-images.githubusercontent.com/46171897/118646203-e2f71180-b7ad-11eb-9d6d-77230abbc020.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-05-18 at 7 52 40 AM](https://user-images.githubusercontent.com/46171897/118646331-1174ec80-b7ae-11eb-974b-d9f2ce0d83b4.png)
