### ISSUE TITLE
B2B ASM emulation gives error on shipping address step for account checkout

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#11361]
**Describe the bug**
When emulating a B2B customer in ASM there is an error on the shipping address step when doing an account checkout.

**Tell us the version of Spartacus**
3.1.0

**To Reproduce**
1. Login with the ASM agent `asagent`
2. Start customer emulation for William Hunter
3. Add a product to cart & start checkout
4. Select `Account` Checkout
5. Open the browser console

The error happens because the cost center drop down contains more options when the session is emulated than what the user has available. See screenshots.

**Expected behavior**
You should be able to checkout without a console error.

**Screenshots**

ASM Emulation

<img width="1052" alt="Screen Shot 2021-03-03 at 6 01 52 PM" src="https://user-images.githubusercontent.com/10605724/109895075-9a26c680-7c5c-11eb-8586-723462b9afb2.png">

Correct result (not emulation)

<img width="1046" alt="Screen Shot 2021-03-03 at 6 06 32 PM" src="https://user-images.githubusercontent.com/10605724/109895024-88452380-7c5c-11eb-889b-3af1ca296de8.png">

**Additional context**

The error happens because the cost center drop down contains more options when the session is emulated than what the user has available.

400 Error on `users/.../carts/.../costcenter?...`

Response:

```
{
   “errors” : [ {
      “message” : “Costcenter PunchOut Organization does not exist.“,
      “type” : “EntityValidationError”
   } ]
}
```

**Comment by LTiger14** [comment]
After some investigation I found out the ASM agent can see all the cost center in the "account shipping address" step.
It is still possible to continue the checkout as long as the agent selects a cost center for which the emulated user has access.

Spartacus handles the errors caused by assigning an invalid cost center to the cart poorly. This ticket will improve the Spartacus handling of the issue.

**Comment by giancorderoortiz** [comment]
@Xymmer continues to happen with 4.2.

**Comment by giancorderoortiz** [comment]
Behaviour observed: No shipping address options given. Unable to checkout when ASM agent has a session.

**Comment by giancorderoortiz** [comment]
Changed type to a bug.

**Comment by giancorderoortiz** [comment]
With 4.2 RC0 (no shipping address to select):

<img width="1218" alt="Screen Shot 2021-11-03 at 11 26 27 AM" src="https://user-images.githubusercontent.com/46171897/140369220-33b1b2c6-dc2a-477d-b1d1-d5f10d122646.png">
<img width="1894" alt="Screen Shot 2021-11-03 at 11 27 05 AM" src="https://user-images.githubusercontent.com/46171897/140369236-65688938-9ca1-4b75-ab2f-84f048bb2a5f.png">

**Comment by giancorderoortiz** [comment]
@Xymmer @KateChuen to discuss during bug triage.

**Comment by Xymmer** [comment]
Bill to repro but sounds like ASM/CommOrg/OCC bug.
GC says same problem with 2011, 2105, and 2005.
Kate tried Marie Dubois logged in (no ASM), gets Custom Retail, can check out.

**Comment by Xymmer** [comment]
Tried it with Postman ~~and seems to work~~ doesn't work
~~let's investigate further what's going on in Spartacus before we create a backend jira~~
Bill to create CXEC ticket

**Comment by giancorderoortiz** [comment]
Issue happens with 4.0 as well.

**Comment by giancorderoortiz** [comment]
4.0 affected by this problem also. B2B and B2C

**Comment by giancorderoortiz** [comment]
<img width="1756" alt="Screen Shot 2021-11-05 at 10 45 28 AM" src="https://user-images.githubusercontent.com/46171897/140533474-a5ce86e8-8daf-48b3-b622-9f76d714ff6e.png">
<img width="1765" alt="Screen Shot 2021-11-05 at 10 59 36 AM" src="https://user-images.githubusercontent.com/46171897/140533480-91a9302c-8ea1-4373-af22-fabaf7d021a3.png">

**Comment by Xymmer** [comment]
Two things to do here:
- improve/get new endpoint for getting cost centers specifying the user, on behalf of asagent (backend dependency)
- can we handle/mitigate issue here so asagent can select address? (Bill tried with 4.2 but it never shows address, is the info there?) - do we even want to do that.

**Comment by Xymmer** [comment]
Closing, moved to internal jira
