### ISSUE TITLE
[Master] Language of Page

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#11360]
## Overview

Investigate and verify if Language Attributes are properly working. Check [WCAG 2.1 3.1.1](https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning-doc-lang-id.html) and in short, we need to verify that `lang=""` attribute is correctly defined on the `<html>` tag and changes correctly when switching languages

- **MASTER** Ticket #11672
- [**Github label:**](https://github.com/SAP/spartacus/issues?q=is%3Aissue+is%3Aopen+label%3Aa11y-sr%2Flanguage-of-page) `a11y-sr/language-of-page`.

## Implementation

- [x] Investigate and verify if wcag 2.1 3.1.1 are met 
- [x] Verify Functionality on Voice Over (mac)
- [x] Verify Functionality on NVDA (win)
- [x] Verity Functionality on JAWS (win)

**Comment by saad-mo** [comment]
@developpeurweb - I think this works as expected on Voice Over, could you please verify on NVDA and JAWS so we can close it?

**Comment by developpeurweb** [comment]
@saad-mo Tested on Windows and Mobile. Works as expected.
- For NVDA and JAWS, the installation of additional Windows language packages might be needed to reproduce each language vocalization properly.
- VO for iPhone and Android Talkback seem to work without any additional configuration.
