### ISSUE TITLE
Add UrlParsingService to public API

### ISSUE THREAD

**Issue by TMazi** [SAP/spartacus#11373]
The `UrlParsingService` used in `SemanticPathService` is not exposed, which makes the overriding of  `SemanticPathService` more difficult.

**Comment by Platonn** [comment]
@Xymmer Agreed. Let's export it in the public API.

@TMazi Until it's released, you might want to use the workaround https://stackoverflow.com/questions/66871919/how-to-use-private-api-of-the-spartacus-library/66871920#66871920

**Comment by Xymmer** [comment]
moved to jira
