### ISSUE TITLE
Default Address Form Title option not translatable

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#11413]
**Describe the bug**
Within the Address form component used for e.g. the shipping address, the title form field automatically adds a default option. This default option's display value is currently hardcoded in the component and cannot be translated.

**Tell us the version of Spartacus**
- Library version: 3.1.0

**To Reproduce**
1. Go to the spartacus demo store
2. Login / register
3. Go to page https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/de/USD/my-account/address-book
4. See title dropdown having all entries, but the first one, translated to german

**Expected behavior**
The title dropdown either uses a translatable default option or offers an option to not show that default option at all

**Screenshots**
![image](https://user-images.githubusercontent.com/3381820/110304217-9b107d00-7ffb-11eb-8c9b-6903dd606123.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
The hardcoded default option gets added in the file `address-form.component.ts`:
![image](https://user-images.githubusercontent.com/3381820/110304474-f0e52500-7ffb-11eb-9a04-5291b251e395.png)

**Comment by giancorderoortiz** [comment]
Still an issue.
