### ISSUE TITLE
redirect to current url not working after reloading page (with F5) in logged oidc mode

### ISSUE THREAD

**Issue by mnboubtane** [SAP/spartacus#11428]
**Describe the bug**
Hi all,

When we log with Authorization Code Flow oidc mode and we reload browser in cartPage, productPage or another page we are redirect to homepage instead of current navigation page
We integrate an private Idp with spartacus and sap-commerce.
there is three side in this flow :
spartacus <--> sap-commerce <--> private Idp

**Tell us the version of Spartacus**
- spartacus 3.1.0
-  angular-oauth2-oidc
- sap commerce 2011.3

**To Reproduce**
1. Go to 'Sign in and register'
2. we are redirect to the Idp via sap-commerce to get a token ...
2. when login was successful 
3. Go to productPage / CategoryPage Or cartPage
4. Reload page (click on reload browser link)
5. result => redirect to hompepage instead of current page

**Expected behavior**
when we reload page we have to still in the current page like on none logged mode

** root cause :  code**
` /**
   * Check params in url and if there is an code/token then try to login with those.
   */
  async checkOAuthParamsInUrl(): Promise<void> {
    try {
      const result = await this.oAuthLibWrapperService.tryLogin();
      const token = this.authStorageService.getItem('access_token');
      // We get the result in the code flow even if we did not logged in that why we also need to check if we have access_token
      if (result && token) {
        this.userIdService.setUserId(OCC_USER_ID_CURRENT);
        this.store.dispatch(new AuthActions.Login());
        this.authRedirectService.redirect();  // value setted to undefined for this scenario
      }
    } catch {}
  }`

and this function will be executed :

`/**
     * Redirect to saved url (homepage if nothing is saved).
     */
    redirect() {
        this.authRedirectStorageService
            .getRedirectUrl()
            .pipe(take(1))
            .subscribe((redirectUrl) => {
            if (redirectUrl === undefined) {
                this.routing.go('/');
            }
            else {
                this.routing.goByUrl(redirectUrl);
            }
            this.authRedirectStorageService.setRedirectUrl(undefined);
            this.lastAuthGuardNavigation = undefined;
        });
    }`

**Desktop (please complete the following information):
 - reproduced in desktop Browser [e.g. chrome 88.0.4324.192]

Thanks for help

**Comment by mnboubtane** [comment]
same issue : #11431

**Comment by marlass** [comment]
Closing this duplicate
