### ISSUE TITLE
Media componet displays a fake image in case no media provided or an error occurs

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#11423]
Media component loads a fake image in case no content is provided or an error occurs. 
See `@HostBinding('class.is-missing') isMissing = false;`
Refactor **cx-configurator-attribute-product-card** and **cx-configurator-cpq-overview-attribute** to display a missing media
**Configuration:**
![image](https://user-images.githubusercontent.com/61147963/110431835-9a84ee80-80ae-11eb-9b5d-9b0f1cbd4f85.png)

**Overview:**
![image](https://user-images.githubusercontent.com/61147963/110431769-83de9780-80ae-11eb-8a3c-6d757122f354.png)

**Comment by schuppell** [comment]
Nice, I really like the idea that we can reuse the core Spartacus component for this instead of developing our own logic when no image is available.

**Comment by Larisa-Staroverova** [comment]
Thanks!
