### ISSUE TITLE
User should be informed if it's not possible to remove bundle product

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#11461]
Configure CONF_CAMERA_BUNDLE.
Note that Sandisk Memory Card cannot be removed, its minimal qty is 1.
As the 'Remove' button is still active, a user might click it. In this case, the user should be notified that the bundle product cannot be removed

**Comment by schuppell** [comment]
We have to add a message "A selection is mandatory for xyz"

**Comment by schuppell** [comment]
https://4prsat.axshare.com/#id=k668bx&p=bundling_multi-select_value_mandatory&g=1
https://4prsat.axshare.com/#id=00d4t0&p=bundling_multi-select_attribute_mandatory&g=1
