### ISSUE TITLE
Prepare e2e tests for multiple parallel execution

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#11479]
Our tests will be run parallel in the SPA CI. They are all based on the same user (not possible to register b2b users)
-> The tests can never assume that a cart is empty initially. They cannot rely on a specific cart entry number

**Comment by Platonn** [comment]
Correction: recently we decided that CPQ e2e tests won't be run in SPA CI. A dedicated backend environment and CI will be maintained by the Team Tiger.

That said, we will still benefit from fixing this issue. For example, when we want to run e2e tests on local, it might conflict with e2e that might run at the same moment on CI. Or any leftover cart items of cpq03 user might affect result of the e2e tests too.
