### ISSUE TITLE
Product duplicated when removing a product from cart

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11508]
**Describe the bug**
When there are two or more products in your cart, and you remove one of them by clicking the remove button, then you will see the product being visually duplicated.

* When you refresh, the duplicated visual gets removed as it was deleted.

**To Reproduce**
B2C/B2B

1. login and add 2 or more distinct products to your cart.
2. go to cart page, and click remove on one of them.
3. product gets duplicated with what is left in the cart 

**Expected behavior**
It should remove the selected product

**Screenshots**
2 or more distinct products
<img width="799" alt="Screen Shot 2021-03-15 at 2 35 17 PM" src="https://user-images.githubusercontent.com/29099466/111204129-337aa480-859c-11eb-9204-2089820b08ac.png">

When removing a product
<img width="803" alt="Screen Shot 2021-03-15 at 2 35 22 PM" src="https://user-images.githubusercontent.com/29099466/111204152-3b3a4900-859c-11eb-8a47-81ae10c0230c.png">

When refreshing the page
<img width="797" alt="Screen Shot 2021-03-15 at 2 35 27 PM" src="https://user-images.githubusercontent.com/29099466/111204173-42615700-859c-11eb-9402-2c9a8000e0e8.png">

**Additional context**
SIMILAR to https://github.com/SAP/spartacus/issues/11404

**Comment by hackergil** [comment]
Related to #10379. Reverted the latest fix.

**Comment by hackergil** [comment]
Fixed by #11404
