### ISSUE TITLE
Quotes flow for Sapphire Testing (Kickoff)

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#11503]
In June 2021, we will be testing a 'quotes' flow at Sapphire event. 

Although we have not formalized our plans for Quotes in SPA I would like to use the flow from the older accelerator product as a kickoff for discussion in the near future.

here is a link:
https://u4yy8c.axshare.com/#id=r8kvie&p=introduction_to_quotes&g=1 

What is in scope, what is not.

Is this the direction we want to go or something different?

Manu and I will create Figma wires based on the outcome.

**Comment by thammonddsg** [comment]
Hello!

We need a separate manager interface to review all pending quotes and edit them. Rather than the current process where you have to impersonate the customer to do so. 

Thanks!
