### ISSUE TITLE
Cleanup the deprecated API introduced in #11469

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11515]
The PR #11469 deprecated many elements of the public API. In 4.0 we should drop them, document, and provide a relevant schematics migration.

In this doc PR https://github.com/SAP/spartacus-docs/pull/1103/files we updated the docs, marking the deprecated flow (<3.2),

In 4.0, if we remove deprecated classes, let's remove also the docs for them

**Comment by ren-tham** [comment]
Pr: (#12334)
Docs PR: https://github.com/SAP/spartacus-docs/pull/1122
