### ISSUE TITLE
Core functionality to get the summary of import to saved cart

### ISSUE THREAD

**Issue by Parthlakhani** [SAP/spartacus#11526]
Implement logic to summarize the data that has been processed and added to the saved cart
which should include

- Number of products successfully added to cart
- Number of products not imported
- Number of products partially imported because of the fewer quantity

**Comment by Pucek9** [comment]
https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Source+of+Truth+for+B2B+Import+to+Saved+Carts+-+April+2021
