### ISSUE TITLE
slot.components is undefined error in getPersonalizationContext

### ISSUE THREAD

**Issue by jolle22** [SAP/spartacus#11535]
**Describe the bug**

We have empty content slots on our spartacus hompeage.
When the hompage is opened the following error is thrown:

```
ERROR TypeError: e.components is undefined

    getPersonalizationContext https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    _next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    _next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    _next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    _next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    next https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
    notifyNext https://storefront.d1.store.net.sap/vendor-es2015.46670be97a18d00accda.js:1
```

**Tell us the version of Spartacus**
- Library version: 3.1

**To Reproduce**
1. Create an empty content slot and add it to a page
2. Visit this page in the browser

**Expected behavior**
Empty content slots are expected on any page.
No error is visible in the console.

**Additional context**
The problem seem to be rooted in the [PersonalizationContextService in line 32](https://github.com/SAP/spartacus/blob/e0f4d154968334dd9fb57f6b44cfe3ead78771c6/projects/core/src/personalization/services/personalization-context.service.ts#L32):
` slot.components.find(`
In other places there is often a ? between slot and components like
`slot?.components`

Thank you for your help :)

**Comment by giancorderoortiz** [comment]
@jolle22 please provide screenshots of the error you describe above.

**Comment by jolle22** [comment]
We updated the version. The error message is gone now. The bug can be closed. Thanks :)
