### ISSUE TITLE
Update LandingPage2Template to include H1 tag

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#11543]
As part of the [Headings and Labels success criterion](https://cxwiki.sap.com/display/spar/Headings+and+Labels) for Screen Reader support, we need to have an `h1` tag in the DOM for the rotor narration to convey proper page hierarchy. 

Requirements: 
- This is not related to the `<title>` tag 
- This `<h1>` tag will be 'visually hidden' since our current design does not call for a Page title heading. 
- Styles can be used to offset the tab from the viewport to make it visually hidden
- Content of this `<h1>` tag can simply be "Homepage" (or match the page title)
- We already have `<h3>` tags for carousel titles that will be converted to `<h2>` in a separate ticket 

Dev Related Info (more investigation needed): 
- Make a new component `PageTitleComponent` based on `bread-crumb component
- Only need `h1` from the `bread-crumb component. no `<nav>` elements.
- Use `.cx-visually-hidden` class to hide it (CSS code provided in PR comments) 
- Make it configurable? (can be added to any page/content slot via Impex) 
- This can be added to other Landing Page templates as well? (it's a component that can be added to any content slot)

To Investigate: 
- List of pages that do not have a bread crumb (maybe in sample data?)

**Comment by saad-mo** [comment]
@WeizhengSap, @plabadie - Any input on how this can be done would be much appreciated.

**Comment by Pucek9** [comment]
sampledata PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/167

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

<img width="720" alt="Screen Shot 2022-03-22 at 2 30 15 PM" src="https://user-images.githubusercontent.com/45409515/159551126-c3c20fa1-5997-4c01-8345-914c16e4f16b.png">

![Screen Shot 2022-03-22 at 2 26 34 PM](https://user-images.githubusercontent.com/45409515/159551408-2d1dafa6-a1f0-4d96-bf54-36cba91762f2.png)


carousel is h2.

<img width="1437" alt="Screen Shot 2022-03-22 at 2 29 50 PM" src="https://user-images.githubusercontent.com/45409515/159551172-8df7ffb5-69e5-4941-8362-128b1bab7cc3.png">
