### ISSUE TITLE
Console errors when viewing order history

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#11567]
**Prepare**:
- checkout develop
- yarn start

**Steps**:
1. open http://localhost:4200/electronics-spa/en/USD/
2. register a new user
3. add product 'Camileo S10 EU' to cart
4. add product 'FUN Flash Single Use Camera, 27+12 pic' to cart
5. proceed to checkout and fill out required data
6. use payment credit card with number '4111111111111111'.
7. Submit order
**Issue 1:**
The console shows Error 'ERROR TypeError: ctx_r4.cart.totalPriceWithTax is undefined'
8. View the Order via Order History
**Issue 2:**
The console shows Error 'ERROR TypeError: ctx_r4.cart.totalPriceWithTax is undefined'

**Comment by bgambocjaviniar** [comment]
related to a change from here https://github.com/SAP/spartacus/pull/10998

**Comment by Uli-Tiger** [comment]
@bgambocjaviniar: can you please assign this to the correct team/board?

**Comment by bgambocjaviniar** [comment]
@dydome 

Can look into this issue as it was from your PR

**Comment by giancorderoortiz** [comment]
This issue is not present in 3.0. 
See https://spartacus-demo.eastus.cloudapp.azure.com:444/powertools-spa/en/USD/
Saw this when testing saved-carts. 
Not sure this is related to CQP. 

![Screen Shot 2021-04-01 at 5 18 52 PM](https://user-images.githubusercontent.com/46171897/113355315-94c9a400-930e-11eb-8a5d-78e7e65d3b27.png)

**Comment by bgambocjaviniar** [comment]
not related  to cpq, nor saved carts. It's related to a ticket that was done for a bugfix as found in here https://github.com/SAP/spartacus/issues/11567#issuecomment-803746376

**Comment by dydome** [comment]
fixed merged to develop and release/3.2.x branches
