### ISSUE TITLE
WAIT FOR CONFLICT HANDLING CHANGE: Conflict Warning message appears during resolve action

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#11572]
Coffee machine is modelled in a way that it is not allowed to select more than qty 2 for attribute COFFEE_MACHINE_REFRIG_UNIT (4th group).
If you increase qty to 3 a warning message is displayed "To many RefrigUnits" (sic!)
-> ok
But if you decrease qty to 2 again the message is displayed again (although 2 is allowed).

**Comment by schuppell** [comment]
Conflict handling will be changed, maybe wait after that to check this issue.

**Comment by ChristophHi** [comment]
Hi @steinsebastian , could you check that, is it still the case with the new component that we introduced?

**Comment by steinsebastian** [comment]
Now the behavior is correct.
