### ISSUE TITLE
SmartEdit is broken with initialNaviagtion enabled

### ISSUE THREAD

**Issue by ghost** [SAP/spartacus#11590]
**Describe the bug**
Based on https://angular.io/api/router/InitialNavigation, we are using
`initialNavigation: 'enabled' // enabledBlocking` router configuration for SSR.
However, it has broken SmartEdit (Preview of Spartacus pages)

**Tell us the version of Spartacus**
- Library version: 2

**To Reproduce**
1. Use
```
    RouterModule.forRoot(routes, {
      ...
      initialNavigation: 'enabled',
   })
```
2. Preview/Edit a Spartacus page on SmartEdit

**Expected behavior**
Able to preview/edit the page.

**Comment by ghost** [comment]
Hi,

Adding more info, we have found the root cause to be in `SmartEditService#getDefaultPreviewCode` where
`this.baseSiteService.getBaseSiteData()` is returning undefined

**Comment by WeizhengSap** [comment]
Hello, can you check whether `basesites?fields=FULL` request successful? 

In version 2, we get `activeBaseSite` from the OCC's `BaseEndpoint`, e.g. for this `https://localhost:9002/occ/v2/electronics-spa`, the `activeBaseSite` is `electronics-spa`. Then we find the base site from the all base sites loaded with `site.uid === activeBaseSite`.

**Comment by ghost** [comment]
Hello @WeizhengSap
The basesites endpoint is called and proper response is received successfully.
However, I believe that it is called after the `getDefaultPreviewCode` is called.

**Comment by WeizhengSap** [comment]
In function `getDefaultPreviewCode`, `this.baseSiteService.getBaseSiteData()` is called. This `baseSiteService.getBaseSiteData()` reads `baseSite` state directly. If the state is empty, then load base sites data. 

So, I think the issue is the `activeBaseSite` cannot be find.

I don't know whether you have context configuration in your application. If not, you can try to add this to see whether it works:
```
context: {
        urlParameters: ['baseSite', 'language', 'currency'],
        baseSite: [
          'electronics-spa',   // your site uid, which must match one of the base sites loaded
       ]
```

**Comment by ghost** [comment]
@WeizhengSap we use auto context configuration https://sap.github.io/spartacus-docs/automatic-context-configuration/

**Comment by WeizhengSap** [comment]
@jongyunchoi-sap: please try to add that static context configuration to test whether it works in SmartEdit. If yes, then that means the auto context configuration does not set `activeBaseSite` correctly. 

BTW, `OccConfigLoaderService` is deprecated in 3.2. Auto context configuration will also call `baseSiteService.get()`.

**Comment by WeizhengSap** [comment]
@jongyunchoi-sap : I am testing 2.0 now, and remove `context` configuration to make it auto configured. The basesites requests are sent twice (one is for auto context configuration; the other one is for smartedit. We fixed it in 3.2).

![Screen Shot 2021-03-26 at 2 49 59 PM](https://user-images.githubusercontent.com/44440575/112672866-cc35dd80-8e42-11eb-900f-78e858692c0e.png)

**Comment by ghost** [comment]
@WeizhengSap the issue is reproducible with static context.
Are you saying that we have to upgrade to 3.2+ to fix this?

**Comment by WeizhengSap** [comment]
@jongyunchoi-sap: In 3.2, we fixed that duplicated `basesties` requests issue. In 2.0, SmartEdit should work as well. Can you test whether subscribe this `baseSiteService.getBaseSiteData()` can get the active basesite data?

**Comment by ghost** [comment]
@WeizhengSap have you tried with `initialNavigation: 'enabled'` option?

**Comment by WeizhengSap** [comment]
@jongyunchoi-sap: Now, I added `initialNavigation: 'enabled',` into RouterModule, then the BaseSite is empty in the OCC request. Even the homepage cannot be opened. So, it is not related to SmartEdit. Can you check whether the application works well before launch it into SmartEdit?

![Screen Shot 2021-03-30 at 9 51 01 AM](https://user-images.githubusercontent.com/44440575/112991395-719bca80-913d-11eb-9247-8474b6379247.png)

**Comment by ghost** [comment]
@WeizhengSap yes, our storefront is fully functional, including in production environment.

**Comment by WeizhengSap** [comment]
@jongyunchoi-sap: if `initialNavigation: 'enabled'` is set, we need something like this: https://github.com/SAP/spartacus/pull/9593/files#diff-88970acf5387dda093bb5c31ef2d9285d49a46e616d10c366d30e9332fa6a5a5, otherwise navigation starts before the configuration is stable (baseSite is not got yet). You can upgrade Spartacus to version >=3.0, and try again.
