### ISSUE TITLE
Not configurable product in the cart is shown erroneous: no Remove link, no Qty

### ISSUE THREAD

**Issue by AlexanderKuschner** [SAP/spartacus#11601]
This issue occurs with the epic/cpq-configurator branch, with develop branch it works fine.

**Comment by ChristophHi** [comment]
Cannot be reproduced in ccv2 team instance, also not locally for me.

**Comment by ChristophHi** [comment]
This is because the ccv2 team instance sends empty config infos as empty arrays, while other environments as undefined
=> we should be more resilient here. 
I can reproduce with my local commerce environment as well.
Needs fix in ConfiguratorCartEntryInfoComponent
