### ISSUE TITLE
(MVP) Switching between selections quickly causes attributes to disappear and error message to appear

### ISSUE THREAD

**Issue by JayEmKay-8** [SAP/spartacus#11612]
In product "Configurable Attribute Types Product", I could cause strange effects on the UI by switching quickly between different radio button selections in the "RB Simple" group. This was especially the case if I clicked in the first attribute (read-only/hidden/editable), where other selections get shown or hidden.

One time no attributes were shown on the UI at all (see pdf).

When leaving the RB Simple group and going back in, if I then selected a different option in the first attribute, I got the message "You are not authorized to perform this action. Please contact your adminitrator if you think this is a mistake." After that, all attributes disappear, empty group as in other screenshot.

[2021-03-16_Team-Testtag_Rumgeklickere_JK.pdf](https://github.com/SAP/spartacus/files/6182665/2021-03-16_Team-Testtag_Rumgeklickere_JK.pdf)

**Comment by AlexanderKuschner** [comment]
The issue does not occurs anymore with the current code state
