### ISSUE TITLE
check why Travis validation checks fail for CPQ pipeline and what we can do about it

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#11639]
for example:
https://github.com/SAP/spartacus/pull/11633/checks?check_run_id=2177314992

**Comment by Changsuwan** [comment]
To reproduce the issue:
In the server, travis does not make it to run checks in product-configurator. However, when we execute the script (validate-lint.sh )locally it manage to run the checks in product-configurator. We discovered one issue and fixed it. We then let the checks run again. Current status: waiting for the checks to finish.

**Comment by Uli-Tiger** [comment]
@Changsuwan  do we have a PR, where this worked fine now?

**Comment by Changsuwan** [comment]
The checks were successful. And the checks work fine. We fixed it directly on epic branch and did not create any pull request or any branch as far as I remember.

**Comment by Uli-Tiger** [comment]
i just meant an example PR to see the improve state.
anyways i just did a PR: https://github.com/SAP/spartacus/pull/12115/checks?check_run_id=2418426946
looks much better now. :-) 
Is there a way to exclude the execution of the b2c cy tests that are guaranteed to fail? maybe by manipulating some config files in our feature branch?

**Comment by Changsuwan** [comment]
cy test = cypress tests? If yes, one can just add "x" in front of "describe". The tests with "xdescribe" will not be executed.

**Comment by ChristophHi** [comment]
That was a lint issue, @schuppell has fixed it
