### ISSUE TITLE
Navigating to a new page doesn't reset focus

### ISSUE THREAD

**Issue by VGRAJED** [SAP/spartacus#11636]
### Steps to reproduce
Use the tab keys to navigate through the page until reaching the breadcrumbs
Click **Enter** to (router) navigate to another page
When the new page is loaded, click **Tab** again

### Expected result
The focus in now on the first focusable element of the page

### Actual result
The focus remained on the last focusable element (in this case, the breadcrumb)

**Comment by Zeyber** [comment]
TO TEST: 
Add to `app.module.ts` to turn on focus resetting on navigation.

```
provideConfig({
      keyboardFocus: {
        enableResetFocusOnNavigate: true,
      },
    }),
```

**Comment by giancorderoortiz** [comment]
Yes, I see the fix. 
Thanks.
