### ISSUE TITLE
JSON i18n translations don't work in SSR in 3.1.0

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11665]
**Describe the bug**
Lazy loaded translations don't work in SSR in 3.1.0. (both from npm and our repo).

Notes:
- Both static and lazy loaded translations work CSR
- Static work in SSR.

**Tell us the version of Spartacus**
- Library version: 3.1.0 form npm OR the repo branch `release/3.1.x`

**To Reproduce**
1. create fresh angular app `$ ng new <appName>`
1. enter the directory `<appName>`
1. install spartacus with ssr v3.1.0 using schematics `$ng add @spartacus/schematics@3.1.0 --ssr`
1. set backend baseUrl in app.module of the fresh app
1. disable ssr optimizations by passing `null` as a second argument of `const ngExpressEngine = NgExpressEngineDecorator.get(engine, null);` in the file `server.ts` of your fresh app
1. if your test backend doesn't have proper SSL cert, please add at the top of the file `server.ts` the line: 
   `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';`
1. copy i18n JSON assets to your app:
    `cp ./node_modules/@spartacus/assets/i18n-assets ./src/assets -r`
1. in app.module set `i18n.debug` to `true` and `i18n.backend.loadPath` to `'assets/i18n-assets/{{lng}}/{{ns}}.json',`:
   ```
      i18n: {
        chunks: translationChunksConfig,
        backend: {
          loadPath: 'assets/i18n-assets/{{lng}}/{{ns}}.json',
        },
        debug: true,
      },
   ```
1. disable Javascript in your browser
2. run `$ yarn dev:ssr`
3. open in the browser http://localhost:4200/

**Expected behavior**
The page has all the labels translated

**Screenshots**
Browser:
![image](https://user-images.githubusercontent.com/4001059/112509293-9e905c00-8d90-11eb-9199-06c2d17e3f1d.png)

SSR console:
![image](https://user-images.githubusercontent.com/4001059/112509417-bbc52a80-8d90-11eb-9f09-654479f58c59.png)

**Comment by janwidmer** [comment]
@Platonn Issue still exists with Version 3.2.1, but ONLY in the CCV2 Cloud. It works locally in production mode, but it does not work in the CCV2 Cloud. I deployed a default Spartacus Project to our Cloud with the following config. The translations are still just empty.

```
import { NgModule } from '@angular/core';
import { translationChunksConfig } from '@spartacus/assets';
import { provideConfig } from '@spartacus/core';
import { defaultCmsContentProviders, layoutConfig, mediaConfig } from '@spartacus/storefront';

@NgModule({
	declarations: [],
	imports: [],
	providers: [
		provideConfig(layoutConfig),
		provideConfig(mediaConfig),
		...defaultCmsContentProviders,
		provideConfig({
			backend: {
				occ: {
					baseUrl: 'https://spartacus-demo.eastus.cloudapp.azure.com:8443',
				},
			},
			context: {
				urlParameters: ['baseSite', 'language', 'currency'],
				baseSite: ['electronics-spa'],
				currency: ['USD'],
				language: ['en'],
			},
			i18n: {
				backend: {
					loadPath: 'assets/translations/{{lng}}/{{ns}}.json',
				},
				chunks: translationChunksConfig,
				fallbackLang: 'en',
			},
			features: {
				level: '3.2',
			},
		}),
	],
})
export class SpartacusConfigurationModule {}
```

Update: 
For us it works also in the CCV2 Cloud on all pages but the home page. So, on the homepage, we still have empty translations after SSR, but only when having the SSR Optimisation Cache activated..

**Comment by lauramontanana** [comment]
@Platonn we are still having issues loading the translations when using SSR in local using `http://localhost:4000` and also in some CCV2 Cloud environments. 

Does `getLoadPath` resolve correctly the path were the translations assets are when not using the default port? Testing locally I see `getRequestOrigin` returns `http://localhost` instead of `http://localhost:4000` which might be the issue.
