### ISSUE TITLE
Replace deprecated dependency i18next-xhr-backend with i18next-http-backend

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11679]
`i18next-xhr-backend` lib has been deprecated in favour of `i18next-http-backend`, so we should switch do the new one.
Introducing new required dependencies is a breaking change. So can be done only in major.

**Comment by dydome** [comment]
I tried to replace it and followed the instruction but then there is an error from the source in the compilation:

![image](https://user-images.githubusercontent.com/18736434/117431202-428d2b80-af29-11eb-95c2-646b409c848b.png)

**Comment by Platonn** [comment]
@dydome did you try also upgrading `i18next`? Maybe it changed its internal  types by the time the I18nextHttpBackend was introduced to replace I18nextXhrBackend? I hope upgrading i8next should help.

At the end, please double check translations work well in Spartacus:
- with TS translations: both CSR and SSR
- with JSON translations: both CSR and SSR

( for more about JSON translations, see: https://sap.github.io/spartacus-docs/i18n/#lazy-loading)

You might also want to take a look at the i18next changelog to look for any breaking changes https://github.com/i18next/i18next/blob/master/CHANGELOG.md

**Comment by dydome** [comment]
Problem resolved with latest `i18next` package.
