### ISSUE TITLE
Make initialization of i18next extendable

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#11675]
Currently the file `i18next-init.ts` contains complex logic, which is not extendable. It was on purpose, as using i18next under the hood is just an implementation detail of Spartacus and we don't want to expose its internals via our public API (in future we might change the i18n engine behind the scenes). 

But it's painful when some new i18n bugs are discovered and customers cannot apply quick fix or workaround themselves. To change any logic (i.e. to workaround a bug), customers would need to dismantle deeply the modules tree up to the `I18nModule` and then provide a custom whole complex factory function `i18nextInit()` - which would be very cumbersome. The alternative for customer is to wait for us releasing an urgent fix.

Plan of attack:
- create a service `@Injectable({providedIn: 'root'}) export class I18nextInitializer` with dependencies:
      
      
      @Inject(I18NEXT_INSTANCE),
      ConfigInitializerService,
      LanguageService,
      HttpClient,
      SiteContextI18nextSynchronizer,
      @Optional() @Inject(SERVER_REQUEST_ORIGIN)
      
- add there protected methods that used to be just loose functions from `i18next-init.ts` 
- the main public method should be `I18nextInitializer.initialize()` that used to be `function i18nextInit()` and it should be invoked by the former `APP_INITIALIZER`
  - note: we can drop the `deps` from the former APP_INITIALIZER
  - note: we don't need to call `toPromise()` at the end `initialize()` method. `APP_INITIALIZER`s can consume Observables as well. And we prefer exposing Observables rather than Promises in Spartacus services' API.
- **let's export in the public API** the `I18nextInitializer` and `SiteContextI18nextSynchronizer` **so customers can extend them**

**Comment by timdk** [comment]
Will these changes be merged into 4.x when they are finalised?

**Comment by Platonn** [comment]
@timdk unfortunately this refactor is not planned to be backported to 4.x
