### ISSUE TITLE
[CPQ] [4.0] cleanUp deprecated code

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#11681]
With the CPQ release (3.3) we deprecated some code, especially constructors, to inject additional dependencies.
with 4.0 we should revisit this.

Clean up is done in related update schematics issues (#11232, #12198, #12199)

**Styling changes:**
- [ ] Add styling changes from this [Wiki page](https://cxwiki.sap.com/pages/viewpage.action?spaceKey=prodandtech&title=Changes+to+styles+in+4.0) into `/docs/migration/css-changes-in-version-4.md` file

**Comment by ChristophHi** [comment]
Also cover feature keys in/feature-libs/product-configurator/rulebased/root/rulebased-configurator-root-feature.module.ts,  /feature-libs/product-configurator/textfield/root/textfield-configurator-root-feature.module.ts
