### ISSUE TITLE
Make PaymentDetails Interface on Cart / Order Interface augmentable

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#11697]
**Is your feature request related to a problem? Please describe.**
We need to add a new property on the Interface `PaymentDetails`. Backend part is done, property get's delivered to the frontend. Now we need to extend the `PaymentDetails` Interface in the Frontend.

**Describe the solution you'd like**
To have Type Safety, we would like to augment the Interface `PaymentDetails` with our new property (As described here: https://sap.github.io/spartacus-docs/type-augmentation/#exporting-type-for-augmentation). That is currently not possible, as only the whole Cart / Order Interface get's exported, but not the Sub Property Price on it.

Please add the `PaymentDetails` interface to the list of augmentable Interfaces.

**Describe alternatives you've considered**
As a workaround, we are casting the `paymentInfo` Object in our component:

```
const customPaymentInfo = paymentInfo as ICustomPaymentDetails;
```

That is working, but obviously not nice..

**Comment by Xymmer** [comment]
moved to jira
