### ISSUE TITLE
Make User Interface augmentable

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#11698]
**Is your feature request related to a problem? Please describe.**
We need to add a new property on the Interface `User`. Backend part is done, property get's delivered to the frontend. Now we need to extend the `User` Interface in the Frontend.

**Describe the solution you'd like**
To have Type Safety, we would like to augment the Interface `User` with our new property (As described here: https://sap.github.io/spartacus-docs/type-augmentation/#exporting-type-for-augmentation). That is currently not possible, as the Interface is not exported to do so.

Please add the `User` interface to the list of augmentable Interfaces.

**Describe alternatives you've considered**
As a workaround, we are casting the `User` Object in our component:

```
interface CustomUser extends User {
	newCustomer?: boolean;
}
```

That is working, but obviously not nice..

**Comment by tobi-or-not-tobi** [comment]
We've done this for 3.2 release, where user is (optionally) moved out of the storefront/core lib.

**Comment by janwidmer** [comment]
ok cool, should I close this one then?

**Comment by marlass** [comment]
`User` model exposed to augmentation from "@spartacus/user/account/root" entry point.
