### ISSUE TITLE
The popover for old sub list still remains in the screen after switching to new sub section in B2B table (while keyboarding?)

### ISSUE THREAD

**Issue by wangzixi-diablo** [SAP/spartacus#11714]
**Tell us the version of Spartacus**
- Library version: 3.2.0-next.2, develop branch

**To Reproduce**

1. open unit list and click one row to enter unit detail page:

![image](https://user-images.githubusercontent.com/58975336/112850773-e559bb00-90dc-11eb-96fe-a3d5699db512.png)

2. the (i) icon as the first focusable element in unit detail page is automatically focused. Press enter key, and you can see popover.

![image](https://user-images.githubusercontent.com/58975336/112850947-133eff80-90dd-11eb-9ff3-38a3f06cb4f8.png)

3.  click Users section to enter unit user sub section. Press enter key. See expected popover in user card:

![image](https://user-images.githubusercontent.com/58975336/112851484-98c2af80-90dd-11eb-8422-871941353c67.png)

4. Click Approver section, now the approver sub section is displayed. HOWEVER, the popover for Users is still displayed in the screen:

![image](https://user-images.githubusercontent.com/58975336/112851715-d4f61000-90dd-11eb-99fb-e148e39a3945.png)

When we click the (i) icon in Approvers card, the corresponding popover can be displayed. Unfortunately, the popover for Users is still in the screen:

![image](https://user-images.githubusercontent.com/58975336/112851910-01119100-90de-11eb-9c51-727d5eb88e60.png)

**Expected behavior**

When we switch from Users sub section to Approver sub section, the popover for former card should disappear.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: Chrome
 - Version 89.0.4389.90 (Official Build) (64-bit)

**Additional context**

**Comment by wangzixi-diablo** [comment]
A finding: in step (3), if we manually click (i) icon instead of pressing enter key, and then perform step 4 as usual, then this issue **COULD NOT** be reproduced.

![image](https://user-images.githubusercontent.com/58975336/113826436-ba462a00-97b4-11eb-8f98-3da5dc8dfafe.png)

**Comment by giancorderoortiz** [comment]
Issue has been fixed.
