### ISSUE TITLE
Library Update y18n

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11741]
Update y18n

See https://github.tools.sap/cx-commerce/spasec/issues/54

**Comment by marlass** [comment]
@giancorderoortiz Can we close this issue?

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-04-22 at 3 06 50 PM](https://user-images.githubusercontent.com/46171897/115771878-75a5bb80-a37c-11eb-943f-3840c3b19ec1.png)
