### ISSUE TITLE
Information Popover is not keyboard accessible (My COmpany and generally)

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#11774]
**Issues captured on video:**
https://video.sap.com/media/t/1_o07yiw6z
_See minutes 0:13 and 4:00_

- ESC key needs to be pressed 2x (twice) otherwise it won’t close, this is not an accessible pattern.
- If popover is opened with SPACEBAR, pressing ESC will trigger the skippers and it won’t close the popover.
- There is no other additional mechanism to close the popover other than the ESC key (Android gesture doesn’t have ESC), a closing button should be included.
- When opening popover with ENTER, popover should receive focus, next TAB should go to closing button. (mandatory)
- When opening popover with SPACEBAR, popover may not be focused but 1x ESC or Tabbing away should close the popover. (optional, if too much work stick to mandatory above)
- **We already have an accessible “details” popover for My Company, that can be used as a reference.**

![Screen Shot 2021-04-01 at 9 15 09 AM](https://user-images.githubusercontent.com/15113219/113300252-bb1a2000-92cb-11eb-8cb1-c5783480a169.png)
![Screen Shot 2021-04-01 at 9 15 48 AM](https://user-images.githubusercontent.com/15113219/113300257-bbb2b680-92cb-11eb-84e8-34f2c4ec280e.png)

**Comment by giancorderoortiz** [comment]
Please fix conflicts in pr(if any), and approve/reject.
Would like to test this fix soon.

**Comment by giancorderoortiz** [comment]
Issue is fixed.
