### ISSUE TITLE
Saved Cart: save for later modal has keyboard trap

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#11775]
**Issues captured on video:**
https://video.sap.com/media/t/1_592w0zd4
_See minutes 0:10 and 3:00_ 

**This prevents a keyboard-user from starting/finishing a task, therefore qualifies as a keyboard trap and must be fixed.**

Happens when creating a brand NEW saved cart with empty fields. The Save button does not receive focus but until tabbing through 14 to 16 times, then it becomes focusable.

![Screen Shot 2021-04-01 at 9 16 54 AM](https://user-images.githubusercontent.com/15113219/113302138-c2dac400-92cd-11eb-996a-a430f3ce8e0d.png)

**Comment by bgambocjaviniar** [comment]
Works as intended. There's no 'trap'. It's just missing the blue outline surrounding the button. 

As shown in this video 

https://user-images.githubusercontent.com/29099466/113318323-5d430380-92de-11eb-8812-89e2f90524a9.mov

**Comment by bgambocjaviniar** [comment]
PR: #11778

More information: https://github.com/SAP/spartacus/pull/11778#pullrequestreview-626500203
