### ISSUE TITLE
[MASTER] B2B Inventory Display 

### ISSUE THREAD

**Issue by ren-tham** [SAP/spartacus#11779]
## Overview

**requirements/mock**: https://cxwiki.sap.com/display/spar/B2B+Inventory+Display+SoT+Nov2020
**github labels**: `inventory-display`. 

## EPIC branch

All tickets should be merged towards `epic/inventory-display`. 

## IMPORTANT

1. Keep in mind accessibility
2. Do not forget about having a threat modelling session
3. Make sure the implemented CSS for the given component supports `Directionality`
4. Be careful of deprecations and adjust accordingly

More information can be found in here https://sap.github.io/spartacus-docs/definition-of-done/

## Implementation

1 - Feature lib
2 - Data Layer
3 - Inventory Display for Product Details Page (PDP). 
4 - Multi-Dimensional Product (MDP).
5 - Sample Data for PDP and MDP
6 - Unit Tests for PDP & MDP
7 - E2E 
8 - Feature Doc

**Comment by bgambocjaviniar** [comment]
closing as epic was merged

only thing missing is 
- support for multi-d, however, the feature is currently not available as of yet.
