### ISSUE TITLE
Console Error e.cart.totalPriceWithTax is undefined. Firefox Order Confirmation Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11789]
Spartacus version: 3.2.0 RC0
Browser:  Firefox. v 85.6
URL :  https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

Steps to reproduce: 
1. Navigate to powertools storefront
2. Add n items to cart (where n > 10)
3. Save cart as "cart1"
4. Navigate to Saved Carts from my-account menu
5. Open "cart1" page and click on button "Make Cart Active" 
6. Complete checkout process.

Expected Results: 
6. Order confirmation page browser console doesn't show any errors. 

Actual Results: 
6. Console error "ERROR TypeError: e.cart.totalPriceWithTax is undefined" is shown. 

---

![Screen Shot 2021-04-01 at 2 59 48 PM](https://user-images.githubusercontent.com/46171897/113342000-ea488580-92fb-11eb-9364-8254e49fc5b6.png)
![Screen Shot 2021-04-01 at 3 03 36 PM](https://user-images.githubusercontent.com/46171897/113342002-eae11c00-92fb-11eb-8957-9a21e4c63e15.png)
![Screen Shot 2021-04-01 at 3 05 13 PM](https://user-images.githubusercontent.com/46171897/113342004-eae11c00-92fb-11eb-844b-99fea6b3cb64.png)

e.cart.totalPriceWithTax is undefined

**Comment by giancorderoortiz** [comment]
Error also appears in order approval page: 

![Screen Shot 2021-04-01 at 3 20 31 PM](https://user-images.githubusercontent.com/46171897/113343531-ef0e3900-92fd-11eb-9cd9-0390560a45e8.png)

**Comment by giancorderoortiz** [comment]
Same error appears in Safari: 
![Screen Shot 2021-04-01 at 3 35 36 PM](https://user-images.githubusercontent.com/46171897/113345113-fe8e8180-92ff-11eb-89a3-887b1bf672e9.png)

**Comment by bgambocjaviniar** [comment]
issue is known, closing for https://github.com/SAP/spartacus/issues/11567

**Comment by giancorderoortiz** [comment]
Appears to be duplicate of https://github.com/SAP/spartacus/issues/11567.
Please re-assess during bug triage.

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/spartacus/issues/11567#issuecomment-812189565

Not related to CPQ, nor saved-carts. This exist prior to saved carts and cpq. It was from a bug fix which caused another bug as it wasn't fully checked. https://github.com/SAP/spartacus/pull/10998

Moreover, if you look at the ticket that was created in that issue above, it was found `pre saved-cart merge`

**Comment by dydome** [comment]
fixed merged to develop and release/3.2.x branches
