### ISSUE TITLE
Saved Carts. Minor Misalignment. Long Cart Name

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11787]
Using Firefox 85.0 (64-bit)
URL: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD
Spartacus version: 3.2

Create a saved cart with a very long name. 
(i.e. "thisisthenameofaverylongsavedcartinspartacusstorefront"
Navigate to saved carts page from my-account.
Delete saved cart. 

Notice saved-cart name exceeds dialog overlay. 

---
![Screen Shot 2021-04-01 at 2 16 41 PM](https://user-images.githubusercontent.com/46171897/113337414-bcf8d900-92f5-11eb-9376-7c7742a54069.png)

**Comment by giancorderoortiz** [comment]
@bgambocjaviniar fyi

**Comment by bgambocjaviniar** [comment]
PR: #11790
