### ISSUE TITLE
E2E tests for Inventory Display

### ISSUE THREAD

**Issue by ren-tham** [SAP/spartacus#11785]

**Comment by giancorderoortiz** [comment]
Is this e2e test going into 3.4?

**Comment by ren-tham** [comment]
Pr: https://github.com/SAP/spartacus/pull/12960

**Comment by bgambocjaviniar** [comment]
backend PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/189
- to have a stock level thershold for the webcam category in electronics - `/c/577`
