### ISSUE TITLE
CxDate is not updated when language changes

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#11799]
**Describe the bug**
We are using the cxDate pipe

`{{ order.date | cxDate: 'longDate' }}`

So when we are in the english version, I clearly see:

`April 1, 2021`

But when I change it to another language (ex: French), I have to update the page to see the french version:

`1 avril 2021`

**Tell us the version of Spartacus**
- Library version: 2.1

**To Reproduce**
Use this pipe and then change the active language, and see that the formatted value does not change

**Expected behavior**
Update the value after changing language.

**Screenshots**

English normal version:

![image](https://user-images.githubusercontent.com/17834635/113424234-15040e00-93d0-11eb-848b-e54e5ba6b1be.png)

Change to French: Everything is updated except the cxDate

![image](https://user-images.githubusercontent.com/17834635/113424532-9bb8eb00-93d0-11eb-908d-c48b317079c0.png)

**Desktop (please complete the following information):**
 - Browser Chrome

**Comment by bit172** [comment]
Closing this issue as it is no longer relevant in current releases.
