### ISSUE TITLE
Can't delete the minimum quantity of item-counter in products details

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11806]
**Describe the bug**
When updating a quantity of a product from the product details page, we can't delete the minimum quantity in the item-counter to type a 'whole' number. It will always be 1 + typed number as 1 is the minimum number.

**To Reproduce**
1. Go to any product details page
2. try to change the quantity to 20
3. Won't be able to update the quantity to 20 as it will be 120. We can't remove the minimum quantity in the product details page

**Expected behavior**
We're supposed to have only a quantity of 20 of the product. Not 120.

**Smartphone (please complete the following information):**
 - Device: any

**Additional context**
Should behave similarly to the item-counter in the cart page. We can delete the input IN MOBILE in the item-counter to type a different number, but not in the product details page.

**Comment by bgambocjaviniar** [comment]
PR: GH-12678

**Comment by giancorderoortiz** [comment]
I'm not convinced this works well. 
If I update the quantity via keyboard and press enter, I expect the subtotal to change. 
However, enter key has no effect. 
I have to click outside the qty text field for the change to take effect.  @developpeurweb this may not be tab-navigation compatible.

**Comment by bgambocjaviniar** [comment]
> I'm not convinced this works well.
> If I update the quantity via keyboard and press enter, I expect the subtotal to change.
> However, enter key has no effect.
> I have to click outside the qty text field for the change to take effect. @developpeurweb this may not be tab-navigation compatible.

Solution provided is the same as any component that would use the item-counter component, such as the one in the cart page. 
I believe what is described above is a separate issue to this ticket.

Before, we're not able to even delete the quantity from the counter in the product details page.
Now, it behaves similarly to the others, such as the one in the cart page.

**Comment by giancorderoortiz** [comment]
ok. Will handle separately.
