### ISSUE TITLE
Saved carts: can't delete description when editing

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#11807]
using saved carts, save a cart
Edit the cart later
The description is optional, yet if I delete the description and save, it remains.
Not high priority. Tested with Chrome on iOS.

**Comment by bgambocjaviniar** [comment]
Context: that's how the API is currently done. When providing no saveCartDescription or providing an empty saveCartDescription, it will always return an existing cart description that was set before or the default value which is '-' if you never provided a description before

future improvement

- fix backend to allow empty description to make the description empty

OR

- fix frontend when we provide an empty saved cart description, we send '-' as a value

**Comment by Xymmer** [comment]
Let's do the workaround by sending - but also create an OCC ticket (CLC) to improve it. After you create the CLC ticket, add the ticket # to #12660

**Comment by bgambocjaviniar** [comment]
PR: GH-12680

**Comment by giancorderoortiz** [comment]
Issue is fixed. 

![Screen Shot 2021-06-11 at 6 06 41 PM](https://user-images.githubusercontent.com/46171897/121753290-16dd0280-cae0-11eb-9afa-661d3b2a8a58.png)

![Screen Shot 2021-06-11 at 6 08 27 PM](https://user-images.githubusercontent.com/46171897/121753292-17759900-cae0-11eb-93ea-be85f7927a7e.png)
