### ISSUE TITLE
[2.1.x] Fix multiple cart request when there is a promotion Sparatacus

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#11801]
This is related to issue https://github.com/SAP/spartacus/issues/8898. The issue was fixed in 3.x but the backport to 2.1.7 is not working.

The issue is caused by the `CheckoutDetailsService` that fires a new request to "load the checkout details" which sends a request to the cart. This request can conflict with other GET cart requests and if the cart contains a promotion it can lead to 400 errors.

At the moment once a user loads checkout the details will be loaded after every cart interaction.

The checkout details should only be loaded when:
- The user starts a checkout
- The user selects a shipping address

**Comment by Xymmer** [comment]
Since this was fixed in 3.x, we'll close. Contact me if this is an issue.
