### ISSUE TITLE
E2E tests for Quick Order

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#11819]
Minimum test cases:

#### Adding and listing SKUs

Add SKU using form > [repeat multiple times] > test listing in quick order listing page

#### Add to cart

Add SKU using form > [repeat multiple times] > Add quick order to cart > Go to cart > verify added SKUs

**Comment by giancorderoortiz** [comment]
To be released with 3.4? 
It's in our master list of improvements for 3.4.
