### ISSUE TITLE
CPQ - specific product is not added to cart

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11811]
**Describe the bug**
When adding the product 'Digital Camera' under `CPQ Configurable Category`, it does not add the product to cart and shows an empty modal.

Therefore, there may exist other CPQ 'products' that may cause this issue, which would require some investigation

**Tell us the version of Spartacus**
- 3.2.0 RC

**To Reproduce**
1.  visit the listing page : https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/CPQ-Configurable-Category/c/CPQConfigurableCategory
2. Click on 'Add to Cart'
3. See empty modal, which displays text that only says `This item was already in your cart. The quantity was updated.
`

**Expected behavior**
Should display product description and buttons as normally done when adding a product to a cart.

**Screenshots**
This specific product doesn't work with CPQ
<img width="1002" alt="Screen Shot 2021-04-05 at 3 23 26 PM" src="https://user-images.githubusercontent.com/29099466/113616655-6526de80-9623-11eb-8153-3b7e38915de6.png">
<img width="1176" alt="Screen Shot 2021-04-05 at 3 27 18 PM" src="https://user-images.githubusercontent.com/29099466/113616683-6e17b000-9623-11eb-8199-8f205e675258.png">

**Additional context**
tested with the ccv2 instance for b2c

**Comment by giancorderoortiz** [comment]
This is a known issue. @Platonn

**Comment by ChristophHi** [comment]
This issue is expected (known co-deployment issue), as the digital camera is a variant base product, and selective carts are deployed. A fix is planned in https://cxjira.sap.com/browse/TIGER-6667.
No issue for customers, as the variant process is not supported in SPA as of now.

**Comment by steinsebastian** [comment]
Discussed with Jutta (PO) and Christoph (Architect). As stated by Christoph on June 9 this is not an issue that customers could face. Therefore removing major label.

**Comment by Xymmer** [comment]
Closing as customers won't face this issue
