### ISSUE TITLE
(MOBILE - iphone se 2020 screen size) Minor misalignment for purchase limits buttons

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11814]
When navigating through my-company, the purchase limits UI  looks out of place compared to its other counterparts. The text, info icon, and buttons are overlapping with the table

![image0](https://user-images.githubusercontent.com/29099466/113622158-935bec80-962a-11eb-9038-c45a6b1d10dd.png)

P.S.
Using an iphone se 2020

**Comment by Xymmer** [comment]
moved to https://jira.tools.sap/browse/CXSPA-274
