### ISSUE TITLE
introduce Quick Order sample-data through impex

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#11827]
This is to create the start of the sample data for quick order to help the team instead of creating them through the back office

Required elements:
- [x] add Quick Order nav item to myaccount navigation
- [x] add path for /my-account/quick-order
- [x] add QuickOrderComponent 
- [x] add Quick Order to site links

**Comment by dydome** [comment]
There was a ticket with PR in the past for quick order implementation -> https://github.com/SAP/spartacus/issues/9013 but from the comments, it looks like it was not working properly.

I tried with something like this:
```
INSERT_UPDATE CMSLinkComponent;$contentCV[unique=true];uid[unique=true];name;url;&linkRef;&componentRef;target(code)[default='sameWindow'];restrictions(uid,$contentCV)
;;QuickOrderLink;Quick Order Link;/my-account/quick-order;QuickOrderLink;QuickOrderLink;;loggedInUser

INSERT_UPDATE ContentPage;$contentCV[unique=true];uid[unique=true];name;masterTemplate(uid,$contentCV);label
;;QuickOrderPage;Quick Order Page;AccountPageTemplate;/my-account/quick-order

INSERT_UPDATE CMSFlexComponent;$contentCV[unique=true];uid[unique=true];name;flexType
;;AccountQuickOrderComponent;Account Quick Order Component;AccountQuickOrderComponent

INSERT_UPDATE ContentSlot;$contentCV[unique=true];uid[unique=true];name;cmsComponents(uid, $contentCV)
;;BodyContent-quick-order;Body content for Quick Order Slot;AccountQuickOrderComponent
```

But unfortunately, it was not working.

**Comment by WeizhengSap** [comment]
PR is this: https://github.tools.sap/cx-commerce/spartacussampledata/pull/132

**Comment by WeizhengSap** [comment]
After talked with Bill, we decided to add `QuickOrder` in `my account`; also add it into `SiteLinksSlot` as well.
![Screen Shot 2021-04-08 at 5 32 07 PM](https://user-images.githubusercontent.com/44440575/114092508-58f38900-9890-11eb-8e1c-787c2ddcc884.png)

**Comment by giancorderoortiz** [comment]
Applicable to both b2b and b2c?

**Comment by dydome** [comment]
For B2B only

**Comment by Xymmer** [comment]
is this done, can this be closed?

**Comment by dydome** [comment]
Yes, we can close it
