### ISSUE TITLE
Update installation script for new schematics

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#11855]
With the new schematics also the installation script needs to be adjusted to handle them properly.

**Comment by giancorderoortiz** [comment]
Deployment of 3.2.0 fails in localhost. 
![Screen Shot 2021-04-08 at 6 24 35 AM](https://user-images.githubusercontent.com/46171897/114014975-33866100-9837-11eb-9a87-045e8d67ef28.png)
![Screen Shot 2021-04-08 at 6 25 02 AM](https://user-images.githubusercontent.com/46171897/114014977-341ef780-9837-11eb-9615-835876f8aea6.png)
![Screen Shot 2021-04-08 at 6 25 33 AM](https://user-images.githubusercontent.com/46171897/114014978-341ef780-9837-11eb-8084-6402ca865e40.png)
![Screen Shot 2021-04-08 at 6 27 39 AM](https://user-images.githubusercontent.com/46171897/114014980-341ef780-9837-11eb-914c-6456d8d9f5d9.png)

**Comment by giancorderoortiz** [comment]
I'm reopening this ticket. 
I am unable to deploy 3.2.0 rc1 with b2b enabled. Attempts fail in localhost and dev-server. 
Requires dev urgent assistance.

**Comment by giancorderoortiz** [comment]
Deployment details: 
URL: http://spartacus-devci767.eastus.cloudapp.azure.com:4200/powertools-spa/en/USD/
Problems: Get the storefront to appear, however, can’t login, can’t add items to cart, etc. Basically, an unusable storefront.
(Hopefully this is a misconfiguration issue, and not a real failure). 

![3_2_0_b2b_powertools_config](https://user-images.githubusercontent.com/46171897/114601917-09cca000-9c64-11eb-8c2a-370613945fa4.png)
