### ISSUE TITLE
Fix styling after Headings update for Screen Reader support

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#11869]
Heading tags were changed in several locations for better representation and hierarchy for the screen reader rotor feature. These changes resulted in minor styling issues that need to be corrected. The goal is to restore the original look and feel before the change. 

A list detailed of changes can be found [here](https://cxwiki.sap.com/display/spar/Headings+and+Labels) 
The [demo site](https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/) can be used as a reference to see what the styling and UI looked like before the changes 

### Todos:
- [ ] Review the detailed list of changes for headings 
- [ ] Restore original styling by comparing with demo site and update SCSS files as necessary 

### Additional info 
Epic Branch: `epic/a11y-sr/headings-and-labels`
Depends on #11867 to be merged in the epic branch first

**Comment by KateChuen** [comment]
Tested locally using develop branch. 

Talked with Miguel and he said this is purely visual, and the headings look ok. So can close this.
