### ISSUE TITLE
[MASTER] Cart Validation

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#11902]
## Requirements description
https://cxwiki.sap.com/display/spar/Feature%3A+Cart+Validation+at+Checkout

## Branch name
`epic/cart-validation`

The following is a checklist for new epics or features acceptance for Spartacus, based on [our Definition of Done document](https://sap.github.io/spartacus-docs/definition-of-done/)

## General

- [x] Epic has been tested on a production-like server using Spartacus installation script
- [x] Epic has been tested in all supported browsers and devices (Check list on DoD page)
- [x] Epic has sufficient end to end (cypress) test coverage
- [x] Schematics code deprecations have been provided and tested
- [x] Epic complies with [Security best practices](https://sap.github.io/spartacus-docs/security-best-practices/)
- [x] Epic complies with [Accessibility best practices](https://sap.github.io/spartacus-docs/a11y-best-practices/)
- [x] Epic CSS supports directionality (if required)
- [ ] Epic code scans have been conducted (sonar, whitesource, checkmarx)

## Audits/reviews

- [x] Architecture review of the epic (with @marlass)

## Documentation
- [x] Documentation input is provided for it to be published on the doc site.

**Comment by medzaksdn** [comment]
Hello @psmul,

Any idea about the delivery of this feature ([[ON HOLD] Feature: Cart Validation [Obelix]](https://github.com/SAP/spartacus/projects/135)), will it be available in the next version ?

kind regards.

**Comment by zksdn** [comment]
Hello @psmul,

Any idea about the delivery of this feature ([[ON HOLD] Feature: Cart Validation [Obelix]](https://github.com/SAP/spartacus/projects/135)), will it be available in the next release ?

Kind regards.

**Comment by giancorderoortiz** [comment]
This will be fixed for 3.3.0 minor release, correct? 
@Xymmer , @Platonn
