### ISSUE TITLE
Unable to point to non localhost frontend for CI e2e run

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11919]
Would like to run e2e tests in CI so that traffic is generated and captured by dynatrace. 

However, it seems that having a base url setup to something other than localhost doesn't work. 

See pr here: 
https://github.com/SAP/spartacus/pull/11917

Tried both: 
"baseUrl": "https://cx-qa16181492.eastus.cloudapp.azure.com/electronics-spa/en/USD"
and
"baseUrl": "https://cx-qa16181492.eastus.cloudapp.azure.com"

**Comment by hackergil** [comment]
In versions before 3.2, this is fixed by adding a `baseSite` to `app.module.ts`
In versions after 3.2, default baseSite is auto detected. No need to configure a default baseSite.

I fixed this on the QA server and it's working now (it has 3.1).
