### ISSUE TITLE
Login call happens twice

### ISSUE THREAD

**Issue by madasu** [SAP/spartacus#11922]
**Describe the bug**
Login call is happening twice on submission.

**Tell us the version of Spartacus**
- "version": "3.0.0" from current develop branch

**To Reproduce**
Go to login page
Enter credentials
Click Submit button
Look into network trace to find 2 calls happening

**Expected behavior**
Only one login call has to happen

**Screenshots**
<img width="480" alt="Screen Shot 2021-04-09 at 5 06 25 PM" src="https://user-images.githubusercontent.com/4014862/114251540-3e83e300-9956-11eb-9001-60ebd16163a7.png">

<img width="616" alt="Screen Shot 2021-04-09 at 5 12 40 PM" src="https://user-images.githubusercontent.com/4014862/114251731-f9ac7c00-9956-11eb-93f2-24e12e9cbf1b.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 89.0.4389.114 (Official Build) (x86_64)

**Comment by giancorderoortiz** [comment]
Unable to reproduce with Spartacus demo server. 
See here: https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/

![Screen Shot 2021-06-20 at 11 03 05 AM](https://user-images.githubusercontent.com/46171897/122679051-4ca47a00-d1b7-11eb-832f-f47059a231a2.png)
![Screen Shot 2021-06-20 at 11 03 29 AM](https://user-images.githubusercontent.com/46171897/122679052-4d3d1080-d1b7-11eb-82be-61f9368ccfc3.png)


Please re-open if necessary and provide a video of double call or HAR file.
