### ISSUE TITLE
[5.0] Deprecation for wishlist - must wait until cart and checkout libs created

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11938]
Must be fixed for 5.0 (was 4.0 but see comments)

Remove `OccSaveCartAdapter` from the core lib, and use the `OccSavedCartAdapter` from the saved-cart feature-lib.
- Update all relevant dependency from the core lib in relation to the deprecated `OccSaveCartAdapter`

**Comment by ren-tham** [comment]
Currently wishlist (in storefrontlib) is dependent on OccSaveCartAdapter (in core). If we deprecate this class and replace it with OccSavedCartAdapter (in feature-lib/cart), we introduce a dependency between storefrontlib and feature-lib (AVOID). 

Cart code splitting is required, before this deprecation. Putting this ticket ON-HOLD.

Will come back at a later time.
