### ISSUE TITLE
Register button in electronics taking full width in tablet view

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11932]
When the viewport is >= 768px to <= 991px, the register button takes full width, whereas the login button stays 'contained'

**To Reproduce**
1. Go to login page
2. Make screen size somewhere between 768 to 991px

**Expected behavior**
The register button matching the login button, vice versa

**Screenshots**
<img width="991" alt="Screen Shot 2021-04-12 at 9 26 56 AM" src="https://user-images.githubusercontent.com/29099466/114402344-ba0dac00-9b71-11eb-98c3-3307ab089deb.png">

**Comment by morganm58** [comment]
I think this is the same issue as https://github.com/SAP/spartacus/issues/12484
