### ISSUE TITLE
Saved Cart e2e B2C support

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#11942]
add support to run saved cart in b2c

**Comment by KateChuen** [comment]
Please make sure these are also added: 
From GC's ticket:

Please verify saved cart functionality with b2c as well by writing an e2e test.
Include restore cart please.
Please complete checkout with saved cart.

**Comment by Xymmer** [comment]
in jira now it seems
https://jira.tools.sap/browse/CXSPA-230
