### ISSUE TITLE
[needs a service] Reduce size of buttons in search/category result pages in mobile, so less space is consumed

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#1194]
The current search result page on mobile has a a lot of space sacrificed to optional functions, such as sorting, filtering and pagination. It would be great if we can optimise this and have a more size-efficient version for mobile that enables the features on demand. 
The following comes to mind: 
- make "Relevance" and "Filter By" small buttons next to the page gridmode button, so that only 1 line is consumed. 
- Hide the applied filters lines. Add applied filters to the fly-menu of the  "Filter By", by making them active filter options. 

![image](https://user-images.githubusercontent.com/4745807/52241325-9e445680-28d3-11e9-8372-4047e53ce98e.png)

**Comment by mikelMHybris** [comment]
This would be something UX/Design would have to approve. I'll send them the link to this ticket.

**Comment by vekterdude** [comment]
Hi Tobias!

3 lines is normal for all that stuff in mobile - if you choose to have pagination at the top. But I'm not a huge fan of pagination, especially at the top of the page. However, I've had a lot of pushback against that in the past from the b2b case side, mostly.

We have options here...
1. Drop pagination from the top of the page and have it only on the bottom, then put 'Sort by' and "grid vs. List" toggle on the same line with filter being a line below.
2. Drop pagination at the top in phone but leave it in Tablet and try to get them both on one line. 
3. Infinite Scroll - drop pagination at the top and bottom of the page altogether forever!

**Comment by Xymmer** [comment]
Hey all, we need short term vs long term solutions... for short term, let's do what Tobias suggests (as well as anything else that can be found to save space while you're there). Anthony, create new tickets for the ultimate solutions and we'll discuss and prioritize. I see many sites have 1 button for both sorting and filtering now (for e.g.) so it can be debate what we do.

**Comment by mikelMHybris** [comment]
<img width="456" alt="Screen Shot 2019-06-05 at 1 35 17 PM" src="https://user-images.githubusercontent.com/30266610/58977171-24e04600-8797-11e9-8fa5-b2f296cce047.png">
<img width="359" alt="Screen Shot 2019-06-05 at 1 35 43 PM" src="https://user-images.githubusercontent.com/30266610/58977173-2578dc80-8797-11e9-8ddc-0efd045ea713.png">

How should the layout be when we have a large pagination like the example above?

**Comment by vekterdude** [comment]
Filtering should always be closer to the products than pagination.

Pagination is Always the first and last thing on the page never in the middle.

so...

Pagination

Filtering / Relevance / Grid List Switch

Page Content

Relevance / Grid List Switch
Pagination

**Comment by mikelMHybris** [comment]
@vekterdude should this also be the order in larger screen sizes?

**Comment by vekterdude** [comment]
Tablet only, I think

This opens a lot of issues since in desktop it is nicer to have everything on the bottom on the same line as that is best for that breakpoint.

This leaves you making a bunch of very custom layouts instead of a smooth choreograph.

If it helps the wires have been updated with Tobias' vision as far as I can parse it!

**Comment by mikelMHybris** [comment]
I need some dev help with this one. If I add a button in the mobile view I think we would need a service to open the facets modal.

**Comment by vekterdude** [comment]
Reduce the number of buttons, right? not the size of the buttons as that is established in the guidelines. Do we need to redesign this a s more efficient component? There is no need for a back button to the right of the '1' for instance. 
Can we make it smarter instead of making it physically smaller?
