### ISSUE TITLE
B2B User Profile Update call fails

### ISSUE THREAD

**Issue by I339232** [SAP/spartacus#11955]
Description: 
When we try to update any information of an existing user in b2b commerce storefront, the update call fails. 
The update call is trying to access the occ api: 
https://localhost:9002/occ/v2/powertools-spa/orgUsers/current?lang=en&curr=USD
It us throwing this error: Request method 'PATCH' not supported. 

This also happens when we try to update the profile details with CDC integration enabled. The update is successful on CDC side but in Commerce it fails with the same error.
Commerce Version: 20.05
Spartacus Version: 3.0.0

**To Reproduce**
1. Enable B2B storefront features and powertools site.
2. Login using an existing user.
3. Go to My Acccounts drop down. 
4. Select Profile Details
4. Update first name or last name
5. Open Network tab in the developer console 
6. Click on Save

Error is displayed and the information is also not persisted on the commerce backend.
For CDC Integration, the update is sent to CDC and CDC has the updated value but it is not updated in Commerce.

**Expected behavior**
The update should be successfully persisted in Commerce.

**Screenshots**
<img width="1678" alt="Screen Shot 2021-04-14 at 10 54 14 AM" src="https://user-images.githubusercontent.com/31727295/114659718-b7e25380-9d11-11eb-8380-35b012a233ee.png">

**Comment by marlass** [comment]
I can confirm the issue with B2B update profile org endpoint not supporting `PATCH` request.
We're currently thinking how to tackle this issue.

In the meantime here is the proposed fix:
- add new configurable endpoint to the OccEndpoints configuration (eg. `updateUser`)
- override `update` method in `OccUserProfileAdapter` (if you use @spartacus/user lib) or `OccUserAdapter` if you haven't switch to new user lib.
- provide the new service

Example `UserFeatureModule` with the fix applied (without lazy-loading). For lazy loading you would need to create new module where you would provide new service and this new module would then need to be lazy loaded:

```ts
import { Injectable, NgModule } from '@angular/core';
import {
  I18nConfig,
  normalizeHttpError,
  OccConfig,
  provideConfig,
} from '@spartacus/core';
import { UserAccountModule } from '@spartacus/user/account';
import {
  userAccountTranslationChunksConfig,
  userAccountTranslations,
} from '@spartacus/user/account/assets';
import { User, UserAccountRootModule } from '@spartacus/user/account/root';
import { UserProfileModule } from '@spartacus/user/profile';
import {
  userProfileTranslationChunksConfig,
  userProfileTranslations,
} from '@spartacus/user/profile/assets';
import {
  UserProfileAdapter,
  USER_PROFILE_SERIALIZER,
} from '@spartacus/user/profile/core';
import { OccUserProfileAdapter } from '@spartacus/user/profile/occ';
import { UserProfileRootModule } from '@spartacus/user/profile/root';
import { Observable, throwError } from 'rxjs';
import { catchError } from 'rxjs/operators';

@Injectable()
export class FixedOccUserProfileAdapter extends OccUserProfileAdapter {
  update(userId: string, user: User): Observable<unknown> {
    // Use separate configurable endpoint instead of `user`
    const url = this.occEndpoints.getUrl('updateUser', { userId });

    user = this.converter.convert(user, USER_PROFILE_SERIALIZER);
    return this.http
      .patch(url, user)
      .pipe(catchError((error) => throwError(normalizeHttpError(error))));
  }
}

@NgModule({
  declarations: [],
  imports: [
    UserAccountRootModule,
    UserAccountModule,
    UserProfileRootModule,
    UserProfileModule,
  ],
  providers: [
    // Provide fixed adapter,
    { provide: UserProfileAdapter, useClass: FixedOccUserProfileAdapter },
    // Configurable separate endpoint for update
    provideConfig(<OccConfig>{
      backend: {
        occ: {
          endpoints: {
            updateUser: 'users/${userId}',
          },
        },
      },
    }),
    provideConfig(<I18nConfig>{
      i18n: {
        resources: userAccountTranslations,
        chunks: userAccountTranslationChunksConfig,
        fallbackLang: 'en',
      },
    }),
    provideConfig(<I18nConfig>{
      i18n: {
        resources: userProfileTranslations,
        chunks: userProfileTranslationChunksConfig,
        fallbackLang: 'en',
      },
    }),
  ],
})
export class UserFeatureModule {}
```
