### ISSUE TITLE
[Master Ticket] CX 2105 E2E Trials

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#11994]
Linux server deployment with CX 2105. 

Run e2e tests to confirm compatibility. 

Remember to make modification to local.properties regarding occ calls. 
See C5-25

frontend: 3.2.0 or 3.3.0. 
backend: 2105 RC

### Findings/issues

* android_client is missing (See [ECP-5723](https://cxjira.sap.com/browse/ECP-5723))
* #12092 Unable to add to cart (due to entries API change)

**Comment by giancorderoortiz** [comment]
Need a stable 2105 RC or stable snapshot.

**Comment by giancorderoortiz** [comment]
Using dev0

**Comment by giancorderoortiz** [comment]
Use dev0 for now

**Comment by giancorderoortiz** [comment]
pr: https://github.com/SAP/spartacus/pull/12063

**Comment by giancorderoortiz** [comment]
Related tickets: 
https://github.com/SAP/spartacus/issues/10658
https://github.com/SAP/spartacus/issues/11103

**Comment by giancorderoortiz** [comment]
My account failures: https://github.com/SAP/spartacus/issues/12085

**Comment by giancorderoortiz** [comment]
Checkout failures: https://github.com/SAP/spartacus/issues/12087

**Comment by giancorderoortiz** [comment]
Miscellaneous failures: https://github.com/SAP/spartacus/issues/12088

**Comment by hackergil** [comment]
Add to Cart fix needed (#12092)

**Comment by giancorderoortiz** [comment]
Retest with 3.3.x pr here: https://github.com/SAP/spartacus/pull/12216
@LTiger14 fyi

**Comment by giancorderoortiz** [comment]
Retest with 3.3.x cypress run here: https://dashboard.cypress.io/projects/k3nmep/runs/14238

**Comment by giancorderoortiz** [comment]
Latest e2e run of cx 2105 and develop branch: https://dashboard.cypress.io/projects/k3nmep/runs/14428/overview

**Comment by giancorderoortiz** [comment]
Latest e2e run of cx 2105 and release/3.3.x branch : https://dashboard.cypress.io/projects/k3nmep/runs/14429/overview

**Comment by giancorderoortiz** [comment]
Significant progress by @LTiger14 here: https://dashboard.cypress.io/projects/k3nmep/runs/14727/overview

**Comment by giancorderoortiz** [comment]
@bgambocjaviniar additional permutations require testing.

**Comment by giancorderoortiz** [comment]
@hackergil , @bgambocjaviniar , @LTiger14 it's necessary to have a more concrete understanding of all the permutations we need to test. 
What we have done is a minimum check.

**Comment by giancorderoortiz** [comment]
test with 3.2.0 here: https://github.com/SAP/spartacus/pull/12514
