### ISSUE TITLE
Sample data for multi-d

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#12008]
We are missing some sample data which is required to work on multi-d feature.

What we need:
- [x] add ProductOrderGridTabComponent to TabPanelContainer for PDP page

![image](https://user-images.githubusercontent.com/18736434/115030632-97f49080-9ec7-11eb-9037-b9042c9b2d21.png)
![image](https://user-images.githubusercontent.com/18736434/115030689-a93d9d00-9ec7-11eb-8d41-3a0453868aa8.png)

- [ ] add MultiDimensionalVariantSelector with ProductVariantMultiDimensionalSelectorComponent (the same approach as VariantSelector)

![image](https://user-images.githubusercontent.com/18736434/115031029-02a5cc00-9ec8-11eb-833c-a2b619bd6306.png)

**Comment by bgambocjaviniar** [comment]
backend PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/173/files

- Added `ProductOrderGridTabComponent` at the 'beginning' of the `CMSTabParagraphContainer` component as mentioned in a call.
- Could not find any reference of existing multi-d cms components in the other modules, therefore made it a `CMSFlexComponent` called `MultiDimensionalVariantSelector` with FlexType `ProductVariantMultiDimensionalSelectorComponent`. 
For example, in Spartacus mapping for the cms component, you would do as follows:

```
cmsComponents: {
        ProductVariantMultiDimensionalSelectorComponent: {
          component: 'anyNameAsSpartcusComponent',
        },
},
```

Currently, setting up local backend to verify the change is reflected correctly. Will add an EDIT at the bottom of here with the time once it's completed.

--------------

EDIT: 
it works with the PR above. You can change the key for the tabbing component under `projects/assets/src/translations/en/product.ts`.TabPanelContainer

You need to have someone deploy it on the multi-d server
<img width="1437" alt="Screen Shot 2021-04-19 at 8 53 47 PM" src="https://user-images.githubusercontent.com/29099466/115321253-6e4e9a00-a151-11eb-9238-2af64f040f2d.png">
