### ISSUE TITLE
Request. E2E Faceting + Checkout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12013]
Please write an e2e test that combines faceting and checkout.

There is already a test for faceting here:
spartacus/projects/storefrontapp-e2e-cypress/cypress/integration/regression/product-search/product-search-product-type-flow.e2e-spec.ts

There is also already a test for checkout here:
spartacus/projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout/checkout-flow.e2e-spec.ts

However, there is no test that combines the 2 functionalities.
This is a basic business flow that requires automated verification.
There must be no doubt that product faceting and checkout work together from end-2-end.
(SKUs must be added to cart and complete checkout after being listed as a result of a faceting process)

This requested test may be long, but now, with parallelization this is no longer a concern.

**Comment by giancorderoortiz** [comment]
@Xymmer @hackergil please consider in upcoming plannings.

**Comment by hackergil** [comment]
@bit172 Please just incorporate adding a product via faceting on the existing checkout e2e test to cover the scenario that @giancorderoortiz is asking for.

**Comment by giancorderoortiz** [comment]
Happy to see this done. Thanks.
