### ISSUE TITLE
[WAIT RESPONSE] Homepage broken after activating Hybris OpenId authentication

### ISSUE THREAD

**Issue by ibenhar** [SAP/spartacus#12048]
We want to use Hybris as OpenId provider (https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/2011/en-US/b68a2438783b4bd09355a1c5434e3e92.html). We have configured the spartacus application to use hybris specific endpoints, we have imported the necessary impexes in hybris database but when we try to login using (oauth flow) everything works fine until we are redirected to the home page where a warning is displayed and the homepage is not shown because of that warning. No server side requests (in browser network tab) is failing. 

The warnings we are getting are the following : 

![image](https://user-images.githubusercontent.com/16373560/115367106-69bbcd00-a1b5-11eb-85e7-ac9647448212.png)

- Library version: 3.1.0

- Only reproducible on our custom code

**Expected behavior**
No warning is shown in the browser console and the homepage is correctly displayed.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.1
 - Browsers : firefox (v: 87.0) & chrome(v: 89.0.4389.90)

**Additional context**
After debugging, the warnings are the result of the following calls : 
1-
![image](https://user-images.githubusercontent.com/16373560/115368207-6412b700-a1b6-11eb-86ad-4331f665816c.png)

and the error is throw in this code section : 
![image](https://user-images.githubusercontent.com/16373560/115368516-ae943380-a1b6-11eb-8526-aa6bf03d61e2.png)

2-
Also, in another call the error is thrown and the warning is displayed : 
![image](https://user-images.githubusercontent.com/16373560/115368894-0fbc0700-a1b7-11eb-9ed9-84f1f4add569.png)

which is also going the through the same call stack to land in an error : 
![image](https://user-images.githubusercontent.com/16373560/115369141-53167580-a1b7-11eb-84de-e458e0b03d11.png)

![image](https://user-images.githubusercontent.com/16373560/115369174-5dd10a80-a1b7-11eb-9ab5-8f7254ec0155.png)

Our config object is the following : 

![image](https://user-images.githubusercontent.com/16373560/115369370-8d801280-a1b7-11eb-8366-18b9ceabf339.png)

**Comment by marlass** [comment]
@ibenhar I tried to reproduce it locally, but I wasn't able to do it. I used implicit OAuth flow and after redirect storefront successfully loaded and I didn't get any errors in console.

The context you provided doesn't help with figuring out the reason. I would need to know which variables are not initialized and I can't figure it out based on the provided screenshots.

Can you reproduce the issue with fresh spartacus application that have changes only in auth configuration? I would like to exclude the case where custom code is causing that issue.
