### ISSUE TITLE
[NOT MVP] align styling of our error/warning messages in the UI

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#12073]
**repo:**
* configure coffee machine
* select starbucks mode and to many Refrig Units, so that you get error and warning messages
* go to overview page

**issue:** styling of error/warning messages and resolve issues message is different. **see the attached screenshot!**
![image](https://user-images.githubusercontent.com/53090888/115571341-31081a80-a2bf-11eb-9501-6ba66f8567b8.png)

**Comment by Larisa-Staroverova** [comment]
The `error/warning messages` banner will be removed from the overview page. For the CMS component should be removed.
Thus the `error/warning messages` and `resolve issues` banners won't be displayed together. The styling should not be the same. It was  discussed with UID
