### ISSUE TITLE
[MVP] After screen resize "mobile" group menu does not disappear

### ISSUE THREAD

**Issue by AlexanderKuschner** [SAP/spartacus#12078]
To reproduce: 
- start CPQ product configuration
- reduce the browser screen width so that the hamburger menu icon appears for the group menu and open this group menu
- now increase the browser screen width so that the "standard" group list is shown again

- Result: hamburger group menu does not disappear and overlapped a part of the screen

**Comment by JayEmKay-8** [comment]
I think Giancarlo has a point when he says "makes core Spartacus look bad". Therefore, I changed this issue from non-MVP to MVP.

**Comment by Changsuwan** [comment]
With the current fix, the group menu in the hamburger menu disappears with a little delay. However, according to the product owner, the result of the fix is acceptable.
