### ISSUE TITLE
[MVP] Before Merge: Cypress Helper: Remove cy.wait('@readConfig')

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#12095]
The cypress helper file product-configuration.ts  uses cy.wait('@readConfig')

This would be incompatible with the SPA VC as there is no readConfig.

Remove/replace the usages of cy.wait('@readConfig')

See: projects/storefrontapp-e2e-cypress/cypress/helpers/product-configuration.ts

**Comment by ChristophHi** [comment]
Obsolete, as I introduced separate helpers for VC. Also see #12103
