### ISSUE TITLE
Better release notes + better tracking in PRs and issues when something was fixed and released

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#12109]

**Comment by bgambocjaviniar** [comment]
closing in favour to JIRA
https://sapjira.wdf.sap.corp/projects/CXSPA/issues/CXSPA-40?filter=allopenissues

**Comment by bgambocjaviniar** [comment]
closed in favor for JIRA https://jira.tools.sap/browse/CXSPA-205
