### ISSUE TITLE
New Service UserAccountService cannot be used

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#12108]
**Describe the bug**
With Version 3.2.0, the `UserService` was deprecated and the successor `UserAccountService` should be used according to the JSDOC.

When using this new Service

`import { UserAccountService } from '@spartacus/user/account/core';`

it gives an error in the console:

```
main.ts:14 Error: NullInjectorError: No provider for UserAccountService!
    at NullInjector.get (core.js:1013) [angular]
    at R3Injector.get (core.js:11173) [angular]
    at R3Injector.get (core.js:11173) [angular]
    at R3Injector.get (core.js:11173) [angular]
    at injectInjectorOnly (core.js:899) [angular]
```

**Tell us the version of Spartacus**
- Library version: 3.2.0

**To Reproduce**
1. Use the new Service `UserAccountService` in a component

**Expected behavior**
The new service can normally be used

**Desktop (please complete the following information):**
OS: all
Browser: all
Version: all

**Smartphone (please complete the following information):**
Device: all
OS: all
Browser: all
Version: all

**Additional context**
Is it maybe related to the fact that the user components have been extracted to a standalone lib? How would one use a service from a lib, which is being loaded async?

**Comment by tobi-or-not-tobi** [comment]
The actual services are lazily loaded, so that only when you use it, the additional js will be loaded. This requires however that you inject the facade instead, so that we can do the magic of loading the service lazily. 

Can you try `import { UserAccountFacade } from '@spartacus/user/account/root';` instead?

**Comment by janwidmer** [comment]
Thanks, that works by doing: `this.userAccountFacade.get()`

**Comment by tobi-or-not-tobi** [comment]
Reopening since we like to improve the deprecation notes
