### ISSUE TITLE
[dupe of 6492?] Aria-labels are hardcoded

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#12128]
That part looks like hardcoded but it can be easily translated like `[attr.aria-label]="'feature.component.ariaCase' | cxTranslate"`. Unfortunately our tool (`i18n-lint`) doesn't catch cases like this.
![image](https://user-images.githubusercontent.com/8040837/115918486-dcf46600-a477-11eb-9314-49684ce8da84.png)

**Comment by developpeurweb** [comment]
@Pucek9 @dydome This ticket might be a duplicate of GH-6492, can you please review that one and if it is, then please close both when finished.
