### ISSUE TITLE
Missing Events: CartRemoveEntryFailEvent and CartUpdateEntryFailEvent

### ISSUE THREAD

**Issue by SebCon** [SAP/spartacus#12141]
**Describe the bug**
Its not really a bug, there arent existing the two events which we need for our implementation:

CartRemoveEntryFailEvent
CartUpdateEntryFailEvent

**Tell us the version of Spartacus**
- Library version: 3.2

**Expected behavior**
There are existing CartUpdateEntrySuccessEvent and CartUpdateEntrySuccessEvent, but not the two events above.

**Comment by znikola** [comment]
FYI: https://github.com/SAP/spartacus/issues/12125
