### ISSUE TITLE
Need to refresh to see SmartEdit changes

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#12170]
An old bug comes back... if you change something in SmartEdit in 3.0, you need to refresh to see the changes.
e.g. update an image or add a component, it works but you must refresh to see it.

**Comment by saschaheijmink** [comment]
Seems to be the same bug https://github.com/SAP/spartacus/issues/11848

**Comment by Xymmer** [comment]
Configuration or occ cache issue, not spartacus, closing

**Comment by jwdwsq** [comment]
@Xymmer not sure if you are implying that #11848 can be fixed via backend occ config/cache settings? The bug is reproducible in ootb smartedit/electronics v2005
