### ISSUE TITLE
Dependency cleanup ->  [user/account] -> CheckoutConfigService

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#12183]
Remove references to checkout types `CheckoutConfig`  in login-register component from _user_ feature lib

The goal for this change is that the user lib can not depend on the checkout lib.

We can simply remove the reference to `CheckoutConfig`.  It seems to me that the dependency on checkout from the register component is not absolutely required.  In the `CheckoutAuthGuard`, the `forced` request param is only added when guest checkout is enabled.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by plabadie** [comment]
No functional changes, only regression.
