### ISSUE TITLE
Checkout: Inconsistent display of quantities

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#12197]
Put any product to cart, increase quantity to a value > 1. Proceed to checkout. 
The checkout displays in its header the sum of cart line items ('Checkout 1 Item'), while in 'Cart Totals' it takes the line item quantities into account ('Cart total (4 items): $1,856.51'). This is a bit confusing.

<img width="812" alt="Screen Shot 2021-04-29 at 07 41 42" src="https://user-images.githubusercontent.com/33626130/116506865-6b287c00-a8be-11eb-8f85-f2ec6c810e93.png">

**Comment by giancorderoortiz** [comment]
@Xymmer @tobi-or-not-tobi , here the use of the word "item" has 2 meanings. 
Should we differentiate and use a different term?

**Comment by Xymmer** [comment]
The title should just be "Checkout"
