### ISSUE TITLE
Extend LanguageService scope / export Problems

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#12200]
**Describe the bug**
To be able to detect the preferred user language, the Service `LanguageService` can be extended. While doing so, several scope / export Problems where found:

1. Within the `initialize` method, the service property `sessionStorage` is used. As it is currently defined as `private` it cannot be used in the `initialize` method and needs to be redefined
2. To be able to access all / default Language from context, I assume, the context utils `getContextParameterValues` and ` getContextParameterDefault` should be used. These utils do not seem to get exported.

**Tell us the version of Spartacus**
- Library version: 3.1.0

**To Reproduce**
1.  Extend the `LanguageService`

**Expected behavior**
1. The Service Property `sessionStorage` is defined as public field, so it can be used in the Extended Service in my Code
2. The context utils `getContextParameterValues` and ` getContextParameterDefault` can normally be used

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Comment by tobi-or-not-tobi** [comment]
@janwidmer I'm not sure what our'e after. Could you use events instead? The `LanguageSetEvent` exposes the active language, which you can observe through the eventService. Or consume the `LanguageService`. I depends on what you need to do actually.

**Comment by janwidmer** [comment]
@tobi-or-not-tobi we want to build a user browser detection logic. So if the user calls the site example.com without an active language, the language should not fallback to the default language from the context, but first check, if one of the users accepted languages (exposed via navigator.languages) matches the languages of spartacus. In that case, this one should be used instead of the default one.

I was told to extend the LanguageService to do so and override the `initialize` method of it. That all works good, but gives the problems described in this ticket.

**Comment by janwidmer** [comment]
Code Example on how I tried to implement it:

```
initialize(): void {
	let value;
	this.getActive()
		.subscribe((val) => (value = val))
		.unsubscribe();
	if (value) {
		// don't initialize, if there is already a value (i.e. retrieved from route or transferred from SSR)
		return;
	}

	if (this.winRef.isBrowser()) {
		// custom variable sessionStorageCustom was needed to be added as sessionStorage is defined private in the Service and cannot be used here
		const sessionLanguage = this.sessionStorageCustom && this.sessionStorageCustom.getItem('language');

		const acceptedLanguages = this.winRef.isBrowser()
			? this.winRef.nativeWindow?.navigator.languages
			: this.request.acceptsLanguages();

		if (
			sessionLanguage &&
			getContextParameterValues(this.config, LANGUAGE_CONTEXT_ID).includes(sessionLanguage)
		) {
			this.setActive(sessionLanguage);
		} else {
			this.setActive(this.determineUserLang(acceptedLanguages));
		}
	} else {
		// when being in SSR; we always use the default language to not compromise CDN caching with a user language
		this.setActive(getContextParameterDefault(this.config, LANGUAGE_CONTEXT_ID));
	}
}

private determineUserLang(acceptedLanguages: string[]): string {
	const acceptedLangCodes = acceptedLanguages.map(this.stripCountry);
	// how can I get the supported languages from the context, as getContextParameterValues is not exported currently
	const supportedLangCodes = getContextParameterValues(this.config, LANGUAGE_CONTEXT_ID);

	const matchingLangCode = acceptedLangCodes.find((code) => supportedLangCodes.includes(code));
	// how can I get the default language from the context, as getContextParameterDefault is not exported currently
	return matchingLangCode || getContextParameterDefault(this.config, LANGUAGE_CONTEXT_ID);
}

private stripCountry(language: string): string {
	return language.trim().replace('_', '-').split('-')[0];
}
```

**Comment by janwidmer** [comment]
Maybe related to existing issue https://github.com/SAP/spartacus/issues/11345

**Comment by Platonn** [comment]
1. Storage synchronization logic will be moved out from LangaugeService to a different class soon in https://github.com/SAP/spartacus/pull/12076, so there are no plans to improve extensibility of web storage property in LangaugeService.
   Workaround for you is creating your own `storage` property in the constructor of your custom LangaugeService:
   ```typescript
      constructor(
        store: Store<StateWithSiteContext>,
        winRef: WindowRef,
        config: SiteContextConfig
      ) {
        super(store, winRef, config);
        this.storage = winRef.sessionStorage; // your custom storage property
      }
   ```
2. `getContextParameterValues` and `getContextParameterDefault` will be exposed in public API in https://github.com/SAP/spartacus/pull/12298
