### ISSUE TITLE
Missing Add To Cart Error Message When Attempting to Add Product Without Complete Config

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12208]
**Environment:**

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1. Navigate to B2B powertools that has CPQ enabled.
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000) and click on "Configure" button
4. Select no options. 
5. Click on Add to Cart button at bottom of screen. 

**Expected Results:** 
5. Error message indicating item can't be added to cart because it's missing configuration. 

**Actual Results:** 
5. Nothing happens. No error message in console.

**Comment by schuppell** [comment]
Add to cart must not be disabled for user.
Expected result discussed with UX is: User can add incomplete product to cart, but checkout is blocked.

**Comment by schuppell** [comment]
@vekterdude : Please confirm expected behaviour, then we can close the issue.

**Comment by Larisa-Staroverova** [comment]
@giancorderoortiz, as @schuppell mentioned the configuration could be imcomplete or the default configuration could be added to the cart.
I will close this ticket
