### ISSUE TITLE
Missing CPQ Menu Option English Text. Shows Label IDs Instead. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12207]
**Environment:** 

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0. 

**Steps to Reproduce:** 
1. Navigate to B2B powertools that has CPQ enabled. 
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000)
4. Observe main configuration page. 

**Expected Results:** 
4. All menu options are shown in localized language (i.e English, German, etc... ). 
4.a. Design, Milk 

**Actual Results:** 
4. Menu options text is shown as label IDs
5.a. CONF_COFFEEMACHINE_3000_GEN_OPT

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-04-29 at 7 41 57 AM](https://user-images.githubusercontent.com/46171897/116546871-29003a00-a8c0-11eb-8503-6f36c2b4a01a.png)

**Comment by giancorderoortiz** [comment]
At minimum, for English, and within and throughout CPQ functionality in Spartacus there must not be menu options, titles, subtitles, radio or checkbox selections whose caption is displayed as label_id instead of English text.

We understand for other supported languages localization/translation is pending, and we accept to release as long as we don't display label_ids in English. 

@Xymmer , @zebercut, @Platonn I recommend not to release 3.3.0 until this issue is fixed.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-04-29 at 8 03 52 AM](https://user-images.githubusercontent.com/46171897/116548068-b42dff80-a8c1-11eb-844a-60365d582a84.png)

The label "NOT_IMPLEMENTED" is shown here instead of "Not Implemented"

**Comment by ChristophHi** [comment]
@giancorderoortiz That's a pure modeling issue with CONF_COFFEEMACHINE_3000 (does not occur with CONF_CAMERA_BUNDLE e.g.), and has nothing to do with Spartacus. On CPQ side, those texts have not been maintained. We noticed that as well and will improve the model. 
Closing the ticket as not related to SPA
