### ISSUE TITLE
Add to Cart CQP Product. Wrong Error Message. No Cart Update

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12218]
**Environment:**

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1.Navigate to B2B powertools that has CPQ enabled.
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000) and press enter.
4. Click in Add to Cart button

**Expected Results:**
4.a Product is added to cart with no-configuration or with default configuration. 
4.b. If product cannot be added to cart, then an error message should be displayed, or the Add-To-Cart button should be disabled.

**Actual Results:**
4. Wrong error message saying "This item was already in your cart. The quantity was updated". 

Most worry-some is that cart itself is not updated at all.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-04-29 at 12 44 22 PM](https://user-images.githubusercontent.com/46171897/116593126-c3777200-a8ee-11eb-9c5c-6c2ad64c8596.png)

![Screen Shot 2021-04-29 at 1 23 03 PM](https://user-images.githubusercontent.com/46171897/116593164-ce320700-a8ee-11eb-8d63-df30d6433992.png)

**Comment by Larisa-Staroverova** [comment]
@giancorderoortiz, it is possible to add an incomplete configuration,namely a configurations with the issues or conflicts, or a default configuration to the cart.
I will close this ticket

**Comment by Platonn** [comment]
@Larisa-Staroverova I have problem to understand how your response addresses the reported bug:
> Wrong error message saying “This item was already in your cart. The quantity was updated”.

Btw. usually the added-to-cart-modal displays also some item summary (the picture, quantity control and buttons 'go to cart' or 'go to checkout'). I cannot see them in the screenshots provided by @giancorderoortiz, but only the message and the "x" button.

I can see also some error in the console of GC: `null value in entry....`

**Comment by Larisa-Staroverova** [comment]
Sorry, I see your point. I wrote a misleading comment.
I retested it and the issue did not appear again. The reason could be the switch from `eudev` to ` dev` CPQ tenant that we did last week. See also [TIGER-7521](https://cxjira.sap.com/browse/TIGER-7521)
