### ISSUE TITLE
Random. Product Configuration Section Fails to Display

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12217]
**Environment:**

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1.Navigate to B2B powertools that has CPQ enabled.
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000) and press enter. 
4. Click on Configure button

**Expected Results:** 
4. Configuration sections and menus are shown. 

**Actual Results:** 
4. Empty configuration slots. 

![Screen Shot 2021-04-29 at 12 59 52 PM](https://user-images.githubusercontent.com/46171897/116589857-1818ee00-a8eb-11eb-910b-5ac1ede3b4a3.png)

**Comment by giancorderoortiz** [comment]
This is a random issue.  Environment stable?

**Comment by ChristophHi** [comment]
This is fixed. Reason was the instability of the CPQ eudev endpoint and the subsequent move to dev, which was facing more downtimes as regularly deployed.
We switched back to eudev and are very rarely facing downtimes.
