### ISSUE TITLE
* In SmartEdit: Slot and component contract is missing when app start with SSR

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#12233]
Start the application with SSR, and then slot and component contract is missing in SmartEdit.

**Comment by WeizhengSap** [comment]
It works in firefox.
![Screen Shot 2021-04-30 at 2 18 28 PM](https://user-images.githubusercontent.com/44440575/116735887-84682000-a9c5-11eb-9ff5-3f9858a32316.png)


In the chrome, open the previewUrl with `cmsTicketId`, we can see that the contract is added to slot and component.
![Screen Shot 2021-04-30 at 3 08 08 PM](https://user-images.githubusercontent.com/44440575/116736181-eaed3e00-a9c5-11eb-86f9-d2612d5df786.png)


But when it is open in `iframe`, the data attributes are lost.
![Screen Shot 2021-04-30 at 3 09 58 PM](https://user-images.githubusercontent.com/44440575/116736362-2a1b8f00-a9c6-11eb-813e-388585a93921.png)

**Comment by giancorderoortiz** [comment]
@WeizhengSap still an issue?

**Comment by WeizhengSap** [comment]
This one can be closed.
