### ISSUE TITLE
CPQ. Subtotal Doesn't Update Throughout Configuration Process. Remains at 0.00

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12242]
**Environment:**

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1. Navigate to B2B powertools that has CPQ enabled.
2. Login
3. Search for Coffee Machine (i.e. CONF_COFFEEMACHINE_3000) and click on "Configure" button
4. Configure option at will. Make sure you choose at least one option for each configuration option in each page. 
5. Click on Add to Cart button at bottom of screen once configuration has been fully completed. 

**Expected Results:**
4.a Subtotal updates each time a new option is selected/added which has a different price. 
4.b. If not immediate subtotal update, at least when navigating to the next configuration page, an update in subtotal is expected. 

**Actual Results:**
4. Subtotal doesn't update. Remains $0.00. 
4.a. Only in cart page do we see a price greater than $0.00

---

End customer must be able to see the financial impact of making different configuration option selections.

**Comment by giancorderoortiz** [comment]
See Base Price : $0.00

![Screen Shot 2021-04-30 at 5 38 58 PM](https://user-images.githubusercontent.com/46171897/116757997-3f4fe800-a9dd-11eb-8845-b51c17141544.png)
![Screen Shot 2021-04-30 at 5 41 34 PM](https://user-images.githubusercontent.com/46171897/116757965-2fd09f00-a9dd-11eb-8610-fd3a2bddef6d.png)

![Screen Shot 2021-04-30 at 5 41 46 PM](https://user-images.githubusercontent.com/46171897/116757966-30693580-a9dd-11eb-981c-a7204924b864.png)
![Screen Shot 2021-04-30 at 5 43 21 PM](https://user-images.githubusercontent.com/46171897/116757982-36f7ad00-a9dd-11eb-9088-c7eb35af47dc.png)

**Comment by Larisa-Staroverova** [comment]
@giancorderoortiz, we had to switch to the dev CPQ environment because in the last days we experienced some issues on another CPQ environment  and our CPQ colleagues are on the vacation and are not able to help us.
The dev CPQ environment contains our test products but not everything is accurately maintained, for instance, pricing.  
I will close this task.
