### ISSUE TITLE
Edit Configuration in Saved Carts Broken

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12254]
Environment:

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1. Navigate to B2B powertools that has CPQ enabled.
2. Login as cpqXX@sap.com user
3. Search for camera bundle product (i.e. CONF_CAMERA_BUNDLE)
4. Click on Add to Cart.
5. In Cart page, for camera bundle product, click on "Edit Configuration" button. 

**Expected Results:** 
5. Configurator page is shown (i.e. https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/USD/configure/cpq/cartEntry/entityKey/0?forceReload=true&resolveIssues=true)

**Actual Results:** 
5. Empty configurator page.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-05-03 at 6 36 05 AM](https://user-images.githubusercontent.com/46171897/116892425-d2ffff00-abfd-11eb-99a4-607c0cf3e699.png)
![Screen Shot 2021-05-03 at 6 36 20 AM](https://user-images.githubusercontent.com/46171897/116892426-d2ffff00-abfd-11eb-90b1-5a301703b33c.png)

**Comment by giancorderoortiz** [comment]
Issue seems random.  :-(

**Comment by Xymmer** [comment]
saved carts does not support cpq at the moment, closing
