### ISSUE TITLE
Saved Carts Functionality Broken with CPQ

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12253]
Environment:

https://jsapps.cpce-teamtiger1-d1-public.model-t.cc.commerce.ondemand.com/powertools-spa/en/
Version: Spartacus 3.3.0 RC0.

**Steps to Reproduce:**

1. Navigate to B2B powertools that has CPQ enabled.
2. Login as cpqXX@sap.com user
3. Search for camera bundle product (i.e. CONF_CAMERA_BUNDLE)
4. Click on Add to Cart. 
5. In cart page, click on "Save for Later" 
6. Provide a name and comment for saved cart and click on save. 
7. Navigate to home page. 
8. From my account, navigate to saved carts. 
9. Confirm saved cart is listed. 
10. Logout. 
11. Wait 1 minute. 
12. Login as cpqXX@sap.com user
13. From my account, navigate to saved carts. 
14. Confirm saved cart previously saved is there. 

**Expected Results:** 
14. Saved cart is listed and upon click, saved carts details page is displayed. 
14.a. It's possible to restore the previously saved cart. 

**Actual Results:** 
14. No saved carts listed. It's gone. 

---
Upon further review and manipulation, one can see that the saved cart functionality doesn't work at all. With or without CPQ products.  ⚠️ ⚠️ ⚠️ 

Compare with 3.3.0 rc0 deployment without CPQ here: 
https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/
Use regular rustic-hw users.

**Comment by giancorderoortiz** [comment]
Save cart with cpq product: 

![Screen Shot 2021-05-03 at 6 34 55 AM](https://user-images.githubusercontent.com/46171897/116890594-cc708800-abfb-11eb-9be0-884b46710a50.png)

Saved cart is listed in Saved Carts page. 
![Screen Shot 2021-05-03 at 6 35 22 AM](https://user-images.githubusercontent.com/46171897/116890644-d8f4e080-abfb-11eb-9034-08a6ce254753.png)

Saved cart details are available 
![Screen Shot 2021-05-03 at 6 35 51 AM](https://user-images.githubusercontent.com/46171897/116890705-e611cf80-abfb-11eb-9cdf-bd27345780a9.png)

After logout and login, saved cart is gone.
![Screen Shot 2021-05-03 at 6 38 11 AM](https://user-images.githubusercontent.com/46171897/116890747-f32ebe80-abfb-11eb-8e63-09e41da8cce2.png)

**Comment by bgambocjaviniar** [comment]
Apparently, it only happens with the user `cpq16@sap.com`. All other users from 17-19 are fine.

**Comment by bgambocjaviniar** [comment]
Do note that it's not the saved cart functionality that is broken with CPQ

`Cart requests (GET requests)` in general are broken with CPQ on with the cpq(16-19) users

**Comment by ChristophHi** [comment]
This is fixed. For a more detailed description of the fix and root cause, see https://cxjira.sap.com/browse/TIGER-7521
