### ISSUE TITLE
Sync site context Accelerator to Spartacus

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#12290]
As part of #11682 we like to support the sync of site context from Accelerator to Spartacus and visa versa. There are various pieces of site context / session state that must be synced:
- language
- currency
- selected store (Point of Service) 

The site context is often part of the URL, but some customers allow users to toggle this without updating the URL. While this isn't best practice, we like to support them with synchronising the state. 

When a user changes the language/currency selection from Accelerator, a JavaScript click/change event on Accelerator stores the language/currency ISO in browser’s session storage with key `language`:
```js
sessionStorage.setItem('language', selectedLanguage); 
```

The synchronisation of selected Store (Point of Service) between Spartacus and Accelerator is implemented via the use of a cookie with key ${site.uid}-storeId.

**Comment by tobi-or-not-tobi** [comment]
@LTiger14 can you validate whether this is already possible with the changes you were planning on in the StatePersistenceService?

**Comment by LTiger14** [comment]
Replaced by #12509

**Comment by LTiger14** [comment]
Replaced by #12509
