### ISSUE TITLE
Checkout examples in Spartacus 3.x documentation are based on 2.x

### ISSUE THREAD

**Issue by maciej-jezierski** [SAP/spartacus#12317]
I am trying to set up various things with version 3.x https://sap.github.io/spartacus-docs
Most of the examples for checkout are based on 2.x which is not usable in 3.x. 

Example: https://sap.github.io/spartacus-docs/extending-checkout/#routing-and-configuration
is referring to B2cStorefrontModule with config while the new way of providing config is with the method provideConfig against the module. Most of the examples are not working.

**Comment by giancorderoortiz** [comment]
@gladius-mtl fyi

**Comment by giancorderoortiz** [comment]
@plabadie fyi

**Comment by gladius-mtl** [comment]
Yes, I'm actually going to create a ticket today that captures all the docs affected by this, because there are a lot, and it will need attention from more than just one developer 🙂

**Comment by gladius-mtl** [comment]
All relevant code examples have been updated. See https://github.com/SAP/spartacus-docs/issues/1161.
