### ISSUE TITLE
[PR provided] Hide the paging/filtering/sorting controls when no search results.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#1231]
To repro: In the main search box in the header, type a search that returns no results.

Expected result: Shouldn't the page be empty or display a message about no results?

Observed results: The page displays the paging/filtering/sorting controls while there are no search results.  The page looks odd and the controls of course don't respond to user interactions.

<img width="648" alt="screen shot 2019-02-07 at 3 09 17 pm" src="https://user-images.githubusercontent.com/7065346/52440259-98c15900-2aeb-11e9-96da-c5b178bdf022.png">

**Comment by Xymmer** [comment]
We received a PR: #3405
