### ISSUE TITLE
Wrong condition in the `OAuthLibWrapperService` casue error during SSR

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#12321]
See this SO question:
https://stackoverflow.com/questions/67299872/error-when-trying-to-access-spartacus-pages-during-ssr-while-authservice-is-impo

I've worked around this by overriding `OAuthLibWrapperService`, in particular I'v changed this condition:
https://github.com/SAP/spartacus/blob/develop/projects/core/src/auth/user-auth/services/oauth-lib-wrapper.service.ts#L38

to this:
```
this.authConfigService.getOAuthLibConfig()?.redirectUri ??
        (!isSSR
          ? // eslint-disable-next-line @typescript-eslint/no-non-null-assertion
            this.winRef.nativeWindow!.location.origin
          : ""),
```

basically, brackets has been added (so during SSR location is not called anymore when `redirectUri` is specified).

**Comment by marlass** [comment]
Will be backported to 3.3. As it can be fixed on the spartacus implementation side I decided to skip older minor backports, as it would cause too much work at this crucial pre major time.
