### ISSUE TITLE
Test passthrough messaging setting with 2105

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#12385]
See https://github.com/SAP/spartacus/issues/10658 for background.
This ticket is to test only that there are no issues with using the backwards compatibility "passthrough" setting with 2105 and Spartacus.

**Comment by giancorderoortiz** [comment]
@bgambocjaviniar fyi

**Comment by bgambocjaviniar** [comment]
The only thing this does is change the message to either a 'generic' error message or a 'forward' error message.

This does not affect Spartacus as we just 'normalize' the error in a way that we show the same error on what we get back from the backend. Moreover, the only thing in Spartacus that we depend on 'sometimes' are the 'type' of errors that we get back, where we display proper 'global messages' accordingly. 

**Will be running e2es against this server (dev0) to confirm nothing breaks in relation to error handling messages.**

**Comment by bgambocjaviniar** [comment]
works for both `FORWARD` and `GENERIC` error message

https://dashboard.cypress.io/projects/k3nmep/runs/15205/specs?utm_source=github
