### ISSUE TITLE
Remove deprecated NgTabsetModule

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#12396]
https://sap.service-now.com/now/workspace/agent/record/sn_customerservice_case/0816f56fdbffe054dc7a9825f396195f

**Comment by Pucek9** [comment]
QA steps:
Open http://localhost:4200/electronics-spa/en/USD/store-finder/find?query=%20 page in mobile mode and compare visibility & functionality of tab/navigation - is it exactly the same as on develop branch.
Best for multiple browsers.

**Comment by giancorderoortiz** [comment]
No regression seen. 
Tested with 4.0 RC0
