### ISSUE TITLE
Smart Edit Not working After Upgrading Spartacus from 1.4.4 to 3.2.0

### ISSUE THREAD

**Issue by satheesh-kumar-m** [SAP/spartacus#12395]
We are facing an issue in the Spartacus upgrade where the Smart Edit is not working as expected. 

Spartacus version:  upgrading from 1.4.4  TO 3.2
Hybris version :  1905.7

Issue:
When a page is opened in AdvancedEdit mode, the page does not highlight the slots on the page and because of that no component can be added or edited.
Context menu is not getting shown in Smartedit.

We followed below document to setup Smart edit,
https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/

And below issue also not  related to my issue,
https://github.com/SAP/spartacus/issues/845

**Comment by satheesh-kumar-m** [comment]
Team,
Anyone please confirm,
Which document needs to be followed for Spartacus 3.2.0,
- https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/#configuring-smartedit-to-work-with-spartacus-32-or-newer
- or
- https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/#configuring-smartedit-to-work-with-spartacus-31-or-older

Looks we should follow old approach for 3.2.0 as well, as 3.2.1 configuration is like lazy loading concept, but 3.2.0 is same as 1.4.4

**Comment by olavii** [comment]
We are facing the same issue after upgrade from 3.0 to 3.2 and performing "Configuring SmartEdit to work with Spartacus 3.2 or Newer" as per instructions.

**Comment by satheesh-kumar-m** [comment]
It works fine after updating the app as per below SAP document,

https://sap.github.io/spartacus-docs/reference-app-structure/

Smart edit will be rendered as lazy loaded module from 3.2.0.

**Comment by satheesh-kumar-m** [comment]
> We are facing the same issue after upgrade from 3.0 to 3.2 and performing "Configuring SmartEdit to work with Spartacus 3.2 or Newer" as per instructions.

We need to update our app structure,
https://sap.github.io/spartacus-docs/reference-app-structure/
