### ISSUE TITLE
Missing translation and text escaping off the button in storefinder list

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#12422]
**Steps to reproduce:**
Open http://localhost:4200/electronics-spa/en/USD/store-finder/find?query=%20 page in mobile mode. Then click for any store

**Results:**
![image](https://user-images.githubusercontent.com/8040837/117986577-08ad9200-b33a-11eb-9b0c-81120cf3a9bd.png)

**Expected results:**
- [ ] fix missing translation key [ [storeFinder:storeFinder.clickBack] - verify if it could be an empty string or if there has to be some "Back" text for a11y
- [ ] fix (too long) text is escaping out of the button (QA: verify on few screen widths)

**Comment by giancorderoortiz** [comment]
Seems ok. 
![Screen Shot 2021-07-14 at 5 39 23 PM](https://user-images.githubusercontent.com/46171897/125696780-84d3c167-fe35-4479-b5b3-01b19b4b64b1.png)

![Screen Shot 2021-07-14 at 5 39 28 PM](https://user-images.githubusercontent.com/46171897/125696782-5da69b61-c51e-47b1-b44a-3b0819bcd732.png)

![Screen Shot 2021-07-14 at 5 40 07 PM](https://user-images.githubusercontent.com/46171897/125696783-788653d6-8d62-4789-b3c5-48e31ac4aca0.png)

**Comment by giancorderoortiz** [comment]
In landscape mode, button size may be wrong. 
Pending deployment in CCV2 to test with mobile devices.
