### ISSUE TITLE
Spartacus 3.2.2 installation- shows few warnings and error

### ISSUE THREAD

**Issue by Ajaykumarkonda** [SAP/spartacus#12434]
Hi Team

I have tried fresh Spartacus installation 3.2.2. Followed below steps
1)  After store creation
2) ng add @spartacus/schematics@3.2.2
3) It prompts few interactive questions are:
4) Please choose which configuration you would like to add? - b2b 
5) Which Spartacus features would you like to setup? Assisted Services Module, Cart, CDC, CDS, Organization (b2b feature), Product, Product Configurator, Qualtrics, SmartEdit, Store Finder, Tracking
6) Which User features would you like to setup? Account, Profile
7) What is your base URL? https://spartacus-demo.eastus.cloudapp.azure.com:8443/
8) Few optional questions left blank
9)  Which Tracking features would you like to setup? Tag Management System - Google Tag Manager
10)Which Product features would you like to setup? Bulk-Pricing, Product-Variants
11) few more question - selected all as option
Installation was completed successfull
12) Next npm install
it shows below
audited 1549 packages in 11.328s

90 packages are looking for funding
  run `npm fund` for details

found 46 vulnerabilities (45 moderate, 1 high)
  run `npm audit fix` to fix them, or `npm audit` for details
13) After that ng serve
**Issue**: I am able to see powertools site but in console i am seeing below warnings and error
![image](https://user-images.githubusercontent.com/23554781/118139439-f9574300-b424-11eb-944a-5e51064e3253.png)

Please let me know is there any missing in installation to overcome the warnings and error.

**Comment by LTiger14** [comment]
Note for implementer:

Error comes from `personalization-context.service.ts` line 33 and happens only when no `context` configuration is provided.

**Comment by WeizhengSap** [comment]
The issue is caused by, cds still call the deprecated `PersonalizationContextService`, but the deprecated `PersonalizationModule` is not imported in 3.2.

**Comment by WeizhengSap** [comment]
@Ajaykumarkonda : I fixed the issue and it will be backported to 3.2 and 3.3. If you don't want to wait for the release, you can import the deprecated `PersonalizationModule` from core to overcome error.
