### ISSUE TITLE
Schematics - introduce a common setup flag

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#12441]
After introducing the new interactive prompts, we've receive a feedback to introduce some sort of a flag that will remove the prompts and install the most common features and configuration (e.g. b2c with user, checkout, etc.).

A maybe better alternative is to run the schematics with the `interactive` flag set to false: `ng add @spartacus/schematics --interactive=false`.

To be decided on the approach, as well as on the default set of features.

Source: https://sap-cx.slack.com/archives/G01F7JM4VKM/p1620863991068000

**Comment by znikola** [comment]
@Xymmer Which features should be pre-selected?

**Comment by Xymmer** [comment]
See https://cxwiki.sap.com/display/spar/Spartacus+ng+Installation+Presets
