### ISSUE TITLE
Menu does not reset itself after being closed on mobile view.

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#12477]
**Describe the bug**
When opening the menu in mobile view, whichever subsequent menus are opened remain when the menu is reopened.

**Tell us the version of Spartacus**
- Library version: 3.3

**To Reproduce**
1. Open Spartacus in mobile
2. Click on menu button
3. Go to any sub-category
4. Close the menu
5. Re-open the menu.

**Expected behavior**
Should start menu state from beginning with all submenus closed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**
I recommend making this fix togglable as a "feature" as some users may still prefer to maintain the menu state.

**Comment by ren-tham** [comment]
Pr: https://github.com/SAP/spartacus/pull/12564
Deprecation Note: https://github.com/SAP/spartacus/issues/12573

**Comment by giancorderoortiz** [comment]
@Zeyber Don't see a fix yet. 
Please double check fix is deployed in 4.0 RC0. 
See http://spartacus-devci7672.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD

![mobile_layout_error](https://user-images.githubusercontent.com/46171897/125695661-f35657a5-bd76-4aeb-85bb-a4f554baf318.png)

**Comment by Zeyber** [comment]
@giancorderoortiz The fix seems to work fine on the deployment provided. What you have shown in the picture seems to be another unrelated issue. Would you mind creating a ticket for it?
