### ISSUE TITLE
Create E2E with 100+ SKU Cart

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12478]
Create perf test to:
1. Login
2. Fill up cart with 100+ SKU
3. In cart page, change qtys throughout.
4. Collect timing data for page update upon qty change.  (fail if delay + 5 sec? )
5. checkout.

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/spartacus/issues/10379

**Comment by giancorderoortiz** [comment]
See https://github.com/SAP/spartacus/issues/12478

**Comment by giancorderoortiz** [comment]
See https://github.com/SAP/spartacus/issues/11997

**Comment by giancorderoortiz** [comment]
See https://github.com/SAP/spartacus/compare/feature/GH-11997

**Comment by giancorderoortiz** [comment]
Halted for now.

**Comment by KateChuen** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-251
