### ISSUE TITLE
ExternalRouting Module does not get added when generating / updating a project

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#12486]
**Describe the bug**
When using schematic to generate / update the project, among others, the file `spartacus-features.module.ts` is generated / updated

Within the spartacus code, this file has the following section:

```
/************************* Opt-in features *************************/

    ExternalRoutesModule.forRoot(), // to opt-in explicitly, is added by default schematics
    JsonLdBuilderModule,

    /************************* External features *************************/
```

After running the schematics, the generated file `spartacus-features.module.ts` in my project does NOT contain the line ` ExternalRoutesModule.forRoot()`

**Tell us the version of Spartacus**
- Library version: 3.3.0

**To Reproduce**
1. Generate a fresh spartacus project
2. Open the file `spartacus-features.module.ts`
3. Notice that the file does not contain the ExternalRoutesModule

**Expected behavior**
According to the comment within the file in the spartacus codebase `// to opt-in explicitly, is added by default schematics` and since the documentation about the feature does not say anything about opting in manually (https://sap.github.io/spartacus-docs/external-routes/), I would expect, that the schematics adds the line according to the spartacus version of the file `spartacus-features.module.ts`.

**Screenshots**
Spartacus Feature Module:
![image](https://user-images.githubusercontent.com/3381820/118669419-034abe80-b7f6-11eb-87c2-082df187e8bc.png)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Other Ticket about External Routing**
https://github.com/SAP/spartacus/issues/12292

**Comment by giancorderoortiz** [comment]
@marlass fyi.
