### ISSUE TITLE
Brainstorm Test Strategy for SmartEdit

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12499]
Need to come up with a test strategy that includes the automated testing of Smartedit in Spartacus. 

Include: 
@hackergil, @bgambocjaviniar 

Dedicated server needed? 
How to test in CI?

**Comment by giancorderoortiz** [comment]
@KateChuen any thoughts?

**Comment by KateChuen** [comment]
Actually had that talk with Bill last release. We decided that it's the smartedit team that will be responsible for the testing going forward. Bill taught them how to install spartacus with smartedit, and they do the testing. 
Whether or not they automate it, is their decision I guess.
