### ISSUE TITLE
Deprecation for 12477

### ISSUE THREAD

**Issue by ren-tham** [SAP/spartacus#12573]
To implement the following feature/bug fix for https://github.com/SAP/spartacus/issues/12477, the constructor for this component needed to be changed to include an additional class in the constructor params list. Also a new class property was introduced as a flag field.

Constructor deprecation for `navigation-ui.component.ts`. 
Introduction of new class property. (method-and-properties).

**Comment by ren-tham** [comment]
Visit PR for more details.

**Comment by ren-tham** [comment]
PR: https://github.com/SAP/spartacus/pull/12679

**Comment by marlass** [comment]
Closed with #12564
