### ISSUE TITLE
e2e suite for SSR

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#12596]
Suite of end to end tests for SSR validation

- [x] Validation of main pages
  - [x] Homepage
  - [x] PLP
  - [x] PDP
- [x] SEO elements validation
  - [x] canonical ulrs,
  - [x] title.
  - [x] description
  - [x] ld schema

- [ ] Add a parameter to make SSR timeout configurable

**Comment by giancorderoortiz** [comment]
Checkout flow excluded from this effort?

**Comment by hackergil** [comment]
@giancorderoortiz Yes. The goal of testing SSR is to make sure the page is properly put together on the server. Testing functionality is not the goal, only initial page rendering.
