### ISSUE TITLE
Add the ability to provide CDC configurations to CDC install schematics

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#12594]
The CDC integration library schematics installs the CDC integration library with the default feature configurations.

Provide a way to pass in custom configurations via the schematics.

The configurations are:

- `baseSite`
- `javascriptUrl`
- `sessionExpiration`

### Proposed changes

- Add the ability to provide the configuration in schematics, interactive and non-interactive.
- Use current values as default (if any).

**Comment by SherwinVarghese** [comment]
This issue has been fixed by [PR#15793](https://github.com/SAP/spartacus/pull/15793)
