### ISSUE TITLE
E2E test for B2C Saved Carts

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12593]
Saved cart functionality verified only for b2b. See 'b2b-saved-cart.e2e-spec.ts'. 

Please verify saved cart functionality with b2c as well by writing an e2e test. 

- Include restore cart please. 
- Please complete checkout with saved cart.

**Comment by giancorderoortiz** [comment]
Please assign to Jonathan.

**Comment by bgambocjaviniar** [comment]
duplicate https://github.com/SAP/spartacus/issues/11942

**Comment by KateChuen** [comment]
To verify if all the scenarios mentioned in this ticket have been implemented in 11942.

**Comment by bgambocjaviniar** [comment]
closing again as mentioned above that this is a duplicate and the other one is in progress which is picked up already
