### ISSUE TITLE
Ecstatic Library Security Update. Bump version to 4.1.3

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12605]
See  https://github.tools.sap/cx-commerce/spasec/issues/63

**Comment by Platonn** [comment]
The impact is very very low. At the worst case it slows down / crashes the dev server that runs with `http-server` package. Btw. I believe we don't use this package at all (other than `yarn start:pwa`)

**Comment by giancorderoortiz** [comment]
To be handled after 4.0 release.

**Comment by giancorderoortiz** [comment]
Risk assumed by team.
