### ISSUE TITLE
Improve ProductVariantStyleSelectorComponent unit tests

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#12644]
![image](https://user-images.githubusercontent.com/10993491/120477810-79c9ed80-c3ac-11eb-80e2-a7a7a6725e74.png)
For some reason, only this component from product/variants feature-lib doesn't have decent unit test coverage.

**Comment by cmanciero** [comment]
Is this still an issue?

![Screen Shot 2022-03-14 at 3 49 06 PM](https://user-images.githubusercontent.com/664825/158249700-fcade42f-f4a8-48a9-8c16-0e37841ab343.png)

**Comment by dydome** [comment]
I was able to fix branches value to meet our coverage target:
![image](https://user-images.githubusercontent.com/18736434/158373756-924d8a63-f73f-4046-a4c6-1bdae900e33c.png)
