### ISSUE TITLE
Increasing item qty in cart creates an infinite loop.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#12662]
Increasing item qty in cart creates an infinite loop.  User can't checkout.

Spartacus version: develop branch on 2021-06-02 ( commit 2bcc19816609d8131ba009b58b9e44e731371146 )
Backend: Main dev server with promotions enabled.

Please make an assessment to see if past releases are also affected and discuss with PO to see if the fix requires a backport and for which version(s).

While there might be more ways to repro, these steps that are sure to reveal the issue:
* Enable all the promotion rules in the backend
* Add the Sony Alpha 350 in the cart
* Go to the cart page
* Click plus to increase the quantity of the Sony Alpha item.

Unexpected result:  
* There is an infinite loop with a backend call
* The checkout button does not work.

![issue-video](https://user-images.githubusercontent.com/7065346/120659887-c963f400-c454-11eb-929c-b62dea2410f1.gif)

**Comment by Xymmer** [comment]
Let's consider backporting to 2.x if warranted, but not back to early 3.x releases

**Comment by Xymmer** [comment]
May(be) related? #11806

**Comment by bgambocjaviniar** [comment]
> May(be) related? #11806

not related

**Comment by Pucek9** [comment]
The issue consists of 2 bugs:
- When we have promotion for free product - while update quantity, cart-item-list.component tries update also this item (unexpected behavior) so in result we got failed response. The [hotfix](https://github.com/SAP/spartacus/pull/12682) will cover only this case.
- cart-item-list.component is observing change of cart state, then try update entry, if its fail it will load cart, when cart is loaded, component will do that again. Creted new issue: #12687

**Comment by giancorderoortiz** [comment]
Review priority. Is it a blocker?

**Comment by bgambocjaviniar** [comment]
> Review priority. Is it a blocker?

A blocker because if there's a free item due to a promotion, and want to update the quantity of the cart item, then we won't be able to checkout due to the infinite loop.

Need a cart owner to review this ticket.

**Comment by giancorderoortiz** [comment]
This works. Loop is gone.
