### ISSUE TITLE
[part of 4.0 feature lib work] CheckoutAuthGuard fails with implicit flow or authorization code flow

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#12709]
When running spartacus with authorization code or implicit flow we get `undefined` as a value from `userService.get()` and that fails in the b2b roles check.

To check:
- why we get undefined there?
- is it correct behavior?

**Comment by giancorderoortiz** [comment]
We need to backport this fix to 3.4.
@plabadie @WeizhengSap. 

Wait for checkout lib work to be merged before working on this bug fix.

**Comment by giancorderoortiz** [comment]
Team decided this is a critical issue that needs to be fixed for 4.0.
