### ISSUE TITLE
Smart edit is unstable after Spartacus storefront upgrade to version 3.2.2

### ISSUE THREAD

**Issue by satheesh-kumar-m** [SAP/spartacus#12705]
We recently upgraded our Spartacus storefront app from **1.4.4** to **3.2.2**

After upgrade Smart edit is unstable, it is not working properly.

Edit options are not working. Sometimes edit options getting enabled.

Storefront rendered in SSR.

Our Hybris version is **1905.19**

Please help us to resolve it.

**Comment by Xymmer** [comment]
@satheesh-kumar-m apologies for late response. 
- There is a known issue if SmartEdit is started and loads Spartacus using SSR for the first page. If you click on a link then go back, it should work after that. Can you confirm?
- Is your storefront otherwise working as expected in 3.2.2?
