### ISSUE TITLE
Drop unnecessary params mapping in the routing configs

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12719]
Routing params mapping 1:1 are redundant and can be removed. Whole lines in:
https://github.com/SAP/spartacus/blob/58963fcc21004935f0d4501b4f926f27e30377bb/feature-libs/cart/saved-cart/root/saved-cart-root.module.ts#L58
https://github.com/SAP/spartacus/blob/58963fcc21004935f0d4501b4f926f27e30377bb/feature-libs/organization/order-approval/root/order-approval-root.module.ts#L57

It shouldn't change any behavior, it's just a code cleanup.

For more, see docs https://sap.github.io/spartacus-docs/configurable-router-links/#parameters-mapping

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.
- did a smoke test of saved cart and order approval in b2b. Looks ok.
