### ISSUE TITLE
Button in AssignCellComponent has no type

### ISSUE THREAD

**Issue by mateuszo** [SAP/spartacus#12722]
**Describe the bug**
I'm not sure if it's a bug or not but caused a lot of trouble in one of our implementation projects. The project requirement was to combine B2B Unit details with B2B Unit edit form so that there's one step less for the user to modify the unit. It worked fine but the approvers' assignment feature worked awkwardly. Once in a while, when the assign/unassign button was clicked the user was redirected to the unit details. It happened frequently but not always which caused trouble in debugging. The cause was that AssignCellComponent became part of the FormComponent and because the button has no type it is a submit button and submitted the unit edit form. To fix this we had to re-create AssignCellComponent only to add `type="button"` to it and modify the configuration to replace the component.

**Tell us the version of Spartacus**
- Library version: 3.2

**To Reproduce**
1. Use AssignCellComponent inside of a form
2. Observe that it not only toggles the assignment but submits the form as well

**Expected behavior**
The button inside the AssignCellComponent should not submit the form - it should have `type="button"` . It is a good practice to declare button type explicitly (see: https://html.com/attributes/button-type/). 

**Additional context**
Sorry for the very complex description. It was hard to debug so it's hard to explain 😅

**Comment by Xymmer** [comment]
Can we get this one merged for 4.2?
