### ISSUE TITLE
Order promotions not showing on Replenishment Orders

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#12745]
Order promotions not showing on Replenishment Orders

Spartacus version: develop branch on 2021-06-10
Backend: Main dev backend (2011)

Steps to reproduce:
* Create a replenishment order with order promotions.
* Go in My Account -> Replenishment Orders -> details
* Expected result: The order promotions returned by the backend are displayed
* Actual result: The order promotions returned by the backend are not displayed

Note: The product promotion for the order items has the same issue, but its fixed by the checkout lib.

![01-place-order](https://user-images.githubusercontent.com/7065346/121741987-3dde0900-cacd-11eb-8154-d79d62ef645b.png)

![02-order-conf](https://user-images.githubusercontent.com/7065346/121741985-3dde0900-cacd-11eb-9c3f-80b302b049fd.png)

![03-repl-order-details](https://user-images.githubusercontent.com/7065346/121741984-3d457280-cacd-11eb-8ddc-459da48913b9.png)

**Comment by giancorderoortiz** [comment]
Team reconsidered and decided this is a Minor bug.

**Comment by giancorderoortiz** [comment]
Issue fixed: 

![Screen Shot 2021-07-14 at 6 03 35 PM](https://user-images.githubusercontent.com/46171897/125699052-ad44b4b7-5ab9-4f98-bd3e-2e7964fa4b9b.png)
