### ISSUE TITLE
Missing translation in the title of the added to cart modal

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12804]
**Describe the bug**
Title of the added to cart modal is not translated. Only the raw translation key is displayed.

**Tell us the version of Spartacus**
- Library version: develop 13fa85353767f55f2acbe0457c144d7955108e0a (for 4.0)

**To Reproduce**
1. Go to any PLP
2. Click on [add to cart] button
3. See missing translation in the title

**Expected behavior**
Title is translated

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/122222748-d5b76a80-ceb2-11eb-831a-a5d6b265bd43.png)

**Additional context**
It would be good to investigate why this translation recently got missing and to double check if the reason didn't cause more missing translations. Possible reasons from top of my head: due to moved translations file, renamed key, ... ?

**Comment by Platonn** [comment]
Could have been already fixed by https://github.com/SAP/spartacus/pull/13028/files#diff-8cc2607fbe1ec0caa87f0c3ecac4f6637a9ff80f8fad2e7856d621d5878d2c48R8

**Comment by bit172** [comment]
I tested it on the latest develop and I'm no longer able to reproduce it. Will need more confirmation before closing this.

**Comment by giancorderoortiz** [comment]
Fixed with 4.0 RC0.
