### ISSUE TITLE
[Master] Technical Architecture Diagrams

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#12809]
Per internal formal security audit requirement (Summer 2021). 
Sirius/PPMS system. 

Technical Architecture Diagrams are hereby requested for Spartacus main features as follows: 

1. ASM https://github.com/SAP/spartacus/issues/12810 (PatrickL?) ***
2. Session Management https://github.com/SAP/spartacus/issues/12813 (Marcin) ***
3. Qualtrics https://github.com/SAP/spartacus/issues/12814 (Brian)
4. SmartEdit https://github.com/SAP/spartacus/issues/12815 (Wei)
5. Tag Management Systems https://github.com/SAP/spartacus/issues/12816 (Nik?) ***
6. Extensibility https://github.com/SAP/spartacus/issues/12817 (Kris?)
7. CPQ https://github.com/SAP/spartacus/issues/12818 (Jutta)
8. CDS https://github.com/SAP/spartacus/issues/12819 (Brian?)
9. B2B My Company https://github.com/SAP/spartacus/issues/12820 (MichalG)
10. Coupons and Promotions https://github.com/SAP/spartacus/issues/12821 (?)
11. Server Side Rendering https://github.com/SAP/spartacus/issues/12822 (Stan) ***
12. PWA https://github.com/SAP/spartacus/issues/12823 (Stan)
13. Lazy Loading https://github.com/SAP/spartacus/issues/12824 (Stan)
14. Consent Management https://github.com/SAP/spartacus/issues/12825 (Nik?) ***
15. Anonymous Consents https://github.com/SAP/spartacus/issues/12826 (Nik?)
16. Saved Carts https://github.com/SAP/spartacus/issues/12827 (Brian)
17. Express and Guest Checkout https://github.com/SAP/spartacus/issues/12828 (Louis)
18. Store Locator https://github.com/SAP/spartacus/issues/12829 (?)
19. Events https://github.com/SAP/spartacus/issues/12830 (Louis)
20. Text Field Configuration https://github.com/SAP/spartacus/issues/12831 (Jutta)
21. B2B Order Approvals https://github.com/SAP/spartacus/issues/12832 (MichalG?)

Examples to be added here: 
https://cxwiki.sap.com/display/spar/Spartacus+Technical+Architecture+Diagrams

**Comment by giancorderoortiz** [comment]
See https://jira.tools.sap/browse/CXSPA-85

**Comment by Xymmer** [comment]
Bill closed all TAM tickets - refer to CXSPA ticket for more
