### ISSUE TITLE
API Documentation not found

### ISSUE THREAD

**Issue by olavii** [SAP/spartacus#12807]
**Describe the bug**
API Documentation, as described in project's README.md, has just disappeared from the ether.

**To Reproduce**
1. Go to API documentation URL https://sap.github.io/spartacus/
2. Observe 404

**Expected behavior**
API documentation is found from API Documentation URL.

**Screenshots**
Described in README.md:
![image](https://user-images.githubusercontent.com/24874051/122265235-29d94380-cee1-11eb-88a5-08f083d44181.png)

Reality:
![image](https://user-images.githubusercontent.com/24874051/122265159-14641980-cee1-11eb-8bce-db4850991b3b.png)

**Comment by olavii** [comment]
API Documentation seems to have been restored.

**Comment by olavii** [comment]
API Documentation seems to have disappeared.

**Comment by olavii** [comment]
API Documentation seems to have broken or gone through changes in release 3.4.0. Please provide information how to access API documentation.

https://github.com/SAP/spartacus/releases/tag/styles-3.1.3 <- docs.zip 18 MB
https://github.com/SAP/spartacus/releases/tag/asm-3.4.0 <- docs.zip 45 KB

**Comment by gladius-mtl** [comment]
@olavii The link to the API documentation is currently working. Do you have any further issues or questions related to accessing the API docs?

**Comment by gladius-mtl** [comment]
There was an issue that was causing the API doc site to stop working whenever a new release was published. The issue has been fixed.
