### ISSUE TITLE
Console error in children create

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#12841]
Need to fix error in console occurring among others in:
http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Retail/children/create

**Comment by Platonn** [comment]
![image](https://user-images.githubusercontent.com/4001059/122421301-91989880-cf8c-11eb-8951-1f8971fc3e67.png)

**Comment by giancorderoortiz** [comment]
Issue fixed.
