### ISSUE TITLE
Schematics installation: It must be possible to select VC configurator without textfield or CPQ

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#12852]
As of 3.4, installation only allows configurators with textfield and with CPQ support. So it's not possible to install the minimal (VC) scope.

In 3.3, one first selected configurators, and then was presented with the 2 additional options.

Has probably been introduced with #12289

**Comment by znikola** [comment]
Right, thanks for catching this.
Sorry for overlooking it.
