### ISSUE TITLE
Change "Santorini" to "santorini" in the theme switch

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#12890]
Right now the theme santorini has a capital "S". It should be a lower case "s".
<img width="1669" alt="Screen Shot 2021-06-21 at 8 49 04 AM" src="https://user-images.githubusercontent.com/2947470/122764693-bc753c00-d26d-11eb-8b6e-835aea8ab2f7.png">
<img width="840" alt="Screen Shot 2021-06-21 at 8 52 31 AM" src="https://user-images.githubusercontent.com/2947470/122765006-0d853000-d26e-11eb-80c7-f1e3002860c8.png">

**Comment by giancorderoortiz** [comment]
Simple change does not take effect. 
Is re-initialization/restart needed in backend?

**Comment by giancorderoortiz** [comment]
This issue blocks comprehensive testing of blue theme in browsers / devices. 
Please fix soon.

**Comment by giancorderoortiz** [comment]
@WeizhengSap, @zebercut, @hackergil, @Xymmer unable to complete this task. 
Instructions provided do not work. 

Deployed on devci3. Santorini theme not seen.

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/187
Theme code has lower 's', and name has upper 'S'. So, in backoffice, you still see `Santorini`, but in Spartacus, you should see `santorini` in class.

**Comment by giancorderoortiz** [comment]
This is working now. 
Finally... 
Some screenshots: 

![Screen Shot 2021-07-11 at 6 26 13 PM](https://user-images.githubusercontent.com/46171897/125211691-3fd6eb80-e276-11eb-8f4d-5cf2382a7c2d.png)
![Screen Shot 2021-07-11 at 6 26 30 PM](https://user-images.githubusercontent.com/46171897/125211692-3fd6eb80-e276-11eb-9f52-2cda9d0d7585.png)
![Screen Shot 2021-07-11 at 6 27 25 PM](https://user-images.githubusercontent.com/46171897/125211693-406f8200-e276-11eb-9951-ff78bc4ba5de.png)
![Screen Shot 2021-07-11 at 6 27 42 PM](https://user-images.githubusercontent.com/46171897/125211694-406f8200-e276-11eb-8f04-fdf91ad70daa.png)
![Screen Shot 2021-07-11 at 6 28 31 PM](https://user-images.githubusercontent.com/46171897/125211695-41081880-e276-11eb-8a1d-1289ccb5d77d.png)
![Screen Shot 2021-07-11 at 6 28 46 PM](https://user-images.githubusercontent.com/46171897/125211696-41081880-e276-11eb-9c81-226a40760c23.png)
![Screen Shot 2021-07-11 at 6 29 02 PM](https://user-images.githubusercontent.com/46171897/125211697-41081880-e276-11eb-9775-4a577810f111.png)
![Screen Shot 2021-07-11 at 6 30 27 PM](https://user-images.githubusercontent.com/46171897/125211699-41a0af00-e276-11eb-939b-d9301a426e27.png)
![Screen Shot 2021-07-11 at 6 30 40 PM](https://user-images.githubusercontent.com/46171897/125211701-41a0af00-e276-11eb-91a9-8cd6abdcd55c.png)
![Screen Shot 2021-07-11 at 6 30 56 PM](https://user-images.githubusercontent.com/46171897/125211702-42394580-e276-11eb-8942-4bc337e95f83.png)

**Comment by giancorderoortiz** [comment]
See http://spartacus-devci7673.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-07-11 at 6 37 46 PM](https://user-images.githubusercontent.com/46171897/125211811-1f5b6100-e277-11eb-919a-8d890b51ecfd.png)
