### ISSUE TITLE
Document migration for arguments of OccEndpointsService.buildUrl

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12938]
Currently our migration docs say:
https://github.com/SAP/spartacus/blob/a05a2ce335ced384e529c3884f3c5425415508cb/docs/migration/4_0.md#L1267

It would be nice to mention also how the signature of the method getUrl->buildUrl has changed.

```
Aguments of the method `getUrl`: 2nd, 3rd and 4th, are now merged in one 2nd argument object with properties: `urlParams`, `queryParams` and `scope`. 
```

**Comment by LTiger14** [comment]
Fixed in https://github.com/SAP/spartacus/pull/12943
