### ISSUE TITLE
Redundant [Sign in / Register] button after login in a fresh installed app 

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12958]
**Describe the bug**
After logging into a fresh installed Spartacus app (using installation script), there is a redundant [Sign in / Register] button.

**Tell us the version of Spartacus**
- Library version: develop 8b54d2719fbd8ff237fd2e36163881e771c71d5a (without ng12 yet)

**To Reproduce**
1. `$ cd scripts/install`
2. `$ ./run.sh install` (takes some time, grab a coffee)
3. `$ ./run.sh start`
4. Open http://localhost:4200/powertools-spa/en/USD/login in your browser, 
5. Login as linda.wolf@rustic-hw.com
6.   Verify a bug: the button `Sign in / Register` remains in the top menu, regardless the user has been already logged in.
7. `$ ./run.sh stop`

**Expected behavior**
There is no `Sign in / Register` button after user logs in.

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/123826819-643ed980-d900-11eb-9736-2fb4ea959b47.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (arm64)

**Additional context**
Note: this bug doesn't happen in our storefrontapp.
Probably there is an issue with the schematics installation script - this needs to be investigated.

**Comment by giancorderoortiz** [comment]
Should be fixed in 4.0

**Comment by giancorderoortiz** [comment]
Change that caused this bug has been reverted. 
Closed during bug triage.
