### ISSUE TITLE
Totally broken styling of B2B My Organization page in a fresh installed app 

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12959]
**Describe the bug**
After visiting B2B My Organization page in a fresh installed Spartacus app (using installation script), the page styling is broken, making the feature unusable.

**Tell us the version of Spartacus**
- Library version: develop 8b54d2719fbd8ff237fd2e36163881e771c71d5a (without ng12 yet)

**To Reproduce**
1. `$ cd scripts/install`
2. `$ ./run.sh install` (takes some time, grab a coffee)
3. `$ ./run.sh start`
4. Open http://localhost:4200/powertools-spa/en/USD/login in your browser, 
5. Login as linda.wolf@rustic-hw.com
6.  Go to http://localhost:4200/powertools-spa/en/USD/organization or http://localhost:4200/powertools-spa/en/USD/organization/units and verify the page is totally mis-styled.
7. `$ ./run.sh stop`

**Expected behavior**
The organization page is properly styled.

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/123827904-4f167a80-d901-11eb-8cf6-ad1c6d96b8e7.png)

![image](https://user-images.githubusercontent.com/4001059/123827966-5ccc0000-d901-11eb-8b01-12a236db3f62.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (arm64)

**Additional context**
Note: this bug doesn't happen in our storefrontapp.
Probably there is an issue with the schematics installation script - this needs to be investigated.

**Comment by morganm58** [comment]
moved to jira
