### ISSUE TITLE
Searchbox is misplaced to the right, but should be centered

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#12961]
**Describe the bug**
Unless some design changes were made recently to move the searchbox to the left, I consider it a bug it's on the left now. It used to be centered.

**Tell us the version of Spartacus**
- Library version: develop 8b54d2719fbd8ff237fd2e36163881e771c71d5a (without ng12 yet)

**To Reproduce**
1. `$ yarn start`
2. visit homepage http://localhost:4200/electronics-spa/en/USD/
3. Verify the searchbox is moved to the left

**Expected behavior**
The searchbox is centered, as it used to be.

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/123830954-1af08900-d904-11eb-82b9-ca63301d79c8.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 91.0.4472.106 (Official Build) (arm64)

**Additional context**
After logging in as an user, the searchbox is back centered.

Not sure, if related: https://github.com/SAP/spartacus/issues/12958

**Comment by Platonn** [comment]
it seems the bug might have been introduced in PR https://github.com/SAP/spartacus/pull/12539
We should sort it out before 4.0, as @developpeurweb has concerns about the styling conventions too

**Comment by developpeurweb** [comment]
@pratikkumar90, when your PR is ready please add @morganm58 or me as reviewers to validate styling conventions. Thanks.

**Comment by giancorderoortiz** [comment]
Change that caused this bug was reverted. Closing during bug triage.
