### ISSUE TITLE
Blue theme not working

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#12966]
Blue Theme (santorini) is added as a class to an app root component. In our Spartacus project (storefrontapp), the root component is `cx-storefront`. But, if Spartacus is installed from libraries (using schematics), the root component node name is `app-root`.

Blue theme should work with the latter.

**Comment by giancorderoortiz** [comment]
Required for 4.0

**Comment by hackergil** [comment]
When building and running spartacus using the installation script (by building the libraries), the CSS for Santorini is not being included in the styles file.

Also, I noticed that we are importing Santorini css in the storefrontapp `src/styles.scss` file, but not on the generated shell app

**Comment by hackergil** [comment]
From @LTiger14:

Rather than making sure the theme is always included in the final styles. We could make it so that the theme is only added when specifically imported by customers (see PR).

That way if the theme is not used, it’s not part of the final CSS bundle.

**Comment by developpeurweb** [comment]
For future themes and style customizations imported into the `styles.scss` file. This issue boils down to **relative paths not working in prod.**
cc @morganm58
