### ISSUE TITLE
Error connecting spartacus with Smart edit SAP

### ISSUE THREAD

**Issue by BeniaminoOsculatiEY** [SAP/spartacus#12976]
Hi,
I'm just trying to connect my local spartacus project with the smart edit of my SAP Commerce Cloud localhost.
I've followed the guide https://sap.github.io/spartacus-docs/smartEdit-setup-instructions-for-spartacus/#page-title to connect spartacus and smart edit, adding the smart edit extension on my local website and allowed into the whiteListedStorefronts my localhost "https://localhost:4200" and setted up my Cockpit WCMS to.
When I try to access to the smart edit this is my error:
![Screenshot 2021-06-30 at 16 04 54](https://user-images.githubusercontent.com/86728004/123974560-f9070d00-d9bc-11eb-986d-a6a5f0d128e0.png)

I've searched online some resolution for this issue but didn't have found something that helps me.
Have someone the same issue or can help me?

Thanks
Beniamino

**Comment by giancorderoortiz** [comment]
@WeizhengSap please confirm this is indeed a bug.

**Comment by WeizhengSap** [comment]
@giancorderoortiz : This is not bug. There is something wrong with the setup. Please make sure the app can be opened with `https://localhost:4200`. From the console log, I can see there are `GET` errors. The requests to backend should work.

**Comment by LTiger14** [comment]
@BeniaminoOsculatiEY Please see the comment above. Also, the console shows you are trying to connect to two backend servers (demo and localhost:9002). Make sure you are using the same one as SmartEdit.
