### ISSUE TITLE
EventService is not working in spartacus 3.4.0

### ISSUE THREAD

**Issue by lmachnik** [SAP/spartacus#12988]
when I subscribe to eventService for PageEvent no any events come during navigating to different pages

```
export class AppComponent implements OnInit {
  ...
  constructor(events: EventService){}
  ...
  ngOnInit() {
     this.eventService.get(PageEvent).subscribe(event => console.log("page event", event));
  }
}
```

 - OS: macOS Big Sur 11.4
 - Browser: chrome
 - Version: 91.0.4472.114

**Comment by znikola** [comment]
Hi. I can't reproduce this with the following vanilla setup:
- `ng new mystore --routing=false --style=scss && cd mystore`
- `ng add @spartacus/schematics@latest --interactive=false`
- implement the given code to subscribe to `PageEvent`
- `yarn start` 
- open the browse, navigate between pages and check the console.

Can you share more details? Have you made any relevant customizations to the events or events service?

**Comment by giancorderoortiz** [comment]
Waiting for reply from @lmachnik
