### ISSUE TITLE
Create sample data (mock server)

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#13]
We've started a mock server implementation, using [json-server](https://github.com/typicode/json-server) and [faker.js](https://github.com/Marak/faker.js). The goal of this mock server is to be up and running for devs so that they can start right away without being dependent on a commerce backend.  (no commerce backend required). Other advantages are around mocking unit tests, e2e testing, and implementing new features for those areas where there's not yet a backend ready. 

Currently the mock data can be generated for a commerce backend. The sample data is outdated, and this is the main thing we like to fix in this epic:
- complete mock data
- generate sample up-to-date sample data
- consider using the mock server for e2e

In addition, we need to publish the mock/sample data in an npm package, so that it can be versioned and pulled for projects.

We might want to do this with the following approach:
1. update existing or create a new sample data set (that's in the backend)
2. generate the mock data from the sample data set

This approach gives a number of advantages:
- we can regenerate with each and every release
- our e2e tests will validate our storefront against the sample data we deliver
- customer can regenerate the sample data for their own projects, e2e tests, etc.
- existing commerce applications can benefit from the data sets
- we can run parts of the app with mock data and others with a real backend

**Comment by holmesadrianh** [comment]
Is there any update regarding mock services? It would be great for the front end developers to be able to create and build the UI and interactive elements without needing the backend up and running. This will really streamline the front end aspect a great deal.

**Comment by ozahid89** [comment]
Hi @tobi-or-not-tobi 
Is it possible to use mock server for development purposes now? I can't seem to find any documentation regarding this.

All files under mock-server/generator are deleted.

**Comment by tobi-or-not-tobi** [comment]
@ozahid89 we've not continued the development the mock server since a long time. I guess the main problem is that it's quit time consuming to create and maintain it, even when we add quiet significant time to automate. 

That being said, you can use a mockserver yourself. The underlying webpack dev server is providing a config to route http requests to an alternative server. 

We've discussed this topic a few times in the team, and decided to drop the mock server (see #7627), at least for. now. I'll create a ticket to drop the mock server entirely to avoid further confusion and set the expectation.
