### ISSUE TITLE
Css-what Library Security Update. Bump Version to 5.0.1

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#13027]
https://github.tools.sap/cx-commerce/spasec/issues/72

**Comment by Platonn** [comment]
The impact is very very low. At the worst case, it slows down / crash the build of the Angular application https://security.netapp.com/advisory/ntap-20210706-0007/

**Comment by giancorderoortiz** [comment]
Risk accepted after conversation with @meeque. Closing.
