### ISSUE TITLE
Enable keyboard-focus configurations by default

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#13036]
In `keyboard-focus.config.ts`, features were introduced to fix bugs that could be reverted if the user decided that they did not want or wanted to customize the solutions. Now that we are going to a new major, lets turn these on by default for desktop and mobile.

The issues being addressed were:
#10143 - `enableResetViewOnNavigate`
#11636 - `enableResetFocusOnNavigate`

Note: Features need to be documented.

**Comment by giancorderoortiz** [comment]
@gladius-mtl see comments in ticket description.
