### ISSUE TITLE
CX 2105 E2E Failures. Missing Android Client. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#13043]
Unable to authenticate to Spartacus when using a backend with CX 2105. 

See https://dashboard.cypress.io/projects/k3nmep/runs/19277/test-results/9fd260df-99ab-4a82-93e2-e213a2477db6

Error: 
![Screen Shot 2021-07-08 at 11 12 09 AM](https://user-images.githubusercontent.com/46171897/124947042-852cbc00-dfdd-11eb-9e01-75f30010d9a8.png)

CX 2105: 
![Screen Shot 2021-07-08 at 11 14 21 AM](https://user-images.githubusercontent.com/46171897/124947336-bc02d200-dfdd-11eb-8053-4eed737390c7.png)

CX 2011:
![Screen Shot 2021-07-08 at 11 14 40 AM](https://user-images.githubusercontent.com/46171897/124947448-d5a41980-dfdd-11eb-9a62-626e16a834c8.png)

**Comment by giancorderoortiz** [comment]
Added a blocks-4.0 label given severity of bug. 
May require update of sample data to force creation of Oauth client. 
Solution should not cause side effects that cause failures when working with 2011. 

@dunqan, @hackergil, @Xymmer, @zebercut

**Comment by plabadie** [comment]
The`mobile_android` auth client can be created by running this impex via HAC:

```
INSERT_UPDATE OAuthClientDetails;clientId[unique=true]    ;resourceIds       ;scope        ;authorizedGrantTypes                                            ;authorities             ;clientSecret    ;registeredRedirectUri
                                ;mobile_android           ;hybris            ;basic        ;authorization_code,refresh_token,password,client_credentials    ;ROLE_CLIENT             ;secret          ;http://localhost:9001/authorizationserver/oauth2_callback;
```
(source: [bottom of this help page](https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/2011/en-US/627c92db29ce4fce8b01ffbe478a8b3b.html))

This impex should probably **not** be part of the sample data unless we make sure it its compliant with security policy. I have reasons to think it might not be compliant.

As a convenience for setting up our dev servers without adding an additional manual impex import step (and without adding it to the sample data either), we have a custom extension for internal use only whose purpose is to load the `mobile_android` oauth client.  It can be part of a followup improvement ticket to add the extension to the server setup procedure/scripts.

**Comment by giancorderoortiz** [comment]
@meeque fyi

**Comment by giancorderoortiz** [comment]
I think this requires documentation as well. @gladius-mtl 
Further internal discussion is needed.

**Comment by hackergil** [comment]
Customers are already being asked to add this client themselves. Our team does not create it.
https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2011/#step-3-import-occ-credentials
