### ISSUE TITLE
Dependency cleanup - ProductListModule

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#13050]
ProductListModule and component currently depends on add-to-cart component, which will be moved out to cart-lib

**Comment by WeizhengSap** [comment]
We can remove `<cx-add-to-cart>` from `product-list-item.component.htm`, and add this config in cart lib. The only thing is registering Outlet happens in `APP_INITIALIZER`. So, this `AddToCart` module has to be in cart root. We have to figure out how to make outlet work with lazy loaded module.
```
provideOutlet({
      id: ProductListOutlets.ITEM_ACTIONS,
      component: AddToCartComponent,
    }),
```
