### ISSUE TITLE
Dependency Cleanup - BadRequestHandler

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#13051]
BadRequestHandler from ( projects/core/src/global-message/http-interceptors/handlers/bad-request/bad-request.handler.ts)

Depends on `isCartNotFoundError` ini the cart utils. BadRequestHandler can't depend on the cart lib.

**Comment by WeizhengSap** [comment]
We can create `CartBadRequestHandler` in cart lib, and move function `handleBadCartRequest` to there.
