### ISSUE TITLE
Routing store APIs are unaccessible

### ISSUE THREAD

**Issue by guiliguili** [SAP/spartacus#13065]
**Describe the bug**
[spartacus/projects/core/src/routing/index.ts](https://github.com/SAP/spartacus/blob/develop/projects/core/src/routing/index.ts) does not use the [spartacus/projects/core/src/routing/store/index.ts](https://github.com/SAP/spartacus/blob/develop/projects/core/src/routing/store/index.ts) which make some APIs (e.g. `CustomSerializer`) unaccessible using "@spartacus/core" import directive

**Tell us the version of Spartacus**
- Library version: 3.3.1

**Comment by Platonn** [comment]
`CustomSerializer` is not meant to be exposed in the current state in the public API. We plan first to refactor it in https://github.com/SAP/spartacus/issues/7070

If you **really** must import it, consider using this trick on your own risk: https://stackoverflow.com/questions/66871919/how-to-use-private-api-of-the-spartacus-library/66871920#66871920
