### ISSUE TITLE
Findings after testing 4.0 migrations on an example app

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#13082]
(priorities: 🟥high, 🟨medium, 🟩low)

- [x] 🟥 A comment is added without leading `// TODO:Spartacus`. See: `Property 'defaultPageSize' was removed, to modify default page size use 'view.defaultPageSize' configuration property.`  (note: it's not the only methods/properties migrations lacking it the preceding //)
   -   TODO: add missing `// TODO:Spartacus`
- [x] 🟥 routing.go -> the comment is vague about the second argument
    -    TODO: Rephrase the comment so it's more helpful (and the docs): `'RoutingService.go' changed signature. Before 4.0, the object with query params could be passed in the 2nd argument. Now the 2nd argument is Angular NavigationExtras object (with 'queryParams' property).`
- [x] 🟥 LanguageService.initialize -> produces a lot of false-positives comments in files that just import LanguageService but declare/use method `initialize()` of a different item than LanguageService
    - [x] TODO: amend comments to include also the name of the class, not only the method - so the comment is more precise and helps customers realise when it's really a false-positive -> for the method initialize() 
    - [x] TODO: repeat it for every migration of properties/methods
- [x] 🟥 Interface `Item` has broken migration (removed API). It uses CartItemComponent instead of the Item as the referenced node.
    -   TODO: fix the typo in removed API migrations to use Item instead of CartItemComponent (+rephrase comment to be clear and concise)
- [x] 🟥 The `@spartacus/cart` lib is not installed after the migration, although the `@spartacus/checkout` depends on it, so it produces an error when building the custom application. Perhaps it's a problem with not installing transitive peer dependencies? TBD
   -    TODO: Investigate why it's not installed and improve the schematics mechanism to install cart lib. Addressed in https://github.com/SAP/spartacus/issues/13086
- [x] 🟨 method OccEndpointsService.getUrl was renamed to buildIUrl and changed signature. The commend is too vague
    -   TODO: Improve the comment so it describes what was the past shape of the arguments and how to refactor them: `Method 'OccEndpointsService.getUrl' was renamed to `buildUrl` and changed signature. Before 4.0, 'urlParams', 'queryParams' and 'scope' were separate arguments (2nd, 3rd and 4th). Now they are properties of one wrapper object passed in the 2nd argument.`
- [ ] 🟨 symbol rename schematics has changed correctly a lot of services to their corespondent New Facades. But we're lacking the general docs on the New Facades
   -   TODO: Add general docs on the New Facades

- [x] 🟩 There is no mention in the docs nor migrations about the CartItemContext needed to be provided on the level of the CartItemComponent. Similar for ProductListItemContext.
    -   TODO: Add docs about required CartItemComponent and ProductListItemContext - they need to be provided in appropriate place in the components tree. Moreover we might provide the error message that happens then those classes are not provided, so it's easier to search for this issue for customers. Addressed in https://github.com/SAP/spartacus/issues/13218
- [x] 🟩 We discovered upgrading angular, ng-bootstrap and ng-select is a bit tricky. It's best to upgrade them all at the same time in one command line.
   -   TODO: Add to our migration docs how to best migrate to ng12 and related 3rd party deps using one command line `ng update @ng-bootstrap/ng-bootstrap @ng-select/ng-select @angular/cli`.
- [x] [not-an-issue] There is no migration nor docs for the removed OccEndpoints: login, revoke
   -  Explanation: the customer implemented a custom login flow which used occ endpoints: login and revoke 
- [x] [not-an-issue] Constructor migration for `CartDetailsComponent` didn't work. It didn't remove the `PromotionService` from `super(
      activeCartService,
      promotionService,
      selectiveCartService,
      authService,
      routingService
    );`
   -  Explanation: the example app used a customized version of the `ActiveCartService`. That's why it didn't match with our migration config `{ className: ACTIVE_CART_SERVICE, importPath: SPARTACUS_CORE },`. So the migration didn't apply, which is fair.
- [x] [won't fix] because of the new app structure, a few things need to be imported by the customers themselves in their app module (i.e. RouterModule, ngrx modules, etc.) -> this will cause runtime errors on app start
   -    Explanaton: those issues should not happen when customer migrates first to the new app structure, which we _highly_ recommend in our 4.0 docs
   
### Future improvements needed in schematics mechanism:
- Currently schematics for methods/properties check only if the item is imported and then it comments ANY existence of the string with the name of the method/property (regardless it belongs to the deprecated item or not). In future, we should consider improving it to take into account only the instance of the referenced item, but not any string of the same name. It's addressed in https://github.com/SAP/spartacus/issues/10140 
- Our schematics mechanism for methods/properties should add `// TODO:Spartacus` by default. There should be no need to define it explicitly in the concrete schematics data. It's addressed in https://github.com/SAP/spartacus/issues/13084

**Comment by giancorderoortiz** [comment]
@zebercut, @Xymmer, @hackergil, @gladius-mtl fyi.

**Comment by Platonn** [comment]
Removing 'critical' lablel, as all most important parts of this ticket are already done and merged to release/4.0.x branch
