### ISSUE TITLE
Flaky e2e asm.e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#13091]
Last 7 days on `asm.e2e-spec.ts` [has a high failure rate on develop](https://dashboard.cypress.io/projects/k3nmep/analytics/top-failures/9b5ca8b2-6650-eb29-babc-a0c9d89cbe95-6bd8135b-5cd3-f405-49f7-8ec924b39d61?branches=%5B%7B%22label%22%3A%22develop%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222021-07-07%22%2C%22endDate%22%3A%222021-07-14%22%7D&viewBy=TEST_CASE). Let's mark it as flaky and then fix it.

![image](https://user-images.githubusercontent.com/4001059/125584428-1a582ceb-3e86-4b2b-9c80-15f63ec5b717.png)

**Comment by dydome** [comment]
It just failed in another check -> https://dashboard.cypress.io/projects/k3nmep/runs/25217/test-results not sure if we should reopen it?

**Comment by hackergil** [comment]
Yep. I've seen this one before intermittently

![Screen Shot 2021-11-23 at 10 08 56 AM](https://user-images.githubusercontent.com/158500/143049913-fb804e9b-b279-446f-8878-9110e0ebb558.png)
