### ISSUE TITLE
Updating an existing address without changing any values throws an error in console

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13128]
**Describe the bug**
When you have an existing address set in your account and try to update it, but choose not to, you will get a console error after clicking the 'UPDATE ADDRESS' button. 

**To Reproduce**
1. Go to your Address book, which can be found under 'My Account'.
2. Click edit on an existing address
3. Do not change any values and click 'UPDATE ADDRESS'

**Expected behavior**
It should not produce any console log errors.

We should handle the case of not updating any values from an address and submitting an 'update address' api request as it throws a console error.

**Screenshots**
![Screen Shot 2021-07-15 at 3 49 18 PM](https://user-images.githubusercontent.com/29099466/125849176-5db9fcb3-a33f-4da1-aa04-9d1af94c1c05.png)

**Comment by Xymmer** [comment]
note that this was started with a pr from someone who is no longer with us... pls check pr is ok or fix it and then move to review
