### ISSUE TITLE
Address book button misalignment

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13129]
**Describe the bug**
The buttons entire width is longer than the input boxes. It should contain the same width or smaller.

**Screenshots**
![Screen Shot 2021-07-15 at 3 57 50 PM](https://user-images.githubusercontent.com/29099466/125849686-cc3dfdf3-d526-45cb-a9f7-cea48de2f20f.png)

**Comment by giancorderoortiz** [comment]
Also an issue with Spartacus 3.0. 
![Screen Shot 2021-07-16 at 3 26 32 PM](https://user-images.githubusercontent.com/46171897/125999111-a56a18f1-d066-472a-9352-56e528c18b75.png)

@morganm58 is it so by design?
