### ISSUE TITLE
Blue theme - styling not applied to the replenishment #

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13127]
**Describe the bug**
With replenishment orders in the replenishment listing 'history' page, there is no blue theming compared to the order listing 'history' page in terms of the order #

**To Reproduce** **Must be in B2B**
1. Go to replenishment orders under 'my account' (when you're logged in). Make sure you have replenishment orders already.
2. Visually see that no styling was applied in relation to the blue theme compared to the order history page.

**Expected behavior**
Same theming as the order history page

**Screenshots**
![Screen Shot 2021-07-15 at 3 41 06 PM](https://user-images.githubusercontent.com/29099466/125848164-5358a121-6b3a-4268-b383-6296387a3f24.png)
![Screen Shot 2021-07-15 at 3 46 37 PM](https://user-images.githubusercontent.com/29099466/125848412-afc16f5e-50af-4f14-8050-2b1dea515d5b.png)

VS

![Screen Shot 2021-07-15 at 3 41 12 PM](https://user-images.githubusercontent.com/29099466/125848172-c4e681f8-fff4-48ee-ab50-564efbce0711.png)

**Comment by giancorderoortiz** [comment]
@morganm58 fyi
