### ISSUE TITLE
[Firefox] - In stock label moving depending on adding/removing a quantity in product details page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13123]
**Describe the bug**
using the firefox browser, In any product details page with a product in stock, the 'In stock' label shifts up or down.

It shifts up when you click the '+' button to increase the quantity
It shifts down when you click the '-' button to decrease the quantity

**USING Firefox browser**
**To Reproduce**
1. Go to any product details page
2. Click on '+' and see the in stock label shift up (visually)
3. Click on '-' and see the in stock label shift down (visually)

**Expected behavior**
The 'In stock' label should not visually move when adding or removing quantities

**Screenshots**
**When '-' is clicked**
![Screen Shot 2021-07-15 at 1 00 45 PM](https://user-images.githubusercontent.com/29099466/125827837-e530747a-20f2-4812-b8b4-a854d891c9c3.png)

**When '+' is clicked**
![Screen Shot 2021-07-15 at 1 01 13 PM](https://user-images.githubusercontent.com/29099466/125827906-46afe51d-4632-4ffe-b62b-a1606740ed85.png)

**Additional context**
Not related to the blue theme.

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.
Tested on Firefox. 
It's ok now. Also verified in chrome and safari. 

![Screen Shot 2022-04-21 at 10 00 25 AM](https://user-images.githubusercontent.com/45409515/164474942-2d791a67-70a4-4b56-a763-532ee1f620c2.png)

![Screen Shot 2022-04-21 at 10 00 20 AM](https://user-images.githubusercontent.com/45409515/164474947-3c3d8934-9858-45a3-baa3-207e387fef2a.png)
