### ISSUE TITLE
Blue theme - My Account visual bug?

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13124]
When the user is not logged in, the blue theme has 'Sign in / Register' as a blue-ish color
When the user is logged in, the 'My Account' dropdown has a white color

**It is hard to see 'My Account' with the light grey background.**

**Expected behavior**
Should have the same color as 'Sign in / Register'

**Screenshots**
![Screen Shot 2021-07-15 at 1 25 28 PM](https://user-images.githubusercontent.com/29099466/125831376-b08e070b-0c7f-45d9-b27d-25d88a0b5468.png)
![Screen Shot 2021-07-15 at 1 24 31 PM](https://user-images.githubusercontent.com/29099466/125831383-e198f0cb-3389-4e2f-b496-8451f233364c.png)

**Comment by morganm58** [comment]
fixed in GH-13147
