### ISSUE TITLE
[BE] Infinite checkout bug with certain regions

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13125]
**Describe the bug**
If you try to checkout with `Macao, China` or `Taiwan, China`, we will see the infinite loop happen on delivery mode. 

1.  login as any user
2. go through the process to add items to your cart and checkout
3. select a new shipping address, and choose either `Macao, China` or `Taiwan, China` as a region. The rest of the form can be anything.
4. see the infinite loop on the next step.

**Expected behavior**
Should be able to go through checkout without a problem

**Screenshots/Videos**
https://user-images.githubusercontent.com/29099466/125840593-2d140c25-a0ae-45c4-8275-036ea43f4574.mov

**Additional context**
There's no response error nor console errors related to the next checkout step.

**Comment by giancorderoortiz** [comment]
Does this happen with any regions in North America or Europe? If so, then please change severity to Major.

**Comment by dydome** [comment]
It is no FE issue. Looks like BE issue. The spinner is here because there are no available delivery modes for this destination.

`https://40.76.109.9:9002/occ/v2/powertools-spa/users/current/carts/'cart_id'/deliverymodes?lang=en&curr=USD`

and the response is:

`{
   "deliveryModes" : [ ]
}`

**Comment by Xymmer** [comment]
created backend issue CXEC-9982, closing
