### ISSUE TITLE
Blue theme - wrapped title and icon that is breaking visual styling in my company for units

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13131]
**Describe the bug**
In my company, under any units, the title and info button are wrapped.

**To Reproduce**
1. Go to my company
2. Click Units
3. Choose any units
4. See the wrapped changes between the title and the info button

**Expected behavior**
The button should stay on the same position pre blue theme.

**Screenshots**
OLD
![Screen Shot 2021-07-15 at 4 59 48 PM](https://user-images.githubusercontent.com/29099466/125857600-007343e0-3ccc-4122-8ac1-b3507c313492.png)

NEW
![Screen Shot 2021-07-15 at 5 00 21 PM](https://user-images.githubusercontent.com/29099466/125857607-4992bd5d-5c73-4245-a25d-7f4cd465fb03.png)

**Comment by giancorderoortiz** [comment]
@morganm58 fyi

**Comment by morganm58** [comment]
fixed in GH-13158
