### ISSUE TITLE
Blue theme - focus on button is red looks like old styling

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#13136]
**Describe the bug**
There is wrong styling for focus for the buttons as links.

**Tell us the version of Spartacus**
- Library version: 4.0

**To Reproduce**
1. Go to PDP
2. Click on 'Show reviews' or "Add to wish list"

**Expected behavior**
Focus with some blue color

**Screenshots**
![santirini issue 1](https://user-images.githubusercontent.com/18736434/125924187-205233f6-049c-4a35-b4c7-65bb3c6fff44.png)
![santirini issue 2](https://user-images.githubusercontent.com/18736434/125924358-a1c462b1-4ef2-4b9f-a5c5-a5d1e1c252c1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge, Chrome

**Comment by giancorderoortiz** [comment]
@morganm58 fyi
