### ISSUE TITLE
Button text is not aligned in Storefinder all stores view

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#13135]
**Describe the bug**
Text in buttons should aligned to the middle of the button area.

**Tell us the version of Spartacus**
- Spartacus 4.0RC.0 (blue theme)

**To Reproduce**
1. Go to 'Find a Store' link
2. Click on '.View all stores'
3. Select a country
4. See misaligned text

**Screenshots**
![Screenshot 2021-07-16 at 10 54 17](https://user-images.githubusercontent.com/6958810/125921854-fd7cafce-4a65-4a7a-a22b-0b0ef5e59bfb.png)

**Desktop**
 - Browser safari 14.1 (16611.1.21.161.6)
 - Device: MacBook Pro

**Comment by giancorderoortiz** [comment]
@morganm58 fyi
