### ISSUE TITLE
Shipping address for Units sticking to left for iphone and ipad

### ISSUE THREAD

**Issue by Parthlakhani** [SAP/spartacus#13132]
CSS issue with shipping address for units

- Library version: 4.0
-Tested on: https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

1. Go to `unit` in `my company`
2. open a unit that has a shipping address added (create address if not found)
3. Shipping address sticks to the left

**Expected behavior**
Normal CSS with some margin, same as desktop.

**Screenshots**

![IMG_0021](https://user-images.githubusercontent.com/72991814/125857423-66c09ec6-c9af-45fe-be9a-989260be87a5.PNG)

<img width="378" alt="Screen Shot 2021-07-15 at 5 03 15 PM" src="https://user-images.githubusercontent.com/72991814/125857332-6bfc8995-87d3-4f07-9bbd-ed0a0d773d60.png">

**Device Information**
 - Device: [ipad Air, iphone X]
 - OS: [iOS14.6, iOS14.2]
 - Browser [Chrome, Safari]

**Comment by giancorderoortiz** [comment]
@morganm58 fyi

**Comment by morganm58** [comment]
<img width="847" alt="Screen Shot 2021-07-21 at 2 32 57 PM" src="https://user-images.githubusercontent.com/2947470/126541359-e7a237a7-73e1-4c32-b7b9-30648f4ec2f9.png">
looks like it's fixed now
