### ISSUE TITLE
Mobile menu is broken

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#13141]
**Describe the bug**
Mobile menu is broken. There overflows on some elements and they have wrong position.

**Tell us the version of Spartacus**
- Library version: 4

**To Reproduce**
1. Click on hamburger menu

**Expected behavior**
Elements positions should be fixed.

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/125928897-2e9ea6cf-41b8-4836-98d9-9f7f0876c581.png)

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS14.6
 - Browser [chrome, safari]

**Comment by Pucek9** [comment]
The same for Chrome and Firefox for Android device (8.1). Issue is visible even in destktop devtools (Windows Chrome / Firefox) mobile view in both environemnts/themes:
https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/
https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/
![image](https://user-images.githubusercontent.com/8040837/125943899-f34cd5a3-aa66-4422-b7da-50bb3b321606.png)
![image](https://user-images.githubusercontent.com/8040837/125942761-e8180c17-de3c-4b36-85dd-1c17e3b039d8.png)

**Comment by bgambocjaviniar** [comment]
duplicate and was fixed in https://github.com/SAP/spartacus/issues/13116

just need to be re-deployed
