### ISSUE TITLE
Selected Option price has to be shown even when Base price is 0.

### ISSUE THREAD

**Issue by AlexanderKuschner** [SAP/spartacus#13140]

**Comment by giancorderoortiz** [comment]
Please add steps to reproduce and screenshots

**Comment by AlexanderKuschner** [comment]
Normally, CPQ configurable product have a base price > 0. However, it is allowed that a CPQ configurable product would have no base price and the total (bundle) price will be a result of the selected options.
To reproduce this issue:
- set a base price = 0 for a CPQ product in the CPQ system (e.g. for CONF_COFFEEMACHINE_3000)
- in the SPA B2B shop search for the product mentioned above and press Configure button.
-  in the configuration screen select the 'Design' group and then select value 'Touchscreen' for the attribute 'Display'
Result:  'Selected Options' price is not shown (expected is in this case $ 200.00) - see screenshot.

**Comment by AlexanderKuschner** [comment]
![NoOptionPrice](https://user-images.githubusercontent.com/54353334/126147305-75ab36c8-4f4c-43b7-8108-ea07a5955338.PNG)
