### ISSUE TITLE
Santorini theme username is the wrong color

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#13147]
When logged in as a user while using Santorini theme the username is the wrong color.
![screen_shot_2021-07-15_at_6 23 59_pm](https://user-images.githubusercontent.com/2947470/125956263-a3cdeba3-1847-4ce7-85a8-004bb35c0efe.png)

**Comment by bgambocjaviniar** [comment]
duplicate of https://github.com/SAP/spartacus/issues/13124
