### ISSUE TITLE
Cannot place order - checkout

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#13142]
**Describe the bug**
I am not possible to place an order on the last checkout step as there is API error

**Tell us the version of Spartacus**
- Library version: 4

**To Reproduce**
1. Go to checkout and follow the step to "review order"
2. Click on 'place order'

**Expected behavior**
Should get a success message with an order confirmation page.

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/125929926-efaa2c29-a3cc-4074-a6cd-41c61bf3ed34.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Comment by bgambocjaviniar** [comment]
I think you're using a b2b account in a b2c storefront, which I believe does not work.

**Comment by giancorderoortiz** [comment]
Please use a b2c user and retry

**Comment by dydome** [comment]
That is correct, with a newly created user it works.
