### ISSUE TITLE
B2B tests failing due to admin user

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#13155]
Most of the B2B tests use Linda Wolf as an admin user.

We've seen failures when b2b tests are running simultaneously against the same backend that we think are related to Linda logging out in one test suite and logging in in another one. This causes issues with access tokens and tests failing.

Explore options to either add a new admin user or find a fix for these scenarios

**Comment by bgambocjaviniar** [comment]
PR: GH-14145
