### ISSUE TITLE
Search API responses returning 'wrong' values for breadcrumbs, brands, etc

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13164]
**Describe the bug**
The b2b response is returning wrong values in terms of breadcrumbs, brand, etc compared to what it was before. You can find the difference by comparing b2c and b2b as shown in the screenshots section.

**To Reproduce**
1. Go to any category page
2. Look at the breadcrumbs and brand filters

**Expected behavior**
The breadcrumb should have a name instead of the number
The brand facet filter should have a name instead of the brand code.

**Screenshots**
**B2B**
![Screen Shot 2021-07-16 at 12 19 39 PM](https://user-images.githubusercontent.com/29099466/125979101-aaa99684-a88a-4831-a5d6-571f9924c668.png)
![Screen Shot 2021-07-16 at 12 25 58 PM](https://user-images.githubusercontent.com/29099466/125979346-5bb9e834-92f4-403d-bf0e-fc369a2488bf.png)

--------------------

**B2C**
![Screen Shot 2021-07-16 at 12 21 37 PM](https://user-images.githubusercontent.com/29099466/125979364-02884487-039c-43ac-90d4-b6cdac80add3.png)
![Screen Shot 2021-07-16 at 12 26 48 PM](https://user-images.githubusercontent.com/29099466/125979371-747f596c-679f-45bc-8e91-8853a1ed31ab.png)

# Demo Spartacus instance that has 3.0 Spartacus 
https://spartacus-demo.eastus.cloudapp.azure.com:444/powertools-spa/en/USD/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Measuring-%2526-Layout-Tools/c/1358
![Screen Shot 2021-07-16 at 1 25 39 PM](https://user-images.githubusercontent.com/29099466/125986118-d14d7f5e-3fbf-41ed-aa20-32a1f8cf4d35.png)

**Comment by bgambocjaviniar** [comment]
I think it may be related to the commerce suite version, for example, 2005 vs 2011 vs 2105
There may exist a config to fix the issue if it's the case.

**Comment by giancorderoortiz** [comment]
@hackergil, @WeizhengSap fyi

**Comment by bgambocjaviniar** [comment]
I was assuming commerce suite versions as I thought the demo server's api `https://spartacus-demo.eastus.cloudapp.azure.com:8443` was using 2005. However, I was wrong as it's on 2011.0.

Our main dev sever 40.x.x.x is on 2011.4.

Using main develop to start the storefront,
- If we point to 40.x.x.x, then the b2b category is shown as those brand_codes
- if we point to https://spartacus-demo.eastus.cloudapp.azure.com:8443, then the b2b category is shown with proper category names

Therefore, I am assuming it's a config issue on the commerce suite that can solve this issue.

**Comment by Xymmer** [comment]
will be fixed when backend is fixed, nothing to do or test on our side, will create ticket for that team, closing
