### ISSUE TITLE
MyCompany - unit - shipping address table looks bad without padding

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#13177]
**Describe the bug**
In MyCompany under Units section when we go to shipping addresses they are looking bad, looks like there is no padding

**Tell us the version of Spartacus**
- Library version: 4

**To Reproduce**
1. Go to MyCompany
2. Click on Units
3. Click on any Unit
4. Click on any Shipping addresses
5. Find table with content

**Expected behavior**
Should have padding in row

**Screenshots**
![image](https://user-images.githubusercontent.com/18736434/126129184-4ecd5738-5d08-4507-a2f5-a1233a0b29f8.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome, Firefox, Edge

**Comment by morganm58** [comment]
<img width="1225" alt="Screen Shot 2021-07-21 at 2 10 12 PM" src="https://user-images.githubusercontent.com/2947470/126539562-6ff062ee-2b2c-4d54-bcb7-b7dd7fdbf504.png">
looks like it's fixed
