### ISSUE TITLE
Image loading strategy should be possible to set as an instance property

### ISSUE THREAD

**Issue by VGRAJED** [SAP/spartacus#13172]
I am using Spartacus version 3.4, and see it is possible to set loading strategy by setting it via the MediaService. Though helpful, it should be possible to pass down through instance property (`@Input`), as some images may require to be eager loaded, while maintaining lazy loading images for the rest.

https://github.com/SAP/spartacus/blob/release/4.0.x/projects/storefrontlib/src/shared/components/media/media.component.ts

An approach akin to just doing:

```
// Use passed down value, or defer to mediaService as default
@Input() loadingStrategy: ImageLoadingStrategy = this.mediaService.loadingStrategy === ImageLoadingStrategy.LAZY
            ? 'lazy'
            : null;
```

**Comment by Platonn** [comment]
Please document the change in the migration doc. 
Please don't create schematics for this migration. Those schematics will be created automatically by the tool of @plabadie  based on the difference between 4.3.x and 5.0, reported by the `api-extractor` tool.
