### ISSUE TITLE
[RE-TEST] Skiplinks are not working on Safari browser

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#13179]
**Describe the bug**
Skiplinks are not working on Safari browser.

**Tell us the version of Spartacus**
- Library version: 4.0-RC.0 deployed on https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/

**To Reproduce**
1. Open Safari browser and go to storefront page
2. Try to navigate with tab and shift+tab to get skip links functionality (see the bug)

**Expected behavior**
On Safari skiplinks should work like on the other browsers:
![Screenshot 2021-07-19 at 12 06 31](https://user-images.githubusercontent.com/6958810/126144471-9007e91f-a802-4cea-93d6-0be1ed8c60af.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.3.1
 - Browser: Safari Version 14.1 (16611.1.21.161.6)

**Comment by developpeurweb** [comment]
- Works fine for me on Safari Version 14.1.1 (16611.2.7.1.4)
- @Matejk00 can you please retest, but first make sure you have [this configuration in your Safari](https://github.com/SAP/spartacus/issues/5041#issuecomment-558883497), ignore the theme Calydon reference.

**Comment by Matejk00** [comment]
Re-tested with mentioned configuration, it's working fine.
