### ISSUE TITLE
Customers can not add own icon types

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13209]
**Describe the bug**
https://stackoverflow.com/questions/68455999/cx-icon-with-custom-icon-types-gives-an-error-when-stricttemplates-is-set-to

**Tell us the version of Spartacus**
- Library version: 4.0-rc

**To Reproduce**

1. Define own icon type in module (different than defined in `enum ICON_TYPE`)
2. Try use this icon type
3. See error like `Type 'CUSTOM_ICON_TYPE.CUSTOM_ICON' is not assignable to type 'ICON_TYPE'. ngtsc(2322)`

**Expected behavior**
Providing own icons should be possible

**Additional context**
Current workaround:
```<cx-icon [type]="$any(CUSTOM_ICON_TYPE.CUSTOM_ICON)"></cx-icon>```

**Comment by Platonn** [comment]
IMO it doesn't block the release. It's an old issue. And the workaround for customer is to use $any locally or configure angular globally not to use strict typing in templates.

Regardless, let's fix it soon.
- from Angular 12+ all new fresh apps have the strict template types enabled by default
- It seems easy to fix
