### ISSUE TITLE
There is a subscription in SelectiveCartService even feature is disabled.

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13200]
**Describe the bug**
https://stackoverflow.com/questions/68457402/spartacus-selective-cart

**Tell us the version of Spartacus**
- Library version: 4.0-rc

**To Reproduce**
1. change flag `selectiveCart.enable` to false in `spartacus-b2c-configuration.module`
2. debug subscription in constructor of `SelectiveCartService` and see that logic is called while login

**Expected behavior**
Logic in constructor shouldn't be called if feature is off.

**Tips**
I believe it's enough to wrap constructor logic in to
```if (this.isEnabled()) {...}```
but it requires nice QA

**Additional context**
Other classes uses this service:
![image](https://user-images.githubusercontent.com/8040837/126372102-1e553175-ea6b-4a54-9c9b-0d1d9679ee4c.png)
Only `CartDetailsComponet` and `CartPageLayoutHandler` verify that feature is enabled by `isEnabled` method before use it.

**Comment by pawelfras** [comment]
The `selectiveCart.enabled` flag is only responsible for handling the “Save for later” button. However, there is one more component that uses `SelectiveCartService` to call the API and is rendered regardless of the flag value - CMS-driven `SaveForLaterComponent`. To completely disable the “Save for later” functionality, remove this component from the Sample Data.
