### ISSUE TITLE
[Firefox B2B] Using spacebar to trigger info popover sends focus to top of page

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13204]
**Describe the bug**

- This happens only on **Firefox** (Mac/Win) and only when the _spacebar_ is used as trigger.
- Pressing the spacebar while focusing on the "i" icon will trigger the popover, but then it can only be seen for a few seconds, then the focus gets removed from the icon, and goes to the top of the page.

**Tell us the version of Spartacus**
- Library version: 4.0-RC.0 deployed on https://b2bspastore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/powertools-spa/en/USD/

**To Reproduce**
1. Using only the keyboard to navigate go to My Company
2. Click on Units
3. Tab to the information "i" icon and focus it.
4. Press the spacebar key.

**Expected behavior**
Same as if we press Enter: focus should remain in place.

**Screenshots**
![Screen Shot 2021-07-20 at 7 45 21 PM](https://user-images.githubusercontent.com/15113219/126411849-2ab1ef06-98c0-47f4-9afc-09c4851c195a.png)

**Desktop Mac:**
 - OS: macOS Big Sur
 - Browser: Firefox
 - Version: 90.0.1

**Desktop Win:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 90.0.1

**Additional context**
This is a minor bug since pressing the Enter key triggers the expected behaviour and no similar issues are found in other browsers.

**Comment by dydome** [comment]
Hi, @developpeurweb I have tested it on Firefox and everything is working fine now. Maybe there was some fix in the meantime. Closing this issue.
