### ISSUE TITLE
Maintain scroll position when moving back and forward

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#13220]
- Related to #10143 
- Chat with Bill and Caine and Stan for this one, it's a bit complex
- We'd want to fix in 4.x and back port to 3.4 if possible for a customer

Ideal situation:
- Search for something, search results appear
- Scroll down
- Click a product link, product page appears, at top of page.
- In product page, scroll down
- Click Back

When clicking Back, the search results page should appear at same scroll position.
When clicking Forward, should end up in same scroll position.
ONLY for Back and Forward. If I click a link, always go to top, even if we know scroll position.
(unless technically that's complicated, and just always go to saved scroll position.)

Some solution inspirations from Jongyun:
https://www.bennadel.com/blog/3534-restoring-and-resetting-the-scroll-position-using-the-navigationstart-event-in-angular-7-0-4.htm

**Comment by bgambocjaviniar** [comment]
Draft: GH-13279

This won't be fix in 4.0. This will be a new 'feature' in 4.x
PR draft is for references on the new 'feature'

**Comment by Xymmer** [comment]
Scroll restore was added to 4.2, can we close this one?

**Comment by Xymmer** [comment]
closing as outdated, fixed with other issues
