### ISSUE TITLE
Order Normalizers stay in core lib (4.x)

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13309]
Order Normalizers stay in core lib only for 4.x.  This will solve issues like the one below:

They will move in Order-lib in the next major release: GH-13321

In order confirmation page, the product image is not visible:

![Screen Shot 2021-07-30 at 10 35 29 AM](https://user-images.githubusercontent.com/44440575/127661009-afb3a29a-7e07-4492-b62a-6161be10764e.png)

**Comment by plabadie** [comment]
There is a high chance the cause is the ORDER_NORMALIZER is not being used as expected.
One of the suggested mitigations for order code dependency issues (GH-13284) is to leave the normalizer token in core for now.
I think this would also solve this bug.

**Comment by plabadie** [comment]
Order Confirmation image issue fixed:

<img width="1255" alt="Screen Shot 2021-08-03 at 2 55 31 PM" src="https://user-images.githubusercontent.com/7065346/128071694-97dcb1bb-cefc-407c-95f9-895db0eafb7e.png">
