### ISSUE TITLE
Santorini theme search box text color

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#13310]
Santorini theme search box text color is wrong.
<img width="532" alt="screen_shot_2021-07-28_at_12 00 17_pm" src="https://user-images.githubusercontent.com/2947470/127662112-a5df4d0b-e91a-4b37-a5e7-482569f158c9.png">

**Comment by KateChuen** [comment]
Tested locally using develop branch. 
Color is ok now.

<img width="1437" alt="Screen Shot 2022-05-26 at 2 43 50 PM" src="https://user-images.githubusercontent.com/45409515/170557547-3c140b6b-4a00-495b-b242-9ecc1ed93c73.png">
