### ISSUE TITLE
[MASTER] Added to Cart Toast

### ISSUE THREAD

**Issue by bit172** [SAP/spartacus#13317]
## Overview

**requirements/mock**: https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=SFR%3A+Added-to-Cart+Toast
**github labels**: `added-to-cart-toast`. 

## EPIC branch

All tickets should be merged towards `epic/added-to-cart-toast`. 

## Implementation

1 - Feature core logic
2 - UI component for the cart window
3 - Styling and animation
4 - Unit Tests
5 - E2E 
6 - Feature Doc

**Comment by Xymmer** [comment]
closing as this ticket moved to https://jira.tools.sap/browse/CXSPA-54
