### ISSUE TITLE
Fix dependencies in OrderDetailPermissionResultsComponent

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#13351]
[OrderDetailPermissionResultsComponent](https://github.com/SAP/spartacus/blob/develop/feature-libs/organization/order-approval/components/details/order-detail-permission-results/order-detail-permission-results.component.ts) can depend directly on `OrderApprovalDetailService` and does not need the abstraction of depending on `OrderDetailsService`
We can then also [remove the provider config](https://github.com/SAP/spartacus/blob/develop/feature-libs/organization/order-approval/components/details/order-approval-details.module.ts#L52-L53) in the cms configuration.

**Comment by WeizhengSap** [comment]
It seems that we cannot change it, because there are 2 cms components mapping to `OrderDetailPermissionResultsComponent` (one requires `OrderApprovalDetailService`, the other one requires `OrderDetailsService`): 
```
OrderApprovalDetailApprovalDetailsComponent: {
          component: OrderDetailPermissionResultsComponent,
          providers: [
            {
              provide: OrderDetailsService,
              useExisting: OrderApprovalDetailService,
            },
          ],
          guards: [AuthGuard, ApproverGuard],
        },
        AccountOrderDetailsApprovalDetailsComponent: {
          component: OrderDetailPermissionResultsComponent,
        },
```
