### ISSUE TITLE
[Epic] Introduce the Order Library

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13354]

**Comment by KateChuen** [comment]
Tested on dev9 server, with develop branch (Frontend) and 2105 backend.

Regression of these features on electronics:
- [x]  Order History
- [x]  Order Cancellations
- [x]  Order Returns

Regression of these features on powertools: (tested with local frontend pointing to dev9 backend)
- [x]  Replenishment orders

Ran the e2e tests locally, pointing to backend on dev9.
- [x]  electronics (order-cancellations-returns.e2e-spec.ts, order-history-no-orders-flow.e2e-spec.ts, order-history-orders-flow.e2e-spec.ts)
- [x]  powertools (b2b-replenishment-order-details-flow.e2e-spec.ts, b2b-replenishment-order-history-no-orders-flow.e2e-spec.ts, b2b-replenishment-order-history-orders-flow.e2e-spec.ts)
