### ISSUE TITLE
B2B Unit Not Created After Refresh Token Expiration

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#13370]
**Setup:**

1. Set access token validity to 1 minute and refresh token validity to 3 minutes in backend (restart required)
2. Enable express checkout in frontend
3. Backend version: 2005.6
4. Frontend branch: epic/oauth-improvements

**Steps to Reproduce:**

1. Login to Spartacus storefront as admin (i.e. linda)
2. Navigate to My Company
3. Click on Units. 
4. Follow steps to add a new business unit. 
5. Wait 3 minutes and 10 seconds. 
6. Click on save. 

**Expected Results:** 
6.a  User is redirected to login. 
6.b. After successful login, user is redirected to MyCompany and B2B unit is created. 

**Actual Results:** 
6.a User is redirected to login. 
6.b. After successful login, user is redirected to My Company Units. 
6.c. B2B unit not created.

**Comment by giancorderoortiz** [comment]
har file: 
[spartacus-devci7672_create_b2b_unit.har.zip](https://github.com/SAP/spartacus/files/6927242/spartacus-devci7672_create_b2b_unit.har.zip)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-08-03 at 5 45 58 PM](https://user-images.githubusercontent.com/46171897/128091711-4be37f13-3d59-463a-bdcd-6229350cca1b.png)

![Screen Shot 2021-08-03 at 5 46 06 PM](https://user-images.githubusercontent.com/46171897/128091714-532c30b0-ec96-40ba-9109-3dc4560b0947.png)

![Screen Shot 2021-08-03 at 5 46 44 PM](https://user-images.githubusercontent.com/46171897/128091716-c5e19918-cae5-4a06-ab65-b166b29e08bd.png)

**Comment by Xymmer** [comment]
closing as we have no mechanism currently to preserve field states before/after expiry/refresh process
