### ISSUE TITLE
Cart Page Headings structure needs optimization

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13371]
**Describe the bug**
While using a Screen Reader and navigating page content using the Elements Dialog the headings' current structure doesn't provide a logical sequence,  this is more noticeable on Screen Readers that will "nest" headings like NVDA (screenshots below).

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Add products to cart
2. Go to Cart Page
3. Open NVDA on Windows
4. Open Elements List (Ins+f7) and select "Headings"
5. See error: Order Summary nested under last product.

**Expected behavior**
Potential arrangement (TBD):
`<h1>` Your Shopping Cart
`<h2>` Cart number
    -- `<h3>`  Product names
`<h2>` Order Summary

**Screenshots**
<img width="960" alt="cart nvda" src="https://user-images.githubusercontent.com/15113219/128095319-89ca6924-d44a-402f-b21f-593c937bdc1f.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome Version 92.0.4515.107
- SR: NVDA 2021.1

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

Tested on mac, so verified the heading level of each one separately:
<img width="1435" alt="Screen Shot 2022-01-12 at 3 23 17 PM" src="https://user-images.githubusercontent.com/45409515/149220037-65e4ea91-aa89-464f-aa1c-649f0aeef546.png">
<img width="1439" alt="Screen Shot 2022-01-12 at 3 23 04 PM" src="https://user-images.githubusercontent.com/45409515/149220039-13b0f09d-446b-45b0-a27d-897d24f1ce83.png">
<img width="1435" alt="Screen Shot 2022-01-12 at 3 23 36 PM" src="https://user-images.githubusercontent.com/45409515/149220035-ab73aa48-21e3-407a-98d3-fb3485bfa896.png">

<img width="817" alt="Screen Shot 2022-01-12 at 3 23 55 PM" src="https://user-images.githubusercontent.com/45409515/149220032-6782fd4d-ff46-4997-9ebc-efeb52827e93.png">


![cartHeadingShoppingCart](https://user-images.githubusercontent.com/45409515/149220018-90ed6b6e-0c26-4b64-8ef6-4ab7ca2d37f5.png)
![cartHeadingCartNo](https://user-images.githubusercontent.com/45409515/149220024-28ef7796-ed63-4f1e-8d76-754d88b298ba.png)
![cartHeadingItem](https://user-images.githubusercontent.com/45409515/149220027-3dd7792c-f754-4c42-8300-8f9d08b403b6.png)
![cartHeadingOrderSummary](https://user-images.githubusercontent.com/45409515/149220028-5e9d1330-384c-4cf2-8c5d-10c2b0f56aff.png)
