### ISSUE TITLE
Checkout Pages Headings structure needs optimization

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13372]
**Describe the bug**
While using a Screen Reader and navigating page content using the Elements Dialog the headings' current structure doesn't provide a logical sequence, this is more noticeable on Screen Readers that will "nest" headings like NVDA (screenshots below).

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Add products to cart
2. Start checkout process
3. Open NVDA on Windows
4. Open Elements List (Ins+f7) and select "Headings"
5. See errors, as per screenshots below.

**Expected behavior**

- Remove "Order Summary" and "Cart Total" from the headings structure, make them a `<div>` to make the nesting look more logical.
- Notice there are also some title inconsistencies (e.g. Delivery Mode/Shipping Method) that need feedback from designers.

**Screenshots**

1. Shipping Address Page
<img width="960" alt="address nvda" src="https://user-images.githubusercontent.com/15113219/128098003-fe2fa5de-dff3-4640-83ca-77ea05d47921.png">

2. Shipping Method
<img width="960" alt="method nvda" src="https://user-images.githubusercontent.com/15113219/128098036-298d7cad-1a70-4ba9-a110-599bff43733c.png">

3. Payment Method
<img width="960" alt="payment nvda" src="https://user-images.githubusercontent.com/15113219/128098055-1447d138-bc69-44e6-a91d-bc1e86ef3437.png">

4. Review Order
<img width="960" alt="review nvda" src="https://user-images.githubusercontent.com/15113219/128098138-51ea685a-68dc-44c1-a2f5-97d345c7b8fe.png">

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser Chrome Version 92.0.4515.107
- SR: NVDA 2021.1

**Comment by saad-mo** [comment]
> Notice there are also some title inconsistencies (e.g. Delivery Mode/Shipping Method) that need feedback from designers.

this data is coming from the backend so it would take some effort to refactor. Maybe it can be tackled during checkout refactor/lib extraction.
