### ISSUE TITLE
Align logic to support ActiveCart/QuickOrder in the future

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13393]

**Comment by Platonn** [comment]
The `import-to-cart.service` now always uses the fresh created saved cart. But to be more generic, it should have a similar logic for recognizing the cart context (active vs. saved) like the `export-entries.service` already has.

Then based on the context, we should use either use:
- `activeCartService.requireLoadedCart()` (the method already exists) OR
- `savedCartService.create()` (the method needs to be implemented) - this method should create a fresh cart, then immediately mark it as a saved cart. It should return an Observable with the state of the cart. It would be good to prevent an emission of the state until the cart is succesfully marked as a saved cart.

btw. for consistency, it would be nice to rename `import-to-cart.service` to `import-entries.service` (similar to `export-entries.service`)

**Comment by Platonn** [comment]
Only now I can see that all the needed changes for generalizing the mechanism will be scoped inside a single service. So now I believe we'll be able do them without significant breaking changes in the future. I think we will need at most adding some optional argument `cartId` to the `loadProductsToCart` method; or add some feature level guard where needed.

Therefore I don't think we need any specific preparation work today. So marking it as stretch.
