### ISSUE TITLE
Move OrderOverviewComponent from shared to order folder

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13403]
`OrderOverviewComponent` is in `shared` folder. We will move it inside `order` folder first, then move it to `order` lib. And make `checkout` lib have cms mapping map from ConfirmationOrderOverview to OrderOverviewComponent.

**Comment by WeizhengSap** [comment]
Change the default cms mapping maybe bring breaking changes. If so, then this ticket can be done in 5.0.

**Comment by plabadie** [comment]
We already have this ticket for 5.0: GH-13324
Perhaps close this ticket if it becomes a duplicate of GH-13324
