### ISSUE TITLE
Remove aria-autocomplete from searchbox

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13432]
**Describe the bug**
- Automated test classifies this as a bug, see screenshot below.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**Expected behavior**

- Pass the automated test.
- Try with other autocomplete values (e.g. listbox). 
- Worst case: Instructions are provided with aria-live already so try removing the attribute and test cross-screen-readers to check if vocalization stays meaningful.

**Screenshots**
![Screen Shot 2021-08-05 at 12 27 11 PM](https://user-images.githubusercontent.com/15113219/128563823-4c686c1b-6b66-4b71-aec3-dbfffdb4c042.png)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

It's using the value "off".
![searchAutoComplete](https://user-images.githubusercontent.com/45409515/146030022-1b921f8d-d28f-45c9-b781-6c8b521d1401.png)
