### ISSUE TITLE
Order Confirmation has two H1

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13437]
**Describe the bug**
- Automated test detects heading jumping level.
- Order Confirmation has two H1, the second one being repetitive

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Go to any product and submit an order.
2. Order Confirmation page gets displayed.
3. Inspect headings as per screenshot.
2. See error

**Expected behavior**
- Second H1 shouldn't be heading.

**Screenshots**
![Screen Shot 2021-08-05 at 7 28 19 PM](https://user-images.githubusercontent.com/15113219/128568661-009221ac-35a8-44de-98ad-3a5ac07153c8.png)
![Screen Shot 2021-08-05 at 7 24 27 PM](https://user-images.githubusercontent.com/15113219/128568827-238faafc-a4e4-4f80-94f9-56d83b3bbec0.png)

**Comment by saad-mo** [comment]
Solution: change `h1` to `span` in `order-confirmation-thank-you-message.component.html`

small but breaking change

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

Only one H1 now. 
<img width="1153" alt="Screen Shot 2021-12-08 at 10 12 11 AM" src="https://user-images.githubusercontent.com/45409515/145235477-2dc61485-385f-498a-b925-2f6162819ab5.png">
<img width="1187" alt="Screen Shot 2021-12-08 at 10 12 34 AM" src="https://user-images.githubusercontent.com/45409515/145235492-99625078-26b2-4567-8d42-afd0c0a0050d.png">
