### ISSUE TITLE
H3 in Order Details page jumps heading levels

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13435]
**Describe the bug**
- Automated test detects heading jumping level.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Go to any product and submit an order.
2. Go to Order History and click on that order.
3. Order Details page is displayed.

**Expected behavior**

- This shouldn't be heading. Assign the same class as the other titles.

**Screenshots**
![Screen Shot 2021-08-05 at 7 41 27 PM](https://user-images.githubusercontent.com/15113219/128567517-32be5ef0-ebb0-4d44-8e2a-79b4fb880fa8.png)

**Comment by saad-mo** [comment]
change `h3` to `span` in `card.component.html`, which is shared across various components. 

breaking change

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

It's now a span

![orderDetails](https://user-images.githubusercontent.com/45409515/146260418-69cd61ed-76e2-4f5f-8fe0-ef6dbead51df.png)
