### ISSUE TITLE
Review ng-select labeling and attributes

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13433]
**Describe the bug**

- Automated testing not passing, although this gets vocalized by all Screen Readers.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**Expected behavior**
- Test should pass
- Alternative: Move the label to a closer level from the ng-select.

**Screenshots**
![Screen Shot 2021-08-05 at 6 02 17 PM](https://user-images.githubusercontent.com/15113219/128565751-ddb86242-409a-4e86-a692-d6e21a527390.png)
![Screen Shot 2021-08-05 at 6 01 30 PM](https://user-images.githubusercontent.com/15113219/128565754-1804506b-303f-47e7-bcdc-76dc420f44b7.png)
![Screen Shot 2021-08-05 at 6 00 54 PM](https://user-images.githubusercontent.com/15113219/128565755-4f4a6292-a96c-49b8-9fd9-c55ba0293ce6.png)
![Screen Shot 2021-08-05 at 7 33 10 PM](https://user-images.githubusercontent.com/15113219/128571567-799bbe16-212a-40eb-80e1-6146975508b9.png)

**Comment by RadhepS** [comment]
Will be resolved by tabbing changes
