### ISSUE TITLE
Latest version of @spartacus/cds missing

### ISSUE THREAD

**Issue by igorgiovannini** [SAP/spartacus#13442]
**Describe the bug**
When a new Spartacus project is generated (or, better, the core libraries/features are added to an Angular project), with the latest version (``ng add @spartacus/schematics@latest``), an error occurs because it can't find the latest version ``4.0.0`` for the package ``@spartacus/cds`` (in fact it is not published on npmjs.org)

**Tell us the version of Spartacus**
- Library version: latest

**To Reproduce**
1. Generate a new Angular project
2. Run the command to add the core libraries/features
3. Choose all the features (at least the ones regarding _context-driven services_)
4. @spartacus/cds@4.0.0 is missing, therefore it throws the error

**Expected behavior**
It should add Spartacus as expected

**Comment by Xymmer** [comment]
known issue, CDS should be released soon
