### ISSUE TITLE
Demo site not working 

### ISSUE THREAD

**Issue by RaphiStein** [SAP/spartacus#13454]
The URL for the demo app (as per the README) is broken
https://spartacus-demo.eastus.cloudapp.azure.com/

There is an error in the console:

`main.7b35f6b0de1e900c9e5f.js:1 ERROR Error: Error: Cannot get base site config! Current url (https://spartacus-demo.eastus.cloudapp.azure.com/) doesn't match any of url patterns of any base sites.`

**To Reproduce**

Visit the URL

**Expected behavior**

Store works

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser Chrome
 - Version 92

**Comment by andreas-becker** [comment]
You're missing the base site config. When added it is working: https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/

**Comment by RaphiStein** [comment]
Oh. I simply clicked the link in the README
`Try out a sample Spartacus storefront on our public demo site`
