### ISSUE TITLE
Verify if Import/export sample-data are properly merged

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#13452]
Checks:
- [x] Should both to be merged in `release/2005/next` and `release/2011/next`?
- [x] Check if sample-data works for: electronics, powertools, apparel-uk

**Comment by Pucek9** [comment]
https://github.tools.sap/cx-commerce/spartacussampledata/pull/194/files
https://github.tools.sap/cx-commerce/spartacussampledata/pull/195/files

**Comment by Matejk00** [comment]
Waiting for the update from #13713
