### ISSUE TITLE
H3 in PDP's Tab group panel jumps heading levels

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13484]
**Describe the bug**

- Automated test detects heading jumping level.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Go to any Product Detail Page
2. Click on the "Spec" Tab
3. Scroll down to a Section heading
4. See error.

**Expected behavior**

- Change to H2

**Screenshots**
![Screen Shot 2021-08-05 at 6 40 38 PM](https://user-images.githubusercontent.com/15113219/129807304-e30e0682-9b8f-45cd-9c97-cc2db8e2e517.png)

**Comment by saad-mo** [comment]
Solution: change `h3` to `h2` in `product-attributes.component.html`. Simple but breaking change.

**Comment by dydome** [comment]
migration doc required

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

It's now H2 now. 
<img width="1383" alt="Screen Shot 2021-12-16 at 11 26 16 AM" src="https://user-images.githubusercontent.com/45409515/146410637-a2ec7181-33cb-4134-ad2c-5fa096bc6ca1.png">
