### ISSUE TITLE
Unable to Checkout (SopMock) After Re-login During Checkout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#13489]
**Steps to Reproduce:** 
1. Navigate to Spartacus storefront 4.0
2. Create a new user John.Doe
3. Login.
4. Add items to cart and proceed to checkout. 
5. Add a new shipping address and click next. 
6. Logout.
7. Wait 30 seconds. 
8. Re-login John.Doe
9. Restart checkout process again. 
10. At Shipping address,  select the shipping address previously entered. 
11. Select shipping method. 
12. Enter credit card details. 
13. Attempt to move on to review page. 

**Expected Results:** 
13. Review page is displayed. 

**Actual Results:** 
13. SopMock request is rejected. Billing province/state is undefined.

**Comment by giancorderoortiz** [comment]
Related to: 
https://github.com/SAP/spartacus/issues/3693
https://github.com/SAP/spartacus/issues/3323
https://github.com/SAP/spartacus/issues/3687
https://github.com/SAP/spartacus/issues/3172

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-08-18 at 11 29 11 AM](https://user-images.githubusercontent.com/46171897/129936292-b4f310d6-c470-40bf-8832-891fd5dc4de2.png)
![Screen Shot 2021-08-18 at 11 31 07 AM](https://user-images.githubusercontent.com/46171897/129936299-83986f3b-b8ab-4ce4-ba3d-5b8252670988.png)
![Screen Shot 2021-08-18 at 11 49 14 AM](https://user-images.githubusercontent.com/46171897/129936301-ccafeefd-5586-4530-a99a-3cbd152655af.png)
![Screen Shot 2021-08-18 at 11 50 07 AM](https://user-images.githubusercontent.com/46171897/129936304-83bb9b36-97a6-42bd-ab0c-8b9162ebcd8e.png)
![Screen Shot 2021-08-18 at 11 50 21 AM](https://user-images.githubusercontent.com/46171897/129936307-4195f832-eaca-4b2c-803b-3ed3d8db33f3.png)

**Comment by giancorderoortiz** [comment]
![backend_2005_no_region](https://user-images.githubusercontent.com/46171897/129936601-cfd16f9c-d5f9-4aa9-8dda-ee343dbcb3a8.png)

**Comment by giancorderoortiz** [comment]
sopmock post call body: 

"recurringSubscriptionInfo_automaticRenew=false&billTo_lastName=customer&billTo_street2=US-CA&ccAuthReply_cvCode=M&billTo_street1=1111%20S%20Figueroa%20St%20US-CA&shipTo_state=CA&shipTo_shippingMethod=standard-net&orderPage_declineResponseURL=sampleUrl&recurringSubscriptionInfo_startDate=20210818&recurringSubscriptionInfo_frequency=on-demand&shipTo_postalCode=90015&orderPage_signaturePublic=R5EptKgJz7JCYRqFXd%2BqicrQlIk%3D&shipTo_country=US&card_accountNumber=************1111&orderPage_serialNumber=your_serial_number&recurringSubscriptionInfo_signaturePublic=p6vGEksY6%2F5Ktj2OO1CtsRCv7vo%3D&card_nameOnCard=Cypress%20customer&shipTo_phoneNumber=555%20555%20555&orderPage_ignoreCVN=true&card_expirationMonth=12&orderPage_cancelResponseURL=sampleUrl&orderPage_ignoreAVS=true&billTo_city=Los%20Angeles&billTo_email=cypress_user_2pvmfivpj_93763769658%40sapcx.com&shipTo_lastName=customer&decision_publicSignature=mEhlMRLCsuPimhp50ElrY94zFyc%3D&billTo_country=US&orderPage_transactionType=subscription&orderPage_merchantURLPostAddress=https%3A%2F%2Flocalhost%3A9002%2Focc%2Fv2%2Felectronics-spa%2Fintegration%2Fmerchant_callback&card_cardType=visa&shipTo_city=Los%20Angeles&shipTo_street1=1111%20S%20Figueroa%20St&shipTo_street2=US-CA&currency=USD&reasonCode=100&paySubscriptionCreateReply_subscriptionID=2a759f08-e64f-43cd-a3fd-697e4a927563&amount=0&decision=ACCEPT&recurringSubscriptionInfo_numberOfPayments=0&shipTo_firstName=Cypress&orderPage_colorScheme=blue&orderPage_receiptResponseURL=sampleUrl&billTo_postalCode=90015&orderPage_version=7&billTo_firstName=Cypress&billTo_state=undefined&orderPage_timestamp=1629299312486&recurringSubscriptionInfo_amount=0&merchantID=your_merchant_id&card_expirationYear=2025&billTo_phoneNumber=555%20555%20555&paySubscriptionCreateReply_subscriptionIDPublicSignature=zLpfe4xFEKz5hEqalYeBptNXw0g%3D&defaultPayment=true&savePaymentInfo=tr"

notice billTo_state=undefined

**Comment by giancorderoortiz** [comment]
@KateChuen fyi

**Comment by Xymmer** [comment]
Also test same scenario but with logout after payment is created, and see if it still happens

**Comment by Xymmer** [comment]
related to old bug where billto state wasn't added (even if null) to the request

**Comment by dydome** [comment]
I have tested it using a scenario from the description and had no problems with placing the order. Using latest develop.

**Comment by psmul** [comment]
I wasn't able to reproduce this problem based on the current develop branch.

**Comment by mszczepaniak** [comment]
Unfortunately I was not able to reproduce this issue as well.

**Comment by giancorderoortiz** [comment]
@dydome, @psmul, @mszczepaniak  please share a screen video recording of your attempt to reproduce this bug.

**Comment by dydome** [comment]
I found what is the problem but was not able to recognize why...?

The problem is with `OccCheckoutPaymentAdapter` in the line 221:
`if (paymentDetails.billingAddress?.region) {
      params[mappingLabels['hybris_billTo_region']] =
        paymentDetails.billingAddress.region.isocodeShort;
    } else {
      params[mappingLabels['hybris_billTo_region']] = '';
    }`

`isocodeShort` sometimes is undefined which is causing issues and 400 status from BE.

The problem is that in `paymentDetails` sometimes we are getting full region object but sometimes only isoCode which is not enough. We can do a hack and use `billTo_state` value from `parameters` but it is not the proper way.

**Comment by WeizhengSap** [comment]
This issue is caused by the codes inside `CheckoutDetailsService`'s constructor:
```
this.cartId$ = this.activeCartFacade.getActive().pipe(
      map((cartData) => {
        const cartUser = cartData.user;
        if (
          cartUser &&
          (cartUser.uid === OCC_USER_ID_ANONYMOUS ||
            cartUser.uid === OCC_USER_ID_GUEST ||
            !!cartUser.uid?.split('|').slice(1).join('|').match(EMAIL_PATTERN))
        ) {
          return cartData.guid as string;
        }
        return cartData.code as string;
      }),
      filter((cartId) => !!cartId)
    );

    this.getCheckoutDetailsLoaded$ = this.cartId$.pipe(
      distinctUntilChanged(),
      tap((cartId) => this.checkoutFacade.loadCheckoutDetails(cartId)),
      shareReplay(1),
      switchMap(() => this.checkoutFacade.getCheckoutDetailsLoaded()),
      skipWhile((loaded) => !loaded)
    );
```
When user logout, then re-login, the `cartId` is the same which will not trigger this `tap((cartId) => this.checkoutFacade.loadCheckoutDetails(cartId))` (because of `distinctUntilChanged()`). To fix it, we can do this:
```
this.cartId$ = this.activeCartFacade.getActive().pipe(
      map((cartData) => {
        const cartUser = cartData.user;
        if (
          cartUser &&
          (cartUser.uid === OCC_USER_ID_ANONYMOUS ||
            cartUser.uid === OCC_USER_ID_GUEST ||
            !!cartUser.uid?.split('|').slice(1).join('|').match(EMAIL_PATTERN))
        ) {
          return cartData.guid as string;
        }
        return cartData.code as string;
      })
    );

    this.getCheckoutDetailsLoaded$ = this.cartId$.pipe(
      distinctUntilChanged(),
      tap((cartId) => {
        if (cartId) {
          this.checkoutFacade.loadCheckoutDetails(cartId);
        }
      }),
      shareReplay(1),
      switchMap(() => this.checkoutFacade.getCheckoutDetailsLoaded()),
      skipWhile((loaded) => !loaded)
    );
```
So, when user logout, `cartId` becomes `undefined`. When user re-login, and `cartId` has some value, this `this.checkoutFacade.loadCheckoutDetails(cartId);` will be called.

**Comment by dydome** [comment]
@WeizhengSap I have prepared PR to fix this -> https://github.com/SAP/spartacus/pull/14052 may you please take a look? @giancorderoortiz are you also able to test it locally?

There is one change It was not working for me with `distinctUntilChanged` I have to remove it. Without removing the problem still persist.

**Comment by Xymmer** [comment]
possible to backport to latest 3.x minor as well?

**Comment by giancorderoortiz** [comment]
fixed! finally. thanks.
