### ISSUE TITLE
Can't create new spartacus 4 app by using @spartacus/schematics

### ISSUE THREAD

**Issue by danielmeurer88** [SAP/spartacus#13482]
**Describe the bug**
I want to create a new Spartacus 4 Storefront from a clean Angular app by following these instructions:
https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries-4-x/

After "ng add @spartacus/schematics@latest", the Angular-CLI installs the schematics but fails with an error: See Screenshot:

Apparently the schematics expects @spartacus/cds in version 4.0.0 but this does not exists.

_EDIT: Could it be that @spartacus/cds@4.0.0 was falsly releasef as 3.4.2? I installed 3.4.2 at my Spartacus 3.4 storefront and threw a lot of errors, saying these errors could be Ivy releated and when I specifically installed version 3.4.1 again then it worked._

node: 12.16.1
npm: 6.13.1
@angular-devkit/schematics: 12.2.1

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
Follow:
https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries-4-x/

**Expected behavior**
A spartacus application that is ready to be used.

**Screenshots**
![spa-bug](https://user-images.githubusercontent.com/21308421/129746151-79e01cea-3fe0-4fae-900b-6dfbae078e1c.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Xymmer** [comment]
Hi! Known issue as CDS is not yet released for 4.0. The CDS library will be released soon.
To get your app to work, when installing with schematics, do not select CDS (Context-Driven Services).
