### ISSUE TITLE
H4 in Cart Page page jumps heading levels

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13483]
**Describe the bug**

- Automated test detects heading jumping level.
- Heading is not meaningful 

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Add items to cart'
2. Click on the Cart button
3. Land on Cart Page.

**Expected behavior**
This should not be a heading. Set as a styled <div> instead.

**Screenshots**
![Screen Shot 2021-08-05 at 6 19 53 PM](https://user-images.githubusercontent.com/15113219/129805942-ff754b7f-02f4-4c03-bf56-a712e03e5ac3.png)

**Comment by saad-mo** [comment]
Solution: change `h4` to `span` in `cart-details.component.html`. small but breaking change.

**Comment by dydome** [comment]
Hi @saad-mo  @developpeurweb, your solution is breaking another fix -> https://github.com/SAP/spartacus/pull/14328 what you think, something change once we fix headings in that PR?

**Comment by saad-mo** [comment]
@dydome it looks like the other PR (#14328) is now merged. is this still an issue?

**Comment by developpeurweb** [comment]
Seems this is no longer an issue.

![2022-01-25_11-00-12](https://user-images.githubusercontent.com/15113219/151012720-d1860ae7-02fb-45dd-9437-6a4245bf021e.jpg)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

It's now a h2. 
<img width="1399" alt="Screen Shot 2022-04-06 at 2 48 17 PM" src="https://user-images.githubusercontent.com/45409515/162058845-05b2feb1-08a9-4759-ac30-1139c938a8a9.png">

<img width="1129" alt="Screen Shot 2022-04-06 at 3 48 10 PM" src="https://user-images.githubusercontent.com/45409515/162058870-5b1ba60c-de72-4e3c-9bb4-215ed0cfd28c.png">

<img width="787" alt="Screen Shot 2022-04-06 at 2 46 47 PM" src="https://user-images.githubusercontent.com/45409515/162058849-7497c4a8-a2e0-4ab7-98c5-a2f35886dd72.png">
