### ISSUE TITLE
Don't find service in the specified "import" path 

### ISSUE THREAD

**Issue by andreafg12** [SAP/spartacus#13495]
I try to import the "UrlParsingService" in my customized service but the path shows "@spartacus/core/src/routing/configurable-routes/url-translation/url-parsing.service"; and the console shows "Module not found: Error: Can't resolve '@spartacus/core/src/routing/configurable-routes/url-translation/url-parsing.service' in 'xxx/protected-routes'

<img width="1642" alt="Screen Shot 2021-08-18 at 2 28 21 PM" src="https://user-images.githubusercontent.com/40365471/129960602-27b687da-e7f6-4473-b2b9-14eea27188d7.png">

**Desktop
 - OS: [MacOs]
 - Browser [chrome]
 - Version [22]

**Comment by Xymmer** [comment]
Hi! not a bug, we think. Looks like incorrect import.
On our side we will check if it should be part of public api, if so, we'll export it.
