### ISSUE TITLE
SSR flickering in ng12 due to inlineCriticalCss

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#13512]
# Intro

Angular introduced something called "inline critical css" - https://angular.io/guide/workspace-config#styles-optimization-options in ng11 (source https://github.com/SAP/spartacus/issues/13512). It extracts and inlines the critical CSS definitions which improves [FCP](https://web.dev/first-contentful-paint/). This is now enabled by default starting from ng12. 

## Problem

While this is great and welcomed improvement, it appears some CSS is missing in our case, which causes the SSR to flicker and jump around after the full styles are loaded.

We proved this is the cause by disabling it for SSR in `projects/storefrontapp/server.ts`:
```ts
  server.engine(
    'html',
    ngExpressEngine({
      bootstrap: AppServerModule,
      // disable for SSR
      inlineCriticalCss: false,
    })
  );
```

## Reproduction

To repro this, you have to run SSR in prod mode:
- `yarn build:libs && yarn build`
- `yarn build:ssr`
- start the `yarn serve:ssr:dev` because of the invalid certificate.
- Open Spartacus and refresh a couple of times - you should notice the flickering with the large SAP logo.

## Goal

It [appears](https://github.com/angular/angular-cli/issues/20864#issuecomment-844927739) Angular uses [Critters](https://github.com/GoogleChromeLabs/critters/) for this.

One hint why this might be happening are the errors we see in the console when running SSR:

```text
Unable to locate stylesheet: /Users/nikolazaric/dev/spartacus/ssr-inline-css-on-prod/dist/storefrontapp/https:/use.fontawesome.com/releases/v5.8.1/css/all.css
1 rules skipped due to selector errors:
  .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang
1 rules skipped due to selector errors:
  .custom-file-input:lang(en)~.custom-file-label -> unmatched pseudo-class :lang
```

The errors is coming from [here](https://github.com/GoogleChromeLabs/critters/blob/main/packages/critters/src/index.js#L522).
The style in question can be found in the built `stlyes.scss` and seen in the browser:

```scss
.custom-file-input:lang(en) ~ .custom-file-label::after {
  content: "Browse";
}
```

It appears the source of this style might be [bootstrap](https://github.com/twbs/bootstrap/issues/29650). Let's first try to fix these and see if the flickering goes away.

Other reason why this is happening because our app is dynamic, and it first needs to resolve the CMS before it starts to render components / CSS.

In this issue, we would like to learn why does it happen for Spartacus?
How can we fix it? 
Can we make it wait a bit longer before resolving the critical CSS?

### Tools

One nice way to detect the unused CSS is described here: https://web.dev/defer-non-critical-css/
We can use it on our _non-inlined_ version of app (with the optmization turned off) and compare it with the CSS we actually inline with the optmization turned on.

**Comment by i507132** [comment]
The same issue happened for us on SSR and we needed to updated both server.ts and also angular.json by adding this property under production.configurations:
```
"optimization": {
    "styles": {
        "inlineCritical": false
    }
}
```

**Comment by znikola** [comment]
Seems to be fixed in the lastest Spartacus just by upgrading to angular 14, closing.
