### ISSUE TITLE
Text is not selectable on Saved Cart dialogs

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13510]
Please see similar ticket & solution https://github.com/SAP/spartacus/issues/13400

```ts
      pointer-events: none;

      button,
      input,
      textarea {
        pointer-events: auto;
      }
```

**Comment by dydome** [comment]
This issue exists because of the cxFocus directive which has event listeners for each click and focus by default first child, that is why cursor select is not working.

**Comment by Dalvir-Personal** [comment]
@Pucek9 We could not reproduce the issue. Please confirm that the issue still exists

**Comment by Dalvir-Personal** [comment]
@Pucek9 We could not reproduce the issue. Please confirm that the issue still exists

**Comment by Xymmer** [comment]
https://jira.tools.sap/browse/CXSPA-269
