### ISSUE TITLE
Remove aria-controls attribute from password link

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13521]
**Describe the bug**
- Automated test detects incorrect use of aria attribute

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**Expected behavior**

- Pass automated test.
- Remove aria-controls attribute from password link

**Screenshots**
![Screen Shot 2021-08-05 at 6 50 13 PM](https://user-images.githubusercontent.com/15113219/130296072-75ced947-0079-4d6d-adbd-4008a170c6a1.png)

**Comment by saad-mo** [comment]
Remove aria-controls attribute from password link does not break anything

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.
![forgotPwd](https://user-images.githubusercontent.com/45409515/146027962-807ac9cd-886c-428b-b68d-b9550726fb76.png)
