### ISSUE TITLE
Remove redundant roles and attributes from Main Navigation

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13522]
**Describe the bug**

- When native links are used `<a href="">`, there is no need to add the `role="link"`.
- `aria-label` attributes will override screen reader narration of text content, this attribute is not needed on the Main Menu nodes as it could potentially alter customizations and it already has text content.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**Expected behavior**

- Remove `role="link"` from all native links having an href `<a href="">`.
- Remove `aria-label` attributes from Main Menu nodes that already have text. 

**Screenshots**
![Screen Shot 2021-08-16 at 9 17 26 AM](https://user-images.githubusercontent.com/15113219/130298361-432bdc88-c03b-4f18-abda-e2ddcda7c5d5.png)
![Screen Shot 2021-08-20 at 6 10 06 PM](https://user-images.githubusercontent.com/15113219/130298368-27ebf9de-9455-43a8-831d-41ecc9c03d7b.png)

**Additional context**

- `role="link"` can be used when a link is not created using native markup and activated with JS, e.g. `<span tabindex="0" role="link"> Fake accessible link </span>`
- The `aria-label` text is invisible and only available to assistive technology and replaces an element's original text, ideally, we use it to label icons, landmarks and form elements.

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

They have been removed from main nav. 

<img width="1440" alt="Screen Shot 2022-01-11 at 12 01 53 PM" src="https://user-images.githubusercontent.com/45409515/149001212-ae6bcbcd-a86d-493e-8d10-37dd629728c8.png">
<img width="1433" alt="Screen Shot 2022-01-11 at 12 01 33 PM" src="https://user-images.githubusercontent.com/45409515/149001215-4c621aed-07a6-403c-a093-cfb2b82936d9.png">
