### ISSUE TITLE
Page title for checkout doesn't change along with checkout steps

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13539]
**Describe the bug**

- Page title stays short and generic throughout the checkout process.
- Automated test detects this

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Add product to cart
2. Start the checkout process
3. Notice the page title not changing along with checkout steps.

**Expected behavior**
- Page title for each step is meaningful. E.g. Checkout: Choose a payment method

**Screenshots**
![Screen Shot 2021-08-05 at 7 13 31 PM](https://user-images.githubusercontent.com/15113219/130532270-9837c4c3-65ce-44c8-8784-7fea893a9cea.png)

**Comment by saad-mo** [comment]
`pageMetaResolver` in `common.ts` only has one generic title for checkout. This need to be expanded to cover all checkout steps

**Comment by saad-mo** [comment]
@developpeurweb The title of the page and page heading (h1 tag) are currently coupled together. Updating the page title for checkout will also update the page title. I am assuming this won't be an issue? 

<img width="1491" alt="Screen Shot 2021-10-28 at 2 11 53 PM" src="https://user-images.githubusercontent.com/15215400/139320615-b6c45f90-a6f9-4e4f-8480-ad639b44db74.png">

also, it would be helpful if you can validate the titles below for each checkout step

- Checkout: Enter the Shipping Address
- Checkout: Choose a Delivery Mode 
- Checkout: Choose a Payment Method
- Checkout: Review Order Details

**Comment by developpeurweb** [comment]
@saad-mo  Accessibility-wise this is NOT an issue but in fact good practice. However, let's notify designers @Manurod2018 and @vekterdude about this change, as this may have an impact on wires/visuals. Also, in case they want to adjust presentation (size, capitalization, separators, etc.). I have also seen this kind of arrangement using dashes and vertical bars.
- Checkout - Enter the Shipping Address
- Checkout | Enter the Shipping Address

**Comment by Manurod2018** [comment]
If it's not an accessibility issue, I am not sure to understand why we are repeating the name of the steps? It is unnecessary and isn't part of any convention.
FYI, for the Santorini theme, we also have Checkout as Heading level 1 and the step title as Heading level 2. This approach follows the standards of each e-commerce site.

![D - B2B - Checkout – Promotions – 1](https://user-images.githubusercontent.com/37299626/140996672-0a789752-3c4d-4e09-9587-8e14d8521dcc.png)
![D - B2B - Checkout – Promotions](https://user-images.githubusercontent.com/37299626/140996676-a706ac2b-e2fc-425d-9864-932cc1d10c19.png)

**Comment by developpeurweb** [comment]
- @Manurod2018 then it seems more like a logic/typescript issue where we will struggle to match mockups since, as @saad-mo mentioned, page title and H1 are currently coupled together. 
- The issue was detected by an automated test, as you can see in the first screenshot, so it's a must-have for the page title. Otherwise, Screen Readers will always vocalize landing on _"Checkout"_ page for all 4 steps.
- The **absence** of context IS an issue for Accessibility. As Saad mentioned, if we provide the context in the heading, then it wouldn't be an issue for Accessibility (but a design issue, I deduce from your comment). To have the page title and the H1 being the same or at least part of it, is in fact a [common and good accessibility practice](https://fae.disability.illinois.edu/rulesets/TITLE_2/). This way the Screen Reader will vocalize every step with context, and also the automated test will pass.
- If still not clear let's sync up with a quick call.

**Comment by Manurod2018** [comment]
I had a talk with Miguel last week, he explained why we had to go with this temporary solution for now: In SPA the title of the page and page heading are currently coupled together, it is at the moment a technical limitation that will have to be fixed later.

**Comment by bgambocjaviniar** [comment]
Provided the solution to Benjamin, but we really never had coupling with the browser title and breadcrumb title. 

For more information on the solution regarding this issue:
- use resolveHeading() to change the breadcrumb title. Basically, we'll keep it as 'Checkout'
- use resolveTitle() to change the browser / dom / seo title. It will be Checkout Shipping Address, Checkout Delivery Mode, etc depending on which step we're in. 

Conclusion: 
breadcrumb title will be: 'Checkout'
actual page title will be: 'Checkout The Step Name'

**Comment by bgambocjaviniar** [comment]
Only possible to test after checkout merge to develop, which is soon

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

Breadcrumb title "Checkout"
Page title "checkout step"
![checkoutShippingStep](https://user-images.githubusercontent.com/45409515/155017198-3e33005c-e64d-4335-a61f-c3ab390b5e23.png)
![checkoutDeliveryStep](https://user-images.githubusercontent.com/45409515/155017203-b18ebef3-1208-4a9e-9785-577a3e2868ad.png)
![checkoutPaymentStep](https://user-images.githubusercontent.com/45409515/155017204-69198afe-e28a-4277-9ad4-ded5158751b1.png)
![checkoutReviewStep](https://user-images.githubusercontent.com/45409515/155017210-a535cfe3-aa27-4138-8c5d-ffc195a6d75f.png)
