### ISSUE TITLE
keep the products zoomed after selecting the currency in OS

### ISSUE THREAD

**Issue by herdaram85** [SAP/spartacus#13538]
**Describe the bug**
keep the products zoomed after selecting the currency in OS

**Tell us the version of Spartacus**
- Library version: 3.3.0
The test was realized in iPhone 12, 11, 8  

**To Reproduce**
1. Go to 'Menu' 
2. Click on 'currency' then choose an option on select component
3. After that going to the product and there are zoomed
4. See an error

**Expected behavior**
The product should continue normal not zoomed

**Screenshots**

Product before the process
![image](https://user-images.githubusercontent.com/78229003/130511921-343c4c41-4b6e-432a-8674-30e5265c6dfd.png)

![image](https://user-images.githubusercontent.com/78229003/130511359-8132ddd1-630e-4bfe-8af6-07c951c6e486.png)

![image](https://user-images.githubusercontent.com/78229003/130511573-8ab033a4-db58-4317-a03e-e8cb8061bd5c.png)

Product after select currency
![image](https://user-images.githubusercontent.com/78229003/130512106-a4c9e944-a5d2-4302-9ebb-3805137d9900.png)

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone12]

**Additional context**

**Comment by Xymmer** [comment]
Currency/language change is normal navigation and currently we don't do anything special here. Let's try to repro and see what's happening especially since we are adding image zoom in 4.x; however if there is no simple solution, close as won't fix as a fresh 'reset' is acceptable
