### ISSUE TITLE
Storage item removal with EntityLoaderResetAction

### ISSUE THREAD

**Issue by 18928172992817182** [SAP/spartacus#13544]
**Describe the bug**
When using the StatePeristenceService with syncWithStorage and EntityLoader state, the value data will be put in either the local or session storage. The data value is updated with the loading, success and failure EntityLoader actions. However if I send an EntityLoaderResetAction, this stored state is never cleared. Because that reset action sets the value to undefined. Undefined supplied to the function persistToStorage in browser-storage.ts is just ignored. Hence the key and data always survives when synced to storage but not in the store. The only way to remove the stored state is to supply an empty object which is naturally truthy but that is very inconvenient.

**To Reproduce**
1. Create some state in your store that is backed by the Entity load action system from Spartacus
2. Add syncWithStorage to that value state
3. Populate with some data
4. Send an EntityLoaderResetAction
5. The store clears fine but the storage remains populated with the old 'value' data passed on the previous actions despite the reset

**Expected behavior**
I expect that when an EntityLoaderResetAction is triggering a context change with undefined in syncWithStorage that the removeItem function is called for that key to clear/reset the storage so that it is equal to the store state.

**This is my local code fix**

```
export function persistToStorage(configKey: string, value: any, storage: Storage): void {
  if (!isSsr(storage)) {
    if (value) {
      storage.setItem(configKey, JSON.stringify(value));
    } else {
      storage.removeItem(configKey);
    }
  }
}
```

Very simple. The removal in the else case does nothing in case the key does not exist. With this the synced storage is always the same as the store when adding syncWithStorage on a state that can truly be undefined. Keys are actually removed from storage when supplied with undefined/falsy.

**Comment by Xymmer** [comment]
@18928172992817182 thanks for the fix!  This mechanism (persistToStorage) was removed in 4.0 so your fix applies to version previous to that. In 4.0 and later, we have a different mechanism, state persistance service, new approach is not affected by this problem.  Please let me know if you require a backport of this fix or if the workaround you provided is sufficient.

**Comment by Xymmer** [comment]
Let's review the fix supplied and consider backporting

**Comment by 18928172992817182** [comment]
I am confused. It is right here in the develop branch: https://github.com/SAP/spartacus/blob/develop/projects/core/src/state/services/state-persistence.service.ts

 in syncWithStorage, that I thought was the new way to handle this:
 
 ```
 subscriptions.add(
      state$.pipe(withLatestFrom(context$)).subscribe(([state, context]) => {
        persistToStorage(
          this.generateKeyWithContext(context, key),
          state,
          storage
        );
      })
    );
```

I am sorry if I am confused. Is that the deprecated part?
