### ISSUE TITLE
When the user changes the page this doesn't trigger Screen Reader narration

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13556]
**Describe the bug**

- When the user changes the page this doesn't trigger Screen Reader narration, detailing **where the user has landed** and elements on the new page.
- Basically, the focus stays trapped on the last read element of the previous page and there's silence as the user lands on a new page.
- Most Screen Readers start "read mode" on landing, this doesn't happen because the focus is trapped.

**Tell us the version of Spartacus**
- Library version: 4.0.0

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS)
2. Tab to Film Cameras Menu option, press Enter to follow the link.
3. Notice how even if the user has changed to a new page (Category Listings) the focus remains on the navigation link.
4. In other cases, it seems the focus moves automatically to the <main> area, instead of having their <title> read on landing.

**Pages having this issue (non-exhaustive list):**

- Homepage
- Category Listings
- Product Details Page
- Order Confirmation
- Order History
- Order Details
- Cancel Items
- Cancel Order
- Cancel Order Confirmation
- My Account > All pages

**Expected behavior**
- When landing on a Spartacus page, the page title gets narrated by the Screen Reader.

**Screenshots**
![2021-08-25_20-16-51](https://user-images.githubusercontent.com/15113219/130881048-a259e4a1-ad14-4ce5-8f1c-26bbd8a59d11.jpg)

**Comment by saad-mo** [comment]
@Zeyber any idea who to fix this? can set keyboard focus on page title when the view changes?

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn:
2 Pages where I found it doesn't narrate are: @developpeurweb can you confirm please?
- Login page
- Homepage 

These pages were ok:
- Register Page
- Product listing page 
- Product Details Page
- Cart page
- Checkout page
- Order Confirmation Page
- Order History Page
- Order Details Page
- Cancel Order Page
- Cancel Order Confirmation Page
- Return Order Page
- Return Order Confirmation Page
- Return Order Details Page
- Wishlist page
- Saved carts page
- Quick Order page
- Find a store page
- Contact Us page
- Help Page
- My Account pages (Address Book, Payment Details, Personal Details, Update Password, Email Address)
- Consent Management Page
- My Interests Page
- Notification Preference Page
- My Coupons page
- Close Account Page

**Comment by developpeurweb** [comment]
@KateChuen 
- Login page narrates well for me on JAWS/NVDA/VO.
- Homepage only narrates on JAWS.

JAWS is the priority, so this is OK for now. I'll create a new ticket for the homepage cross-sr issue.
Thanks!
