### ISSUE TITLE
How to add Bootstrap theme color variant? 

### ISSUE THREAD

**Issue by aholmesdd** [SAP/spartacus#13564]
Make theme-colors "!default" to allow for overriding?

I am able to override the theme variables, however, I am not able to add theme colors or override the theme colors. If there is no simple way of doing this already, would it be possible to make the theme-colors variable "!default" making it easier to override?

https://github.com/SAP/spartacus/blob/256c032dc902348e15b1d346ddfdb4c462a5923c/projects/storefrontstyles/scss/theme/sparta/_variables.scss#L48

**Comment by developpeurweb** [comment]
The ideal place to override styles on the customer's end is the `storefrontapp/src/style.scss` file using **css variables**, there you can code styles directly or import styles into this file.
E.g.

![Screen Shot 2021-06-30 at 6 30 02 PM](https://user-images.githubusercontent.com/15113219/131895052-554997ea-dcf3-4a93-abc2-41b76eaa5132.png)



**Please note:** The `storefrontstyles/scss/theme/sparta/_variables.scss` file is not meant for customizations, it's just the starting point (at the core) to compile and process all needed variables.
