### ISSUE TITLE
Quick order: Some questions about the behavior

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13568]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps**
Have 2 items in the quick order list
Try to add > than stock, so for eg, for product 3881022, add qty 60. And for product 3592865, add qty 120
You'll see that the qty has been updated to 56 and 115 respectively.
Click Add to cart.

**Actual Result**
You get an error message "Error proceeding to cart" saying the quantity was reduced. 
![Screen Shot 2021-08-30 at 1 27 56 PM](https://user-images.githubusercontent.com/45409515/131380085-5a7407d8-07fe-48c6-9e49-f5556ea92291.png)

**Expected Result**
Perhaps, it should be more of an information message than error message? Because the items were added in cart.

**Comment by Xymmer** [comment]
agree, info message is better. Error message is for more serious things, this is just a warning.

**Comment by dydome** [comment]
As I understand you both @KateChuen and @Xymmer you want to split errors and warnings into two message blocks? Split items that were out of stock and items that were reduced? I spoke about current implementation with UI and they agree to do it this way. What I think you want to see is something like this (I did it with dev inspector):
![image](https://user-images.githubusercontent.com/18736434/132201703-224aaa34-4eb7-46b3-a21e-15494930358b.png)

This improvement will require rebuilding few things and it is not a "quick win" change. @Xymmer should we discuss it once again with UI guys?
