### ISSUE TITLE
Default Google Font API optimization required by Spartacus OOTB! 

### ISSUE THREAD

**Issue by srikanta72** [SAP/spartacus#13563]
The default GAPI Font used by Spartacus to need to have a property `&display=swap` at the end to resolve page speed score issue.

Page speed issue shows issue : 
![Gfont_spartacus OOTB issue](https://user-images.githubusercontent.com/25590140/131148122-ab23d6a7-cda2-45dc-a201-1fc7825b4959.png)

As per:  https://web.dev/font-display/?utm_source=lighthouse&utm_medium=unknown#google-fonts
Recommended Fix : <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap" rel="stylesheet">

Issue at OOTB level : 
file : node_modules\@spartacus\styles\scss\_fonts.scss
line : @import url('https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700'); << it do not have swap option

Kindly let us know if this can be overridden easily to not to appear in page speed. 

Project reference hierarchy to track the issue >> src\styles.scss>>node_modules\@spartacus\styles\_index.scss>>node_modules\@spartacus\styles\scss\app.scss>>node_modules\@spartacus\styles\scss\_fonts.scss>>node_modules\@spartacus\styles\scss\theme\sparta\_fonts.scss

**Comment by Zeyber** [comment]
`$font-url` has been exposed with default value `https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700` but can now be overridden with `https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700&display=swap` to achieve this in versions`>= 4.1`. The default url will be set with the swap value in `5.0`.
