### ISSUE TITLE
Verify is defaultGlobalMessageConfigFactory still needed

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13571]
We were forced to using the factory for configuration with TS dynamic keys, but probably in new Angular, it should work for standard configuration too.
- [x] verify is it possible to use `provideDefaultConfig` for this case
if it works:
- [x] replace factory by standard config for global messages
- [x] update docs for global messages

@Optional()
- [ ] create ticket for other occurences

**Comment by KateChuen** [comment]
Tested on develop using yarn.
Did not test all the messages, but global messages look ok.
