### ISSUE TITLE
Facets are styled as checkboxes but vocalized as links, not enumerated and availability not identified

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13572]
**Describe the bug**

1. Screen Reader does not enumerate all checkboxes contained in facet groups.
2. When landing on the first 2 facets after entering the group it vocalizes the whole content, the bloated narration stops after the 3rd facet but still, all facets get vocalized as links.
3. Available items are not being vocalized as "items" but only as numbers.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**
1. Open any Screen Reader (VO, NVDA, JAWS).
2. Tab to "Digital Cameras > Shop All Digital Cameras" category in Main Menu.
3. Tab to facet group "Stores".
4. Tab to first facet (simulated checkbox).
5. Listen to screen reader narration.

**Expected behavior**
- Screen Reader enumerates checkbox in each group : "Stores, group, expanded, 6 items". Use `role="group"` and list `<ul>`.
- Screen reader vocalizes facets as checkboxes and its state. Use: `role="checkbox"`, `aria-checked="false"`, `aria-labelledby` to convey proper vocalization.
- Screen Reader vocalizes: _"Stores, Chiba, 55 items available, checkbox, unchecked"_ (best). Or, _"Store and items available, Chiba, 55, checkbox, unchecked"_ (probably easier). TBD

**Screenshots**
![Screen Shot 2021-08-30 at 3 49 05 PM](https://user-images.githubusercontent.com/15113219/131396655-26e56007-ca12-41ef-b811-0441cfad77de.png)
<img width="712" alt="Screen Shot 2020-10-13 at 7 01 39 PM" src="https://user-images.githubusercontent.com/15113219/131396821-5a910068-4ff6-436b-b418-78588fe59cec.png">
<img width="723" alt="Screen Shot 2020-10-13 at 7 03 25 PM" src="https://user-images.githubusercontent.com/15113219/131396827-c37d48da-373b-40b3-9743-b634aae87fde.png">
![Screen Shot 2021-08-30 at 4 43 52 PM](https://user-images.githubusercontent.com/15113219/131403084-d8f8998b-ac5a-434e-8cae-42eddd0edb4d.png)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

![facet2](https://user-images.githubusercontent.com/45409515/155602635-37727eca-2821-471b-9696-938318acd60c.png)
![facet1](https://user-images.githubusercontent.com/45409515/155602641-8a222c87-6e31-4b89-bd76-aef2d25670a2.png)
