### ISSUE TITLE
[needs assistive directive] JAWS/NVDA Add-to-cart needs meaningful vocalized feedback for screen reader users

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13581]
**Describe the bug**
- If the user is on the results page and hits the add to cart button the dialog gets vocalized only as "updating cart" but there is no vocalization of:
- An item being successfully added or
- The item was already in the cart and the quantity was updated. 

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**

1. Open any Screen Reader (VO, NVDA, JAWS).
2. Tab to any product category. E.g. "Film Cameras"
3. Tab to the first product.
4. Add product using the keyboard (Enter or Spacebar).
5. Listen to screen reader feedback.

**Expected behavior**
- Include success/warning message in the same context as the _"Updating cart"_ message.
- Screen reader vocalizes:  _"1 item has been added to your cart"_ or if the product is already in the cart...
- Screen reader vocalizes: _"The item was already in the cart. The quantity was updated."_ 
- Use: `aria-live="polite"` and `aria-atomic="true"`.

**Screenshots**

![Screen Shot 2021-08-31 at 11 34 51 AM](https://user-images.githubusercontent.com/15113219/131538025-0a0b9b04-8dee-4f48-a32e-fe0c6570fe2c.png)
![Screen Shot 2021-08-31 at 11 32 58 AM](https://user-images.githubusercontent.com/15113219/131538066-f3c45c39-2b9a-4b04-a72e-17f16130af10.png)

**Comment by developpeurweb** [comment]
- While testing the spinner ticket I realized there's no **JAWS/NVDA** vocalization for  _"item added to your cart"_ and _"The item was already in the cart. The quantity was updated."_
- This ticket predates the assistive directive implementation, so maybe it's why it slipped through the cracks.

**Comment by KateChuen** [comment]
Tested on VO on mac. 
<img width="1233" alt="Screen Shot 2022-05-09 at 4 14 42 PM" src="https://user-images.githubusercontent.com/45409515/167491207-4fdccb25-7bc5-42d9-9f2b-28175dd18fb3.png">

<img width="1220" alt="Screen Shot 2022-05-09 at 4 11 58 PM" src="https://user-images.githubusercontent.com/45409515/167491244-ddcbd2f3-c4e4-4020-bbd7-3d8f4bd365a4.png">


**Remaining**: To be tested on JAWS
