### ISSUE TITLE
[Master Ticket] Revamp existing form according to the new specs.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#1358]
The existing form in the storefront need to be updated according to the new UX specs concerning mostly validation and the submit button's behaviour.  ( the 3 pages in the ‘inline errors’ folder ):
https://98qkkl.axshare.com/#g=1&p=main_action_on_form_pages

We need to make a list of all our forms and create one ticket per form so the work can be spread amongst developers.
A non exhaustive list of forms is:
- Register
- Login
- My account - Address book 
- My account - Payment types
- The checkout steps.

The example form is set to be the "Forgot your password" page which has an example of the new validation implementation.  The example is not perfect, but fits 80% of the requirement:

```
    <label>
      <span class="label-content">Email address</span>
      <input
        type="email"
        class="form-control"
        placeholder="Enter email"
        formControlName="userEmail"
        [ngClass]="{
          'is-invalid':
            form.controls['userEmail'].invalid &&
            (submited ||
              (form.controls['userEmail'].touched &&
                form.controls['userEmail'].dirty))
        }"
      />
      <div
        class="invalid-feedback"
        *ngIf="
          form.controls['userEmail'].invalid &&
          (submited ||
            (form.controls['userEmail'].touched &&
              form.controls['userEmail'].dirty))
        "
      >
        <span>Please enter a valid email.</span>
      </div>
    </label>
```

This leverages the build in angular validations mechanics.  The small flaw is that once the field is touched and the user comes back to it later, the validation message displays right away.  Otherwise it meets the requirements.  We might consider this an edge case, or we can spike for a better solution.  

It would be a good idea to complete a bigger form before doing all the others.  The register form is a good candidate for that.
We should take this opportunity to improve the unit tests on the forms to assess the validation behaviour.  Some of our forms have been hit with regression in this regard and the current unit tests didn't catch it. ( for example, some forms don't display an error message for some invalid fields and it used to do so. )

**Comment by developpeurweb** [comment]
Please keep in mind Accessibility concerns when improving validation patterns.
https://cxwiki.sap.com/display/spar/Form+Validation+Accessibility+Patterns

**Comment by Xymmer** [comment]
Kacper did a big improvement but I'm not sure he was aware of this ticket. I'll follow up to see where we stand.
