### ISSUE TITLE
Quick order: Search icon is always disabled

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13596]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.84.65.98

**Steps**
Go to powertools storefront
Click on Quick Order
Start typing a SKU

**Actual Result**
The search icon remains disabled
![Screen Shot 2021-08-30 at 10 51 14 AM](https://user-images.githubusercontent.com/45409515/131362893-9ba0f544-0330-4d3e-8657-b2c6d6f1744b.png)

We can only press ENTER to search for a SKU.

**Expected Result**
Was expecting a similar experience with the main search textfield. 
When we start typing, it gives a list of relevant items. Even if it does not, I would expect the search icon to be enabled, and I can click on it, then it would give me relevant results. 
But I can see why we don't want a list of search results here. We want the item displayed or not. 
So my question is, should we enable the search icon? Or remove it perhaps? It's a bit misleading to me. As a user, I would try to click on it, but nothing...

**Comment by Xymmer** [comment]
If we strive to be same as main search field, the improvement is to display "x"
Since that's our standard (you could argue why :) ) let's do same
![image](https://user-images.githubusercontent.com/4998145/131849598-97cd927e-ca0b-4efc-b251-f072275a35cf.png)

**Comment by bgambocjaviniar** [comment]
Issue with mobile as well. I'd like to have that display "x" button after typing something as well, but I think the intention would be similar to the input box in storefinder, where we can just type and click the "search icon" instead of pressing 'enter/return/etc'

**Comment by dydome** [comment]
@KateChuen Please review this ticket as Quick Order was improved in 4.2 release and I think this issue does not exist anymore

**Comment by KateChuen** [comment]
Yes correct. Not applicable anymore. 
Now, it gives a list of suggestions when we start typing(as of 3 characters or as configured)... and there's a X icon to close the list and clear the search box.

**Comment by developpeurweb** [comment]
@KateChuen @dydome the X icon is not Keyboard Accessible. It should be if we're following along the lines of the Main Search.

**Comment by KateChuen** [comment]
@developpeurweb Can you open a ticket to make it keyboard accessible please?
