### ISSUE TITLE
Order Approval/Reject emits cart update

### ISSUE THREAD

**Issue by halimfr** [SAP/spartacus#13599]
**Describe the bug**
When approving or rejecting an order, a PATCH request is sent to /users/current/carts/00001005/entries/0?qty=200&lang=en&curr=GBP
It looks like an event is emitted from the approval/reject to the cart update.
No customisation has been on the class level that just extends the Product class : 
export class CustomOrderDetailActionsComponent extends OrderDetailActionsComponent {}

**Tell us the version of Spartacus**
- Library version: 3.2

**Comment by Xymmer** [comment]
Let's investigate if we can repro ootb and determine impact, and come back to bug triage team to assess when we'll do a fix if needed.

**Comment by Xymmer** [comment]
we agreed to release this fix for 4.2 and backport 3.2-3.4
