### ISSUE TITLE
4.1.0 Flaky E2E Test Execution

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#13613]
Flaky Tests: 

![Screen Shot 2021-09-03 at 7 25 23 AM](https://user-images.githubusercontent.com/46171897/131998154-0238e3dd-acd0-45ab-8f46-12832112936a.png)

Status updates: 

1. asm - ok
2. cart - ok 
3. login - ok
4. store-finder
5. tabbing order - can/t run
6. b2b - units - fail
7. b2b - users - fail
8. product-configurator-cart - pend

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-09-03 at 11 44 46 AM](https://user-images.githubusercontent.com/46171897/132044967-77204677-c8f2-4bc2-999e-bb2f5bdea819.png)
![Screen Shot 2021-09-03 at 11 48 20 AM](https://user-images.githubusercontent.com/46171897/132044981-101f1050-5329-4a61-9895-111146226439.png)
![Screen Shot 2021-09-03 at 11 52 38 AM](https://user-images.githubusercontent.com/46171897/132044988-b3f56d00-a9e3-4529-bc88-85359fda3be4.png)

**Comment by giancorderoortiz** [comment]
b2b:
![Screen Shot 2021-09-03 at 2 08 49 PM](https://user-images.githubusercontent.com/46171897/132049513-aabb758f-9742-440c-a33f-740854772b3f.png)
![Screen Shot 2021-09-03 at 2 11 51 PM](https://user-images.githubusercontent.com/46171897/132049516-ad865bac-c17c-4f3b-8b1b-50dd415f5341.png)

**Comment by Xymmer** [comment]
4.1 done, closing
