### ISSUE TITLE
[Tablet] Gap between Quick order and Coupons

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#13624]
**Describe the bug**
Gap between Quick order and Coupons block on tablet resolution.

**Tell us the version of Spartacus**
- Library version: 4.1-rc

**To Reproduce**
1. Switch to tablet resolution
2. Add product to cart
3. Go to cart

**Expected behavior**
Gap between blocks should be removed.

**Screenshots**
![gap](https://user-images.githubusercontent.com/6958810/132307624-59629872-f7cc-48d7-ac49-bcb6c8331eed.jpg)

**Tablet**
 - Device: Tablet Samsung Galaxy Tab A
 - OS: Android
 - Browser Chrome

**Comment by kpawelczak** [comment]
@Matejk00 Seems to be fixed in the newest version.

![Bez tytułu](https://user-images.githubusercontent.com/42094017/157206971-1b39d553-c10e-43b0-ac37-cb0d371fc04a.png)

**Comment by dydome** [comment]
Yes it was fixed :)

**Comment by kpawelczak** [comment]
Closing as per comment above
