### ISSUE TITLE
Don't always fall back to CSR if rendering is in progress

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#13623]
The goal of this ticket is to improve the SSR performance in the following way:

- The `timeout` option is set to 3s
- An initial request for the `/` hits the server and SSR render is triggered. 
- let's say the rendering of the `/` will take 4s. This means that after 3s, the first request will timeout and return CSR to the end user
- the `/` continues to render in the background for one more second, and then it'll finish the render successfully.
- the second request comes in 2s after the first one
- in the current implementation, the second request would immediately fall back to CSR, as we're still rendering the first request.
- this improvement will allow the second request to wait at most 3s before falling back to CSR (honoring the `timeout` option). This is the maximum time the second request will wait, and it's likely the response will come sooner (as we'll see below).
- 2s after the second request arrived, the render for `/` finishes. The second request is responded to with the SSR 2s after it was sent.
- if we scale this up, and say that 1000 new requests hit the server after the initial request, we begin to see how this improvement will lower the rate at which the CSR fallback happens, and how much quicker the responses will be for the subsequent requests.

**Comment by Platonn** [comment]
QA:
Enable `reuseCurrentRendering` and `debug` options in `SsrOptimizationOptions` in `server.ts`

Execute a simple bash script for testing, for example:
```bash
#!/usr/bin/env bash
PORT="4200"

curl http://localhost:${PORT}/electronics-spa/ > home1.html & \
 curl http://localhost:${PORT}/electronics-spa/ > home2.html & \
 curl http://localhost:${PORT}/electronics-spa/faq > faq1.html & \
 curl http://localhost:${PORT}/electronics-spa/faq > faq2.html;

sleep 0.5;

 curl http://localhost:${PORT}/electronics-spa/ > home3.html & \
 curl http://localhost:${PORT}/electronics-spa/ > home4.html & \
 curl http://localhost:${PORT}/electronics-spa/faq > faq3.html & \
 curl http://localhost:${PORT}/electronics-spa/faq > faq4.html;
```


(for stress testing you might use a vendor tool from npm `loadtest`. Here's example for making 1000 parallel requests:
```bash
$ loadtest -c 1000 -n 1000 http://localhost:4200/
```
)
