### ISSUE TITLE
Support redirects from external auth pages to pages with AuthGuard

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#13622]
When we implemented auth in Spartacus we didn't assumed that there will be a case when we redirect from auth provider page to the page that is protected with AuthGuard.

When this case happens and we use Authorization Code Flow that require a bit more time to finish (it does a call with code to exchange it for a token) the guards might be invoked too quickly (before we get the token).

**How we should behave in this situation?**

We should have some flag that says if the login is in progress. If so we should wait in AuthGuard for it to finish first before me make a decision to redirect user to login page.

**Comment by Platonn** [comment]
Do you mean implementing this logic inside `AuthService.isUserLoggedIn()` or you see other potential places for it?

**Comment by marlass** [comment]
I thought about introducing another observable to AuthService like `loginInProgress$` and then leveraging it in `AuthGuard` to wait before this one completes, but the idea about integrating it directly into `isUserLoggedIn` is even better and could potentially fix even more problems than only this AuthGuard redirecting to quickly.

**Comment by Xymmer** [comment]
Is this fixable for 4.2?

**Comment by Zeyber** [comment]
This situation should also be covered in e2es in #9445

**Comment by Zeyber** [comment]
QA Steps:
- Setup code flow in backoffice like [this](https://user-images.githubusercontent.com/4001059/158995444-c4043115-b7b0-4a9f-a58a-3695d9f3108f.png)
   [@Platonn's edit]: add `implicit` and `authorization_code`:
  <img width="293" alt="image" src="https://user-images.githubusercontent.com/4001059/167805722-840b875d-fef1-4bf5-a20b-e4274f2131f3.png">

- Go to auth protected page (eg. checkout).
- Login
- You should be redirected back to the checkout page.

**Comment by Platonn** [comment]
moving to Jira https://jira.tools.sap/projects/CXSPA/issues/CXSPA-405
