### ISSUE TITLE
[retest] Quick order: input box should not allow empty strings to trigger the action to add a product to the form.

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13636]
**Describe the bug**
A user can submit an empty product which throws a global message saying Product with code 'null' not found.

**To Reproduce**
1. Go to quick order page
2. Click on the input box to submit a product code, but leave it blank
3. Press enter or return in mobile

**Expected behavior**
- Should not throw an error or dispatch any 'actions' when the input box is empty similarly to the 'search' input box from the storefinder or the global product search.
- Should also handle if the input box has only empty spaces to not trigger the 'actions' as well for user experience.

**Screenshots**
![Image from iOS](https://user-images.githubusercontent.com/29099466/132406404-7e75ae97-0ea4-493c-9d98-bf8101de5aca.png)

**Comment by Xymmer** [comment]
Brian says retest, as it might be fixed
After MichalD merges stretch fixes

**Comment by dydome** [comment]
@Xymmer you are writing, I am closing the issue. After quick order stretch fixes merge. the problem does not exist anymore.
