### ISSUE TITLE
Quick order: Updated qty in message is different from qty in cart

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13632]
**Environment Details**
Browser: Chrome 
Device: mac
ccv2: https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/

**Steps**
Go to Electronics storefront
Go to Quick Order
Type this SKU: 676442
and press Enter
Type in a huge number in the qty box, for eg: 1000000
Click Add to Cart

**Actual Result**
You're able to type in any number in the qty box
You get a message saying the qty has been changed to 9999
<img width="1138" alt="Screen Shot 2021-09-07 at 3 35 45 PM" src="https://user-images.githubusercontent.com/45409515/132401381-2c3d8f10-8b56-439d-aecb-5fb647833c8c.png">

But if you go to your cart, you'll see the item and the qty is in fact 1000
<img width="804" alt="Screen Shot 2021-09-07 at 3 35 59 PM" src="https://user-images.githubusercontent.com/45409515/132401387-0e71c291-f1dd-421d-ac92-21803d355f2d.png">

**Expected Result**
Message about the updated qty should reflect the qty in the cart

**Comment by dydome** [comment]
Hi @KateChuen it is not a Quick Order issue but rather a cart problem. I think there was a purpose in the past to set the maximum value to 1000 if there is no stock level information. I think to not show wrong information I will remove this part of the code. Please refer to my PR with fix -> https://github.com/SAP/spartacus/pull/14086

**Comment by KateChuen** [comment]
Tested locally, on develop branch, pointing to 2105 backend (dev9).
Works now. The message is accurate and clear. 
![13632_fixed](https://user-images.githubusercontent.com/45409515/138467526-8e5b37df-d5f8-4753-b21a-91bd6f8b86f1.png)

**Comment by KateChuen** [comment]
Will retest it once above PR has been merged to develop.

**Comment by KateChuen** [comment]
Retested after the latest PR has been merged. Works!
