### ISSUE TITLE
Quick order/session management: Successful message added to cart but was not

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#13633]
**Environment Details**
Browser: Chrome 
Device: mac
ccv2: https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/

**Steps**
Login to electronics storefront
Leave session idle for a long time (not sure how long it took)
Go to Quick Order
Type some SKUs and press Enter
Click Add to Cart

**Actual Result**
You'll get a successful message it was added to cart. But cart is empty.
You get a message saying the qty has been changed to 9999

**Expected Result**
Should get appropriate message.

**Note**
Does it have to do with an expired session or token?

**Comment by dydome** [comment]
@KateChuen I am not sure how to test it. As I wrote it a couple of other bugs for quick-order after the big upgrade to 4.2 release, may you verify it once again?

**Comment by KateChuen** [comment]
Retested locally on develop branch, pointing to 2105 backend on dev9. 
it works now, was not able to reproduce it anymore.
