### ISSUE TITLE
Make `ActiveCartService.addEntry` behaviour stable for concurrent calls

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#13645]
Currently `addEntry` method tries to make sure we have an active cart (loads or creates one) before we try to add to it. However, when we call this method multiple times simultaneously we can create multiple carts and add entries to different carts.

At the moment it doesn't impact default entry handling as the UI blocks any interaction until we have successfully added an entry to the cart, but the custom implementation of the UI can allow to add multiple products in a short window of time (clicking add to cart on multiple products in the listing).

This bug is present for a very long time, so I guess for a very long time no one had problem with it.

I would recommend working on it when moving the cart feature to the cart library or for a major release, as fixing it properly might require some breaking changes.

**Comment by mateuszo** [comment]
I did face this issue. The workaround was to force the client to use the spinner :D . Another workaround is to create custom data flow for this.
There's also a similar issue with `updateEntry` method which is used by the cart details component.

**Comment by Xymmer** [comment]
Setting this to must-fix for 5.0. 
We discussed backporting this one but the work is not a simple bug fix, so can't backport.

**Comment by WeizhengSap** [comment]
In `add-to-cart.component.ts`, I made this `this.activeCartService.addEntry(this.productCode, quantity)` called 3 times. So, when clicking "Add to Cart" button, the function `addEntry` will be called 3 times. 
For anonymous user, I can see that: there is only one cart created, and 3 entries are added to the same cart.

![Screen Shot 2021-12-06 at 10 26 11 AM](https://user-images.githubusercontent.com/44440575/144863351-ee732b8a-30cf-41b7-9596-cc51097d6fef.png)
 
But, for login user, I can see the issue.

**Comment by WeizhengSap** [comment]
This ticket is moved to QA column, so that other devs can double check it.
