### ISSUE TITLE
Quick order: missing button and label, as per mockups

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13653]
**Describe the bug**

- Quick order is not as per mockups. With only one button visible there is the expectation the disabled button will get enabled once the search field is filled in, which is not the purpose of the button.
- It's also missing the **Name or SKU** label on top of the search field.

**Screenshots**
**Currently:**
![Screen Shot 2021-09-03 at 9 28 56 AM](https://user-images.githubusercontent.com/15113219/132574051-037dbd60-2f2d-474e-8f60-9f625f36f10d.png)

**Approved mockups:**
![Screen Shot 2021-09-03 at 10 40 07 AM](https://user-images.githubusercontent.com/15113219/132574132-65ec7279-116e-4aba-b389-59b80e73153a.png)

**Comment by dydome** [comment]
Hi @developpeurweb starting from the second point it is already solved with new quick order implementation. 

Going to the first point, I am not sure what is wrong here? I had a few conversations with UX team and I was informed to hide the "Empty list" button if there is no entry on it.

**Comment by dydome** [comment]
I think we can close this issue as it will be solved with PR-> https://github.com/SAP/spartacus/pull/14091
