### ISSUE TITLE
Percentage of a page loaded not being vocalized 

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13698]
**Describe the bug**
- Currently, there's no hint as to what percentage of the page has been loaded, so a Screen Reader user wouldn't know when a page has loaded fully.
- This is particularly helpful for users with slow internet connections.
- This could be related to Lazy Loading.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**Expected behavior**
- Screen Reader vocalizes the percentage of the page that has loaded.
- "Loading" messages get vocalized using `aria-live="polite" aria-atomic="true"`

**Screenshots**

Some examples of how this feature is expected to be vocalized:

<img width="639" alt="Screen Shot 2020-10-07 at 6 17 29 PM" src="https://user-images.githubusercontent.com/15113219/133162974-a58afadc-f38c-4378-85ea-435da8be5ca1.png">

<img width="620" alt="Screen Shot 2020-10-07 at 6 05 41 PM" src="https://user-images.githubusercontent.com/15113219/133162991-e60aa40a-a158-4324-a837-90f5b2ec5909.png">

**Comment by FollowTheFlo** [comment]
After discussion with @developpeurweb , behavior needed:
Display 'Loading' when spinner is displayed then 'Loaded' once spinner disappears.

**Comment by FollowTheFlo** [comment]
note for new assignee:
- part1: "display 'Loading' when spinner is displayed " was done in PR #15211
- part2 is needed: **display 'Loaded' once spinner disappears**

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

It now says "Loading" while the page is loading. 
And "Loaded" when the page has loaded.

Percentage loaded has not been implemented.
<img width="1158" alt="Screen Shot 2022-04-22 at 1 30 07 PM" src="https://user-images.githubusercontent.com/45409515/164765242-776e5e36-d36b-4fea-a9e8-5ec096e95f20.png">

<img width="1158" alt="Screen Shot 2022-04-22 at 1 30 22 PM" src="https://user-images.githubusercontent.com/45409515/164765252-a30e0a48-02fb-4b2b-a301-631d4af20a54.png">

<img width="1152" alt="Screen Shot 2022-04-22 at 1 30 30 PM" src="https://user-images.githubusercontent.com/45409515/164765260-6155e310-847d-43ad-9f33-533e270822ca.png">
