### ISSUE TITLE
E2E for import active cart

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13715]
- [x] Provide e2e scenario for import to active cart, because now only scenarios for import to saved-cart are provided

**Comment by Matejk00** [comment]
Possibly can be closed, to confirm with @Pucek9, because we already have e2e's implemented.

**Comment by Matejk00** [comment]
After conversation with @Pucek9 turned out that we only have e2e's implemented for saved-cart, not for active-cart. So still needs to be added.
