### ISSUE TITLE
Find a Store: On the Store Details page, there is no vocalized feedback of context change when landing

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13740]
**Describe the bug**
- When landing on a Store Details page, there's no change of context feedback as to where the user has landed or what happened on the screen.

**Tell us the version of Spartacus**
- Library version: 4.0.0.

**To Reproduce**

1. Open any Screen Reader (VO, NVDA, JAWS).
2. Go to the Find a Store page
3. Click on the "View All Stores" button
4. Click on any location having stores
5. When landing on the Store Details page, there is no vocalization this is a new page.

**Expected behavior**

- The best way to achieve this is by unlocking the focus before landing on the Store Details page, and adding the store name to the page title.
- An alternative method, if the previous isn't possible, is to add `role="alert"` to the store name, so it gets vocalized on landing. See example below.

**Screenshots**
![Screen Shot 2021-09-15 at 3 48 38 PM](https://user-images.githubusercontent.com/15113219/133501177-d63b8437-c67e-49d9-b236-bc30db14307c.png)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

On store details page, it's ok now. It vocalizes the info about the store.
![storeFinder](https://user-images.githubusercontent.com/45409515/155597300-8c24b59e-c049-4e01-8868-d468bd018e37.png)

But did find that "View all stores" got broken. Created ticket https://github.com/SAP/spartacus/issues/15243 for this.
