### ISSUE TITLE
Deprecation - Remove `keyboardFocusFactory` and `OnNavigateFocusService` and use the new functionality from /storefrontlib/router folder

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#13762]
Remove the deprecated 'old' restoration scroll storefrontlib/layout/a11y/keyboard-focus.
The code in storefrontlib/router is going to replace it.

- [ ] remove references and folder /storefrontlib/layout/a11y/keyboard-focus/on-navigate 
- [ ] remove /storefrontlib/layout/a11y/keyboard-focus/config
- [ ] remove references of files from keyboard-focus.module.ts

**Comment by Platonn** [comment]
closing in favor of https://jira.tools.sap/browse/CXSPA-601
