### ISSUE TITLE
[small adjustment needed] Order History accordions don't vocalize if they are collapsed or expanded

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13770]
**Additional context**

- Fix this ticket only after the whole Screen Reader milestone for desktop is completed. 

**Describe the bug**

- Order History tabs are converted into accordions on mobile, but don't provide any hint they are being collapsed or expanded

**To Reproduce: Watch Test Videos**

- Android Talkback test video
https://video.sap.com/media/t/1_1gtfpn6o
min 1:30:00
  
- Iphone VoiceOver test video
https://video.sap.com/media/t/1_qa70rxtl
min 0:42:32

**Expected behavior**
- Screen reader vocalizes the expanded or collapsed state of the accordion.

**Comment by pawelfras** [comment]
It depends on #11637

**Comment by developpeurweb** [comment]
A small adjustment on the aria-label for consistency.


<img width="1258" alt="Screen Shot 2022-03-11 at 9 41 39 AM" src="https://user-images.githubusercontent.com/15113219/157889414-26348a9d-39cc-4469-adb4-f986b030e3dc.png">
