### ISSUE TITLE
Create new component for "EXIT CONFIGURATION" Button in SPA Header

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#13806]
New component should trigger a "browser back" when clicked. 
When no browser back is possible, the user should go the the product detail of the product which is configured.

Component will be added in rulebased module, lazy loading is expected.
Component has to take care that the header is styled correctly.

**Comment by ChristophHi** [comment]
This is still open, since https://github.com/SAP/spartacus/pull/14213 is pending. The corresponding sample data PR is also still open, no complete test possible
