### ISSUE TITLE
DpPaymentMethodModule makes checkout core and components eager loaded

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#13821]
DpPaymentMethodModule directly import @spartacus/checkout/components and @spartacus/checkout/core, which make them eager loaded.

**Comment by Platonn** [comment]
Hi @WeizhengSap
1. Did we plan to fix it before 5.0?.
2. Do you think it’s a low hanging fruit to fix it?
3. Does your cart refactor need to be merged first, before we fix it? Or can be fixed in parallel by someone else?

**Comment by WeizhengSap** [comment]
@Platonn: I want to give this ticket to the owner of digital payment. :)

**Comment by WeizhengSap** [comment]
doc PR: https://github.com/SAP/spartacus-docs/pull/1407
