### ISSUE TITLE
Checkout payment type module not exported

### ISSUE THREAD

**Issue by jamesgarzon** [SAP/spartacus#13897]
**Is your feature request related to a problem? Please describe.** 
For a new B2B we need to customize payment type and this module is not exported

**Describe the solution you'd like**
Export Payment type module in the index of checkout components

**Comment by Xymmer** [comment]
Investigate if there is a good reason we don't export payment module.
If there is a good reason, reset this ticket to 5.0.
If not and we should have it exported, do for 4.2.

**Comment by Platonn** [comment]
It seems we just [overseen exporting this module](https://github.com/SAP/spartacus/blob/develop/feature-libs/checkout/components/components/index.ts). Let's export both the module and the component!

@jamesgarzon Temporarily you might want to use the dirty workaround: https://stackoverflow.com/questions/66871919/how-to-use-private-api-of-the-spartacus-library/66871920#66871920

**Comment by bgambocjaviniar** [comment]
PR: GH-14263
