### ISSUE TITLE
Possibility to cancel improting entries

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#13901]
My investigations:

I tried both, `unsubscribe` and 
```ts
takeUntil(this.launchDialogService.dialogClose.pipe(filter(Boolean))),
```

but the core implementation is synchronous 
```ts
 addEntries(
    userId: string,
    cartId: string,
    products: Array<{ productCode: string; quantity: number }>
  ): void {
    products.forEach((product) => {
      this.store.dispatch(
        new CartActions.CartAddEntry({
          userId,
          cartId,
          productCode: product.productCode,
          quantity: product.quantity,
        })
      );
    });
  }
```
so I can not cancel it from outside - only refresh the page which causes removing the request queue.

So, there are 2 possible scenarios when I cancel:
- When I wait and I can see the count of products has been updated, then I open and see a fully imported cart.
- When I open the cart before it's fully loaded, it realizes that `processCount` is wrong and cart is automatically removed.
![image](https://user-images.githubusercontent.com/8040837/135277638-c73a8bfc-311c-4410-a5e4-00c2d32e6f88.png)

**Comment by Pucek9** [comment]
Hold confirmed with @marlass:
- in general, it would be good to have commands for a single addEntry and then some better queuing could be done with the possibility of interruption. Too big effort to change it now.
- we shouldn't touch it now (while cart refactors and moving to lib).

**Comment by Xymmer** [comment]
moved to https://jira.tools.sap/browse/CXSPA-309
