### ISSUE TITLE
Add support for more than 4 tabs in TabParagraphContainerComponent

### ISSUE THREAD

**Issue by sam-garland** [SAP/spartacus#13948]
**Is your feature request related to a problem? Please describe.**
When a Spare Parts tab is added to the product details page the width of the tab headers is not consistent since the CSS is currently hard coded to allow up to 4 tabs.

**Describe the solution you'd like**
Add a CSS variable that allows a higher number of tabs (in this case 5) to be specified.

**Describe alternatives you've considered**
A fully dynamic layout based on the number of tabs that need to be shown.
This level of complexity is probably unjustified and it also could also delay the point at which tab layout (or at least the final layout can occur).

**Additional context**
The current behaviour with 5 tabs is shown in the screenshots below:
![Wide screen](https://user-images.githubusercontent.com/52560012/135733102-eefad1a0-3947-4fd0-b8a9-4203cbfeca1c.png)

![Truncated](https://user-images.githubusercontent.com/52560012/135733164-189e706f-b4ba-4895-a6c8-f3a6b8207de4.png)

In this scenario the results are fine when the total width allocated to 4 tabs is redistributed among 5 tabs instead.

**Comment by Xymmer** [comment]
To Mikel to investigate if we can adjust default styling to accomadate a 5th tabs, but that would be our max and for more tabs, we'd have to improve the design of the tab handling

**Comment by Xymmer** [comment]
@sam-garland were you going to submit a fix to core team?

**Comment by sam-garland** [comment]
> @sam-garland were you going to submit a fix to core team?
Yes @Xymmer, I'll do that.

**Comment by sam-garland** [comment]
Mikel mentioned that he would take this up.
