### ISSUE TITLE
Empty OCC baseUrl breaks SSR mode

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#13944]
## Overview

In case when we run Spartacus in the same domain as the API we don't want to set OCC URL as API endpoints should be referenced with relative URLs (not the absolute).

## Steps to Reproduce

1. Have Spartacus and backend on the same domain
2. Remove the `occ.baseUrl` option from your config
3. Check that the page doesn't work

The application is crashed with the following error:

```
ERROR TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
    at subscribeTo (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:131192:15)
    at innerSubscribe (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:274679:93)
    at CatchSubscriber.error (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:118063:109)
    at SwitchMapSubscriber.notifyError (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:274653:26)
    at SimpleInnerSubscriber._error (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:274621:21)
    at SimpleInnerSubscriber.error (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:105894:18)
    at CatchSubscriber.notifyError (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:274653:26)
    at SimpleInnerSubscriber._error (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:274621:21)
    at SimpleInnerSubscriber.error (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:105894:18)
    at Observable._Observable__WEBPACK_IMPORTED_MODULE_0__.Observable.scheduler.schedule.error.error [as _subscribe] (/Users/artem.zur/Documents/Projects/storefront/dist/storefront/server/main.js:273227:100)
```

## Expected behavior

A Spartacus application works without `occ.baseUrl` in SRR mode 

## Environment Details

- Spartacus:  *-3.4.1

## Additional context

- The issue https://github.com/SAP/spartacus/issues/10436 solved the same problem for Auth flow
- https://angular.io/guide/universal#using-absolute-urls-for-http-data-requests-on-the-server

**Comment by rpisarew** [comment]
I had a similar issue and my solution for this looks like that:

```typescript
@NgModule({
  imports: [
    AppModule,
    ServerModule,
    ServerTransferStateModule,
    ConfigModule.withConfigFactory(
      (req: Request) => {
        const host = req.headers['x-forwarded-host'];
        const proto = req.headers['x-forwarded-proto'];
        const baseUrl = environment.name === 'local' ? environment.occBaseUrl : `${proto}://${host}`;

        return {
          backend: {
            occ: {
              baseUrl,
            },
          },
        };
      },
      [REQUEST],
    ),
  ],
  bootstrap: [AppComponent],
})
export class AppServerModule {}
```

I take the protocol and host from the forwarded headers of the proxy and build the baseUrl out of it. Locally I have no proxy, because of that I use there a static URL from my env config.

**Comment by artem-zur** [comment]
@RPisarew, thanks a lot for the workaround!

**Comment by artem-zur** [comment]
> I had a similar issue and my solution for this looks like that:
> 
> ```ts
> @NgModule({
>   imports: [
>     AppModule,
>     ServerModule,
>     ServerTransferStateModule,
>     ConfigModule.withConfigFactory(
>       (req: Request) => {
>         const host = req.headers['x-forwarded-host'];
>         const proto = req.headers['x-forwarded-proto'];
>         const baseUrl = environment.name === 'local' ? environment.occBaseUrl : `${proto}://${host}`;
> 
>         return {
>           backend: {
>             occ: {
>               baseUrl,
>             },
>           },
>         };
>       },
>       [REQUEST],
>     ),
>   ],
>   bootstrap: [AppComponent],
> })
> export class AppServerModule {}
> ```
> 
> I take the protocol and host from the forwarded headers of the proxy and build the baseUrl out of it. Locally I have no proxy, because of that I use there a static URL from my env config.

@RPisarew, maybe this information can be interesting for you. If I've correctly understood the implementation of [NgExpressEngineDecorator](https://github.com/SAP/spartacus/blob/develop/core-libs/setup/ssr/engine-decorator/ng-express-engine-decorator.ts#L89), the application should work in SSR mode with relative URLs by using a value of either "Host" or "X-Forwarded-Host" request header. This is very similar to your workaround.

P.S. I tested the behaviour of NgExpressEngineDecorator, it doesn't work as expected.

**Comment by Xymmer** [comment]
Thanks for providing workaround 
We'll try to fix this for 4.2.
Also evaluate if it needs a backport to 3.x

**Comment by Platonn** [comment]
@RPisarew @artem-zur 
Please note that it's not secure to trust on the raw x-forwarded-... headers! You need to trust the proxy that have set it. See https://expressjs.com/en/guide/behind-proxies.html

For knowing the server request URL or origin you should use the the Spartacus tokens `SERVER_REQUEST_ORIGIN`or `SERVER_REQUEST_URL` (see https://sap.github.io/spartacus-docs/server-side-rendering-coding-guidelines/#getting-the-request-url-and-origin).
Their resolver function **take into account** the trusted proxy configured for Express.js. See:
https://github.com/SAP/spartacus/blob/ea55840f9119a9ceab8025ef497a2d56cbc03645/core-libs/setup/ssr/engine-decorator/ng-express-engine-decorator.ts#L89-L106

**Comment by artem-zur** [comment]
Hi @Platonn, thanks a lot for the engagement and additional information in regard to this topic. You mentioned `NgExpressEngineDecorator` which is already a part of the Spartacus *-3.4.1, so theoretically SSR should work from the box without setting an OCC base URL but if a request contains either `X-Forwarded-Host` or `Host` header, right? Or should we do an additional configuration except for the mentioned headers (for example the workaround from @RPisarew), to make SSR work from the box with a relative URL?

P.S. I'm just trying to understand if this ticket is a bug or I missed something when a configuration of the Spartacus application was made.

**Comment by Platonn** [comment]
Just to be on the same page:
The `Request` in `getRequestOrigin(req: Request)` refers to the request for storefront page html (from the SSR). e.g `http://my-store.com`
But please note that in the default CCV2 setup the OCC API is hosted on a different domain than the storefront.

Only if you serve both the storefront and the OCC API on the same domain, then you can derive the OCC domain from the storefront SSR Request's domain.

Side question: does your requirement (of leaving occ.baseUrl empty / relative) work in CSR?

**Comment by Platonn** [comment]
... and to answer your question @artem-zur : Spartacus currently doesn't support the empty occ.baseUrl in general.
Moreover, by default you should get a console.warn if the occ.baseUrl is not configured.
https://github.com/SAP/spartacus/blob/bc69ae2e86bbe45e17df67f8081a92e60f0923ea/projects/core/src/occ/config/occ-config-validator.ts#L9

So if you want to derive the OCC base url from the storefront request url in SSR, you need a custom workaround based on the `SSR_REQUEST_ORIGIN`.

Although we could consider adding the support of a relative OCC base url as a feature, I'm not in favor of doing that. The separation of domains for storefront and API helps the secure infrastructure OOTB. For more see https://security.stackexchange.com/questions/188522/why-some-applications-host-the-api-in-a-different-domain

If I'm missing something, please let me know.

**Comment by Xymmer** [comment]
closing as we won't be adding support for this based on ootb security, and there is possibility of customizing for these cases.

**Comment by artem-zur** [comment]
Thank you very much, @Platonn!

> Only if you serve both the storefront and the OCC API on the same domain, then you can derive the OCC domain from the storefront SSR Request's domain.

This is exactly our case, we use `SERVER_REQUEST_ORIGIN` to then use its value as `backend.occ.baseUrl`, this is how our configuration looks like:

```ts
export function occConfigFactory(
  serverRequestOrigin: string | null
): OccConfig {
  const config: OccConfig = {
    backend: {
      occ: {
        // A `serverRequestOrigin` is only available in SSR mode
        // While in CSR mode the app can work without `baseUrl`
        //
        baseUrl: serverRequestOrigin ?? undefined,
      },
    },
  };

  if (environment.occBaseUrl && config.backend?.occ) {
    config.backend.occ.baseUrl = environment.occBaseUrl;
  }

  return config;
}

export function provideOccConfig(): Provider {
  return provideConfigFactory(occConfigFactory, [
    [new Optional(), SERVER_REQUEST_ORIGIN],
  ]);
}
```

> Side question: does your requirement (of leaving occ.baseUrl empty / relative) work in CSR?

Yes, it works.

P.S. Unfortunately, now we have another [issue](https://stackoverflow.com/questions/76365847/spartacus-server-request-origin-resolves-wrong-protocol-in-ssr), related to this topic. @Platonn, if you have a minute, can you please check it from your side, I would be very appreciated.
