### ISSUE TITLE
[MOBILE only] Set minimum width and height to 48px on Links and Buttons

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#13991]
**Describe the bug**

- Some interactive elements **on mobile** are not large enough by Lighthouse's best practices.
- Tap target areas should be at least 48x48px.
- See the screenshots below for the Homepage, as an example, but please run Lighthouse on all pages to verify.

**Tell us the version of Spartacus**
- Library version: 4.0

**Expected behavior**

- Minimum height is at least 48x (either by min-height value or padding).
- Minimum width is at least 48x (either by min-width value or padding).
- Improve CSS by adding the pixels needed to the targets areas, to match a minimum of 48px **on mobile** media queries.

**Screenshots**

![Screen Shot 2021-10-06 at 6 52 52 PM](https://user-images.githubusercontent.com/15113219/136295111-4cf79fcf-5b09-49b6-b07c-4f98e21cc43e.png)

![Screen Shot 2021-10-06 at 6 53 08 PM](https://user-images.githubusercontent.com/15113219/136295186-96f13836-d10c-4081-b14c-6003c5f7adf0.png)

![Screen Shot 2021-10-06 at 6 53 20 PM](https://user-images.githubusercontent.com/15113219/136295197-058325a1-e1f4-4533-a26d-3d47b2dd46d3.png)

**Comment by morganm58** [comment]
moved to Jira
