### ISSUE TITLE
[for 2.0 upgrading] Update custom applications

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#14]
While the architecture is completely driven to allow for upgradability, there will be breaking changes from one version to another that wil make upgrades less seamless as we'd like. Also, dependency management can cause a lot of time for app developers for each and every (larger) release that we bring. Therefor we like to use angular schematics to allow for a seamless upgrade of dependencies and other breaking changes we might do.

**Comment by Xymmer** [comment]
superceded by speciifc schematics tickets since creation of this issue, closing
