### ISSUE TITLE
Fix flaky added-to-cart-modal e2e test

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#14017]

**Comment by bgambocjaviniar** [comment]
someone to pick as I will be focusing on another task at hand

**Comment by psmul** [comment]
Tests don't seem to be flaky anymore. They passed smoothly on pipeline many times.

**Comment by hackergil** [comment]
@psmul test IS flaky after you run it several times in both the runner and headless. See attached

![Screen Shot 2021-11-18 at 9 28 06 AM](https://user-images.githubusercontent.com/158500/142434317-84981aca-26db-44d1-a4c3-634f77f1f04d.png)

![Screen Shot 2021-11-18 at 9 28 29 AM](https://user-images.githubusercontent.com/158500/142434296-731a8b96-52f6-44ec-8079-bad3b59cb6b8.png)
