### ISSUE TITLE
cx-media gives error when [container] prop is used with strictTemplate: true 

### ISSUE THREAD

**Issue by dimitarlaskov-novarto** [SAP/spartacus#14037]
**Describe the bug**
I'm using cx-media component to show some product images. In the source code of Spartacus there's examples with cx-media which is accepting images in the [container] property from the default data model of the Product.
But in the newest version of Spartacus with Angular 12 the strictTemplate property is enabled by default (which is good), but when I pass something like this to the cx-media component:
` <cx-media [container]="product.images?.PRIMARY" format="product"></cx-media>`

I get a complain from the compiler:
`Type 'ImageGroup | ImageGroup[]' is not assignable to type 'MediaContainer'.`

This is a bummer, because usually the cx-media component is used very often with product images and the strictTemplate option is usually really helpful so I don't want to disable it.

**Tell us the version of Spartacus**
- Library version: 4.1.1

**To Reproduce**
1. Create new project with the latest Spartacus libraries
2. Use cx-media component in an example component somewhere in the application
3. Get current product and assign product.images.PRIMARY to the [container] property of the cx-media component (make sure that the strictTemplate flag is set to true).

**Expected behavior**
The container property of cx-media component should accept types of ImageGroup | ImageGroup[] or there should be other property which accepts ImageGroup | ImageGroup[].

**Screenshots**
![image](https://user-images.githubusercontent.com/82885895/137328301-37a2782e-0eea-4a82-9f6e-fd6b0761f6d1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version:  latest version

**Comment by Xymmer** [comment]
1. Investigate what new types we should add, then add them (for 5.0)
2. Backport to last 4.x release
