### ISSUE TITLE
As Customer I wish to be able to see my password on the login and reset password Page in order to confirm that what i wrote is correct

### ISSUE THREAD

**Issue by flaville** [SAP/spartacus#14066]
**Is your feature request related to a problem? Please describe.**
Some of our customers have a lot of trouble with password management and sometimes forgot that Capslock is enabled or padlock is not enabled.
The goal is to allow the customer to be able to see his password easily.

**Describe the solution you'd like**
We overrided component ResetPasswordFormComponent (copy past it as properties are private :( ) and added: 
- boolean attribute(s) who define the status of the input field(s)
- a function in order to calculate the display mode, for example: 
`changePasswordDisplay(): void {
    this.passwordHide = !this.passwordHide;
  }
`
- two new icons type: 'EYE' and 'EYE_SLASH'
- customized html rendering like this using input-group-append bootstrap class: 
`
        <input class="form-control" type="password" name="password" [type]="passwordHide ? 'password' : 'text'" placeholder="{ 'register.password.placeholder' | cxTranslate }}" formControlName="password" />
        <div class="input-group-append" (click)="changePasswordDisplay()">
          <cx-icon
            class="input-group-text h-100 d-flex"
            role="button"
            [type]="getIconType(passwordHide)"
            name="passwordIcon"
          ></cx-icon>
        </div>
`

- added bootstrap style like this: 
`@import '~bootstrap/scss/input-group';`

**Describe alternatives you've considered**
Allow developer to override properly ResetPasswordFormComponent component as for LoginFormComponent

**Additional context**
![image](https://user-images.githubusercontent.com/62143872/137871535-461c1989-5bff-410f-81fa-d659a886f65a.png)

**Comment by Xymmer** [comment]
this ticket moved to jira it seems
https://jira.tools.sap/browse/CXSPA-292
