### ISSUE TITLE
Remove order components import from organization lib and checkout lib

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#14099]

**Comment by WeizhengSap** [comment]
We can use the `Routing Context` introduced by `import/export` feature.

**Comment by WeizhengSap** [comment]
sample data PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/211

**Comment by plabadie** [comment]
The benefits don't seem to outweigh the complexity cost and migration procedure required.

**Comment by plabadie** [comment]
Won't fix
