### ISSUE TITLE
Image Zoom: Perhaps remove the selection box on the arrow when in focus

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14122]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 20.62.192.238

**Steps to Reproduce**
Go to electronics storefront
Go to pdp of this product: 1934793
Click on "Expand Image"
Click on the arrow to navigate through the images

**Actual Result**
Looks like there's a selection box when the arrow is in focus or being selected. 
If I go to mobile view size, there's no selection box, the arrow is just red to show it's in focus. 

![Screen Shot 2021-10-26 at 3 26 33 PM](https://user-images.githubusercontent.com/45409515/138948103-9c4c2cc6-a43c-4e47-a318-173ac381b47e.png)

![imagezoomArrow](https://user-images.githubusercontent.com/45409515/138948120-abbc5fa3-d78a-4c78-bf17-95d356424516.png)

**Expected Result**
Maybe to be consistent, just have the arrow red? No need for the selection box, which is also slightly displayed under the image. I think it looks more neat, without the box...

**Comment by Xymmer** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-307
