### ISSUE TITLE
Image Zoom: The focus is not on the correct thumbnail when navigate through arrows

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14120]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: develop branch on my local
Backend: release/2011/next branch on devci4
Happens on: 0.62.192.238

**Steps to Reproduce**
Go to electronics storefront
Go to pdp of this product: 1934793
Click on "Expand Image"
Click on a thumbnail, for eg, first one
Click on the arrow to go to the next image

**Actual Result**
The focus is still on the first thumbnail

![imagezoomNext](https://user-images.githubusercontent.com/45409515/138945408-e1f41b4f-23c5-4c7a-a180-0934f463125e.png)

**Expected Result**
I think the focus should move along with the image being displayed. So if i'm on the 2nd image, the focus should be on the second thumbnail.

**Comment by RadhepS** [comment]
Parked it due to 4.2 testing, now it is not in Bill's 4.2 release board. I have removed my assignment due not getting a chance to start working on it due to switching to tests for 4.2 (Picked up Friday end of day and we started testing on Monday).
