### ISSUE TITLE
Fix flaky b2b-order-approval e2e test

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14130]

**Comment by Matejk00** [comment]
After investigation I think those e2e's are not flaky, they are passing all the time and I was not able to reproduce following errors:
https://dashboard.cypress.io/projects/k3nmep/analytics/top-failures/e6d6824d-b3b4-824c-af82-9a1cacba987e-cf0d2e95-d448-dc2e-70aa-828c5026a3dc?branches=%5B%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22b2b%2Forder-approval%2Fb2b-order-approval.e2e-spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22c7b73f04-f889-7fe7-cfa9-dc37466e38eb%22%7D%2C%7B%22label%22%3A%22b2b%2Fregression%2Forder-approval%2Fb2b-order-approval.e2e-spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22e6d6824d-b3b4-824c-af82-9a1cacba987e%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222021-09-01%22%2C%22endDate%22%3A%222021-11-16%22%7D&viewBy=TEST_CASE

Possible reason of those failings is temporary no response from CI server or some manual change in sample data. In my opinion we can close this ticket, and back to this e2e scenarios if failings appear in the future.
