### ISSUE TITLE
Fix flaky wishlist e2e test

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14131]

**Comment by bgambocjaviniar** [comment]
re-opening as test is still flaky from develop commit checks

https://dashboard.cypress.io/projects/k3nmep/runs/25323/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&utm_source=github

https://dashboard.cypress.io/projects/k3nmep/runs/25297/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&utm_source=github

**Comment by BenjaminEmiliani** [comment]
Noticed it too, will modify it and make a PR.

**Comment by BenjaminEmiliani** [comment]
Current work in process: make specs of wish-list agnostic and independent from one to another.
