### ISSUE TITLE
Empty Order History after placing order [order lib issue]

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#14177]
**Describe the bug**
The order history List is empty after placing an order. 

Current Result: on http://spartacus-devci7674.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
<img width="1158" alt="Screen Shot 2021-11-01 at 9 49 01 AM" src="https://user-images.githubusercontent.com/15215400/139694015-df42fa0c-9998-4150-a1b4-cdb7c5fc9f90.png">

Expected: show the placed order in the history after some time. 

**Tell us the version of Spartacus**
- Library version: 4.2.rc0 smoke testing 

**To Reproduce**
1. Go to b2c site http://spartacus-devci7674.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
2. Create a new account
3. Place an order 
3. Go to order history: My Account > Order History
4. Placed order does not show up in history.

**Desktop (please complete the following information):**
 - OS: Macbook
 - Browser: Chrome
 - Version:  latest

**Comment by Xymmer** [comment]
not seen in 4.1

**Comment by giancorderoortiz** [comment]
Same issue observed with different backends. 
cx 2011 --> http://spartacus-devci767.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/
cx 2105 --> https://spartacus-devci7674.eastus.cloudapp.azure.com:4201/electronics-spa/en/USD

**Comment by giancorderoortiz** [comment]
Call to "occ/v2/electronics-spa/users/current/orders?pageSize=5&lang=en&curr=USD" is not being made. 
See demo server: 
![Screen Shot 2021-11-02 at 10 16 49 AM](https://user-images.githubusercontent.com/46171897/139864997-9bf1796d-9582-49f3-91fa-bd5589453f51.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-11-02 at 10 16 41 AM](https://user-images.githubusercontent.com/46171897/139865543-c7bb7f42-954e-4153-b71c-ac5b4631f362.png)

**Comment by giancorderoortiz** [comment]
Order in fact being placed. See backoffice:

![Screen Shot 2021-11-02 at 11 05 57 AM](https://user-images.githubusercontent.com/46171897/139873863-d8575eff-0a7a-4ef9-8659-db0fea4de6ab.png)

**Comment by plabadie** [comment]
For now, it looks like the order lib is simply not installed on the server used for the test.

**Comment by plabadie** [comment]
Issue fixed in the schematics.  Need to re-install the app on the test server with the installer to fix the issue.

Need to test the installation on Windows as well.  This ticket covers that: #14241

**Comment by giancorderoortiz** [comment]
Issue fixed.
