### ISSUE TITLE
After closing the Zoom dialog the focus doesn't return to the triggering button

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#14186]
**Describe the bug**
When using keyboard-only navigation to open the Zoom dialog, and then closing it, the focus does not return to the "Expand image" button that triggered the event. Focus parks somewhere in-between buttons. From that parking spot, the user can tab backwards and get back to the triggering button. 

**Tell us the version of Spartacus**
- Library version: 4.2.RC0

**To Reproduce**
1. Go to the "Expand Image" button using the keyboard
2. Hit Enter or Spacebar to open the Zoom dialog.
3. Hit Enter or Spacebar again to close the Zoom dialog.
4. Focus ring disappears and goes to a place between the "Expand image" and the "Show reviews" buttons.
5. After closing the Zoom dialog Tabbing-back gets the user back to the "Expand image" button.
6. After closing the Zoom dialog Tabbing-forward gets the user forward to the "Show reviews" button.

**Expected behavior**
- Focus should go back to the "Expand Image" button when closing the dialog. Similar to how the Add to Cart button works after closing the dialog.

**Screenshots**
![focus-entry](https://user-images.githubusercontent.com/15113219/139734599-f9175de0-e49b-4509-af55-6d681811cde7.jpg)
![focus-exit](https://user-images.githubusercontent.com/15113219/139734626-8a7237a6-bd2b-4c40-95ec-2ec1316abad0.jpg)

**Comment by giancorderoortiz** [comment]
I see a fix with 4.2.0 release build.
