### ISSUE TITLE
Hamburger menu item that is not a dropdown acts like a dropdown

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#14191]
**Describe the bug**
When on the hamburger menu, mobile/desktop/etc, the menu item without a 'caret' is acting as a dropdown menu when already on the page. For example, when on the category page for 'camcorder', try to go to 'camcorder' again, and it will act as a dropdown, where we can go back.

**To Reproduce**
1. Using the hamburger menu, go to camcorder
2. open hamburger menu again, and click camcorder again
3. it should not 'open' the camcorder dropdown menu as there's no subcategories for it
4. see video

**Expected behavior**
Should close hamburger menu after clicking camcorder again

**Screenshots/Videos**

https://user-images.githubusercontent.com/29099466/139853237-fb0dcc1f-229b-42ab-ac57-c01dece6b528.MP4

**Comment by BenjaminEmiliani** [comment]
fixed by #14719?

**Comment by BenjaminEmiliani** [comment]
Closing issue, solved in #14422
