### ISSUE TITLE
Scroll position restoration with intermittent back to top restoration on page routes for iOS

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#14206]
**Describe the bug**
On iphone using chrome, when we click a hamburger menu item, and click the last product on the product listing page, it sometimes does not go back to the top. (no browser controls)

**To Reproduce**
1. Go to hamburger menu and click any category
2. scroll to the last product and click it
3. See pdp scroll restoration not going back to the top

**Expected behavior**
For any navigation (click to other routes / pages), it should always go back to the top of the page

**Comment by giancorderoortiz** [comment]
Retest successful with iphone 12. CCV2 deployment.
