### ISSUE TITLE
Import to saved cart creates a saved cart even when there's no valid products added

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#14228]
**Describe the bug**
Using the import to cart feature in saved cart, we're able to create a saved cart by trying to import an invalid product to the saved cart list.

**To Reproduce**
1. Login and head to saved carts under the my-account dropdown menu
2. use a csv file with an invalid product for the catalog. Ex: trying to import products that is b2c in b2b, vice-versa
3. See created 'empty saved cart'

**Expected behavior**
Should not create an empty saved cart as when you visit the details page of that empty cart, it will try and delete it.

**Screenshots**
![IMG_0155](https://user-images.githubusercontent.com/29099466/140184233-14ce1217-60c6-4f69-baed-723d26939675.png)

**Comment by Xymmer** [comment]
suggestion is to check saved cart after import if product count > 0, if not then don't save the cart; should delete it also so it's not hanging around.
