### ISSUE TITLE
[as designed?] Accessibility: Unselected shipping method is skipped through tabbing

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14221]
**Environment Details**
Browser: Chrome 
Device: mac
Frontend: release/4.2.x branch on https://spartacus-devci7674.eastus.cloudapp.azure.com:4201/electronics-spa/en/USD/
Backend: 2105.1 

**Steps to Reproduce**
Go to electronics storefront
Login, add product to cart, proceed to checkout
On the shipping method checkout page, tab through the shipping methods

**Actual Result:**
It skips the 2nd option of shipping method. You need to reverse tab if you want to select it.

**Comment by psmul** [comment]
Actually, it's not a bug, but how things work. For browser engine, radio group is considered single control element, thus we are forced to navigate with arrows inside radio group. As a reference: 
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/radio_role#keyboard_interactions

**Comment by developpeurweb** [comment]
Correct, as @psmul said.
There is table of **Common Keyboard Interactions** in our documentation for future reference: 
https://sap.github.io/spartacus-docs/a11y-best-practices/#common-keyboard-interactions

**Comment by KateChuen** [comment]
Closing as functions as designed.
