### ISSUE TITLE
Test the Spartacus installation with schematics on Windows

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#14241]
The fix to #14177 used a path separator to solve an issue with the schematics installer.

We need to make sure this works well on Windows (who uses a different path sepatrator).

One way to test it is to use the installer:
- cd in `scripts/install`
- Change the branch config in `config.defaut.sh` for `BRANCH='release/4.2.x'`
- launch: `./run.sh install

Some things to help validate the fix:
- make sure the files in `apps/csr/src/app/spartacus` are properly generated.
- you can start the CSR app to make sure is runs

**Comment by Zeyber** [comment]
Installed and ran on windows machine in CSR mode. OCC directory takes the absolute path of the machine which needs to be corrected before starting. This has been an issue with the installer for some time though and works fine after correcting.
![image](https://user-images.githubusercontent.com/11735817/140528366-46c089c9-a717-49fd-8ab4-63121ccaedac.png)
