### ISSUE TITLE
Unable to Deploy CPQ with Installation Script

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14243]
**Steps to Reproduce:**

1. Deploy Spartacus in localhost. 
2. Use branch release/4.2.0-rc.0
3. In config file, set CPQ flag as true.  (Leave all other flags as false)
4. Do ./install.sh install
5. Do ./install.sh start
6. Open Spartacus in localhost. http://localhost:4200/electronics-spa/en/USD/
7. Register an user. 
8. Login with newly registered user. 

**Expected Results:** 
8. User is logged in. 

**Actual Results:**
8. User doesn't login. OrgUsers API used erroneously as if it were a b2b deployment

---

Request: 
URL: https://40.76.109.9:9002/occ/v2/electronics-spa/orgUsers/current?lang=en&curr=USD

Response: 
`{
   "errors" : [ {
      "message" : "It's not allowed to execute this call from the current channel",
      "type" : "AccessDeniedError"
   } ]
}
`

---

<img width="1861" alt="Screen Shot 2021-11-04 at 11 30 35 AM" src="https://user-images.githubusercontent.com/46171897/140364067-f221aad6-0d0e-43a5-87f3-9aeca8940e3d.png">
<img width="1856" alt="Screen Shot 2021-11-04 at 11 30 44 AM" src="https://user-images.githubusercontent.com/46171897/140364112-6e8770fc-7f5b-4453-8f55-4c532dbbd066.png">

**Comment by giancorderoortiz** [comment]
@Larisa-Staroverova @ChristophHi fyi.

**Comment by ChristophHi** [comment]
@giancorderoortiz CPQ enforces B2B, so that's expected. (That's not true for other configurators like VC and textfield, they allow B2C and B2B)

**Comment by giancorderoortiz** [comment]
Closing per comments above. 
@KateChuen fyi
