### ISSUE TITLE
Test non-lib order features

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#14245]
By default, apps upgrading to 4.2 will all use the legacy non-lib order feature code.
( order history, cancellations and returns, replenishment orders )

The order lib is a non backwards compatible opt-in option for existing apps and the default for apps generated with spartacus 4.2.

To test non-lib order code, one way is to generate a 4.1 app and upgrade it to 4.2.
The other way its too generate a new app with 4.2 and switch it back to legacy order code.  To do this, you need to change imports in the file `projects/storefrontapp/src/app/spartacus/spartacus-features.module.ts`. (you essentially have to revert [these changes](https://github.com/SAP/spartacus/commit/7092d564427d2b832336d0d16dff6799725a3839#diff-dc9f4f7a653227b897e7c4c7596438465e65b13c75ea028c508147f84db3225a))

...which means you need to:

1) Remove these imports that use the order lib code:
- UserOccTransitional_4_2_Module (@spartacus/core)
- UserTransitional_4_2_Module (@spartacus/core)
- OrderFeatureModule (./features/order-feature.module)

2) Add back the old non-lib feature module code
- UserOccTransitionalModule (@spartacus/core)
- UserTransitionalModule (@spartacus/core)
- OrderCancellationModule (@spartacus/storefront)
- OrderDetailsModule (@spartacus/storefront)
- OrderHistoryModule (@spartacus/storefront)
- OrderReturnModule (@spartacus/storefront)
- ReplenishmentOrderDetailsModule (@spartacus/storefront)
- ReplenishmentOrderHistoryModule (@spartacus/storefront)
- ReturnRequestDetailModule (@spartacus/storefront)
- ReturnRequestListModule (@spartacus/storefront)

3) re-build

**Comment by giancorderoortiz** [comment]
Testing with yarn will suffice here? Or Schematics will need to be tested as well?

**Comment by KateChuen** [comment]
Gil recommends installing a shell app locally, then install 4.1 via schematics. Then I upgraded to 4.2 using yarn as per Patrick's instruction.

**Comment by KateChuen** [comment]
Steps to install:
`ng new <appname> --style=scss --routing false`
`cd <appname>`
`ng add @spartacus/schematics@4.1 --baseUrl https://20.84.65.98:9002 --baseSite=electronics-spa`
`yarn start`

Make sure it starts and loads fine. If that's ok, we proceed to upgrading. 
`vi package.json`
Change all versions of @spartacus to 4.2
`rm -rf node_modules`
`yarn install`
`yarn start`

**Comment by KateChuen** [comment]
Tested locally, pointing to devci4 backend (2105).
- tested. b2c: order history, quick order, cancel/return
- tested b2b: order history, quick order, replenishment order
All good.

**Comment by giancorderoortiz** [comment]
Before: 
<img width="870" alt="before" src="https://user-images.githubusercontent.com/46171897/141208304-5e1040fe-da5c-4ea5-9f3b-51f93b8b2918.png">

After:
<img width="532" alt="after" src="https://user-images.githubusercontent.com/46171897/141208336-f442a551-c29e-413c-b57f-e8d46395395c.png">

Orders Placed: 
<img width="1236" alt="orders_placed" src="https://user-images.githubusercontent.com/46171897/141208341-a8476f7d-f394-4bb7-b6ec-e42ebf6123a4.png">

**Comment by giancorderoortiz** [comment]
Upgrade procedure detailed by Kate yields positive results
