### ISSUE TITLE
Return History link from My Account menu leads to a 404

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#14257]
**Describe the bug**
Return History link from My Account menu leads to a 404. It's supposed to go to order history view with the returns tab open. 

**Tell us the version of Spartacus**
- Library version: 4.2 latest Pre-RC 

**To Reproduce**
1. Go to https://spartacus-devci7674.eastus.cloudapp.azure.com:4201/electronics-spa/en/USD/
2. Create a new account or login 
3. Go to My Account > Return History
4. See 404 page renders instead of return history 

**Expected behavior**
The link should navigate to return history view 

**Screenshots**
<img width="700" alt="Screen Shot 2021-11-05 at 10 33 27 AM" src="https://user-images.githubusercontent.com/15215400/140537966-547ccd8e-bf37-41f6-a124-ec2f097b890f.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome Latest 

**Additional context**
There is no Return history link in `4.1.x`

**Comment by bgambocjaviniar** [comment]
duplicate https://github.com/SAP/spartacus/issues/14189
