### ISSUE TITLE
Add Checkout Functionality to ASM Tests

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14260]
Current ASM e2e tests do not cover checkout. 

Manual tests failed to catch issues with checking out and ASM agent's user account emulation. 
Significant improvements are needed in test coverage. 

See bug: 
https://github.com/SAP/spartacus/issues/11361

Request: 

1. Add happy path checkout to ASM & B2C user, and ASM & B2B user.

**Comment by giancorderoortiz** [comment]
@KateChuen @plabadie

**Comment by giancorderoortiz** [comment]
Test: spartacus/projects/storefrontapp-e2e-cypress/cypress/integration/regression/asm.flaky-e2e-spec.ts

**Comment by plabadie** [comment]
Just a bit of context:
The shared checkout e2e logic was flaky.  What happened is that the whole ASM test was disabled as flaky because of that.  To improve ASM coverage, we removed the checkout from ASM so we could enable the rest of ASM coverage.

**Comment by Xymmer** [comment]
Closing, moved to internal jira
