### ISSUE TITLE
Flaky test regression/product-configurator-textfield-cart.flaky-e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#14274]
https://github.com/SAP/spartacus/blob/29b4bc71e8f27677c67ef4095ebb309b0de9e7b1/projects/storefrontapp-e2e-cypress/cypress/integration/regression/product-configurator-textfield-cart.flaky-e2e-spec.ts#L3-L7

See https://cxjira.sap.com/browse/TIGER-7252

**Comment by ChristophHi** [comment]
The underlying OCC API's will only be released in 22.05, so we can run this test only on our time pipeline at this point. The above comment is wrong, I will fix it

**Comment by KateChuen** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-258
