### ISSUE TITLE
Cart main feature chunk is broken.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#14276]
Issue from branch `feature/GH-14172` on PR #14246

There should be a little over 300kB of lazy loaded chunks for the cart main feature.  We have much less than that.

```
default-feature-libs_cart_main_occ_public_api_ts.js                  | -                    |   39.33 kB
feature-libs_cart_main_public_api_ts.js                              | -                    |    3.44 kB
```

**Comment by WeizhengSap** [comment]
`feature-libs_cart_main_public_api_ts.js` is still empty, but we have default files for components, core, and occ. The `main.js` size is reduced.
