### ISSUE TITLE
4.2 forVersion styles are being overwritten

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#14279]
With the style version flag set to 4.2 the forVersion mixin styles are being overwritten. 

![Screen Shot 2021-11-08 at 12 35 30 PM](https://user-images.githubusercontent.com/2947470/140795846-923edfaa-e72a-4867-a8bf-b323d62721b4.png)

**Comment by Xymmer** [comment]
this issue blocks release unless we decide it doesn't and will fix in 4.2.1.

**Comment by morganm58** [comment]
@developpeurweb  found the solution. I'll updating the mixins.
