### ISSUE TITLE
Whitesource scan - npm.accessToken is not defined

### ISSUE THREAD

**Issue by SarathchandrachDel** [SAP/spartacus#14278]
Security team is using Whitesource scan to give clearance to the project.[OOTBwhitesource.0.log](https://github.com/SAP/spartacus/files/7498671/OOTBwhitesource.0.log)
**Tell us the version of Spartacus**
- Library version: 1.4.0-next.1

**To Reproduce**
It is internal Whitesource configuration provided by Deloitte

**Expected behavior**
We are expecting not to see any error like "npm.accessToken is not defined" or way to suppress these kind of issues.

**Screenshots**
Will provide white source scan log in the attachments

**Desktop (please complete the following information):**
- NA

**Smartphone (please complete the following information):**
  NA
**Additional context**
Need clearance from or provide if spartacus had any white source scan log for reference.

**Comment by Xymmer** [comment]
Hi we don't have white source scan logs to share.
Also to mention the library is "next.1" which is not an official release.
