### ISSUE TITLE
Alignment Error. Cents in New Line. Cart Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14291]
See image: 
![alignment-error-ccv2-cart](https://user-images.githubusercontent.com/46171897/140924088-16758f9d-3f82-44c8-b78f-dd7825f6d8c4.png)

**Comment by giancorderoortiz** [comment]
Visible in CCV2 with 4.2

**Comment by BenjaminEmiliani** [comment]
Currently a work in progress by @developpeurweb and should be fixed in ticket, #7312

**Comment by dydome** [comment]
The problem does not exist anymore. Ticket to close. Tested on latest develop branch.
