### ISSUE TITLE
Possible flakiness in Cart Import/Export e2e tests

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#14327]
https://dashboard.cypress.io/projects/k3nmep/analytics/top-failures?branches=%5B%7B%22label%22%3A%22develop%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%22develop%22%7D%5D&browsers=%5B%5D&chartRangeMostCommonErrors=%5B%5D&chartRangeSlowestTests=%5B%5D&chartRangeTopFailures=%5B%5D&committers=%5B%5D&cypressVersions=%5B%5D&flaky=%5B%5D&operatingSystems=%5B%5D&runGroups=%5B%5D&specFiles=%5B%7B%22label%22%3A%22regression%2Fcart-import-export.e2e-spec.ts%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%220bcda4a3-023f-4a8a-739f-eefa57925cbc%22%7D%5D&status=%5B%7B%22label%22%3A%22Passed%22%2C%22value%22%3A%22PASSED%22%7D%2C%7B%22label%22%3A%22Failed%22%2C%22value%22%3A%22FAILED%22%7D%5D&tags=%5B%5D&timeInterval=WEEK&timeRange=%7B%22startDate%22%3A%222021-10-16%22%2C%22endDate%22%3A%222021-11-15%22%7D&viewBy=TEST_CASE

**Comment by hackergil** [comment]
This test is failing frequently in `develop` branch, see

https://dashboard.cypress.io/projects/k3nmep/runs/27135
https://dashboard.cypress.io/projects/k3nmep/runs/27133

**Comment by RadhepS** [comment]
Will fix issues with branch if there are any and get someone to review it so we can merge it asap

> This test is failing frequently in `develop` branch, see
> 
> https://dashboard.cypress.io/projects/k3nmep/runs/27135 https://dashboard.cypress.io/projects/k3nmep/runs/27133

**Comment by giancorderoortiz** [comment]
Cart import/export flakiness:

![Screen Shot 2022-01-18 at 11 03 49 AM](https://user-images.githubusercontent.com/46171897/149973564-e6b03eeb-8ec8-4f89-ac23-059b3de09535.png)

**Comment by giancorderoortiz** [comment]
Failures:
![Screen Shot 2022-01-18 at 11 06 47 AM](https://user-images.githubusercontent.com/46171897/149974274-2718ca9b-adbb-42b8-9959-e06ec2f6532b.png)
