### ISSUE TITLE
URLs are not configurable in the stock-notification feature

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#14343]
Let's use configurable routes instead of hardcoded strings here:
https://github.com/SAP/spartacus/blob/ef39ddc3237b0ebfb829f1d6171ee1cd739d1687/projects/storefrontlib/cms-components/product/stock-notification/stock-notification.component.html#L30
https://github.com/SAP/spartacus/blob/ef39ddc3237b0ebfb829f1d6171ee1cd739d1687/projects/storefrontlib/cms-components/product/stock-notification/stock-notification-dialog/stock-notification-dialog.component.html#L40
https://github.com/SAP/spartacus/blob/ef39ddc3237b0ebfb829f1d6171ee1cd739d1687/projects/storefrontlib/cms-components/product/stock-notification/stock-notification-dialog/stock-notification-dialog.component.html#L61

**Comment by KateChuen** [comment]
Tested on develop branch. 
Verified that when a product is oos, I get redirected to the notification preference page when I click on "notification channel" link, from both the pdp page and on the notify me dialog. 
And I can also get redirected to "My interests" page when I click on "My Interests" link from the "notify me" dialog.
