### ISSUE TITLE
Transfer state of Queries

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#14358]
We have a mechanism for transferring SSR state to the CSR app, based on the branches of the NgRx  state. This helps the performance.

The more we switch to Commands and Queries, the more we will need to transfer the state of those querie.

It would be good to provide

**Comment by Platonn** [comment]
moved to jira https://jira.tools.sap/browse/CXSPA-403

**Comment by artem-zur** [comment]
Hi there! We found the draft https://github.com/SAP/spartacus/pull/15739/ which was made some time ago in order to improve the above-described behavior. Any chance we can get some update on when it would be possible to expect this feature?
