### ISSUE TITLE
Cart Validation E2E Failures CI. CX 2105. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14378]
Cart validation e2e test passes in localhost, both interactive, and headless mode. 
However, it fails randomly with CX 2105. 

Test has been disabled to allow CI CX upgrade to proceed. 

See https://dashboard.cypress.io/projects/k3nmep/runs/24940

Backend URL:  https://20.84.65.98:9002 (cx 2105.1)

Investigation is required. 
![Screen Shot 2021-11-16 at 11 04 14 AM](https://user-images.githubusercontent.com/46171897/142511561-1e423f21-a6b7-4406-8e0f-6fa96e0511e7.png)
![Screen Shot 2021-11-16 at 11 10 50 AM](https://user-images.githubusercontent.com/46171897/142511562-bd614fa3-a1a0-45a9-8bce-feb64b90eab8.png)
![Screen Shot 2021-11-16 at 11 12 20 AM](https://user-images.githubusercontent.com/46171897/142511563-75f12aab-de6e-43c4-8f61-7bdee44c0152.png)

**Comment by Xymmer** [comment]
closing as a new version of e2e was implemented, this ticket no longer valid.
