### ISSUE TITLE
Create a Service for Dynamic Vocalized Feedback (SR improvement)

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14371]
Discussion with @saad-mo @developpeurweb led to the following proposition:

There are a few outstanding Screen Reader tickets in our aim for 5.0 that require inserting context dynamically for accessibility end users upon an action (place an order, cancel a deletion, etc).

**Issue**
The issue we are facing with such tickets is that when using Window's compatible assistive technologies, JAWS and NVDA, a dynamically added "live-region" (regions exposed to Screen Reader API to make it announce any changes within the region) will NOT be picked up by the API unless it is preloaded in the page and then the content changes.

For this reason, we had to insert the live-region for Global Messages where it is pre-loaded (storefront.component.html) instead of the dynamic component itself (`<div *ngIf="messages$ | async as messages">`). Link to this PR --> #13781.

**Suggestion**
To avoid using Global Messages every time we would like to add more Screen Reader context to specific use cases, we wonder if it would be possible to create a new service similar to Global Message in the sense that we can pre-load it with a live region in the main template and pass the desired message to be read by the Screen Reader. In this service we would not inject a banner as Global Message service does, but instead the message can be contained in a cx-visually-hidden div so no visual changes occur and then remove it after a delay.

Example of selector name: `cx-at-message` (at -> assistive technology)

This service would enable adding more context for visually impaired users much easier for current and future features.

We are open to further discussions and suggestions on this topic.

**Comment by KateChuen** [comment]
Please also tackle the issue mentioned about the payment details from ticket https://github.com/SAP/spartacus/issues/13676

`Payment Details page during checkout. If you input an invalid expiry date (in the past), it does not voice the error message.`

**Comment by KateChuen** [comment]
Tested on my local, using develop branch. 

Talked with Miguel, he said this is already in place, and one scenario to check this is to hear the message when we remove an item from cart.

Confirmed this action is vocalized:
<img width="920" alt="Screen Shot 2022-05-19 at 3 33 54 PM" src="https://user-images.githubusercontent.com/45409515/169388227-e9cfcd61-4cc8-47f4-ad29-6970d4e10555.png">
