### ISSUE TITLE
json-ld (structured data) is not working in SSR Spartacus installed via schematics [closed not an issue]

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#14380]
**Describe the bug**
The `<script>` with id `"json-ld"` doesn't appear in SSR Spartacus 4.2.0 installed via schematics

**Tell us the version of Spartacus**
- Library version: 4.2.0, but also 3.4.5 (so it's an old bug)

**To Reproduce**
1. Install default Spartacus 4.2.0 with Angular 12 via schematics with `--ssr` flag:
   - `npx @angular/cli@12 new test420`
   - `ng add @spartacus/schematics@4.2.0 --ssr --baseUrl="https://40.76.109.9:9002"`
2. Add at the top of `server.ts` file, the line: `process.env.NODE_TLS_REJECT_UNAUTHORIZED = '0';` (to mitigate SSL errors related to test backend)
2. Run `yarn build:ssr && yarn serve:ssr`
3. Run `curl http://localhost:4000/electronics-spa/en/USD/ > home.html`
4. Bug: check the created file on your disk `home.html` doesn't contain the script with the id `json-ld`

**Expected behavior**
- [ ] `home.html` contains contain the script with id `json-ld`. 
- [ ] double check it's working also for PDP and PLP:
`curl http://localhost:4000/electronics-spa/en/USD/product/358639/dsc-n1 > pdp.html`
`curl http://localhost:4000/electronics-spa/en/USD/Open-Catalogue/Cameras/Webcams/c/577 > plp.html`

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS Monterey
 - Browser: Chrome
 - Version 95.0.4638.69 (Official Build) (arm64)

**Additional context**
- docs for the feature: https://sap.github.io/spartacus-docs/structured-data/
- the customer says it has was working in Spartacus 2.0, but stopped working when upgraded to 3.4
- ✅ json-ld does work in **our repo** branch `release/4.2.x` in SSR prod mode
   - `yarn build:libs && yarn build && yarn build:ssr && yarn serve:ssr:dev`
   - `curl http://localhost:4000/electronics-spa/en/USD/ > home.html`)
   - <img width="697" alt="image" src="https://user-images.githubusercontent.com/4001059/142610770-7fe6cbe6-974f-4d7b-8f5f-099b38097f83.png">
- ✅ json-ld does work in **our repo** branch `release/4.2.x` in CSR dev mode (yarn start) with config  `seo: { structuredData: { disableInDevMode: false } }`. 
    <img width="467" alt="image" src="https://user-images.githubusercontent.com/4001059/142591961-a63114ba-99b7-4ed2-b308-9605fd530c0c.png">   
- ❌  json-ld doesn't work in Spartacus 4.2.0 **installed via schematics** in CSR dev mode (yarn start) with config `seo: { structuredData: { disableInDevMode: false } }` . 
   <img width="447" alt="image" src="https://user-images.githubusercontent.com/4001059/142609035-2d91279a-c419-49a9-9260-32b8744b7db3.png">
- **I suspect there might be something different between our repo's storefrontapp and the app installed via schematics - that causes json-ld not working in a schematics-generated app**
- How to debug: Check if the feature module of the json-ld feature is even imported in the app - directly or indirectly (imported by other higher order module). If not - that the cause of the problem. If yes - then extend the classes/services related to the json-ld feature, and see if their crucial methods are even executed.  

**Reference:**

To install **3.4.5 with Angular 10**:
- `npx @angular/cli@10 new test345`
- `ng add @spartacus/schematics@3.4.5 --ssr --baseUrl="https://40.76.109.9:9002"`

**Comment by znikola** [comment]
Just by importing the `JsonLdBuilderModule` the "problem" goes away - I verified that home, pdp and plp pages indeed have the `json-ld` tag:

![Screenshot 2021-11-19 at 14 10 36](https://user-images.githubusercontent.com/11561723/142628195-22a8572c-248a-4009-a2de-49b87a9218ff.png)
![Screenshot 2021-11-19 at 14 10 45](https://user-images.githubusercontent.com/11561723/142628204-e3441c34-9282-4212-979a-1d44aa82602a.png)
![Screenshot 2021-11-19 at 14 10 57](https://user-images.githubusercontent.com/11561723/142628206-e356e3e5-96ab-49f7-b037-8335b91ec33e.png)


I'll double check with the client.

**Comment by Xymmer** [comment]
closing but checking with nik
