### ISSUE TITLE
Get checkout details only when checkout-related actions are not loading

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#14396]
In `CheckoutDetailsService`, there `loadCheckoutDetails`. We need to check whether the "set delivery address" or "set delivery mode" or "set payment details" is running. `loadCheckoutDetails` only can be run when the loading flags of these processes are `false`.

**Comment by Xymmer** [comment]
No workaround possible for this, but we will provide a fix for 4.2 and try to backport to 3.4 (seems likely we can)
