### ISSUE TITLE
Fake Test Impact Analysis Reorg

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14437]
In order to reduce execution times of e2e tests in pipeline: 
1. For each functionality, reorg tests into core and supplemental tests. 
2. Execute only core tests per PR or branch. 
3. Execute both core and supplemental tests within a 24 hour period. 

Goals: 
1. Test execution in pipeline: 10 minutes.  (Current is 30 min + 2-3 retries because of flakyness)

Pending discussion: 
1. Failure analysis. 
2. Roll back strategy. 
3. Who fixes what when?

**Comment by giancorderoortiz** [comment]
Branch: 
https://github.com/SAP/spartacus/tree/feature/GH-14437_fake_test_impact_analysis

**Comment by giancorderoortiz** [comment]
Improve cart coupons test for perf purposes: 
https://github.com/SAP/spartacus/issues/14500

**Comment by giancorderoortiz** [comment]
Green run here: 
https://dashboard.cypress.io/projects/k3nmep/runs/26010/specs

**Comment by giancorderoortiz** [comment]
Significant reductions in execution time here: 

<img width="1517" alt="Screen Shot 2021-12-06 at 3 06 41 PM" src="https://user-images.githubusercontent.com/46171897/144914851-6fc15dcb-0fc8-4083-a754-53aa17152b34.png">
<img width="1529" alt="Screen Shot 2021-12-06 at 3 06 54 PM" src="https://user-images.githubusercontent.com/46171897/144914855-36f70eb2-dd93-49a3-9ab7-d3406478ee24.png">

**Comment by giancorderoortiz** [comment]
Before: 
As an example, take: https://dashboard.cypress.io/projects/k3nmep/runs/26011/specs

B2B
- Test specs: 17. 
- Machines 1. 
- E2E tests: 220. 
- Duration: 19.24m

B2C
- Test Specs: 70. 
- Machines: 4
- E2E tests: 450. 
- Duration: 14:38m

---
After (execution of only core tests) 
Example: https://dashboard.cypress.io/projects/k3nmep/runs/26010/specs
B2B
- Test specs: 15. 
- Machines 2. 
- E2E tests: 107. 
- Duration: 4:55m

B2C
- Test Specs: 69. 
- Machines: 5
- E2E tests: 295. 
- Duration: 5:55m

**Comment by giancorderoortiz** [comment]
@KateChuen afaik I have kept same functionality coverage.

**Comment by KateChuen** [comment]
Looks good. Good time execution. 
Point 1 & point 2 OK. ✅
Point 3: as mentioned by the team (and I like the idea) 🔆
- Run _all_ tests (core + supplemental) every time we merge to develop

Plus I would add: 
- run all tests (core + supplemental) twice a day. Just to make sure that if something breaks, we catch it quickly. (which maybe won't be needed if we run all tests when we merge to develop, we'll catch if something is broken right away.
