### ISSUE TITLE
Adjust styling for numeric input field

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#14442]
Clarify how the error message should be styled.

At the moment it looks the following way:
![image](https://user-images.githubusercontent.com/61147963/143422259-3affcae4-ab1a-45f9-91d8-ae18e38493b0.png)

**Comment by schuppell** [comment]
<img width="418" alt="Screen Shot 2021-11-25 at 11 23 09" src="https://user-images.githubusercontent.com/51401884/143424225-4655e0c7-84d1-4f59-9e92-89b58489eb2a.png">
Error Message should be below input field
