### ISSUE TITLE
Improve narration for search boxes

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14467]
**Describe the bug**
 The combination of the placeholder and aria-label on the search inputs lead to a confusing narration for Main search, quick-order and find a store.

**Tell us the version of Spartacus**
- Library version: 4.2

**To Reproduce**
1. Turn on a Screen Reader (VO, JAWS, NVDA)
2. Click on the main search input
3. Observe narration and repeat with search input in 'Quick Order' and 'Find a Store'

**Expected behavior**
A clear and concise narration of the search element across all three components for visually impaired users. Consult with designers, @Manurod2018 and @vekterdude, for their recommendations on narration.

**Screenshots**
![](https://user-images.githubusercontent.com/15215400/138715119-d4b0885a-fdf0-48c8-bb91-682ac56b5467.png)

To Do - improve narration for:
- [x] Main Search
- [x] Quick Order
- [x] Find a Store

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.


<img width="1288" alt="Screen Shot 2022-04-04 at 11 28 41 AM" src="https://user-images.githubusercontent.com/45409515/161581804-e27dad0a-671c-473f-8666-456c7e5668fc.png">

<img width="1142" alt="Screen Shot 2022-04-04 at 11 23 22 AM" src="https://user-images.githubusercontent.com/45409515/161581853-37175c20-ac83-417b-af31-5fb84766da3b.png">

<img width="1146" alt="Screen Shot 2022-04-04 at 11 19 40 AM" src="https://user-images.githubusercontent.com/45409515/161581910-343325de-e9f2-4b41-a60c-b3a91e17d8e6.png">
