### ISSUE TITLE
Angular schematic to generate files/boilerplate code for migration schematics

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14487]
### Suggestion:

Create an angular schematic that auto-generates the files needed for a new migration schematic along with the default code that is needed / shared across all migration files.

### Discussion:

Is this needed? How many files are required for a migration schematic of a single component?

**Comment by psmul** [comment]
After some discussion around it with other devs, we find it to be overkill to create such mechanisms (and schematics implementation) to simply generate such a template file with few lines in it.
We already had one approach to dev-schematics in our project, but it didn't turn out so useful as we thought it would be. Creating such files is not a constant need in our project, but pretty periodic and rare.

**Comment by BenjaminEmiliani** [comment]
I agree, closing ticket based on discussion.
