### ISSUE TITLE
Cart Coupons Test. Add validation to Order Confirmation Page. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14500]
Coupon validation is being done in order details page which causes unnecessary delays.
Delays in CI pipeline observed. 
Instead, validate coupon right after order is placed in order confirmation page. 

File: coupons.e2e-spec.ts

**Comment by giancorderoortiz** [comment]
@KateChuen fyi

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-12-01 at 7 37 55 PM](https://user-images.githubusercontent.com/46171897/144336647-a2d11a8e-23dc-46ab-9994-e82ec0f2970f.png)

**Comment by giancorderoortiz** [comment]
@Xymmer, @hackergil can this be addressed for 5.0 release?

**Comment by szczepaniak-michal** [comment]
Work in progress by @pawelfras
