### ISSUE TITLE
OccProductSearchPageNormalizer not extensible

### ISSUE THREAD

**Issue by PascalAOMS** [SAP/spartacus#14508]
**Is your feature request related to a problem? Please describe.**
We want to extend the `OccProductSearchPageNormalizer` and realize once again that 75% of the methods are `private`.
Extensibility is therefore not given.

_Our use-case:_
In the product list page (PLP) we show products which have their own selectable variants on their detail pages.
The facets show the total number of variants and not the number of displayed base products on the PLP.
Hence as soon as there are multiple variants for a displayed product, the facettes disappear.

https://github.com/SAP/spartacus/blob/develop/projects/core/src/occ/adapters/product/converters/occ-product-search-page-normalizer.ts#L67
```js
value.count < target.pagination.totalResults
```
We need to change this to something like
```js
value.count < target.pagination.totalVariantResults
```

**Describe the solution you'd like**
Why is it so difficult to use  `protected` instead of `private` when developing a framework for so many differently nuanced use-cases?
Spartacus really seems to value its privacy. 🕵️‍♂️

**Describe alternatives you've considered**
Can't really rage-quit so I copy the whole file instead of a single method. 🎉

**Comment by Xymmer** [comment]
we probably want to make most methods protected but have a discussion with architects first

**Comment by KateChuen** [comment]
No QA required for this ticket.
