### ISSUE TITLE
Page title on login page is not updated when switching languages

### ISSUE THREAD

**Issue by ilona-sedova** [SAP/spartacus#14512]
**Describe the bug**

- Page title stays the same during switching between language selector values.

**Tell us the version of Spartacus**
- Library version: 3.3.0

**To Reproduce**
1. Go to login page
2. Select language other than English from language selector in the top left corner
3. Notice the page title not changing

**Expected behavior**

- Page title is changed depending on language selected from language selector.

**Screenshots**
![jYpX4rV](https://user-images.githubusercontent.com/78151678/144627409-150877fe-e09a-452d-8802-dfbdae9d05b9.png)

**Comment by Xymmer** [comment]
was fixed in 4.x, closing
