### ISSUE TITLE
Flaky b2b/regression/my-company/users.e2e-spec.ts

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14511]

**Comment by bgambocjaviniar** [comment]
👍 

I noticed as well. There was a merged fix for this flakiness that tackles my-company flakiness a while back.
https://github.com/SAP/spartacus/pull/14247

develop commit where it failed: https://dashboard.cypress.io/projects/k3nmep/runs/25827/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&utm_source=github


Error is similar to the flaky failed checks on that PR. I would avoid using static wait if possible and instead wait for an actual request response that is used to populate 'something'
