### ISSUE TITLE
Export button not aligned properly on order-confirmation page

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#14535]
When an order is placed, we can see the "export to CSV" button underneath the cart items on the order-confirmation page.
It is styled nicely for desktop resolution, but it appears to be misaligned on lower resolutions (see screen-shot):
![Screenshot 2021-12-06 at 11 19 48](https://user-images.githubusercontent.com/11561723/144829644-9e5fc7dc-5c5e-44dc-bf07-0ce0c2021348.png)

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

export button is aligned now.
<img width="459" alt="Screen Shot 2022-04-14 at 2 20 46 PM" src="https://user-images.githubusercontent.com/45409515/163454945-c474bb56-456c-47ca-babf-f8e79a5e4af3.png">

<img width="507" alt="Screen Shot 2022-04-14 at 2 10 31 PM" src="https://user-images.githubusercontent.com/45409515/163454952-23e77637-8766-44a1-a344-c3e7fd8f355a.png">

<img width="446" alt="Screen Shot 2022-04-14 at 2 10 12 PM" src="https://user-images.githubusercontent.com/45409515/163454956-ff2f00a3-84ad-4ff7-b8b9-4dc8cc80f339.png">

<img width="517" alt="Screen Shot 2022-04-14 at 2 09 56 PM" src="https://user-images.githubusercontent.com/45409515/163454957-af8d73e6-b636-452b-a6fb-8e3dd987eee9.png">
