### ISSUE TITLE
Styles in cart-lib not fully applied when was moved out of global styles

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#14599]
Currently, in any usage of item-counter in the cart-lib, the styling is not fully applied compared to what it was before

and cart order entry with the 'opacity' being like a readonly view

# OLD - develop

## 1
![Screen Shot 2021-12-13 at 3 13 37 AM](https://user-images.githubusercontent.com/29099466/145775664-5d4709de-826d-4e7d-b656-574a219c1f9e.png)
![Screen Shot 2021-12-13 at 3 13 43 AM](https://user-images.githubusercontent.com/29099466/145775686-6e2014d8-a2b4-4f8a-a570-ebd0d8ed44e6.png)

## 2
![Screen Shot 2021-12-13 at 3 22 27 AM](https://user-images.githubusercontent.com/29099466/145923056-61a162b8-50ff-4641-8fcb-5fd885c60620.png)

# NEW - cart-lib

## 1
![Screen Shot 2021-12-13 at 3 13 19 AM](https://user-images.githubusercontent.com/29099466/145775711-72e0ff5e-a0fe-44e0-85a2-a06515abf2ec.png)
![Screen Shot 2021-12-13 at 3 13 47 AM](https://user-images.githubusercontent.com/29099466/145775719-4efc9cd0-eb0a-4221-8eb5-0a1b97b7a84d.png)

## 2
![Screen Shot 2021-12-13 at 3 22 23 AM](https://user-images.githubusercontent.com/29099466/145923065-608ee4be-4799-42b9-85e2-4edde6689793.png)

**Comment by WeizhengSap** [comment]
I fix the `item-counter` one, for the cart order entry one, it is a bug in develop branch. Go to the checkout review step. In this step the items should be `readonly`, but it looks like this in develop branch. 
![Screen Shot 2021-12-14 at 5 31 17 PM](https://user-images.githubusercontent.com/44440575/146082549-763063d0-cb79-49f7-b305-30fc93ecccd7.png)
 
In function `createForm` of `CartItemListComponent`, there is code:
```
     if (!item.updateable || this.readonly) {
        this.form.controls[controlName].disable();
      }
```
but `createForm` is called in here. When it is called, the `@Input() readonly` may not be set yet. So, the default value of the `readonly` is used. 
```
@Input('items')
  set items(items: OrderEntry[]) {
    this.resolveItems(items);
    this.createForm();
  }
```
