### ISSUE TITLE
Fix refreshing of customized price

### ISSUE THREAD

**Issue by marek-sap** [SAP/spartacus#14604]
Refreshing of customized prices is not working in Spartacus.
I have created customized prices for products based on:
https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/2105/en-US/8c5af47f8669101488e59df61b2f6ab4.html
Then i assigned those customizations to my testing user.

In Spartacus storefront after login to my testing user, price didn't changed.
After refreshing the page, price changed to customized value.
Similar situation is for logout event => price is not changing after logout. I need to refresh the page to get default price.

It seems that login and logout events are not refreshing prices.

Steps to reproduce:
1. Create some customized prices based on: https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/2105/en-US/8c5af47f8669101488e59df61b2f6ab4.html
and assign them to customer (testing user).
2. Go to Spartacus storefront
3. Navigate to product for which you customized price. (You should see default price)
4. Login to you testing user (for which customized price should be applied)
5. After successful login product price still have default value (It should be changed after login)
6. Reload the page, now you should see customized price.

**Comment by Xymmer** [comment]
Anette is asking that this be backported to 4.x as well a fixed for 5.0
let's evaluate the work needed and where the problem lies so we can fit it in.
could be: too fast, spartacus using cache, or occ api returning cached value.

**Comment by WeizhengSap** [comment]
To QA:
1. enable b2b, choose one product from powertools (e.g. `3755219` which is also a product in carousel in homepage)
2. go to backoffice, create a new price row (set product to `3755219`, set customer to some b2b customer, and set Price to `10`)
![Screen Shot 2022-03-23 at 3 00 10 PM](https://user-images.githubusercontent.com/44440575/159765681-b884004f-272e-4f19-a773-215b38f069d4.png)
)
3. in Spartacus, check the price of product `3755219`. For login user, it is `10$`, for anonymous user, it is `48$`. (Check it in homepage, and pdp both)

**Comment by Xymmer** [comment]
to confirm, we are putting this in 5.0 and backporting to 4.x when approved

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn, pointing to dev7 backend.

- Verified that specific user (gi.sun) sees the customized price (18.18) both on pdp and homepage.
<img width="1177" alt="Screen Shot 2022-04-08 at 11 47 55 AM" src="https://user-images.githubusercontent.com/45409515/162494831-4c3a08b3-227b-4545-addc-5a1c46ea1275.png">
<img width="1122" alt="Screen Shot 2022-04-08 at 11 47 47 AM" src="https://user-images.githubusercontent.com/45409515/162494879-f8b9cd96-be62-4d0d-a796-c6d0ecc22e20.png">

- Verified that anonymous and other logged in users (mark.rivers) see the default price (48) both on pdp and homepage.
<img width="1129" alt="Screen Shot 2022-04-08 at 11 47 20 AM" src="https://user-images.githubusercontent.com/45409515/162494921-f6dc071b-20b6-4569-99c0-19af3bd9746e.png">
<img width="1207" alt="Screen Shot 2022-04-08 at 11 50 58 AM" src="https://user-images.githubusercontent.com/45409515/162494965-f89c0646-c88e-40bb-8fd7-f30e9434b092.png">

But I have one question @WeizhengSap 
- I know you mentioned only on homepage and pdp. So, on product listing page, the customized price is not reflected for the specific user. Normal?

**Comment by WeizhengSap** [comment]
@KateChuen: that's normal. The customized price doesn't applied in `search`.
