### ISSUE TITLE
SSO Example With Azure AD and Spartacus Session Management

### ISSUE THREAD

**Issue by huboo** [SAP/spartacus#14627]
Dear teams,

Could you please share an example of how to alter Session Management to integrate SSO, thank you.

We know Spartacus is an Angular based project and Azure AD provided a tutorial also done SSO base Angular, I was wondering could you please share some example or code snippets to integrate SSO with Spartacus.

Spartacus Session Management: https://sap.github.io/spartacus-docs/session-management/
Azure tutorial: https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-angular-auth-code
Angular example: https://github.com/Azure-Samples/ms-identity-javascript-angular-tutorial/tree/main/1-Authentication/2-sign-in-b2c

Regards,
Wayne

**Comment by Xymmer** [comment]
Hi, we don't have an example, best to contact SAP Commerce expert services
