### ISSUE TITLE
Move the placeOrder() logic from the checkout library to the order library

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#14649]
### What to do
We should move the logic of "placing the order" from the `checkout` lib to the `order` lib. This includes  the adapter, controller and the facade (and maybe something else too...).

### Reasons
During the cart lib's code splitting refactor, we discovered that `occCheckoutAdapter.placeOrder()` (in the lazy-loaded `checkout` lib) uses the `ORDER_NORMALIZER` token, which is provided only in the lazy loaded `order` lib. This unclear lib cross-dependendy causes a few problems:

- Now the action of "placing the order" in the last step of the checkout won't work if we don't lead the `order` lib "artificially" in advance.
- it feels natural to me to have the "placing the order" action in the Order domain lib. Although it's debatable whether it should belong to the checkout or the order domain, there are no known disadvantages of having it in the Order domain. But there are problems of having it in the Checkout domain.
- Having the "place order" in the core facade of the Order domain feels natural also from the OCC API point of view. The OCC endpoint for placing the order is a part of the [OCC Orders module](https://40.76.109.9:9002/occ/v2/swagger-ui.html#/Orders/placeOrder): `[POST] /{baseSiteId}/users/{userId}/order`.

### When to do
We should consider doing this ticket **ONLY AFTER** the ongoing refactors of the cart lib and the checkout lib are done (merged to develop in a releasable state). It's to to avoid unnecessary conflicts that could complicate and delay the ongoing cart and checkout lib refactors.

**Comment by bgambocjaviniar** [comment]
QA:

- checkout should behave similarly to what it was before

**Comment by KateChuen** [comment]
Tested on develop branch
B2C: 
- checkout as a registered user
- express checkout
- guest checkout

B2B:
- checkout using account payment
- checkout using card payment
- replenishment order
