### ISSUE TITLE
Consent is not detected when reloading page

### ISSUE THREAD

**Issue by nnamlaht** [SAP/spartacus#14648]
When adding a e2e test for fix #14480 (https://github.com/SAP/spartacus/pull/14561), we noticed different behaviour for different users: 
(1) with a newly registered user the fix #14480 works and reloading a page does not revoke consent. 
(2) testing with one of the provided test users (e.g. `test-user-with-orders@sap.cx.com`) the fix does not work and reloading a page still does not detect already granted consent.

It is reproducible in argonauts' e2e tests (projects/storefrontapp-e2e-cypress/cypress/integration/vendor/cds/profile-tag/default-events.e2e-spec.ts) and on a locally running spartacus instance (wired to https://40.76.109.9:9002).

Steps to reproduce:
(1)
- go to fresh http://localhost:4200/electronics-spa/en/USD/ 
- click 'Allow All' on consent banner
- register a new user
- sign in with the new user
- reload the page (eventlayer DOES contain ConsentChangedEvents)

(2)
- go to fresh http://localhost:4200/electronics-spa/en/USD/ 
- click 'Allow All' on consent banner
- sign in with one of the provided test users (e.g. `test-user-with-orders@sap.cx.com`)
- reload the page (eventlayer does NOT contain any ConsentChangedEvent anymore)

**Comment by znikola** [comment]
To me, this sounds like it works as expected, and seems like "Moving from Anonymous User to Logged In Customer" user flow - https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/2105/en-US/fbf047927e8845038581d49c22d37bc3.html.

In a nutshell, if an anonymous user gives their consent, and then logs in, the anonymous consents are ignored in favor of the registered user's consents.

Closing the issue, but we can discuss  and re-open if I misunderstood.
