### ISSUE TITLE
Breadcrumb misaligned with Page title

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#14651]
**Describe the bug**
Breadcrumb is not aligned with the page title. 

Current alignment.
![Screen Shot 2021-12-17 at 9 51 11 AM](https://user-images.githubusercontent.com/15215400/146571597-5a214966-4aed-4d03-ba8f-4280b1fe1a57.png)

Fixed alignment: 
![Screen Shot 2021-12-17 at 9 51 23 AM](https://user-images.githubusercontent.com/15215400/146571695-efe7afb0-cb45-431c-838d-f13abb8aab22.png)

Misalignment is caused by the change in markup with [this commmit](https://github.com/SAP/spartacus/commit/4c09b10ce989c238be5446892d5269abc80ed29a#diff-746451e140cb5dcdef9a9727360c6c738cc1082c243ebe5b268b964397397494L1). Fix is to simply set `padding-left:0` for the `ol` element.

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
Looks ok now. Verified on a few pages... 
<img width="418" alt="Screen Shot 2022-01-12 at 3 02 01 PM" src="https://user-images.githubusercontent.com/45409515/149215165-729efddc-b1d3-4500-bf46-2526e5581ba0.png">
<img width="408" alt="Screen Shot 2022-01-12 at 3 01 49 PM" src="https://user-images.githubusercontent.com/45409515/149215169-ab80f4f1-ce15-483a-b0a2-ee829e537814.png">
<img width="701" alt="Screen Shot 2022-01-12 at 3 01 37 PM" src="https://user-images.githubusercontent.com/45409515/149215170-8bf86838-b38d-4586-a048-f124e7b8a373.png">
<img width="715" alt="Screen Shot 2022-01-12 at 3 00 31 PM" src="https://user-images.githubusercontent.com/45409515/149215172-a1868c2b-68af-4607-a21f-c512132e7847.png">
<img width="551" alt="Screen Shot 2022-01-12 at 2 59 22 PM" src="https://user-images.githubusercontent.com/45409515/149215173-1420592d-5074-431c-b0ff-ef694df794fb.png">
<img width="479" alt="Screen Shot 2022-01-12 at 2 59 11 PM" src="https://user-images.githubusercontent.com/45409515/149215175-8b8066a7-8b0a-4caf-a059-3acccd07c9b9.png">
<img width="584" alt="Screen Shot 2022-01-12 at 2 58 57 PM" src="https://user-images.githubusercontent.com/45409515/149215177-de249809-8500-4d25-87e8-e0bc299c7b0d.png">
<img width="532" alt="Screen Shot 2022-01-12 at 2 58 48 PM" src="https://user-images.githubusercontent.com/45409515/149215178-a373b6e6-9a54-498a-b84c-fad2c4366e78.png">
