### ISSUE TITLE
Display unique customer ID on Personal Details Page

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#1467]
We are asked for integration reasons to display the unique customer ID on profile page.
We assumed it's "Customer ID" as seen in Backoffice.
Does OCC give us that info?

---
### Update 

Due to backend changes required to properly return 'customerID' as part of Order Detail payload, this ticket will only show Customer ID on the `Personal Details` page. 

Rest of changes will be covered in the new ticket - #8442

**Comment by plabadie** [comment]
OCC does provide a "customerId" field as part as the user details.  It doesn't look like something that we usually display though, it's a big uid.

```
  "customerId": "b9f5aa64-e6af-404b-8caf-561f8f444272",
```

**Comment by vekterdude** [comment]
Tablet Account Home: https://98qkkl.axshare.com/#g=1&p=t_account_home 
Tablet Order Details Header: https://98qkkl.axshare.com/#g=1&p=t_order_history_details 
Tablet Returns History: https://98qkkl.axshare.com/#g=1&p=t_return_complete_order 
Tablet Order Confirmation: https://98qkkl.axshare.com/#g=1&p=t_order_confirmation_1

**Comment by Xymmer** [comment]
required for a 1908 release (Charles B)

**Comment by Xymmer** [comment]
Deadline for this is 1908 C3P
We'll do it in June.

We'll add it to all locations that display order details: order confirmation, order details
There is no Account Home, so we'll add it to email and names page.
When we do returns, we'll add it there too.

When done let me know I will notify Charles.

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/spartacus/pull/8443#issuecomment-673547498

As mentioned, this will be done only when 3.0 branch is available

**Comment by giancorderoortiz** [comment]
Test successful 

![Screen Shot 2020-11-02 at 11 05 19 AM](https://user-images.githubusercontent.com/46171897/97972492-98bebd80-1d92-11eb-966b-6e0652afee75.png)
![Screen Shot 2020-11-02 at 11 05 49 AM](https://user-images.githubusercontent.com/46171897/97972494-98bebd80-1d92-11eb-8c9f-2ec66faf5930.png)
![Screen Shot 2020-11-02 at 11 06 40 AM](https://user-images.githubusercontent.com/46171897/97972496-99575400-1d92-11eb-8d26-1d01bb66fe65.png)
![Screen Shot 2020-11-02 at 11 07 00 AM](https://user-images.githubusercontent.com/46171897/97972498-99575400-1d92-11eb-80ef-70e3957bba78.png)
![Screen Shot 2020-11-02 at 11 09 00 AM](https://user-images.githubusercontent.com/46171897/97972499-99575400-1d92-11eb-972c-bf93b31d8006.png)

**Comment by giancorderoortiz** [comment]
May need documentation?
