### ISSUE TITLE
AMP: Contrast issues (Severity 4)

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#14685]
Severity 4

There are several issues wrt contrast.

AMP-Note (example): "This SPAN contains text with a background color of #f4f4f4 rgb(244, 244, 244) and foreground color of #747881 rgb(116, 120, 129) that is less than 18 point in size; or bold text less than 14 point in size that has a luminosity contrast ratio of 4.023, which is below 4.5:1"

Tester remark:
It has to be checked whether those contrast issues are not part of theme-styling.
Only configuration-specific styling might be adapted.

Example:
![Contrast example](https://user-images.githubusercontent.com/54309425/146956817-a74ec0e3-27fb-4c61-a1de-a594743a7a9d.png)

**Comment by steinsebastian** [comment]
There are contrast issues for:

- Product Title Area: Product Code (ID)
- Tab-Area: Configuration Link
- Tab-Area: Overview Link
- Group-Menu: Active Group Name (light red)
- Prev/Next-Area: Next button
- Add-To Cart Button
- Value Surcharge
- Product ID in product-card
- Button in product-card
- Link to PDP in product-card
- Overview: Name of attribute
- Overview: Product ID of bundle
- Overview: Value Surcharge
- "No option selected" in product-card

**Comment by schuppell** [comment]
Will be fixed by https://github.com/SAP/spartacus/pull/14855

**Comment by schuppell** [comment]
The only open thing left, is the Value Surcharge.
I contact the designer, because in this case a high contrast would signal, that the price got added.
