### ISSUE TITLE
(semanticly) currentPage in url does not match current page in Pagination

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14728]
**Describe the bug**
When navigating through a list of products with pagination, the url parameter, currentPage, does not match the current page of the pagination (see screenshot below).

**Version of Spartacus**
4.2

**To Reproduce**
1. Go to 'BRANDS > Shop All Brands >'
2. Click on 'Page 2'
3. Observe url 

**Expected behavior**
Url param to match current page of navigation

**Screenshots**
<img width="1436" alt="current_page_bug" src="https://user-images.githubusercontent.com/49131189/147830293-6ac246f2-5225-447c-a500-facd1807b85e.png">

**Comment by Xymmer** [comment]
not related to #14711

**Comment by Xymmer** [comment]
fix for 4.x and 5.0

**Comment by Xymmer** [comment]
the feature works but index is 0 based

**Comment by Xymmer** [comment]
we probably will never change this behavior but thanks for reporting Ben!!!!
