### ISSUE TITLE
Need License confirmation for open source projects.

### ISSUE THREAD

**Issue by SarathChandra84** [SAP/spartacus#14733]
Hi Team,

As part of the internal whitesource scan for our project, Internal security is looking for clarification on Licenses for few dependency libraries as part of node_modules folder. As below libraries have dual licenses available, please let us know which license sparatcus leverages.

abbrev-1.1.1 ->  ISC & MIT 
acorn-node 1.8.2-> Apache 2.0 and MIT
pause-stream 0.0..11 -> Apache 2.0 and MIT
from-0.1.7.tgz -> Apache 2.0 and MIT
Marked v0.7.0 -> MIT and BSD3
bcryptjs-2.4.3.tgz -> MIT and BSD2.

Please let me know if you need more information.

Thanks.

**Comment by Xymmer** [comment]
hi, we provide Spartacus libraries under apache. all other libraries are provided by npm and your usage of Angular, so it's actually your choice.
