### ISSUE TITLE
SSR flickering on PLP

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#14769]
We've noticed a "flickering" on our PLP pages. 

## Reproducing the issue

1. on develop, run `yarn dev:ssr`
2. perform a search
2. refresh on the search results page
3. you should see the product list page rendered _first_ and then facet list appearing after we switch to CSR.
4. to see the issue more clearly, you can use the browser's performance profiler to record the loading of Spartacus, and then inspect the screenshots.
 
## Potential causes for this problem

1. We don’t render the facets in the mobile view. We do mobile-first SSR (i.e. without facets menu), and as the CSR kicks in, the desktop viewport is detected in the browser, and the facets are rendered. In this particular example of the PLP page, this will cause facets to appear with a delay, which is perceived as flickering.
2. In `product-facet-navigation.component`, we are using the breakpoint service, which will cause flickering for pages which have different layouts for mobile and desktop (e.g. PLP and navigation menu). We should look into using a different technique of rendering for different layouts (see 5th bullet point).
3. using any delays in streams (`observeOn(asyncScheduler)`, `debounce(0)`, etc.) will cause flickering after CSR kicks in. Currently, we use `observeOn(asyncScheduler)` in the `product-facet-navigation.component`, and the reason for it is because we wanted to render a part of template only if a CSS rule is applied to _another_ part of the template - i.e. in the component's html, there's `trigger` element which is controlled by the components scss which hides on desktop screen sizes. This causes another render to happen. Trying to remove the remove the `observeOn(asyncScheduler)` will produce the error `ERROR TypeError: Cannot read properties of undefined (reading 'nativeElement')` because the element is not yet rendered at the time of accessing it. Instead, we could try to use `ngAfterViewInit` to check if the CSS is applied, but we will likely run into "content changed after rendered" error.
4. On top of that, in `isOpen$` we also have the following code which might cause some delays in rendering: `delayWhen((launched) => interval(launched ? 0 : this.CLOSE_DELAY))`.
5. We can investigate alternative approaches to handling a different layout for mobile and desktop in SSR. Having a different layout will save some unnecessary computing, but another option is always render both layouts and use pure CSS to hide certain layouts for the given screen size. Downside of this approach is the fact that we will be rendering everything, which might cause performance issues on slower devices. The upside is that there won't be any flickering, and we will have everything rendered in SSR for SEO purposes / easy transition to CSR.
6. We should make 2 and 3 part of our SSR guidelines.

## Additional fixes

As an additional fix which we can do is in the `facet-list.component.ts`' `isDialog` setter, where we directly access the document. We can inject `winRef` and access the `document` via it.

**Comment by Xymmer** [comment]
we'll aim to fix for 5.0. won't backport unless specifically asked but it might not be possible (will find out after investigation)

**Comment by DENCREAT** [comment]
I have the same ussue

**Comment by Xymmer** [comment]
might not be able to fit this for 5.0, scope of this ticket is big, we'll do best effort and see how far we get by release time

**Comment by Platonn** [comment]
Closing in favor of https://jira.tools.sap/browse/CXSPA-2968
Perhaps fixed in 6.7 in PR https://github.com/SAP/spartacus/issues/14769
