### ISSUE TITLE
handle add to cart error

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#14762]
If the "add to cart" has error, we need a better way to handle it. For example, for anonymous user, add one product in cart, then remove the cart from backoffice. Add this product again. Since the active cart is gone, so the "addEntry" is failed. We can see the error message of "cart not found", but the modal is empty with spinner running.
![Screen Shot 2022-01-12 at 12 04 55 PM](https://user-images.githubusercontent.com/44440575/149196156-ae9eacfa-505c-4316-85f8-ab8143defcd5.png)

**Comment by Ross-Rawlins** [comment]
Hi what solution did you come up with? and what version was is deployed to?
