### ISSUE TITLE
Improve the SSR state transfer and performance on PLP

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#14770]
As part of #14769's investigation, we noticed a performance hit where Spartacus issues `/search` http call after the CSR kicks in. But, this should not happen as we have the state transferred from SSR, containing the whole `product` state slice wich includes the search results (products, facets, etc.).

To reproduce:

1. on develop, run `yarn dev:ssr`
2. perform a search
2. refresh on the search results page
3. notice the `/search` http call in the network tab

**Comment by Xymmer** [comment]
a bug was also reported in #15023 
Product list component loaded twice #15023
Nik said duplicate but make sure this fix covers that bug

**Comment by Platonn** [comment]
Closing in favor of https://jira.tools.sap/browse/CXSPA-2968
Perhaps fixed in 6.7 in PR https://github.com/SAP/spartacus/issues/14769
