### ISSUE TITLE
CDC(merge) test is running on 4.2.x back port PR

### ISSUE THREAD

**Issue by wangzixi-diablo** [SAP/spartacus#14788]
I am using this PR to do back port on 4.2.x:

https://github.com/SAP/spartacus/pull/14777

I found out that cypress: CDC(merge) is running on the PR which is not correct according to Gil. 

<img width="681" alt="clipboard" src="https://user-images.githubusercontent.com/58975336/149767248-33d79d2d-48ad-43ff-b7ab-b311075cb527.png">

As requested by Gil, I create this ticket to track the issue.

**Comment by hackergil** [comment]
CDC e2es are optional. You should be able to merge your PR even without them failing.
