### ISSUE TITLE
ASM E2E High Failure Rate in Pipeline. Improvement Request. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14801]
ASM E2E Tests have a high failure rate in pipeline. 

It's decreasing overall performance of the test suite. 
It causes unnecessary repetition in order to get a green build. 
Request timeout was increased to 45 secs, but no improvement was seen. 

**Request:** 
- Please analyze failures in pipeline (not localhost, nor dev server)
- Address issues where e2e fail.  Consider backend maybe under high load. 
- Modify e2e test so that it's flexible at certain junctions where backend maybe under high load. 

- Test modifications in a dev server (headless mode) at least 25 times at different intervals throughout the day. 

---
As starting point, look at: 
https://dashboard.cypress.io/projects/k3nmep/runs/27308/test-results/bf343fd6-bf7c-4717-bbd1-6a3ffa088039

Stats from Cypress:
![Screen Shot 2022-01-18 at 10 50 20 AM](https://user-images.githubusercontent.com/46171897/149971229-ed2eaa3b-a47e-4bce-87e2-39b64ef847f0.png)

**Comment by RadhepS** [comment]
This appears to no longer be an issue:
https://dashboard.cypress.io/projects/k3nmep/analytics/flaky-tests

@giancorderoortiz could you please confirm before I close this ticket?

**Comment by RadhepS** [comment]
This appears to no longer be an issue:
https://dashboard.cypress.io/projects/k3nmep/analytics/flaky-tests

@giancorderoortiz could you please confirm before I close this ticket?
