### ISSUE TITLE
Apparel Checkout As Guest. High Failure Rate in Pipeline. Improvement Request

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14804]
Apparel Checkout as Guest Tests have a high failure rate in pipeline. (develop branch)
File: regression/variants/apparel-checkout-as-guest.e2e-spec.ts

It's decreasing overall performance of the test suite.
It causes unnecessary repetition in order to get a green build.

**Request:**

- Please analyze failures in pipeline (not localhost, nor dev server)
- Address issues where e2e fail. Consider backend maybe under high load.
- Modify e2e test so that it's flexible at certain junctions where backend maybe under high load.
- Test modifications in a dev server (headless mode) at least 25 times at different intervals throughout the day.

----

See https://dashboard.cypress.io/projects/k3nmep/runs/27221/overview
https://dashboard.cypress.io/projects/k3nmep/runs/27221/test-results/d7b9926f-01cc-4b33-952d-4971f602905b

![Screen Shot 2022-01-18 at 12 07 00 PM](https://user-images.githubusercontent.com/46171897/149984963-5f8bd46f-e4c3-45b5-b081-b56da34c7325.png)

![Screen Shot 2022-01-18 at 12 13 01 PM](https://user-images.githubusercontent.com/46171897/149985526-8c5eb144-25d3-4cb2-8753-9cdf61c70c9e.png)

**Comment by giancorderoortiz** [comment]
@KateChuen fyi

**Comment by KateChuen** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-261
