### ISSUE TITLE
quick-order-form.component.d.ts constructor is missing 

### ISSUE THREAD

**Issue by LLink-dev** [SAP/spartacus#14821]
**Describe the bug**
Trying to overwrite the QuickOrderFormComponent in customer project. I noticed that the constructor is deprecated and the recommended constructor is missing quick-order-form.component.d.ts. I'm only able to overwrite the deprecated constructor. This one only has 2 parameter and the recommended one has 4 parameters. The source code of release 4.2 show both constructors but the d.ts file just contains the deprecated one.   

**Tell us the version of Spartacus**
- 4.2.1

![image](https://user-images.githubusercontent.com/57799307/150361121-e13fbe52-9b30-4c54-a803-1240d9e266b3.png)

**Comment by dydome** [comment]
Hi @LLink-dev the problem is solved with https://github.com/SAP/spartacus/issues/14058. It will be a part of 5.0 release
