### ISSUE TITLE
4.3.x and CX 2011 Test

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#14841]
4.3.x and CX 2011 Test

backend: https://138.91.105.158:9002

---
-- Following tests specs have failed and require manual verification: 4.3.x and CX 2011 Test #14841
--- Cart Validation
--- Cart
--- My Coupons
--- My Account / Address Book
--- M Account / Payment Methods
--- Product Search
--- Site Context / Language / Cart
--- Site Context / Language / Checkout
--- Site Context / Language / My Account

--- B2B Account Checkout
--- B2B Replenishment

**Comment by giancorderoortiz** [comment]
@KateChuen  fyi

**Comment by giancorderoortiz** [comment]
[e2erun_cx2011_b2c.log](https://github.com/SAP/spartacus/files/7929348/e2erun_cx2011_b2c.log)

![Screen Shot 2022-01-24 at 5 43 21 PM](https://user-images.githubusercontent.com/46171897/150877370-eead1ad4-28b7-4904-bee5-cd71f693fe40.png)

**Comment by giancorderoortiz** [comment]
B2B:
![Screen Shot 2022-01-25 at 9 39 08 AM](https://user-images.githubusercontent.com/46171897/150997565-bbbf7bb9-1eff-4e0d-92ab-15be6827dbfa.png)

**Comment by giancorderoortiz** [comment]
[e2e_b2b_cx_2011.log](https://github.com/SAP/spartacus/files/7934416/e2e_b2b_cx_2011.log)

**Comment by hackergil** [comment]
@BenjaminEmiliani , Jonathan and I ran these failing tests today and they all passed.
