### ISSUE TITLE
Support correct HTTP Status Codes -  especially 404

### ISSUE THREAD

**Issue by domvo** [SAP/spartacus#14885]
**Is your feature request related to a problem? Please describe.**
We use Spartacus behind a CDN. That CDN relies on a 404 Status Code in order to do its caching correctly. Currently, when the "404" Page is rendered, it is returned with a 200 Status code.

**Describe the solution you'd like**
When I request a route that doesn't exist, it should not only show the 404 Page, but also set the Status Code correctly.

**Describe alternatives you've considered**
With plain Angular Universal it is possible to configure this through the server.ts.

**Comment by janwidmer** [comment]
@domvo we have had this problem too.. 

We implemented the following solution (more or less, what @tobi-or-not-tobi described in his comment in ticket https://github.com/SAP/spartacus/issues/9681), which helps us to return the correct http status to the user (e.g. Search engine bot):

server.ts
```
  // All regular routes use the Universal engine
  server.get('*', (req: Request, res: Response) => {
    console.log('[Node Express] rendering index html..');
    res.render(
      indexHtml,
      {
        req,
        providers: [
          { provide: APP_BASE_HREF, useValue: req.baseUrl },
          { provide: 'REQUEST', useValue: req },
          { provide: 'RESPONSE', useValue: res },
        ],
      },
      (_error, html) => {
        if (res.get('X-Response-Status') === '404') {
          // 404 coming from OCC Call for not existing page within SSR
          console.log(`[Node Express] 404 for url ${req.baseUrl}`);
          res.status(404).send(html);
        } else if (res.get('X-Response-Status') === '301' && res.get('X-Redirect-Url') !== '') {
          // 301 coming from OCC Call for wrong / outdated URL within SSR
          console.log(`[Node Express] 301 for url ${req.baseUrl}`);
          res.redirect(301, res.get('X-Redirect-Url'));
        } else {
          // return rendered html for default
          res.send(html);
        }
      }
    );
  });
```

occ-redirect.interceptor.ts
```
declare module '@spartacus/core' {
  interface Page {
    redirectUrl?: string;
  }
}

@Injectable()
export class OccRedirectInterceptor implements HttpInterceptor {
  constructor(
    @Inject(PLATFORM_ID) private platformId: object,
    private occEndpointsService: OccEndpointsService,
    @Optional() @Inject(REQUEST) public request: Request,
    @Optional() @Inject(RESPONSE) public response: Response
  ) {}

  intercept(req: HttpRequest<any>, next: HttpHandler): Observable<HttpEvent<any>> {
    return next.handle(req).pipe(
      filter((response): response is HttpResponse<any> => response instanceof HttpResponse),
      tap((response) => {
        const isPagesCall =
          response.url && response.url.indexOf(this.occEndpointsService.getRawEndpointValue('pages') || '') > -1;

        if (isPlatformServer(this.platformId) && response.url && isPagesCall) {

          const page = response.body as Page;

          // if the redirectUrl is set, we are on a page with wrong url (e.g. product / category page with missing / outdated name)
          // we set a response header to be used in the node express render callback
          if (page.redirectUrl) {
            this.response.set('X-Response-Status', '301');
            this.response.set('X-Redirect-Url', page.redirectUrl);
          }
        }
      }),
      catchError((error: any) => {
        if (error instanceof HttpErrorResponse) {
          // only execute if we are in SSR mode
          // if the pageId is notFound, we set a response header to be used in the node express render callback
          if (isPlatformServer(this.platformId)) {
            this.response.set('X-Response-Status', '404');
          }
        }
        return throwError(error);
      })
    );
  }
}
```

This is how it works:
1. the request comes to the node server
2. the request / response are getting injected into the application
3. the Application goes into Server Side Rendering and get's normally bootstrapped
4. the Application executes the needed OCC calls to the backend
5. for the 4th case described in this ticket, the OCC pages call returns with a 404 http status code
6. for cases, where the requested url is wrong (missing / outdated category or product name), the OCC pages call returns a custom property `redirectUrl` containing the correct url determined by the URL resolver in the backend
7. we use a http request interceptor to intercept the backend response and set a custom http header flag on the node express response, which was injected into the application in step 2
8. after rendering the Page in SRR, the node express render callback get's executed
9. we can check for the custom http header flags set in step 7 and take the appropriate action with the node express response (either setting a http status code or executing a redirect)

I am sharing this to maybe help others, which need to implement something like this..
Of course, it would be great, if a solution would be offered out of the box from spartacus.

**Comment by Xymmer** [comment]
hi @domvo thanks for the feature request. We're moving to an internal jira so will close this issue and follow up post-5.0 with this topic as one of the candidates. We agree it should be possible

**Comment by Platonn** [comment]
related PR https://github.com/SAP/spartacus/pull/18742/
