### ISSUE TITLE
Bug on mobile navigation when navigating to current page open

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#14906]
**Describe the bug**
'My Account' navigation node disappears after clicking on the same navigation point three times (target navigation point leads to the currently open page)

**To Reproduce**
1. Change to mobile view
2. Click on menu
3. Click on 'My Account' 
4. Click on any page, e.g. 'Personal Details'
5. Repeat steps 2 to 4, two more times (make sure to select the same page each step)
6. Open menu and observe the absence of 'My Account'

Result after reproducing bug:
<img width="487" alt="Screen Shot 2022-01-28 at 4 33 01 PM" src="https://user-images.githubusercontent.com/49131189/151624483-7da834c2-0b07-4507-ba98-53b1de42d6ea.png">

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

Ik ok now. MyAccount doesn't disappear.

<img width="503" alt="Screen Shot 2022-04-22 at 1 52 56 PM" src="https://user-images.githubusercontent.com/45409515/164768549-2f05dfea-00eb-46bf-b1ed-af10be753e42.png">
