### ISSUE TITLE
occ baseurl meta doesn't work for b2ctelcotmfwebservices

### ISSUE THREAD

**Issue by boliveiratelco** [SAP/spartacus#14907]
I am configuring spartacus tua in ccv2 environment and the meta 
`<meta name="occ-backend-base-url" content="OCC_BACKEND_BASE_URL_VALUE" />`
It works for /occ but not for /b2ctelcotmfwebservices. 
I have multiple environments to manage baseUrl which must be the same endpoint as /occ.

SAP Commerce Cloud 2105.2
Telco And Utilities 2111.0
Spartacus TUA: 3.4

**Comment by Xymmer** [comment]
Hi @boliveiratelco, it's easy to say that this isn't spartacus, but it probably isn't :) it's better if you create a supprot request through SAP's launch pad, https://launchpad.support.sap.com/

**Comment by klaycon** [comment]
hi @boliveiratelco, I have the same problem... CORS /b2ctelcotmfwebservices

Do you remember how to solve it?
