### ISSUE TITLE
Schematics - order of feature modules

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#14959]
```
In SpartacusFeaturesModule, ...featureModules, is the last in provider list. So, configuration of[CHECKOUT_FEATURE]: {...} in digital-payment will replace the one in checkout feature.
```

The above comment is from Wei's from this PR: https://github.com/SAP/spartacus/pull/14954
It got me thinking about our current installation schematics. As we didn't have a reason to think about the order of feature before, we are simply _not_ ensuring this.
Let's take a look at the following use cases:

### Installing feature using the main prompt

When we run `ng add @spartacus/schematics` we will be prompted to select which features to install.

The order of installation is not deterministic, and it depends on multiple factors:
- the order in which it appears in the prompt list
- the order in which they are selected - as we depend on the Angular passing us the list of selected features, which might be changed if the user selects a feature, then deselects, and then selects again.
- some internal dependency discovery that which we have (think of the case where customers select a feature which a has a dependency on another Spartacus features, which isn't selected).

Because DP has to be listed after Checkout, we need to ensure this by ordering the imports of features in spartacus-features module.
Currently, this is _not_ the case, and can be seen in the following examples:
- `ng add @spartacus/schematics`
- select _only_ DP. Checkout is not selected, but it will be installed as it's a dependency of DP.
- when the schematics finishes, in the Spartacus features module, the order will the following: `DigitalPaymentsFeatureModule,CheckoutFeatureModule,UserFeatureModule`.

We can see the order is wrong - the `DigitalPaymentsFeatureModule` should be listed _after_ `CheckoutFeatureModule`.

### Installing a feature using its own schematics

Let's say the app already exists with some features installed (but not the `Checkout`), and the user runs `ng add @spartacus/digital-payments`.
It's hard to imagine Spartacus without Checkout, but technically it's possible. The result of the installation will be exactly the same as the one above.

## How to solve the problem

We could try to determine the order of the feature module imports by running the following algorithm:

- when we have the list of selected features
  - detect their dependencies
  - store them in a certain data structure
- once we have the list of all spartacus features which should be installed
  - determine which features is the most dependent on. We could do this by e.g. counting how many times appears in the data structure from above
  - as the last step in the installation process, we could re-arrange the list of features in the spartacus features module according to the order 

Since we want to make sure the order is preserved, it would be good to add a comment above the import whose order is critical.
E.g.
```ts
imports: [
...
CheckoutFeatureModule,
// should be imported after CheckoutFeatureModule
DigitalPaymentsFeatureModule,
...
]
```

## Conclusion

To me, this is something that we want to address, and invest time, because it can save us a lot of time with potential mis-configuration issues.

**Comment by plabadie** [comment]
For the algorithm, we might also have to generate an internal dependency tree and then install the features bottom up.
