### ISSUE TITLE
Can remove promotional item from cart while free item remains

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14957]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Add product 1934796 to cart
Go to cart. Promotional item 1934796 is in cart, plus the free product 137220.
Now, add any other product, for eg: 1934794
Go to cart
Remove promotional item 1934796

**Actual Result**
The free product 137220 remains in cart. 
<img width="1022" alt="Screen Shot 2022-02-04 at 9 49 05 PM" src="https://user-images.githubusercontent.com/45409515/152626222-d93b9cd8-a602-479f-92e6-dcf358924dfe.png">

**Expected Result**
Probably it has to do with the whole promotions module... Please confirm, if so, can close it.
But would expect the free item to be removed together with the promotional item
However, if I do try and place an order, the free item will be removed, which is correct. 
Or if I sign out and sign back in, the free item will be removed. 
Was just expecting it to be reflected right away when the promotional item is removed from the cart.

**Comment by Xymmer** [comment]
investigate if related to spartacus/cartlib; if so, fix for 5.0.
if not (so it's occ api), create jira and add jira issue link to this ticket, and close this one and let Bill know.

**Comment by KateChuen** [comment]
Tested on develop branch. Ok now. The free item is also removed when the promotional item is removed.
