### ISSUE TITLE
Cart page: Name of Proceed to Checkout button changes when clicked

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14952]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Add a few items to cart (at least 5 items)
Go to cart page
Click on "Proceed to Checkout" button

**Actual Result**
There are times where you'll see the name of the button change while it's processing. It's very quick, but can still see it.
<img width="1005" alt="Screen Shot 2022-02-04 at 10 04 26 AM" src="https://user-images.githubusercontent.com/45409515/152553413-f5cb8f28-d7cc-4349-939a-a774802c5c32.png">

**Comment by Xymmer** [comment]
change the text to "Processing"
