### ISSUE TITLE
Free product is added to wish list and price not reflected

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14956]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Add product 1934796 to wish list
Go to wish list - you'll see product 1934796 and the free product as well
Click on "Add to Cart" on the product 1934796
Then click on "Add to Cart" on the free product
Then click again "Add to cart" on the free product

**Actual Result**
In the added-to-cart modal, you'll see the price is $0.
But if you go to cart, the price of the extra "free" product is $8. Which is correct. 

<img width="847" alt="Screen Shot 2022-02-04 at 9 39 35 PM" src="https://user-images.githubusercontent.com/45409515/152626057-1cdfe08f-faf8-4a76-9356-d45cb649b463.png">
<img width="751" alt="Screen Shot 2022-02-04 at 9 40 07 PM" src="https://user-images.githubusercontent.com/45409515/152626076-cc38ec94-e1b6-4256-8992-8714e3ed2084.png">

**Expected Result**
I would not expect the free product to be added to the wish list, only the product 1934796. Then if I do add the product 1934796 to cart, then it should add the free product to cart also. 
Since the free product is in my wish list, I would expect the real price of the free product to be reflected in the wishlist, i.e, $8, OR the price of the free product to be reflected in the added to cart modal, if I'm adding more than i'm supposed to.

**Comment by Xymmer** [comment]
investigate if related to spartacus/cartlib; if so, fix for 5.0.
if not (so it's occ api), create jira and add jira issue link to this ticket, and close this one and let Bill know.
similar issue in #14957

**Comment by WeizhengSap** [comment]
free product is not updatable. So, I will remove "add to cart" or "remove" button for it.

**Comment by KateChuen** [comment]
Tested on develop branch. Works well now. 
- When a promotional item is added to the wishlist, the free item is also added along in the wishlist. However, there's no action that can be taken for the free item (cannot add it to cart or remove it from wishlist). 
- When the promotional item is removed from the wishlist, the free item is also removed from the wishlist. 
- When the promotional item is added to cart from the wishlist, the free item is also added to cart. 

<img width="977" alt="Screen Shot 2022-02-28 at 10 56 32 AM" src="https://user-images.githubusercontent.com/45409515/156015906-79ec8142-80e0-458f-94c4-ef5298386752.png">
