### ISSUE TITLE
Qty in added to cart modal does not match qty in cart if qty is greater than 9999

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14955]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Go to any powershot A480 product, for eg product ID 1934795
Click on "Add to Cart" 
In the added-to-cart modal, change the qty to 100000

**Actual Result**
You'll see the qty in the qty box is still 100000, but by the total number of items in cart, only 9999 was added. 
If you go to cart, you'll see the qty next to the item is 9999. 

However, you can then go ahead and either, increase the qty by clicking on the + sign, or manually typing in 100000 again. 
<img width="849" alt="Screen Shot 2022-02-04 at 9 17 58 PM" src="https://user-images.githubusercontent.com/45409515/152625471-a99f3d3c-e53b-4784-8780-76028e7127fb.png">

<img width="919" alt="Screen Shot 2022-02-04 at 9 16 17 PM" src="https://user-images.githubusercontent.com/45409515/152625422-2342007f-8b37-460d-b557-ca2f22b3c4b4.png">

<img width="827" alt="Screen Shot 2022-02-04 at 9 21 08 PM" src="https://user-images.githubusercontent.com/45409515/152625447-8fa82717-dab1-4252-8d44-f1036a2fdb82.png">

**Expected Result**
As least the number in the qty box of the added-to-cart modal should be the same as the number in the cart. It should update the qty in the added to cart modal to 9999.

**Comment by Xymmer** [comment]
investigate if related to spartacus/cartlib; if so, fix for 5.0.
if not (so it's occ api), create jira and add jira issue link to this ticket, and close this one and let Bill know.

there might be a ticket for 9999 issue already though
older issue: #13632 but maybe not same

**Comment by KateChuen** [comment]
Tested on develop. 
- Now the qty in the added-to-cart modal corresponds to the qty in cart. 
- We can't add more than 9999 in both the added-to-cart modal and on the cart page. 
<img width="797" alt="Screen Shot 2022-02-28 at 11 19 13 AM" src="https://user-images.githubusercontent.com/45409515/156021400-d54a8892-77e3-4f75-ab46-eff9a382ef09.png">


Question to @Xymmer? Should we disable the + button in the qty field if we can't add more than 9999? I think we configured the maximum amount that can be bought to 9999, but the stock is > than 9999. And the + sign becomes disabled only when it's out of stock. Which is not the case. For me it's fine this way too, as long as user cannot add more than 9999. Or perhaps a message to inform the user he can't add more than 9999? What do you think?

**Comment by KateChuen** [comment]
Tested on develop. 
- Now the qty in the added-to-cart modal corresponds to the qty in cart. 
- We can't add more than 9999 in both the added-to-cart modal and on the cart page. 
<img width="797" alt="Screen Shot 2022-02-28 at 11 19 13 AM" src="https://user-images.githubusercontent.com/45409515/156021400-d54a8892-77e3-4f75-ab46-eff9a382ef09.png">


Question to @Xymmer? Should we disable the + button in the qty field if we can't add more than 9999? I think we configured the maximum amount that can be bought to 9999, but the stock is > than 9999. And the + sign becomes disabled only when it's out of stock. Which is not the case. For me it's fine this way too, as long as user cannot add more than 9999. Or perhaps a message to inform the user he can't add more than 9999? What do you think?

**Comment by Xymmer** [comment]
fine with as is, don't think we need to backport
