### ISSUE TITLE
Cannot import file with more than 10 products to cart but we can to saved cart 

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#14975]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Add more than 10 products to cart, for eg, 12 different products.
Export the cart
Save the cart
Go to saved carts 
Import the file we just exported (or any file that has more than 10 products)
Now go to cart
Import the same file

**Actual Result**
We get an error that it's greater than 10. Why can we import in saved carts, but not in cart? 

<img width="522" alt="Screen Shot 2022-02-08 at 10 13 26 AM" src="https://user-images.githubusercontent.com/45409515/153016582-300bb9e0-81b4-40f8-aea5-4a913f74e910.png">

**Comment by BenjaminEmiliani** [comment]
Hey @KateChuen, this behaviour is by design
<img width="475" alt="Screen Shot 2022-02-08 at 10 31 32 AM" src="https://user-images.githubusercontent.com/49131189/153020081-bd34b746-c110-48f6-b0c1-5ab1d3d3213d.png">

**Comment by KateChuen** [comment]
Ah thank you!!!! I'll close this.
