### ISSUE TITLE
AMP errors on Shipping Address and Payment Method forms

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#14988]
**Describe the bug**

- During checkout when Shipping Address and Payment Method forms are displayed while entering the information for the first time, it seems the forms have the same errors on the ng-select element.
- Same error is detected on the Address Book section of My Account.
- Screenshots have more details about the nature of the problem.

**Tell us the version of Spartacus**
- Library version: develop (5.0)

**Checkout**
![Screen Shot 2022-02-09 at 5 38 04 PM](https://user-images.githubusercontent.com/15113219/153313794-f7803dc7-3d46-4871-adee-77b3075f5fe8.png)
![Screen Shot 2022-02-09 at 6 25 48 PM](https://user-images.githubusercontent.com/15113219/153313976-80390954-1267-4c6a-9682-ddc83fe5ad77.png)
![Screen Shot 2022-02-09 at 6 25 29 PM](https://user-images.githubusercontent.com/15113219/153313988-3136b8b4-ccbc-455e-afe3-6cd5b5bf6f73.png)
![Screen Shot 2022-02-09 at 6 26 16 PM](https://user-images.githubusercontent.com/15113219/153314009-36930036-9c30-47e4-961b-f25ad59e245d.png)
![Screen Shot 2022-02-09 at 6 26 07 PM](https://user-images.githubusercontent.com/15113219/153314021-0d6d36eb-01e1-483e-89a6-180c075948fd.png)

**Address Book**
![Screen Shot 2022-02-09 at 6 23 26 PM](https://user-images.githubusercontent.com/15113219/153314089-9ce25f1b-ae5e-46d1-97d8-18ea483be0d0.png)

![Screen Shot 2022-02-09 at 6 22 55 PM](https://user-images.githubusercontent.com/15113219/153314080-23d660b4-c068-4807-822c-a6caa04a2fde.png)

![Screen Shot 2022-02-09 at 6 22 17 PM](https://user-images.githubusercontent.com/15113219/153314073-b6890067-b024-4598-95bb-37e9af689089.png)

**Comment by Dalvir-Personal** [comment]
Ticket on hold temporarily. [Please see this comment for more details](https://github.com/SAP/spartacus/issues/14997#issuecomment-1047240306)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

<img width="880" alt="Screen Shot 2022-04-08 at 10 52 01 AM" src="https://user-images.githubusercontent.com/45409515/162467104-811d1a8e-4c08-4afc-9b59-ecf3f8e3412a.png">

<img width="871" alt="Screen Shot 2022-04-08 at 10 51 14 AM" src="https://user-images.githubusercontent.com/45409515/162467275-4a7f1ae7-f7bb-4305-a20d-b611d76a42d5.png">
