### ISSUE TITLE
Saved Cart qty is totalItems instead of totalUnitCount in SavedCartFormDialogComponent

### ISSUE THREAD

**Issue by BrentEerlingen** [SAP/spartacus#15005]
**Describe the bug**
When a saved cart is made active, the SavedCartFormDialogComponent shows a small summary of the saved cart. The qty that is presented is not equal to the total amount of products in the cart, but is equal to the amount of unique products. This is not consistent with the qty that is presented in the saved carts list.

**Tell us the version of Spartacus**
- Library version: 4.3

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a cart with 2 unique products
2. Make sure that the quantities of both products are not the same
3. Go to cart
4. Save cart
5. Go to saved carts page
6. Check quantity in list (this equals totalUnitCount)
7. Click "make cart active"
8. Check quantity in modal (this equals totalItems, should be totalUnitCount)

**Expected behavior**
In the SavedCartFormDialogComponent, the value of qty is the totalItems. This refers to the total number of unique items. This should be the totalUnitCount as it represents the total amount of product in the cart. This makes it also in line with the saved carts list, where the totalUnitCount is used as well.

**Desktop:**
 - OS: macOS Big Sur 
 - Browser: Firefox
 - Version: 97.0

**Comment by Xymmer** [comment]
check and make it consistent i.e. if total number of products is what we're using in the saved carts list, and everywhere else, change qty presented as described. I * think * we use total number of items (not unique items) everywhere so makes sense

**Comment by KateChuen** [comment]
Tested on develop branch.
OK now, Qty = total number of items in cart on both saved cart listing page and make cart active dialog. 

<img width="1134" alt="Screen Shot 2022-03-11 at 1 21 01 PM" src="https://user-images.githubusercontent.com/45409515/157927667-5f3dec3e-85d1-40f1-809b-3cf98947fb40.png">
<img width="1128" alt="Screen Shot 2022-03-11 at 1 20 53 PM" src="https://user-images.githubusercontent.com/45409515/157927673-444f80f8-7611-427e-a924-f2151e60afd3.png">
<img width="485" alt="Screen Shot 2022-03-11 at 1 20 47 PM" src="https://user-images.githubusercontent.com/45409515/157927678-f87a0157-d754-4ffa-b80d-88a8422d723a.png">
