### ISSUE TITLE
Problems with extend BannerComponent

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#15013]
**Describe the bug**
Observed here: https://stackoverflow.com/questions/71030337/not-able-to-use-cx-media-component-with-a-media-container
I can see TS compilation errors while try extends BannerComponent. It's related to used wrong types:
- Type 'string | undefined' is not assignable to type 'string | any[]'. `[url]="data.urlLink"`
- Type 'string | null' is not assignable to type 'string' `[target]="getTarget(data)"`
- Type 'CmsBannerComponentMedia | CmsResponsiveBannerComponentMedia | undefined' is not assignable to type 'MediaContainer'.
  Type 'undefined' is not assignable to type 'MediaContainer'.  ` [container]="data.media"`

**Tell us the version of Spartacus**
- Library version: 4.3

**To Reproduce**

1 Create a new Angular app, add Spartacus by schematics, set any possible backend
2 Add own MyBannerComponent extends BannerComponent, use copied template from BannerComponent
3 Try to compile
4 See error list:
```
Error: src/app/my-banner/my-banner.component.html:3:4 - error TS2322: Type 'string | undefined' is not assignable to type 'string | any[]'.
  Type 'undefined' is not assignable to type 'string | any[]'.

3   [url]="data.urlLink"
     ~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.


Error: src/app/my-banner/my-banner.component.html:4:4 - error TS2322: Type 'string | null' is not assignable to type 'string'.
  Type 'null' is not assignable to type 'string'.

4   [target]="getTarget(data)"
     ~~~~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.


Error: src/app/my-banner/my-banner.component.html:7:14 - error TS2322: Type 'CmsBannerComponentMedia | CmsResponsiveBannerComponentMedia | undefined' is not assignable to type 'MediaContainer'.
  Type 'undefined' is not assignable to type 'MediaContainer'.

7   <cx-media [container]="data.media"></cx-media>
               ~~~~~~~~~

  src/app/my-banner/my-banner.component.ts:6:16
    6   templateUrl: './my-banner.component.html',
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    Error occurs in the template of component MyBannerComponent.

```

**Expected behavior**
The component should compile properly, without any input.

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser: Chrome

**Additional context**
- Analogical issue for the different component: https://github.com/SAP/spartacus/issues/13652

**Comment by Xymmer** [comment]
fix for 5.0, backport to last 4.x.x

**Comment by plabadie** [comment]
The suggested workaround ideally is:
- For the customers to fix the strict compilation issue in their custom code.

Not ideal but still possible:
- The customer disables the angular compilation option `strictTemplates` .

Upgrading our code to support strictTemplates compilation is possibly a sizeable task we might want to prioritize for a post 5.0 major release.

similar to #13652

**Comment by WeizhengSap** [comment]
https://github.com/SAP/spartacus/issues/14037 already fix the `cx-media` issue, and it was backported.
