### ISSUE TITLE
linked page contained in ParagraphComponent could not be loaded under SmartEdit

### ISSUE THREAD

**Issue by wangzixi-diablo** [SAP/spartacus#15051]
**Describe the bug**
This issue is reported by customer.

When a Spartacus page link is contained in a ParagraphComponent, the link could NOT be loaded under SmartEdit succcessfully.

**Tell us the version of Spartacus**
- Library version: 4.2

**To Reproduce**
1. Make some changes in backoffice. For me, I use a local Hybris server.

Maintain `cms.components.allowUnsafeJavaScript=true` in `hybris\config\local.properties`，then start server.
![clipboard1](https://user-images.githubusercontent.com/58975336/154486140-e969abad-4c00-4b5d-944f-d1cf22b46751.png)

2. Search for Component with ID NoticeTextParagraph. 

![clipboard2](https://user-images.githubusercontent.com/58975336/154486179-ac8f45f2-8db0-4b06-9fc4-27407dadb691.png)

In its property field, maintain content as:

```html
<div><a href="/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Measuring-%2526-Layout-Tools/c/1358">Jerry Link</a></div>
```

![clipboard3](https://user-images.githubusercontent.com/58975336/154486218-7578a995-dc0f-4c1d-bd71-903b19686ebc.png)

Save the change, it will appear in the footer area under footer navigation area, as below:

![clipboard4](https://user-images.githubusercontent.com/58975336/154486309-0b918d49-70d6-4b3c-93c6-9c3344a4068b.png)

3. log in SmartEdit, click homepage:

![clipboard5](https://user-images.githubusercontent.com/58975336/154486354-eb2c0543-cede-457a-9988-3ec7080ac56f.png)

![clipboard6](https://user-images.githubusercontent.com/58975336/154486385-5d9bd405-a094-40b8-bb0b-6215860ccac1.png)

Error：

SmartEdit hangs there: 

> SmartEdit is having difficulty loading the page. The page is either not compatible with SmartEdit or connection to it has been lost. Wait for the page to load or disable editing by going to Preview mode.

![clipboard7](https://user-images.githubusercontent.com/58975336/154486443-f19c6865-41db-42fa-b5ba-63911721e1d3.png)

However, if we directly click the same OOTB navigation link which is `NOT` within a paragraphComponent, the link could be opened in SmartEdit without errors:

![clipboard8](https://user-images.githubusercontent.com/58975336/154486476-eeec8596-700d-4761-8a5f-c41fddef5d5f.png)
![clipboard9](https://user-images.githubusercontent.com/58975336/154486517-b052ffeb-8ace-411d-9462-63beb4960dc3.png)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser：chrome

# some initial comparison between two scenarios

I made some comparison between two scenarios: link contained in ParagraphComponent vs OOTB navigation link and observed two differences.

behavior | link contained in ParagraphComponent | OOTB navigation link
:-: | :-: | :-: 
href attribute rendered in html | href="/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Measuring-%2526-Layout-Tools/c/1358" | href="/powertools-spa/en/USD/Open-Catalogue/Office-Equipment%252C-Supplies-%2526-Accessories/Hand-Tools/Measuring-%2526-Layout-Tools/c/1358"
screenshot | ![](https://img-blog.csdnimg.cn/790c43a8bf864132a0e55aa24306d9ed.png)| ![在这里插入图片描述](https://img-blog.csdnimg.cn/2c20274de5304a4fbd415c495ebcfcbc.png)
cmsTicketId appended in CMS request?  | no:https://localhost:9002/occ/v2/powertools-spa/cms/pages?pageType=CategoryPage&code=1358&lang=en&curr=USD| yes:https://localhost:9002/occ/v2/powertools-spa/cms/pages?pageType=CategoryPage&code=1355&lang=en&curr=USD&cmsTicketId=6478827360217344df347bfa-b4c5-4210-98a1-c35b92a76ce1

**Comment by WeizhengSap** [comment]
The issue is `<a href="...">` make the app reloaded.

**Comment by Xymmer** [comment]
also mailto links

**Comment by Zeyber** [comment]
@wangzixi-diablo @WeizhengSap 

I tried adding a link to the FAQ paragraph component on the dev server `https://40.76.109.9:9002` and didn't run into the issue on Smart Edit or locally. Am I missing something? I'm not really well-versed with SmartEdit.

SmartEdit
![image](https://user-images.githubusercontent.com/11735817/155521529-9bd186f8-8b6e-46c6-9dd4-306187c63536.png)

Local
![image](https://user-images.githubusercontent.com/11735817/155521771-214f7603-ab35-4094-91ad-d0db027ff55d.png)

**Comment by WeizhengSap** [comment]
@Zeyber : If you click this new link, the whole app will be reloaded (you can check the requests in browser's Network).

**Comment by Zeyber** [comment]
Backporting to 4.3.x and 3.4.x: 
- https://github.com/SAP/spartacus/pull/15577
- https://github.com/SAP/spartacus/pull/15574
