### ISSUE TITLE
Avoid the core team code owners being flooded with notifications about changes in every PR

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#15182]
Since we introduced codeowners again in https://github.com/SAP/spartacus/pull/14908/files, by assgning the whole core team to the shared parts of code like core lib, storefront lib, feature libs, then every core team member is flooded with notifications about changes in any PR related to the shared code. 
This disturbs the workflow for people that relied on being notified only about PRs they participate in actively (review or author).

We checked with @Pucek9 on a test repo https://github.com/AlaMaKotaOrg/test-codeowners that when you create a **hidden** Github team and make it a code owner, then it its members don't receive notifications. But the drawback is that noone outside this team can see who is a member of this team. Therefore the PR author would not know who to ask for a review.

Alternatively, we can spike using the tool `Pullapprove` that the Angular team is using. See https://github.com/angular/angular/blob/5e9b41181e6f09420a0443d66cb2ebe986e56559/.pullapprove.yml

**Comment by Platonn** [comment]
[Pullapprove](https://www.pullapprove.com) is paid. Assuming we have ~40-60 maintainers in the repo, then the "Organization" plan applies for us (for <100 approvers). As of now, it costs  $6 / month per reviewer , which in total would be $240-360 / month. 

If we prove this tool fits our needs, we will need to approve the bugdet with the management

Note: this tool is not free for open-source projects:
> ![image](https://user-images.githubusercontent.com/4001059/154717305-0c57e0fa-3c88-4bad-937d-3430b65e73c2.png)

For more, see https://www.pullapprove.com/pricing/

**Comment by Pucek9** [comment]
After reviewing the documentation, in short, the tool stands out with the following benefits:
- phased reviews - allows for the queue of requested people/teams 
- group conditions - it can base on files, but also labels, etc.
- reviewers - allows for setting count of approves, can set approvers which will be not notified (eg. admins), allow for set how many people will be requested to review (by random or given)

**Comment by Pucek9** [comment]
The problem with notifications for standard codeowners, follows from difficulty with filtering emails (rules). There is no difference between email-sender in notifications for all reviewers (which is treated as spam) and specified ticket in which the reviewer has been engaged (which is in most cases desirable).

**Comment by Pucek9** [comment]
Some tools I found that most probably don't pass requirements
- ~https://github.com/marketplace/actions/codenotify~
- ~https://github.com/octobox/octobox~
Anyway, let's additionally verify are we able to have the satisfied results with some configurations:
https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team

**Comment by Xymmer** [comment]
might not be a low hanging fruit to fix this, close if not, MichalG and Kris will discuss

**Comment by Pucek9** [comment]
Discussed with Criss:
It would be possible to check such a [solution that we choose one](https://docs.github.com/en/organizations/organizing-members-into-teams/managing-code-review-settings-for-your-team#configuring-auto-assignment) (fake) person to be assigned, but most likely all the rest will still be requested (notified). In any case, most people ignore these messages already, so the topic has been dropped - very low priority and potentially high cost of the improvement.
