### ISSUE TITLE
[Regression] Image alternative text is the product description instead of product name

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#15215]
**Describe the bug**

- Image alternative text is the product description instead of the product name. This triggers an AMP error and bloats SR narration for the user. This was already fixed.
- This got fixed in GH-13523

**Expected behaviour**
- No AMP errors.
- SR vocalizes product name when focusing on an image.

![Screen Shot 2022-02-17 at 5 39 53 PM](https://user-images.githubusercontent.com/15113219/155165165-f9288ae9-3384-405a-a84f-ae8952a0658f.png)

![Screen Shot 2022-02-17 at 5 41 46 PM](https://user-images.githubusercontent.com/15113219/155165156-513ef952-e05a-406b-bbf1-d9d9f5c0018f.png)

**Comment by KateChuen** [comment]
Tested on develop branch using yarn.

It's now using product name, and no AMP error.
![Screen Shot 2022-04-21 at 2 12 33 PM](https://user-images.githubusercontent.com/45409515/164526144-c96e328d-728c-4246-ad31-be901f369f92.png)

![Screen Shot 2022-04-21 at 2 11 56 PM](https://user-images.githubusercontent.com/45409515/164526162-00d65eb2-5820-44e6-b559-77a120f8cecb.png)
