### ISSUE TITLE
Page layout handler is not called on page rendering

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#15236]
VariantConfiguratorPageLayoutHandler's handle method is no longer called on navigating to a new page. It is only called once after a browser refresh.

I cannot exactly tell what broke it, but it worked in develop branch at least until February 1st (with commit 3813105)

**Comment by Platonn** [comment]
Thanks @ChristophHi noticing it! 
Would you mind providing the bug reproduction steps, please?
(e.g. 
1. what options to set before running `yarn start`
2. which pages to open (or links to click) in the storefront
3. how to observe the broken behavior vs. what should be the expected behavior

**Comment by ChristophHi** [comment]
Reproduction doesn't require entering configurator.
Just use `yarn start,` and notice that VariantConfiguratorPageLayoutHandler#handle is called only once. Navigate to any page, the method is not called anymore.
Previously, the handle method was called on any navigation to another page

**Comment by KateChuen** [comment]
Tested on develop branch.

Before, going on product configuration page, then cart page, then back to product configuration page would display duplicated fields on the page. 
![Screen Shot 2022-03-22 at 12 10 16 PM](https://user-images.githubusercontent.com/45409515/159525668-067f9602-0cf1-4f98-9ba8-6db28f904e7a.png)


![Screen Shot 2022-03-22 at 12 10 26 PM](https://user-images.githubusercontent.com/45409515/159525182-a498803d-dc74-4172-967b-d7dc7e747212.png)


Now it's ok. the page is displayed properly. 
![Screen Shot 2022-03-22 at 11 43 09 AM](https://user-images.githubusercontent.com/45409515/159525644-426e89ce-382b-4d1a-b90f-2082951d53e8.png)
