### ISSUE TITLE
Store Finder: View all stores doesn't vocalize and display number of results

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15243]
**Steps:**
Go to electronics -> Find a store 
Click on "View all stores"

**Result:**
Before it used to vocalize the number of result found. (was tested in https://github.com/SAP/spartacus/issues/13738)
But it looks like it's broken now, and it says '111' which is meaningless to the user. 

![storeFinder1](https://user-images.githubusercontent.com/45409515/155596950-a56558ed-6e17-4165-a3d7-d6f99c8feb20.png)

**Comment by FollowTheFlo** [comment]
Vocalizing the loader spinner fix the problem #13698
Not sure about the reason, probably related to focus.

**Comment by FollowTheFlo** [comment]
tested with VO/Chrome
<img width="1614" alt="image" src="https://user-images.githubusercontent.com/30024415/156642137-627e4f52-b7f1-4c85-b846-1fcbc017d8b7.png">

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.

OK now. It vocalizes the results properly.
<img width="1289" alt="Screen Shot 2022-03-10 at 2 41 08 PM" src="https://user-images.githubusercontent.com/45409515/157742178-cfb8f0f5-9e55-4a74-8b21-681c2632af5b.png">
