### ISSUE TITLE
Checkout: do not allow card selection of already selected address/payment

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#15249]
currently, we can select already selected address/payment cards, which fires requests to set it again in the backend, but we do not need to set it again when it is already selected.

Moreover, every time we select a new address, it deletes the delivery mode set value from the backend. Therefore, clicking the same address should not be allowed as it puts the delivery method back to 'TBD' in the order overview section.

**Comment by KateChuen** [comment]
Tested on develop branch.

Can't select already selected address and payment.
