### ISSUE TITLE
Invalid ID when having more than one cx-card on checkout

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#15248]
**Describe the bug**

- AMP shows an error when having more than one cx-card on **Delivery Address** and **Payment Details**. It seems that it points to a non-existent ID.

**Expected behaviour**

- No AMP errors

![Screen Shot 2022-02-24 at 4 20 06 PM](https://user-images.githubusercontent.com/15113219/155619654-cf180225-492f-49d9-ac30-b1cd38f05fd8.png)
![Screen Shot 2022-02-24 at 4 47 39 PM](https://user-images.githubusercontent.com/15113219/155619663-a183da83-f14a-426d-84d2-bc948c3aeb96.png)

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

No AMP errors now.

<img width="1069" alt="Screen Shot 2022-04-22 at 10 28 40 AM" src="https://user-images.githubusercontent.com/45409515/164735184-1da28537-d691-46bc-9bf2-9def8b7f2848.png">

<img width="1082" alt="Screen Shot 2022-04-22 at 10 29 33 AM" src="https://user-images.githubusercontent.com/45409515/164735179-b653664c-33c7-41ce-a5b5-b861a41b69ff.png">
