### ISSUE TITLE
Smoothing the checkout-flow steps

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#15245]
Checkout mvp was merged, but there's further improvements to be done.

- remove sideeffects of going to the next steps
- place things into properties to not create new streams
- fire less requests for better performance
- remove doubly spinner

**Comment by bgambocjaviniar** [comment]
QA:
- checkout-flow should behave the same way as before

**Comment by KateChuen** [comment]
Tested checkout flow through ticket #13044
