### ISSUE TITLE
Aria Roles without names in Review Order

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#15246]
**Describe the bug**

- AMP detects aria roles without accessible names.
- This is probably coming from cx-card(s) of the previous steps where regions have names, **proceed carefully.** 

![Screen Shot 2022-02-24 at 4 00 03 PM](https://user-images.githubusercontent.com/15113219/155610726-fc7909ed-5d0f-4b77-add6-aebc4b3f31a7.png)

**To Reproduce**
1. Go to the last step on checkout
2. Run AMP and see the error.

**Expected behaviour**

- No AMP errors.
- **Best solution:** Remove roles at the last step **without** affecting previous steps.
- **Alternative solution:** If roles can't be removed at the last step, then **add `aria-label` and remove `tabindex="-1"`** so the user can jump to them with the rotor. Suggested names: _Review Payment, Review Shipping Address, Review Shipping Method_.

![2022-02-24_16-06-30](https://user-images.githubusercontent.com/15113219/155610979-f59d4dcf-8499-4ae6-8bc5-85dc0f73ab32.jpg)

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

<img width="793" alt="Screen Shot 2022-04-07 at 10 44 59 AM" src="https://user-images.githubusercontent.com/45409515/162229137-29cd5fe5-150a-4fce-9deb-3bf88e88b44a.png">

<img width="1138" alt="Screen Shot 2022-04-07 at 10 54 12 AM" src="https://user-images.githubusercontent.com/45409515/162229165-d993b174-db60-45de-b425-26203463ad1e.png">
