### ISSUE TITLE
Move the delete cart events from saved cart to the general cart event builder

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#15255]
Currently, the CartActions for deleting a cart is registered with the saved cart events builder. Some features would want to 'catch' the delete cart events, but it is currently thrown by the SavedCartEvents, which is semantically wrong.

Thanks to @BenjaminEmiliani to finding the issue

**Comment by bgambocjaviniar** [comment]
QA:
- deleting a saved cart and clearing a cart should behave the same way as before

**Comment by KateChuen** [comment]
Tested on develop branch (using installation script).
