### ISSUE TITLE
Big qty isn't fully displayed

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15265]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Add a product to cart, with qty of 4 digits (for eg: product 1934795, qty 9999)
Proceed to checkout. 

**Actual Result**
On the order review checkout page, you'll see that the qty is too big, so it's fully displayed. 

Also happens if you're on the cart page, and you click on "save for later" and go to the "save later" section of the page. 

<img width="864" alt="Screen Shot 2022-02-28 at 11 21 23 AM" src="https://user-images.githubusercontent.com/45409515/156042549-4014beb4-18ef-46cf-ae31-949bc226fa24.png">
<img width="804" alt="Screen Shot 2022-02-28 at 1 56 38 PM" src="https://user-images.githubusercontent.com/45409515/156042554-c416f943-e295-4d7b-bf05-c91d39de8a58.png">

**Comment by kimhw0630** [comment]
![image](https://user-images.githubusercontent.com/11823988/156428845-b9509d41-3033-4de5-9b00-5177df15d98b.png)
look like above change will fix
![image](https://user-images.githubusercontent.com/11823988/156428998-089bffb3-24bf-4a14-add3-a1a981aaf0ad.png)

**Comment by giancorderoortiz** [comment]
Should support up to 5 digits, no?

**Comment by kimhw0630** [comment]
I will change to pxs (65px) to support up to 6 digits.

**Comment by KateChuen** [comment]
Tested on develop branch. 
OK now.

It supports 6 digits which meets the "should support up to 5 digits".
<img width="750" alt="Screen Shot 2022-03-11 at 1 43 41 PM" src="https://user-images.githubusercontent.com/45409515/157933214-960ad576-8fc8-40d4-a6ff-06b3cd60e719.png">
