### ISSUE TITLE
Input of item counter in SavedCartDetailsItems is disabled

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15286]
**Describe the bug**
The middle section input of the item-counter in Saved Cart Details is disabled, but the quantity can be incremented/decremented with [-] [+] buttons.

**To Reproduce**
1. Create a shopping cart and save cart
2. Navigate to 'Saved Carts' under 'My Account'
3. Click on the saved cart
4. See error on item counter

**Expected behavior**
Uniform behaviour of item-counter  across features

**Screenshots**
<img width="1156" alt="Screen Shot 2022-03-02 at 4 07 40 PM" src="https://user-images.githubusercontent.com/49131189/156449863-f55cd229-7644-4eeb-9467-0c15da9ec8b8.png">

**Comment by KateChuen** [comment]
Tested on develop branch. The qty text field is now editable. 
<img width="1146" alt="Screen Shot 2022-03-17 at 11 32 01 AM" src="https://user-images.githubusercontent.com/45409515/158835300-e2d07cde-9d99-4675-9869-bc0a80cb0b5e.png">
