### ISSUE TITLE
should the item not cancelled be in the cancelled section

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15295]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Have 2 products in cart.
Place order.
Go to Order History.
Cancel 1 item in the order.
![orderCancellations3](https://user-images.githubusercontent.com/45409515/156590199-efa5662c-91c5-4dde-af26-c989e2f2c9cb.png)

Once the order cancellation has been processed, click on the order to see the details.

**Actual Result**
On the order details page, we see the item that was not cancelled, in the "cancelled" section, and also in the "In Process" section.
I can't remember for sure, but I was wondering if it should be in the "cancelled" section. 

![orderCancellations2](https://user-images.githubusercontent.com/45409515/156590709-03e9353e-773b-4287-961d-9c9ae0f1b346.png)

**Comment by BenjaminEmiliani** [comment]
Hey @KateChuen I can't give the answer to your question as I am unfamiliar of the intended requirements of the "Order Details' of orders with cancelled items. One way to see it that explains why a product that was not selected to be cancelled appears in both, is to think in terms of 'bundle'. What I mean is the bundle of items (the lens + camera) have been removed from the order, and the order now contains a bundle of size 1 (camera only). 

This is just a way of reasoning the current behaviour. I could be wrong and perhaps the desired behaviour is to exclude 'progress' items form 'cancelled'

**Comment by WeizhengSap** [comment]
@KateChuen : What @BenjaminEmiliani said is correct. This is designed as this. There are 2 consignments in this order: one is "cancelled" and the other one is "in processing". When we cancel one item in consignment, actually the consignment itself is cancelled. How to split consignments is determined by backend. 

I will close this ticket.
