### ISSUE TITLE
Items in non-shipped consignments are also listed in order returns form

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15298]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on electronics storefront
Place an order with many items, so that we have at least 2 consignments
Set only 1 consignment to shipped
Click on "Request a return"

**Actual Result**
the item in the other consignment that's still in process is also listed in the orders returns form.

<img width="1095" alt="Screen Shot 2022-03-03 at 10 30 06 AM" src="https://user-images.githubusercontent.com/45409515/156597445-af7472d9-7805-4a06-8491-ae19f12b7b25.png">

<img width="1100" alt="Screen Shot 2022-03-03 at 10 29 52 AM" src="https://user-images.githubusercontent.com/45409515/156597390-5703e987-c869-43cd-945d-58275dbe2fbd.png">

**Expected Result**
The order returns form should only list the items that are in the "shipped" state.

**Comment by Xymmer** [comment]
this is backend issue, closing and I have an improvement request open
