### ISSUE TITLE
AMP error on PDP, duplicate labels point to different href

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15315]
**Describe the bug**
On PDP, a breadcrumb element has an accessible name of 'x-category' that is the same as another <a> element in the header navigation but doesn't go to the same HREF.

**To Reproduce**
1. Go to a PDP of any product
2. run Access Assistant 

**Screenshots**
<img width="478" alt="Screen Shot 2022-03-04 at 4 46 39 PM" src="https://user-images.githubusercontent.com/49131189/156846195-11076971-67ec-4cea-bdc2-658225c221cb.png">
<img width="1536" alt="Screen Shot 2022-03-04 at 4 48 29 PM" src="https://user-images.githubusercontent.com/49131189/156846529-d99f1fcf-c440-4178-be14-91a420fd63ed.png">

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.
<img width="798" alt="Screen Shot 2022-04-06 at 2 41 48 PM" src="https://user-images.githubusercontent.com/45409515/162046199-729cb156-99a0-4272-9bcc-23add58ba6b3.png">
<img width="786" alt="Screen Shot 2022-04-06 at 2 27 57 PM" src="https://user-images.githubusercontent.com/45409515/162046202-554840d3-5bfb-41b6-b82e-485f9bd442b8.png">
