### ISSUE TITLE
Add to cart button misalignment in table viewport

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15327]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac

**Steps to Reproduce**
- Go to powertools
- Go to a list page
- Set the viewport to a tablet one

**Actual Result**
The "Add to Cart" text is misaligned in the button.
<img width="897" alt="Screen Shot 2022-03-08 at 10 36 30 AM" src="https://user-images.githubusercontent.com/45409515/157271581-bc86084b-81d2-430a-9cda-6b1a820c421c.png">

**Comment by morganm58** [comment]
This will be fixed in GH-15357.

**Comment by KateChuen** [comment]
Tested on my local, using develop branch. 

Still an issue, so Opened a ticket in Jira: https://jira.tools.sap/browse/CXSPA-514
