### ISSUE TITLE
Qty on saved cart can be more consistent

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15329]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on powertools storefront
Have a saved cart with a few different items, and different quantities of the items
Go to saved carts page
Select the saved cart to view the details
Click on "Make the cart active"

**Actual Result**
On saved cart listing page, the quantity = number of total items in cart
<img width="1140" alt="Screen Shot 2022-03-08 at 10 43 59 AM" src="https://user-images.githubusercontent.com/45409515/157306821-b392910c-07ba-497d-972f-824749fdaa68.png">

On saved cart details page, we see the accurate different details.
<img width="1187" alt="Screen Shot 2022-03-08 at 10 44 45 AM" src="https://user-images.githubusercontent.com/45409515/157306707-c2f86841-981b-468d-87eb-17c74f13c8d5.png">

On the "make cart active" dialog, quantity = number of different items. 
<img width="489" alt="Screen Shot 2022-03-08 at 10 44 14 AM" src="https://user-images.githubusercontent.com/45409515/157306770-9b11368d-8695-4051-b611-816b8d5c8ab2.png">

**Expected Result**
Maybe we need to make it consistent, or rename quantity? Maybe use the word "Items" on the dialog like in the saved details page?

**Comment by bgambocjaviniar** [comment]
it was fixed [here](https://github.com/SAP/spartacus/pull/15299), where qty in dialog would now be 84

duplicate of https://github.com/SAP/spartacus/issues/15005

**Comment by KateChuen** [comment]
Tested in ticket https://github.com/SAP/spartacus/issues/15005
