### ISSUE TITLE
Next scheduled orders for replenishment orders [check if backend]

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15323]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac

**Steps to Reproduce**
- Sign In powertools as a customer, for eg, Marie.dubois@rustic-hw.com
- Place a replenishment order A starting today(Monday Mar 7th), to be replenished every Monday. 
- Place a replenishment order B starting today(Monday Mar 7th), to be replenished every 7th day in a month.

**Actual Result**
The next scheduled order for replenishment order A is on the 13th, which is a Sunday. 
<img width="1022" alt="Screen Shot 2022-03-07 at 2 52 31 PM" src="https://user-images.githubusercontent.com/45409515/157110157-c5963705-1599-4865-aa7f-8d48b0e6fa86.png">

The next scheduled order for replenishment order B is on the 6th of April. 
<img width="977" alt="Screen Shot 2022-03-07 at 2 53 36 PM" src="https://user-images.githubusercontent.com/45409515/157110241-ad2cff40-af0f-4694-9f93-44fe79afc326.png">

Whereas the rest, it's still set on the 15th of the month. Is it because it's the current month. Whereas the other one is for the next month? And the current month is 31 days? 

<img width="982" alt="Screen Shot 2022-03-07 at 2 59 45 PM" src="https://user-images.githubusercontent.com/45409515/157110351-d616dfe5-cb88-432f-8584-fdd1668278ab.png">

- To be confirmed if it's normal or not. And we probably get the value from the backend?

**Comment by Xymmer** [comment]
check to be sure this is information coming from the backend, if so create SPA jira issue and we'll ask for backend improvement

**Comment by FollowTheFlo** [comment]
The replenishment order is created based on GMT timezone (+0000). On my browser set on Montreal timezone (GMT-04:00), the occurence appears 4h before, so sunday at 8pm. It is more explicit when setting time format as full:
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/30024415/158636970-34b48503-5503-4665-a5bb-0337348d3247.png">
It would explain, the issue about 'showing previous day'.

**Comment by KateChuen** [comment]
Closing since I can't reproduce it. It's consistent to 1 day before the date now. 
![Screen Shot 2022-03-16 at 3 54 46 PM](https://user-images.githubusercontent.com/45409515/158678759-82b9b0dd-5237-44de-8e5f-a366450799dc.png)
