### ISSUE TITLE
B2B: Status of Approved order goes to Pending

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15324]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac

**Steps to Reproduce**
- Sign In powertools as a customer, for eg, Marie.dubois@rustic-hw.com
- Place a big order, >$75000.
- Once the order is set as "Administrator Approval", login as linda.wolf@rustic-hw.com
- Approve the order
- Once the order is set to "Merchant Approval", login to admincockpit as acctmgra
- Approve the order
- Go back to powertools and login again as marie.dubois
- Go to Order History, the status of the order is "Approved"

<img width="1229" alt="Screen Shot 2022-03-07 at 3 48 16 PM" src="https://user-images.githubusercontent.com/45409515/157116495-949b7765-cd3c-4e9a-9131-1141e867b9d0.png">
- Click on the order to see the details

**Actual Result**
The status changes to Pending now. 
<img width="845" alt="Screen Shot 2022-03-07 at 3 50 15 PM" src="https://user-images.githubusercontent.com/45409515/157116550-f69a2524-d81a-476f-95b3-bb41801c97b6.png">

And if you go back to the Order History page, the status is Pending. 
<img width="776" alt="Screen Shot 2022-03-07 at 3 50 48 PM" src="https://user-images.githubusercontent.com/45409515/157116588-fd605b5a-5ca5-494e-847d-f749463c4c27.png">

**Comment by Xymmer** [comment]
it's pending because of built-in backend merchant check for big orders... the merchant has to approve it also at this point (let me know if i'm incorrect here)

**Comment by KateChuen** [comment]
Merchant has already approved.
And it is seen as approved at some point. See screenshot in description.

**Comment by Xymmer** [comment]
Backend fix required indeed it is a bug and not backend configuration
creating ticket for backend team

**Comment by KateChuen** [comment]
Ticket for backend team: https://jira.tools.sap/browse/CXEC-9254
