### ISSUE TITLE
Misalignment on saved cart listing page

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15328]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Login on powertools storefront
Have a few saved carts in your account
Go to saved carts page

**Actual Result**
There's misalignment on the page.
<img width="1160" alt="Screen Shot 2022-03-08 at 1 48 38 PM" src="https://user-images.githubusercontent.com/45409515/157305722-b3d75475-8cdd-4fb7-88f1-5c6e6da94ffe.png">

**Comment by BenjaminEmiliani** [comment]
Taken care of in PR #15313

**Comment by KateChuen** [comment]
Tested on develop branch.

It's aligned now. 
<img width="1209" alt="Screen Shot 2022-03-11 at 1 55 45 PM" src="https://user-images.githubusercontent.com/45409515/157934058-52780c9a-57f3-4236-9664-26e2635a3c9c.png">


However, I'm wondering (from memory), 
- Shouldn't the values in the TOTAL and QTY columns be aligned centered, instead on the left? And Perhaps the ID column too?
@Xymmer @developpeurweb would you recall what we had before? Or this is fine?

**Comment by BenjaminEmiliani** [comment]
> Tested on develop branch.
> 
> It's aligned now. <img alt="Screen Shot 2022-03-11 at 1 55 45 PM" width="1209" src="https://user-images.githubusercontent.com/45409515/157934058-52780c9a-57f3-4236-9664-26e2635a3c9c.png">
> 
> However, I'm wondering (from memory),
> 
> * Shouldn't the values in the TOTAL and QTY columns be aligned centered, instead on the left? And Perhaps the ID column too?
>   @Xymmer @developpeurweb would you recall what we had before? Or this is fine?

---response---
@KateChuen As for the alignment of the middle columns, I based it of wireframes 
![Screen Shot 2022-03-04 at 7 46 32 PM](https://user-images.githubusercontent.com/49131189/158187357-7492058c-6531-458e-9ed9-a2adfc796b25.png)

**Comment by Xymmer** [comment]
agreed we should at least right-align, but is a decimal separator align option? (not specifically .dot because it could be a comma in some regions)

**Comment by developpeurweb** [comment]
I recall we had right-align before on money amounts for tables, due to decimal places, but seems mockups are left-aligned. I'll ask designers to clarify and @morganm58  for tables' standardization.

**Comment by i813386** [comment]
Hi  Should the actions column heading  be left justified like the others?
![image](https://user-images.githubusercontent.com/15654746/163256962-37b74297-880d-47c2-94d5-5f4af7048bf1.png)

**Comment by morganm58** [comment]
> Hi Should the actions column heading be left justified like the others? ![image](https://user-images.githubusercontent.com/15654746/163256962-37b74297-880d-47c2-94d5-5f4af7048bf1.png)

The "actions" should be aligned right as it is in your screenshoot
