### ISSUE TITLE
Cannot add to cart from quick order in B2B

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15339]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local (installed using script)
Backend: 40.76.109.9

**Steps to Reproduce**
Go to powertools storefront
Go to quick order
Add an item in quick order
Click on "Add to cart"

**Actual Result**
I get a warning message saying the qty has been modified to the actual qty I had set.
But the item was not added to cart
In the console, we get a 401 error.
<img width="1427" alt="Screen Shot 2022-03-09 at 11 56 03 AM" src="https://user-images.githubusercontent.com/45409515/157491910-0c15e442-e843-40d6-95c0-ac7c5156588f.png">

**Expected Result**
If we are not supposed to be able to add an item from quick order, then maybe it should redirect the user to login page, or give the appropriate message that the user should login first?

Could be related to this issue: https://github.com/SAP/spartacus/issues/15340

**Comment by bgambocjaviniar** [comment]
should be good as discussed, but to verify and double check the installation script again

**Comment by KateChuen** [comment]
Ok now, after setting ADD_B2B_LIBS=true. Able to add to cart from quick order.
