### ISSUE TITLE
Site context component in the header UX improvement

### ISSUE THREAD

**Issue by BCmps** [SAP/spartacus#15336]
**Is your feature request related to a problem? Please describe.**
Currently the site context components for for example language and currency in the top header does not give a positive feedback to the user when he/she wants to click on the element.

**Describe the solution you'd like**

1. Extend the click area so the chevron is included:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/101265891/157477166-420cfdc0-cccf-4c0a-aad2-e65fed305770.png">

2. Change the "default cursor" to a "hand cursor" when the user hovers over the click area.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

- The click area includes the chevron now.

- The cursor is now a hand cursor when hover over the click area.

<img width="455" alt="Screen Shot 2022-04-21 at 12 22 31 PM" src="https://user-images.githubusercontent.com/45409515/164507029-c614212f-5769-4045-894b-7fd3e278d244.png">

<img width="712" alt="Screen Shot 2022-04-21 at 12 22 40 PM" src="https://user-images.githubusercontent.com/45409515/164507039-18eff898-17b1-4550-8b9f-a50881add129.png">

<img width="428" alt="Screen Shot 2022-04-21 at 12 22 55 PM" src="https://user-images.githubusercontent.com/45409515/164507055-6edafcdd-f1f5-488e-84fc-d6ca17bf6587.png">

<img width="433" alt="Screen Shot 2022-04-21 at 12 23 07 PM" src="https://user-images.githubusercontent.com/45409515/164507070-aca20ef0-48a8-4933-88e2-e8a366f8087f.png">

<img width="497" alt="Screen Shot 2022-04-21 at 12 23 13 PM" src="https://user-images.githubusercontent.com/45409515/164507081-565e5e63-ebc5-4cd1-ae47-4b5b6b41edc6.png">

<img width="527" alt="Screen Shot 2022-04-21 at 12 23 21 PM" src="https://user-images.githubusercontent.com/45409515/164507087-ef2e5c0f-7921-4e68-af30-932089664178.png">
