### ISSUE TITLE
B2B: Cannot login if use the installation sript

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15340]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local (**_installed using script_**)
Backend: 40.76.109.9

**Steps to Reproduce**
Go to powertools storefront
Sign in as a customer

**Actual Result**
I get a 401 error.
<img width="1433" alt="Screen Shot 2022-03-09 at 12 01 07 PM" src="https://user-images.githubusercontent.com/45409515/157492481-40ed95ce-f462-4cf8-baf9-c04266582361.png">

**Note**
Please note I installed it using the installation script. B2C using installation script works (can login).
B2B worked when I used yarn though.
But B2B using installation script doesn't work

**Comment by bgambocjaviniar** [comment]
should be good as discussed, but to verify and double check the installation script again

**Comment by KateChuen** [comment]
Yes confirmed, setting ADD_B2B_LIBS=true works. Can login now.
