### ISSUE TITLE
Scroll Back to Top Feature

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15356]
Create floating cms driven feature to scroll back to top.

Previously explored in #8440

**Comment by KateChuen** [comment]
Tested locally using develop. It's OK. 
- Tested on different pages, and it works as intended.
- Only have one question, when we have the Cookies Consent window opened at the bottom of the page, we can't see the "Scroll to Top" button, it's hidden underneath it. @Xymmer @developpeurweb Are you ok with that? 
- Created a ticket in Jira to also have e2e tests for this feature. https://jira.tools.sap/browse/CXSPA-516

**Comment by Xymmer** [comment]
>when we have the Cookies Consent window opened at the bottom of the page, we can't see the "Scroll to Top" button, it's hidden underneath it
ok with that, works as I expected (although I didn't discuss with them, good guess!)
