### ISSUE TITLE
Saved cart: The qty text field is not directly updatable (but you can click +/-)

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15359]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local (**_installed using script_**)
Backend: 40.76.109.9

**Steps to Reproduce**
Go to electronics storefront
Sign in as a customer
Have a saved cart
Open the saved cart
Click on the qty text field.
Click on the + and - signs.

**Actual Result**
As you can see, you cannot edit the qty text field by typing in it like you would on an active cart. Which looks like you're not supposed to be able to. But you can edit the qty by using the + and - signs or remove the item. And the changes are saved.
<img width="1020" alt="Screen Shot 2022-03-10 at 10 27 34 AM" src="https://user-images.githubusercontent.com/45409515/157732989-d9cf11d8-ce7e-4a64-af25-a5982695f77d.png">

**Expected Result**
Should allow user to also update the qty by typing in the text field.

**Comment by bgambocjaviniar** [comment]
it's being fixed in here https://github.com/SAP/spartacus/pull/15314

**Comment by KateChuen** [comment]
Tested through https://github.com/SAP/spartacus/issues/15286
