### ISSUE TITLE
"mailto:" or "tel:" URL's don't work 

### ISSUE THREAD

**Issue by Gjoot** [SAP/spartacus#15355]
**Describe the bug**
LinkComponent / GenericLinkComponent doesn't support "mailto:" or "tel:" URL's

**Tell us the version of Spartacus**
- Library version: all

**To Reproduce**
1. Create a CMSLinkComponent
2. Set "Link to" to "External Link"
3. Fill "mailto:test@test.com" in the URL field
4. Save and sync content catalog
5. Go to the spartacus site and click on the new CMSLinkComponent
6. you will get an not found page because the link is treated as an internal link

**Expected behavior**
GenericLinkComponent should recognize a "mailto" or "tel" as an external URL

**Comment by Xymmer** [comment]
similar but not the same as the other bug that was worked on (#15051 )
@gjoot what version of Spartacus are you using? we'll fix in 5.0 and backport to 4.x.
