### ISSUE TITLE
Find a store: Find My Location and Back to List buttons styling

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15357]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local
Backend: 40.76.109.9

**Steps to Reproduce**
Go on electronics storefront
Go to a tablet viewport
Go to "Find a Store"
Click on "View All Stores"
Click on a store, to see the store details.

**Actual Result**
The "Use my location" text does not fit in the button.
<img width="1035" alt="Screen Shot 2022-03-10 at 11 31 22 AM" src="https://user-images.githubusercontent.com/45409515/157710150-f756f172-c7a8-4d83-a120-c2b237c154bb.png">

The "Back to List" text does not fit in the button.
<img width="1076" alt="Screen Shot 2022-03-10 at 1 46 30 PM" src="https://user-images.githubusercontent.com/45409515/157733810-898b71a5-c8c8-4485-a6a4-90e213ecc4ad.png">

**Comment by Xymmer** [comment]
to be finished in https://jira.tools.sap/browse/CXSPA-277
