### ISSUE TITLE
Text to be corrected on the Notification dialog

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15399]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local 
Backend: 40.76.109.9

**Steps to Reproduce**
Go to electronics storefront
Sign in as a customer
Go to a product that's out of stock, for eg: 872912
Click on "Notify Me" button.

**Actual Result**
On the dialog, you'll find 2 mistakes:

as soons as -> should be corrected to -> as soon as
Manage your prefered notification -> should be corrected to -> Manage your preferred notification
at the Notification Preference Page -> should be corrected to -> on the Notification Preference page
at My Interests page -> should be corrected to -> on My Interests page

<img width="750" alt="Screen Shot 2022-03-16 at 2 50 31 PM" src="https://user-images.githubusercontent.com/45409515/158675096-1334b306-cca2-48be-aa01-fa17e0be2f88.png">

Also, on coupons page, can we change the word "Effective" to "Active" if it's coming from Spartacus? 
![Screen Shot 2022-03-16 at 3 30 17 PM](https://user-images.githubusercontent.com/45409515/158682616-d9a50017-8254-4076-bff9-0ab770965644.png)

**Comment by BenjaminEmiliani** [comment]
As an FYI, the green title of the coupon status is part of the coupon entity.
<img width="641" alt="Screen Shot 2022-03-17 at 11 38 28 AM" src="https://user-images.githubusercontent.com/49131189/158836717-c9fc001b-50f0-4dc7-abbc-759930c44015.png">

However we do map it to a string, i.e. if status of coupon is effective then `'myCoupons.' + coupon?.status` => 'myCoupons.effective => 'EFFECTIVE'

<img width="299" alt="Screen Shot 2022-03-17 at 11 39 52 AM" src="https://user-images.githubusercontent.com/49131189/158837059-33689bf8-b624-45fc-8aaf-7c6c3f7659b4.png">

So technically we could map 'myCoupons.effective => 'ACTIVE' but would not make it consistent
