### ISSUE TITLE
AMP errors on Register and Personal Details page (ng-select)

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15409]
Recent change (https://github.com/SAP/spartacus/issues/14997) added a directive to handle aria-label and aria-controls for ng-select to comply with SAP AMP.

Use new directive (cxNgSelectA11y) to correct reported error by Access Assistant on Registration page and Personal Details page

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using yarn
More extensive testing (on other screenreaders and devices) will be done with RC.

<img width="872" alt="Screen Shot 2022-04-07 at 12 07 20 PM" src="https://user-images.githubusercontent.com/45409515/162248295-61e200d1-f6c8-4ea2-9809-f189e0fdd3c6.png">

<img width="871" alt="Screen Shot 2022-04-07 at 12 06 24 PM" src="https://user-images.githubusercontent.com/45409515/162248315-af222e58-f083-4bae-8bb4-3808c2438a3c.png">
