### ISSUE TITLE
Error displayed when updating an address in Address Book

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#15412]
**Environment Details**
Browser: Chrome
Device: mac
Frontend: develop branch on my local 
Backend: 40.76.109.9

**Steps to Reproduce**
Go to electronics storefront
Sign in as a customer
Have an address saved in address book
Go to Address Book
Edit the address

**Actual Result**
We get a successful message that the address is updated, and it is indeed updated.
But we also get an error message. 

![AddBk](https://user-images.githubusercontent.com/45409515/158887486-00dea6e5-088f-4606-afb2-b4394c65b509.png)

**Expected Result**
Should not get an error message when updating the address

**Comment by kimhw0630** [comment]
Seems checking userId and cartId before dispatch loadCart action fixes the problem.
![image](https://user-images.githubusercontent.com/11823988/159720579-00dfc8b8-87e9-4bff-8ad7-f2fe94744f94.png)

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

No error displayed now, only the successful message. 

<img width="1179" alt="Screen Shot 2022-04-13 at 2 07 03 PM" src="https://user-images.githubusercontent.com/45409515/163243287-c79b6478-9442-4c7c-a552-8cf1755300c1.png">
