### ISSUE TITLE
B2B Registration Feature (CXSPA-186)

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#15437]
### Overview

About: https://wiki.wdf.sap.corp/wiki/display/spar/B2B+Registration 
Source of Truth: https://wiki.wdf.sap.corp/wiki/display/spar/B2B+Registration+SoT 
Questions: https://wiki.wdf.sap.corp/wiki/display/spar/Questions+to+B2B+Registration

### Branch

`epic/b2b-registration`

### Overall Feature

- [ ] Epic has been tested on a production-like server using Spartacus installation script
- [ ] Epic has been tested in all supported browsers and devices (Checklist on DoD page)
- [ ] Epic has sufficient end to end (cypress) test coverage
- [ ] Schematics code deprecations have been provided and tested
- [ ] Epic complies with [Security best practices](https://sap.github.io/spartacus-docs/security-best-practices/)
- [ ] Epic complies with [Accessibility best practices](https://sap.github.io/spartacus-docs/a11y-best-practices/)
- [ ] Epic CSS supports directionality (if required)
- [ ] Epic code scans have been conducted (sonar, whitesource, checkmarx)
- [ ] Epic renders successfully in SSR

### Audits/reviews

- [ ] Architecture review of the epic
- [ ] Security and threat modeling audit/review from the Security team
- [ ] Accessibility audit/review from the UX team

### New Library

If your epic will be introduced or introduces a new library:
- [ ] Library provides schematics to install the library
- [ ] Library modules can be lazy-loaded appropriately
- [ ] Library has been tested for a customer using Spartacus installation script

### Sample data

If the new feature requires new or updated sample data for a specific Commerce backend version:

- [ ] Sample data has been added to the sample data repo and merged to the next version to be released
- [ ] New sample data has been loaded and tested on a dev server
- [ ] New sample data has been loaded and tested in our CI server

### Documentation

- [ ] Documentation input is provided for it to be published on the doc site

Jira ticket: https://jira.tools.sap/browse/CXSPA-186

**Comment by Xymmer** [comment]
closed moved to jira
