### ISSUE TITLE
Pre build is not used on cloud

### ISSUE THREAD

**Issue by Exotelis** [SAP/spartacus#15463]
Hey everyone,

in our project we want to use a prebuild application on the cloud. Unfortunately, the dist/ we submit to the cloud is completly ignored. Currently, we build the following structure:

```
dist
|--<app-name>
   |--browser
      |-- index.html
   |--server
      |-- main.js
```
The dist folder is located in `<repo-root>/js-storefront/<app-name>/`
The manifest is structured as follows:
```
{
  "applications": [
    {
      "name": "<app-name>",
      "path": "<app-name>",
      "ssr": {
        "enabled": true,
        "path": "dist/<app-name>/server/main.js"
      },
      "csr": {
        "webroot": "dist/<app-name>/browser/"
      }
    }
  ],
  "nodeVersion": "12"
}
```
is the cloud expecting a different structure? We stumbled over a few documentations which are not very consistent in some points. Also, the only place where I could find some information about the prebuild is here: https://help.sap.com/viewer/b2f400d4c0414461a4bb7e115dccd779/v2105/en-US/63577f67a67347bf9f4765a5385ead33.html
On the help page the example expects the index.html not to be in the browser directory. However, the build on the cloud is working perfectly fine, but not the prebuild approach.

Cheers

**Tell us the version of Spartacus**
- Library version: 4.1

**To Reproduce**
- Prebuild angular
- Trigger a cloud build
- Expect the prebuild to be used

**Expected behavior**
I would expect the cloud to use the already existing `dist/` folder and not run `yarn install` and `yarn build:ssr` again

**Comment by Exotelis** [comment]
I pointed this topic out in another issue already https://github.com/SAP/spartacus/issues/7993 but I was asked to create a dedicated issue, so here it is :)

**Comment by Xymmer** [comment]
closing as this issue is one that's been reported in SAP ticketing system, but also not for Spartacus code itself but for how builds are run (separate team and they don't use github).
