### ISSUE TITLE
Improve SR a11y of TabParagraphContainer component

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15477]
**Description**:
Initially, screen reader support for TabParagraphContainer component was made specific to the instance in PDP. The component is generic and also being used in Order History UI to display order related tabs. As seen in the image below, the component instance is exposed to screen reader API as a region, 'Tab group with more product details'.
<img width="1536" alt="Screen Shot 2022-03-29 at 1 29 04 PM" src="https://user-images.githubusercontent.com/49131189/160670643-d5ac66a2-a756-4cfe-abf2-3b196fd1a221.png">

**Expected** :
Generic screen reader support for TabParagraphContainer component

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

OK now. It says Order History Details.
![OrderHistory1](https://user-images.githubusercontent.com/45409515/164751606-2c62f3dd-b9aa-46bc-899a-223a90effd7b.png)
![OrderHistory2](https://user-images.githubusercontent.com/45409515/164751610-9a3a894e-9ae6-442a-adad-23ca8d2542e8.png)
