### ISSUE TITLE
Address type augmentation

### ISSUE THREAD

**Issue by lucadallavalle** [SAP/spartacus#15492]
Hi,
I see in the [public_api.ts](https://github.com/SAP/spartacus/blob/develop/projects/core/public_api.ts) that the [Address](https://github.com/SAP/spartacus/blob/develop/projects/core/src/model/address.model.ts) entity is not exposed for augmentation.
It would be useful for us because we are going to add custom property to it.

Is there a reason for that? Is it planned? Would you like a PR?

Thanks.

**Comment by Xymmer** [comment]
Hi! sure thanks send us a pr, unless we get to it first :)

**Comment by Xymmer** [comment]
also let's backport to 4.x.

**Comment by znikola** [comment]
Hi @undrivendev, here's a PR for the latest 4.3.x (#15551), and 5.0 (#15550).
You can monitor them to see when they're merged, and the change will be released in the next 4.3.x release.

**Comment by lucadallavalle** [comment]
Hey @znikola, thank you very much. I wanted to give it a shot, but you got it earlier :) .
