### ISSUE TITLE
CMS Component with Angular Child Routes not working correctly

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#15509]
**Describe the bug**
We have built a CMS Component which uses Angular Child routes. Doing so, we have followed the Documentation [here](https://sap.github.io/spartacus-docs/adding-and-customizing-routes/#adding-angular-child-routes-for-a-content-page) and also looked at the Storefinder Implementation of Spartacus itself.

**Tell us the version of Spartacus**
- Library version: 4.3

**To Reproduce**
Problem 1:
Steps to reproduce the behaviour:
1. Create a CMS Component which defines a child Route `my-child` in it's module by following the [Spartacus Documentation](https://sap.github.io/spartacus-docs/adding-and-customizing-routes/#adding-angular-child-routes-for-a-content-page) and the respective child component
2. Add a Link pointing to the child component by using `<button [routerLink]="['/my-page/my-child']">Link to child component</button>`
3. Add this component to a hybris content page with the label `/my-page`
4. Open this Page in your Spartacus Instance
5. Click on the button leading to the child page
6. Instead of navigating to the child component, Spartacus tries to load a cms page with the label `/my-page/my-child`

Problem 2:
Steps to reproduce the behaviour:
1. Do the above steps 1-3
2. Open a new Browser Window and enter the full URL including the child route
3. This is also trying to load a content page with the label `/my-page/my-child` instead of recognising the child route and just returning the page data of the page `my-page`

**Expected behaviour**
1. Navigating to a child component within a CMS Component works as described in the Documentation
2. Doing a full page reload on an URL of a CMS page including a route of a child component works (As it does on the [storefinder page](https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/store-finder/view-all)

**Desktop (please complete the following information):**
 - OS: all
 - Browser all
 - Version all

**Smartphone (please complete the following information):**
 - Device: all
 - OS: all
 - Browser all
 - Version all

**Additional context**
Problem 2 seems to be cause, because the method `handleCmsRoutesInGuard` of the Service `CmsRoutesImplService` get's a list of Components, which already seems to be based on the wrong Page Call Data, which DOES NOT include the Component with Child routes anymore (because it was trying to load the CMS Page with the label `/my-page/my-child` which does not exist

Both described Problems seem to work for the storefinder component, which is also built using angular child routes. When Opening the Page https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/store-finder/view-all, the `pages` call seems to return the data for the root storefinder page. If there is additional care needed in that case (e.g. adjust the page controller to check for substrings matching a page label), I would expect to see a hint in the documentation..

**Comment by janwidmer** [comment]
It looks like, the above behaviour seems to happen only, if the page-label DOES NOT have a slash at the begin. With having a slash, it works correctly..

**Comment by Xymmer** [comment]
Hi janwidmer, we require that page labels start with slash, that indeed is source of the problem as you saw. Spartacus requires the slash (e.g. see https://sap.github.io/spartacus-docs/adding-and-customizing-routes/#adding-a-content-page-route). This seems to be also SmartEdit requirement, double-checking with that team to be sure.

**Comment by janwidmer** [comment]
@Xymmer would it be possible to add a small hint on this page https://sap.github.io/spartacus-docs/adding-and-customizing-routes/#adding-a-content-page-route regarding that slash and that it's required?
