### ISSUE TITLE
Update theme colors

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#15510]
Sparta and Santorini have updated primary accent colors that should be added to the color variables.

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

No AMP error on both sparta and santorini theme. 

<img width="1250" alt="Screen Shot 2022-04-22 at 9 55 07 AM" src="https://user-images.githubusercontent.com/45409515/164728700-d927f807-0207-44e2-8cc7-1140dadcbc54.png">

<img width="1101" alt="Screen Shot 2022-04-22 at 9 38 35 AM" src="https://user-images.githubusercontent.com/45409515/164728739-2a3d0720-30bf-4733-9e33-e1fc1816a7dd.png">
