### ISSUE TITLE
Custom Protocol Handler for Generic Links

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#15526]
While we can fix bugs/add handlers for protocols as they appear in generic links from the CMS, a custom protocol handler could be used to solve the issue instead of needing to upgrade to a patched version.

This handler would react to a given protocol within a link via regex and transform the link accordingly given custom logic.

See https://github.com/SAP/spartacus/pull/15429/files for an example of an OOTB protocol fix that needs to be backported.

There are many protocols that could occur, therefore we should add this custom handler to avoid back porting for every fixed/added OOTB handler: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-href

**Comment by Zeyber** [comment]
Will need back porting to `4.x` and `3.x` along with https://github.com/SAP/spartacus/pull/15429

**Comment by Zeyber** [comment]
Backporting to 4.3.x and 3.4.x: 
- https://github.com/SAP/spartacus/pull/15559
- https://github.com/SAP/spartacus/pull/15558

**Comment by Platonn** [comment]
What to QA:
Customize (extend) the behavior of `GenericLinkComponentService` so that `cx-generic-link` component recognizes custom protocols (like `android://` or `data:`) as external links (don't treat them as local SPA navigations).

**Comment by Matejk00** [comment]
QA done. Tested on localhost, with shell app crated from `release/4.3.x` branch.

Links starting from `tel:` and `mailto:` redirects to specific external apps.

All external links for protocols (http, https) are working properly, also I extended `GenericLinkComponentService` and same result was for `ftp`. 

![Screenshot 2022-04-22 at 13 54 47](https://user-images.githubusercontent.com/6958810/164710104-8c1bc76a-7ea6-4255-85e0-c3327e05705b.png)

However I noticed some issue for `data:` and `android://` protocols, when I wanted to navigate through those links in browsers prepends target with "unsafe:" keyword. 

![Screenshot 2022-04-22 at 13 54 03](https://user-images.githubusercontent.com/6958810/164710841-33622ebe-9ee1-418d-a9b1-f03ff234e678.png)
![Screenshot 2022-04-22 at 13 55 26](https://user-images.githubusercontent.com/6958810/164710845-5a9b1a8f-b70e-4a34-a365-b1f1ad73f604.png)

After click on it I'm getting error in a console:

```
Failed to launch 'unsafe:data:,Hello' because the scheme does not have a registered handler.
```

In theory it is possible to access this address from browser perspective.

![Screenshot 2022-04-22 at 14 11 05](https://user-images.githubusercontent.com/6958810/164712265-85c71979-fa67-4f98-9bc5-05c2805d3aff.png)

@Zeyber @Platonn 
Do you have any thoughts on that?

**Comment by Zeyber** [comment]
I would say that users can add handlers for that `unsafe:` appending if it occurs.
