### ISSUE TITLE
Default value of $font-url in styles.scss could not be overwritten by customers

### ISSUE THREAD

**Issue by wangzixi-diablo** [SAP/spartacus#15534]
**Describe the bug**

For certain reasons ( refer to this stackoverflow [discussion](https://stackoverflow.com/questions/71705078/sap-spartacus-sparta-theme-requesting-open-sans-by-default-not-dsgvo-complia) for detail ) some customers would like to overwrite the default value of variable `$font-url` in styles.scss. When customers set new value to variable `$font-url`, the new value does appear in compiled `style.css`. However, the default value `https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700` still remains in compiled `style.css`. As a result, both fonts will be loaded in the runtime. Customer would like the default font is NOT loaded any more.

**Tell us the version of Spartacus**
- Library version: 4.1

**To Reproduce**
1. Create a new Storefront using schematics via command line:

`ng add @spartacus/schematics@4.1`

2. open styles.scss file in src folder, overwrite the `$font-url` value with below code:

```scss
/* You can add global styles to this file, and also import other style files */

$font-url:'https://fonts.googleapis.com/css?family=Tangerine';
$styleVersion: 4.1;
@import '~@spartacus/styles/index';
```

3. the default font url still exists in compiled `style.css`, as a result it is still loaded in the runtime:

![image](https://user-images.githubusercontent.com/58975336/161548541-2ea01125-4883-472d-b982-86613054f528.png)

![image](https://user-images.githubusercontent.com/58975336/161548707-b7d8c174-22db-4364-9e11-c9a3d3a7e3b6.png)

**Expected behavior**

Only the customized font url is loaded in the runtime. The default font url, `https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700`, should **NOT** be loaded.

**Comment by Xymmer** [comment]
Are all of these related? #15534, #12714, #15425?
Can we backport to 3.x and 4.x?

**Comment by wangzixi-diablo** [comment]
additional comment: Customers also expect the variable `$font-url` should have possibility to be empty, so that they can skip totally the loading of additional fonts(Google font web API).

The business reason behind is: Since 2022 using Google Fonts over their web api is no longer data protection compliant in some country and the font loading should be suppressed accordingly.

**Comment by developpeurweb** [comment]
@Xymmer 
The **Google Font** issue specifically has been addressed before on ticket GH-13563, but I think there are some limitations as to how it will work on `>= 4.1` vs `5.0`. From what I read this is still shaky on minor releases, but works well on majors. Caine and Mateusz work on this, so they probably know more about how the fix works.

**Comment by Xymmer** [comment]
will finish this one off in jira
