### ISSUE TITLE
Spike B2B Punchout

### ISSUE THREAD

**Issue by szczepaniak-michal** [SAP/spartacus#15549]
https://jira.tools.sap/browse/CXSPA-194

**Comment by FollowTheFlo** [comment]
Punchout docs on Portal with intro, backend architecture, data flow: https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/2011/en-US/8ac40cf08669101486f5ce44920c3f91.html

**Comment by FollowTheFlo** [comment]
wiki where all the info are gathered:
[https://wiki.wdf.sap.corp/wiki/display/spar/B2B+Punchout](https://wiki.wdf.sap.corp/wiki/display/spar/B2B+Punchout)

**Comment by Xymmer** [comment]
moved to jira
