### ISSUE TITLE
UserID still anonymous when register as Guest

### ISSUE THREAD

**Issue by MedKhaldiConfo** [SAP/spartacus#15546]
**Describe the bug**
When register as a guest, the userID still anonymous.

**Spartacus version**
- Spartacus : 3.2.1

**To Reproduce**
1. Register as Guest
2. Checking OCCs calls from FE
3. userID still anonymous

**Expected behavior**
For guest users, the userID sould be current instead of anonymous.

**Comment by bgambocjaviniar** [comment]
I believe it is proper and should be anonymous. 

More information can be found here https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/2105/en-US/8adb50aa866910149533e8c748b730c9.html

But it states that guest users are anonymous users

**Comment by Xymmer** [comment]
closing as we think we answered this question, but let me know by reopening if not.
When you "register as guest" you're actually sending your email to the backend for creation of a unique guid, to have permanent identification for order. It's kind of made into a one-off identifiable cart. But you're still considered anonymous user as far as backend says.
