### ISSUE TITLE
Order approval details table is broken

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#15555]
The order approval details table is broken because of the table refactor.

**To Reproduce/QA:**

1. login as Anthony Lombardi.
2. order a few things.
3. go to order history and select the order.
4. scroll to the bottom of the page.

**Comment by KateChuen** [comment]
Tested locally using develop branch. 

Tested on chrome, firefox and safari. 
And different viewports. OK on desktop and Mobile. The headers are missing on the tablet viewport. Opened ticket https://jira.tools.sap/browse/CXSPA-524


<img width="1262" alt="Screen Shot 2022-05-27 at 10 49 39 AM" src="https://user-images.githubusercontent.com/45409515/170724578-939ca444-0fe6-4910-bc27-8d7f002d6494.png">

<img width="436" alt="Screen Shot 2022-05-27 at 10 50 16 AM" src="https://user-images.githubusercontent.com/45409515/170724553-93c909aa-1ab4-47d9-862a-b8135254a487.png">

<img width="434" alt="Screen Shot 2022-05-27 at 10 50 01 AM" src="https://user-images.githubusercontent.com/45409515/170724566-cdcf5420-3a45-405c-b84f-9b95fac542c2.png">
