### ISSUE TITLE
Improve styling of Breadcrumbs after previous refactor for SR

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15553]
This PR, #14095, introduced a change to the layout of breadcrumbs navigation, `markup structure change from nav > span > a to nav > ol > li > a`, and this change added a margin to the navigation nodes, see screenshot below:

<img width="1124" alt="Screen Shot 2022-04-05 at 11 58 01 AM" src="https://user-images.githubusercontent.com/49131189/161796241-9d0de447-2d83-4deb-823c-de836cb75e8a.png">

Set styling back to previous state (ss taken from 4.2):

<img width="1118" alt="Screen Shot 2022-04-05 at 12 01 52 PM" src="https://user-images.githubusercontent.com/49131189/161796708-c8a164ec-4080-4b60-95cd-32fce651e070.png">

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

![breadcrumbs1](https://user-images.githubusercontent.com/45409515/164487325-6d61b056-03f0-4f40-ba67-e30f2abb2e55.png)

![Screen Shot 2022-04-21 at 10 58 30 AM](https://user-images.githubusercontent.com/45409515/164487416-4b5225de-bbbd-48a9-8795-ec6870116553.png)
