### ISSUE TITLE
Adapt configuration related additions in cart to refactored tables

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#15566]
The cart view has been refactored to use real table-tags. Thus our additions don't fit (e.g. bundle items).
<img width="803" alt="Screenshot 2022-04-06 at 16 43 25" src="https://user-images.githubusercontent.com/54309425/162176587-87f2b451-2f91-42aa-b5b2-2055c0cd1fe3.png">

**Comment by developpeurweb** [comment]
@Larisa-Staroverova pls be aware of this ticket for grouping notifications, GH-15483 we are still waiting for a decision on mockups.

**Comment by JayEmKay-8** [comment]
For reference: this is what it used to look like before the table refactoring. Much easier to check and to grasp at a glance:
![Spartacus_CPQCameraBundle_Cart-mit-Items-und-issue](https://user-images.githubusercontent.com/54537803/179513106-6e9d60ad-983b-4037-b811-19cc5c09006d.png)
