### ISSUE TITLE
Improve SR a11y of Applied Filters on PLP 

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15562]
**Current Behavior**
Keyboard navigation through applied filters does not provide meaningful narration for screen reader users. 

**To Reproduce**
1. Go to any PLP with facets
2. Apply one or more filters
3. Tab through applied filters with a screen reader on
4. SR only vocalizes value of filter

**Expected behavior**
More context in SR vocalization

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.
![filter2](https://user-images.githubusercontent.com/45409515/164486375-59c5d341-f2c0-48a6-af89-e2044902a924.png)
![filter1](https://user-images.githubusercontent.com/45409515/164486380-b8625524-8ddb-4681-810e-51486ff184fc.png)
