### ISSUE TITLE
Align greeting name with search bar and cart button

### ISSUE THREAD

**Issue by BenjaminEmiliani** [SAP/spartacus#15591]
**Description**
The user greeting label is not aligned with all other elements at that level.
<img width="1149" alt="Screen Shot 2022-04-12 at 10 25 10 AM" src="https://user-images.githubusercontent.com/49131189/162984773-7b174869-3c39-45e1-8b02-849645d07dee.png">\
\
\
\
**Expected Layout**
Based on wireframe for Spartacus sample storefront, page header should be aligned as follows
<img width="1021" alt="Screen Shot 2022-04-12 at 10 27 37 AM" src="https://user-images.githubusercontent.com/49131189/162985303-885a1bd5-6f0a-4b2c-abe7-6016413a0333.png">

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

Alignment ok now.

<img width="1272" alt="Screen Shot 2022-04-13 at 2 04 13 PM" src="https://user-images.githubusercontent.com/45409515/163242767-ded00e33-a5ed-48be-9518-3a1aa46f6cb7.png">
