### ISSUE TITLE
Check if E2E test for stack messages is required

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#15609]
Up to now we have no E2E test for resolve issues banner on overview page.

If it is required, implement it.

**Comment by Uli-Tiger** [comment]
there is a test for resolve issues navigation:
**\spartacus\projects\storefrontapp-e2e-cypress\cypress\integration\regression\product_configurator\product-configurator-vc-cart.e2e-spec-flaky.ts Conflict Solver->should support the conflict solving process**

**Comment by Uli-Tiger** [comment]
- The existing test was enhanced to work with both flavors (pre 2205 and post 2205) by switching a boolean var.
- A new test was added for the 2205 resolve conflict behaviour.
- A new test was added for the existing resolve issues behaviour. It tests it isolated and more detailed then the existing cart test.
