### ISSUE TITLE
Punchout Link throws error with Dev11 server (v2205)

### ISSUE THREAD

**Issue by FollowTheFlo** [SAP/spartacus#15606]
**Describe the bug**
On test server Dev11(2205),  Punchout Accelerator URL throw an error 'server Error: PunchOut Exception'

**Tell us the version of Spartacus**
- Not Spartacus related, Accelerator and cx server 2205

**To Reproduce**
1. on Postman, open Collection JSON file: https://wiki.wdf.sap.corp/wiki/download/attachments/2834994437/punchout.postman_collection.json?version=1&modificationDate=1649694383000&api=v2
2. Set global variable 'hostname' with value 'spartacus-dev11.eastus.cloudapp.azure.com:59002/' (Make sure your IP is whitelisted, see https://wiki.wdf.sap.corp/wiki/display/spar/IP+Whitelisting)
3. Run request OCC Setup to generate Punchout URL. 
4. In response, between URL tag, open the generated URL -> Whiite page with 'server Error: PunchOut Exception'

**Expected behavior - works fine with Server Team server**
It is working fine with server provided by Etienne (server team) : cg79x9wuu9-eccommerc1-p1-public.model-t.myhybris.cloud
Using it as a workaround
<img width="1723" alt="image" src="https://user-images.githubusercontent.com/30024415/163415645-5d62133c-a38c-4723-98ae-667b8a8c7249.png">

**Screenshots of the problem with Dev11**
![image](https://user-images.githubusercontent.com/30024415/163415362-1649218e-a65b-4ed8-9c0a-924f6f025cfd.png)
<img width="1284" alt="image" src="https://user-images.githubusercontent.com/30024415/163415411-f3b8dde0-18ef-4971-aa97-60a2683f3d73.png">

**Comment by FollowTheFlo** [comment]
Tomcat logs show:
ERROR [hybrisHTTP39] [199.87.113.13] [DefaultPunchOutController] Unable to find customer for given credentials [[NetworkId,AN01000865920-T]]
INFO   | jvm 1    | main    | 2022/04/14 14:35:34.959 | de.hybris.platform.b2b.punchout.PunchOutException: Unable to find customer for given credentials [[NetworkId,AN01000865920-T]]

**Comment by FollowTheFlo** [comment]
AN01000865920-T not present on Dev11 Punchout Credential
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/30024415/164008182-305e18a6-7311-4b83-9115-1a02b47fe57a.png">

**Comment by Xymmer** [comment]
closing as it's now https://jira.tools.sap/browse/CXSPA-248
