### ISSUE TITLE
@spartacus/cart releases broken

### ISSUE THREAD

**Issue by WingmanImd** [SAP/spartacus#15676]
**Describe the bug**
The @spartacus/cart@4.3.0 release on github contains a "base" folder containing what seems to be a refactor of some sort.
The @spartacus/cart@4.3.0 yarn release does not contain this changes for some reason.

Furthermore the @spartacus/cart@4.3.1 release on github do not contain the changes from 4.3.0 but some 6 months old code(the one from the @spartacus/cart@4.3.0 release seems to be 3 months old). Same is true for @spartacus/cart@4.3.2. The yarn releases for this two seem to also be broken

Is this the expected behavior? The develop branch contains the newer 4.3.0 code and not the one in the yarn releases.

**Tell us the version of Spartacus**
@spartacus/cart@4.3.0-@spartacus/cart@4.3.1-@spartacus/cart@4.3.2

**To Reproduce**
Add @spartacus/cart@4.3.0 or above to your package.json and try to use this:
`import { ActiveCartFacade, Cart } from '@spartacus/cart/base/root';` - this will throw an warning as the requested export just do not exist

If you look in your node_modules folder the  code in @spartacus/cart seems to be the old one

**Expected behavior**
Get the code from @spartacus/cart@4.3.0 github release

**Comment by Xymmer** [comment]
"base" folder should not have been included in 4.3, we checked our latest 4.3.x... the "base" was likely a mistake that was corrected later. Closing but let us know if there is an issue.
