### ISSUE TITLE
Sometimes base site is missing from the request url.

### ISSUE THREAD

**Issue by emAsif** [SAP/spartacus#15694]
**Describe the bug**
Base site is missing sometimes when network request is sent (while getting orgunit using UserAccountFacade and OrgUnitService)

**Tell us the version of Spartacus**
- Library version: [4.1.1]

**To Reproduce**

1- When we use the UserAccountService to get the current orgunit uid.

2- Request is made to the 'orgUsers/${userId}' to get the current uid fails. Base site is missing from request url one out of five times when we refresh the page with that particular component making the request.

3- failed request can be viewd in the network and error can be viewed in the network's response tab.

**Expected behavior**

I would expect the Base site to be added to the request url every time the request is made.

**Error Output**

expected request url: https://localhost:9002/occ/v2/haba-proDE/orgUsers/current?fields=FULL&lang=de&curr=EUR

current request url: https://localhost:9002/occ/v2/orgUsers/current?lang=en&curr=USD

```
Network response error: '{
   "errors" : [ {
      "message" : "Base site orgUsers doesn't exist",
      "type" : "InvalidResourceError"
   } ]
}'
```

ps: 'base site can be seen missing from the current behaviour of the response being generated which happens one out of five times on average when the page is refreshed'

**Desktop (please complete the following information):**
 - OS: [iOS]
 - Browser [chrome, safari]
 - Version [12.3.1]

**Additional context**
code scenario: Getting the orgunit uid using the UserAccountService(extending  user interface) and then getting the orgUnit for the current user using OrgUnitService.

All services used were out of the box spartacus provided services.

**Comment by dev-jan** [comment]
We experience the same issue, but with the current user Endpoint. Example:

```
https://SAP-COMMERCE-BACKEND/occ/v2/users/current?lang=en&curr=USD
```

The base site is also missing in this request. It worked with Spartacus 4.2.0, but with Spartacus 4.3.3, this bug exists.

Do you have any solution or workaround? As this failing request blocks our checkout, so we cannot work with the new Spartacus Version. Also, using the old version is not an option for us, since it contains other bugs.

Thanks for your help!

**Comment by janwidmer** [comment]
@emAsif our problem was caused because we initialized some services from within the spartacus tracking module.. we moved it into our application and now, the base site is always there..

**Comment by Xymmer** [comment]
Hi, we think this is configuration, closing but reopen if not.

In backend we have config for prefix of "org" for b2b, then yes then b2buser will be "orguser" (which is default).
if false, then for b2b it's not orguser, just user, but that's for backwards compatibility reasons. 
In Spartacus we use only orguser, which is recommend as this is the default ootb backend config going forward.

However, you can change what Spartacus users in endpoint configuration.

Example replace endpoint in your app:

```
const defaultB2bUserAccountOccEndpoints: UserAccountOccEndpoints = {
  user: 'orgUsers/${userId}',
};

const defaultB2bUserProfileOccEndpoints: UserProfileOccEndpoints = {
  userUpdateProfile: 'users/${userId}',
  userCloseAccount: 'users/${userId}',
};

const defaultB2bCartOccEndpoints: CartOccEndpoints = {
  addEntries: 'orgUsers/${userId}/carts/${cartId}/entries?quantity=${quantity}',
};

const defaultB2bOrderOccEndpoints: OrderOccEndpoints = {
  placeOrder: 'orgUsers/${userId}/orders?fields=FULL',
  scheduleReplenishmentOrder:
    'orgUsers/${userId}/replenishmentOrders?fields=FULL,costCenter(FULL),purchaseOrderNumber,paymentType',
};

export const defaultB2bOccConfig: OccConfig = {
  backend: {
    occ: {
      endpoints: {
        ...defaultB2bUserAccountOccEndpoints,
        ...defaultB2bUserProfileOccEndpoints,
        ...defaultB2bCartOccEndpoints,
        ...defaultB2bOrderOccEndpoints,
      },
    },
  },
};
```

**Comment by emAsif** [comment]
@Xymmer Following are the configuration we are using and here everthing seems to be fine regarding orgUser.

```
const defaultB2bUserAccountOccEndpoints: UserAccountOccEndpoints = {
  user: 'orgUsers/${userId}'
};

const defaultB2bUserProfileOccEndpoints: UserProfileOccEndpoints = {
  userUpdateProfile: 'users/${userId}',
  userCloseAccount: 'users/${userId}'
};

const b2bCheckoutOccEndpoints: CheckoutOccEndpoints = {
  setDeliveryAddress: 'orgUsers/${userId}/carts/${cartId}/addresses/delivery',
  placeOrder: 'orgUsers/${userId}/order?fields=FULL'
};

@NgModule({
  declarations: [],
  imports: [],
  providers: [
    provideConfig(layoutConfig),
    provideConfig(mediaConfig),
    ...defaultCmsContentProviders,
    provideConfig(<OccConfig>{
      backend: {
        occ: {
          baseUrl: environment.occ.baseUrl,
          prefix: environment.occ.prefix,
          endpoints: {
            ...defaultB2bUserAccountOccEndpoints,
            ...defaultB2bUserProfileOccEndpoints,
            ...b2bCheckoutOccEndpoints,
            addEntries: 'orgUsers/${userId}/carts/${cartId}/entries?quantity=${quantity}',
            placeOrder: 'orgUsers/${userId}/orders?fields=FULL',
            scheduleReplenishmentOrder:
              'orgUsers/${userId}/replenishmentOrders?fields=FULL,costCenter(FULL),purchaseOrderNumber,paymentType',
          }
        }
      }
    }),
...
...
```
