### ISSUE TITLE
The Schematics tool generates wrong versions of Spartacus library dependencies

### ISSUE THREAD

**Issue by shanyang78** [SAP/spartacus#15695]
Please follow the steps below to reproduce the issue:
1, use "ng new mystore --style=scss" to create a new angular project
2, use "ng add @spartacus/schematics@2.0.1 --baseUrl https://spartacus-demo.eastus.cloudapp.azure.com:8443 --occPrefix /occ/v2/ --baseSite=electronics-spa" to add library dependencies, including Spartacus libs.

Instead of generating version 2.0.1 Spartacus library dependencies, it generates version 2.1.9 Spartacus library dependencies as of April 2022.

**Comment by Xymmer** [comment]
asking Nik for background info

**Comment by Xymmer** [comment]
we'll want to fix this in 5.x
