### ISSUE TITLE
Not able to login and create carts and orders 

### ISSUE THREAD

**Issue by sachinmalvi1983** [SAP/spartacus#15745]
Hi Team,
I'm using SAP Hybris 2105 version and installed Spartacus as per given steps in below link
https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2105/

I'm using B2B storefront for which I'm not able to login with any of customer however I am able to login via Hybris storefront.
For carts/login I'm getting below error.

Full authentication is required to access this resource UnauthorizedError

- Library version: [e.g. latest]

1. Go to(https://localhost:4200/powertools-spa/en/USD/login
2. Enter credentials and Click on Sign-In 
![image](https://user-images.githubusercontent.com/105030416/168288747-e83a9094-ab44-4010-b38a-944d4cab81e1.png)
4. After login site redirects to home page with below error  
![image](https://user-images.githubusercontent.com/105030416/168306075-995f04fb-4867-4e48-9e55-cfca29656a6f.png)

Add to cart functionality also does not work. After adding item to cart it says "This item was already in your cart. The quantity was updated." but could not see cart

![image](https://user-images.githubusercontent.com/105030416/168306386-4d838f71-297c-4237-864a-2f7aad9f0de5.png)

On Cart page seeing below error
![image](https://user-images.githubusercontent.com/105030416/168306759-230cc497-b2a8-449c-aaca-4b5991e17c23.png)

**Expected behavior**
Entire B2B functionality should work.

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Chrome
 - Chrome Version [101.0.4951.41 (Official Build) (64-bit)]

**Additional context**

**Comment by Xymmer** [comment]
Hi sachinmalvi1983, there are 2 possible reasons:
- when setting up spartacus as a b2b store, you have to install at least one b2b feature. it's because b2c and b2b are considered two different "channels" (in backend parlance)
-  also make sure that you have imported the default user/passwords, but unlikely this is the reason for this problem
closing as i think that will solve it, but reopen if not
