### ISSUE TITLE
Conflict group renders only on second click

### ISSUE THREAD

**Issue by JayEmKay-8** [SAP/spartacus#15755]
Spartacus connected to P3 and RR5.
Product: RR5 Home Theater VC Configurator (CPQ_HOME_THEATER)

When solving conflicts and clicking on the conflict group, the conflict group doesn't render but only shows a yellow line. Only on the second click does the conflict group render.
This doesn't happen all the time, but it happens often enough. Not sure what the trigger is.

See attached video.

https://user-images.githubusercontent.com/54537803/168603812-9a8d2be0-4f89-4983-8679-df0f62187258.mp4

**Comment by ChristophHi** [comment]
@JayEmKay-8 I took a close took and saw that this is a pure backend issue (another that is related to non-sticky sessions that we are facing here). See https://jira.tools.sap/browse/CXIEP-1538.
