### ISSUE TITLE
BLOCKED Number of issues deviate on overview and config page

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#15758]
Blocked, could be a consequence of https://jira.tools.sap/browse/CXEC-11739

Spartacus connected to P3 and RR5.
Product: RR5 Home Theater VC Configurator (CPQ_HOME_THEATER)

On overview page the message "1 issue must be resolved before checkout" is displayed. When navigating to the configuration page the issue is not visible (neither any error message nor a group is marked erroneous).
See attached video.

 

https://user-images.githubusercontent.com/54309425/168808928-6afb14ee-0131-4550-8016-bfd4f66b53f4.mp4

**Comment by ChristophHi** [comment]
Closing ticket, as it's a pure backend issue (https://jira.tools.sap/browse/CXEC-11739)
