### ISSUE TITLE
Order History not reloaded upon placing new order / entering order history list

### ISSUE THREAD

**Issue by zuzanna-bialecka** [SAP/spartacus#15806]
**DESCRIPTION**
Entering the order history page after placing an order DOES NOT reload the list of orders. It is taken from cache even if there was an order placed in the meantime. 

**VERSION**
- Library version: 4.3.4

**STEPS TO REPRODUCE**
1. Go to my account / order history
2. Place a new order
3. Go back to my account / order history
4. In most cases the new order is NOT visible until the cache is invalidated
5. Change to a different page -> if the page was not yet cached proper list of orders will be visible

**Expected behavior**
The order list is reloaded each time a new order is placed or an order update is received. 

**Screenshots**
![Order History Magic 2](https://user-images.githubusercontent.com/106664100/171379633-7a744580-8a86-4351-8029-b613149db733.gif)

![ORDER HISTORY MAGIC](https://user-images.githubusercontent.com/106664100/171377450-5811b92d-201a-46e2-9575-9130a0cb353d.gif)

**Desktop (please complete the following information):**
 - OS: MacOs
 - Browser: chrome, safari, firefox

**Additional context**

**Comment by WeizhengSap** [comment]
Each time we go to order history page, there is an OCC request sent to get the order history data. 
I did this testing: user has 3 orders, then place a new order. Go to history page, there are still 3 orders. The data got from backend is not updated. So, there is nothing we can do in Spartacus.
![Screen Shot 2022-06-03 at 11 14 47 AM](https://user-images.githubusercontent.com/44440575/171871952-976860e8-3aee-498a-872e-c0a41eda1c31.png)

**Comment by Xymmer** [comment]
hi zuzanna, if you are a customer or partner dev (not sure :) - best to create a support ticket.
if SAP dev create jira
