### ISSUE TITLE
Account Home Page

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#1582]
The goal of this spike is to find a solution to implement the Account Home Page.

https://98qkkl.axshare.com/#g=1&p=w_account_home

If the wireframe is not already updated: the Account Home Page will be composed exclusively of "Navigation Tiles".

The ideal way to implement these tiles is to create an additional CMS type for it on the backend.

However.

The goal of this spike is to find the next **best solution that does not require a backend update**.
The main reason for that to make sure the account profile features can work in a backwards compatible way.

Any solution can be considered:

- Use Paragraph components
- Use an existing link component and style it with CSS
- Use CSS in creative ways to add the image and/or the box look for the links.
- Revise the design to accommodate a specific solution ( drop the image and/or the description for example and use some existing link component from the CMS )
- Hardcode the account home nav cards in an angular component.

**Comment by tobi-or-not-tobi** [comment]
@plabadie just want to make you aware of some analysis I did for navigation related data models and usage in the backend: https://wiki.hybris.com/display/prodandtech/CMS+Navigation. It's not finalised, but you might understand where I like to go with this.

**Comment by Xymmer** [comment]
do we have 2 tickets for this? stretch for 2.1
