### ISSUE TITLE
multicountry sample data

### ISSUE THREAD

**Issue by jquenee** [SAP/spartacus#15834]
Since SAP Commerce 2205, multicountrysampledataaddon is deprecated. Please consider to add/adapt this sample data for Spartacus. That will be nice feature to demonstrate how Spartacus can run in multi-country context with common and specific content catalog.

https://help.sap.com/docs/SAP_COMMERCE/4c33bf189ab9409e84e589295c36d96e/6ef452c6eb274e35a14ad49e32a8c5e7.html?locale=en-US&version=2205&q=multicountrysampledataaddon

**Comment by Xymmer** [comment]
hi jquenee! thanks for the submission, moving this to our internal jira for investigation
