### ISSUE TITLE
Allow providing a custom initializer for i18next in a more flexible way

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#15861]
## Overview

To be able to provide a custom initializer (`i18nextInit()`) for i18next you have to copy/paste:

- Injection token `I18NEXT_INSTANCE`
- function `i18nextAddTranslations()`
- class `SiteContextI18nextSynchronizer`
- function `i18nextGetHttpClient()`
- function `getLoadPath()`

## Expected behavior

We should be able to provide a custom initializer for i18next, it's extremely useful especially if you want to use more opportunities from i18next or additional features, for [example](https://github.com/SAP/spartacus/issues/13460#issuecomment-1157614046).

## Workaround

We still can provide a custom initializer by:

1. Copying the above-mentioned implementations
2. Provide a custom `I18nextTranslationService` with the custom `I18NEXT_INSTANCE`

## Environment details

Spartacus: 3.4.10

## Additional context

Besides that, by doing this copy/paste, the application creates two instances of `i18next`, you can easily check it in heap snapshots. I didn't notice any drawbacks from this, but in theory, it's not normal to have these two instances, since we don't need them.

**Comment by Xymmer** [comment]
Hi artem-zur, we'll move this ticket as improvement in our internal jira, thx!

**Comment by artem-zur** [comment]
Thanks, @Xymmer!

Any chance we can track progress somehow?

**Comment by stefanlange** [comment]
Is there any progress here?
