### ISSUE TITLE
Change Overview structure, that subgroups are inside the parent group div to enable easier stickyness

### ISSUE THREAD

**Issue by schuppell** [SAP/spartacus#15897]

**Comment by steinsebastian** [comment]
For testing the new sticky group headers:
In projects/storefrontapp/src/app/app.module.ts set "level" to 5.1
In projects/storefrontstyles/scss/_versioning.scss set the following:
$_fullVersion: 5.1;
$_majorVersion: 5;
$styleVersion: 5.1 !default;
