### ISSUE TITLE
Localisation of configurator prices, texts and numeric values

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#15905]
Run SPA/commerce electronics-spa store with its default customizing,
(1) On changing language from ‘en’ to ‘de’ in SPA, numeric formatting of prices doesn’t change in cart and product details. Texts for translated CMS entities change however
(2) When entering the configuration screen, the texts for attributes and values don’t change. Also the price formatting doesn’t change (like in cart). But validation of numeric attribute values changes, the comma is required as decimal separator e.g.

**Comment by ChristophHi** [comment]
Reason: Parts of formatting is done on UI, parts in commerce. Moreover, the rules for deriving countries from locales that don’t specifiy a country deviate.
For prices, formatting is done in commerce. Commerce does not associate a country per default with a language ‘en’ or ‘de’. So when changing ‘en’ to ‘de’, the used formatter stays the same. See DefaultPriceDataFactory in commercefacades
Solution: Introduce commerce languages ‘en_US’ and ‘de_DE’. Adapt the SPA customizing for supported locales, see  /default-site-context-config.ts
The validation and formatting of numeric attributes is done based on frontend (ng) tools however. Here, a switch from ‘en’ to ‘de’ will directly lead to a different display according to locales, as ng assumes US as default for ‘en’ locale and Germany for ‘de’ locale. Reason for that is that we wanted to give the end user fast feedback on wrong formatting and don’t trigger a roundtrip to the backend.
Note that the attribute and value texts won’t change when editing a cart configuration, that’s independent from a locale change that happened after a product has been put to the cart
