### ISSUE TITLE
Order Confirmation Template Page is not Opening in SmartEdit in [Preview and Advance Edit mode ]

### ISSUE THREAD

**Issue by suhashankare** [SAP/spartacus#15938]
Order Confirmation Template Page is not Opening in SmartEdit , its redirecting to Home page [in Preview and Advance EDIT mode]

Added SmartEditLauncherService check in application but still its not working

**Comment by Xymmer** [comment]
Hi suhashankare, the way SmartEdit works, you have to place an order to see it
