### ISSUE TITLE
[SPIKE] New CMS Component Type for Account Home Page 

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#1594]
The goal of this spike is to find the cleanest way to implement the "Navigation Boxes" on the Account Home Page.

https://98qkkl.axshare.com/#g=1&p=w_account_home

If the wireframe is not already updated: the Account Home Page will be composed exclusively of "Navigation Tiles".

The ideal way to implement these tiles is to create an additional CMS type for it on the backend.

We could extend the Link component and add a description and an image.

Evaluate if the image could be better driven by CSS.

**Comment by Xymmer** [comment]
we realized we don't need it
