### ISSUE TITLE
Wrong product is shown when order is selected from the Order History first time.

### ISSUE THREAD

**Issue by AlexanderKuschner** [SAP/spartacus#15964]
To reproduce:

- Create two orders: first one with any product P1 and second one with any product P2

- Go to Order History (Orders), select the first order TWICE -> Correct product P1 is shown.

- Select the second order one time from the Order History -> Issue: Product P1 from the first order is shown.

- Select the second order second time from the Order History -> Correct product P2 is shown.

**REMARK: The issue can be reproduced only when connection between SPA and Commerce is "fast".** So I was able to reproduce the issue when SPA and Commerce were installed locally on my PC. When I used Commerce on another Server (different from my local PC) I was not able to reproduce this issue.

**Comment by ChristophHi** [comment]
Cannot be reproduced, seems to be an issue of local commerce environment.

**Comment by ChristophHi** [comment]
After Sascha made me aware of the fact that for him it also does not occur when using a remote commerce backend: 
Could also reproduce that with a local commerce environment, hence re-opening. I am using B2B, no ASM

**Comment by Xymmer** [comment]
make sure to create corresponding jira issue as we track all issues in internal jira now
also note we create 5.0.x maintenance already

**Comment by ChristophHi** [comment]
@Xymmer That has nothing to do with VC, hence removing the label. 
And what is the project for creating the JIRA issue? Are we allowed to create issues there?

**Comment by ChristophHi** [comment]
Will close, copy created as https://jira.tools.sap/browse/CXSPA-1052
