### ISSUE TITLE
Reset all facets/applied filters on PLP

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#16068]
**Is your feature request related to a problem? Please describe.**
The problem is that in Spartacus there is no build-in method to easily clear all applied filters on the PLP page.

**Describe the solution you'd like**
There should be a method to clear filters state with query parameters.

**Comment by ZakTreister** [comment]
@dydome 
Because the filtering is relying on the routing all you really need to do is create a link to an empty route:

 `<button
        routerLink="./"
        [queryParams]="null"
        >
        {{ 'facet.clearAll' | cxTranslate }}</button>`

**Comment by dydome** [comment]
@ZakTreister it is not right, there is possible that you have other queryParams for sorting for example or for any other staff. Your proposition clearing everything not only facets... :(

**Comment by ZakTreister** [comment]
@dydome 
You are right. I checked again in the search response and I see that I have a propertey breadcrumbs[0].removeQuery.query.value that's value seems to remove the filters while leaving the sorting

**Comment by dydome** [comment]
@ZakTreister  This value is *new query params state without that one particular facet not all

**Comment by ZakTreister** [comment]
You are right

**Comment by Platonn** [comment]
You can remove a single queryParam from the current url (in this example, it's called `query`) e.g. with the following code snippet:

```ts 
    this.router.navigate([], {
      queryParams: {
        query: null, // resets the `query` queryParam
      },
      queryParamsHandling: 'merge', // leaves other all existing queryParams
    });
```
