### ISSUE TITLE
Yotpo integration is somewhat insecure

### ISSUE THREAD

**Issue by meeque** [SAP/spartacus#16072]
**Describe the bug**
Well, not exactly a bug, let alone a vulnerability, but there is room for improvement.

**Tell us the version of Spartacus**
- Library version: _develop branch in this Git repo_

**To Reproduce**
1. Conduct a code review.
2. Go to [YotpoService](../blob/develop/projects/vendor/src/yotpo/service/yotpo.service.ts).
3. **A:** Observe that the `constructor` dynamically loads JS code from a 3rd-party origin.
4. **B:** Observe that the `addYotpoInitWidgetsScript` inserts a inline JS block (with hardcoded JS code).

**Expected behavior**

* **A:**
  * Ideally, host the JS as part of the Spartacus `YotpoModule` instead.
  * Or, enforce [Subresource Integrity](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity).
  * If none of the above is feasible (e.g. because the vendor updates the JS file often and older versions become incompatible):
    * At least add an additional guard. Do not load the JS, if no `appToken` is configured. Legitimate use won't work without it anyway. 
    * Feel free to log missing `appToken` to the console, when in dev mode.
    * Document how Spartacus users can allow-list the 3rd-party origin in their [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), without weakening it too much.
* **B:**:
  * Ideally, move the JS code to a separate, self-hosted JS file. Can also be part of a bundle.
  * Or, enforce _Subresource Integrity_.
    * And document how Spartacus users can allow-list the inline JS block in their _CSP_, **without** resorting to `unsafe-inline`.
  * Also consider wrapping the whole JS snippet in an anonymous function call, in order to prevent pollution of the global JS namespace.
    * That is, wrap code in `(function() { /* ... */ })()`.

**Additional context**
No big deal, but some basic hygiene would be nice;-)

**Comment by giancorderoortiz** [comment]
Closed. To be handled internally in https://jira.tools.sap/browse/CXSPA-1112
