### ISSUE TITLE
Attempts to login with wrong credentials many times does not lock the account

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#1622]
In ACC, there's an implementation where after 5 failed login attempts, the account gets locked. 
However, on SPA, the account doesn't get locked. 

Tried adding this property oauth2.maxAuthenticationAttempts=3, and this didn't work either.

Gustavo found an implementation on platform side, and a test on OCC side. But will need more investigation.

**Comment by Xymmer** [comment]
need backend update

**Comment by giancorderoortiz** [comment]
Related to #3690

**Comment by giancorderoortiz** [comment]
But in fact, a front end mechanism should be put in place to avoid locking an account by mistake and decreasing the effectiveness of a brute force attack. 

Let's take for example a 3 attempts scenario (which is customary). 
After the second attempt, a warning should be displayed to the user indicating that the account may be locked afterwards. 
After the third attempt, there should be some sort of delay mechanism that doesn't let the user retry a login until a period of time has passed. (I have seen this in banking applications, for example). 

Yes, I agree that If backend policy regarding max login attempts is not set, then the user account is vulnerable to a brute force attack. However, the frontend shouldn't make it straight-forward. 

With Burp, I am able to generate brute force attacks that generate hundreds of permutations per second.

**Comment by giancorderoortiz** [comment]
https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/1905/en-US/28cfbf93784640d09929ee4e9b97ba1e.html?q=brute%20force%20prevention

**Comment by giancorderoortiz** [comment]
Actually able to lock account after n unsuccessful attempts. Based on backoffice configuration. Closing ticket. 

![Screen Shot 2020-11-16 at 6 16 28 AM](https://user-images.githubusercontent.com/46171897/99246472-586c3000-27d3-11eb-89a1-439717649849.png)
