### ISSUE TITLE
Make CDC Core services available in public API

### ISSUE THREAD

**Issue by claudio147** [SAP/spartacus#16875]
Would be great if the CDC Core services can get exported to public api. Currently it's not possible to extend services and facades in `cdc/core/auth`

Basic need behind that is to remove the session expired message or at least adjust the message type to a WARNING instead of ERROR.

![image](https://user-images.githubusercontent.com/12095490/217528512-1ef8ea13-681a-4cc5-b707-3fdd3114ff2d.png)

**Comment by SherwinVarghese** [comment]
Hi @claudio147,


Is this the only reason for exposing the service?

I believe issue [16877](https://github.com/SAP/spartacus/issues/16877) points to the same problem.
Fixing this issue would suffice?

Please provide additional reason for exposing the CDC core service layer.

**Comment by claudio147** [comment]
@SherwinVarghese Yes you're right it's the only reason and it points to the same problem. See also the comment here https://github.com/SAP/spartacus/issues/16877#issuecomment-1479649967
