### ISSUE TITLE
Spike lazy loading 

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#17]
For runtime performance reasons we need to move into an architecture where different parts of the application are lazy loaded. Angular provides lazy loading out of the box, however the lazy loaded elements are driven by the router. The router is typically related to "pages". This works well in case the page content is determined during design time, so that the code can be split up at build time. But with CMS driven pages, where the page content is composed at runtime, this technique doesn't fly. A smarter approach is required to allow for a good mix of CMS driven pages and lazy-loaded techniques.
We basically need to lazy load components. The granularity can be decided, but CMS components should be lazy loaded (although a few of them could be bundled together) as they can be added to any CMS page at any time.

Some things to keep in mind:
- lazy loading and SSR might conflict as the initial served page already has some components. These components shouldn't be reloaded
- Angular elements could be leveraged, but the current footprint for bootstrapping is probably to big (until we get ngivy)
- web components could be the answer, but we must carefully evaluate browser support and the size of polyfills to enable it

**Comment by Xymmer** [comment]
closing as we spiked and introduced lazy loading in 2.0
