### ISSUE TITLE
Investigate CMS components still not in spartacus

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#1722]
as discussed and described in https://wiki.hybris.com/display/spar/CMS+Components+Last+Mile

**Comment by aelharrak** [comment]
Hello @Xymmer,
Any news about CMS components !
i cant display my new componenet  :

------------------ copyright.component.ts ---------------------
import { Component, ChangeDetectionStrategy, ɵtemplate } from '@angular/core';
import { CmsComponentData } from '@spartacus/storefront';
import { CmsParagraphComponent } from '@spartacus/core';
@Component({
  selector: 'app-copyright',
  templateUrl: './copyright.component.html',
  styleUrls: ['./copyright.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})

export class CopyrightComponent extends CmsComponentData<CmsParagraphComponent>{
  public getText(): string {  
  return this.contextParameters().getComponentState().getText().template.replace('${currentYear}', (new Date()).getFullYear().toString());
  }
}
---------------copyright.component.html -----------------------
<p [innerHtml]="getText()"></p>
--------------------------------------

<contentSlot><components><component><uid>CopyrightComponent</uid><typeCode>CopyrightComponent</typeCode><modifiedTime>2019-06-03T16:52:00.098+02:00</modifiedTime><name>CopyrightComponent</name><template>Copyright © 2020-${currentYear} by Sapours, Inc., or related companies. All rights reserved.</template><container>false</container></component></components><name>Footer</name><position>Footer</position><slotId>FooterSlot</slotId><slotShared>true</slotShared></contentSlot>


Thank u :)
