### ISSUE TITLE
Reset the shipping cost when the shipping address changes.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#1743]
At the moment of writing this ticket:

- It seems that the backend can can adjust the shipping price when the shipping address changes.
We were able to assess this by using addresses in Vietnam and Belgium.

- It also seems that changing items in the cart has no influence on shipping costs.
----

In Spartacus, we would like the shipping method to clear from the cart when we apply changes to the cart like changing the shipping address or updating items in the cart.

This behaviour/rules may be configurable in the backend.  The goal of this spike is to determine if it is possible for the backend to reset the shipping cost/method when we change the shipping address or the items in the cart.

**Comment by Xymmer** [comment]
looks like the cart is recalculated in all cases when cart changes, before submitting
can we do something to signal to the user that something changed?
