### ISSUE TITLE
Fix for 'this' is undefined in ProductEffects.productLoadEffect

### ISSUE THREAD

**Issue by querplex-gw** [SAP/spartacus#17852]
'this' is undefined in ProductEffects.productLoadEffect

There was a fix done in 6.2.x
https://github.com/SAP/spartacus/pull/17594

But this fix is missing in 6.3.x / 6.4.x and 6.5.x
see also https://github.com/SAP/spartacus/pull/17595

**Comment by kpawelczak** [comment]
Hello @querplex-gw 
Thank you for bringing this to our attention. The 'this' undefined issue has been resolved in 6.5. We will fix it in 6.3 and 6.4 in an upcoming patch release, but we can't provide a fixed date for it yet.

**Comment by kpawelczak** [comment]
@querplex-gw we have released patch versions 6.3.1 and 6.4.1, which include the fix to "this" is undefined for ProductEffects.

**Comment by querplex-gw** [comment]
thanks ...
