### ISSUE TITLE
❗[Urgent] SSR - Custom providers are getting overwritten

### ISSUE THREAD

**Issue by CarlLavoieNcr** [SAP/spartacus#18336]
**Describe the bug**
We are no longer able to pass custom providers using Spartacus `OptimizedSsrEngine`.
This is caused by https://github.com/SAP/spartacus/pull/17512/files.

more specifically these lines 
![image](https://github.com/SAP/spartacus/assets/116568114/a3b0d54a-cbc4-4d94-b2ed-9889e901d5bc)

The providers are overwritten by the new code.

**Tell us the version of Spartacus**
- Library version: 6.2.x

**To Reproduce**
1. Setup spartacus
2. Pass a new provider in the server.ts as explained in the documentation https://sap.github.io/spartacus-docs/server-side-rendering-in-spartacus/ 
3. Try to access the injection token's value
4. returns `null`

**Expected behavior**
The value should be returned as it's being passed to the provider in the server.ts file.

**Desktop (please complete the following information):**
 - Device agnostic

**Smartphone (please complete the following information):**
 - Device agnostic

**Additional context**
There is no easy work around given all of the functions are private and therefore can't be overwritten. The only possible workarounds would be to copy paste spartacus' code to make the changes or do bypass the SSR Optimizations altogether.

**Comment by CarlLavoieNcr** [comment]
Solution

```
Subject: [PATCH] Github#18336 - fix the SSR optomized Engine providers to allow custom values to be passed
---
Index: core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts b/core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts
--- a/core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts	(revision 40515ffa468e6f3df23853a2c08acbf1106efd15)
+++ b/core-libs/setup/ssr/optimized-engine/optimized-ssr-engine.ts	(revision 9edfaa9bd2f8ff5bf529678120bdf059467b7c15)
@@ -453,11 +453,12 @@
     options = {
       ...options,
       providers: [
+        ...options?.providers,
         {
           provide: EXPRESS_SERVER_LOGGER,
           useValue: this.logger,
         },
-      ],
+      ]
     };
 
     this.expressEngine(filePath, options, (err, html) => {

```

**Comment by wangzixi-diablo** [comment]
JIRA ticket CXSPA-5726 is created for it.

**Comment by wangzixi-diablo** [comment]
fixed by https://github.com/SAP/spartacus/pull/18344
