### ISSUE TITLE
Cannot Disable SSR TransferState for Product

### ISSUE THREAD

**Issue by umpc** [SAP/spartacus#18358]
**Describe the bug**
It appears to be impossible to disable transfer state for 'product'. The transfered state data is always used instead of making new requests in the browser.

**Tell us the version of Spartacus**
- Library version: 5.0

**To Reproduce**
1. In SpartacusConfigurationModule, add this under provider:

`provideConfig({
      state: {
        ssrTransfer: {
          keys: {
            cms: StateTransferType.TRANSFER_STATE,
            siteContext: StateTransferType.TRANSFER_STATE,
          },
        },
      },
    } as StateConfig),`
    
 I've also tried this version that matches the format in the 3 year old docs page but returns a compiler error:

`provideConfig({
      state: {
        ssrTransfer: {
          keys: {
            product: false,
          },
        },
      },
    } as StateConfig),`

2. Open Dev Tools, Network tab
3. Browse to a product page
4. Observe that no requests are made for product data

**Expected behavior**
Requests would be made on the client side to get product data

**Desktop (please complete the following information):**
 - OS: macOS 11.7.6
 - Browser Chrome
 - Version 120

**Additional context**
We're having issues getting SSR page rendering to be performant at scale. So we need to cache product pages, but we can't cache product pages with inaccurate price info, so we need to get the latest info from the backend but this does not happen because we cannot reconfigure the storefront to make the calls again.

**Comment by wangzixi-diablo** [comment]
the approach mentioned here seems obsolete: https://github.com/SAP/spartacus/issues/806
