### ISSUE TITLE
Migration failed error during 2211.19 update

### ISSUE THREAD

**Issue by MehmetSert** [SAP/spartacus#18665]
**Describe the bug**
While updating my project from 6.8 to 2219.19, I get an error saying `Migration failed: Unexpected token / in JSON at position 1116` in the `Updates the SSR setup` step.

**Tell us the version of Spartacus**
- 6.8

**To Reproduce**
1. Delete package-lock.json file
2. Run the following command in the project directory;
`ng update @spartacus/schematics@2211.19 --force`
or
`ng update @spartacus/schematics@2211.19.0 --force`

**Expected behavior**
Successful completion of steps

**Screenshots**
![Screenshot at Mar 23 17-40-21](https://github.com/SAP/spartacus/assets/16652871/56006533-bbc9-4976-bc27-92bfecd567d7)

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1

**Additional context**
The error details occurring in `angular-errors.log` are as follows:
````
[error] SyntaxError: Unexpected token / in JSON at position 1116
    at JSON.parse (<anonymous>)
    at checkIfSSRIsUsed (/speedybunny/js-storefront/speedybunny/node_modules/@spartacus/schematics/src/shared/utils/package-utils.js:114:30)
    at /speedybunny/js-storefront/speedybunny/node_modules/@spartacus/schematics/src/migrations/2211_0/ssr/ssr.js:14:53
    at callRuleAsync (/speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/src/rules/call.js:77:24)
    at /speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/src/rules/call.js:72:40
    at Observable._subscribe (/speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
    at Observable._trySubscribe (/speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
    at /speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
    at Object.errorContext (/speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
    at Observable.subscribe (/speedybunny/js-storefront/speedybunny/node_modules/@angular-devkit/schematics/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)


````

After the error, the content of `node_modules/@spartacus/schematics/src/migrations` looks like this;
![Screenshot at Mar 23 17-45-33](https://github.com/SAP/spartacus/assets/16652871/4face686-5f5e-4598-a6bf-7e9f64582340)

My `package.json` content looks like this;
![Screenshot at Mar 23 17-47-48](https://github.com/SAP/spartacus/assets/16652871/3b26b673-94d5-4c17-a58c-2a379bbe6467)

**Comment by felix-ka** [comment]
Hi @MehmetSert,

I faced a similar issue during the migration. As you can see in the error log the migration is trying to parse a JSON file. If you look into the respective code you'll notice that the migration is trying to parse the angular.json file. If this file is not formatted correctly then the JSON parse aborts. Once I opened the file Intelij showed me that there was a comma after the last entry of a collection/array. 

Hope that solves the problem.

Cheers

**Comment by MehmetSert** [comment]
> Hi @MehmetSert,
> 
> I faced a similar issue during the migration. As you can see in the error log the migration is trying to parse a JSON file. If you look into the respective code you'll notice that the migration is trying to parse the angular.json file. If this file is not formatted correctly then the JSON parse aborts. Once I opened the file Intelij showed me that there was a comma after the last entry of a collection/array.
> 
> Hope that solves the problem.
> 
> Cheers

Thank you @felixkam93 your comment gave me an idea and there were some lines in the comment line in the angular.json file, I deleted them and tried again and it finished successfully.
