### ISSUE TITLE
Validate occ prefix config

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#1910]
Currently, when the configured occ prefix doesn't have the leading slash, the application breaks with a nothing-saying warning in the console:
```
TypeError: You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, Array, or Iterable.
```

We need to use the existing config validator and check if the configured occ prefix has the leading slash. If no, return warning message.

**Comment by giancorderoortiz** [comment]
Please fix.  Causes delays in development. OCC prefix config is critical.

**Comment by Platonn** [comment]
@giancorderoortiz you assigned yourself. Are you going to implement the validator?

**Comment by giancorderoortiz** [comment]
No. Just wanted to double check if it's still an issue.

**Comment by giancorderoortiz** [comment]
I don't see this issue happening with develop branch (June 9). Yarn deployment

**Comment by psmul** [comment]
Couldn't reproduce this issue in any scenario. Closing
