### ISSUE TITLE
Add logger service

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#2196]
We have a lot of places in code with console warnings.
It always need inject serverConfig for verify production flag like:

```ts
constructor(
    // ...
    private serverConfig: ServerConfig // or other config
  ) {}

// ...
if (!this.serverConfig.production) {
      console.warn(`content`);
    }
// ...
```
let's clean code little bit to get:
```ts
constructor(
    // ...
    private logger: Logger
  ) {}

// ...
this.logger.warn(`content`)
// ...
```

Please consider & discuss with @tobi-or-not-tobi possibility to use importable or even global service

**Comment by Pucek9** [comment]
After release 1.0 we avoid changes angular dependencies in our constructors.
Let's create it as util (not angular dependency), it allows for easier update occurrences

**Comment by Pucek9** [comment]
there is discussion about
- have that logger public - for us it's great because we have to use it not only in core, but it's not useful/safe for customers
- revert wrapping logs which were not checked by if(isDevMode) like that - or maybe have some log levels?
- potential problem with ssr (verify that window is definied is obvious, but not sure that its safe solution)

**Comment by dunqan** [comment]
We discussed it in the broader group and decided to postpone it for now, at least until Tobias is back, as we consider: making a full-blown solution (could be a part of error handling in general).
We can also decide on settling for something temporary, but still, it requires some agreements on implementation details
