### ISSUE TITLE
The sale section has no empty content page

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#2236]
## Environment Details

Description:  When the user visits the sale page and nothing is currently on Sale, there is no blank content page to advise the user that it is not an error, but merely a lack of relevant content.

## Steps to Reproduce
Turn off all Sale items in the storefront (probably current situation anyway) and visit the Sale page accessible from the upper header dropdown of the same name.

**Comment by vekterdude** [comment]
Wireframe and Visual assets on the way for this problem from Anthony R. And Manu R.

**Comment by tobi-or-not-tobi** [comment]
This page is actually an ordinary content page, with static content so far. I'd suggest to add a more informative message about this. It's not a bug, but looks bad indeed. 

@Xymmer can we add some content here?
