### ISSUE TITLE
Align horizontal rules (lines) in list view and grid view 

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#2245]
Description:  horizontal rules (lines) in list view and grid view catalog at the top of any catalog  page are not aligned 
How to duplicate: Visit any catalog page – list view or grid view

![SNAG-0010](https://user-images.githubusercontent.com/44620139/56984218-82a7bf80-6b53-11e9-9a4d-789893acb404.png)

**Comment by Xymmer** [comment]
Bill has asked for clarification on what the outcome should be

**Comment by vekterdude** [comment]
<img width="424" alt="Screen Shot 2019-05-29 at 11 15 17 AM" src="https://user-images.githubusercontent.com/44620139/58569395-095bc500-8204-11e9-8bd6-cd7bec4f2027.png">

**Comment by Xymmer** [comment]
setting to future as i don't see us being able to line up those lines.
would need another proposal, for example the pagination bar goes all left or something, or the addition of a filter title (filter by isn't there anymore)

**Comment by tobi-or-not-tobi** [comment]
@Xymmer I'm in favour of closing this ticket, as there's not reasonable approach to align the lines, it would require an alternative UI; The line below the facet heading will move up and down, based on the existence of the selected facet values. The line of the sorting/pagination is however static and will not change. 

Please note that we already dropped the "Filter by" heading a while back in case there is no facet selection.
