### ISSUE TITLE
Spike (doable?): Store hours display improvements e.g. "closes 9pm"

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#2254]
Description:  We need a discussion with developers and architects about how to display the store opening status in a single line. We (UX) would like:

Daily cycle:  If Closed: “Opens <9am>” (Red)
If Open: “Open until <9pm>” (Green)

If the opening or closing hours spans more than 24 hours:  If Closed: “Opens <Monday> <9am>” (Red)
If Open: “Open until <Saturday> <9pm>” (Green)

If open for more than the next week:
“Open 24 hours”

If major holiday is approaching in less than one week, but otherwise 24 hours:
Open until <Wednesday> <1pm>

**Comment by Matejk00** [comment]
We should have #4166 done before.
