### ISSUE TITLE
Support hreflang attribute

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#2373]
For SEO we like to support the `hreflang` link attribute, so that alternative pages in different markets and languages can be exposed to crawlers. This is useful for crawlers so that they can offer the right page to the end user. 

There are various issues with creating different links to the same content in other sites/languages. 

- Markets and languages are mixed and used in various ways to build URL. Some customers use different domains to differentiate markets, where others use a single domain and use market and language route parameters. Spartacus is likely not aware of the different domains per market as the `/basesites` API does not expose this.
- Not all pages exists in all languages. The product assortment might vary, the navigation might differ or some (content) pages might not be available from market to market. This is often different in a single site that has a language selector. 
- The actual links might be localized. I.e. product pages often have the (localized) product name in the title. 
- Unstructured (cms) content cannot be connected by page labels. Often the page labels are localized, so that the linking cannot be automated. A CMS link would be required from page to page, which is not available in the CMS. 

In order to build links to alternative lang/market variants, additional structure must be provided from the backend. As long as this structure is not in place, Spartacus can allow to introduce to resolve alternate pages, but cannot provide a default implementation in most cases.

**Comment by tobi-or-not-tobi** [comment]
This could be done as part of #1661

**Comment by danielbickel** [comment]
Besides the mentioned hreflang tag which should be made possible, there are also more SEO functionalities Spartacus should respect:

•	Sitemap.xml
•	Schema.org
•	Canonicals (where hreflang comes into play but not only hreflang)

... and of course for every site, as multi-domain/country is a regular use-case for such commerce systems.

As storefront is not aware of the different (related) sites, this has to be done before I think.

**Comment by tobi-or-not-tobi** [comment]
@danielbickel we've added support for schema.org (json-ld) in #4748, will be added in next release, somewhere this week. I'd be happy to take your feedback on board.

**Comment by tobi-or-not-tobi** [comment]
Complication for the creation of `hreflang` alternatives:
The PDP and PLP routes are configurable with product related data. This requires a potential additional call per page in order to fetch the localised data for the given content. 

Examples:
- use the localised (pretty) product name as it's part of the route
- use the localised (pretty) category name as it's part of the route

**Comment by andreas-becker** [comment]
Hey @tobi-or-not-tobi or @Xymmer any improvements on this?
