### ISSUE TITLE
Add CmsPageGuard to Logout route

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#2507]
The Logout route with `LogoutGuard` was meant to support 2 cases:
1. when `/logout` page label is defined in the backend - then present the CMS page of 404
2. otherwise - redirect to a login (or home) page

But since the logout route doesn't have `CmsPageGuard` - it doesn't support the first case.

For testing we should set up a `/logout` cms page in the backend and see if it's presented when we visit i.e. url `localhost:4200/blah/blah`

**Comment by qjimmy** [comment]
PR #8371
