### ISSUE TITLE
Can we define dependencies in spartacus libs?

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#2542]
Question that came from our slack channel: Is there a reason why you don't manage the dependent packages and versions just as regular dependencies? Instead of just including the spartacus libraries everyone now has to manage around 20 dependencies to resolve everything and fix vulnerabilities from npm audit. It would be quite handy to only include storefront and everything else just works.

**Comment by tobi-or-not-tobi** [comment]
We're using peer dependencies since we'er building libraries. Customer might want to use the same libraries, peer dependencies are recommended so that the same lib code will not be bundled twice.

**Comment by marlass** [comment]
The peerDependencies works great for us and we are creating automation around the updates and automatic installation. No point of changing that.
