### ISSUE TITLE
boolean attributes in CMS (component) are given as string values

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#2687]
In #2659 we experienced unexpected behaviour with the backend response. Apparently, the SearchBox component configuration properties, such as displayProducts, displaySuggestions and displayProductImages are given as string values, while these are of type boolean. We've worked around for this in the searchbox component, but should come up with a generic solution when the component data is parsed and provided to CMS components. Component developers should not be bothered with this.

At the same time, we'd expect the backend to expose boolean values, we've created https://jira.hybris.com/browse/CMSX-8937.

**Comment by artem-zur** [comment]
@tobi-or-not-tobi, thank you for this issue! We have the same situation, especially with custom components :(

**Comment by janwidmer** [comment]
Hey @tobi-or-not-tobi,

Any updates on this bug? It would really be nice, If I don't have to make manual string to boolean conversions as done here:  https://github.com/SAP/spartacus/blob/ee007f7e56d5c899e85392fc4fa7bc51cd7016c1/projects/storefrontlib/src/cms-components/navigation/search-box/search-box.component.ts

I cannot access the above SAP Backend ticket about it..we just built a custom component and have exactly that issue..

BR jan

**Comment by tobi-or-not-tobi** [comment]
@janwidmer this is low prio at the moment.
