### ISSUE TITLE
A back button on Order Details Page

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#2740]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Have at least 1 order in Order History.
Go to MyAccount -> Order History
Select one order

**Actual Result**
Would be nice to have a "Back" button on the page to go back to the Order History Listing Page.

**Comment by qjimmy** [comment]
Tried to reproduce, a back button is now available. Closing this. 
<img width="689" alt="Screen Shot 2020-04-20 at 4 29 19 PM" src="https://user-images.githubusercontent.com/30666844/79796797-26214f80-8324-11ea-8e18-620297869e05.png">
