### ISSUE TITLE
Add e2e for testing in SSR mode

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#2745]
Run e2e tests with Spartacus in SSR mode

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/cloud-commerce-spartacus-storefront/tree/develop/docs/current_drafts/ssr.md

**Comment by bgambocjaviniar** [comment]
PR: GH-2815

**Comment by Platonn** [comment]
Please note that in SSR not all functionalities are available due to lack of the JS, so you probably can't go through whole happy path of checkout (I'm pretty sure you cannot open added-to-cart dialog without JS).

**Comment by hackergil** [comment]
@Platonn Understood. But in this case, we are running the smoke tests with spa running on a node server with javascript enabled. All of them must pass.

**Comment by hackergil** [comment]
Closing in favor of #12596
