### ISSUE TITLE
Mobile/Tablet View: Messages hiding MyAccount menu

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#2869]
**Environment Details**
Spartacus: latest develop
Browser: Chrome 73.0.3683.86
OS: Mac Os

**Steps to Reproduce**
_Mobile View_
Login
Update Personal Details (My Account)
Don't close the successful message
Click on hamburger menu

**Actual Result**
The successful message is hiding the "My Account" section
![myAccountMobileHidden](https://user-images.githubusercontent.com/45409515/58898456-a1582380-86c8-11e9-95e1-458d75d80fd9.png)

![myAccountMobile](https://user-images.githubusercontent.com/45409515/58898464-a4531400-86c8-11e9-8af6-215fc4a8b321.png)

**Expected Result**
Should probably have a section just for the messages?

**Comment by mikelMHybris** [comment]
@KateChuen it looks like someone fixed this. Could you check it again?

**Comment by KateChuen** [comment]
On desktop view, the issue is fixed.

On mobile/tablet view, the message still hides "My Account". But the message disappears after a while, so it's not a big deal. But do we still want to fix it? @Xymmer

**Comment by Xymmer** [comment]
yes but low prio
maybe create a new ticket and i'll prioritize just that fix, we can pass this one

**Comment by Xymmer** [comment]
closing for now
