### ISSUE TITLE
[CMSX-8953 done in 2005] make component property "modifiedTime" consistent with the component data in backend

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#2876]
check this for details: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2521

**Comment by Xymmer** [comment]
CMSX is https://cxjira.sap.com/browse/CMSX-8953 - was fixed in 2005
When fixing this ticket, talk to Wei and maybe Tobias.
How do we differentiate if the customer is using 1905 or 2005? Does it matter in this case? Or we do a call and if we get an error, we try the old way?

**Comment by tobi-or-not-tobi** [comment]
Unfortunately the CMS changes have not resulted in the modifiedtime attribute, but somehow have reverted this change. I might misunderstood, or there was some confusion, either way we're converting now in Spartacus converters as we have code (tests mainly) that depends on this. We've also taken the opportunity to improve the code (extensible, readability and decreased objects).
