### ISSUE TITLE
[recheck] Improvements to fix for navigations

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#2909]
After removing ng-bootstrap for the navigations, there are some discrepancies between what the UX screenshots proposes, and what we have:

https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5a836fee948d985d0c1ff69e
The menu under "Digital Cameras" is in bold in the ux screenshot. But what we have is not bold. 
<img width="1031" alt="navLinksDigitalCam" src="https://user-images.githubusercontent.com/45409515/58960869-06b61e00-8776-11e9-9a65-626d78c1be9c.png">

https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5a836feb94d981543837411e
The arrows in the menu are not like on the ux screenshot. They are all pointing down instead of pointing to the right for the headerNavs. 
<img width="446" alt="mobileMenu" src="https://user-images.githubusercontent.com/45409515/58965164-1fc2cd00-877e-11e9-8fb8-3cf35d5c0be8.png">

https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5af4accbc44b2e6a43b1ea6d
The arrow for MyAccount keeps pointing down even when expanded. On the ux screenshot, it shows pointing up?
<img width="506" alt="mobileMyAccount" src="https://user-images.githubusercontent.com/45409515/58965286-58fb3d00-877e-11e9-8d45-8237137c7c7a.png">

https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5cd453312e4f02039b83e2fc
MyAccount is all in caps.
<img width="506" alt="mobileMyAccount" src="https://user-images.githubusercontent.com/45409515/58966836-01aa9c00-8781-11e9-931c-70ca15ec011f.png">

https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5af4acca3959627923079801
Directions of the arrows again
<img width="461" alt="mobileArrows" src="https://user-images.githubusercontent.com/45409515/58966752-dde75600-8780-11e9-8e33-b6e088f17904.png">

**Comment by kacperknapik** [comment]
Can be fixed in #7206

**Comment by kacperknapik** [comment]
This is NOT fixed in #7206
