### ISSUE TITLE
Turn on es2015 in unit tests

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#2962]
When I tried to turn on `target: 'es2015'` in `tsconfig.spec.json` of `core` and `storefrontlib`, many unit tests failed with `Error: No test scheduler initialized`

We may try upgrading some jasmine dependencies (i.e. 'jasmine marbles'). If it doesn't help we may try i.e. this workaround: https://stackoverflow.com/questions/55222252/ngrx-effects-spec-throws-error-as-no-test-scheduler-initialized

**Comment by Xymmer** [comment]
Veal if still needed and update milestone, or close

**Comment by Platonn** [comment]
We really don't need to change target of unit tests from es5 to es2015. So I close this ticket.
