### ISSUE TITLE
Smoke e2e: verify SSR starts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#2979]
When someone add in the code the implicit global `document` or the metod `winRef.document.localStorege.getItem()` without awarness of SSR, the SSR may be broken.

Tslint rules can't cover all cases.

It would be good to automatically prevent adding such code. We should add one e2e test that verifies builds SSR and verifies that it launches properly.

As a follow up, we may consider a set of more specific e2e tests that run in SSR (i.e. checking SEO tags, robots, basic navigation by links without JS - to test page is availabe for crawlers).

**Comment by Platonn** [comment]
Config can by provided dynamically in cypress thanks to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4087. Currently it's passed via the window object in before page load. But for SSR we need to pass it to the server even when making the navigation request.
Possible mediums:
a) URL query param i.e. `/cart?cxTestConfig=<serializedConfig>`
b) cookie

**Comment by hackergil** [comment]
@Platonn SSR tests have been added since a while ago. Should we close this one or keep it?

**Comment by Platonn** [comment]
yes, let's close it! Many thanks for adding ssr e2e @hackergil !
