### ISSUE TITLE
address forms: show inactive province/state instead of hiding it

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#2983]
looks weird when it's blank, like something's missing (there is)
check all address forms:
- add/edit addresses for account
- checkout shipping address
- doesn't affect credit card address as currently it doesn't ask for state/province

![image](https://user-images.githubusercontent.com/4998145/59165694-b92b0f80-8aed-11e9-933c-65e290d072b6.png)

**Comment by mikelMHybris** [comment]
<img width="919" alt="Screen Shot 2019-06-11 at 1 30 58 PM" src="https://user-images.githubusercontent.com/30266610/59293423-2e612680-8c4d-11e9-9ce5-c965ed911432.png">
state goes next to zip code when you select a country with that format. Do you still want this to change?

**Comment by Xymmer** [comment]
sorry i mixed it up and then thought i updated the ticket
could we show 'state' and its menu, but inactive, until we choose a country that has provinces/states?
instead of hiding it.
@mikelMHybris

**Comment by developpeurweb** [comment]
This doesn't seem like a CSS issue, more like TS, the element gets removed from the DOM
