### ISSUE TITLE
Create an impex to use to PDP with 1811

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#3004]
In the spartacussampledaddon there are new slots and components that make the product details page more CMS driven. This breaks the pdp page compatibility with 1811.

This ticket is to provide an impex to run in 1811 for the pdp to work

**Comment by Xymmer** [comment]
trying it now

**Comment by tobi-or-not-tobi** [comment]
closing as this is no longer relevant, we won't expect customers on pre 1905 to work with Spartacus, and if they would they'd need to bring in the PDP setup themselves. 
@Xymmer correct me if I'm wrong.
