### ISSUE TITLE
Internal security code review

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#3031]
Perform an internal security audit before 1.0 release, including:
1) Review code for possible security threats (XSS / proper sanitization, not using JIT, 
2) Make sure any security sensitive code is justified and properly guarded
3) Check if Angular built-in XSSI/XSRF protection is not mitigated in any way
4) Review package dependencies for security risk

**Comment by marlass** [comment]
Quick check:
1. No usage of `bypassSecurity*` methods
   [innerHTML] used for HTML content, so it is sanitized
4. Did `yarn audit`. 3 warnings found (none of it is dangerous - vulnerabilities in our documentation tool and i18n linter)

Will look more into the code later.

**Comment by Xymmer** [comment]
would checkmarx and sonarqube cover these reviews?

**Comment by giancorderoortiz** [comment]
Threat modelling methodology applied extensively throughout key features of product. 
Closing ticket.
