### ISSUE TITLE
Sometimes, Breadcrumb not updated (safari) - for multi-d products

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#3042]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  
- Browser: 
- OS: 
- Device: 
**Mac/Safari** 
- Other environment details: 

## Steps to Reproduce
1. go to category page: "Compact Cameras". In breadcrumb, you will see "Home/Digital Compacts/47 results for Ditital Compacts"
2. Click product "DSC-H20, Green" or "DSC-H20 Blue" or "DSC-H20 Red" in the list to go to pdp, I see this:
![Screen Shot 2019-06-11 at 1 29 10 PM](https://user-images.githubusercontent.com/44440575/59293556-69fbf080-8c4d-11e9-89b2-c2e2f4b97a23.png)
The DSC-H20, Green or Blue or Red are variant products of DSC-H20.

**Comment by Xymmer** [comment]
These are multi-dimensional products, which we don't officially support. We'll fix in future

**Comment by giancorderoortiz** [comment]
Unable to reproduce with Spartacus 3.0. 
Multi-D products in Electronics not enabled. 

Reopen if necessary.

Similar issue not seen with apparel-uk
See https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/apparel-uk-spa/en/GBP/product/300617328/Bike%20Bones%20SS%20Youth%20passion%20L
