### ISSUE TITLE
Iphone8: Cannot collapse all of the tabs on PDP

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3053]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Go to a pdp of a product for eg: 1981415
Scroll down
Click on the - sign next to Product Details

**Actual Result**
Cannot collapse the tab. One tab has to always be open. 
It's a pain if you expand the specs tab by mistake, and you have to keep scrolling to go to the next tab, for eg, the Shipping tab.

**Comment by Xymmer** [comment]
setting to stretch, won't let it block the release
