### ISSUE TITLE
[RE-Test] Iphone8+: Spinner is not well positioned on the screen

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3056]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: Iphone8+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

**Steps to Reproduce**
Do an action that will show the spinner for eg: 
Add an item to cart or
Set an address or payment info as default or 
Delete an address or payment

**Actual Result**
The spinner is not centered. It's displayed anywhere on the screen.

![IMG_8294](https://user-images.githubusercontent.com/45409515/59300353-fb269380-8c5c-11e9-9c0f-8b4602265e52.PNG)
![IMG_8290](https://user-images.githubusercontent.com/45409515/59300354-fb269380-8c5c-11e9-9f16-3d052a9f53bd.PNG)

**Comment by znikola** [comment]
Can confirm this happens on Chrome on Galaxy S8 as well: 
![Screenshot_20190612-143902_Chrome](https://user-images.githubusercontent.com/11561723/59377401-29b97280-8d20-11e9-97c0-1f55263a4469.jpg)

**Comment by morganm58** [comment]
Looks like it's no longer an issue in emulator. The spinner never centers on the page. It centers in the container of the loading element.

**Comment by giancorderoortiz** [comment]
I no longer see this issue. 
Tested in Chrome, Safari, public instance as well as dev-com5. 
Spinner "appears" centered on the screen, but as @morganm58 says it centers inside the container of the loading element.
