### ISSUE TITLE
The country drop down is not searching/searchable

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#3062]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
1. Add items to the shopping cart
2. Go to checkout
3. Add your address to your account
4. The first drop down is Country. I am trying to select Canada, I am clicking on letter C on my keyboard and expecting to see the first country starting with C to comes up, but nothing happens

## Additional Information

![image](https://user-images.githubusercontent.com/6307948/59301806-7a699680-8c60-11e9-93fc-1f158737867f.png)

**Comment by Xymmer** [comment]
this is an improvement and won't block release, setting to stretch

**Comment by qjimmy** [comment]
Tried to reproduce, is now searchable. Closing this.
<img width="874" alt="Screen Shot 2020-04-20 at 4 27 27 PM" src="https://user-images.githubusercontent.com/30666844/79796605-d80c4c00-8323-11ea-86e6-140fda5dcc76.png">
