### ISSUE TITLE
Buttons spacing in Address Book and PDP Reviews

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#3067]
- On mobile view -> My account -> address book -> Delete -> need spacing between the 2 buttons?

<img width="500" alt="buttonsAddressBook" src="https://user-images.githubusercontent.com/45409515/58821261-ac488080-8602-11e9-8b78-bf1f7d688202.png">

- On mobile view -> pdp -> Reviews -> Write a review

<img width="500" alt="Screen Shot 2019-06-11 at 4 22 07 PM" src="https://user-images.githubusercontent.com/15113219/59303849-14cbd900-8c65-11e9-9a47-fadd6c438c1f.png">

Originally part of GH-2835
cc @KateChuen

**Comment by KateChuen** [comment]
Tested on dev10
✅chrome
✅safari
✅firefox

✅Address Book
<img width="422" alt="Screen Shot 2020-04-23 at 11 17 17 AM" src="https://user-images.githubusercontent.com/45409515/80116879-7aab1180-8554-11ea-885f-60efd9a719a4.png">

✅Review Form
<img width="366" alt="Screen Shot 2020-04-23 at 11 18 56 AM" src="https://user-images.githubusercontent.com/45409515/80116885-7d0d6b80-8554-11ea-8d1e-0a467cb10fac.png">
