### ISSUE TITLE
The search result does not match with the query

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#3070]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  Beta
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/
- Browser: 
- OS: 
- Device: 

## Steps to Reproduce
Search for 'water', and you will see unrelated results in the search result. We need to improve it.

**Comment by Xymmer** [comment]
search results controlled by the backend/sample data, customers would tailor this to their products.
But agreed, it would be nicer if we updated this.
putting to future
