### ISSUE TITLE
Roadmap Draft for Accessibility Implementation

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#3072]
Opening this ticket as per conversation with @Xymmer _"could you plan to develop a document that goes over what we plan to implement, for publication in spartacus github wiki, you’d have to write it in markdown"_

**Comment by giancorderoortiz** [comment]
Proposed functionality should follow a SDLC as specified here: https://wiki.wdf.sap.corp/wiki/display/PSSEC/Secure+Software+Development+Lifecycle+Overview

And must comply with security standards as detailed here:
https://wiki.wdf.sap.corp/wiki/display/PSSEC/SAP+Product+Standard+Security+-+Version+8.0

**Comment by kacperknapik** [comment]
@developpeurweb do we need that ticket still?

**Comment by developpeurweb** [comment]
@kacperknapik yes please, this is my compass reminding me that we still have guidelines to implement in future rounds, as well as the start date of the paper trail.
To be kept at the bottom of the Backlog and `FUTURE` milestone until ALL guidelines have been implemented.

**Comment by developpeurweb** [comment]
### 2.0

- **Keyboard Navigation** and related features were successfully achieved in 2.0
https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Feature%3A+Accessibility

### NEXT

- **Screen Readers** support Desktop and Mobile will be the next milestone (story needs spiking) https://cxwiki.sap.com/display/spar/Screen+Readers
- **Form Validation** improvement is related to Screen Readers. https://cxwiki.sap.com/display/spar/Form+Validation+Accessibility+Patterns
- **Avoid Regressions** for features related to Keyboard Navigation such as _Tab/Reading Order_ and _Consistent Navigation_.

**Comment by developpeurweb** [comment]
Closing this ticket and replacing it with https://github.com/SAP/spartacus/issues/8857 for the NEXT Accessibility round regarding Screen Readers.
