### ISSUE TITLE
Wrong number of items for PLP grid

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#3075]
Grid has 3 items per row so if there are 10 items per page the last row contains just one item. It might be interpreted by user as the last page of results (which is not the case as we are on the first page).

![image](https://user-images.githubusercontent.com/788092/59305403-7e1a0f00-8c9a-11e9-8e08-eb716bb03f4e.png)

**Comment by Xymmer** [comment]
the grid *always* has 3 columns? if so then let's make it 12, but what happens at different viewports?

**Comment by giancorderoortiz** [comment]
Please fix conflicts in pr(if any), and approve/reject.
Would like to test this fix soon.

**Comment by giancorderoortiz** [comment]
Issue still present in Spartacus 3.0 demo server. 
https://spartacus-demo.eastus.cloudapp.azure.com/apparel-uk-spa/en/GBP/search?q=men:relevance:gender:MALE&currentPage=1
