### ISSUE TITLE
Multi-site improvements

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#3085]
- extendible site context (allow for custom site contexts)
- multi-site landing page
- multi-site context selector
- language / currency browser detection

With 1905 we have a new backend API that we could leverage to load the different sites. 

Other ideas:
- add a site-group in the backend
- ensure that the `legacy` config is more specific, i.e. `legacy: '1811'`
- limit multi-site for different backend versions

**Comment by alanktwong** [comment]
@tobi-or-not-tobi and @Xymmer we're using Spartacus for a client that will be aggressively multi-site. Some sites will have be multi-lingual. Spartacus itself should have a site selector. So all the features you mention in your 1st comment are useful for us.

Is there any rough guess (to a month) for when release 1.1 will go out?
