### ISSUE TITLE
Simplify dependencies

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#3099]
We currently specify fine-grained version numbers to the package.json files and documentation, for example: 

`"@spartacus/core": "0.1.0-beta.0"`

This means that we need to update the dependencies and documentation with every release. npm has a mechanism to solve this, using tags. We already publish the latest tag on npm, so we could change the dependencies to:

`"@spartacus/core": "@latest"`.

**Comment by hackergil** [comment]
This has been done a while back already.
