### ISSUE TITLE
Samsung Tab (Chrome): Fix long loading times

### ISSUE THREAD

**Issue by RadhepS** [SAP/spartacus#3121]
## Environment Details

- Spartacus:  Beta
- Browser: Chrome
- OS: Android Version 5.0.2 
- Device: Samsung Tab

## Steps to Reproduce
Refresh the application page

## Observed Results
Takes roughly 10-15 seconds to see results after refreshing the page.
It is way too long and will hinder customer experience significantly.

Also noticed the same issue when using my Moto Z Play (Android Version 8.0.0).
The load time on my phone is slightly better but it still takes 8-10 seconds to load the page.

**Comment by Xymmer** [comment]
doesn't block release but let's see if something can be done, setting to stretch

**Comment by giancorderoortiz** [comment]
Still an issue?

**Comment by giancorderoortiz** [comment]
Issue no longer present. 
Tested Spartacus 3.0 demo server in Samsung Tablet.
