### ISSUE TITLE
If you reduce quantity in add to cart modal, page scrolls weird (iPad Air Safari horizontal)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3126]
Seen in iPad Air Safari horizontal

**Comment by giancorderoortiz** [comment]
Still an issue?

**Comment by giancorderoortiz** [comment]
Retest done with Spartacus 3.4 in CCV2. 
Ipad Pro. 
Unable to reproduce. 
Scroll up/down in PDP works fine after/during changing qty in Add-To-Cart modal.
