### ISSUE TITLE
Login page:  'Don’t have an account' link should be closer to Register

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3130]
right now:
![image](https://user-images.githubusercontent.com/4998145/59936020-09bf3880-941d-11e9-8a16-46a42751e5a3.png)

would like to see "Don't have an account?" or "I don't have an account"
![image](https://user-images.githubusercontent.com/4998145/59936118-3bd09a80-941d-11e9-879e-670ec01e5780.png)

**Comment by developpeurweb** [comment]
Fixed as per screenshot below

![Screen Shot 2020-04-14 at 1 39 30 PM](https://user-images.githubusercontent.com/15113219/79256785-988ebd00-7e56-11ea-92bb-d6d50918fa61.png)

**Comment by developpeurweb** [comment]
btw PR #7256 is the one that needs to be reviewed.

**Comment by bgambocjaviniar** [comment]
works as intended, and in all media queries sizes

- one thing to note, the question mark added to the text is a good touch :)
