### ISSUE TITLE
Checkout tabs could use improvement when they fall to 2 lines (iPad Air Safari horizontal)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3132]
iPad Air safari

**Comment by Xymmer** [comment]
![IMG_0024](https://user-images.githubusercontent.com/4998145/59394363-5fc11b80-8d4d-11e9-9cd9-ada7a6adf2b5.PNG)

**Comment by developpeurweb** [comment]
I cannot reproduce this bug as I don't have a real iPad Air to test with. However by emulating in MacBook and Safari to the narrowest screen size before the media query changes: it seems there is no longer an issue.

![Screen Shot 2020-04-13 at 5 15 10 PM](https://user-images.githubusercontent.com/15113219/79162258-f665cb00-7daa-11ea-99f4-fdd16165e966.png)

**Comment by developpeurweb** [comment]
@Xymmer has an iPad, he volunteered to test this issue.

**Comment by giancorderoortiz** [comment]
Retest done on Ipad. Issue no longer seen. Alignment seems correct. 

![ipad1](https://user-images.githubusercontent.com/46171897/82893763-873dd380-9f1f-11ea-9c85-b30a23b01499.png)
![iPad2](https://user-images.githubusercontent.com/46171897/82893766-873dd380-9f1f-11ea-8c43-7ae43157f88a.png)

**Comment by giancorderoortiz** [comment]
Tested with public instance. d4
