### ISSUE TITLE
Price of shipping not displayed in checkout review

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3137]
Seen in iPad Air safari but applies to all devices/browsers

**Comment by Xymmer** [comment]
![IMG_0025](https://user-images.githubusercontent.com/4998145/59394422-a1ea5d00-8d4d-11e9-988d-6731238257da.PNG)

**Comment by hackergil** [comment]
Where exactly should the shipping price be displayed?

**Comment by Xymmer** [comment]
Somethign like this, if info is present:
![image](https://user-images.githubusercontent.com/4998145/87596304-de5d5a80-c6bd-11ea-8fa4-c38ffafa4b5e.png)

also, it should not say "estimated shipping" at right if they user has chosen his shipping by now.

**Comment by benmarcotte** [comment]
Seems to be working as intended.
![image](https://user-images.githubusercontent.com/55809994/87689126-d6e99000-c755-11ea-9203-687c7d396eec.png)
