### ISSUE TITLE
Unit Testing crashes on first run

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3184]
In my environment, I get the following error when running `ng test`:

![image](https://user-images.githubusercontent.com/11735817/59500020-e6ceda80-8e98-11e9-9366-cb4d37189047.png)

If I use `Ctrl + C` to close the program, chrome closes and reopens and the tests work.

I am not sure if this is something that occurs for myself or others as well.

Note: In the screenshot I have used `browsers=ChromeHeadless` but this issue recurs regardless of the flag.

**Comment by Platonn** [comment]
I don't see a need to run unit tests for the `storefrontapp` because we don't have any (as it's only shell app consuming libraries).

The error appears due to misconfiguration of angular.json. Low priority.
