### ISSUE TITLE
[retest] Firefox: red border on form's required input

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#3190]
## Steps to Reproduce
All devices on firefox
- create a shipping address through myaccount/address-book or through the checkout

## Observed Results
It is already showing red border when nothing is typed

<img width="1026" alt="Screen Shot 2019-06-14 at 8 27 58 AM" src="https://user-images.githubusercontent.com/29099466/59509190-5be0e680-8e7e-11e9-8c8e-53e3398faf5a.png">

## Expected Results
Should not show the red border until something is typed wrong

**Comment by developpeurweb** [comment]
This seems like a known issue with Firefox, more [insight here](https://stackoverflow.com/questions/5939341/firefox-4-is-there-a-way-to-remove-the-red-border-in-a-required-form-input).

**Comment by Xymmer** [comment]
it's been a while for this one, let's retest

**Comment by giancorderoortiz** [comment]
Issue no longer present in Spartacus 3.0 demo server. 
https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/my-account/address-book

![Screen Shot 2021-06-06 at 9 21 08 AM](https://user-images.githubusercontent.com/46171897/120925877-9dd94780-c6a8-11eb-9378-bfee83db5e20.png)
