### ISSUE TITLE
Need consistent "Default" wording for AddressBook and PaymentDetails

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3194]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: mac
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Have at least 1 address and 1 payment saved.

**Actual Result**
Go to Address Book and Payment Details page.
The wording for the "default" part should be consistent on both pages.

Address:
![Screen Shot 2019-06-14 at 10 48 04 AM](https://user-images.githubusercontent.com/45409515/59517763-4a093e80-8e92-11e9-9a00-d962e28d9c9f.png)

Payment:
![Screen Shot 2019-06-14 at 10 48 11 AM](https://user-images.githubusercontent.com/45409515/59517786-5097b600-8e92-11e9-814c-d35477018c9f.png)

**Comment by qjimmy** [comment]
Have Ben do this ticket when he is added to the SAP org. Ticket is very similar to my first ticket and good introduction to the project's basics
