### ISSUE TITLE
[early Nov] What to do about sonar scanning test code

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3198]
In #1005
Gill wrote:
For the console.log warnings, I've disabled the rule for typescript. Let me know if I should bring it back. For the password warnings, they are only on the test files (where it is ok to have passwords hardcoded). We can:

Disable the rule
Stop scanning the tests
Other option you can think of

Let's discuss what to do

**Comment by giancorderoortiz** [comment]
See https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AW2RCOHtEsf8yKnMaWlc&resolved=false&types=VULNERABILITY

Internal discussion about removing hard-coded passwords from test data in cypress.
