### ISSUE TITLE
[Mobile] Change input type in phone number input (address form)

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#3233]
At the moment the input type for the phone number input is `text`. This input should be `tel` for a better experience on mobile https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/tel. (As demonstrated by the screenshots)

Change the type for the phone number input from `text` to `tel`.

Input `text`:
![Screenshot_20190617-161139](https://user-images.githubusercontent.com/10605724/59633738-30c6f300-911b-11e9-8b49-a0917ef71220.png)

Input `tel`: 
![Screenshot_20190617-161043](https://user-images.githubusercontent.com/10605724/59633745-34f31080-911b-11e9-95e9-56e0627e12e8.png)

**Comment by giancorderoortiz** [comment]
What would be the expectation with iOS devices?

**Comment by Xymmer** [comment]
The effect is to have the keybpad appear when you click in the box.
Just tested on dev16, it's working
