### ISSUE TITLE
iphone8+: Shipping price is misaligned in checkout step

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3249]
**Environment Details**
Spartacus: beta release
Browser: Chrome
Device: mac
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/

**Steps to Reproduce**
Add an item to cart
Proceed to checkout

**Actual Result**
On the "Delivery Mode" checkout step, the price looks misaligned. Maybe it's not, but it looks off to me. I was expecting it to be aligned with the delivery mode name I guess...
![IMG_8434](https://user-images.githubusercontent.com/45409515/59700752-0bd98b00-91c2-11e9-806d-d53f93f5bbb3.PNG)

Address:

**Comment by giancorderoortiz** [comment]
Issue still seen in public instance.  
However it's seen as fixed in dev-server5/8
![Screen Shot 2020-05-26 at 5 50 06 AM](https://user-images.githubusercontent.com/46171897/82886648-d3374b00-9f14-11ea-9ac9-c4351c3f6d14.png)
