### ISSUE TITLE
Spike how to improve first load performance or document how it will be

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3298]
Our PWA score is looking good except for performance. Our first load will work very well when SSR is supported. We need to spike to come up with a list of improvements or document why it will be better. Ideally our model t server serves ssr but that's not available yet. Let's be transparent about explaining this as we know that our performance is good.
![image](https://user-images.githubusercontent.com/4998145/59853547-19684f80-933f-11e9-8b91-85cf92ef51fc.png)

**Comment by PiotrZ-Eclipse** [comment]
Is there any news on this one? We are adopting Spartacus now and the performance score of raw application in [lighthouse](https://chrome.google.com/webstore/detail/lighthouse/blipmdconlkpinefehnmjammfjpmpbjk) tool is 0. 
When we have implemented the SSR as described [here](https://sap.github.io/cloud-commerce-spartacus-storefront-docs/server-side-rendering-in-spartacus/) we ended up with performance score of 42 which is still quite low.
I know there are some improvements planned in 1.4 and 2.0 but will they affect first-time load?

**Comment by Xymmer** [comment]
Hey PiotrZ! I can confirm we're working on the improvements for 1.4 and 2.0 as you stated.
- ssr indeed does speed things up as you saw so that's good
- we're working on 2-3 cms-based loading improvements that should improve performance
- the release of 2.0 (using Angular 9/ivy) should speed things up as well, as well as lazy loading feature

how much that will impact lighthouse score, i can't say right now, but we are setting up a server to measure it ourselves
