### ISSUE TITLE
Shipping improvements: update totals when choosing shipping, change label when chosen

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#3351]
1. When displaying the cart or the shipping address, displaying "Estimated Shipping" is ok because the customer hasn't chosen yet. But after the customer has chosen shipping, the label should say "Shipping" not "Estimated Shipping".
2. On shipping method page, when the customer chooses a shipping method, update the page right away (the totals should reflect the cost, and the label should change now that the customer has specified something).

![image](https://user-images.githubusercontent.com/4998145/60037741-63736d00-9680-11e9-813c-f4746813fbe6.png)

**Comment by marlass** [comment]
Did it for 2.0.0 release, because it involves behavior changes which can be considered breaking. And @ravulapati-valtech provided PR.

**Comment by giancorderoortiz** [comment]
Test successful 

Standard Shipping
![Screen Shot 2020-06-14 at 1 28 19 PM](https://user-images.githubusercontent.com/46171897/84599946-b622d780-ae43-11ea-8c71-e47b26b96fbc.png)

Premium Shipping 
![Screen Shot 2020-06-14 at 1 29 02 PM](https://user-images.githubusercontent.com/46171897/84599947-b91dc800-ae43-11ea-9e57-f86571c1411d.png)

Order Review
![Screen Shot 2020-06-14 at 1 29 41 PM](https://user-images.githubusercontent.com/46171897/84599949-ba4ef500-ae43-11ea-93b8-9abff313e2f1.png)
