### ISSUE TITLE
[retest after translations] Lang DE: My Account: Spacing before SignOut link

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3417]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: https://dev-com-2.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
viewport 1100x710
Sign in
CHange language to DE
Hover on "My Account"

**Actual Result**
There's more spacing right above the Sign Out link.
<img width="372" alt="Screen Shot 2019-06-26 at 2 14 47 PM" src="https://user-images.githubusercontent.com/45409515/60204491-f0ebc400-981c-11e9-8cc2-b73d27af9ce2.png">

In ENGLISH, it looks good:
<img width="341" alt="Screen Shot 2019-06-26 at 2 14 30 PM" src="https://user-images.githubusercontent.com/45409515/60204498-f8ab6880-981c-11e9-8585-0395e8f31f2b.png">

**Comment by Xymmer** [comment]
it's because "Close Account" is not translated in CMS sample data.
Retest after we get translations.

**Comment by giancorderoortiz** [comment]
Issue no longer seen in Spartacus 3.0 demo server. 
https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/de/USD/

![Screen Shot 2021-06-06 at 9 28 32 AM](https://user-images.githubusercontent.com/46171897/120926135-a67e4d80-c6a9-11eb-8575-2c1e18c7e654.png)
