### ISSUE TITLE
[RE-TEST] iphone8+: Can't see the whole add to cart modal in landscape

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3458]
**Environment Details**
Spartacus: Release 1.0
Browser: Safari
Device: iphone8+
Happens on: https://dev-com-19.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Go to a PDP
Go to landscape view
CLick on "Add to cart"

**Actual Result**
The "Add to cart" modal is too big for the screen. So either I only see the bottom half of it and I can't close it.
If you go to landscape view AFTER clicking on AddToCart, then you only see the top half of the modal and you can't click on the buttons "go to cart" or "proceed to checkout" (even scrolling down)
![IMG_8649](https://user-images.githubusercontent.com/45409515/60354761-f2db9180-999a-11e9-9c5b-54c564d901ac.PNG)

**Comment by developpeurweb** [comment]
As per Slack conversation with @KateChuen this is no longer an issue, scrolling works fine for modals on a real iPhone7 device, tested on dev-3 on May 13, 2020.

**Comment by Xymmer** [comment]
retested on dev8, works
