### ISSUE TITLE
[retest] [firefox][mac] select in personal details looks strange

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#3468]
Only this select has this style.
![image](https://user-images.githubusercontent.com/8040837/60438019-f62b8300-9c0f-11e9-9933-bb65dd1febbc.png)
Additionaly only this select allows for correct selecting by keyboard letter #3469

**Comment by morganm58** [comment]
This is a typescript issue. If the select is changed to ng-select that should fix it.
