### ISSUE TITLE
[Xiaomi/Chrome/Firefox] - Too many product reviews on click "more" button

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3479]
When clicking "More" whilst viewing product reviews on the product page, I am given a seemingly endless list of reviews which I have to scroll for a long time to get through. We should limit how many reviews are loaded at one time and keep showing "more" to incrementally show more reviews.

**Comment by Xymmer** [comment]
need pagination or infinite scroll?

**Comment by Zeyber** [comment]
> need pagination or infinite scroll?

Pagination will allow users to navigate to older reviews without having to scroll for a long time. But I think that its more likely that the user is interested in more current reviews so in my opinion I think that click "More" show (5-10+ more) is a better option. 

Infinite scroll would mean that the user will have to endlessly scroll to the bottom of the reviews list before getting past the reviews to the rest of the content so it would defeat the purpose.
