### ISSUE TITLE
[Xiaomi/Chrome] - FAQ Page has poor text alignment

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3481]
Text aligned like this on Chrome but looks fine in firefox:

![image](https://user-images.githubusercontent.com/11735817/60444242-1a419100-9c1d-11e9-88e0-5281953eb391.png)

**Comment by KateChuen** [comment]
Tested on dev3, on chrome, firefox & safari.
The text is aligned now. ✅
<img width="383" alt="Screen Shot 2020-06-08 at 10 46 11 AM" src="https://user-images.githubusercontent.com/45409515/84046349-faac0000-a977-11ea-9d19-3c2ed3ca9b38.png">
