### ISSUE TITLE
Mobile - need mobile specific banners

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3485]
This does not look mobile friendly in my opinion as buttons are difficult to read and press:

![image](https://user-images.githubusercontent.com/11735817/60445249-20d10800-9c1f-11e9-8059-352aecdbec10.png)

**Comment by developpeurweb** [comment]
This is as per mockups as possible and has been like this for quite a while.
@Xymmer should we align with Manu on this topic?

**Comment by Xymmer** [comment]
good idea, let's ask if we can get mobile-specific images

**Comment by Manurod2018** [comment]
We have 4 different sizes for all main banners: Mobile, Tablet, Desktop and Widescreen.
See attached a few examples of banners for the mobile inflection point.

Not sure about the ones on the bottom, these are old. I didn't create them and I am not sure they have a responsive version for them so maybe we can just update them. Let me know if we need additional banners?
![Electronics_Accessories_EN_480W](https://user-images.githubusercontent.com/37299626/68772861-8b944600-05f8-11ea-904c-0fae88c8683f.png)
![Electronics_ChristmasRed_EN_480W](https://user-images.githubusercontent.com/37299626/68772863-8b944600-05f8-11ea-8d6e-a93a242fa305.png)
![Electronics_LoyalCustomers_EN_480W](https://user-images.githubusercontent.com/37299626/68772864-8b944600-05f8-11ea-8cb1-30b88f7f3a79.png)
