### ISSUE TITLE
samsung s10 firefox: Edit and Delete buttons not too responsive on Address Book Page

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3491]
**Environment Details**
Spartacus: Release 1.0
Browser: Firefox
Device: samsung s10+
Happens on: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/de/USD/

**Steps to Reproduce**
Go to MyAccount -> Address Book
CLick on the Edit and Delete buttons.

**Actual Result**
These 2 buttons are not too responsive. most of the times, clicking on them doesn't do anything.
But the "Add new address" button works well.

![977e9bd4-768f-4b08-9439-bac893b45480](https://user-images.githubusercontent.com/45409515/60473179-f2acf180-9c39-11e9-82c2-ad7247e703c5.JPG)

**Comment by psmul** [comment]
Tested on virtual Samsung s10 (Borwserstack) with Chrome and Firefox. Could not reproduce a problem, buttons seem to work as intended. 
@KateChuen only solution I can propose is to increase padding for those buttons, which might increase their clickable field.

**Comment by developpeurweb** [comment]
Before fixing this ticket, let's wait for this other issue GH-4330 to be solved.

**Comment by benmarcotte** [comment]
Tested it on my S10 with firefox, chrome and the slack browser, no issues on my end.

**Comment by Parthlakhani** [comment]
Tested on Samsung s10 firefox, could not reproduce the issue.

**Comment by Parthlakhani** [comment]
Closing the issue as it can not be reproduced.

**Comment by giancorderoortiz** [comment]
Tested on Samsung Tablet. 
Demo server. 3.0. 
No issues found. 
Unable to reproduce. 
Buttons respond to touch normally.
