### ISSUE TITLE
'Ship to this address' button visible even when address is selected

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#3505]
Chrome.
![obraz](https://user-images.githubusercontent.com/4001059/60503961-fe8fc680-9cc0-11e9-9166-88a668058277.png)

**Comment by developpeurweb** [comment]
As a user, I've always thought this is a bit confusing as well... what we currently have doesn't match mockups or wireframes. Currently the link **_"Ship to this address"_** just selects the card, but doesn't switch it as default as intended in the wires... for that, users will have to go to `My Account > Address Book` and click on **_"Set as default"_** (last screenshot) .
@Xymmer Perhaps a realignment with Manu and Anthony is needed here?

**Current view:**

![Screen Shot 2019-07-02 at 3 39 28 PM](https://user-images.githubusercontent.com/15113219/60541817-61448a80-9ce0-11e9-857f-a4eb21f9ae7b.png)

**Mockups:**

![Screen Shot 2019-07-02 at 3 04 05 PM](https://user-images.githubusercontent.com/15113219/60541838-6d304c80-9ce0-11e9-8dbf-b054715b78ac.png)

**Wires:**

![Screen Shot 2019-07-02 at 3 36 43 PM](https://user-images.githubusercontent.com/15113219/60541866-7faa8600-9ce0-11e9-9aec-4bdef0977b6b.png)

**My Account > Address Book**

![Screen Shot 2019-07-02 at 3 55 17 PM](https://user-images.githubusercontent.com/15113219/60542431-f2683100-9ce1-11e9-9d56-18c90cb98a6c.png)

**Comment by Xymmer** [comment]
we don't want to do too much in checkout, so it was decided not to be able to set default in checkout

can the visibility be set by you guys are is it a ts thing?

**Comment by developpeurweb** [comment]
@Xymmer we can set it as `display: none` (this can be unset by the client though).

**Comment by Platonn** [comment]
I think it will be safer and more maintainable to do it in the component's logic

**Comment by qjimmy** [comment]
PR #8273
