### ISSUE TITLE
[android] title is not updated after remove applied filter

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#3514]
![image](https://user-images.githubusercontent.com/8040837/60508289-7c0c0480-9cca-11e9-863f-caadbd9d54a7.png)
After click "X" list of product is updated, but title not.
![image](https://user-images.githubusercontent.com/8040837/60508391-b37ab100-9cca-11e9-8ee8-478a79d8e748.png)

**Comment by psmul** [comment]
Problem occurs only for mobile devices. When calling */search?* call, no *breadcrumbs* field is returned which results in not refreshing search results header. Tested only on the public instance, should be checked on dev-envs.

**Comment by bgambocjaviniar** [comment]
Closing as it is no longer an issue. You can verify by testing in the current public instance https://spartacusstore.cg79x9wuu9-eccommerc1-p4-public.model-t.myhybris.cloud/
