### ISSUE TITLE
[Xiaomi/Firefox] - Close Menu on 'back' button press for mobile

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#3522]
It would feel more natural on mobile to close the menu modal when it is open on 'back' press and navigating to the previous page if the menu is closed.

**Comment by developpeurweb** [comment]
@Xymmer UX suggestion TBD with Manu and Anthony. If a GO, this will be more on the TS side.

**Comment by Xymmer** [comment]
closing as we have a project to do an overhaul of mobile experience, and we'll make sure this improvement is included for consideration
