### ISSUE TITLE
[retest] Broken styling of thumbnails in PDP for SSR

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#3542]
0. disable JavaScript in your browser
1. set baseUrl to modelt
2. run ssr
```
yarn build:core:lib
yarn build
yarn build:ssr
yarn start:ssr
```
3. Go to http://localhost:4200/electronics-spa/en/USD/product/1990255/DSC-HX1

Then the styling of thumbnails is broken:

![obraz](https://user-images.githubusercontent.com/4001059/60579796-1da35c80-9d84-11e9-9d8b-cf23e641cab3.png)

**Comment by psmul** [comment]
After discussion with Tobias, fixing this issue is put to "ON HOLD" due to fact of big carousel refactor coming relatively soon.

**Comment by Platonn** [comment]
We should check if the carousel refactor was already done and if the bug disappeared .

**Comment by Xymmer** [comment]
Moving to 2.1, if we discover there is a problem in 2.0, let's backport fix to 2.0.1.
Also we need ccv2 running SSR so ask Gil when ready

**Comment by Xymmer** [comment]
it's a safari renderer problem
doesn't happen in firefox or chrome on desktop, but in safari on desktop and in ios (as all browsers use same renderer in ios)

**Comment by Xymmer** [comment]
are we really supporting non-javascript?
i tested this with my ccv2 that has a slightly older 2.0 and it also doesn't work beyond home page

changing priority from 2.1 to 2.x
i'm pretty sure we aren't supporting that scenario, but let's discuss

**Comment by giancorderoortiz** [comment]
Correct. Same behaviour seen in Edge. Unable to pass beyond homepage. @tobi-or-not-tobi fyi.
