### ISSUE TITLE
Upselling products - no image on the item causes visual issues

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#3564]
## Environment Details

dev-com-19

## Steps to Reproduce

go to product - 3557133

## Observed Results

Visual issues due to no image existing in the backend for this item
![Screen Shot 2019-07-03 at 2 45 10 PM](https://user-images.githubusercontent.com/29099466/60617315-7b926d00-9da1-11e9-8bec-40d330973a72.png)

## Expected Results
should have a placeholder

**Comment by qjimmy** [comment]
Added the vbc label, will remove from board.

**Comment by dydome** [comment]
@bgambocjaviniar looks like the problem is solved now and the issue could be close.
