### ISSUE TITLE
[Android][Chrome] Alt image in a cart is too large

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#3567]
![image](https://user-images.githubusercontent.com/8040837/60657874-57db2f80-9e52-11e9-83a3-24f8550ac332.png)

**Comment by dydome** [comment]
@Pucek9  Checked it on the latest version and the problem does not exist anymore.

![image](https://user-images.githubusercontent.com/18736434/105490928-d3f7cb00-5cb5-11eb-8e37-f9b67c9defdd.png)
