### ISSUE TITLE
Add type safety to Checkout module

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#357]
Typesafety should be added wherever possible. A few suggestions where type safety should be added:

* method parameters
* method return values
* if there's no return value for method (it's void), add `void` as the return to make it more specific
* test files
* object literals
* if you need OCC types, take a look at #301's PR
* if working with CMS components, as a generic type use `<T extends Component>`, where `Component` is an interface from `projects/core/src/occ-models/occ.models.ts`

The goal is to have a completely type safety code.

**Comment by MitchellScottSandre** [comment]
PR: GH-409

**Comment by MitchellScottSandre** [comment]
@WeizhengSap I have made all changes you requested to the PR. I also pulled your changes that you made but am not getting 2 errors related to ` Can't bind to 'cxOutlet' since it isn't a known property of 'ng-container'.` and I do not know where to begin to investigate this problem
