### ISSUE TITLE
Checkmarx - Angular_Improper_Type_Pipe_Usage

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#3634]
**Scan Date:**
June 30, 2019.

**Report**
https://cx.wdf.sap.corp/CxWebClient/ViewerMain.aspx?scanId=4547096&ProjectID=63198

**File:**
\cloud-commerce-spartacus-storefront-develop\projects\storefrontlib\src\cms-components\myaccount\consent-management\components\consent-management.component.html

**Line:**
12

**Violations:**
1

**Checkmarx Severity**
Medium

**Issue:**
Angular_Improper_Type_Pipe_Usage

**Comment:**

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-10 at 5 39 56 PM](https://user-images.githubusercontent.com/46171897/61007012-c714c000-a339-11e9-855b-172ea255152b.png)

**Comment by tobi-or-not-tobi** [comment]
I do not see a problem with this code, looks very standard to me (assuming it's about line 12).

**Comment by giancorderoortiz** [comment]
Issue no longer seen in 2.0-rc.0.
Closing ticket.
