### ISSUE TITLE
[retest after #3663] Able to Add Addresses After User Signout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#3635]
**Setup:**
1. Open Burp and setup proxy. 
2. Setup browser to burp's proxy. 

**Steps to Reproduce:** 
1. Navigate to Spartacus storefront. (easier if using Firefox)
2. Register as new user. (hereinafter john.doe@acme.com)
3. Sign out. 
4. Sign in as john.doe
5. Navigate to My Account -> Address Book
6. Add one address. 

7. In parallel, using Burp, navigate to http history and send current addresses request to repeater. 
(i.e. GET /rest/v2/electronics-spa/users/current/addresses?)
8. In repeater, execute request one more time to confirm addresses from user john.doe can be retrieved. 

9. In Spartacus storefront, sign out and wait 15 - 30 seconds. 
10. In burp -> repeater, request addreses one more time. 

**Expected results:** 
10. Access violation error. Bearer token has expired. 

**Actual results:**
10. Able to retrieve user john.doe's addresses. 
10.a. Furthermore, I am able to add addresses subsequently (Using POST /rest/v2/electronics-spa/users/current/addresses?)
11. I'm even able to continue adding addresses if another user is logged in Spartacus. (I thought having this new user would invalid previous token somehow)

**Comment by giancorderoortiz** [comment]
![address-added-after-logout](https://user-images.githubusercontent.com/46171897/61008139-c6c9f400-a33c-11e9-8412-a1eafaba65a1.png)
![burp-add-user-address](https://user-images.githubusercontent.com/46171897/61008140-c6c9f400-a33c-11e9-96b7-bd79ae35e6ce.png)
![burp-get-user-addresses](https://user-images.githubusercontent.com/46171897/61008141-c6c9f400-a33c-11e9-9e50-2a8d135f1322.png)
![different-user](https://user-images.githubusercontent.com/46171897/61008142-c6c9f400-a33c-11e9-9032-2b39f7ea893d.png)
![get-user-address-after-logout](https://user-images.githubusercontent.com/46171897/61008143-c6c9f400-a33c-11e9-9ec0-17da41af950c.png)

**Comment by meeque** [comment]
Well, the underlying problem is that Spartacus does not invalidate Access Tokens and Refresh Tokens. This is well known, but sad behavior.

Upon user logout, Spartacus merely forgets the tokens in the Web Browser. It does not invoke any token invalidation on the server side. 

Thus, any tokens that Burp (or any other tool) previously collected, can still be used to authorize any API requests to the server.

This is an architectural risk in the current implementation of both Spartacus and the SAP Commerce oAuth extension.

**Comment by giancorderoortiz** [comment]
See #1018

**Comment by hackergil** [comment]
This will be fixed with #3663

**Comment by Xymmer** [comment]
rested after #3663

**Comment by giancorderoortiz** [comment]
This issue is now solved. 
Session token actually invalidated after user logout
![Screen Shot 2020-10-25 at 3 32 28 PM](https://user-images.githubusercontent.com/46171897/97117086-e4f56800-16d7-11eb-9757-a1e9e8ba2036.png)
![Screen Shot 2020-10-25 at 3 36 07 PM](https://user-images.githubusercontent.com/46171897/97117087-e58dfe80-16d7-11eb-8721-2bd478fa33ed.png)
