### ISSUE TITLE
Performance improvements for CMS page load [master]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#3649]
There are a number of performance improvements we can make in Spartacus to improve the loading of the initial and sub-sequential pages. This ticket describes a high-level change in the consumption of the backend API (OCC) to load page data. Whenever we're happy with a high-level design, we'll start the discussion with backend teams to see if they can support us here. 
There are number of topics that we like to improve:
- Payload of the CMS page structure
- Splitting the CMS page structure in both page and page template
- improve cache-ability of the CMS page structure

**CMS page structure payload** (#3668)
One of the main performance gains will be around the CMS page structure which is loaded when we navigate the storefront. The current payload is polluted and too heavy weighted for the purpose, and is loaded over and over again during navigation. While there is actually a good reason to reload page data while navigating (in order to support the CMS restrictions which might expose new pages and components during navigation), the possibility that component would actual change on a 2nd page load is fairly low. Therefor we should consider a more efficient API that will be used to evaluate if there's a change. If any, we could do an additional call, or – even better – introduce server push to preload it automatically.

**Avoid reloading full page data**  (see #3667)
Additionally, the current page payload contains both the CMS page structure as well as the associated CMS page template structure. As already pointed out, the payload is heavy, and blocks the experience. In order to optimise, we should avoid loading the full payload during navigation. 

**Improve cache-ability** (TODO: needs flashing out)
Another area of improvements is related to caching. With the cache architecture we're aiming for (#1169), we like caching of static ánd dynamic content wherever we can. Caching improves the experience on the first visit (loading from CDN) as well as on any sub-sequential page-visits in the same session (loading from service worker). There are however a number of areas where we cannot cache the payload due to a couple of reasons: 
- The payload contains both data that should and should not be cached. For example, the product details contain both the static product data as well as stock and price data. Since this is exposed in a single payload, there's no optimised approach to cache this data, even within the single page experience. Let alone a returning user. 
- The payload of the backend is often personalised while the endpoint itself is generic. This means that the payload cannot be cached on the CDN, simply because other users would have the same payload. In order to ensure a unique ánd cached payload at the same time, the endpoints must be made unique.

**Comment by dunqan** [comment]
We should postpone/do GH-4603 first.

**Comment by tramtranthingoc** [comment]
Hi @tobi-or-not-tobi,

Do you have any update on progress of "Improve cache-ability: The payload contains both data that should and should not be cached. For example, the product details contain both the static product data as well as stock and price data." ?

Thank you,
Tram Tran

**Comment by Xymmer** [comment]
Hi we have closed this issue as we won't get to it soon, but when we revisit, we'll reopen or create a new ticket. There is no update on the issue mentioned.
