### ISSUE TITLE
[requires cms occ update] Avoid reloading full page data

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#3667]
This ticket is part of a wider initiative to improve the performance (#3649).  

The current page payload contains always the CMS page structure and the associated CMS page template structure. This is polluting the payload with every page load, while in most cases the data doesn't change. While there's another improvement ticket to minimise the payload (#3668), this ticket is about making the overall payload ore efficient. 

There's a good reason to reload the full page data (including the header and footer) when the user navigates to the next page, as so-called personalisation can cause a change in previous loaded page data. The user behaviour can impact any components during navigating, even if they're in the header and footer. That being said, the likeliness of loading new data in the same session is fairly small, and in a lot of storefronts not even happening at all. This is why we're looking into a more efficient approach to validate whether new page(template) data is available for the next page. 

In order to optimise the performance, the backend API must be called in such a way that existing data is not exposed again. It is important to not break the existing API, so that the new approach is backwards compatible. While we could introduce new endpoints to expose page vs page template data, we can keep using the existing API with a small (optional) addition. This is illustrated in the following steps:

1. User opens page A
2. Spartacus loads both the CMS page data as well as the CMS page template slot data, using the existing `/cms/pages` API.  
  The API returns a (new) hash for both the page data (`pageHash`) as well as a hash for the pageTemplate data (`pageTemplateHash`). 
3. The user navigates to page B
4. Spartacus uses the existing `/cms/pages` API, but passes in both the `pageHash` and `pageTemplateHash` which has been given in the previous request.
  If the page template changes has changed between page A and B (i.e. if A was the login page), the page template data will be returned together with the new `pageTemplateHash`;
5. The user navigates back to page A  
6. Spartacus uses the existing `/cms/pages` API, but passes in both the `pageHash` and `pageTemplateHash` which has been given in the previous request.  
  If the page has changed since the last visit (i.e. a new component is exposed because of the user roles), the page data will be returned. If there's no change, only the same `pageHash` is returned. 
  If the page template has changed since the last visit, the page template data will be returned. If there's no change, only the same `pageTemplateHash` is returned. 

This approach comes with the following advantages:
- Performance; during most navigation the page template data will not be added, and in a lot of occasions the page data is not reloaded as well.
- Accurate; we always validate whether the existing page data is up-to-date. Moreover, if different data is being requested (i.e. other fields), this will work transparent.
- Efficient; everything is done with a single API call, no need to have complete new endpoints or do any validation client side. We only add the hashes. 
- Backwards compatible; if the page or page template hashes are not given, it works like before. (Spartacus should also be backwards compatible in case the hashes are not returned).
- Simple; the hash is created server side, so that we do not have two places to create the hash. This is more simple and avoids two different hash techniques. Moreover, we can change the hashing strategy going forward.

Storefronts that uses multiple page templates, could even benefit from caching multiple data sets by using the `pageTemplateHash` key.

This could be a CMS specific solution, but we could also consider making this an OCC generic solution. All APIs could be used in a similar way. This would however mean that we need to come up with a 2nd endpoint for page templates, as otherwise the page template will be exposed with every new page.

**Comment by tobi-or-not-tobi** [comment]
@Xymmer not sure why you closed this, it's an important ticket that requires significant changes in our code base. While we discussed this with the CMS team to come up with the API, we also need a (master) ticket to align and execute in Spartacus.

Once the CMS ticket is created we should link it here.

**Comment by Xymmer** [comment]
Transferred to SmartEdit team: CMSX-9147

**Comment by rirypheng** [comment]
To be addressed in CMSX-9146 instead.

**Comment by tobi-or-not-tobi** [comment]
We're evaluating an alternative design based on Etags, as this will give us a standard approach for a hash. The only open question we're investigating atm, is whether the etag hash can be used in the client app. If that's the case, the design in this ticket will change. 

With etags, the flow could become:
- page endpoint for page-only components and some page metadata (including page template ID). The etag found on the http response (if available?) will be stored in the client.
- The page template ID returned with the 1st request is used for a 2nd request to fetch the page template components. Again, the etag found on the http response (if available?) will be stored in the client.
- On next page / template responses, we compare the etag with the current (or any stored) to avoid a re-store the content in case it's the same. 

This design would both benefit from network consumption as well as client optimisation. It would however not decrease the load on the server, since the request will go out anyway. 

FYI @rirypheng

**Comment by RomanTikhonov** [comment]
Hi Guys!
We still have a problem with duplicate pageData requests. Is this issue related with this question or there is an other?

Thanks! =)

**Comment by znikola** [comment]
TODO:

- [ ] - Issue a back-end PR to `cmsoccaddon`. The controllers that need to be changed are: `cmsoccaddon/acceleratoraddon/web/src/de/hybris/platform/cmsoccaddon/controllers/ComponentController.java` and `cmsoccaddon/acceleratoraddon/web/src/de/hybris/platform/cmsoccaddon/controllers/PageController.java`. Add the `@CacheControl(directive = CacheControlDirective.PRIVATE)` on the class-level. The imports are: 
```
import de.hybris.platform.webservicescommons.cache.CacheControl;
import de.hybris.platform.webservicescommons.cache.CacheControlDirective;
```
