### ISSUE TITLE
Firefox: Lang & Curr drop down menu are barely readable

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#3692]
**Environment Details**
Spartacus: 1.0.1
Browser: Firefox
Device: mac 
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
Click on the language drop down menu

**Actual Result**
The color is white, a whitish background, making it really hard to read, unless you hover over the menu items. 
<img width="1215" alt="Screen Shot 2019-07-17 at 10 35 15 AM" src="https://user-images.githubusercontent.com/45409515/61384649-0766c780-a87f-11e9-9a7c-8d915198198f.png">

**Comment by developpeurweb** [comment]
This is a small Firefox fix adjusting the `select` menu's `background-color` and the icon's `z-index` in this file:
`projects/storefrontstyles/scss/components/layout/header/_site-context-selector.scss`

**Comment by bgambocjaviniar** [comment]
works in chrome, safari, and firefox now
