### ISSUE TITLE
Track button in order details doesn't look right

### ISSUE THREAD

**Issue by joseegm** [SAP/spartacus#3713]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  branch feature/consignment tracking
- Browser: all
- OS: all
- Device: all
- Other environment details: 

## Steps to Reproduce
Navigate to My Account -> Order History -> Click on an order that has been shipped

## Observed Results
![Screen Shot 2019-07-19 at 11 23 51](https://user-images.githubusercontent.com/22662903/61526517-d0c5b400-aa1a-11e9-9b07-e3ae5ed76e2a.png)
Visual Inconsistency with the Design Design Guideline

## Expected Results
![Group 3223](https://user-images.githubusercontent.com/22662903/61526690-34e87800-aa1b-11e9-821f-8e223dbf9aec.png)
Design Guideline

## Repository Used
main repo

**Comment by Xymmer** [comment]
#3055 and #3713 are probably the same issue

**Comment by developpeurweb** [comment]
This has long been fixed, but only works in calydon, therefore lining up for `calydon-as-base`

**Comment by developpeurweb** [comment]
This is no longer an issue if we take the initial screenshot as reference, although on this comment's date, the current DOM only has a button and the rest of the information is displayed in a modal. There must have been an exception to the design guidelines at some point, @Xymmer can you please validate the layout shown in the screenshots below as the correct one:

<img width="1193" alt="Screen Shot 2020-03-30 at 4 50 19 PM" src="https://user-images.githubusercontent.com/15113219/77960997-2be8bf80-72a7-11ea-994e-a917ac3d4b21.png">

<img width="1207" alt="Screen Shot 2020-03-30 at 4 48 49 PM" src="https://user-images.githubusercontent.com/15113219/77961027-3a36db80-72a7-11ea-96df-32efe4df83fa.png">

**Comment by Xymmer** [comment]
looks good

**Comment by KateChuen** [comment]
Tested on dev10 on chrome, firefox, safari. I don't have the shipping date, so the Track button is closer to the element above it. 
I think it still looks ok. 

<img width="1216" alt="Screen Shot 2020-04-07 at 9 19 44 AM" src="https://user-images.githubusercontent.com/45409515/78677507-d4091480-78b5-11ea-8827-d595b63aee00.png">
