### ISSUE TITLE
[ready now, #4603 almost done] Allow to get multiple cms components data in one request

### ISSUE THREAD

**Issue by msoplinski** [SAP/spartacus#3769]
Feature request (discussed with @WeizhengSap on Slack):

For now in `CmsService.getComponentData` we can get one component's data via its uid. This method prepares request to OCC and saves response as component data in the store and returns an observable with such chain.

However, for navigation there is a custom method to fetch multiple navigation node components in one request (see `NavigationEntryItemEffects` and `CmsComponentConnector.getList`).

What we miss here is to have a method like `CmsService.getComponentsData` which will get a list of uids of component and prepare one request to OCC for multiple components data.

**Comment by artem-zur** [comment]
Hi guys!
Any news about this case ?

Will be grateful, if we can make this issue more priority.

**Comment by Xymmer** [comment]
@artem-zur it's doable so we'll try

**Comment by Xymmer** [comment]
note to dev: make sure this change is backwards compatible.

**Comment by WeizhengSap** [comment]
Please don't forget to pass `productCode`, `categoryCode`, and `categoryCode` as parameters.

**Comment by Platonn** [comment]
We should postpone/do GH-4603 first.

**Comment by Platonn** [comment]
### The meaty part was done in https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/4603 . As a result of it, the method `CmsService.getComponentData` still recieves only one id (not array), but the ngrx effect buffers all the actions dispatched in one Javascript tick (i.e. done in one `forEach`) to make only one http call in with all buffered IDs (scheduled for the next macrotask).

Therefore the requirements for this ticket can be adding method:
```
getComponentsData(uids: string[]){
return combineLatest(uids.map(uid => this.getComponentData(uid)))
   .pipe(debounceTime(0)) // prevent cascading partial updates in one tick
}
```

**Comment by znikola** [comment]
PR: #6236

**Comment by znikola** [comment]
`getComponentData` method can be safely and optimally used to load multiple components data at the same time. Calling `getComponentData` multiple times for different components will always result in optimized back-end request: all components requested at the same time (in one event loop) will be loaded in one network call.

Therefore, closing this issue for now, as there's no need to add a new method.
