### ISSUE TITLE
[Breaking changes] Redo #3229 as it was revert

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#3838]
See description in #3229

**Comment by Xymmer** [comment]
@LTiger14  question: we redo in 2.x?

**Comment by LTiger14** [comment]
To be redone as part of 2.x since it is a breaking change for 1.x.

**Comment by Xymmer** [comment]
@Platonn evaluate if this is a MUST for 2.0 as it was a breaking change that was reverted.

**Comment by kacperknapik** [comment]
**QA results**
- works as expected
