### ISSUE TITLE
[Breaking changes] Redo GH-2737 as it was revert

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#3839]
See
issue: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/2737
pr: https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/3731

NOTE: will revert back once we can handle breaking changes properly

**Comment by bgambocjaviniar** [comment]
REVERT PR: GH-3840

**Comment by bgambocjaviniar** [comment]
Keeping this open to revert back to what it needs to be when ready

**Comment by Xymmer** [comment]
@bgambocjaviniar : this is for 2.x?

**Comment by bgambocjaviniar** [comment]
Well apparently, this was pushed 15 days after reverting to not include breaking change, but the new flow became this one

https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3140, so I don't know if this is relevant anymore

**Comment by Xymmer** [comment]
tried it just now, doesn't happen anymore
