### ISSUE TITLE
Remove "/" from E2E cypress.json baseUrl

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#3878]
Having baseUrl as "http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/" causes random failures when running regression tests. 

Ending "/" should be removed automatically in case of user error (which is fairly common in this case). 

End to end tests must work with either:
"http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/"
"http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200"

file: /spartacus-installation/source/projects/storefrontapp-e2e-cypress/cypress.json

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-07-31 at 3 21 01 PM](https://user-images.githubusercontent.com/46171897/62241516-4b8db800-b3a7-11e9-8d55-9761740948a0.png)

**Comment by marlass** [comment]
Already in place
