### ISSUE TITLE
Spike: check if IVY is ready for chained libs

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#3888]
During the spike for IVY that I did about month ago I had problems to ivy-compile Storefront lib due to errors complaining about previously ivy-compiled Core lib dependency.

Possibly, the recent fix https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3741 could fix the problem - we need to double check.

If we still cannot compile with ivy all 3 elements: Core, Storefront and ShellApp (in a chain), we should verify whether IVY is ready for chained libs at all (it's not guaranteed, as IVY is still experimental feature). For instance, we can generate new 2 dummy libs (one depending on another) and a new shell app and try to compile them all with IVY.

---
#### How to enable ivy compiler
Set `angularCompilerOptions.enableIvy: true` in tsconfig of all libs/shell app.
Note: it runs ivy-ngcc (backward compatibility compiler) on all angular projects in node_modules (even @angular/core, etc.).

#### How to run ivy-ngcc (ivy backward compatibility compiler) on some dependency manually (i.e. on sprtacus core lib) 
run `node_modules/.bin/ivy-ngcc`

#### Fix known IVY's issue with ModuleWithProviders
Set `angularCompilerOptions.decoratorsAs: "static fields"` in ts config of all libs.
(source: https://medium.com/@sarunint/how-can-you-experimentally-try-angular-ivy-right-now-c23930062b4c , https://github.com/angular/angular/issues/28603)

**Comment by Xymmer** [comment]
We are about to release 2.0 with ng 9, so I assume this ticket no longer needed

**Comment by Platonn** [comment]
Angular team recommended not to compile libs (but only apps) with IVY until Angular 10/11. By then Angular team promised that it will be able to compile libs with ivy
