### ISSUE TITLE
Re-organizing ngrx store for storefinder

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#3943]
NgRX store for storefinder have to be reorganized. Right now we use same data in two places.

Example:
![_store_duplicated_data](https://user-images.githubusercontent.com/6958810/62536638-baa75880-b84e-11e9-9931-65d044a3932c.png)

Goal: create only one object and there keep all necessary data for storefinder.

Name: dev's choice.

**Comment by mszczepaniak** [comment]
We decided that we will release this ticket in the next patch after the storefinder will be released, since it has no direct impact on the functionality itself.

**Comment by Xymmer** [comment]
update: we'll aim to do this for 3.0, as it requires a lot of breaking changes

**Comment by dunqan** [comment]
We should not refactor ngrx store here, the alternative improvement with Command and Queries should be considered.
