### ISSUE TITLE
login cms page loaded again after redirect from login to other page

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#3974]
## Steps to Reproduce
1. as anonymous user, load 'my-account/address-book' page directly
2. user is redirected to 'login page', then login this user
3. user is redirected to 'my-account/address-book' page.
4. open network tab, you will see that 'login' page is loaded when redirect from 'login' page to 'my-account/address-book' page.

![Screen Shot 2019-08-07 at 12 49 31 PM](https://user-images.githubusercontent.com/44440575/62641708-3c13ef00-b912-11e9-9e68-21b8535af649.png)

**Comment by dydome** [comment]
Verified, and the problem does not exist anymore.
