### ISSUE TITLE
unable to get/set storage data such as refresh_token programmatically 

### ISSUE THREAD

**Issue by mrSingh007** [SAP/spartacus#3992]
I am trying to set refresh token to localStorage after user have selected a remember me checkbox (Remember me functionality). Currently  there is no any way to set this programmatically except through config like:
```
const config:StateConfig = {
      state: {
        storageSync :{
          keys: {
            "auth.userToken.token.refresh_token": StorageSyncType.LOCAL_STORAGE
          }
        }
      }
  }
```
But I want to set storage from component after performing some actions. Currently unable to find any docu or service which can do this.

## Environment Details

- Spartacus:   "@spartacus/assets": "~1.0.1",
    "@spartacus/core": "~1.0.1",
    "@spartacus/storefront": "~1.0.1",
    "@spartacus/styles": "~1.0.1"
- Browser: chrome

## Expected Results
should be possible to set refresh_token to the storage from component through a service.

## Offer to Fix
NO

**Comment by mrSingh007** [comment]
similar like `getKeysForStorage` there should be public method `setKeysForStorage` method

**Comment by marlass** [comment]
In 2.0 we release new state persistence service which could be used here to solve this problem. Closing this ticket.
