### ISSUE TITLE
Refactor Page templates

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#4]
Page templates control the overal layout of a page and can be selected by business users in the CMS. Our storefront UI must have a clean list of page template components, which only represent a CMS page templates from the backend. The current implementation has a number of issues:
- Multiple page templates have been introduced lately for no good reason, we need to clean this up
- Page templates and page components are redundant. We can drop the page components and route directly to the page template component. This is related to the work in #3. 
- Page templates should only represent the "page", any sub sections (i.e. myaccount/addresses) should reuse the page template (and could introduce nested router outlets, see again #3.

**Comment by Xymmer** [comment]
this ticket is old so i'm checking with tobias if still valid

**Comment by Xymmer** [comment]
we'll have to define what to do, and check if there would be breaking changes.
