### ISSUE TITLE
Deprecated in 1.1: Occ configurable endpoints (#4066)

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#4125]
For 2.0:

`client-authentication-token.service.ts`
- Make OccEndpointsService in constructor mandatory

`user-authentication-token.service.ts`
- Make OccEndpointsService in constructor mandatory

`occ-cart-entry.adapter.ts`
- Remove `getCartEndpoint`
- Remove //Todo 2.0: Remove
- Remove legacy methods
- Remove FeatureConfigService from constructor

`occ-cart.adapter.ts`
- Remove `getCartEndpoint`
- Remove //Todo 2.0: Remove
- Remove legacy methods
- Remove FeatureConfigService from constructor

`occ-user-order.adapter.ts`
- Remove `getCartEndpoint`
- Remove //Todo 2.0: Remove
- Remove legacy methods
- Remove FeatureConfigService from constructor

`feature-toggles.ts`
- Remove feature toggle for configurableOccEndpoints

**Comment by bgambocjaviniar** [comment]
PR: GH-6926
