### ISSUE TITLE
Outlet ID for SimpleResponsiveBannerComponent missing last letter

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4226]
The name for banners is 
SimpleResponsiveBannerComponent

but the ID generated for outlets is missing the last 't'
is this an issue or just a limitation?
![image](https://user-images.githubusercontent.com/4998145/63604410-a5922f80-c599-11e9-88c6-2f3dec4a1f31.png)

**Comment by KateChuen** [comment]
It's a typo, and very quick to fix but if we fix it, it's a breaking change.

**Comment by KateChuen** [comment]
Gil confirms that it's being truncated, and it's not a typo.

**Comment by Xymmer** [comment]
@Platonn is this something we should fix or live with?

**Comment by tobi-or-not-tobi** [comment]
This is actually not a bug nor a typo. The `[ng-reflect-model]` that is used under the hood has a maximum limit of 30 characters, the rest of the outlet ref is truncated. There are other reasons why this way of debugging the outlets isn't good enough. Long story short, we're not able to fix this, nor do we want the future of outlets/sproutlets to be base on the inline comments that are visible in dev mode.
