### ISSUE TITLE
Test codebase on examples of insecure usage of native APIs

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#4249]
While doing a threat modelling review on the codebase, we've discussed some usage of native APIs rather than using the Angular APIs. This can lead to insecure code, so we should double check on this. 

we need to:
- make the team aware of the code that can hurt
- do regular tests on the code (i.e. every major release)

**Comment by meeque** [comment]
Some ideas on what to search for in the code base:

* By-pass of Angular sanitization:
  Usage of the `bypass*` methods of [DomSanitizer](https://angular.io/api/platform-browser/DomSanitizer)
* Access to underlying DOM API for an Angular component:
  Usage of the `nativeElement` accessor of Angular [ElementRef](https://angular.io/api/core/ElementRef#properties)
* Direct usage of native DOM APIs:
  Often such access is rooted in `document` of the [DOM API](https://developer.mozilla.org/en-US/docs/Web/API/Document). In particular, watch out for usage of DOM `innerHtml` and similar.
* Evaluation of dynamic JS code:
  `eval()`, but also `setTimeout()` and `setInterval()` when used with a `string` argument.

**Comment by meeque** [comment]
Fyi, #3031 seems to be similar to this one.
