### ISSUE TITLE
Mitigate errors in URL decoding

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#4252]
There's a concern that the handling of URL path parameter and endpoint configuration for the backend configuration is vulnerable when special characters are used in the product codes. For example non-ascii, chines or polish characters. 

We should add some tests to make sure that sanitisation is done in the right way. 

An example is give with a question mark in the product code: 
- the browser will encode the question mark
- the application will decode the question mark 
- the application code doesn't test on the validation of the generated URL (the question mark for example would break the OCC endpoint)

We like to follow up on this risk and must do the following:
- consider replacing dynamicTemplate with some custom solution that will handle basic string interpolation with proper escaping
- if decided to keep dynamicTemplate, add missing tests
- add tests to OccEndpointsService to make sure we encode / decode parameters in the right way.

**Comment by dunqan** [comment]
Example:
For product code set as: 'd sa ? dsa sdsaa / /   '
We get this not valid url as a result: '/rest/v2/electronics-spa/products/d sa ? dsa sdsaa / /   ?fields=DEFAULT,averageRating,images(FULL),classifications,numberOfReviews,categories(FULL)'
