### ISSUE TITLE
Better have progress-bar or some message after adding payment method

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#4280]
In checkout step 3 (adding payment method), after clicking "continue" button, it may take several seconds for the new payment to be validated and added. It's better that there is some message or progress-bar/spinner telling the user to wait for this process.

**Comment by WeizhengSap** [comment]
Maybe duplicate with this: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3102

**Comment by qjimmy** [comment]
Fixed by PR-4544

**Comment by qjimmy** [comment]
@Xymmer not sure, but I think PR #5678 should close this. There's a spinner while the payment is processing now.

**Comment by WeizhengSap** [comment]
It can be closed.
