### ISSUE TITLE
Spike LoginPage hosted by authorisation server

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#4281]
Implement oauth implicit with:
- add iframe with authorisation login page in the CMS login component
- implement redirected page
- store the access token whenever there's a successful redirect

**Comment by meeque** [comment]
Here is an example URL to the authorization endpoint of SAP Commerce:

https://localhost:9002/authorizationserver/oauth/authorize?response_type=token&client_id=spartacus&state=123&redirect_uri=https%3A%2F%2Flocalhost%2Fredirect
