### ISSUE TITLE
e2e tests for order cancellations

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#4291]
The steps are:
1. place an order (status is `in progress`)
2. open order details page, you should see `cancel items` button
3. click the button, go to `cancel order` page, you should see a list of `cancellable` items (there is 'max quantity' link, clicking which can max all quantities)
4. click 'continue' button, go to confirmation page, you should see the items with quantities you set in last step (make sure the total is calculated correctly)
5. click 'submit request' button, order is cancelled partially or completely. If this step is successful, you should be redirect to 'order history' page.

**Comment by qjimmy** [comment]
PR #5843

**Comment by qjimmy** [comment]
PR #6048

**Comment by qjimmy** [comment]
Need to merge into develop with the new changes

**Comment by qjimmy** [comment]
PR #6725

**Comment by bgambocjaviniar** [comment]
Asking if we need above right now because it was skipped for 1.4, and we do not know if it works, so it would be redundant to have it

**Comment by hackergil** [comment]
We have tests for C&R now.
