### ISSUE TITLE
[PARKED] Keep expanded list when going back to the PLP page when using Infinite Scroll

### ISSUE THREAD

**Issue by RadhepS** [SAP/spartacus#4362]
Improvement that should be done to Infinite Scroll.

Steps:
1. Activate Infinite Scroll
2. Navigate to Product List Page
3. Scroll down and cause the list to expand
4. Click on any product (This will navigate you to the product details page)
5. Click the back button on the browser

Expected result:
It should display the old expanded list

Current result:
It resets the list to the original size.

**Comment by Xymmer** [comment]
This is actually a PWA guideline
https://developers.google.com/web/progressive-web-apps/checklist#pressing-back-from-a-detail-page-retains-scroll-position-on-the----------previous-list-page

**Comment by Xymmer** [comment]
#5143 depends on this one
