### ISSUE TITLE
[Depending on RAY-447] Add to cart modal should not be displayed if item was not added to cart

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#4363]
**Environment Details**
Spartacus: develop branch
Browser: Safari
Device: mac
Happens on: https://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- Go to a product that has variant, for eg: product: 1978440_md
- Click on "Add to cart"

**Actual Result**
You get an error that you should choose a variant in the background, but you also get the "add to cart modal". 
![Screen Shot 2019-08-30 at 2 56 28 PM](https://user-images.githubusercontent.com/45409515/64045208-bfea8100-cb36-11e9-8854-4b81f22f5f9e.png)

**Expected Result**
Perhaps in case of errors where the item was not actually added to cart, the "add to cart" modal should not be displayed?

**Comment by WeizhengSap** [comment]
There is `purchasable` property in product data. If it is `false`, the `add to cart` button should disabled
![Screen Shot 2019-10-02 at 8 36 46 AM](https://user-images.githubusercontent.com/44440575/66044690-2248ef80-e4f0-11e9-8002-d696df884f1d.png)

**Comment by Xymmer** [comment]
Depends on https://cxjira.sap.com/browse/RAY-447
The purchasable field shows up for pdp page but not search query

**Comment by giancorderoortiz** [comment]
Unable to reproduce with Spartacus 3.0.
