### ISSUE TITLE
Search Service should return results instead of updating SearchBoxComponent

### ISSUE THREAD

**Issue by mrSingh007** [SAP/spartacus#4384]
Currently `SearchService` have `search` method, which have return type void. Because of that this service can not be used for other purposes (like quick entry). 
There should be another method which should return result as observable so that service can be used on other components. 

Currently `search` method update `SearchBoxComponent`  automatically.

## Environment Details

  @spartacus/assets": "~1.0.4",
    "@spartacus/core": "~1.0.4",
    "@spartacus/storefront": "~1.0.4",
    "@spartacus/styles": "~1.0.2",

## Offer to Fix
NO

**Comment by Pucek9** [comment]
In storefrontlib we have: `SearchBoxComponent` and `SearchBoxComponentService`. SearchBoxComponentService has been created to move part of dependencies & logic from component to service. It allows replacing that logic
Main dependency is SearchboxService (fascade) from core.

I understand you want to have a method search observable. Why you don't want to observe `this.searchBoxComponentService.getResults(config)`?

**Comment by mrSingh007** [comment]
Hi @Pucek9 , its being long time since this ticket was created. Is your question still open for me? 
if yes, I have to analyse again in 1.3 version. Let me know, if you need any info from me and if I should analyse the problem again.

**Comment by Pucek9** [comment]
Hi @mrSingh007, AFAIK SearchBox was not refactored since that time, the approach should be same
