### ISSUE TITLE
cart.e2e-spec.ts is failing on and off in nightly builds

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#4454]
this test has been failing on and off in the past couple of builds. 

In build 355 it fails because: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/355/console

>  1) Cart should add product to cart as anonymous and merge when logged in:
     CypressError: Timed out retrying: cy.click() failed because this element is not visible:

In build 353, it fails because:

>  1) Cart should be loaded for logged user after "cart not found" error:
     CypressError: Timed out retrying: cy.click() failed because this element is not visible:

**Comment by qjimmy** [comment]
Solved by GH-5287
