### ISSUE TITLE
Use feature toggle for enabling Kyma

### ISSUE THREAD

**Issue by josecervera** [SAP/spartacus#4481]
Reading the docs, I see Kyma integration is enabled by changing a property in the authentication configuration: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/kyma-integration/

For coherence, I think this should probably be a feature flag toggle which -I believe- were introduced later in the code:

https://sap.github.io/cloud-commerce-spartacus-storefront-docs/feature-flags-and-code-deprecation/

**Comment by znikola** [comment]
Hi @josecervera,
Thanks for pointing this out. You are right, we could use a feature toggle instead of the enable property in the config.
Another option that we will consider is to remove the flag all together, because importing the `KymaModule` should be enough to enable kyma integration.

**Comment by znikola** [comment]
Docs PR: https://github.com/SAP/spartacus-docs/pull/560
PR: https://github.com/SAP/spartacus/pull/7302
