### ISSUE TITLE
Review page: Qty & total do not align with the headers

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#4518]
**Environment Details**
Spartacus: Release 1.1.1 
Browser: Chrome
Device: mac
Happens on: http://dev-com-17.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
View 1100x900

**Steps to Reproduce**
Add a product to cart
Proceed to checkout

**Actual Result*
On the order review step, the qty & total do not align with the headers.

<img width="925" alt="Screen Shot 2019-09-11 at 11 55 14 AM" src="https://user-images.githubusercontent.com/45409515/64719605-97e41180-d496-11e9-8930-b0182e0f4de6.png">

**Comment by dydome** [comment]
The problem does not exist anymore. This page layout changed in the meantime: 
![image](https://user-images.githubusercontent.com/18736434/106874892-621c7a00-66d6-11eb-9bff-0f8b2df6c328.png)
