### ISSUE TITLE
Dual Backend Recipe - Smoke E2E Tests Failures

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#4536]
Smoke tests on dual recipe (dev-com3) are failing. 
(http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/)
Investigation not done yet. 
Backend has b2c_b2b_acc_oms + spartacus addon. 

Specs failing: 
1. checkout-flow-spec
2. currency-spec
3. outlets-e2e-spec
4. routing-e2e-spec

Failing 11. 
Passing 26

**Comment by bgambocjaviniar** [comment]
Forgot to put status:

checkout --> relating to pricing (not the same as what we have)
currency --> relating to pricing (not the same as what we have)
outlets --> its working
routing --> its working

**Comment by hackergil** [comment]
Closing this one since we are not using neither the server nor the recipe.
