### ISSUE TITLE
Dual Backend Recipe - Regression E2E Tests Failures

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#4547]
Regression tests on dual recipe (dev-com3) are failing.
(http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/)
Investigation not done yet.
Backend has b2c_b2b_acc_oms + spartacus addon.

Failing 71 tests. 
Failing specs: 
1. added-to-cart-modal.e2e
2. billing-address.e2e
3. cart.e2e
4. checkout-as-persistent-user
5. my-account/address-book-e2e
6. my-account/order-history-e2e
7. my-account/payment-method-e2e
8. site-context/currency...
9. site-context/language...

![Screen Shot 2019-09-13 at 7 58 35 AM](https://user-images.githubusercontent.com/46171897/64861825-ff1cd580-d5fe-11e9-8fa2-a9eb53b431cb.png)

**Comment by giancorderoortiz** [comment]
Screenshots and videos here: 

[regression_screenshots.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3609964/regression_screenshots.zip)

[regression_videos.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3609969/regression_videos.zip)

[product-search.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3609973/product-search.zip)

[my-account.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3609971/my-account.zip)

**Comment by giancorderoortiz** [comment]
Miscellaneous errors: 

1. Cart: 
![Cart -- should display empty cart if no items added and when items are removed (failed)](https://user-images.githubusercontent.com/46171897/64861888-25db0c00-d5ff-11e9-8b5f-ebac2512c183.png)

2. Payment Method
![Payment Methods -- should go to payment details page for login user -- should be able to set secondary card as default (failed)](https://user-images.githubusercontent.com/46171897/64861913-325f6480-d5ff-11e9-9053-3ff20bc6e472.png)

3. Order History
![Order History with orders -- should sort the orders table by given code (failed)](https://user-images.githubusercontent.com/46171897/64861928-44410780-d5ff-11e9-8f60-82837d5a536c.png)

4. Added to Cart: 
![Added to cart modal -- adding different products to cart (failed)](https://user-images.githubusercontent.com/46171897/64861951-558a1400-d5ff-11e9-8388-d1ba0f2c2488.png)

**Comment by hackergil** [comment]
Closing this one since we are not using this environment or recipe
