### ISSUE TITLE
Remove duplicated selectors from Sparta theme

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#4614]
![Screen Shot 2019-09-13 at 1 43 33 PM](https://user-images.githubusercontent.com/15113219/65061425-e6d2f080-d947-11e9-81fd-7af5e0113b43.png)

**Comment by developpeurweb** [comment]
**For QA:**

- Validate the code was moved.
- Validate payment-method, tab-paragraph-container and order-detail-totals remain visually unaffected.

**Comment by bgambocjaviniar** [comment]
QA results:
- code was moved
- all mentioned components in the corresponding pages aren't affected by the change
