### ISSUE TITLE
TM security improvements - ASM [best effort to fix before final release]

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4615]
https://github.tools.sap/cx-commerce/spasec/issues?q=is%3Aopen+is%3Aissue+label%3Aasm
5 issues as of Sept17 (token revocation separate issue)

Sec Verification (i.e. GC):
- (doc) https://github.tools.sap/cx-commerce/spasec/issues/7
ASM specific authentication (older ticket, created early Sept)
- [ ] https://github.tools.sap/cx-commerce/spasec/issues/24
Oathserver requests encryption
- (doc) https://github.tools.sap/cx-commerce/spasec/issues/28
Default credentials for ASM agent 

The following issues raised are handled in other tickets:
- https://github.tools.sap/cx-commerce/spasec/issues/27
URL validation ( centralized configurable endpoint feature, will be addressed by GH-4620 )
- https://github.tools.sap/cx-commerce/spasec/issues/26
Path traversal ( centralized configurable endpoint feature, will be addressed by GH-4619 )

**Comment by giancorderoortiz** [comment]
Rearranged order of priorities. Last 3 issues can be checked by me first. 

Items 26, 27 need dev work.

**Comment by giancorderoortiz** [comment]
ok
