### ISSUE TITLE
TM security improvements - Configurable Endpoints

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4619]
https://github.tools.sap/cx-commerce/spasec/issues?q=is%3Aissue+is%3Aopen+label%3Aconfigurable-endpoints
3 actionable issues as of Sept17

- [x] https://github.tools.sap/cx-commerce/spasec/issues/17
Code generation
- [ ] https://github.tools.sap/cx-commerce/spasec/issues/19
Input/URL validation

**Comment by giancorderoortiz** [comment]
Any updates?

**Comment by LTiger14** [comment]
Can be tested by reproducing these steps. https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5276

**Comment by LTiger14** [comment]
There is another page with a similar problem http://localhost:4300/apparel-uk-spa/en/GBP/product/74844_purple%2Bpink%2Bgoldenrad/The%20Zona%20Women%20purple%2Fpink%2Fgoldenrad

**Comment by LTiger14** [comment]
Passed full suite of tests: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/332/

**Comment by LTiger14** [comment]
Moved 18 to #7119

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/6347

**Comment by LTiger14** [comment]
For QA: go through the app electronics + apparel.

- Add product to cart
- Checkout (new user)
- Edit address
- Checkout again existing user
- Close account

**Comment by LTiger14** [comment]
Passed QA
