### ISSUE TITLE
TM security improvements - input validation

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4620]
https://github.tools.sap/cx-commerce/spasec/issues?q=is%3Aissue+is%3Aopen+label%3Ainput-validation
4 issues as of Sept17
- [ ] https://github.tools.sap/cx-commerce/spasec/issues/12
Solr/SQL/DB
- [x] https://github.tools.sap/cx-commerce/spasec/issues/13
XML
NOTE: This is documentation only. Talk to Matt about it first.
- [ ] https://github.tools.sap/cx-commerce/spasec/issues/14
URL validation
- [ ] https://github.tools.sap/cx-commerce/spasec/issues/15
Malicious Effect

**Comment by giancorderoortiz** [comment]
URL validation requires tests to be written.

**Comment by giancorderoortiz** [comment]
@Xymmer, @hackergil any bandwidth to fix this issue?

**Comment by wangzixi-diablo** [comment]
> URL validation requires tests to be written.

ok, I will list all use cases where special chars might be included in produce code first.

**Comment by giancorderoortiz** [comment]
Retest in https://github.com/SAP/spartacus/issues/9455

**Comment by wangzixi-diablo** [comment]
> Retest in #9455

Hello @giancorderoortiz ,

how about test result? 

Best Regards,
Jerry
