### ISSUE TITLE
[retest] Cart not found error displayed

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#4622]
### How to reproduce

1. Activate guest checkout
2. Add product to cart, go to checkout checkout as guest
3. Once on the shipping address page go to login and login
4. You can see the error

This also happens for other cases please experiment.

![Screen Shot 2019-09-17 at 4 29 17 PM](https://user-images.githubusercontent.com/10605724/65077204-843e1c80-d968-11e9-8a9a-8c3d4f903310.png)

**This does not affect how users can use the cart but it bad UX**

### Expected behavior

You should not see the error

**Note this is not a guest checkout exclusive issue**

**Comment by WeizhengSap** [comment]
I cannot reproduce this use case. But, add product to anonymous cart, then login, I can see the "Cart not found" error.

**Comment by Xymmer** [comment]
we set this one to hold but we found some kind of bug, do we fix or close? can we repro?

**Comment by LTiger14** [comment]
Was able to reproduce using the second set of steps. Updated ticket, still an issue.

**Comment by psmul** [comment]
I wasn't able to reproduce the provided steps in any configuration. Might need further investigation.

**Comment by Xymmer** [comment]
@KateChuen or @giancorderoortiz : can you re-verify this is no longer happening, or let me know if it is.

**Comment by KateChuen** [comment]
Tested on dev10 against 1905 backend. Was not able to reproduce it.
I followed the steps in the ticket.
Also logged in at every step of checkout. 
And did a few logins randomly. 
Did not see this error.
