### ISSUE TITLE
Mobile: MyAccount menu is not displayed if a page is clicked twice

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#4644]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://localhost:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Run a yarn
- Start your app
- Load the storefront on a mobile view
- Login
- Click on the hamburger menu, My Account, and any myaccount page, for eg, email address.
- Click on the hamburger menu again, my Account, and the same myaccount page.

**Actual Result**
Instead of MyAccount being displayed in the menu, it's now the myaccount page. which is weird... because if you want to go back to the MyAccount menu.... it gets confusing.

<img width="458" alt="Screen Shot 2019-09-18 at 2 17 49 PM" src="https://user-images.githubusercontent.com/45409515/65174919-d726db00-da1f-11e9-8309-5e1373a944a2.png">
<img width="438" alt="Screen Shot 2019-09-18 at 2 22 50 PM" src="https://user-images.githubusercontent.com/45409515/65174921-d7bf7180-da1f-11e9-8649-04f9b063a6d1.png">

**Comment by dydome** [comment]
@KateChuen it looks like problem was solved in the meantime. I check it on mac and chrome and everything looks fine.
