### ISSUE TITLE
Cannot remove coupon if the coupon code is ".."

### ISSUE THREAD

**Issue by KevinSu89** [SAP/spartacus#4724]
Cannot remove coupon if the coupon code is ".."

## Environment Details

- Spartacus: development environment
- Browser: Chrome  76.0.3809.132
- OS: macOS Mojave 10.14.6
- Device: macbook

## Steps to Reproduce
1. Create a coupon with code ".."
2. Apply this coupon to a cart
3. Remove this coupon from cart

## Observed Results
Cart is deleted

## Expected Results
The coupon is deleted

## Offer to Fix
NO.

## Additional Information
1. It seems that the browser treat ".." as super path. The url should be XXXX/cart/cartid/voucher/.., but the url which browser sent out is XXXX/cart/cartid
2. When testing this via Swagger UI, the cart will be deleted as well

**Comment by giancorderoortiz** [comment]
@KateChuen  Pending confirmation in internal dev-server.

**Comment by giancorderoortiz** [comment]
check path traversal vulnerability

**Comment by Xymmer** [comment]
let's verify this is still happening and attempt a fix
if spending more than half a day, talk to bill

**Comment by tobi-or-not-tobi** [comment]
Related to #4725 and #4726

**Comment by markywilson** [comment]
This issue is still happening and after deeper investigation, it seems that the issue has to do the request mapping in the endpoint. Spartacus makes the right API call with the right params but it gets handled incorrectly.

**Comment by tobi-or-not-tobi** [comment]
Dropping bug label as this is not a Spartacus bug, nor something we can fix in Spartacus. It's a backend bug. It's also a niche, and we shouldn't spend time here imho.

**Comment by tobi-or-not-tobi** [comment]
closing in favour of #4726
