### ISSUE TITLE
Cannot remove coupon if the coupon code contains "."

### ISSUE THREAD

**Issue by KevinSu89** [SAP/spartacus#4725]
Cannot remove coupon if the coupon code contains "."

## Environment Details

- Spartacus: development environment
- Browser: Chrome 76.0.3809.132
- OS: macOS Mojave 10.14.6
- Device: macbook

## Steps to Reproduce
1. Create a coupon which the code contains ".", e.g. abcd.efg
2. Apply this coupon to a cart
3. Remove this coupon from cart

## Observed Results
The remove request get "200" as return, but the coupon is not removed from the cart

## Expected Results
The remove request get "200" as return, and the coupon is removed from the cart

## Offer to Fix
NO.

## Additional Information
When testing this via Swagger UI, the coupon cannot be removed but receive "200" as well

**Comment by giancorderoortiz** [comment]
check path traversal vulnerability

**Comment by markywilson** [comment]
This issue is still happening and after deeper investigation, it seems that the issue has to do the request mapping in the endpoint. Spartacus makes the right API call with the right params but it gets handled incorrectly.

**Comment by tobi-or-not-tobi** [comment]
Dropping bug label as this is not a Spartacus bug, nor something we can fix in Spartacus. It's a backend bug. It's also a niche, and we shouldn't spend time here imho.

**Comment by tobi-or-not-tobi** [comment]
closing in favour of #4726
