### ISSUE TITLE
Refresher course on contribution/coding guidelines for Spartacus tribe

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#4790]
- [ ] breaking changes chapter (Bill to talk to Matt and Stan) - how to avoid it with deprecation (maybe we move this chapter to contributors guide: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/feature-flags-and-code-deprecation/#code-deprecation)

Once we have content updated, everyone re-read the docs and Bill will hold trivia contest after.

**Comment by Zeyber** [comment]
The new Public API change detection bot is leaving us with notes on our prs which is cool but its not really clear what it is checking for or how to deal with failures.
