### ISSUE TITLE
[HOLD]Separate B2b and b2c

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#4971]
Now, we add both `B2cStorefrontModule.withConfig` and `B2bStorefrontModule.withConfig` in `app.module.ts`. When we want to start b2c, we comment out the `B2bStorefrontModule`; and when start b2b, comment out `B2cStorefrontModule`.

We need a better way to separate the b2b and b2c applications.

**Comment by WeizhengSap** [comment]
This is from Tobias:
We'd like to approach this slightly different. We like to have a single build if possible, that is driven by a backend driven configuration. This should simplify e2e testing and development in general.

    add a channel configuration to the SiteContextConfig, which represents the basesite.channel form the backend
    we can start with a static configuration for now, but going forward we should load this from the basesite (similar to urlParameters)
    we like to keep a single layout configuration. if needed we can implement sample data changes to reflect the same layout config, or bring in alternative page templates if needed (but not preferred).
    we like to extend the new B2bStorefrontModule from the B2cStorefrontModule based on the idea that b2b contains the full b2c feature set plus some additional b2b specific features.
    we like the idea to clean up the appModule, but without the environment specific import. We could add the B2bStorefrontModule either way and ensure that the right end points / normalisation is done when we're in a b2b channel. Probably something we need to discuss going forward.

We hope to tackle the channel specific endpoint consumption in the lower layers of the app. Ideally in the adapters, but perhaps we need to investigate if that's doable.

Hope you can give it another tweak.

**Comment by Xymmer** [comment]
to sync up with Tobias and Nik about this and whether what's in develop is good for us or we have to do something else

**Comment by WeizhengSap** [comment]
I will close this ticket because the b2b fundamental config is in develop now.
