### ISSUE TITLE
Category page empty when no products

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#4973]
@Xymmer needs input what should be displayed in such case:
![image](https://user-images.githubusercontent.com/788092/66669096-0dd6c680-ec57-11e9-8e05-00119465d066.png)

**Comment by Xymmer** [comment]
Similar to when we search: No products found for category "xyz".

**Comment by vekterdude** [comment]
![m_search_landing_no_results](https://user-images.githubusercontent.com/44620139/101925628-13ec6e00-3ba0-11eb-8d8d-f54a68d9993c.png)
