### ISSUE TITLE
Anonymous consent breaking changes

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#4989]
Anonymous consents ticket: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/3800 
Search the code base for the following comment: `TODO(issue:4989) Anonymous consents`

**Comment by kacperknapik** [comment]
Breaking changes removed from `RegisterComponent` with #4237

**Comment by znikola** [comment]
Remove deprecated constructors in:
- `consent-management.component.ts`
- `footer-navigation.component.ts`

**Comment by znikola** [comment]
PR: https://github.com/SAP/spartacus/pull/7062
