### ISSUE TITLE
Breaking Changes since v1.3: Payment-method component clean up (#2291)

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#4992]
Migration payment method component to cleaner component in #2291.

**`payment-method.component.html`**

- changed conditional `existingPaymentMethods?.length && !newPaymentFormManuallyOpened` to `(existingPaymentMethods$ | async).length && !newPaymentFormManuallyOpened`

**`payment-method.component.ts`**

- refactor method call in line 128 `this.globalMessageService.add()` to separate method `this.sendPaymentMethodFailGlobalMessage(paymentInfo[key])`

- refactor card creation at lines 159-172 to separate method `this.createCard()`

- refactor method name `this.next()` to `this.goNext()`

- refactor method name `this.back()` to `this.goPrevious()`

- refactor method name `this.paymentMethodSelected()` to `this.selectPaymentMethod()`

**Comment by mirkosoft** [comment]
Closing this as deprecated code is already removed and documentation is up to date.
