### ISSUE TITLE
[multisite in dev mode] optimize e2e

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#5020]
See master ticket https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5019

If the performance becomes an issue, we can avoid the initial blocking OCC call for basesites in every e2e test. The approach could be:
- use hardcoded basesites for almost all e2e tests
- write a few e2e tests to verify mutli-site feature

There are various possible ways to hardcode the base sites for almost all e2e tests, i.e.:
- intercept the calls for base sites and return mocked response, see https://docs.cypress.io/api/commands/route.html#Syntax 
- on page load inject to DOM the trasferred config (pretend the solution used in SSR to transfer the config).

**Comment by Xymmer** [comment]
related to #9055

**Comment by Platonn** [comment]
closed in favour of refined https://github.com/SAP/spartacus/issues/5019
