### ISSUE TITLE
Consent management selections are clashing if logged in on different browsers [is this a use case?]

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5060]
**Environment Details**
Spartacus: epic/anonymous-consents branch
Browser: chrome
Device: mac
Happens on: http://dev-com-14.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/

**Steps to Reproduce**
- Login on Chrome, go to Consent Management page, reject all consents and stay on the consent management page.
- Login on firefox, go to Consent Management page, and accept one consent, and stay on the consent management page.
- Login on safari, and on consent management page, click on "Allow All". Only 2 are toggled on.

<img width="712" alt="Screen Shot 2019-10-17 at 11 59 43 AM" src="https://user-images.githubusercontent.com/45409515/67027841-49024b00-f0d8-11e9-8bb8-09239d38a494.png">

**Comment by Xymmer** [comment]
Evaluate if this is a valid use case we need to support. Fix if so, close with explanation if not.

**Comment by Xymmer** [comment]
Clicking allow all should enable all no matter what.
Same with disabling all.
Investigate if this is possible or if there are api issues.
If we can't fix, short term solution, remove the two *all links.
Talk to Bill if unsure.

**Comment by bgambocjaviniar** [comment]
moving to do because owner for the PR finished their internship,
**therefore**, anyone can pick up or create a new PR.

**Comment by giancorderoortiz** [comment]
I no longer see this error.  Consents toggled per sequence of events. 
Closing ticket.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2021-06-06 at 10 20 03 AM](https://user-images.githubusercontent.com/46171897/120928104-4b505900-c6b1-11eb-8395-215ba2b6bba5.png)
![Screen Shot 2021-06-06 at 10 20 12 AM](https://user-images.githubusercontent.com/46171897/120928105-4b505900-c6b1-11eb-9e5c-6a24465f7253.png)
![Screen Shot 2021-06-06 at 10 20 22 AM](https://user-images.githubusercontent.com/46171897/120928106-4b505900-c6b1-11eb-9d39-07b5e8ecce21.png)
