### ISSUE TITLE
API extractor fails from time to time

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#5084]
API extractor fails from time to time. Need to inspect the reason and fix it.

**Comment by Xymmer** [comment]
blocked because of legacy github

**Comment by marlass** [comment]
Happens from time to time
![image](https://user-images.githubusercontent.com/6259079/74235447-4b179780-4ccf-11ea-8cf2-465fda95060c.png)


Might be worth checking, but it is hard to reproduce.

**Comment by marlass** [comment]
It is no longer blocked

**Comment by marlass** [comment]
No longer an issue after bot rewrite
