### ISSUE TITLE
PDP reports error when clicking 'add to cart' and at the same time, the stock is changed to out of stock.

### ISSUE THREAD

**Issue by kate1zheng** [SAP/spartacus#5107]
## Environment Details

- Spartacus: 1.2
- Browser: Google Chrome Version 76.0.3809.132
- OS: MacOS jave version 10.14.6
- Device: laptop

## Steps to Reproduce
1. go to a PDP with some stocks, it shows 'add to cart' button (keep the page here)
2. go to backoffice, change the stock as out of stock
3. back to the PDP kept in step1, then click 'add to cart' button

## Observed Results
it reports error like below,  in this situation, end user should refresh whole page manually to recover
![image](https://user-images.githubusercontent.com/43032959/67271090-768e3080-f4ec-11e9-93a4-686b81e0953c.png)

## Expected Results
should we change the UI to out of stock??

**Comment by Xymmer** [comment]
more like an improvement than a bug. when you add to cart and we get such an error, we should recognize that it's out of stock and update the page likewise
