### ISSUE TITLE
SonarCloud issue review for 2.0

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5133]

**Comment by tobi-or-not-tobi** [comment]
We have a false-positive for the media `alt` attribute: https://sonarcloud.io/project/issues?id=sap_cloud-commerce-spartacus-storefront&open=AWpyfx8AyRjJygCrYORj&resolved=false&types=BUG

This is using dynamic attribute binding. I've logged a ticket at https://community.sonarsource.com/t/support-angular-dynamic-attribute-binding/17275.

**Comment by hackergil** [comment]
Also, code coverage for Spartacus is 44%. A couple of reasons for this:
* e2e tests are considered source, and they shouldn't
* the mock server does not have tests (and as far as I know it's dead code, we are not using it nor maintaining it)

**Comment by Xymmer** [comment]
bill to discuss with gil

**Comment by Xymmer** [comment]
https://sonarcloud.io/project/branches?id=sap_cloud-commerce-spartacus-storefront
