### ISSUE TITLE
Structured data without reviews produces errors

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#5153]
Using provided chrome plugin to validate schema's (https://chrome.google.com/webstore/detail/structured-data-testing-t/kfdjeigpgagildmolfanniafmplnplpl) I was able to produce errors for certain products.

Product without any reviews (product/1978440_md/DSC-H20_MD)
```
ratingValue	     (MISSING_FIELD_WITHOUT_TYPE)
ratingCount	   0  (NON_POSITIVE_FIELD)
reviewCount	   0  (NON_POSITIVE_FIELD)
```

**Comment by tobi-or-not-tobi** [comment]
QA
- open product without reviews
- confirm that the structured data does not contain the product review schema

**Comment by giancorderoortiz** [comment]
Test successful 
![Screen Shot 2020-11-02 at 9 50 44 AM](https://user-images.githubusercontent.com/46171897/97881864-eedb2480-1cf0-11eb-9417-21d68afb7290.png)
![Screen Shot 2020-11-02 at 9 50 53 AM](https://user-images.githubusercontent.com/46171897/97881866-eedb2480-1cf0-11eb-9b35-2720755d6969.png)
