### ISSUE TITLE
Create generic visuals that represent components not specific features

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5173]

**Comment by Manurod2018** [comment]
Can you elaborate? Not sure I understand.
Are you referring to the Guideline? https://app.zeplin.io/project/5a836f2897c4a02f0105b093/screen/5a836ffc6fcdb14071daefda
There you can see some examples of components like basic forms elements, table, cards and modals for alerts. We will add more to the UX guidelines that Jose is building.
