### ISSUE TITLE
Improve look of buttons e.g. seem to wide

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5174]

**Comment by Manurod2018** [comment]
The width of the buttons is currently aligned with the grid. When there is a form field, the button is also set to 100% width so it looks in alignment with the rest of the content and the layout feels more balanced. Then the rule is that when there are 2 buttons, the two share the same width. 
A lot of websites and Web Apps have a full-width design when you look at them on an ipad. 
Attached are some screens with the current implementation and some examples with smaller buttons. 
Which one is better? I guess it's a personal taste.
I am ok having them smaller and left align, as long as we have a rule defining the width for each inflection point. 

![Tablet - PDP – 1](https://user-images.githubusercontent.com/37299626/68778703-85ef2e00-0601-11ea-8290-89b923e5b6e1.png)
![Tablet - PDP – 2](https://user-images.githubusercontent.com/37299626/68778704-8687c480-0601-11ea-9290-d9b769e4ebb5.png)
![Web 1920 – Reset Password](https://user-images.githubusercontent.com/37299626/68778706-8687c480-0601-11ea-88a7-090c0bec746c.png)
![Web 1920 – Sign In – 1](https://user-images.githubusercontent.com/37299626/68778708-8687c480-0601-11ea-9193-9c615529c938.png)
![Web 1920 – Sign In – 2](https://user-images.githubusercontent.com/37299626/68778709-8687c480-0601-11ea-8125-1275a5efdf1e.png)

**Comment by Xymmer** [comment]
I guess my point is, is that once a button is a certain width, it's easy to find/tap/click. For mobile there is some kind of pattern where buttons reach across the screen but that's probably because we're assuming somone is holding their phone and trying to press with one hand. Otherwise it seems like for every other viewport, the buttons are absurdly wide.

I would generallylike to see them all tightened up, which would also allow more buttons on one line.
For example, instead of defining a big width, we define the minimum padding of 10px or whatever.

e.g.
![image](https://user-images.githubusercontent.com/4998145/68952909-bd3f1580-078e-11ea-9a5f-c3f318171410.png)
