### ISSUE TITLE
Review of how we tag links and buttons

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5176]
Miguel mentioned that the same links are tagged differently e.g. action links. The main problem is our no-breaking-change rule: that we can't easily make style changes when we notice something or want to change something. I want to understand the issues and make a list for 2.0 release so we can streamline and provide an improved styling system for customers.

**Comment by developpeurweb** [comment]
This is related to this other ticket GH-4340

**Comment by developpeurweb** [comment]
Changes to be done according to the **Action Links Standardization Guide**
https://cxwiki.sap.com/display/spar/Action+Links+Standardization

**Comment by Xymmer** [comment]
let's go with underline, not bold, no upper case (sentence caes preferred) for now

**Comment by kacperknapik** [comment]
@developpeurweb Please update the status of this ticket. A quick comment below is enough.

**Comment by developpeurweb** [comment]
@kacperknapik this ticket is currently waiting for tests to pass so it can be merged.

**Comment by developpeurweb** [comment]
**For QA:**
All `cx-action-link` accounted for on this page: https://cxwiki.sap.com/display/spar/Action+Links+Standardization should be style uniformly.
Note: "Sentence case" does not exist in CSS so we used _Capitalized Case_ instead.

**Comment by LTiger14** [comment]
QA notes: All the actions links are styled in the same way
