### ISSUE TITLE
e2e tests failing in nightly builds 

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5219]
These tests have been failing in jenkins in the nightly builds because of the anonymous consents dialog:

- regression/store-finder.e2e-spec.ts
because, now there's the cookies button "View Details" which is interfering with the "Back to List" button. And it's supposed to click on the latter, but couldn't find it. Need to fix the test to find and click on this button. 

- regression/checkout/checkout-as-guest.e2e-spec.ts
on the checkout shipping method step, it's not seeing the 'Continue" button because of the anonymous section showing up. 

- 

Logs here:
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/507/consoleFull

**Comment by qjimmy** [comment]
Already closed by GH-5029

**Comment by marlass** [comment]
Closing in favor of more specific issues.
