### ISSUE TITLE
[update sample data] Check accelerator collections url to reapply in SPA

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#5237]
Apparel UK accelerator store has urls for "collections", eg. `/yacceleratorstorefront/en/Collections/Streetwear/c/streetwear`:
![image](https://user-images.githubusercontent.com/788092/67946009-9bfff600-fbe0-11e9-8c1a-5830fe1dafae.png)

@Xymmer to investigate on this one. Takeouts from the meeting:
- do not follow the `/Brands` way (don't hardcode that route anywhere in the front app); probably better to make content/landing page
- `/Collections` or `/Brands` are regular categories, however they contain other categories (subcategories) instead of products

**Comment by Xymmer** [comment]
we agreed that this blocks 1.5 FF until we know for sure what work is needed, for routing refactoring, if any. Change milestone to 1.5.0 if not.

**Comment by mirkosoft** [comment]
Broken links in the menu (apart of brands #6242):
- "all streetwear"
- accelerator filtered queries (with `?q=topRated` for example):
  - men's belts (streetwear)
  - all youth sublinks

**Comment by mirkosoft** [comment]
For the last pending issue (facet links like `?q=topRated` in the above comment) routing bug founded must be fixed first: #6368 
As a temporary solution (just the "YOUTH" navigation node sublinks are affected) we can either remove YOUTH from the navigation or change it's sublinks to something without facet filters included as query params).

**Comment by mirkosoft** [comment]
As agreed, let's modify the below links temporarily:
```
/Collections/Streetwear/c/streetwear%3Fq%3D:topRated:category:251100
/Categories/Streetwear-youth/Boardshorts-youth/c/270600%3Fq%3D:relevance:brand:Billabong
/Categories/Streetwear-youth/Boardshorts-youth/c/270600%3Fq%3D:relevance:brand:69%2BSlam
/Categories/Streetwear-youth/Boardshorts-youth/c/270600%3Fq%3D:relevance:brand:Quiksilver
/Categories/Streetwear-youth/Boardshorts-youth/c/270600%3Fq%3D:relevance:brand:Volcom
/Categories/Streetwear-youth/T-Shirts-youth/c/270100%3Fq%3D:relevance:brand:Billabong
/Categories/Streetwear-youth/T-Shirts-youth/c/270100%3Fq%3D:relevance:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100%3Fq%3D:relevance:brand:Burton
/Categories/Streetwear-youth/T-Shirts-youth/c/270100%3Fq%3D:relevance:brand:DC
/Categories/Streetwear-youth/T-Shirts-youth/c/270100%3Fq%3D:relevance:brand:Quiksilver
```
to:
```
/Collections/Streetwear/c/251100
/Categories/Streetwear-youth/Boardshorts-youth/c/270600
/Categories/Streetwear-youth/Boardshorts-youth/c/270600
/Categories/Streetwear-youth/Boardshorts-youth/c/270600
/Categories/Streetwear-youth/Boardshorts-youth/c/270600
/Categories/Streetwear-youth/T-Shirts-youth/c/270100
/Categories/Streetwear-youth/T-Shirts-youth/c/270100
/Categories/Streetwear-youth/T-Shirts-youth/c/270100
/Categories/Streetwear-youth/T-Shirts-youth/c/270100
/Categories/Streetwear-youth/T-Shirts-youth/c/270100
```

After fixing #6368 let's change those links finally to a form acceteptable by spartacus:
```
/Collections/Streetwear/c/251100?sortCode=topRated
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?sortCode=relevance
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Billabong
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:69%2BSlam
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Quiksilver
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Volcom
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Billabong
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Burton
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:DC
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Quiksilver
```

**Comment by mirkosoft** [comment]
sampledata PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/70

**Comment by KateChuen** [comment]
The url is different from what's mentioned in the ticket. I'm getting this for eg: But at least the categories are being displayed, with sorting and facets too.

category/270600?sortCode=relevance
category/270600?sortCode=relevance&query=:relevance:category:270600:brand:Billabong

**Comment by giancorderoortiz** [comment]
Streetwear categories urls: 
1. Men - Bags - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/160700
2. Belts - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/Collections/Streetwear/c/251100
3. Shorts - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/250600
4. T-shirt men - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/250100
5. Bags - Women - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/160400
6. Pants Women - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/260900
7. T-shirt Women - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/260100
8. Tops - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/261800
9. Skirts and Dresses - http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/260700
10. Boardshorts youth http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/270600
11. T-shirt youth http://dev-com-12.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/270100

**Comment by giancorderoortiz** [comment]
qa accepted

**Comment by Xymmer** [comment]
ping Miro if any questions

**Comment by mirkosoft** [comment]
Change links affected in this PR:
https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/70/files

as below:
```
/Collections/Streetwear/c/251100?sortCode=topRated
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?sortCode=relevance
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Billabong
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:69%2BSlam
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Quiksilver
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Volcom
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Billabong
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Burton
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:DC
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Quiksilver
```
accordingly.

**Comment by Xymmer** [comment]
Since https://github.com/SAP/spartacus/issues/6368 is fixed now, the goal is to put the the URLs back to normal in the sample data.
This issue is marked 2.1, but let's release sample data updated with next patch

**Comment by mirkosoft** [comment]
QA steps:
1. as a backend use latest `release/1905/next` branch (reinitialize on the server or local, no matter)
2. on the front go to apparel-uk-spa base site and check whether all links in the top menu works as expected; in particular check below links are the same and work fine:
/Collections/Streetwear/c/251100?sortCode=topRated
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Billabong
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:69%2BSlam
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Quiksilver
/Categories/Streetwear-youth/Boardshorts-youth/c/270600?query=:relevance:category:270600:brand:Volcom
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Billabong
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Blue%2BTomato
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Burton
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:DC
/Categories/Streetwear-youth/T-Shirts-youth/c/270100?query=:relevance:category:270100:brand:Quiksilver

**Comment by KateChuen** [comment]
Tested on dev10. 
The links above work fine. 

Found a few issues. Let me know if they will be fixed in this ticket, or you want new tickets for them:
↪️ Opened ticket https://github.com/SAP/spartacus/issues/8132 for these issues.

1. Go to Brands -> Billabong. Then go Brands -> Blue Tomato. The applied filter still says "Billabong".
<img width="1065" alt="Screen Shot 2020-07-03 at 10 29 20 AM" src="https://user-images.githubusercontent.com/45409515/86478345-21abe680-bd18-11ea-9208-e355db0c144b.png">

2. Go to Youth -> Tshirts. Then go to Snow -> Shop all snow. You'll see the header of the previous page is still displayed.
<img width="1063" alt="Screen Shot 2020-07-03 at 10 17 17 AM" src="https://user-images.githubusercontent.com/45409515/86478185-e3162c00-bd17-11ea-8828-f0125f1e1849.png">

3. Missing the applied filter for the categories under Youth. For eg, Youth -> Tshirts -> Billabong. Should display applied filter "Billabong".
<img width="1064" alt="Screen Shot 2020-07-03 at 10 32 30 AM" src="https://user-images.githubusercontent.com/45409515/86478677-9e3ec500-bd18-11ea-9950-4ff05c52efa1.png">
