### ISSUE TITLE
Display 'Estimated Delivery Date' generally, and, in BOPIS feature, specifically.

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#5246]
Improvement, not a bug (BOPIS related)

"21 available for delivery" "Get it delivered by: < Month DD, YYYY >"

In Accelerator, the system was not able to determine what the estimated delivery date of an item was/is.
As time has passed, this is becoming information that both customers and user expect to see.

This ticket is primarily intended to begin the process of developing this feature improvement. If it requires a spike then so be it. If it is a simple API integration let's go for it etc...

Some connection (API) to shipping companies may be necessary. Please investigate.

**Comment by Xymmer** [comment]
i'll have someone look into the backend to see if this info is available

**Comment by Xymmer** [comment]
closing until the backend can provide this info
it's been added to bill's wishlist of features that require api's
