### ISSUE TITLE
Investigate (Spike) what is needed to build an Account Homepage

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#5247]
Connected to Ticket: [Spike] Account Home Page #1582

There is a UX request to have an account homepage to alleviate what is an awkward experience in the mobile menu.

Our verticals are developing numerous new account areas for themselves and need to start designing their tiles, sourcing their logos, and writing copy to describe the area to users etc...

Some of the vertical lists are rapidly getting long to the point of being out of hand.

Different versions of this homepage will exist in different verticals or b2b/b2c options.

I would like to get to the point where this story can be done quickly in an emergency escalation (without having to wait a year to avoid a breaking change), then leave the priority of 'when' to build the feature up to the PO.

Please investigate this issue and "report back" so we can make a decision and move forward.

**Comment by Xymmer** [comment]
was done
