### ISSUE TITLE
Styling Improvements to Coupons / Promotions In Cart & Checkout

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#5252]
Address styling issues listed in https://wiki.hybris.com/display/spar/Promotions+Update+Feb+2019%3A+Potential+Promotions+and+Update+to+Applied+Promotions+in+Spartacus

Some improvement ideas: 
1. In cart, It should be clear how much money was saved because of a coupon/promotion.  Improve alignment, justification.  This also applies to checkout journey, confirmation page and order details page. 
2. In cart & checkout journey, handle styling when having more than 1 coupon. 
3. When several promotions apply, there should be spacing between their description so that it's easier to understand. 
4. Properly handle coupons with large names (i.e. GIVEAWAY16-MMZ6-3CCK-EDMM-1C5D).

**Comment by giancorderoortiz** [comment]
Guest Checkout Order Confirmation:
![Screen Shot 2019-11-01 at 9 27 47 AM](https://user-images.githubusercontent.com/46171897/68027975-1f295680-fc8a-11e9-9ae4-97921b9d81e4.png)

**Comment by giancorderoortiz** [comment]
Guest Checkout Cart: 

![Screen Shot 2019-11-01 at 9 29 19 AM](https://user-images.githubusercontent.com/46171897/68028008-30726300-fc8a-11e9-9dd5-6491655c1a9b.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2019-11-01 at 9 31 00 AM](https://user-images.githubusercontent.com/46171897/68028111-61529800-fc8a-11e9-9458-f2d681a7219c.png)

**Comment by giancorderoortiz** [comment]
With 2.0rc4, It's perceived that layout and spacing for coupons/promotions is better in order- details page using old accelerator. It's easier to understand. 
In old accelerator, applied promotions and coupons are grouped in one single place, and they also have a section title. With Spartacus, it feels this info is all over the place. 

**This is with Spartacus:** 
![Screen Shot 2020-06-02 at 6 11 52 AM](https://user-images.githubusercontent.com/46171897/83508700-4d794980-a498-11ea-976c-4bb0a2732b52.png)
![Screen Shot 2020-06-02 at 6 12 03 AM](https://user-images.githubusercontent.com/46171897/83508719-536f2a80-a498-11ea-9078-a33c3642a45b.png)

**This is with Electronics:** 
![Screen Shot 2020-06-02 at 6 12 36 AM](https://user-images.githubusercontent.com/46171897/83508739-5bc76580-a498-11ea-9d0a-b115561e0abb.png)

**Comment by developpeurweb** [comment]
**Agreed:** It doesn't seem to match mockups.

![Screen Shot 2020-06-02 at 9 40 12 AM](https://user-images.githubusercontent.com/15113219/83527132-5fb5b080-a4b5-11ea-98cb-de36ae0d994b.png)
