### ISSUE TITLE
[On Hold #4619] PDP Handling of the "+" signs in the request url

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#5276]
Go to product with style variants whose url contains "+":
http://localhost:4200/apparel-uk-spa/en/GBP/product/95385_cardinal
and click that variant (stout white/true black):
![image](https://user-images.githubusercontent.com/788092/68203393-f83e8d80-ffc5-11e9-872f-81b7afe182b8.png)

You got 404 because the `/page` call get `code` param with `+` sign which is being url encoded into space: 
![image](https://user-images.githubusercontent.com/788092/68203627-7dc23d80-ffc6-11e9-877f-3991491952f7.png)

related to #4260

**Comment by KateChuen** [comment]
This could be fixed by ticket https://github.tools.sap/cx-commerce/spasec/issues/19

**Comment by LTiger14** [comment]
There is another issue with a similar problem http://localhost:4300/apparel-uk-spa/en/GBP/product/74844_purple%2Bpink%2Bgoldenrad/The%20Zona%20Women%20purple%2Fpink%2Fgoldenrad

**Comment by LTiger14** [comment]
Fixed in https://github.com/SAP/spartacus/pull/6347
