### ISSUE TITLE
Missing visual indication on focus on asm search results

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5286]
**Environment Details**
Spartacus: develop branch
Browser: Safari
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Login as an agent (asagent/123456)
- Start typing a customer's email address to get a search result
- Hover over one of the search results

**Actual Result**
There's barely any visual indication where the focus is. 
<img width="1052" alt="Screen Shot 2019-11-05 at 2 11 07 PM" src="https://user-images.githubusercontent.com/45409515/68238238-c3870200-ffd6-11e9-9066-7c1a588a9dfc.png">

**Expected Result**
Need it to be more obvious to the user.

**Comment by morganm58** [comment]
the username and password isn't working for me. So I can't login to check it out

**Comment by developpeurweb** [comment]
Fixed and now looks like this:

![Screen Shot 2020-04-15 at 5 49 18 PM](https://user-images.githubusercontent.com/15113219/79392565-8d648b80-7f41-11ea-9b10-e28f58d3c888.png)

**Comment by bgambocjaviniar** [comment]
works, hover now has a darker color than the lighter version before
