### ISSUE TITLE
Remove switches (checkboxes standard on/off for now)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5325]
In the visuals reference, let's remove the on/off switches, standardizing on checkboxes. They look weird in desktop, and already I see issues with having a word in the button for localization.

I can understand why we'd want to do it in mobile, as they seem to be used more there, but from my understanding of this ui, it's more for turning features on/off (a coffee pot being an example) and maybe or preferences. ButI don't see a strong use case for anything in our storefront.

![image](https://user-images.githubusercontent.com/4998145/68391959-b123da00-0136-11ea-8bfd-067261492b75.png)

**Comment by Manurod2018** [comment]
Using the right control at the right place is important. 
Toggles and checkboxes have similar functions but for different contexts, so it's always better to rely on standards and best practices.

A toggle switch represents a physical switch that allows users to turn things on or off, like a light switch. They are used for instantaneous actions and provide immediate results. 

A checkbox does not apply the settings at an instant like a switch. It requires a submit button and takes effect only after the user commits. 

Here it's clearly an on/off type of decision.
We can remove the labels ON and OFF next to the toggle as the design is clear enough and doesn't rely solely on color but uses high-contrast to signal state change.

![Consent – Modal – M](https://user-images.githubusercontent.com/37299626/68780757-bbe1e180-0604-11ea-803c-23304f44cf24.png)
![Consent – Modal – T](https://user-images.githubusercontent.com/37299626/68780758-bc7a7800-0604-11ea-86d8-568759cc9648.png)
![Consent – Page – D](https://user-images.githubusercontent.com/37299626/68780759-bc7a7800-0604-11ea-8ac7-f70c616165a8.png)
![Consent – Page – M](https://user-images.githubusercontent.com/37299626/68780761-bc7a7800-0604-11ea-8702-a790faf40a20.png)




![Consent – Modal – D](https://user-images.githubusercontent.com/37299626/68780756-bbe1e180-0604-11ea-9106-cbeeee5811f3.png)

**Comment by Xymmer** [comment]
I'm trying to reduce investment and maintenance costs and this is one area I wish I had learned of sooner. Using the right control in the right is admirable but when there are alternatives, I choose simplicity and less implementation cost. I don't know of anything in Spartacus that can't use a checkbox, and I'm starting to see people misuse this control. Let's proceed with the change please.
