### ISSUE TITLE
Styling issues with the asm ui expand collapse arrow

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5335]
**Environment Details**
Spartacus: develop branch
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Styling Issues**
- On mobile viewport, you can see the _expand/collapse arrow_ is on top of the list. It should be hidden behind the list. 
![Screen Shot 2019-11-07 at 1 53 57 PM](https://user-images.githubusercontent.com/45409515/68419379-1d6b0180-0168-11ea-8df2-1e42a9ea2cc1.png)

- On tablet viewport, you can see the _expand/collapse arrow_ is overlaid on the _Search input field_. 
![Screen Shot 2019-11-07 at 1 55 00 PM](https://user-images.githubusercontent.com/45409515/68419484-4f7c6380-0168-11ea-94ee-9f1fafc1c7a5.png)

![Screen Shot 2019-11-07 at 1 55 07 PM](https://user-images.githubusercontent.com/45409515/68419732-d2052300-0168-11ea-80df-c71944310bd1.png)

- On firefox, you can see the _expand/collapse arrow_ isn't quite aligned within its box. 
<img width="1436" alt="Screen Shot 2019-11-07 at 1 56 03 PM" src="https://user-images.githubusercontent.com/45409515/68419572-7dfa3e80-0168-11ea-86db-54780bf8d8b4.png">

<img width="590" alt="Screen Shot 2019-11-07 at 2 13 18 PM" src="https://user-images.githubusercontent.com/45409515/68419709-c580ca80-0168-11ea-9b24-0450e680a3bb.png">

**Comment by Xymmer** [comment]
For the toggle button overlapping, let's add a static horizontal bar to avoid all the overlapping unpleasantness. it's impossible to know how partners will change this, it will cause a lot of headaches.

example
![image](https://user-images.githubusercontent.com/4998145/68482427-953c3900-0207-11ea-9112-1c9b6d231118.png)

**Comment by tobi-or-not-tobi** [comment]
I'd simplify the UI and get rid of the arrow icon. If we just keep the ASM top-bar (the dark blue one) at all times, and add a collapse icon next to the close button, it's a straightforward UI. The ASM navigation will always be available and doesn't interfere with the storefront UI (and thus there shouldn't be a need to customize this part).

**Comment by qjimmy** [comment]
I noticed that in order to place the minimize button behind the list, just set the `z-index` to 10 for the _expand-ui-btn_ class in the **asm.scss** file.

**Comment by tobi-or-not-tobi** [comment]
@qjimmy sure, easy to fix but generally speaking not a great UI if you ask me.

**Comment by Xymmer** [comment]
Let's fix as Tobias suggest, but do a mock and show me so i understand it :) I think it's somewhat similar to the examples i posted

**Comment by bgambocjaviniar** [comment]
PR: GH-7544 (MERGED)

release PR: GH-7564 (MERGED)

**Comment by bgambocjaviniar** [comment]
QA steps:

- enable asm
1) click the hide asm, which hides the body content below the navbar of asm
2) click the show asm, which displays the body content below the navbar of asm

rinse and repeat for when the agent is in the login form, customer-selection, and emulation on chrome, safari, and firefox

**Comment by giancorderoortiz** [comment]
Test successful. 
Server: http://dev-com-8.accdemo.b2c.ydev.hybris.com:4200/
Hide/show asm arrow behaves as expected. 

![Screen Shot 2020-05-22 at 7 47 34 AM](https://user-images.githubusercontent.com/46171897/82664965-d5419700-9c00-11ea-8c15-1ffb1b3b3ce3.png)
![Screen Shot 2020-05-22 at 7 47 43 AM](https://user-images.githubusercontent.com/46171897/82664966-d5da2d80-9c00-11ea-8c69-3496700acb46.png)
![Screen Shot 2020-05-22 at 7 48 22 AM](https://user-images.githubusercontent.com/46171897/82664967-d672c400-9c00-11ea-992b-5888dc353e9a.png)
