### ISSUE TITLE
Create an example of a banner with a text overlay using RotatingImagesComponent (CMS)

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#5354]
RotatingImagesComponent is a container component that can hold various components.

This component supports an overlay for a text on top of the banner as it the various banner components, therefore, it has headline and a content that can be used as text.

Provide one example in Spartacus for a text overlay

**Comment by tobi-or-not-tobi** [comment]
@bgambocjaviniar we have already an impex for this, it's just a matter of finding a place to import . commit the impex.

**Comment by Xymmer** [comment]
Saad is doing this and will document
