### ISSUE TITLE
[HOLD] Update Typescript (3.5 -> 3.7) when Angular supports it

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#5363]
Typescript version 3.7 has been released.
It adds 2 useful features:
- Optional chaining operator
- Nullish Coalescing

More: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html

Let's update that package and obsolete code in the project.

**Comment by tobi-or-not-tobi** [comment]
we're depending on a couple of things here:
- angular doesn't yet support it (unless you set the `disableTypeScriptVersionCheck` in tsconfig)
- ts/es linters aren't ready yet, so you have a bad experience in IDE
- prettier stable 3.0 is required as well

But, totally agree, as soon as those dependencies are in place, we should use it!

**Comment by Pucek9** [comment]
@tobi-or-not-tobi 

Not really, I tested it in this stack and it's working as well! :)
"typescript": "^3.7.2", ✔
"prettier": "^1.19.1", ✔
"tslint": "^5.20.1", ✔

Webstorm 2019.2 (stable) ✔
VSCode 1.41.0-insider ✔

So one probable blocker is Angular and stable vs-code
"angular": "~8.2.5", ❔ (not verified yet)
VSCode 1.40.0 (stable) ❌

**Comment by Xymmer** [comment]
if we're agreeing to update, let's do it after 1.3.0 is out to be safe.
also is this something that ca be done in a patch fix, it has no effect compatibility-wise?

**Comment by Pucek9** [comment]
Update
In VSCode 1.40.1 (stable) ✔ it enough to select typescript version from the workspace
"angular": "~8.2.5" ❌
```ERROR: The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.7.2 was found instead.
An unhandled exception occurred: The Angular Compiler requires TypeScript >=3.4.0 and <3.6.0 but 3.7.2 was found instead.

**Comment by trusktr** [comment]
Regarding the all-too-common "has or is using private name" error, I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822

**Comment by Xymmer** [comment]
we're up to 3.8.3 for 2.0.
