### ISSUE TITLE
[on hold because of carousel refactor][Android] Banner component not changing images on mobile devices

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#5395]
Banner component not changing its image on smaller screens ie different devices, especially **Android** devices? The image always stays the same, no matter what other images you have defined in **impex file**. 
This is replicable on https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/ as well.

**Original source:** 
https://stackoverflow.com/questions/58707944/banner-component-not-changing-images-on-mobile-devices

_No screenshots provided_

**Comment by developpeurweb** [comment]
This doesn't seem like a CSS issue at first glance since the banner image, whichever, is set to take 100% of the width throughout all media queries.

This seems more an issue of a **specific size image(s) not being "swapped" at the expected breaking point(s)** but to those breaking points set in the _layout-config_ file or related TS files.

![Screen Shot 2019-11-13 at 1 14 37 PM](https://user-images.githubusercontent.com/15113219/68792091-aeceed80-0618-11ea-93cb-ff563d1c5feb.png)
 

This might be related to this other issue GH-5398

**Comment by KateChuen** [comment]
When you take this ticket, please also work on ticket #5398

**Comment by kacperknapik** [comment]
as Tobi mentioned in the title, this ticket/fix is on hold, since we plan on changing the whole carousel implementation

**Comment by tobi-or-not-tobi** [comment]
QA: 
- test as part of #7229 with an android phone

**Comment by kacperknapik** [comment]
QA'd with #7229
