### ISSUE TITLE
[Spike needed] Banner slots for extra small devices and breaking points not in sync with each other

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#5398]
**Original source:**
https://app.slack.com/client/TCT7GM9LL/CD16V16FR/thread/CD16V16FR-1571829130.137000

Spartacus seems to use its own breakpoints which are valued in the breakpoint.service as follows:
const DEFAULT_BREAKPOINTS = {
 [BREAKPOINT.xs]: 576,
 [BREAKPOINT.sm]: 768,
 [BREAKPOINT.md]: 992,
 [BREAKPOINT.lg]: 1200,
};
These breakpoints however are mixed between spartacus components.
For example:
Header slots have min-width: 992 and after that they are MD.
Media has max-width: 992 and after that they're LG.
To my understanding slots use the breakpoints as min-width and medias use it as max-width.
Is this a mistake in Spartacus and if not, is there a simple way to unify the breakpoint rules?
(also Bootstrap 4 uses different breakpoints for devices than Bootstrap 3, might there be some mixup of these or are they set one device width behind on purpose?
https://getbootstrap.com/docs/4.0/layout/overview/)

-----------

When we go belowdevice width:1055, spartacus uses slots for Extra small Devices (xs).
however spartacus also uses the same Device Width for Small (sm) images. So never are they in sync with each other.
[BREAKPOINT.md]: 1055= XS on header slots
[BREAKPOINT.md]: 1055= SM on Medias
I've attached a picture to visualize the issue.

![B460A461](https://user-images.githubusercontent.com/15113219/68786168-52b29c00-060d-11ea-8127-f4d1c06b275e.PNG)

-----------

In the last example we had overwriten the standard breakpoints, but the issue still applies.
I can try to break this down more if needed and sorry for being so persistent about this.
In as simply as I can put it:
In hybrises media container we put 4 different sized pictures for all 4 device widths (xs, sm, md, lg).
With spartacus it is impossible to get the xs picture to show.

**Comment by developpeurweb** [comment]
This doesn't seem like a CSS issue at first glance since the banner image, whichever, is set to take 100% of the width throughout all media queries.

This seems more an issue of a **specific size image(s) not being "swapped" at the expected breaking point(s)** but to those breaking points set in the _layout-config_ file or related TS files (as per screenshot).

This might be related to this other issue GH-5395

**Comment by KateChuen** [comment]
Work with Miguel to investigate.

**Comment by tobi-or-not-tobi** [comment]
QA:
- see #7229

**Comment by KateChuen** [comment]
Tested through #7229.
