### ISSUE TITLE
[Wait for new API] Use new save cart API to create wish list

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#5411]
In #5227, the logic to create a wish list was implemented using the "save a cart" API. The only way to create a wish list was to create a new empty cart and then save it.

With the new API this is a one step process. This ticket is to convert the logic in the `createWishList$` effect to use this new API. It should still specify the cart's name and description. As for now (single wishlist) **the wishlist's name should be `wishlist`**. A check will be previously made to make sure a wish list with that name does not already exist.

Also figure out a mechanism for the cases when the new API is not there (older versions).

**Comment by Xymmer** [comment]
won't do as the api wasn't updated
