### ISSUE TITLE
Quick Order UX - evaluate if old ui is ok

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5418]
Quick Order was designed when we had UX people. Current UX seems to be ok. Can we agree that we'll reuse current UX?
See https://wiki.hybris.com/display/spar/Feature%3A+B2B+Quick+Order

**Comment by vekterdude** [comment]
Old UI is not super OK, but I believe the API's are probably totally 100% sound for these small revisions.

Some of the issues that make the UI non-reusable are that we are using different components this time around. These wires demonstrate the components used elsewhere in the SPA project and should aid front end devs.

We also want to have at least SOME chance that the UI is usable in B2C scenario, and elements of the UI from previous product are not well suited to that goal. (Like the discoverability of the 'tab' key etc...)

We also MUST have a confirmation (of 'clear form' action) to meet a11y and heuristics principle requirements. (if we have a 'clear form' button)

Here is the (only slightly) revised proposal for quick order:
Mobile: https://djjr4w.axshare.com/#id=n9762q&p=m_quick_order&g=1 

Tablet: https://djjr4w.axshare.com/#id=cbwblj&p=t_quick_order&g=1

Desktop: https://djjr4w.axshare.com/#id=cbwblj&p=t_quick_order&g=1

Cheers!

**Comment by Xymmer** [comment]
duplicate as we have a newer ticket
