### ISSUE TITLE
[Blocked] Update CCv2 to install backend from CEP

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#5448]
Per Frank's suggestion. Update the manifest to install the latest 1905 with the latest Cloud Extension Pack

https://wiki.hybris.com/display/jointrd/1905+Cloud+Extension+Pack

- [x] Update Spartacus recipe
- [x] Fix problem with wro4j
- [ ] Deploy in both CCv2 instances

**Comment by hackergil** [comment]
Wro4j problem is fixed on the latest 2005 snapshot.
This ticket is blocked until we can get someone to fix d4

**Comment by Xymmer** [comment]
we've updated 1905 and 2005 manifests to work with spartacus and ccv2, closing
