### ISSUE TITLE
Proposal for variants configuration options

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#5466]
Aim of this ticket is to decide what (if any) of the variants related logic/behaviour should be configurable at some level.
Below listed are some thoughts:
- robots.txt are set to NOINDEX for the non purchasable products (ie. base product); business may need this behave in a different manner (set to `INDEX` or `rel="canonical"`, etc)
- redirection from the non purchasable product is performed (this is not server handled 301 - just the angular route change in guard). This also might depend on business I believe (to do or not do such redirects, or do them just for some products)
- customization for component's templates
- some customizations during SSR like adding 301 redirect (from non purchasable products)

**Comment by Xymmer** [comment]
Let's decide what to do in the future based on feedback
