### ISSUE TITLE
ASM: the customer session message is aligned to the left

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5473]
**Environment Details**
Spartacus: develop
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- Sign In with asagent/123456 in the asm section
- Sign in as a customer through the login form

**Actual Result**
The message "Standard customer session in progress" used to be centered. Now it's aligned to the left.

<img width="980" alt="Screen Shot 2019-11-19 at 10 58 35 AM" src="https://user-images.githubusercontent.com/45409515/69166043-98191280-0ac0-11ea-9296-77fba1bf6b88.png">

Miguel says: 
" the container is half the width it used to be"

![Screen Shot 2019-11-19 at 11 17 38 AM](https://user-images.githubusercontent.com/45409515/69166089-a830f200-0ac0-11ea-98df-216521b6141e.png)

**Comment by Xymmer** [comment]
unless we find this blocked functionality, not urgent to fix. setting to p3

**Comment by Xymmer** [comment]
it's ok, let's leave it
