### ISSUE TITLE
anonymous consent e2e spec not stable

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#5482]
_moving from anonymous user to registered user_ part is failing. Test sometimes fails and sometime passes. 

_projects/storefrontapp-e2e-cypress/cypress/regression/anonymous-consents/anonymous-consents-flow.e2e-spec.ts_

Logs here: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/563/console

**Comment by giancorderoortiz** [comment]
I don't see this test failing anymore. 
It runs consistently in CI and localhost interactive mode. 
Running against dev-com6 2005 backend.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-06-26 at 11 32 57 AM](https://user-images.githubusercontent.com/46171897/85874816-3846c080-b7a1-11ea-87ac-fe4ee67cd76b.png)
![Screen Shot 2020-06-26 at 11 33 15 AM](https://user-images.githubusercontent.com/46171897/85874817-38df5700-b7a1-11ea-899f-220ae3fbb8d8.png)
![Screen Shot 2020-06-26 at 11 35 05 AM](https://user-images.githubusercontent.com/46171897/85874819-38df5700-b7a1-11ea-8c31-3aa61fde75cc.png)
