### ISSUE TITLE
Remove assistedservicesstorefront from the asm requirements.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#5503]
assistedservicesstorefront brings some sample data we need to get asm working in spartacus.

Ideally this extension would not be required for ASM to work in spartacus.  Investigate what we could do to improve this.

Could we move the sample data to a lower layer extension in the commerce suite?
Could we move the required sample data in the spartacus sample data?

**Comment by Xymmer** [comment]
created c3po ticket for this, https://jira.hybris.com/browse/C3PO-2340
closing this one
