### ISSUE TITLE
ASM style improvement suggestions

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#5513]
From Simon (but we have to check how it compares to matching SAP standards):
1. Change the background colour of the white bar when you're in a customer session
2. Make the search box smaller (half the size), center it
3. Put a nice logo to the left of the search box
4. Get rid of the italic fonts
5. Center the 'standard customer session in progress' text and get rid of the box
(known issue: https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5473) 
6. Make the whole white box smaller, like half the size - it's eating up screen real-estate
7. Use standard SAP colours for the 'start session' box

**Comment by bgambocjaviniar** [comment]
asm-toggle-ui needs to be included to be done in the issue
