### ISSUE TITLE
[need arch input] Missing module dependencies

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/spartacus#5526]
#5255 
# Summary 
When trying to import some specific core functionalities, there a no documentation around which module needs to be imported in which order and the only way to make it work it by trial and error. Modules themselves should properly declare their dependencies through imports so that as a developer, we can choose which module (ie. ProductModule) to import without having to figure out its inner dependencies. As an example, the GlobalMessageModule is required for the ProductModule effects, but is not imported.

# Environment Details
- Spartacus:  Latest
- Browser: N/A
- OS: N/A
- Device: N/A
- Other environment details: N/A

## Steps to Reproduce
Import the core/ProductModule without importing GlobalMessagesModule.

## Observed Results
Missing providers for GlobalMessagesModule

## Expected Results
ProductModule should properly define / import its dependencies.

**Comment by KateChuen** [comment]
@tobi-or-not-tobi do you have feedback on what we should do here please?
