### ISSUE TITLE
Installation script issues

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#5562]
When trying to fix the issues with SSR on the installation script (as described in #5370 ), we are now getting the following errors:

> Your global Angular CLI version (8.2.2) is greater than your local
version (8.0.6). The local Angular CLI version is used.

To disable this warning use "ng config -g cli.warnings.versionMismatch false".
Schema validation failed with the following errors:
  Data path ".budgets[1].type" should be equal to one of the allowed values.

We need to fix this to be able to install SSR. Also:
* The script is using outdated versions of project files (see files/) that need to be updated
* Parts of the script can be replaced by our angular schematics targets (npm add @spartacus)

**Comment by tobi-or-not-tobi** [comment]
@hackergil Not sure why this is considered an issue. The warning is very common, but doesn't affect the actual build.
