### ISSUE TITLE
Forced User Sign In Should be a Modal

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#5582]
Currently forced Sign In pages are embedded pages. This was a change from the legacy project done to limit the number of modals.

However, by moving to modal we lost the ability for the user to navigate backwards (cancel) by closing the window.

user can still use the back button, but this is not a 'best practices' solution and does not respect our novice user persona(s).

I suggest we move the forced sign in to modal windows.

What is a 'forced sign in' page or page set?
Forced sign in is when an unsigned user navigates to a feature that requires authentication to continue, such as: checkout, account. and in the near future, wish list, saved carts etc...

This is a breaking change and would be best done before the next large 'breaking' update.

Wireframes available on request.

**Comment by Xymmer** [comment]
agree this would be a good change

**Comment by Xymmer** [comment]
closing for now and we'll bring this back when we do a general ui refresh
