### ISSUE TITLE
Improvements to state utils (loader, entity, entity-loader, ...)

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#5588]
Things that we could improve in state utils:

- [x] share everything under the same `StateUtils` namespace
- [x] rename `entityStateSelector` to `entityLoaderStateSelector`
- [x] use selectors from loader utils in entity-loader
- [x] rename `EntityResetAction` to `EntityLoaderResetAction`

**Comment by Matejk00** [comment]
QA steps:
- import `StateUtils` from `@spartacus/core` and check if all state utils (reducers, actions, selectors, states) are available from that namespace.

**Comment by mszczepaniak** [comment]
Tested successfully.
