### ISSUE TITLE
cart page is not reloaded on another browser

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5652]
**Environment Details**
Spartacus: cart refactoring branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- On chrome, login as a customer. 
- Add a product to cart.
- On firefox, login with the same customer. Go to cart page
- On chrome, proceed to checkout and place the order.
- On firefox, click on "Proceed to checkout" 

**Actual Result**
You get an error "cart not found" but then it gets stuck on the cart page. And it looks like it's still processing the request.
If you go to a pdp page, you'll see that the cart still contains the item. 
Go back to cart page, and it still has the item. 

**Expected Result**
Cart page should be reloaded. And it should show an empty cart. 

<img width="991" alt="Screen Shot 2019-12-04 at 10 51 31 AM" src="https://user-images.githubusercontent.com/45409515/70157970-75702780-1684-11ea-9458-24238242b2b0.png">

**Comment by marlass** [comment]
This issue seems to also exist on `develop`. I could add error checks in cart refactor in one call, but it would be an only quick fix and this could still happen in other places. Let's leave it after the cart refactor merge.

**Comment by Xymmer** [comment]
@KateChuen @marlasak is this still happening?

**Comment by KateChuen** [comment]
Still happening.

**Comment by marlass** [comment]
Still would love to have time to do it, but it was postponed, because it might be related to retry/error handling mechanism.

**Comment by giancorderoortiz** [comment]
This issue continues to happen.  Dev branch. Oct 26, 2020. 
This ticket has been opened for almost 1 year. 
Fixing for 3.0?

**Comment by giancorderoortiz** [comment]
http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/

**Comment by LTiger14** [comment]
QA:
- On chrome, login as a customer.
- Add a product to cart.
- On firefox, login with the same customer. Go to cart page
- On chrome, proceed to checkout and place the order.
-  On firefox, click on "Proceed to checkout"

-> You should be redirect to cart with a global message

**Comment by giancorderoortiz** [comment]
It's somewhat clunky, but it will do for now. 
Tested with Chrome, FF, Edge. 

![Screen Shot 2020-11-06 at 2 22 33 PM](https://user-images.githubusercontent.com/46171897/98406257-a34fb000-203b-11eb-8cb2-e6132166358f.png)
