### ISSUE TITLE
[retest] asm: getting http response error after ending a customer's session

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5675]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: mac
Happens on: http://localhost:4200/electronics-spa/en/USD/?asm=true

**Steps to Reproduce**
- On chrome, login as an agent (asagent/123456). 
- Start a customer session.
- End the customer session.

**Actual Result**
You get this error right after a call that results in a 401: 

`Unknown http response error: -1 `

**Expected Result**
<img width="439" alt="Screen Shot 2019-12-05 at 2 42 28 PM" src="https://user-images.githubusercontent.com/45409515/70268198-f6571e00-176d-11ea-9800-d4b472e0cfd8.png">
<img width="468" alt="Screen Shot 2019-12-05 at 2 42 42 PM" src="https://user-images.githubusercontent.com/45409515/70268199-f6571e00-176d-11ea-93c6-3e30eab80248.png">

**Comment by Xymmer** [comment]
retest as we think it's fixed

**Comment by giancorderoortiz** [comment]
This issue is now fixed. Closing
![Screen Shot 2020-10-25 at 2 54 04 PM](https://user-images.githubusercontent.com/46171897/97116186-f8053980-16d1-11eb-8f9d-a3f48a041900.png)
