### ISSUE TITLE
add events for cds to the events service

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#5687]
In #5182 we introduced events service.

In this ticket we will add some events for CDS:
- login event. should fire only once, when the user logs in. Different than `AuthService.isUserLoggedIn()`.
- User is on PDP page
- User is on PLP page
- Facet changed on a PLP page (search results, category and brand page)

**Comment by Platonn** [comment]
related to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5062

**Comment by znikola** [comment]
Closing as it's not relevant anymore.
