### ISSUE TITLE
anonymous-consents-config-flow e2e failing consistently. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#5734]
Test anonymous consents flow is passing. 
However, test anonymous consents config flow has been failing consistently over past few days. 

**Screenshots:**
![Anonymous consents - config flow -- when config registerConsig is changed, requiredConsents and hideConsents exist, -- should check if marketing consent in the dialog is disabled -- before all hook (failed)](https://user-images.githubusercontent.com/46171897/70554974-288cc500-1b4c-11ea-991f-0a8601705c31.png)

![Anonymous consents - config flow -- when config legalDescription is false and showAnonymousConsents is false -- should not display the consents on the consents management page -- before all hook (failed)](https://user-images.githubusercontent.com/46171897/70554982-2a568880-1b4c-11ea-85df-a44b8224771b.png)

**Test execution video:** 
[anonymous-consents.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3946424/anonymous-consents.zip)

**Comment by giancorderoortiz** [comment]
Related to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5482

**Comment by giancorderoortiz** [comment]
latest failure with develop branch dec_10_2019

**Comment by marlass** [comment]
Working correctly for some time on develop branch. Closing
