### ISSUE TITLE
Express Checkout e2e Failing Consistently. Develop Branch

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#5737]
Enabled express checkout in config prior to running.
Failure has continued for more than one week.

frontend: dev-com6
backend: dev-com17

Screenshot: 

![Express checkout -- go to checkout -- before all hook (failed)](https://user-images.githubusercontent.com/46171897/70556359-bec1ea80-1b4e-11ea-9d82-8eab8fb16892.png)

Video: 
[express-checkout.e2e-spec.ts.mp4.zip](https://github.com/SAP/cloud-commerce-spartacus-storefront/files/3946508/express-checkout.e2e-spec.ts.mp4.zip)

**Comment by marlass** [comment]
For more than a month express checkout tests are passing on develop. Closing this one
