### ISSUE TITLE
Store cart entries by the entry KEY

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#5749]
When cart entries are loaded from the backend, the cart data is persisted in Spartacus. The cart entries are persisted by the product code, which is fundamentally wrong. A cart can have multiple entries with the same product: 
- Multiple cart entries with the same product but different product configurations (i.e. different engraving for the same product)
- A free gift promotion results in a separate entry in order identify the cart line differently on the cart

We should change the default behaviour, and introduce a cart entry KEY. The key could be the cart entry `entryNumber` for OCC, but to adapt alternative cart systems (including cloud cart) we should make the cart KEY agnostic, so that each adapter implementation can _normalise_ the key. 

**Update:** The above mentioned change is already partially fixed with the recent cart refactoring for multi-cart. The only changes left are related to selecting the cart by it's entry rather than the entry KEY. 

Also note that one of our customers has already gone through this change, and used the cart PK for the key, since the `entryNumber` is an incremental number that might cause problems if a line will get deleted from the cart.

**Comment by Xymmer** [comment]
Related to https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/5747 ?

**Comment by kacperknapik** [comment]
Was it done in #5747 ?

**Comment by marlass** [comment]
Nope
