### ISSUE TITLE
variants: Mini variants logo missing from plp

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#5787]
**Environment Details**
Spartacus: variants branch
Browser: Chrome
Device: mac
Happens on: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**
- On chrome, go to a category listing page, for eg: http://dev-com-15.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP/category/200100

**Actual Result**
The mini variant logos are missing from that page.

<img width="1042" alt="Screen Shot 2019-12-12 at 1 21 52 PM" src="https://user-images.githubusercontent.com/45409515/70739305-8522e800-1ce4-11ea-931b-05b1606baf42.png">

**Comment by bgambocjaviniar** [comment]
closing as it seems to be fixed 
![Screen Shot 2021-06-16 at 10 05 12 AM](https://user-images.githubusercontent.com/29099466/122233852-63cb2b00-ce8a-11eb-9ef1-2a66a38172d2.png)
