### ISSUE TITLE
[retest] Broken navigation bar on SmartEdit

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/spartacus#5817]
## Environment Details

- Spartacus:  1.2
- Browser: Chrome
- OS: Mac OSX
- Device: Mac
- Other environment details: 8

## Steps to Reproduce

1. Go to SmartEdit
2. Load the OOTB Spartacus Storefront
3. Go to preview mode 
4. Hover on the navigation menu (ie. Digital Cameras)

## Observed Results
The menu opens but is not visible. 

## Expected Results
The menu should be visible.

## Offer to Fix
No

## Additional Information
SmartEdit uses component wrapping to display their overlays which causes this issue. Although this issue in mainly on SmartEdit, regarless of that the menu should still be displayed properly on OOTB Spartacus.

**Comment by tobi-or-not-tobi** [comment]
@CarlEricLavoie this is a know issue, but afaik not something which can be solved by Spartacus team, would you agree. 

@WeizhengSap do you remember the outcome of earlier investigations for this issue?

**Comment by CarlEricLavoie** [comment]
@tobi-or-not-tobi  - it's indeed mostly a SmartEdit issue, but it could be fixed in Spartacus from what I can see.

There seems to be an unnecessary "overflow : hidden" applied on the NavBar content slot. Not sure why it has been placed there, but that's what's causing the issue when SmartEdit wraps with relative containers. 

![2019-12-14_22-26-38](https://user-images.githubusercontent.com/7239120/70857673-fc14d800-1ec0-11ea-9ff0-35c2a49b0a4f.png)

Disabling that overflow hidden fixes it and doesn't seems to have side effects.
Given that all level2 menus are absolute and that containers are normally not relative (unless in smartedit) that overflow has no use afaik.

I might have a use for mobile, in which case it could be restricted to mobile as well.

**Comment by tobi-or-not-tobi** [comment]
@CarlEricLavoie that's really valuable feedback! The `overflow:hidden` has been added (if I remember correctly) to make sure that too much navigation items in desktop mode would not overflow to the next line. It was a dirty fix, and we should flow the items into an additional burger/kebab icon nav from my pov

**Comment by KateChuen** [comment]
We think this is fixable in Spartacus. But let us know if it's not.

**Comment by giancorderoortiz** [comment]
@Xymmer @WeizhengSap how should we proceed with this issue?

**Comment by WeizhengSap** [comment]
@giancorderoortiz : you can test navigation bar in smartEdit preview mode to see whether it works.

**Comment by Xymmer** [comment]
This is working as of 3.3, closing
