### ISSUE TITLE
Changes in order-detail page style structure

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#5839]
@tobi-or-not-tobi can I please have your feedback on this issue.

While working on the **cancellations-returns** process I found out that all _Order Detail_'s page styles contained in `order-details` folder are obsolete and disconnected from the cx-components list. This is the current state in `develop`.

![Screen Shot 2019-12-16 at 7 56 50 AM](https://user-images.githubusercontent.com/15113219/70925479-4a2cf700-1ff9-11ea-86aa-8399af21a8e0.png)

That mainly because at some point in the past (8 months ago) the whole "order-details" styles were reset to template level styling, but while ignoring the already existing styles. 

![order-detail-headline](https://user-images.githubusercontent.com/15113219/70926503-40a48e80-1ffb-11ea-94e7-fa1044ee3ae9.jpg)

Since we cannot reconnect those styles, and NOW they were already transferred to **a template level theme calydon fix** for that page, the aforementioned files are no longer needed, except for "consignment-tracking" which we can move to a more meaningful place with related files.

The underlined components above are no longer needed as files, can we agree to remove the whole `order-details` folder and files, and create a new folder called `order-history` to move all style comprised in that area: **consignment-tracking, order-history and all cancel-return styles**... since the _Order History_ page serves as index or  entry point for all subsequent pages, which are as well where the cancellations and returns process is contained, precisely as part of that history.

This is my feature branch showing the new proposed arrangement, we delete those in red and group all those in green:

![Screen Shot 2019-12-16 at 11 59 24 AM](https://user-images.githubusercontent.com/15113219/70926935-0091db80-1ffc-11ea-9ff3-73e63569dac9.png)

**Comment by developpeurweb** [comment]
**For QA:**

- Validate the code was moved
- Validate _order-details page_'s layout remains visually unaffected.

**Comment by bgambocjaviniar** [comment]
* approved as the code was removed and many redundant css removed.
* layout did not change and looks like how it is supposed to be displayed in here https://github.com/SAP/spartacus/issues/7127
