### ISSUE TITLE
Automating shellapps/libraries/ci scripts for future integrations

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#5842]
More integrations will be coming and we need a way to facilitate each of them, so that they can not worry about the small things and focus on the actual integrations.

- Shellapps
- Libraries
- CI script

The above needs to be automated.
Possible solution: schematics, python, etc...

**Comment by marlass** [comment]
Might be worth to look into: https://github.com/nrwl/nx

Maybe that's a better solution to our monorepo setup than trying to create our own solutions for apps/libraries/... management.

**Comment by bgambocjaviniar** [comment]
will be finishing on my own time (didn't had time to continue)
