### ISSUE TITLE
Remove Bootstrap Styling Dependencies

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#5926]
We have remaining bootstrap styling dependencies in the spartacus styles library that have conflicts when attempting to add our own styles (eg. bootstrap focus styles coinciding with our own). Instead of trying to override these when they occur, we should remove bootstrap dependencies from the spartacus styles library and fix the styles on the components that this might break.

**Comment by tobi-or-not-tobi** [comment]
@Zeyber can you make the title more specific as it gives the impression that we're dropping bootstrap completely.

**Comment by Zeyber** [comment]
> @Zeyber can you make the title more specific as it gives the impression that we're dropping bootstrap completely.

Updated the description
