### ISSUE TITLE
Breaking changes since 1.5 - customer coupon

### ISSUE THREAD

**Issue by maggielin0** [SAP/spartacus#5971]
for customer coupon #5662 
introduce new customerCouponService into CartCouponComponent constructor.

replace old constructors (overload)
```
constructor(
    cartService: CartService,
    authService: AuthService,
    cartVoucherService: CartVoucherService,
    formBuilder: FormBuilder,
    customerCouponService: CustomerCouponService,
    featureConfig: FeatureConfigService
  );
  /**
   * @deprecated Since 1.5
   * Add customerCouponService,featureConfig for customer coupon feature.
   * Remove issue: #5971
   */
  constructor(
    cartService: CartService,
    authService: AuthService,
    cartVoucherService: CartVoucherService,
    formBuilder: FormBuilder
  );

  constructor(
    private cartService: CartService,
    private authService: AuthService,
    private cartVoucherService: CartVoucherService,
    private formBuilder: FormBuilder,
    private customerCouponService?: CustomerCouponService,
    protected featureConfig?: FeatureConfigService
  ) {}
```

with the new one:
```
 constructor(
    private cartService: CartService,
    private authService: AuthService,
    private cartVoucherService: CartVoucherService,
    private formBuilder: FormBuilder,
    private customerCouponService: CustomerCouponService
  )
```

in `ngOnInit()`, using featureLevel 1.5 to add new code for customer coupon  

```
if (this.featureConfig && this.featureConfig.isLevel('1.5')) {
//new code
}else{
//old code
}
```
NOTE: remove the if statements with featureFlags altogether, leaving only the 'new code' part

in cart-coupon.component.html, using cxFeatureLevel to contain new and old one
```
<ng-container *cxFeatureLevel="'1.5'">
//new code
</ng-container>
<ng-container *cxFeatureLevel="'!1.5'">
//old code
</ng-container>
```
Please remove old code in <ng-container *cxFeatureLevel="'!1.5'"> block and <ng-container *cxFeatureLevel="'1.5'"> statement,  only remain 'new code' part.

**Comment by Xymmer** [comment]
something for next new major? (2.0 likely?)

**Comment by maggielin0** [comment]
It's for 1.5 due to the BC of the constructor.

**Comment by kacperknapik** [comment]
this ticket contains very little BC, and all of them are handled by our featureFlags. so we can easily merge it to 1.5 @Xymmer

**Comment by tobi-or-not-tobi** [comment]
we've discussed some refactoring with the team and decided to do this work as part of this ticket, see #5971
