### ISSUE TITLE
occ-cms-page-normalizer does not handle page with single slot

### ISSUE THREAD

**Issue by neilhubertprice** [SAP/spartacus#6004]
Slack thread: https://spartacus-storefront.slack.com/archives/CD16V16FR/p1578326204139800

According to comments on that thread: it appears to be a bug when the page only has one slot coming from hybris.

The payload that comes over from hybris looks like this when there are multiple slots.
> "contentSlots" : {
>       "contentSlot" : [ { ...}, {...} ]
> 

But when there is only one slot it comes over like,
> "contentSlots" : {
>       "contentSlot" : {...}
> 

Notice how contentSlot is only a json object and not an array.

In occ-cms-page-mormalizer this is parsed as an array: 
>   private normalizePageSlotData(source: any, target: CmsStructureModel): void {
>     for (const slot of source.contentSlots.contentSlot) {
>       target.page.slots[slot.position] = {
>         components: [],
>         properties: slot.properties,
>       } as ContentSlotData;
>     }
>   }

**Comment by Xymmer** [comment]
to be triaged with a dev
