### ISSUE TITLE
Variants+SmartEdit: Product not found error

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6022]
as reported by Brian and Louis
smartedit seems to work but it gives errors for carousel products, which work without smartedit

carousel works in electronis for smartedit

also saw this:
![image](https://user-images.githubusercontent.com/4998145/72006999-c395bf00-321e-11ea-8f6d-972a4534fc4f.png)

**Comment by mirkosoft** [comment]
what is this about exactly?

**Comment by LTiger14** [comment]
Should be re-tested and provide more details on the issue.

**Comment by LTiger14** [comment]
Could not reproduce, Bill to check again.
