### ISSUE TITLE
Improve cart's coupons input/select field

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#6023]
While reviewing my coupons and browsing the UI, I noticed that it doesn’t match visual mockups as per screenshot below.

![Screen Shot 2020-01-07 at 12 17 34 PM](https://user-images.githubusercontent.com/15113219/72021739-b5569b80-323c-11ea-9fdd-d3b986bc2804.jpg)

**Turns out there are 2 ways to claim a coupon:** some coupons have to be claimed and referenced to “My Coupons” page in order for them to show up in the cart's select box, but others could be entered **manually** directly in the input field and clicking on the apply button, that said, it seems the mockups do not reflect both scenarios.

This situation introduces the following issues:

1. Maintenance for a **new component**, the dropdown currently implemented is similar to the search box which was made custom, as opposed to using a default angular select box, which are already styled (like those in the Results Page or the My Coupons page).
2. Current solution is not keyboard accessible, as default select boxes are.

We have 2 solutions as I see it (suggestions are welcome as long as they’re accessible):

1. Make the current component fully keyboard accessible and find a solution so it's possible to scroll through multiple coupons on mobile. (visual could look somewhat similar to that in the mockup but **without the arrow** from the select box).
![Screen Shot 2020-01-07 at 12 17 34 PM](https://user-images.githubusercontent.com/15113219/72022992-c654dc00-323f-11ea-9d26-70cd11f71477.png)

2. Leave the field with apply button for manual input, and add a select box underneath for claimed coupons assigned to the user. (suggested visual below).
![Screen Shot 2020-01-08 at 5 39 10 PM](https://user-images.githubusercontent.com/15113219/72023011-cce35380-323f-11ea-9daa-ee59c7957059.png)

Either way please confirm these options with the Designer in charge and write the decision and attach approved mockup in this ticket.

**Comment by Xymmer** [comment]
this was done due to addition of customer coupon feature, which is independent of regular coupons. we have to support both somehow. Miguel's suggestion of providing a separte drop down for "known" coupons (coupons assigned to the customer) fits the bill easily and re-uses existing components.

**Comment by maggielin0** [comment]
PANDA-3347 is created to track this improvement.

**Comment by Xymmer** [comment]
was done for 2.0 in another ticket
