### ISSUE TITLE
[retest] [probably 2005 release only] invalid notification type error with 1.4

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6050]
(I'm using latest 2005 zip that contains latest commercewebservices)

Type in product number like 816323 or 816321 (doesn't seem to matter if it's a word or number)
Click suggested product
Get type error

![image](https://user-images.githubusercontent.com/4998145/72189827-e1eced80-33cb-11ea-87bd-150b6be042fc.png)

**Comment by Xymmer** [comment]
we do not see this in 1905, bill to double-check with local 1905 to be sure.

**Comment by Xymmer** [comment]
retest, i have not seen this recently while playing with 2005

**Comment by Xymmer** [comment]
Haven't seen this issue in a long time in 2005

**Comment by giancorderoortiz** [comment]
Unable to reproduce with 2005 backend. 
http://dev-com-5.accdemo.b2c.ydev.hybris.com:4200/
Invalid notification type error message not seen, nor displayed in console
