### ISSUE TITLE
Item "8796096828309 (and others) no longer valid" global message when starting checkout

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6081]
Seeing this message when adding to cart and then going to checkout.
Through express checkout.
When testing cancel/returns with this cart:
899387: 1
572461: 2
1099285: 3
1422706: 4
594471: 5

But nothing gets removed from my order.
![image](https://user-images.githubusercontent.com/4998145/72361388-6b980600-36bf-11ea-9b9d-82461dbebc5a.png)

Later when recreating same order, see this:
![image](https://user-images.githubusercontent.com/4998145/72362624-79e72180-36c1-11ea-8bfc-3dc8d754a70b.png)

Later, same:
![image](https://user-images.githubusercontent.com/4998145/72363341-b404f300-36c2-11ea-8f51-e40f26dcfbcb.png)

**Comment by KateChuen** [comment]
To be retested in 2.0 after Marcin's cart refactoring.

**Comment by kacperknapik** [comment]
It's either fixed or I cannot reproduce it.

**Comment by kacperknapik** [comment]
This ticket is dependant on some backend changes. Errors are currently hidden. This will be possibly done after 2105.
