### ISSUE TITLE
"Redirect is not allowed for a preflight request" error (not a bug in Spartacus)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6122]
If your Spartacus site is not appearing, and in the console you see a CORS error: 
“Response to preflight request doesn’t pass access control check: Redirect is not allowed for a preflight request”, it might be because OCC is not configured correctly, and when your app is making an OCC call, the commerce suite is returning a redirect for displaying an error. The problem may not be CORS.

Check the OCC is working by going to <server>/rest/v2.

**Comment by omkar25** [comment]
Error when loading homepage on spartacus from angular i am getting below message on browser console.
Can someone help to me i am new to setup spartacus with cx ...
Access to XMLHttpRequest at 'https://localhost:9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&pageType=ContentPage&pageLabelOrId=homepage&lang=en&curr=USD' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: Redirect is not allowed for a preflight request.

**Comment by Nani-Boddeti** [comment]
If you face the issue with 2005 Commerce Cloud version. Please try by replacing the **rest** with **occ** in app.module.ts file,as in version 2005 ycommercewebservices extension is replaced with commercewebservices extesnion which has webroot as /occ where as the latter has webroot [/rest.]
