### ISSUE TITLE
Search bar: the chosen word from the drop-down is not shown

### ISSUE THREAD

**Issue by mlogvyna** [SAP/spartacus#6170]
**Steps to Reproduce:**
1. Go to UI -> click on search bar to perform a search
2. Start to type any word (e.g: manage) to get the full word hint in the drop-down
3. Choose any option from the drop-down hints (e.g: management)
![image](https://user-images.githubusercontent.com/60095122/72720615-08a4e400-3b83-11ea-96b0-a27a9ee68cc8.png)

4. Pay attention on the search results and on the chosen word in search bar

**Observed Results:**
The chosen word from the drop-down hint (e.g: management) is not shown on the search bar, however the search result is performed
![image](https://user-images.githubusercontent.com/60095122/72720558-ec08ac00-3b82-11ea-8eb3-12e392cb487a.png)

**Expected Results:**
The chosen word from the drop-down hint (e.g: management) is shown on the search bar

**Comment by Xymmer** [comment]
moving this one to 3.0, so we don't block 2.1 release

**Comment by bgambocjaviniar** [comment]
moving to do because owner for the PR finished their internship,
**therefore**, anyone can pick up or create a new PR.
