### ISSUE TITLE
Cancel item before consignments created, total price incorrect

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#6183]
Required: cancel returns, OMS (dev10).
1. Add various products. To make it obvious, check out.
2. Cancel an item before consignments are created.

Result: The subtotal displayed does not excluded the cancelled, unconsigned product.
If the product was part of a consignment, it's fine.
Need to determine if there is something Spartacus can do, or if it's a backend issue.

Update: backend issue, same in Accelerator

**Comment by WeizhengSap** [comment]
<img width="733" alt="Screen Shot 2020-01-20 at 4 37 07 PM" src="https://user-images.githubusercontent.com/44440575/72811385-8f160000-3c2d-11ea-8d31-019878011487.png">

Cancel one product in an entry (which has 2 products), the total is not updated.

**Comment by Xymmer** [comment]
moving to 'retest' bucket after this ticket is fixed: https://jira.hybris.com/browse/C3PO-2060

**Comment by Xymmer** [comment]
Backend was fixed in June, see https://cxjira.sap.com/browse/C3PO-2060. Retest Spartacus

**Comment by psmul** [comment]
![image](https://user-images.githubusercontent.com/10993491/121345937-be620580-c925-11eb-87cf-1d2bdb3c428d.png)


Can confirm that backend fix solved the issue. After adding and ordering item in a quantity of 6 and canceling 1 quantity of that product, the price updated to the one corresponding to quantity.
