### ISSUE TITLE
Server did not respond error during checkout on the public instance [SAFARI]

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#6237]
## Environment Details

- Browser: **Happens Safari**
- URL: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/

## Steps to Reproduce

- Create an account & login
- add product to cart
- checkout with product in cart
- add shipping address
- Click on continue

## Observed Results

The /checkout/delivery-mode page loads indefinitely and a global error message pops up with the message of : _The server did not respond_

## Expected Results

Normal checkout flow

**Comment by Xymmer** [comment]
Was able to repro using ipad safari

**Comment by Xymmer** [comment]
@qjimmy could you verify if this is only cloud server? If so then it’s a config issue with that server and not Spartacus or something special about Safari

**Comment by LTiger14** [comment]
@LTiger14 check version on ccv2
@qjimmy Try to repro on dev-12

**Comment by mirkosoft** [comment]
Checked ccv2 in:
- safari mac (bug occurs)
- chrome mac (bug occurs)
- firefox mac (OK)

**Comment by LTiger14** [comment]
Just to clarify my earlier comment ccv2 is on 1.4

**Comment by mirkosoft** [comment]
Safari Mac: for local spartacus (feature level 1.4) pointing to dev17 there is an error:
`Failed to load resource: the server responded with a status of 400 ()`
for PUT request:  `/rest/v2/electronics-spa/users/current/carts/00002521/addresses/delivery`.
However checkout goes to next step.

**Comment by mirkosoft** [comment]
Once it's fixed pls merge it to latest maintnance branch too (1.5.1)

**Comment by Platonn** [comment]
Could not reproduce using:
- Browser: Chrome 80
- backend: dev-com17
- branch: latest develop 1019ba543a5e68a6d47a244658df29bdf139dd15

I didn't get any global message error and I could finish checkout successfuly. But I could observe error in the console after clicking [Continue] on 'Checkout/Shipping Address' page:
![image](https://user-images.githubusercontent.com/4001059/78893677-02305500-7a6c-11ea-8602-1710444dc9c2.png)

**Comment by Xymmer** [comment]
Closing and we'll retest in full when we update our servers
