### ISSUE TITLE
Robots.txt file is not available

### ISSUE THREAD

**Issue by PiotrZ-Eclipse** [SAP/spartacus#6243]
## Environment Details

- Spartacus:  1.3
- Browser: Any
- OS: Any
- Device: Any
- Other environment details: Any

## Steps to Reproduce
When using old accelerator storefront (with /yacceleratorstorefront extension being configured with web module) and accessing /yacceleratorstorefront/robots.txt url then the default robots.txt file will be served.

## Observed Results
Robots.txt file is not served and is not existing in repository.

## Expected Results
Static Robots.txt file from code repository is served.

## Repository Used
release/1.3.1

## Offer to Fix
NO

## Additional Information
Attaching view from old storefront:
![robots txt-old_storefront](https://user-images.githubusercontent.com/57955321/73076789-204fd580-3ebf-11ea-92e0-4221594a0a4a.png)

**Comment by tobi-or-not-tobi** [comment]
`robots.txt` files are part of the application code, and cannot be _served_ with a library. We could however ship a `robots.txt` file with the asset lib, but it's not give too much value – happy to learn if you think different. 

We do have a meta tag driven robots approach, where individual strategies can be applied per page. We also have an open ticket on the CMS where robots will be configurable. With that approach, business users can control the robot strategy per (content) page.

**Comment by tobi-or-not-tobi** [comment]
Removing the bug label as I do not consider this a bug, and closing as there's not much reasonable we can do.
