### ISSUE TITLE
Storefinder "Use my location" does not work - Radius is hardcoded

### ISSUE THREAD

**Issue by kbalagtey-tacit** [SAP/spartacus#6275]
#5727  Environment Details

- Spartacus:  1.4
- Browser: Chrome
- OS: Mac

## Steps to Reproduce
Click the "Use my location"

https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/store-finder

## Observed Results
No results returned

## Expected Results
Results to show. 

## Repository Used
https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/store-finder

## Offer to Fix
No

## Additional Information

The issue is caused by the radius parameter. At the moment, this is hardcoded to use 10000000

According to the documentation -https://developers.google.com/places/web-service/search

The maximum radius should be  50 000 meters. Ideally, this should also be configurable.

**Comment by Xymmer** [comment]
Both a bug to fix and an improvement to make it configurable

**Comment by kacperknapik** [comment]
**QA results**
- works as expected
