### ISSUE TITLE
Option to disable "Exact Match" in searchbox

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/spartacus#6325]
We need a way to disable the "exact match" in the search-box-component.service.ts without disabling all suggestions.

Right now, everything is private and there are no configuration to disable the exact match.

## Environment Details

- Spartacus:  1.4.0

## Steps to Reproduce
open search-box-component.service.ts

## Observed Results
function getExactSuggestion is private and there are no configuration available to disable the exact match.

## Expected Results
There should be a configuration variable to control whether or not we want to use exact match.

**Comment by CarlEricLavoie** [comment]
@Xymmer @tobi-or-not-tobi  - is this something that could be retrofited into 1.4.0 so that it makes it into the RC? We are currently force to completely copy-paste the service to overwrite this behavior. We'll revert our change once this is merged and available.

**Comment by Xymmer** [comment]
keeping 2.1-stretch, if we get it into 2.1, great

**Comment by hackergil** [comment]
Reopened since TranslationChunksConfig change is unrelated and protected methods need to be tested.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by kacperknapik** [comment]
**QA results:** the service is now extendable - all methods that the user would want to extend, are not private/protected anymore
