### ISSUE TITLE
Empty Cart flashes before showing Cart items

### ISSUE THREAD

**Issue by kbalagtey-tacit** [SAP/spartacus#6341]
The empty cart shows before showing the cart item list

## Environment Details

- Spartacus: Next
- Browser: Chrome
- OS: Mac

## Steps to Reproduce

1. Add item to cart
2. Go to cart page
3. Refresh the page

## Observed Results

The empty cart shows before showing the cart items

## Expected Results
Do not show empty cart if there are items in the basket

## Repository Used
Reproducible in demo site - https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/cart

## Offer to Fix
NO

**Comment by KateChuen** [comment]
@hackergil to reproduce.
