### ISSUE TITLE
Create OCCUserService

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6367]
Move OCC user functionality into separate service.

Utilize storage sync feature to keep it even after page reloads. It would be good if each auth submodule (OCCUser, ClientCredentials would be a separate entity under `auth` store feature.

**Comment by marlass** [comment]
Wait for #8114 before reviewing

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- verify in `UserAuthModule` code that we store information about user id only in `UserIdService`.
- it should not be stored in ngrx store
- it should not be stored in AuthStorageService
