### ISSUE TITLE
Generic link component doesn't handle query params

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#6368]
When trying with such url:
http://localhost:4200/apparel-uk-spa/en/GBP/Collections/Streetwear/c/251100%3FsortCode%3DtopRated
server responds with 404 because it's trying to get category `251100?sortCode=topRated` instead of just `251100`.
Fix is probably about parsing the link before passing it to `routerLink` in `GenericLinkComponent` and adding extracted facet params as query params to `routerLink`.

Please also note that for performance reasons changing detection strategy to `OnPush` (for `GenericLinkComponent`) should be checked and implemented as well if all works fine with it.

**Comment by Platonn** [comment]
The logic of splitting URL into the path and query params should be placed in a GenericLinkComponentService to be extendable and so customers can handle some custom edge cases.

**Comment by Xymmer** [comment]
to miro to check and write status

**Comment by mirkosoft** [comment]
This issue is still occurring and needs to be fixed as in the comments above.

**Comment by Xymmer** [comment]
i marked this as backend-dependency but don't see why;
@mirkosoft or @Platonn is this dependent on backend change?

**Comment by Platonn** [comment]
## QA steps

### Prereqisites
In the CMS add query params to some link in the category navigation (i.e. Blank Videotapes)
![image](https://user-images.githubusercontent.com/4001059/83019535-68c2ff80-a027-11ea-9376-8e9f35d42650.png)

1. go to backoffice
1. In left hand navigation: WCMS -> Component
1. search for "Videotapes" and open the `BlankVideotapesCategoryLink` of the `SPA Electronics Content Catalog: Online`
1. add query params to the `URL`, for example query with availableInStores and sorting mode: 
   ```
   /Open-Catalogue/Cameras/Camera-Accessories-26-Supplies/Blank-Video-Tapes/c/604?query=:relevance:allCategories:604:availableInStores:Fukuoka%20Best%20Western%20Fukuoka%20Nakasu%20Inn&sortCode=name-asc
   ```

### Testing
1. Open the storefront
1. In the category navigation open Accesories ->Blank Videotapes (the link should direct to previously configured URL containing query params)
   ![image](https://user-images.githubusercontent.com/4001059/83037709-67500200-a03c-11ea-8055-32d9bb2c95c5.png)

1. Verify that you see the PLP of the Blank Videotapes with the sorting and facets preselected by the query param
   ![image](https://user-images.githubusercontent.com/4001059/83020079-44b3ee00-a028-11ea-8cae-4df0ee12db2f.png)

**Comment by giancorderoortiz** [comment]
Test successful. Good. 
Only observation is that the change in backend doesn't reflect in frontend right away. 
Takes a couple of retries and/or reload of page. 
Tested on dev-com2. Frontend: develop. Backend: 2005. 

![Screen Shot 2020-06-01 at 9 06 03 AM](https://user-images.githubusercontent.com/46171897/83412209-b785e600-a3e7-11ea-989b-17bb19d33354.png)
![Screen Shot 2020-06-01 at 9 08 52 AM](https://user-images.githubusercontent.com/46171897/83412220-b9e84000-a3e7-11ea-81f2-5ceb6b377654.png)
