### ISSUE TITLE
`language-my-account-pages.e2e-spec.ts` is failing

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#6375]
`language-my-account-pages.e2e-spec.ts` fails because a product is out of stock.

To repro, run the test agains dev12

**Comment by plabadie** [comment]
Closing.  Can't repro the out of stock issue.

**Comment by plabadie** [comment]
Fails on 1.5.x for a yet unknown reason
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/20/consoleText

**Comment by bgambocjaviniar** [comment]
closing as it has never failed in the non-flaky regression suite
