### ISSUE TITLE
Verify datepicker (budget) logic 

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6392]
Get to know expected behavior for time zones and fix or make sure that it is correct.

**Comment by Zeyber** [comment]
According to api standards: https://github.tools.sap/cx-commerce/architecture/blob/master/docs/technology-guidelines/api-guidelines/api-design.md#3651-date
- We should include timezone information in our timestamps.
- This indicated we should include the local +- timezone offset
