### ISSUE TITLE
Maximum length of HTTP GET request for loading cms components

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#6406]
As pointed out on [stackoverflow](https://stackoverflow.com/questions/60000422/request-uri-too-long-on-spartacus-services/60072164#60072164), the standard GET request for componentIds is failing when the list of components is very long. In case there's a longer number of components being loaded at the same time, the request might fail, as GET requests are limited by both clients and server configurations.

The original code that allows for POST requests instead (we actually moved from POST to GET, see #1033), is still in the code base. We should either leverage POST or leverage pagination and reduce the number of requests in a single call. 

We're moving more and more towards component based loading. See #3649 and #5845. This ticket is going to become increasingly important.

**Comment by GaryZA** [comment]
Is there a reason this was closed-without-action ? I am currently trying to work around the same issue listed on [stackoverflow](https://stackoverflow.com/questions/60000422/request-uri-too-long-on-spartacus-services/60072164#60072164)
