### ISSUE TITLE
Remove usage of getUserToken outside of auth module

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6410]
getUserToken gives raw access to auth tokens only places that requires that data are interceptors.
For common use cases others methods make more sense:
- getOccUserId (if you need occ user id)
- isUserLoggedIn (if you only need is user is logged)

**Comment by marlass** [comment]
Wait for #8114 before reviewing

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- verify that `getToken` and `getItem` methods from `AuthStorageService` or from `AsmAuthStorageService` are used only inside the `UserAuthModule`.
