### ISSUE TITLE
Extract client_credentials auth from user auth stuff

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6412]
Client credentials required for particular API endpoints (user registration, guest checkout) are not related to user token stuff. We can easily extract it into separate module and make it more understandable for us and developers extending that.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- check if whole code responsible for client auth is placed in `ClientAuthModule` (services, ngrx, interceptors, models)
- only configuration used by client auth can be outside of this module (as it is shared with user auth)
