### ISSUE TITLE
Add generic (multid) variant support

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#6426]
Currently spartacus variants support three variant types: size, style and color. To meet parity and fit to backend 100% let's add generic variant type. Implementation details to come.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by mirkosoft** [comment]
First you have to have a product with `GenericVariantProduct` variants. BTW - any idea why it's not the case anymore on dev12/17 ? there was a product with code `1978440_md` with generic variant added but it's not there anymore.
More steps to come.

**Comment by hackergil** [comment]
I spoke to @mirkosoft about this. Deprioritizing it for now since this task is b2b dependent and it will use multi-d variants, which are not supported yet.

**Comment by mirkosoft** [comment]
closing this as already covered by #7878
