### ISSUE TITLE
Deferred Loading doesn't work properly in SSR mode

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#6449]
Deferred Loading makes double loading (screen blinking) during first page rendering in SSR mode.

## Environment Details

- Spartacus:  *-1.5.0

## Steps to Reproduce

1. Activate deferredLoading inside layout configuration with the following parameters: 
```
deferredLoading: {
  strategy: DeferLoadingStrategy.DEFER,
  intersectionMargin: '50px'
}
```
2. Build and start application in SSR mode.
3. Open any page in Browser with cleared cache.

## Observed Results

Page loads twice. Looks like SPA application reloads view rendered by SSR.

## Expected Results

Page correctly loads without screen blinking.

**Comment by Matejk00** [comment]
@artem-zur  we can't reproduce this bug on current 1.5 version. Can you confirm if this still exists?
Be sure that you have `BrowserTransferStateModule` imported in your's `app.module.ts` file.

**Comment by artem-zur** [comment]
@Matejk00, we just have upgraded our application to Spartacus 2.0 and still have this issue with double reloading in SSR mode. Yes, of course we have `BrowserTransferStateModule` in `app.module.ts` file.

And one more important thing, regarding to https://sap.github.io/spartacus-docs/deferred-loading/#server-side-rendering we can't use deferred loading with application which builded in SSR mode, is it right ?

**Comment by artem-zur** [comment]
With @psmul suggestion, I'v created and linked a new, separate issue specially for Spartacus 2.0 version.
