### ISSUE TITLE
Missing translation for the deliveryStatus in Order Details

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/spartacus#6450]
Instead of the label, [myAccount:orderDetails.deliveryStatus] is shown.

See the picture below
![order](https://user-images.githubusercontent.com/4272069/74035341-64ac9c80-49ba-11ea-9f46-4b96ed17b87e.png)

**Comment by dydome** [comment]
@mszczepaniak for version 3.0.0 it looks like the problem is solved as there is a different structure.
