### ISSUE TITLE
Get rid of duplication of binding on use ng-select

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6454]
In most of forms, when we use ng-select we have binding (`bindLabel, bindValue`) and additional set value by function from event `(change)`.

e.g in address-form.component
```
<ng-select
  formControlName="titleCode"
  [searchable]="false"
  [clearable]="false"
  [items]="titles"
  bindLabel="name"
  bindValue="code"
  (change)="titleSelected($event)" 
>
</ng-select>
````

```
  titleSelected(title: Title): void {
    this.address['controls'].titleCode.setValue(title.code);
  }
```

Probably additional function called on change is unnecessary - form value works same as without

**Comment by Matejk00** [comment]
QA: Tested on all checkout flow forms and no errors occured,
