### ISSUE TITLE
spartacussampledataaddon is not imported into Eclipse

### ISSUE THREAD

**Issue by geffchang** [SAP/spartacus#6456]
## Environment Details

- Spartactus: 1.5.0-RC.0 and earlier
- IDE: Spring Tool Suite 4 / Eclipse

## Steps to Reproduce
1. Prepare Hybris using the Spartacus guide
2. Using SAP Hybris Commerce Development Tools for Eclipse, import the hybris/bin/platform project

## Observed Results
1. Majority of Hybris projects are imported into Eclipse
2. spartacussampledataaddon is not imported into Eclipse

## Expected Results
spartacussampledataaddon project is imported into Eclipse

## Repository Used
N/A

## Offer to Fix
NO

## Additional Information
spartacussampledataaddon does not have a .project file (which is also specified in .gitignore). So, it's not consdered as an Eclipse project

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/147
