### ISSUE TITLE
Spartacus running on nginx

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#6461]
To simplify installation and testing of spartacus, we will run it statically on nginx

- [ ] Prototype (spartacus runs on nginx, e2e smoke tests pass)
- [ ] Make sure dev servers have nginx
- [ ]  Update spartacus installation script
- [ ] Update ansible recipe to install on dev servers
- [ ] Make sure PWA works

**Comment by marlass** [comment]
We might not need it with the updated spartacus-installation script.

**Comment by marlass** [comment]
Obsolete issue.
