### ISSUE TITLE
Order details page as guest displays empty order

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#6480]
Endpoint for order details should redirect to the homepage when the user is not logged in.

Viewing orders as a guest user is not supported. If the guest would like to see his orders, he has to create an account.

**Original title for this ticket:** 
Guest Checkout Order Details are empty after order is completed

**Issue details:**

Complete the order process as via guest checkout and navigate to the following url with the order number indicated on the order confirmation page (eg. `http://localhost:4200/electronics-spa/en/USD/guest/order/00008364`).

Order Details page show no information:
![image](https://user-images.githubusercontent.com/11735817/74229429-a42cfe80-4cc2-11ea-8d71-ee1908487301.png)

**Comment by giancorderoortiz** [comment]
This issue needs to be caught by e2e tests. 
It seems function  verifyOrderConfirmationPageWithCheapProduct() in  /projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts is not doing what it must. 

Perhaps the "should" ought to be removed from:
cy.get('cx-cart-item .cx-code').should('contain', cheapProduct.code);

**Comment by hackergil** [comment]
I just discussed with the team.
- Viewing orders as guest is not supported. If the guest would like to see his orders, he has to create an account. 
- Downgrading this ticket to P2. This route should be protected. We will redirect order details to the homepage if the user is not logged in.

**Comment by giancorderoortiz** [comment]
I see. I was a bit confused. Agree with @hackergil . Redirect to homepage as done with old accelerator.

**Comment by qjimmy** [comment]
PR #6915

**Comment by Platonn** [comment]
✅ QA passed on branch `release/1.5.x` - guest order details redirects anonymous user to the login page

It still should me merged to `release/2.0.x` and `develop` (and to be QAd there).
