### ISSUE TITLE
[already fixed?] lazily load anonymous consent templates

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#6519]
At the moment, anonymous consent templates are always loaded upfront, even if consent has been given. This requires a backend call. The templates should only be fetched if the dialog component is triggered.

**Comment by tobi-or-not-tobi** [comment]
We might want to list this as part of #5077

**Comment by Xymmer** [comment]
asking Nik if it was done already

**Comment by znikola** [comment]
Done as part of https://github.com/SAP/spartacus/pull/8150
