### ISSUE TITLE
Applied Promotions documentation

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/spartacus#6521]

**Comment by gladius-mtl** [comment]
Hi @mszczepaniak 👋 
Is there a doc PR for this ticket? Or is no documentation required? 
If documentation is needed, can you create a ticket in the docs repo, and send me a PR when a draft is ready to look at? 🙂 
Here is the link for creating new tickets in the docs repo: https://github.com/SAP/spartacus-docs/issues/new
And if you need any info about working in the docs repo, there is this guide: https://github.com/SAP/spartacus-docs/blob/master/contributing_to_docs/developer-guide.md

Of course, you can always ask me if you have any questions as well 🙂

**Comment by gladius-mtl** [comment]
PR for the doc input is https://github.com/SAP/spartacus-docs/pull/610
PR has been merged.
