### ISSUE TITLE
ASM Customer Search functionality returns server error in Spartacus public instance

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#6545]
## Environment Details

- Spartacus:  Public Instance https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/
- Browser: Chrome

## Steps to Reproduce
- Enable ASM with the url query `?asm=true`
- Log into as an ASM agent and search for a customer (Type at least 3 characters)

## Observed Results
Global error message pops up saying a server error occured

<img width="1414" alt="Screen Shot 2020-02-13 at 2 42 33 PM" src="https://user-images.githubusercontent.com/30666844/74472772-74235e00-4e70-11ea-8a7c-9068285a98a0.png">

## Expected Results

It should display the list of results or it should display no user found in the list

**Comment by tobi-or-not-tobi** [comment]
I assume this is because the ASM module hasn't been installed on the backend. @hackergil can you confirm?

**Comment by Xymmer** [comment]
we'll make sure asm is working with big server update coming, so closing this one
