### ISSUE TITLE
Cart never gets loaded when using the new active-cart service.

### ISSUE THREAD

**Issue by CarlEricLavoie** [SAP/spartacus#6547]
If we don't use the now **deprecated** cart.service.ts, the inital cart never gets loaded. 
The active cart service has an additional check on the load() function which prevents the "current" cart from being loaded more than once. This check doesn't exist on the cart.service.ts and that means if we don't import the cart.service.ts an anonymous cart is not loaded.

## Environment Details

- Spartacus:  1.5.0-next.2

## Steps to Reproduce
Change mini-cart component for custom implementation that does not user **deprecated** cart.service.ts

## Observed Results
Cart is not loaded (item count / total not loaded)

## Expected Results
Cart should be loaded

**Comment by marlass** [comment]
I switched from CartService to ActiveCartService in mini cart component and everything is still loading correctly.
I'm just wondering why you want to load this cart multiple times? Why the one load is not enough? Each cart modification (add to cart/update entry, etc.) will trigger reloads.

Or in your case, the first load failed?

**Comment by Xymmer** [comment]
@CarlEricLavoie let us know

**Comment by CarlEricLavoie** [comment]
Hey guys, Sorry at this point we've completely changed our configuration and I can't reproduce this issue. I'll close this ticket and reopen with more details if we encounter this problem again.

**Comment by Xymmer** [comment]
thanks! closed
