### ISSUE TITLE
Add Address button is misaligned when there's only one button

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#6610]
**Environment Details**
Spartacus: epic/accessibility branch
Browser:  Chrome & Safari & Firefox
Device: mac
Happens on: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD

**Steps to Reproduce**
- Have a new user
- Go to MyAccount -> Address Book 

**Actual Result**
Scroll down and look at the "Add Address" button. 
Isn't it misaligned when there's only one button?

![66059212-a78cce00-e509-11e9-8316-c3f857673db5](https://user-images.githubusercontent.com/45409515/74744211-d93fd080-522f-11ea-94cf-6bb84b7719ec.png)

**Comment by dydome** [comment]
@Xymmer it looks like this is a deliberate procedure as there is added style: justify-content: flex-end;

This style property is also used in payment-method, payment-form, payment-type, shipping-address and address-form components. We should leave it or add different class and styles just for shipping-address component.
