### ISSUE TITLE
[Fixed in #7735] - Update cart for B2B (for non-multi-d products)

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#6636]
update/remove entries in cart.

**Comment by Xymmer** [comment]
Louis says in #7714:

After investigating these are my findings. To be able to add a product to cart the addEntries endpoint needs to be replace with the B2B one orgUsers/${userId}/carts/${cartId}/entries. Note multid products (like boots) create weird behavior in the cart even with the B2B endpoint. The cart will not show the multid product when any product is added to the cart until the page is refreshed. The entryNumber of all the multid products is -1.

Also to be taken into consideration, the GET cart from B2B only returns the current cart. This is very limiting compared to the regular cart endpoint. The regular GET cart seems to behave correctly even for B2B so it should be favored over it's B2B counterpart.

The update quantity and remove work out of the box.
For the delivery, the cart endpoint for the delivery address needs to be updated to PUT orgUsers/${userId}/carts/${cartId}/addresses/delivery.

**Comment by Xymmer** [comment]
How we do this depensd on #7759 but otherwise can be started

**Comment by Xymmer** [comment]
Affected by multi-d changes as well, so what we did is split this ticket:
This one is about updating cart an dcalls for normal products
Another ticket will be for special multi-d handling

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/7870
