### ISSUE TITLE
Coupon button hides focus indicator on iPhone7

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#6667]
![Screen Shot 2020-02-19 at 11 35 53 PM](https://user-images.githubusercontent.com/15113219/75007194-5f336580-5442-11ea-89d7-f423486833b3.png)

**Comment by giancorderoortiz** [comment]
Issue has been fixed. 
Retest with 3.0 and 3.4

(3.0)
Linux: https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/

(3.4) 
https://spartacusstore.cg79x9wuu9-eccommerc1-p5-public.model-t.myhybris.cloud/electronics-spa/en/USD/

Used iPhone7, Safari.
