### ISSUE TITLE
z-index layer conflict between mobile menu and pagination button

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#6668]
![Screen Shot 2020-02-19 at 11 38 56 PM](https://user-images.githubusercontent.com/15113219/75007371-e54fac00-5442-11ea-83a2-74091d36ac2d.png)

**Comment by Fonsu** [comment]
This issue does not seem to be present on develop since `PaginationComponent` has gone through major refactor.  Please retest.

**Comment by KateChuen** [comment]
was not able to reproduce it on tablet and mobile view, on desktop, pointing to dev10.

Will leave it to @developpeurweb to retry on a real device, pointing to dev10. 

But I believe this was fixed in #6060.

**Comment by KateChuen** [comment]
@developpeurweb confirmed it looks good now, pointing to dev10.

![Screen Shot 2020-04-01 at 10 33 24 AM](https://user-images.githubusercontent.com/45409515/78149834-72076580-7404-11ea-8721-16c47926e29a.png)
