### ISSUE TITLE
Readonly doesn't work on first render for quantity component

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#6690]
On the cart item list with read-only quantity component it could still be modified in the input field.

How to reproduce:
- got to last checkout step
- click the quantity value
- you can modify the value through normal input or with arrows

Desired behavior:
- can't change read-only values

**Comment by tobi-or-not-tobi** [comment]
seems a duplicate of #6180

**Comment by kacperknapik** [comment]
Fixed in #7339
