### ISSUE TITLE
Support relative path for Service Worker 

### ISSUE THREAD

**Issue by josecervera** [SAP/spartacus#6723]
I'm trying to set a reverse proxy with nginx, to serve the Spartacus app relative to a path.
I've changed the base-href in index.html, and built with

`ng build --prod --base-href=/mystore/`

It works for the most part, but there's an error trying to read ngsw-worker.js, as it is not relative to the given path.
I think the issue is in pwa.module.ts, using the same absolute syntax:
https://github.com/angular/angular-cli/issues/11848

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/10212

To test:

1. Run `yarn build:libs`
2. Run `yarn build --base-href=/mystore/`
3. In the dist, make sure in storefrontapp everything is in a folder called "mystore" **except** the `index.html`
4. Run `yarn start:pwa`
5. Visit http://locahost:4200, in the server console you should see a `..."GET /mystore/ngsw-worker.js"...` with no errors & in your browser network you should see the service worker gear
6. Stop the server, move the `ngsw-worker.js` next to the `index.html`
7. Restart the server, visit localhost, the service workers should still load (no server errors)
