### ISSUE TITLE
Fix aux tests for cx-navigation-ui after component refactor

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#6743]
Search for instances of `// TODO: ... (#6743)` and fix them after navigation-ui component refactor.

**Comment by kacperknapik** [comment]
`navigation-ui` component fix: #7206

**Comment by giancorderoortiz** [comment]
which e2e test cases were affected by this?

**Comment by Zeyber** [comment]
QA:
- Check for no more instances of `// TODO: ... (#6743`
- Check aux e2e tests pass

**Comment by psmul** [comment]
QA done. Test are passing as expected and no TODO instances found for this task number.
