### ISSUE TITLE
Homepage Label/ID should be dynamic

### ISSUE THREAD

**Issue by jongyunchoi-sap** [SAP/spartacus#6746]
## Environment Details

- Spartacus: 1.4.1
- Browser: N/A
- OS: N/A
- Device: N/A
- Other environment details: N/A

## Steps to Reproduce
On SAP Comerce, create a Content Page with Homepage flag `true` and label nor ID not being `homepage`, and browser to URL `/`.

## Observed Results
Spartacus tries to find homepage using `homepage` is label/ID.

## Expected Results
Spartacus finds the homepage using the right label/ID or the Homepage flag.

**Comment by Xymmer** [comment]
the logic related to this issue will be refactored for 3.0, but we'll investigate if this particular issue can be fixed sooner.

**Comment by tobi-or-not-tobi** [comment]
QA: 
- flag another content page as homepage (`page.homepage = true`) in the backoffice / SmartEdit. We've tested this with the contact page. 
- If not done automatically, mark the former homepage to false
- Ensure that the new page is showed up when you go to the root of Spartacus

limitations: 
- Only content pages can be marked as home page.
