### ISSUE TITLE
[MASTER] Image zoom on product page

### ISSUE THREAD

**Issue by reyhanehsalkhi** [SAP/spartacus#6757]
The image on product detail page should be zoomable.

**Comment by tobi-or-not-tobi** [comment]
Zoomed images can be done in various ways.
1. Hover the main image, and see a (masked) zoomed version
2. Click on an icon on top of /nexst to the main image, and get a zoomed image (often in a modal dialog)
3. Click anywhere on the main image, and get a zoomed version

In order tp provide maximum flexiblity for the customer without changing the component, we need 2 things:
1. trigger – An (icon) element on the main image that we can use to trigger the zoomed
2. zoom image – An IMG element next to the main image that holds the zoomed image

The trigger would use an icon from the ICON system (`IMAGE_ZOOM`). The trigger can be styled to support all 3 scenario's. 
The zoomed image (`IMG`) can be styled with CSS to get the right position, mask, etc.

**Comment by Xymmer** [comment]
duplciate of louis' new issues
