### ISSUE TITLE
Storefinder search icon works with mouse but NOT with keyboard

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#6766]
The magnifying glass icon receives focus when getting there by using the keyboard but nothing happens when pressing down the `ENTER` key while on the icon being focused, as opposed to clicking on it with the mouse, behaviour should be the same (like a submit button).

![Screen Shot 2020-02-28 at 9 08 21 PM](https://user-images.githubusercontent.com/15113219/75719599-0619cc00-5ca3-11ea-8c13-ccb72f81b08e.png)

**Comment by Matejk00** [comment]
Fixed in #6676

**Comment by Matejk00** [comment]
QA steps:
1. Go to storefinder.
2. Type something in a search input area.
3. Navigate using "Tab" key to search icon button and hit "Enter".

Expected result:
- Search action should be performed.

**Comment by mirkosoft** [comment]
QA passed.
