### ISSUE TITLE
Configurable trigger rules

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#6778]
In order to provide more flexibility towards opening the target dialog for triggers (i.e. addToCart dialog, consentDialog, etc), we need to come up with a mechanism to dynamically render the dialog. 

In this ticket we come up with a generic solution to render the target. Asm and skipLinks are already doing this individually, we want this to be generic for all dialogs. 

We need a configuration for the individual trigger(components) to look up the target information. 

```
config: {
	trigger: {
		addToCart: {
			outlet: 'cx-storefront`,
			pos: 'BEFORE'
		},
		consent: {
			url: cxRoute
		},
		closeAccount: {
			inline: true,
			pos: 'AFTER'
		}
	}
}
```

**Comment by LTiger14** [comment]
For QA: 

- Test that the ASM UI opens with the `?asm=true` parameter.
- Remove the parameter
- Refresh, asm should still be open
- Close it with the X
- Refresh, asm should be closed
