### ISSUE TITLE
HTML lang iso should use hyphen instead of underscore

### ISSUE THREAD

**Issue by ghost** [SAP/spartacus#6802]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  1.4.1
- Browser:  N/A
- OS: N/A
- Device: N/A
- Other environment details: N/A

## Steps to Reproduce
Create a site whose default language ISO consists of both language and region codes e.g. `es_MX`

## Observed Results
Rendered page has `<html lang="es_MX">` (by `htmlLangProvider`), using the Java locale ISO format.

## Expected Results
The underscores are replaced by hyphens `<html lang="es-MX">` to conform to the [RFC-5646](http://www.rfc-editor.org/rfc/rfc5646.txt).

**Comment by Xymmer** [comment]
We get this value from backend
Simple change to do
Kris to double-check with Tobias to be sure

**Comment by Platonn** [comment]
Very simple: replace all `_` ---> `-` in the `lang` variable here:
https://github.com/SAP/spartacus/blob/feature/GH-4646/projects/storefrontlib/src/cms-structure/seo/html-lang-provider.ts#L20

**Comment by ghost** [comment]
@Platonn I had opened a PR for this. https://github.com/SAP/spartacus/pull/6813

**Comment by Platonn** [comment]
Thanks @jongyunchoi-sap! Please mind to follow our commit guidelines in the merge-commit message (so we can automaticaly generate a changelog entry from your fix):  
https://sap.github.io/spartacus-docs/commit-guidelines/
PS. Don't hesitate to add `BREAKING CHANGE:` note 😉
