### ISSUE TITLE
Icon type driven CSS classes are not cleared when the icon type is changed

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#6818]
When icons are changed, the former CSS classes are not removed from the host element. This results in duplicated CSS classes, which doesn't update the icon font as one of the classes takes precedence. 

This is seen at the facet navigation when a facet group is toggled.

**Comment by tobi-or-not-tobi** [comment]
QA
- open listing page
- toggle facet groups
- confirm that the collapse/expand icon is changed when the  group is collapsed/expanded

**Comment by KateChuen** [comment]
Tested on dev10. 
- collapse/expand groups work.
![Screen Shot 2020-03-06 at 9 35 18 AM](https://user-images.githubusercontent.com/45409515/76110788-27353200-5fad-11ea-86c1-f1cf1106e7fe.png)
![Screen Shot 2020-03-06 at 9 36 26 AM](https://user-images.githubusercontent.com/45409515/76110790-27cdc880-5fad-11ea-9e0b-c88903c0f20f.png)
![Screen Shot 2020-03-06 at 9 40 09 AM](https://user-images.githubusercontent.com/45409515/76110792-27cdc880-5fad-11ea-8f23-92d953e046eb.png)

- collapse/expand facet groups are saved when going from one plp to another, so for eg, from webcams to all digital cameras to all accessories, to camcorders, to film cameras.

- however, it's not saved when going to brands(canon for eg). Is that intended or an issue?

**Comment by tobi-or-not-tobi** [comment]
@KateChuen thanks for the review. The current behaviour doesn't persist the _UI state_ for the expanded facet groups, but we do this actually in #6581. 

I guess you can move this to done now?
