### ISSUE TITLE
[depends on 6839] Failing E2E: Wishlist

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6820]
Wishlist e2e test is failing on `develop` branch and `dev-17`.

File: regression/wish-list.e2e-spec.ts
```
  7 passing (57s)
  1 failing

  1) Wish list checkout should add product to cart, to wish list and checkout:
     CypressError: Timed out retrying: cy.click() failed because this element is disabled:

<button class="btn btn-block btn-primary" disabled="">Continue</button>

Fix this problem, or use {force: true} to disable error checking.
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console and #6157.

**Comment by bgambocjaviniar** [comment]
related to the button being disabled found here https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6839

will fix itself once above is done
