### ISSUE TITLE
Failing E2E: Applied promotions

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6823]
Applied promotions e2e test is failing on `develop` branch and `dev-17`.

File: regression/applied-promotions.e2e-spec.ts  
```
 7 passing (31s)
  1 failing

  1) Applied promotions Applied promotions as a logged user Should verify promotions in order confirmation details:
     CypressError: Timed out retrying: Expected to find element: '.cx-item-list-row', but never found it.
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console and #6011.

**Comment by bgambocjaviniar** [comment]
PR: GH-6895

**Comment by bgambocjaviniar** [comment]
As mentioned in the spa e2e chat, I will remove myself as the order-history retry function is found in the my-coupons e2e PR

feel free to re-use the PR, or create a new one!
