### ISSUE TITLE
Failing E2E: Product details

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6824]
Product details e2e tests are failing on `develop` branch and `dev-17`.

File: regression/product-details.e2e-spec.ts 
```
 10 passing (2m)
  8 failing
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console and #6464.

**Comment by bgambocjaviniar** [comment]
PR: GH-6894
