### ISSUE TITLE
Failing E2E: My coupons

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6825]
My coupons e2e tests are failing on `develop` and maintenance pointed to `dev-17`.

File: mobile/my-coupons/my-coupons-mobile.e2e-spec.ts 
```
7 passing (1m)
  1 failing

  1) 576p resolution - My coupons test for pagination and sort should page and sort my coupon list:
     CypressError: Timed out retrying: expected '<span.card-label-bold.cx-coupon-card-id>' to contain 'dragonboat'
```

File: regression/my-coupons/my-coupons.e2e-spec.ts 
```
  6 passing (1m)
  2 failing
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console and https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/52/consoleFull 

Also: #6465.

**Comment by LTiger14** [comment]
There is already ticket #6465 that will take care of it.
