### ISSUE TITLE
Failing E2E: Checkout-as-persistent-user

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6826]
Checkout e2e tests are failing on `develop` and maintenance pointed to `dev-17`.

File: regression/checkout/checkout-as-persistent-user.e2e-spec.ts 
```
 8 passing (1m)
  4 failing
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console and https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/52/consoleFull.

flaky it fails at times (known issue and being worked on from someone on the maintenance branch

**Comment by bgambocjaviniar** [comment]
duplicate GH-6696
