### ISSUE TITLE
Failing E2E: CDS

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6828]
CDS e2e tests are failing on `develop` branch and `dev-17`.

File: vendor/cds/profile-tag.e2e-spec.ts  
```
  0 passing (16s)
  1 failing

  1) Profile-tag component "before each" hook for "should send a Navigated event when a navigation occurs":
     CypressError: Timed out retrying: Expected to find element: 'cx-profiletag', but never found it.
```

File: vendor/cds/merchandising-carousel.e2e-spec.ts
```
  0 passing (8m)
  28 failing
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests/868/console.

**Comment by bgambocjaviniar** [comment]
https://sap-cx.slack.com/archives/GSZNFM99A/p1582728790013600
