### ISSUE TITLE
Failing E2E: Payment methods

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#6829]
Payment methods e2e tests are failing on maintenance pointed to `dev-17`.

File: regression/my-account/payment-methods.e2e-spec.ts 
```
 3 passing (1m)
  3 failing

  1) Payment Methods Authenticated user should add a second payment method:
     CypressError: Timed out retrying: Expected to find element: 'cx-review-submit', but never found it.
```
For more details please follow: https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-maintenance/52/consoleFull and #6152.

**Comment by LTiger14** [comment]
There is already a ticket for payment methods in review #6152.
