### ISSUE TITLE
Tree Component

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6835]
Please discuss with @tobi-or-not-tobi or Anthony about tree component decision

Depends on: #6544

**Comment by psmul** [comment]
There's a problem with accessibility on mobile devices. When we go to unit branch, focus with tabindex is not resetting, causing focus to appear on second or third position instead of first.

**Comment by psmul** [comment]
After some discussion with @Zeyber, re-assessment of functionality will be done and after that, we'll decide how to proceed wit a11y and SEO.
