### ISSUE TITLE
Spartacus.sh script not updated. NG9

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#6856]
It seems the Spartacus deployment script has not been updated and it's failing with miscellaneous errors such as: 

"node_modules/@spartacus/core/src/window/window-ref.d.ts:5:9 - error TS1086: An accessor cannot be declared in an ambient context.
5     get nativeWindow(): Window;
          ~~~~~~~~~~~~
node_modules/@spartacus/core/src/window/window-ref.d.ts:6:9 - error TS1086: An accessor cannot be declared in an ambient context.
6     get sessionStorage(): Storage;
          ~~~~~~~~~~~~~~

https://github.tools.sap/cx-commerce/spartacus-installation/blob/develop/spartacus.sh

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-03-09 at 12 18 49 PM](https://user-images.githubusercontent.com/46171897/76249460-bfcfea00-6219-11ea-87a7-f877f325b794.png)

**Comment by giancorderoortiz** [comment]
Is there a workaround while script is being fixed?

**Comment by hackergil** [comment]
Templates for script need to be updated with the latest angular libs, typescript version, etc. (same as the storefrontapp ones)
files/package.json

Maybe there are some changes also in
files/app.module.ts

**Comment by marlass** [comment]
You could check 2.0 branch on installation script repository. That should help.

Also I did some groundwork for schematics only spartacus-installation in v2 branch. I still want to polish some things there after 2.0 release, but that should make maintenance of this script easier and also support for running multiple types of deployment at the same time (ssr, only client side, pwa)

**Comment by hackergil** [comment]
@marlass +1 about polishing and simplifying, thanks
@giancorderoortiz I pushed a fix. Please give it a try.

**Comment by Xymmer** [comment]
is this done, can we close?

**Comment by marlass** [comment]
Yes. We can close this one. We have other tickets to fix it.
