### ISSUE TITLE
NavigationUIComponent doesn't allign nav to the right if stick out

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#6899]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  
- Browser: Chrome 80.0.3987.132
- OS: Windows 10
- Device: 
- Other environment details: 

## Steps to Reproduce
Place ``CustomSiteLogin`` slot with ``cx-navigation component`` for "My Account" element somewhere on the right side, just next to the window right border. After page reloads, window size has overflowed, and we can see the bottom horizontal scroll. Once you hover 'My Account' element, '`cx-navigation-ui`' will appear with user account available pages like: 'order history', 'password' or 'logout'. Because this element has css class visibility it resized body content and the horizontal scroll is available.

## Observed Results

Wrongly implemented ``alignWrappersToRightIfStickOut`` on component constructor.

Image with an example:
[Screenshot](https://imgur.com/a/S89qpEv)

## Expected Results
Nav wrapper will align to the right border if stick out.

## Repository Used
Master branch

## Offer to Fix
At first value: ``allowAlignToRight`` should be as a default set to true. Than method, ``alignWrappersToRightIfStickOut`` should be run on the beginning of the component lifecycle, but even if we put it to ``ngAfterViewInit`` it is too early. In debugging I had to set timeout.

**Comment by kacperknapik** [comment]
Potentially fixed in #7206

**Comment by kacperknapik** [comment]
This is NOT fixed in #7206
