### ISSUE TITLE
Cms page data loaded twice during the first visit

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#6900]
During the first visit in spartacus storefront the CMS page data is loaded twice for no good reason. It should be loaded once.

The bug is caused by `pageRefresh$` effect triggered on the langauge change. But cms data shouldn't be reloaded when the language is set for the first time.

How to reproduce:
1. Open chrome dev tools in the Network tab and filter only requests mathing the pattern `pages? method:GET`
2. Open spartacus home page by link (or refresh)
3. Verify that the call is made twice
![image](https://user-images.githubusercontent.com/4001059/76533171-f0ad5a80-6477-11ea-9163-dc0b31fdd6ac.png)

Expected result:
3* Call is made once

**Comment by Platonn** [comment]
I guess this bug has been there for a couple of versions and looks bad for performance. That's why it's a SHOULD for 2.0

**Comment by Platonn** [comment]
It requires some breaking changes to fix. So  it would be good to fix it before RC.

**Comment by Platonn** [comment]
## QA steps
1. Verify that the CMS backend call for endpoint `/pages?` is made only once on the initial page visit 
2. Moreover we need to test that the call for CMS page is made again when we change the language using the language selector (in the top left corner menu)

There are many combinations of configuration and user journeys that that we need to test. For each `CONFIGURATION VARIANT` please `VERIFY THAT` it's working `WHEN YOU` follow an user's journey:

![image](https://user-images.githubusercontent.com/4001059/80401976-7fa5f300-88bd-11ea-821d-74775d93d479.png)

**Comment by kacperknapik** [comment]
**QA results**
- only one call visible in all scenarios
