### ISSUE TITLE
Cannot send request for partial order cancellation

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#6909]
Place an order with several entries. Open the "Cancel Order" page, and cancel some products in one entry. Go to "Cancel Order Confirmation" page, the `Submit Request` button is disabled. 

![Screen Shot 2020-03-13 at 9 34 22 AM](https://user-images.githubusercontent.com/44440575/76627874-36b6fc80-6512-11ea-9d35-1e09645b187a.png)

Click `back` button to back to "Cancel Order" page, cannot update the quantity set in previous step; and "Continue" button is disabled as well.

![Screen Shot 2020-03-13 at 9 34 31 AM](https://user-images.githubusercontent.com/44440575/76627936-51897100-6512-11ea-9a9b-9bbcde5527c8.png)

**Comment by Xymmer** [comment]
To repro and if indeed it's still happening, fix
Reminder that cancel/returns only works with 2005 release
