### ISSUE TITLE
Do a complete order cancellation for an order with promotion, the total value is less than 0

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#6910]
Do a complete order cancellation for an order with promotion. After it is done, the total value is less than 0.
![Screen Shot 2020-03-13 at 9 34 57 AM](https://user-images.githubusercontent.com/44440575/76628212-c2c92400-6512-11ea-86a8-4849c8ed6048.png)

![Screen Shot 2020-03-13 at 9 41 02 AM](https://user-images.githubusercontent.com/44440575/76628218-c65cab00-6512-11ea-9fc7-c489a10a085d.png)

**Comment by WeizhengSap** [comment]
This may be caused by backend.

**Comment by Xymmer** [comment]
Bill to follow up if this happens in 1905 and 2005 releases, for api's

**Comment by Xymmer** [comment]
will fix in https://jira.hybris.com/browse/C3PO-2219

**Comment by Xymmer** [comment]
can't be fixd in spartacus, but the backen code used is mock anyway.
