### ISSUE TITLE
Diagnose warnings with exporting duplicate symbols while building libraries

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#6920]
While compiling librareis with ViewEngine we get some warnings: 

- WARNING: Conflicting namespaces ...
- WARNING: Non-existent export ...

They are not showing up where compiling with Ivy.
We should double-check if we are OK with them and if it is possible to disable them.

**Comment by hackergil** [comment]
We are now only compiling with Ivy, so closing this one
