### ISSUE TITLE
Update documentation for anonymous consent to explain current behavior

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#6923]
Relating to this https://github.com/SAP/cloud-commerce-spartacus-storefront/issues/6467
and as requested

**Comment by bgambocjaviniar** [comment]
DOC PR: https://github.com/SAP/cloud-commerce-spartacus-storefront-docs/pull/536

**Comment by gladius-mtl** [comment]
PR reviewed and merged.
