### ISSUE TITLE
My Company e2e tests - skelet + tests

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6939]
prepare generic solution for easier testing a11y and functionality of pages like:
- [x] details page
- [x] form (create/edit)
- [x] listing

### Tests to be done
- [x] Budgets
- [x] Cost Centers
- [x] User Groups

**Comment by Matejk00** [comment]
On hold till we figure out if any UI changes are needed.

**Comment by Zeyber** [comment]
Was unmerged do to red regression pipeline. Need to remerge after dev0 is updated with sample data.
