### ISSUE TITLE
QA Users  functionality not covered by E2E

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6942]
Test matrix is:
https://cxwiki.sap.com/display/spar/Test+Matrix+for+B2B+My+Company
We'll highlight what isn't yet covered by E2E here

**Comment by psmul** [comment]
Based on provided matrix, users.e2e aren't covering listed topics below:
- User entity can disabled/deleted
- User password can be changed
- No tests for any of sub category

**Comment by Xymmer** [comment]
Caine says the only E2E left is #9804, admin changes their own password
I tested it manually, all fine, closing
