### ISSUE TITLE
QA Spend Permissions functionality not covered by E2E

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6948]
Test matrix is:
https://cxwiki.sap.com/display/spar/Test+Matrix+for+B2B+My+Company
We'll highlight what isn't yet covered by E2E here

**Comment by Matejk00** [comment]
Based on provided matrix, purchase limits e2e aren't covering listed topics below:

- create/details/edit -> Limit per timespan: amount, currency, time period
- create/details/edit -> Limit per order: amount, currency
- enable/disable purchase limit

**Comment by Matejk00** [comment]
E2Es cover all scenarios in test matrix.
