### ISSUE TITLE
Purchase Limits E2E tests

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6949]
Purchase Limits have extra form fields that are not handled in `my-company-form.ts` cases. That is why Purchase Limits are not finished by #6939.

**Comment by Zeyber** [comment]
Will be closed by #6939

**Comment by Zeyber** [comment]
Removed this from the scope of #6939

**Comment by Matejk00** [comment]
Based on provided matrix, purchase limits e2e aren't covering listed topics below:

- create/details/edit -> Limit per timespan: amount, currency, time period
- create/details/edit -> Limit per order: amount, currency
- enable/disable purchase limit
