### ISSUE TITLE
Improve breakpoint service

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#6960]
While using javascript for breakpoint specific layout is generally discouraged, there are some edge cases where this is needed. Therefor we like to offer a few features to observe the breakpoint in relation to the screen size:
- isUp – Indicates whether the given breakpoint is equal or larger than the window size
- isDown – Indicates whether the current screen size is larger than the minimum size of the given breakpoint
- isEqual – Indicates whether the current screen size fits to the given breakpoint

While we're on this, we indicated that the `BreakpointService` actually contains a glitch that we've (accidentally) hidden by providing an incorrect layout configuration for the page layout. It's a small issue, but confusing, and with extending the BreakpointService it's time to fix this.

**Comment by KateChuen** [comment]
Can you add QA steps please?

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- validate the storefront in desktop, tablet, mobile and verify that the UI looks business as usual
- observe the new `isUp`, `isDown` and `isEqual` methods in custom code:

```typescript

constructor(
    private breakpointService: BreakpointService
  ) {
    this.breakpointService
      .isDown(BREAKPOINT.xs)
      .subscribe(down => console.log('down:xs', down));
    this.breakpointService
      .isDown(BREAKPOINT.sm)
      .subscribe(down => console.log('down:sm', down));
    this.breakpointService
      .isDown(BREAKPOINT.md)
      .subscribe(down => console.log('down.md', down));
    this.breakpointService
      .isDown(BREAKPOINT.lg)
      .subscribe(down => console.log('down.lg', down));
    this.breakpointService
      .isDown(BREAKPOINT.xl)
      .subscribe(down => console.log('down.xl', down));

    this.breakpointService
      .isUp(BREAKPOINT.xs)
      .subscribe(up => console.log('up:xs', up));
    this.breakpointService
      .isUp(BREAKPOINT.sm)
      .subscribe(up => console.log('up:sm', up));
    this.breakpointService
      .isUp(BREAKPOINT.md)
      .subscribe(up => console.log('up.md', up));
    this.breakpointService
      .isUp(BREAKPOINT.lg)
      .subscribe(up => console.log('up.lg', up));
    this.breakpointService
      .isUp(BREAKPOINT.xl)
      .subscribe(up => console.log('up.xl', up));

    this.breakpointService
      .isEqual(BREAKPOINT.xs)
      .subscribe(eq => console.log('eq:xs', eq));
    this.breakpointService
      .isUp(BREAKPOINT.sm)
      .subscribe(eq => console.log('eq:sm', eq));
    this.breakpointService
      .isUp(BREAKPOINT.md)
      .subscribe(eq => console.log('eq.md', eq));
    this.breakpointService
      .isUp(BREAKPOINT.lg)
      .subscribe(eq => console.log('eq.lg', eq));
    this.breakpointService
      .isUp(BREAKPOINT.xl)
      .subscribe(eq => console.log('eq.xl', eq));
  }
```

**Comment by Zeyber** [comment]
Storefront page looks the same in desktop/tablet/mobile screen widths as before.

Full desktop-width reports:
```
down:xs false
down:sm false
down.md false
down.lg false
down.xl true
up:xs true
up:sm true
up.md true
up.lg true
up.xl true
eq:xs false
eq:sm false
eq.md false
eq.lg false
eq.xl true
```

Tablet width:
```
down:xs false
down:sm false
down.md true
down.lg true
down.xl true
up:xs true
up:sm true
up.md true
up.lg false
up.xl false
eq:xs false
eq:sm false
eq.md true
eq.lg false
eq.xl false
```

Mobile width:
```
down:xs true
down:sm true
down.md true
down.lg true
down.xl true
up:xs true
up:sm false
up.md false
up.lg false
up.xl false
eq:xs true
eq:sm false
eq.md false
eq.lg false
eq.xl false
```

These seem to be correct.

**Comment by Zeyber** [comment]
> QA steps:
> 
> * validate the storefront in desktop, tablet, mobile and verify that the UI looks business as usual
> * observe the new `isUp`, `isDown` and `isEqual` methods in custom code:
> 
> ```ts
> constructor(
>     private breakpointService: BreakpointService
>   ) {
>     this.breakpointService
>       .isDown(BREAKPOINT.xs)
>       .subscribe(down => console.log('down:xs', down));
>     this.breakpointService
>       .isDown(BREAKPOINT.sm)
>       .subscribe(down => console.log('down:sm', down));
>     this.breakpointService
>       .isDown(BREAKPOINT.md)
>       .subscribe(down => console.log('down.md', down));
>     this.breakpointService
>       .isDown(BREAKPOINT.lg)
>       .subscribe(down => console.log('down.lg', down));
>     this.breakpointService
>       .isDown(BREAKPOINT.xl)
>       .subscribe(down => console.log('down.xl', down));
> 
>     this.breakpointService
>       .isUp(BREAKPOINT.xs)
>       .subscribe(up => console.log('up:xs', up));
>     this.breakpointService
>       .isUp(BREAKPOINT.sm)
>       .subscribe(up => console.log('up:sm', up));
>     this.breakpointService
>       .isUp(BREAKPOINT.md)
>       .subscribe(up => console.log('up.md', up));
>     this.breakpointService
>       .isUp(BREAKPOINT.lg)
>       .subscribe(up => console.log('up.lg', up));
>     this.breakpointService
>       .isUp(BREAKPOINT.xl)
>       .subscribe(up => console.log('up.xl', up));
> 
>     this.breakpointService
>       .isEqual(BREAKPOINT.xs)
>       .subscribe(eq => console.log('eq:xs', eq));
>     this.breakpointService
>       .isUp(BREAKPOINT.sm)
>       .subscribe(eq => console.log('eq:sm', eq));
>     this.breakpointService
>       .isUp(BREAKPOINT.md)
>       .subscribe(eq => console.log('eq.md', eq));
>     this.breakpointService
>       .isUp(BREAKPOINT.lg)
>       .subscribe(eq => console.log('eq.lg', eq));
>     this.breakpointService
>       .isUp(BREAKPOINT.xl)
>       .subscribe(eq => console.log('eq.xl', eq));
>   }
> ```

Note: The last section needs to be changed from `.isUp` to `.isEqual`
