### ISSUE TITLE
My company threat modeling

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#6974]

**Comment by giancorderoortiz** [comment]
First Threat modelling found the following critical issues: 
https://github.com/SAP/spartacus/issues/8026
https://github.com/SAP/spartacus/issues/8025

An E2E Test is needed to confirm access is restricted to b2b pages. 
https://github.com/SAP/spartacus/issues/8028

**Comment by giancorderoortiz** [comment]
Will conduct an additional security pass over the next few days before final check with Michael.

**Comment by kacperknapik** [comment]
Can this be moved to done? @Pucek9 @giancorderoortiz

**Comment by giancorderoortiz** [comment]
No. Security issues still pending verification.

**Comment by Xymmer** [comment]
closed as new tickets opened
2/3 tickets already done, last one in to do
