### ISSUE TITLE
getActive() method from ActiveCartService not getting empty after order confirmation

### ISSUE THREAD

**Issue by rayson20** [SAP/spartacus#6979]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  1.5.0
- Browser: Chrome, Version 80.0.3987.132
- OS: Mac
- Other environment details: Angular 8

## Steps to Reproduce
1. Add a cart
2. Go to cart
3. Go to the checkout page
4. Click Place Order (Will redirect to the Order Confirmation Page)
5. In Order Confirmation Page, Click to the cart page.

## Observed Results

the getActive() method from ActiveCartService is still returning the previous cart and getActiveCartId() also getting the previous cart id

## Expected Results
getActive() should get the new active cart which is empty cart and getActiveCartId() will return the new cart ID

## Repository Used
N/A

## Offer to Fix
NO
## Additional Information
However, when I go to the cart page after the order confirmation page and reload the page again. it will now get the empty cart but will show an error "Cart not found." since he is getting the previous cart ID.

slack thread: https://spartacus-storefront.slack.com/archives/CD16V16FR/p1584614533341800

**Comment by Xymmer** [comment]
@marlasak has this problem been resolved with the 2.0 cart udpates?

**Comment by marlass** [comment]
Haven't check yet. Let's leave it until we are sure it is working correctly.

**Comment by marlass** [comment]
I wasn't able to reproduce this bug on 1.5 release as well as on 2.0 release.

@rayson20 Do you still have this issue?
