### ISSUE TITLE
Bug: carousel slides takes incorrect height when last slide is smaller (1.5 broken)

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#6980]
This template is to be used for bug reports and small enhancements. For feature requests, please contact the project owner.

Note: For the bug to be accepted, it must be reproducible using the latest release of Spartacus. See our [Contributor Documentation](CONTRIBUTING.md) for more information.

## Environment Details

- Spartacus:  v1.4
- Browser: Chrome
- OS: Mac
- Device: Mac
- Other environment details: Responsive bug

Div.slides takes in consideration just the height of last slide

![image](https://user-images.githubusercontent.com/17834635/77064438-c90e4300-69df-11ea-8ee2-065f47e03ac5.png)

## Steps to Reproduce
Last slide is smaller than the rest 

/div class="slides"/
..../div class="slide"/normal content/div/
..../div class="slide"/normal content/div/
..../div class="slide"/normal content/div/
..../div class="slide"/**small content**/div/
/div/

## Observed Results

Overflow in carousel slides

## Expected Results
The <div class="slides"> get height of higher children or change dynamically

## Offer to Fix
Yes https://github.com/SAP/cloud-commerce-spartacus-storefront/pull/7000

**Comment by KateChuen** [comment]
Evaluate the fix and backport to 1.5 and fix in 2.0 as well.

**Comment by Matejk00** [comment]
QA steps:
Check if text from product carousel slides does not overlap other elements.

This fix should be checked on:
- [x]  1.5 version `release/1.5.x`
- [x]  2.0 version `release/2.0.x`
- [x]  2.1 version `develop`

**Comment by Zeyber** [comment]
QA: Not seeing pictures in `1.5.x`. Other branches are fine.

**Comment by Matejk00** [comment]
Fix merged, ready to re-check on `release/1.5.x` branch.

**Comment by mszczepaniak** [comment]
Tested successfully
