### ISSUE TITLE
chore: update schematics - improve component deprecation migration script

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#7010]
Before modifying html template file, we should first check if the component.ts is inheriting a Spartacus component. If the condition is satisfied we should only then apply changes to the template.

**Comment by mirkosoft** [comment]
Once this is done let's re-apply/re-check code commented out with the below commit:
https://github.com/SAP/spartacus/pull/6799/commits/add17e3a47c8e02f95b29cdc5f57bca157cf1209
and delete the `feature/GH-6166` branch.
