### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError after adding a product second time into the cart

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7014]
## Steps to Reproduce
1. Open PDP, i.e. http://localhost:4200/electronics-spa/en/USD/product/358639/DSC-N1
2. Add item to cart
3. *In the modal* click `[+]` button to increment the quantity

## Observed Results
The error appears in the console:
![image](https://user-images.githubusercontent.com/4001059/77338030-077e6780-6d2a-11ea-9aff-d4ee21107833.png)

## Expected Results
No error occurs in the console

## Additional information
Alternative way to reproduce:
1. Go to PDP
2. Add item to cart
3. Close the modal
4. Add item again to the cart

**Comment by Xymmer** [comment]
Set to 2.1 must but we'll discuss if it should be 2.0 to be sure

**Comment by Platonn** [comment]
After discussion with Tobias, I change it to 2.0 must.

**Comment by Platonn** [comment]
### QA steps:
1. Open the console 
2. Play with the item counter (quantity box), try values: min, max, intermediate and outside of range (those should be automatically corrected); and:
   - [x] verify it works OK
   - [x] the disabled state of input and +/- buttons is OK
   - [x] no redundant backend calls are made to update quantity when not needed
   - [x] no ExpressionChanged...Error occurs in the console.
3. Repeat (2) in the following places
   - [x] PDP
   - [x] "Added to cart modal"
   - [x] Cart page
   - [x] Checkout review (last checkout step) page
