### ISSUE TITLE
Duplicate footer notice

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7016]
![image](https://user-images.githubusercontent.com/6259079/77349441-4f59ba80-6d3b-11ea-916a-cecdb2235e2c.png)

With anonymous consents disabled there is a double notice in the footer.

**Comment by znikola** [comment]
We can close this issue, as it's explained in the docs: https://sap.github.io/cloud-commerce-spartacus-storefront-docs/anonymous-consent in the `Footer notice` section how to avoid this.

**Comment by znikola** [comment]
Now that we've remove the anonymous consents feature flag, this issue has re-appeared. Reopening the ticket.

**Comment by znikola** [comment]
Sample addon PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/84
Docs update PR: https://github.com/SAP/spartacus-docs/pull/566
PR: https://github.com/SAP/spartacus/pull/7376

**Comment by LTiger14** [comment]
QA done no duplicate footer notice anonymous consents work as before.
