### ISSUE TITLE
Cleanup in cart actions

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7030]

**Comment by Pucek9** [comment]
As Linda Wolf (12341234) I can't click "remove" / "save for later" / increase / decrease count of items in cart
![image](https://user-images.githubusercontent.com/8040837/79777772-08f67c00-8338-11ea-8661-8e9767856d5b.png)

For other users it can be done

**Comment by Pucek9** [comment]
Idk is it related to cart, but it occur when I go directly from cart to category (e.g Webcams) 
![image](https://user-images.githubusercontent.com/8040837/79778078-7b675c00-8338-11ea-8f45-7ae170dfe4f8.png)

**Comment by Pucek9** [comment]
sQA done
