### ISSUE TITLE
Support lazy loadable components in CMS mapping

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7035]
Provide support for using dynamic import for cms mapping

**Comment by dunqan** [comment]
QA steps:
1. Create simple component in shell app (using schematics `ng g component` for example )
2. Assign this component to any component in cms mapping using dynamic import, for example:
```
        BreadcrumbComponent1: {
          component: () =>
            import('./llcmp/llcmp/llcmp.component').then(
              (m) => m.LlcmpComponent
            ),
        },
```
3. Check if component is displayed properly and if related chunk is loaded lazily

**Comment by Platonn** [comment]
✅  It works on a fresh shell app.
