### ISSUE TITLE
Create separate entry points for cms components.

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7045]
To support lazy loading components or modules from libraries we need to provide separate entry points in those libraries.

We can consider doing it for:
- individual cms components
- modules with cms components
- groups of cms components

**Comment by Xymmer** [comment]
still 2.1 stretch?

**Comment by dunqan** [comment]
Closing as the effort become part of specialized tickets, related to lazy loading and library reorg (including #7959)
