### ISSUE TITLE
Remove deprecations in authentication token services

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7046]
Cover deprecations in the following files:
- projects/core/src/auth/services/user-authentication/user-authentication-token.service.ts
```
  /**
   * @deprecated since version 1.1
   * Use constructor(http: HttpClient, config: AuthConfig, occEndpointsService: OccEndpointsService) instead
   */
```

- projects/core/src/auth/services/client-authentication/client-authentication-token.service.ts  
```
  /**
   * @deprecated since version 1.1
   * Use constructor(http: HttpClient, config: AuthConfig, occEndpointsService: OccEndpointsService) instead
   */
```

**Comment by mirkosoft** [comment]
Closing this as it's already covered in the following PR:
https://github.com/SAP/spartacus/pull/6926/
