### ISSUE TITLE
Remove deprecation in product list components

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7047]
Cover deprecations in the following files:

- projects\storefrontlib\src\cms-components\product\product-list\container\product-list.component.ts `* @deprecated since version 1.x`

- projects\storefrontlib\src\cms-components\product\product-list\container\product-scroll
product-scroll.component.ts `* @deprecated at release 2.0.`

**Comment by psmul** [comment]
QA done. Migrations for those deprecations works as intended.
