### ISSUE TITLE
Remove deprecation in page slot component

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7054]
Applies to:

- projects\storefrontlib\src\cms-structure\page\slot\page-slot.component.ts
```
   * @deprecated we'll stop supporting this property in 2.0 as
   * @deprecated since version 1.4
```

**Comment by tobi-or-not-tobi** [comment]
I start working on this without knowing jimmy start working on this. I'm doing some refactoring on the way as well.

**Comment by tobi-or-not-tobi** [comment]
QA:
- Ensure that page slots are rendered. That's basically the case for each and every page. This was a refactor.

**Comment by KateChuen** [comment]
✅Looks ok. Tested on dev10 on chrome, firefox, safari.
