### ISSUE TITLE
E2E - specific issues with a 2005 version environment 

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7071]
## Context
Issue is related to specific errors found in the e2e that runs against an environment with version 2005. Dev-com 19 was used as a test in the `feature/b2b-e2e-maintenance` branch. The newly created job in jenkins `spartacus-regression-tests-b2b` is running against the `feature/b2b-e2e-maintenance` branch.

## Specific errors
- [ ] Store finder API /stores request on queries, such as searching for japan. Returns nothing in dev19, but in dev17, it returns values.

## Other errors to fix to lower rate of failure
- [ ] Sample data difference like prices and product names (asserting a hardcoded data from the 1905.11 environment)
- [ ] test-data.impex was not injected to the server (devcom 19), therefore creating some e2e errors like myinterest, consignment-tracking, and others.
- [x] orders placed error (order-history not existing) - should be fixed once PR gets in

**Comment by hackergil** [comment]
These have been fixed.
