### ISSUE TITLE
Refactor component wrapper directive

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7080]
We should do it before implementing #7035

**Comment by dunqan** [comment]
QA steps:
1. Verify if cms components are instantiated properly with proper cms data
2. Verify if cms web components works

   - example cms web component implementations: https://github.com/tobi-or-not-tobi/spartacus-bootcamp/pull/15/files

**Comment by Matejk00** [comment]
QA done. 

During QA following errors were found in a console.
![QA_7080](https://user-images.githubusercontent.com/6958810/80346356-e3530080-886a-11ea-8113-d7aabe57405c.png)

After conversation with @dunqan seems that errors are not related with scope of this task.
