### ISSUE TITLE
CART CHANGE event implementation

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7086]
The main purpose of this event is to be usable for tag managers.

This event should happen after the que of pending processes on cart is done and cart is reloaded. The payload of this event should contain the list of the reasons of change (names of granular events/processes that affected the cart) and the value of the latest cart. Ideally we could add to the paylaod also the previous cart.
Reasons could bechange in: entry (add, remove, update) and voucher (add, remove). 

Implementation detail actions (or occ-specific actions) should not be reflected in the CartChangeEvent - i.e. create cart, load cart.

However we should concider whether the merge cart isn't a good reason to dispatch a change cart event (since some entries be added thans to merging with anonymous cart)

**Comment by Platonn** [comment]
For extendability, it would be good to allow customers to plug also custom events to affect the generic "cart change event".

**Comment by znikola** [comment]
Note: as we're going to remove ngrx from the cart lib, these events should not be based on it (if possible).
A though how to approach this: we could consider just creating a common parent for all cart events, which would effectively serve as a CartChangeEvent (for more see https://sap.github.io/spartacus-docs/event-service/#event-type-inheritance)

**Comment by Xymmer** [comment]
moved to jira
