### ISSUE TITLE
Cart-list-item not rendering sometimes in order-details page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7090]
## Environment Details

dev17

## Steps to Reproduce
- place an order
- visit the order detail page by doing one of the following

- visit the page by typing the url to the order history page with the order #7089 
or
- hope that the order came fast, and click the order from the order history page

## Observed Results

cart-item-list component did not get render, however when you refresh, it shows it.

## Expected Results

render cart-item-list instantly without re-rendering it

**Comment by Xymmer** [comment]
investigate if this is some kind of race condition - the ordre was just placed, you are trying to go directly to the order through URL, maybe order info not fully formed yet. if so then let's close as won't fix. if reproducible even after a bit of delay then it's a bug to further check how to fix.

**Comment by bgambocjaviniar** [comment]
not a bug, it was because unconsigned entries were removed.
closing as it is fixed in https://github.com/SAP/spartacus/issues/7293
