### ISSUE TITLE
Hardcoded occurrences of the OCC prefix

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7101]
Spartacus is using the configured OCC prefix to build the backend URL for OCC related calls. The prefix defaults to `/rest/v2`, which reflects the default OCC prefix in the backend (< 2005). 

While there's a default prefix, there are however several unnecessary notions of a hardcoded OCC prefix in the Spartacus code base. This is only part of the "internal" code and is not exposed in the libraries, but it does confuse devs who look into the source. We like to change this to end up with a single notion of the default prefix, which we can change once 2005 is a thing. 

In the commerce backend of 2005, the prefix will change from `/rest/v2` to `/occ/v2`. 
https://github.com/SAP/spartacus/search?q=rest%2Fv2&unscoped_q=rest%2Fv2 shows a list of hardcoded configurations of the prefix. 

These hardcoded prefixes are in one of the following categories:
- (outdated/obsolete) mocks
- e2e tests
- (outdated) instructions
- unit tests
- schematics?
- service worker cache configuration

With this ticket we like to drop those whenever we can, or move them to a configuration so we can easily move to the new endpoint.

**Comment by Xymmer** [comment]
Pawel has this search and replace to configure Spartacus locally:
LC_ALL=C find . -type f -exec sed -i '' -e 's|rest/v2|occ/v2|g' {} \;

**Comment by bgambocjaviniar** [comment]
QA steps:
- test checkout and make sure orders are placed
- test spartacus generally as a whole and make sure no new errors pops out

**Comment by KateChuen** [comment]
Tested on dev10. 
✅ checkout and orders ok. 
✅ spartacus as a whole looks ok.
❗️ could not test 'edit cart page' because of ticket 7337. But I tested changing the qty on pdp and added to cart modal.

**Comment by KateChuen** [comment]
✅Now that 7337 is fixed, tested "edit cart page" on dev3.
