### ISSUE TITLE
Publish weekly release

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#7109]
- [x] April 8 - 2.0.0-next.4 
- [x] April 15 - 2.0.0-next.5 & 2.0.0-next.6
- [ ] April 22
- [ ] April 29
- [ ] May 6
- [ ] May 13
- [ ] May 20
- [ ] May 27
- [ ] June 3
- [ ] June 10
- [ ] June 17
- [ ] June 24

**Comment by marlass** [comment]
@zebercut Can we close this issue?

**Comment by hackergil** [comment]
On behalf of Farzin, I don't think we need this anymore. He can correct us later :)
