### ISSUE TITLE
Missing BrowserTransferStateModule import for 1.5 schematics with SSR

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#7114]

**Comment by psmul** [comment]
Fix was provided for both versions, 1.5 and 2.0.

QA steps:
- build and pack locally schematics project
- create new clean app somewhere
- apply locally packed schematics with SSR mode

Expected results:
- `src/app.module.ts` should contain BrowserTransferStateModule in imports

**Comment by Matejk00** [comment]
QA done, works as expected.
