### ISSUE TITLE
Top Navigation refactoring to support Screen Readers

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#7120]
Navigation needs to be refactored to support Screen Readers, some of the things that need to be done:

1. Add ARIA attributes describing relationship between elements and their states.
2. Improve semantics: Remove H5, use a 
3. Test with Screen Readers (NVDA, VoiceOver, TalkBack)

**Comment by kacperknapik** [comment]
Will potentially be fixed in #7206

**Comment by kacperknapik** [comment]
This is NOT fixed in #7206

**Comment by developpeurweb** [comment]
It seems this is no longer an issue after navigation refactoring done in #13561 and #13511
