### ISSUE TITLE
Item-counter support for Screen Readers

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#7122]
For the next Accessibility milestone concerning Screen Readers (SR), the item-counter components needs to be properly ARIA labeled and provide instructions on how to change quantity if the SR doesn't provide this by default.

- More details here: https://cxwiki.sap.com/display/spar/Item-counter+Accessibility
- master ticket: #11192

**Comment by saad-mo** [comment]
#12702 merged

**Comment by saad-mo** [comment]
QA steps for Screen Reader Improvements: 
- Open PDP
- Verify that `-` and `+` buttons on the item counter have `aria-label attribute

**Comment by KateChuen** [comment]
Tested on develop branch of spartacus using installation script
More extensive testing (on other screenreaders and devices) will be done with RC.
![AddOneMore](https://user-images.githubusercontent.com/45409515/144909904-f72d6045-1ab2-4237-b99c-e3100c29085d.png)
![RemoveOne](https://user-images.githubusercontent.com/45409515/144909950-6f502ad9-5d66-490e-aba3-33a83344bd1c.png)
