### ISSUE TITLE
Release 2.0

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#7124]
The below list shows what needs to be done to release the final release of 2.0. 

1. - [x] [All must do coding tickets](https://github.com/SAP/spartacus/issues?q=is%3Aissue+milestone%3A2.0+label%3Amust+)
2. - [x] Publish RC, @marlass  
3. - [x] 2.0 Manual test (Features, CDS, Qualtrics), @KateChuen  : https://github.com/SAP/spartacus/issues/7126 -> covers 4 & 5 too
4. - [x] [2.0 Delivering docs](https://github.com/SAP/spartacus-docs/issues?q=is%3Aissue+is%3Aopen+label%3AMUST+label%3Ainput-required+milestone%3A2.0), @gladius-mtl

**Comment by marlass** [comment]
@zebercut can we close this issue?
