### ISSUE TITLE
[Keeping it here until dev17 pulls latest sample data and  reinit] Order Details: Permanent change in sample data needed to drop flexbox order, 

### ISSUE THREAD

**Issue by developpeurweb** [SAP/spartacus#7127]
There's a Documentation Ticket related to this issue: 
https://github.com/SAP/spartacus-docs/issues/473

Currently the slot order in the **Order Details page** is managed through the CSS flexbox `order` property, this is NOT ideal as it breaks Accessibility when using keyboard-only navigation by forcing the order of the element visually and not in the correct DOM order while tabbing. As per screenshot below.

![Screen Shot 2020-04-01 at 5 19 22 PM](https://user-images.githubusercontent.com/15113219/78189687-7f424580-7440-11ea-9670-217c092a9301.png)

In order to stop depending on CSS to arrange this layout, **the slot order needs to be managed from the source, potentially in the sample data**. 

If the flexbox order is **deactivated** it would look like this:

![Screen Shot 2020-04-01 at 5 25 46 PM](https://user-images.githubusercontent.com/15113219/78189755-a00a9b00-7440-11ea-875e-9b71f80bf5c8.png)

**Original mockups** look like this, so this is how the slot order should be arranged.

![Screen Shot 2020-04-01 at 5 35 13 PM](https://user-images.githubusercontent.com/15113219/78189798-b87ab580-7440-11ea-8a0a-f3f4c4bfe386.png)

**Comment by bgambocjaviniar** [comment]
PR: GH-7158
BACKEND PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/80/files

Also, updated dev-17 to have the backend slots positioned properly, but it won't persist until the backend PR gets in and we need to re-initializes dev-17 to have it.

**Comment by developpeurweb** [comment]
The CSS PR is approved, we still need to make sure the **BACKEND PR** is merged in order to close this ticket.

**Comment by LTiger14** [comment]
QA: Order is good and no flex
