### ISSUE TITLE
[Fixed by GH-5176] Add-to-cart modal: Remove button is misaligned

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7128]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: tablet view
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
Calydon: **disabled**

**Steps to Reproduce**
- Add an item to cart.

**Actual Result**
The "Remove" button is misaligned.

<img width="765" alt="Screen Shot 2020-04-01 at 6 02 42 PM" src="https://user-images.githubusercontent.com/45409515/78191374-da296c00-7443-11ea-86b7-704509a88c51.png">

**Comment by developpeurweb** [comment]
Got fixed by GH-5176

![Screen Shot 2020-04-21 at 4 13 15 PM](https://user-images.githubusercontent.com/15113219/79909653-5849b480-83eb-11ea-935d-204aea44c473.png)

**Comment by KateChuen** [comment]
Tested on dev3. 
✅Misalignment is now fixed.
