### ISSUE TITLE
[Fixed by #7206] Cannot navigate to myAccount using keyboard

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7131]
**Environment Details**
Spartacus: develop branch
Browser: Chrome, firefox, safari
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
Calydon: **disabled**.

**Steps to Reproduce**
- Login
- Navigate using keyboard to MyAccount

**Actual Result**
Cannot navigate to MyAccount using the keyboard.
<img width="1191" alt="Screen Shot 2020-04-01 at 10 46 33 PM" src="https://user-images.githubusercontent.com/45409515/78205679-cd6c3e80-746a-11ea-9451-be94703ef802.png">

**Comment by kacperknapik** [comment]
This is fixed in #7206
