### ISSUE TITLE
[Fixed by GH-7317] order details: item without an image is misaligned

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7132]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: tablet view
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
Calydon: **disabled**

**Steps to Reproduce**
- Place an order with an item that does not have an image.
- Go to Order History -> Order details

**Actual Result**
The item without an image is misaligned.

<img width="1197" alt="Screen Shot 2020-04-01 at 10 51 51 PM" src="https://user-images.githubusercontent.com/45409515/78206027-b548ef00-746b-11ea-9aef-9ceabba4d3d8.png">

**Comment by developpeurweb** [comment]
This ticket will get fixed by GH-7317 changes.

**Comment by KateChuen** [comment]
Tested on dev3. 
✅Misalignment is now fixed.
<img width="1025" alt="Screen Shot 2020-04-28 at 10 44 05 AM" src="https://user-images.githubusercontent.com/45409515/80501407-65abf500-893d-11ea-84c4-c9eac316e2ab.png">
