### ISSUE TITLE
Order details: user is allowed to change the qty

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7133]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device: tablet view
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD
Calydon: **disabled**

**Steps to Reproduce**
- Place an order with an item that does not have an image.
- Go to Order History -> Order details
- Click on the qty amount and change the number

**Actual Result**
It allows the user to change this value.

**Expected Result**
It should not allow the user to change this value even if it's not saved.

<img width="1193" alt="Screen Shot 2020-04-01 at 10 56 29 PM" src="https://user-images.githubusercontent.com/45409515/78206393-aca4e880-746c-11ea-898d-9a050684f933.png">

**Note**: Also happens on Order Checkout Review Page. And on that page, the change is saved, and the price is even updated, which is good. So the order is placed with the updated qty.

**Comment by Xymmer** [comment]
@tobi-or-not-tobi we think this is part of refactoring work you are doing

**Comment by amarendramohantyvaltech** [comment]
Is it still opened and need a fix?

**Comment by kacperknapik** [comment]
Fixed in #7339
