### ISSUE TITLE
Check possibility of upgrade thirdy party dependencies

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7172]
It applies to:

-  "@ng-bootstrap/ng-bootstrap": ">=4.1.0 <6.0.0",
-  "@ng-select/ng-select": ">=2.13.2 <4.0.0",
-   "ngx-infinite-scroll": "^8.0.0"

**Comment by dunqan** [comment]
QA steps:
-  confitm that ng-bootstrap related functionality works as before (modal windows)
- confitm that ng-select functionality works as before

**Comment by mirkosoft** [comment]
QA passed: both widgets work as expected.
