### ISSUE TITLE
Document cxFocus directive

### ISSUE THREAD

**Issue by gladius-mtl** [SAP/spartacus#7198]
This ticket is to indicate that draft doc input is required for the `cxFocus` directive topic.

**Comment by tobi-or-not-tobi** [comment]
@gladius-mtl  I'm surprised to see this ticket in this repo, should we not have those tickets in your docs repo?

**Comment by gladius-mtl** [comment]
This ticket can be closed because it is replaced by https://github.com/SAP/spartacus-docs/issues/552
