### ISSUE TITLE
Infinite loop for get cart when an error is returned

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7209]
This bug comes from the community https://spartacus-storefront.slack.com/archives/CD16V16FR/p1585761120084100.

The reported bug is as follows:

We are seeing an infinite loop just like the one discussed on: #3590, #3478 and #4043
On cart.effect.ts, 'UnknownResourceError' on filter is triggering the ClearCart action making "loading" (LoaderState<CartState>) to switch between false and true which in turn ends up triggering CartActions.LoadCart on cart.service.ts
Using version 1.3.0

[...]

I was able to replicate this issue by forcing an exception on the backend. I generated a NullPointerError which ends up sending a 400 response status and the following error:
{ errors: [{ "type": "NullPointerError"}]}
I replicated the infinite loop on branch release/2.0.x, using spartacus out of the box, without any modifications.
This case makes the cart state to look like this:
![sparatcusLoop](https://user-images.githubusercontent.com/10605724/78687209-eee18600-78c1-11ea-9050-66b2be115296.png)

#### Summary

Returning an unhanded error when trying to fetch the cart causes the load cart request infinite loop.

## Environment Details

- Spartacus:  1.3 and 2.0
- Browser: Any
- OS: Any
- Device: Any

## Steps to Reproduce

Return an error on GET cart request that is unhanded. (handled errors are `notFound` and `UnknownResourceError`)

## Observed Results

Infinite load cart requests.

## Expected Results

Error is handled

**Comment by LTiger14** [comment]
Fixed in develop with the new ActiveCartService

**Comment by kacperknapik** [comment]
**QA results**
- works as expected
