### ISSUE TITLE
Remove hello world html from the newly generated angular app

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7217]
Whenever a new app is created, the app.component.html still contains the hello world html. This is confusing for new devs who start with Spartacus. It would be good to drop the html and replace it with the cx-storefront component. 

We could offer a toggle in the CLI, but I don't see much value here. If in any case the dev likes to keep the former html, he should rely on git to role back those changes.

**Comment by mirkosoft** [comment]
Pleeas add/do QA as soon as pipeline is green
