### ISSUE TITLE
Fix error when Comment element has not parentElement (ie11)

### ISSUE THREAD

**Issue by antshater** [SAP/spartacus#7220]
Only error that block running spartacus in IE 11 is error occurs in getHostElement method in OutletDirective, please change 
```return this.getHostElement(element.parentElement);```
 to 
```this.getHostElement(element.parentNode); ```

## Environment Details

- Spartacus:  1.5.3
- Browser: IE 11
- OS: Windows

**Comment by Xymmer** [comment]
fix in 2.0 and decide on backporting

**Comment by tobi-or-not-tobi** [comment]
QA:
- confirm that outlets render on IE11. This can be done by adding custom outlets, or evaluate the use of skiplinks or ASM which depend on outlets.

**Comment by Xymmer** [comment]
i'll test on ie 11

**Comment by Xymmer** [comment]
Note: we don't really support IE11 but we decided to fix this one as it was low-anging fruit that unblocks further IE11 compatibility fixing that certain customers want to do. It's very unlikely we'll fix anything further for IE11 :)
