### ISSUE TITLE
Remove legacy flag we only support 1905+

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7231]
After discussing with Bill, we believe we do not need the legacy property under the occ object as we want only want to support 1905+ from now on.

**Comment by Xymmer** [comment]
step 1: spike what legacy affects, then chat with bill

**Comment by Xymmer** [comment]
the legacy flag affects GET or POST of cms which was changed between 1811 and 1905
could also be the salutation change in occ api between 1811 and 1905
and the idea is that we want to make it semantice (1905, 2005) instead of true/false

**Comment by tobi-or-not-tobi** [comment]
Closing, as we dropped the flag with #9748. The good news is that we still support the legacy system, but the code must be added explicitly.
