### ISSUE TITLE
Error on installation script with 2.0.0-next.4

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7236]
After installing and trying to start the latest next release, we get the following error:

chunk {styles} styles.js, styles.js.map (styles) 1.81 MB [initial] [rendered]
chunk {vendor} vendor.js, vendor.js.map (vendor) 339 kB [initial] [rendered]
Date: 2020-04-09T13:17:17.814Z - Hash: 3ca8096850c74a2b768b - Time: 59238ms

ERROR in node_modules/@spartacus/core/src/cms/store/effects/components.effect.d.ts:12:179 - error TS2694: Namespace '"/Users/i867028/git/github/spartacus-installation/app/spartacus/node_modules/@ngrx/effects/effects"' has no exported member 'CreateEffectMetadata'.

12     loadComponent$: (({ scheduler, debounce }?: any) => Observable<CmsActions.LoadCmsComponentFail | CmsActions.LoadCmsComponentSuccess<CmsComponent>>) & import("@ngrx/effects").CreateEffectMetadata;
                                                                                                                                                                                     ~~~~~~~~~~~~~~~~~~~~
node_modules/@spartacus/core/src/product/store/effects/product.effect.d.ts:10:161 - error TS2694: Namespace '"/Users/i867028/git/github/spartacus-installation/app/spartacus/node_modules/@ngrx/effects/effects"' has no exported member 'CreateEffectMetadata'.

10     loadProduct$: (({ scheduler, debounce }?: any) => Observable<ProductActions.LoadProductFail | ProductActions.LoadProductSuccess>) & import("@ngrx/effects").CreateEffectMetadata;
                                                                                                                                                                   ~~~~~~~~~~~~~~~~~~~~
src/app/app.module.ts:70:9 - error TS2326: Types of property 'features' are incompatible.
  Type '{ level: string; anonymousConsents: boolean; }' is not assignable to type '{ level?: string; consignmentTracking?: boolean; saveForLater?: boolean; cmsPageLoadOnce?: boolean; }'.
    Object literal may only specify known properties, and 'anonymousConsents' does not exist in type '{ level?: string; consignmentTracking?: boolean; saveForLater?: boolean; cmsPageLoadOnce?: boolean; }'.

**Comment by marlass** [comment]
Outdated issue. Closing
