### ISSUE TITLE
Update header for use with 2005 and occ prefix

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7237]
(Bill asks: Is #7487 related or duplicating a bit of this one?)

With 2005 and the `/occ/v2` prefix we need to update our documentation and configuration for custom headers.

The custom headers are:
- `cache-control` and `x-anonymous-consents` for Anonymous consents. See https://sap.github.io/spartacus-docs/anonymous-consent/
- `x-profile-tag-debug` and `x-consent-reference` for Context Driven Services. See https://sap.github.io/spartacus-docs/cds-integration/

#### Acceptance criteria
- Update documentation (anonymous and CDS) to mention adding the headers mentioned above in `corsfilter.commercewebservices.allowedHeaders` for 2005. For older versions the headers should still go in`corsfilter.ycommercewebservices.allowedHeaders`.
- Update the manifest for CCv2 to reflect this change
- Update the deployment script for Spartacus to reflect this change

**Comment by giancorderoortiz** [comment]
backend dev servers are not configured this way OOTB. 
modifications needed.

**Comment by giancorderoortiz** [comment]
@hackergil fyi

**Comment by bgambocjaviniar** [comment]
1) doc repo: https://github.com/SAP/spartacus-docs/issues/568
2) backend repo: https://github.tools.sap/cx-commerce/ec-e2e_staging/tree/ccv2-spa/20.05 (prettier prettified the file)
3) deployment script repo: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/21

1- updated all instances where we need to mention 2005
2- created a branch for 2005 (no pr as I guess we need to have both versions)
3- added the property to the spartacus recipe

**Note:** I think we need to wait for having our main backend as 2005 before getting these in
2 and 3: only added the necessary property and no added changes

**Comment by hackergil** [comment]
PRs merged. Changes can be applied/tested on Dev7

**Comment by giancorderoortiz** [comment]
doc repo not updated yet. 
https://github.com/SAP/spartacus-docs/pull/569/files

**Comment by giancorderoortiz** [comment]
> 1. doc repo: [SAP/spartacus-docs#568](https://github.com/SAP/spartacus-docs/issues/568)
> 2. backend repo: https://github.tools.sap/cx-commerce/ec-e2e_staging/tree/ccv2-spa/20.05 (prettier prettified the file)
> 3. deployment script repo: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/21
> 
> 1- updated all instances where we need to mention 2005
> 2- created a branch for 2005 (no pr as I guess we need to have both versions)
> 3- added the property to the spartacus recipe
> 
> **Note:** I think we need to wait for having our main backend as 2005 before getting these in
> 2 and 3: only added the necessary property and no added changes

Please note that several dev-servers are now 2005. dev-com2, dev-com8, dev-com5, dev-com16

**Comment by giancorderoortiz** [comment]
@gladius-mtl waiting for doc repo update before closing this ticket.

**Comment by giancorderoortiz** [comment]
change in pr 21 applied to https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/24/files as well. (2005 cx based spartacus recipe)

Documentation update to be handled separately.
