### ISSUE TITLE
Replace add voucher process with event system for vouchers

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7241]
Add voucher process is used only to get information about success/fail action.
Event system is better solution for that case. We just need events for vouchers and then we could cleanup AddVoucher actions, CartVoucherService and CartCouponComponent.

**Comment by znikola** [comment]
Depends on https://github.com/SAP/spartacus/issues/7084 and https://github.com/SAP/spartacus/issues/7085

**Comment by Platonn** [comment]
moved to https://jira.tools.sap/browse/CXSPA-375

**Comment by plabadie** [comment]
Removed deprecated notices since there is no replacement available #15864
