### ISSUE TITLE
Add a git hook for changes in yarn.lock

### ISSUE THREAD

**Issue by kacperknapik** [SAP/spartacus#7243]
### Problem
When we pull the latest develop branch with changes in `yarn.lock`, sometimes we don't update `node_modules` right away, which might introduce problems and errors in our local app. Also, after some changes in this file (eg. packages version updates), we have to remind people to reinstall `node_modules`.

### Solution
We can create a git hook - probably using `husky` or similar git hook solution, which would monitor `package.json` file and will throw an error (or notify the user in other way) about those changes and the need to reinstall `node_modules`.
Optionally this hook could reinstall it for us, automatically.

**Comment by marlass** [comment]
Deps change not that often now and no one asks for it.
