### ISSUE TITLE
Update migration guide about BillingAddressFormModule

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#7250]
We have missing info about in `BillingAddressFormModule` in: https://github.com/SAP/spartacus/blob/release/2.0.0-next.4/docs/migration/2_0.md#files-removal

Additionaly, there is probably mistake in `schematics\src\migrations\2_0\removed-public-api-data.ts`
```ts
// projects/storefrontlib/src/cms-components/checkout/components/payment-method/billing-address-form/billing-address-form.module.ts
{
  node: BILLING_ADDRESS_FORM_MODULE,
  importPath: SPARTACUS_STOREFRONTLIB,
  comment: `'${BILLING_ADDRESS_FORM_MODULE}' was removed. The form and the whole logic was moved to 'PaymentFormComponent'.`,
},
```
I think it should be `PaymentFormModule` instead of `PaymentFormComponent` in comment

**Comment by kacperknapik** [comment]
**QA results**
- works as expected
