### ISSUE TITLE
Application makes a duplicate request for products search in SSR mode

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#7253]
When you firstly get category page in SSR, application makes two duplicate requests for getting products data:

1. From Node.js to build the page
2. From user's web browser

## Environment Details

- Spartacus:  *-1.5.0
- Browser: Chrome
- Other environment details: Node.js 10.16.0

## Steps to Reproduce

1. Build and start application in SSR mode.
2. Open any category page with empty cache.

## Observed Results

We will see `/products/search` request which duplicates the same from SSR.

## Expected Results

Application doesn't make a duplicate request for products search in SSR mode.

## Additional Information

SSR always successfully renders category page with products data and we don't need one more request on the client side.

**Comment by psmul** [comment]
Hello @artem-zur. From what I've investigated, this issue was fixed in 1.5.2 patch release. Please try to update an application to (if possible) the latest 1.5 and let me know if the problem still occurs.

**Comment by artem-zur** [comment]
Hi @psmul! Thanks, I will respond to you after upgrading to Spartacus 2.0-RC (it's cuz we are actually in progress just now).

**Comment by artem-zur** [comment]
@psmul, I'm so sorry, I haven't seen that this issue has "blocks-final-2.0" label. Is it ok, if I will check it in 2.0-RC ?

**Comment by psmul** [comment]
@artem-zur Hey, sure thing. So, for now, I will close this issue, but you can create a new one any time or just ping me here if you get any lead on a bug.

**Comment by artem-zur** [comment]
Hi @psmul! Sorry for such long pause, I double checked the situation in Spartacus 2.0 - we still have the issue. And one important thing, I reproduced the same behaviour on public Spartacus demo https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/.

Maybe I can provide some additional information ?

**Comment by artem-zur** [comment]
@psmul, Based on our chat, I'v created and linked a new, separate issue specially for Spartacus 2.0 version.
