### ISSUE TITLE
can't submit cancel request in 2.0 (works in 1.5) (can't repro)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7277]
submit an order then try to cancel
submit button never becomes active in 2.0 but it works in 1.5.
using 2005 backend. there's no error in console.
![image](https://user-images.githubusercontent.com/4998145/79495123-1cc97780-7ff2-11ea-919c-d92bab32c6d4.png)

**Comment by Xymmer** [comment]
note that clicking submit may have actually triggered submission as i saw that the particular thing i was trying to cancel, was canceled. but the button didn't change nor did the page.

**Comment by kacperknapik** [comment]
Cannot reproduce this bug

**Comment by kacperknapik** [comment]
Waiting for C&R to be enabled on dev7

**Comment by qjimmy** [comment]
Happened on electronics spa with dev-7 

Blocking cancellation e2e since submitting is buggy

<img width="1382" alt="Screen Shot 2020-05-12 at 5 02 44 PM" src="https://user-images.githubusercontent.com/30666844/81858089-2e3e6a80-9531-11ea-996c-5942e521ada6.png">

**Comment by Xymmer** [comment]
Kacper will create new ticket for api error, since we see that Cancel is working now

**Comment by kacperknapik** [comment]
The ticket: https://github.com/SAP/spartacus/issues/7781
