### ISSUE TITLE
Refactor `PageMetaResolver` to make it consistent with Handlers implementation

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7279]
PageMetaResolver should implement Handler and share common interface and logic for handler resolution.

**Comment by KateChuen** [comment]
QA steps please.

**Comment by Platonn** [comment]
## QA steps:
### Testing:
1. Implement custom product page meta resolver with custom heading (i.e. in your app.module.ts)
   ```typescript
    @Injectable()
    export class CustomProductPageMetaResolver extends ProductPageMetaResolver {
      resolveHeading(): Observable<string> {
        return this.product$.pipe(map((p: Product) => `custom title '${p.name}'`));
      }
    }
   ```
1. and provide it in the AppModule:
   ```typescript
   @NgModule({
     providers: [
      {
        provide: PageMetaResolver,
        useClass: CustomProductPageMetaResolver,
        multi: true,
      },
    ],
     /* ... */
   })
   export class AppModule { /* ... */ }
   ```

1. Open PDP (i.e. http://localhost:4209/electronics-spa/en/USD/product/816802/Cyber-shot%20W55) and verify that you can see the custom title:
![obraz](https://user-images.githubusercontent.com/4001059/79971969-75d35880-8495-11ea-9552-d7d8205da826.png)

1. Add to the implementation of `CustomProductPageMetaResolver` the `getPriority` method returning very low priority, i.e. `Priority.FALLBACK`:
   ```typescript
   getPriority(): Priority {
       return Priority.FALLBACK;
   }
   ```
1. refresh the page and verify that the custom resolver didn't kick in, but you can see the following message of the default `ProductPageMetaResolver `:
![obraz](https://user-images.githubusercontent.com/4001059/79972451-453fee80-8496-11ea-81b9-f0e603ff36cc.png)

**Comment by Platonn** [comment]
QA successfull ✅
