### ISSUE TITLE
Refactor `HttpErrorHandler` to make it consistent with Handlers implementation

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7280]
`HttpErrorHandler` should implement Handler and share common interface and logic for handler resolution.

**Comment by KateChuen** [comment]
QA steps please.

**Comment by Platonn** [comment]
## QA steps:
### Prerequisites
1. drop config for the occ `baseUrl` (so any call to backend will fail with `504` http error) 
1. launch storefront locally by running `yarn start`

### Testing:
1. Implement custom error handler for 504 (i.e. in your app.module.ts)
   ```typescript
   @Injectable()
   export class CustomBadGatewayError extends BadGatewayHandler {
     responseStatus = 504;

     handleError() {
       this.globalMessageService.add(
         'custom error handling!',
         GlobalMessageType.MSG_TYPE_ERROR
       );
     }
    }
   ```
1. and provide it in the AppModule:
   ```typescript
   @NgModule({
     providers: [
       { provide: HttpErrorHandler, useClass: CustomBadGatewayError, multi: true },
    ],
     /* ... */
   })
   export class AppModule { /* ... */ }
   ```

1. Open the storefront and verify that you can see the custom handled error message on a blank page:
![obraz](https://user-images.githubusercontent.com/4001059/79890021-280c1100-83ff-11ea-8ca6-0754f705c174.png)

1. Add to the implementation of `CustomBadGatewayError` the `getPriority` method returning very low priority, i.e. `Priority.FALLBACK`:
   ```typescript
   getPriority(): Priority {
       return Priority.FALLBACK;
   }
   ```
1. refresh the page and verify that the custom handler didn't kick in, but you can see the following message of the default `BadGatewayHandler`:
![obraz](https://user-images.githubusercontent.com/4001059/79890292-92bd4c80-83ff-11ea-9ee9-3db4d7361655.png)

**Comment by Platonn** [comment]
During the QA found the bug #7324
