### ISSUE TITLE
Bring back unconsigned entries

### ISSUE THREAD

**Issue by mszczepaniak** [SAP/spartacus#7293]
Unconsigned entries template was deleted from order-detail-items component, this ticket's goal is to bring them back and show them in order history.

**Comment by bgambocjaviniar** [comment]
QA steps: 

**1)**
- place an order
- go to the order detail page of that order #
- verify the response if it populated the cart-list-item with unconsigned entries which displays the status as `PENDING`

**2)**
After a few seconds / minutes,
They will be converted to `consigned entires`, and verify the translations are properly mapped

**To change the consignment,**
- go to backoffice
- top left of the search bar in the backoffice, write order to filter
- click the orders nav
- search within that nav, your order #
- in one of the attributes/properties, go to consignment and change the consignments to any value and verify that it was updated in the frontend with the correct mapping (it may take a few seconds to update)

```
Mapping values corresponds to 

 IN_TRANSIT -> In Transit
 READY_FOR_PICKUP -> Ready for Pickup
 READY_FOR_SHIPPING -> Ready for Shipping
 WAITING -> Waiting
 DELIVERING -> Delivering
 PICKPACK -> Preparing for Shipment
 PAYMENT_NOT_CAPTURED -> Payment Issue
 READY -> In Process
 DELIVERY_REJECTED -> Delivery Rejected
 SHIPPED -> Shipped
 TAX_NOT_COMMITED -> Tax Issue
MIDDLE
 PICKUP_COMPLETE -> Pickup Complete
 DELIVERY_COMPLETED-> Delivery Complete
BOTTOM
 CANCELLED -> Cancelled
 Pending 
```

**Comment by Matejk00** [comment]
QA done.

1) Works as expected.
2) All values are displaying properly, and with proper translation.
