### ISSUE TITLE
[Backend fix in 2105] ASM empty categoy page on apparel

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7313]
## Environment Details

- Spartacus:  develop
- Browser: Firefox 76.0b3
- OS: Mac OS 10.15.4
- Other environment details: dev-17 backend

## Steps to Reproduce

- Load apparel
- Start ASM session
- Click a category in the header, the products are displayed
- Select a different category, nothing is displayed
- Select the first category, nothing is displayed

## Observed Results

Error in console for all category search requests similar to:

```
{"0":{"message":"Product code '300389093' is not unique, 2 products found!","type":"AmbiguousIdentifierError"}}
```

page looks like

<img width="992" alt="Screen Shot 2020-04-20 at 8 50 17 PM" src="https://user-images.githubusercontent.com/10605724/79813117-bf625d00-8348-11ea-8e49-acfa9457c7ca.png">

## Expected Results

Should display the PLP with products

**Comment by LTiger14** [comment]
This is backend related. See https://cxjira.sap.com/browse/C3PO-2348

**Comment by giancorderoortiz** [comment]
@plabadie fyi

**Comment by giancorderoortiz** [comment]
I'm changing priority to Major. It prevents purchase of product with ASM assistance. 
Still happens on 3.4. Firefox, Chrome. 
Tested on CCV2 environment. 

![Screen Shot 2021-06-20 at 4 42 18 PM](https://user-images.githubusercontent.com/46171897/122687832-a1131e00-d1e6-11eb-8d6a-02b0142ed8ed.png)

**Comment by LTiger14** [comment]
A backend fix is merged for 2105. Backend ticket https://cxjira.sap.com/browse/BAD-3620

**Comment by Xymmer** [comment]
closing, moved to jira
