### ISSUE TITLE
LaunchConfig not added to StorefrontConfig

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7338]
LaunchConfig was not added to StorefrontConfig type, so customer using `StorefrontModule.withConfig({ launch: ... })` gets errors that `launch` property it's not allowed.

Btw. in the second parameter of the `render` method of LaunchRenderStrategy (and its deriving classes) it would be good to replace type `LAUNCH_CALLER` with `LAUNCH_CALLER | string` for extendability.
https://github.com/SAP/spartacus/blob/develop/projects/storefrontlib/src/layout/launch-dialog/services/launch-render.strategy.ts#L19

**Comment by LTiger14** [comment]
# QA for launcher service

## ASM 

Add this config to your `app.module`

```
      launch: {
        ASM: {
          outlet: 'cx-storefront',
          component: AsmMainUiComponent,
          position: OutletPosition.AFTER,
        },
      },
```

When opening ASM with `?asm=true` the asm dialog will be at the bottom of the page

## Custom inline service

1. Create a new file and paste the following code to override the `InlineRenderStrategy`

### This will:
- Add a custom class `wow-i-am-good`
- New alert on close (could be an event or something)

```
@Injectable({ providedIn: 'root' })
export class CustomLaunchStrategy extends InlineRenderStrategy {
  protected dialogClasses = [
    'd-block',
    'fade',
    'modal',
    'show',
    'wow-i-am-good',
  ];

  render(
    config: LaunchInlineDialog,
    caller: LAUNCH_CALLER | string,
    vcr: ViewContainerRef
  ): Observable<ComponentRef<any>> {
    return super
      .render(config, caller, vcr)
      .pipe(tap((component) => component.onDestroy(() => alert('TADA!!! 🎉'))));
  }
}
```

In app.module:

`{ provide: InlineRenderStrategy, useClass: CustomLaunchStrategy },`

Open the anonymous consent dialog using the button in the footer. It will add the class like here:

<img width="527" alt="Screen Shot 2020-05-06 at 3 56 07 PM" src="https://user-images.githubusercontent.com/10605724/81223277-c11c5980-8fb3-11ea-9e88-ac56679b9084.png">

On close you will see an alert:

<img width="788" alt="Screen Shot 2020-05-06 at 3 56 34 PM" src="https://user-images.githubusercontent.com/10605724/81223194-9f22d700-8fb3-11ea-821b-c4a7d222b58b.png">

## Anonymous consent dialog side nav

1. Add the following configuration in the `app.module.ts`

```
      launch: {
        ANONYMOUS_CONSENT: {
          outlet: 'cx-storefront',
          inline: false,
          component: AnonymousConsentDialogComponent,
          dialogType: DIALOG_TYPE.SIDEBAR_START,
        },
      },
```
2. Create a new file and paste the following code to override the `OutletRenderStrategy`

```
@Injectable({ providedIn: 'root' })
export class OutletStrategy extends OutletRenderStrategy {
  protected sidebarStartClasses = ['to-da-side'];
}
```
3. Provide the new service in the `app.module`

`{ provide: OutletRenderStrategy, useClass: OutletStrategy },`

4. Add the following custom css in `styles.scss`

```
.to-da-side {
  position: fixed;
  z-index: 1000;
  background: none;
  top: 0;
  left: 0;
  width: 500px;
  height: 100%;

  .cx-anonymous-consent-dialog {
    max-width: 100% !important;
    min-width: 100% !important;

    height: 100%;
    margin: 0;

    .cx-dialog-content {
      height: 100%;

      > div {
        height: 100%;
      }
    }
  }
}
```

Open the anonymous consent dialog using the button in the footer. It should look like this:
<img width="1081" alt="Screen Shot 2020-05-06 at 4 09 53 PM" src="https://user-images.githubusercontent.com/10605724/81223519-1b1d1f00-8fb4-11ea-901d-ae51c3ded112.png">

**Comment by KateChuen** [comment]
Tested locally, pointing to dev10 (1905 suite).

✅Adding launcher service in asm
<img width="1440" alt="Screen Shot 2020-05-11 at 9 54 19 AM" src="https://user-images.githubusercontent.com/45409515/81579658-694a6d80-937a-11ea-812e-1d087fb65358.png">

✅Creating a Custom inline service for anonymous consent
<img width="1438" alt="Screen Shot 2020-05-11 at 11 11 41 AM" src="https://user-images.githubusercontent.com/45409515/81579832-a0b91a00-937a-11ea-9c63-2e0f3ce15e30.png">

✅Creating Anonymous consent dialog side nav
<img width="327" alt="Screen Shot 2020-05-11 at 11 26 02 AM" src="https://user-images.githubusercontent.com/45409515/81580005-df4ed480-937a-11ea-8c25-a04f7577f06b.png">
<img width="556" alt="Screen Shot 2020-05-11 at 11 26 11 AM" src="https://user-images.githubusercontent.com/45409515/81580007-dfe76b00-937a-11ea-80c8-0ff9ea8697fe.png">
<img width="578" alt="Screen Shot 2020-05-11 at 11 31 33 AM" src="https://user-images.githubusercontent.com/45409515/81580142-086f6500-937b-11ea-960a-0216912fd74c.png">

<img width="1138" alt="Screen Shot 2020-05-11 at 11 25 41 AM" src="https://user-images.githubusercontent.com/45409515/81579958-d0682200-937a-11ea-887d-b2d92f289100.png">
