### ISSUE TITLE
Item counter editable in places where it shouldn't be

### ISSUE THREAD

**Issue by kacperknapik** [SAP/spartacus#7339]
### Problem
Item counter should be disabled, when the value should be readonly. In order details page (and probably in other places too) it is actually accessible and you can change its value.

### Possible solution
Add `disabled` or `readonly` attribute to the item counter when the value should be readonly.

![image](https://user-images.githubusercontent.com/22354613/79987628-f56d2180-84ad-11ea-96c0-761cae614d3e.png)

**Comment by mszczepaniak** [comment]
**QA Steps:**
1. Add product to cart
2. Check that you can change the item count in the cart by selecting the input and writing the number
3. Check that you cannot change the item count in the order history

**Comment by Matejk00** [comment]
QA done. Item count input works as expected.
