### ISSUE TITLE
Improvements on spartacussampledataaddon

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7341]
The goal of this ticket is to improve the sample data we use for e2e tests. At the moment, to inject the sample data that we use for cypress e2e tests, we have to manually import test_data.impex for both apparel and electronics stores. Here's some feedback from @frankgrupe :

"sample data" is there for being able to test all scenarios.

* Sample customers/addresses: create them without password and then add the password to the central file
* cms data: why not make that part of the sample data?
* promotion/coupons: why not make that part of the sample data?
* stock: why not change the sample data to have different cases?
* orders/consignments: you should never import these ideally, cause you are "faking" business logic to create them, you can easily create them when needed via OCC

We also must eliminate duplication between apparel and electronics sample data, if any.

**Comment by Xymmer** [comment]
to Gil to eval and produce new tickets for changes, but not meant for one person to do the work - let's spread it out during 2.x to all teams

**Comment by frankgrupe** [comment]
just to be clear: it is nothing SPA related really, but I think the EC sample data should be improved, so you can test everything WITHOUT adding stuff on the top, so it would require an additional C3PO ticket and the spartacussamplesaddon gets smalled and smaller

**Comment by hackergil** [comment]
We are now importing sample data without additional steps

**Comment by frankgrupe** [comment]
@hackergil So you are dropping spartacussampledata? Sorry, don't understand what you did, this ticket was also about bringing spartacussampledata back into electronicsstore etc and I don't think this happened yet.
Do we need a NEW ticket to move major parts of spartacussampledata back into electronics/apparel/powertools?
We cannot continue as is for much longer, cause you create your own small world of sample data in the addon and customers would basically have to mix and match both our and SPA sample data and then add customer one, which is a big step. Are you even splittng the sample data for cms, promotions, cpq, ... to modularize it as all our modules are optional, so will spartacussampledata work with every combination of backend modules? Maybe we need a call about how to proceed here?

**Comment by hackergil** [comment]
@frankgrupe yes, let's discuss the approach once more. We can create new tickets from the outcome.
