### ISSUE TITLE
Attribute 'Colour of Home Theatre': Images only visible after update is done

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#7345]
Configure product CONF_HOME_THEATER_ML. Add to cart.

Edit configuration from cart. Images for 'Colour' are not visible, only when one triggers an update on the config page

**Comment by steinsebastian** [comment]
Issue on OCC side. Created jira issue TIGER-6446

**Comment by steinsebastian** [comment]
Issue on OCC side. Created jira issue TIGER-6446
