### ISSUE TITLE
facet decoding doesn't work anymore

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7348]
Since the refactor of the facet component, facet with spaces (i.e. "Fukuoka Best Western Fukuoka Nakasu Inn") are broken.

**Comment by Platonn** [comment]
It seems to be an older issue. It didn't work even in a commit before the facet refactor: 586bff9964add1623f53ac3c9284c6ecc93c9f93 . So it's not caused by the refactor #7230 (adb901bf44da5806662465a1c8c39916c3829f51).

**Comment by Platonn** [comment]
### How to reproduce:
1. Go to PLP of Digital Cameras http://localhost:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/c/575
2. Select any facet from left menu that contains a space inside, i.e. "Fukuoka Best Western Fukuoka Nakasu Inn (52)"
3. Verify there is no products returned (empty list)
![image](https://user-images.githubusercontent.com/4001059/80356887-6a5ba500-887a-11ea-9810-789227f4bb19.png)


### Expected result:
52 products should be returned from backend and displayed in PLP

**Comment by Platonn** [comment]
Note: I checked on this random commit 0f06cac7c59b0128edb4ad6e4a6786b29d98b7b6 that it used to work.

**Comment by znikola** [comment]
To QA: https://github.com/SAP/spartacus/issues/7348#issuecomment-619853560

**Comment by Zeyber** [comment]
QA: Verified facet filters work on plp
