### ISSUE TITLE
NavigationUIComponent alignment in case of "rtl" interfaces

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7354]
Related to the functionality of #6899
For stickouts in the right it works correctly.
Might be worth to check if that also works in `rtl` interfaces and alignment near left end of the screen.

**Comment by morganm58** [comment]
It looks like it works fine to me. 
![Screen Shot 2021-06-21 at 12 41 55 PM](https://user-images.githubusercontent.com/2947470/122797999-12f27280-d28e-11eb-92fe-22be420c32db.png)

**Comment by morganm58** [comment]
I cannot replicate
