### ISSUE TITLE
Screen position should be adjusted on group change

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#7362]
Configure CONF_CAMERA_SL. Skip through groups, do some attribute assignment 'Specification'. Click 'next' -> 
'prev'/'next' buttons are hardly visible as the next group is much smaller. In this case view should scroll so that 'prev' / 'next' don't change their position much

**Comment by steinsebastian** [comment]
The following behavior was proposed by Anthony:
On every group change it should be scrolled to the top of the configuration area. Group change means: prev/next buttons and group-menu.
If the hierarchy-level in a multilevel product is changed via group-menu no scrolling should be done.
