### ISSUE TITLE
Remove not possible after login

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#7369]
An entry that has been added to cart anonymously cannot be removed after login.

Video: https://sap-my.sharepoint.com/:v:/p/sebastian_stein/EXcWgBDfAVJKhi6dhXhN3AIB1qgXwHAfYrWzOdz8VVPr3g?e=Nkgfh2

Step by step

-> User is not logged in
-> Dependency PC
-> Select some values
-> Add to cart
-> Continue to cart
-> Login with cpq02@sap.com
-> Now the remove link does not work anymore

**Comment by ChristophHi** [comment]
Reason: An error occurs during cart processing (on server side: No mapping for GET /occ/v2/electronics-spa/users/current/customercoupons).
Which leads to the cart 'lock' state not beeing reset. Can be overcome by entering a dummy coupon code e.g., afterwards cart is open again.
Has nothing to do with our scope.

Wait until next merge from develop (sample data, SPA) and then try again

**Comment by ChristophHi** [comment]
This has nothing to do with the SPA side. Extension customercouponocc seems to be missing in our setup, causing an error that causes the lock state to persist.
