### ISSUE TITLE
Missing media doesn't render on product reference component

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7370]
Whenever there's a missing media for a product, we tend to not render the cx-media component. This however results in a view without any image, including the missing image. We like to render missing images which is why we always render the cx-media component.

**Comment by tobi-or-not-tobi** [comment]
QA:
- open /electronics-spa/en/USD/product/2053266/EOS%20500D%20body and verify that the 2nd product reference image is shown as a missing image

We also render missing media on the product carousel now. Not sure if we have this in the sample data though.

**Comment by KateChuen** [comment]
Tested on dev3. 
✅It's properly displayed now.
<img width="927" alt="Screen Shot 2020-04-30 at 9 51 14 AM" src="https://user-images.githubusercontent.com/45409515/80718716-7fc60e80-8ac8-11ea-8bd0-eb37b2b6bea4.png">
<img width="425" alt="Screen Shot 2020-04-30 at 9 51 31 AM" src="https://user-images.githubusercontent.com/45409515/80718721-805ea500-8ac8-11ea-9216-54d4f8360805.png">
