### ISSUE TITLE
Update installation script and move it to the main repo.

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#7375]
This ticket is for two tasks:
- [x] Improvement of the installation script (us `v2` branch as base). It shouldn't require any manual steps despite of spartacus version being installed and env details.
- [x] Once improved let's move it to the our main repo

**Comment by giancorderoortiz** [comment]
Some comments after usage in linux dev-servers. 
1. Avoid prompts as we'd like to run this script from CI as well. (i.e. npm credentials, delete previous installation, etc)
2. Add a flag "-f" to force overwrite of previous installation so that prompt can be avoided.

**Comment by giancorderoortiz** [comment]
Furthermore: 
- Should install apparel store as well. 
- Please leave placeholder in config.sh for powertools also. 
- Should be able to re-install same version more than once without having to manually -delete/reconfigure any of the underlying components.

**Comment by hackergil** [comment]
@mirkosoft I would suggest to merge what we have so far and create new ticket(s) for the remaining work.

**Comment by mirkosoft** [comment]
Most of identified issues has been resolved, for the ones left separate issues has been created:
https://github.com/SAP/spartacus/issues/7949
https://github.com/SAP/spartacus/issues/7950
https://github.com/SAP/spartacus/issues/7951

**Comment by giancorderoortiz** [comment]
Script should also work for powertools. (i.w. my-company branch for example)

**Comment by marlass** [comment]
> Script should also work for powertools. (i.w. my-company branch for example)

I think it will be done once we make use of dev-schematics.

**Comment by giancorderoortiz** [comment]
Tested extensively on Linux dev-servers as well as Mac. 
Most issues raised have been fixed or will be addressed on separate tickets. 
It's indeed a significant improvement over previous installation script. 
Kudos. 👍

**Comment by giancorderoortiz** [comment]
pending support for powertools... https://github.com/SAP/spartacus/issues/7965
