### ISSUE TITLE
Product list component refresh on init

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7382]
# Environment Details

- Spartacus:  Any
- Browser: Any
- OS: Any

## Observed Results

From Slack: 
We are working on the PLP and we’re seeing an odd behavior. If you could explain the logic behind it, that would be helpful.
in the `product-list.component.ts` it seems like we are always clearing search results using `this.productListComponentService.clearSearchResults();` in the init function. which removes all search information from the store. The `ProductListComponentService` still works because it filters any values that is empty see `searchResults$` . Other services like `CategoryPageMetaResolver` however do not filter the results properly, which means it receives an empty SearchPage every time we load the page, which results in breadcrumbs being emptied.
1:29
In our custom CategoryPageMetaResolver, we added the same validation, which fixes the problem, but it seems very odd to clear search result everytime we navigate the the PLP.

<img width="834" alt="Screen Shot 2020-04-27 at 1 31 17 PM" src="https://user-images.githubusercontent.com/10605724/80428058-01dee900-88b7-11ea-8feb-b770b219477f.png">

This was introduced to fix https://github.com/SAP/spartacus/issues/879. It does not seem necessary anymore as the language change now clears the search data by itself. See screenshot with the clear call disabled.

<img width="637" alt="Screen Shot 2020-04-27 at 6 47 58 PM" src="https://user-images.githubusercontent.com/10605724/80428367-ab25df00-88b7-11ea-8e40-a106e54c4db8.png">

## Expected Results
Can we get rid of this?

**Comment by Xymmer** [comment]
to dev: evaluate and either fix or say why not; also adjust milestone if necessary

**Comment by Xymmer** [comment]
Louis to evalute, if a bug, keep in the board. if not, close

**Comment by LTiger14** [comment]
It's not really a bug more of an improvement/cleanup for something we don't need anymore.

**Comment by LTiger14** [comment]
QA:
- Go to PLP (any search or category)
- Change currency, make sure the prices update
- Change language, make sure the description of the product changed language

**Comment by psmul** [comment]
QA done. Provided QA steps work as intended.
