### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError occurs on breadcrumb

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7413]
1. Open category (i.e. film camera's)
2. Open cart page
3. Open product list page (i.e. camcorders0

You should see a `ExpressionChangedAfterItHasBeenCheckedError` on the dev tools.

**Comment by bgambocjaviniar** [comment]
PR: GH-7464

**Comment by giancorderoortiz** [comment]
I don't see this expression ExpressionChangedAfterItHasBeenCheckedError
Testing with http://dev-com-8.accdemo.b2c.ydev.hybris.com:4200/
