### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError is thrown

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#7418]
This error is thrown after navigating from the overview page back to the configuration.
![image](https://user-images.githubusercontent.com/61147963/80715315-781d5e80-8af6-11ea-8510-c010277880ad.png)

**Comment by tobi-or-not-tobi** [comment]
@Larisa-Staroverova is this still happening? And if so, what do you mean with "overview page" and "configuration"?

**Comment by ChristophHi** [comment]
@tobi-or-not-tobi , @Larisa-Staroverova : It has been fixed. On our side we needed to delay the initialization of one component
