### ISSUE TITLE
Product Configuration Model is not found error is thrown

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#7420]
This error is thrown by navigating back to the configuration back from the overview page.

![image](https://user-images.githubusercontent.com/61147963/80728493-4660c380-8b07-11ea-9a1b-9b4fcc873492.png)

**Comment by steinsebastian** [comment]
Exception on server side:
NFO  [hybrisHTTP40] [RestHandlerExceptionResolver] Translating exception [de.hybris.platform.sap.productconfig.services.exceptions.ConfigurationNotFoundException]: ProductConfigurationModel with id='54b02e22-b9b7-4643-aa6d-4947382aeae9' not found
ERROR [hybrisHTTP40] [RestHandlerExceptionResolver] de.hybris.platform.sap.productconfig.services.exceptions.ConfigurationNotFoundException: ProductConfigurationModel with id='54b02e22-b9b7-4643-aa6d-4947382aeae9' not found
	at de.hybris.platform.sap.productconfig.services.impl.ProductConfigurationPersistenceServiceImpl.getByConfigId(ProductConfigurationPersistenceServiceImpl.java:83)
	at de.hybris.platform.sap.productconfig.services.intf.ProductConfigurationPersistenceService.getByConfigId(ProductConfigurationPersistenceService.java:37)
	at de.hybris.platform.sap.productconfig.services.strategies.lifecycle.impl.PersistenceConfigurationAssignmentResolverStrategyImpl.retrieveRelatedObjectType(PersistenceConfigurationAssignmentResolverStrategyImpl.java:76)

**Comment by Larisa-Staroverova** [comment]
**Full stacktrace:**
INFO  [hybrisHTTP39] [147.204.7.110] [RestHandlerExceptionResolver] Translating exception [de.hybris.platform.sap.productconfig.services.exceptions.ConfigurationNotFoundException]: ProductConfigurationModel with id='c73699cd-4199-486c-b014-fc5f19265407' not found
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | ERROR [hybrisHTTP39] [147.204.7.110] [RestHandlerExceptionResolver] de.hybris.platform.sap.productconfig.services.exceptions.ConfigurationNotFoundException: ProductConfigurationModel with id='c73699cd-4199-486c-b014-fc5f19265407' not found
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.impl.ProductConfigurationPersistenceServiceImpl.getByConfigId(ProductConfigurationPersistenceServiceImpl.java:83)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.intf.ProductConfigurationPersistenceService.getByConfigId(ProductConfigurationPersistenceService.java:37)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.strategies.lifecycle.impl.PersistenceConfigurationAssignmentResolverStrategyImpl.retrieveRelatedObjectType(PersistenceConfigurationAssignmentResolverStrategyImpl.java:76)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.testdata.strategies.lifecycle.impl.DynamicConfigurationAssignmentResolverStrategyImpl.retrieveRelatedObjectType(DynamicConfigurationAssignmentResolverStrategyImpl.java:22)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.impl.ProductConfigurationServiceImpl.retrieveRelatedObjectType(ProductConfigurationServiceImpl.java:191)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.impl.ProductConfigurationServiceImpl.isRelatedObjectReadOnly(ProductConfigurationServiceImpl.java:170)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.services.impl.ProductConfigurationServiceImpl.retrieveCorrectPricingDate(ProductConfigurationServiceImpl.java:198)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.rules.service.impl.ProductConfigurationRuleAwareServiceImpl.provideConfigurationModel(ProductConfigurationRuleAwareServiceImpl.java:178)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.rules.service.impl.ProductConfigurationRuleAwareServiceImpl.retrieveConfigurationModel(ProductConfigurationRuleAwareServiceImpl.java:149)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.089 | 	at de.hybris.platform.sap.productconfig.facades.impl.ConfigurationOverviewFacadeImpl.getOverviewForConfiguration(ConfigurationOverviewFacadeImpl.java:136)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at de.hybris.platform.sap.productconfig.occ.controllers.ProductConfiguratorCCPController.getConfigurationOverview(ProductConfiguratorCCPController.java:180)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at jdk.internal.reflect.GeneratedMethodAccessor1797.invoke(Unknown Source)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:888)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.090 | 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:322)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$StatisticsGatewayFilter.doFilter(AbstractPlatformFilterChain.java:410)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.sap.productconfig.occ.filter.ProductConfigurationOCCSessionAttributesFilter.doFilterInternal(ProductConfigurationOCCSessionAttributesFilter.java:44)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.commercewebservices.core.auth.GuestRoleFilter.doFilterInternal(GuestRoleFilter.java:75)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.091 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.cmsocc.filter.CMSPreviewTicketFilter.doFilterInternal(CMSPreviewTicketFilter.java:81)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.commercewebservices.core.v2.filter.CartMatchingFilter.doFilterInternal(CartMatchingFilter.java:38)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.personalizationservices.filter.CxOccPersonalizationFilter.doFilterInternal(CxOccPersonalizationFilter.java:42)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at com.hybris.yprofile.consent.filters.OCCConsentLayerFilter.doFilterInternal(OCCConsentLayerFilter.java:53)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.commercewebservices.core.filter.SessionCurrencyFilter.doFilterInternal(SessionCurrencyFilter.java:36)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.commercewebservices.core.filter.SessionLanguageFilter.doFilterInternal(SessionLanguageFilter.java:36)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.092 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.commercewebservices.core.filter.Europe1AttributesFilter.doFilterInternal(Europe1AttributesFilter.java:36)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.commercewebservices.core.filter.ConsentFilter.doFilterInternal(ConsentFilter.java:59)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.commercewebservices.core.v2.filter.UserMatchingFilter.doFilterInternal(UserMatchingFilter.java:89)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.093 | 	at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.oauth2.provider.authentication.OAuth2AuthenticationProcessingFilter.doFilter(OAuth2AuthenticationProcessingFilter.java:176)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.access.channel.ChannelProcessingFilter.doFilter(ChannelProcessingFilter.java:157)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.094 | 	at de.hybris.platform.commercewebservices.core.v2.filter.BaseSiteMatchingFilter.doFilterInternal(BaseSiteMatchingFilter.java:58)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.WebAppMediaFilter.doFilter(WebAppMediaFilter.java:122)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.PolyglotPersistenceCallbackFilter.doFilter(PolyglotPersistenceCallbackFilter.java:36)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.webservicescommons.filter.RestSessionFilter.doFilter(RestSessionFilter.java:39)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.Log4JFilter.doFilter(Log4JFilter.java:37)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:92)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.webservicescommons.filter.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:33)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.095 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain$InternalFilterChain.doFilter(AbstractPlatformFilterChain.java:292)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain.processStandardFilterChain(AbstractPlatformFilterChain.java:200)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at de.hybris.platform.servicelayer.web.AbstractPlatformFilterChain.doFilterInternal(AbstractPlatformFilterChain.java:177)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:113)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at de.hybris.platform.webservicescommons.filter.SessionHidingFilter.doFilter(SessionHidingFilter.java:34)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.096 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.springframework.web.filter.ShallowEtagHeaderFilter.doFilterInternal(ShallowEtagHeaderFilter.java:104)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at de.hybris.platform.servicelayer.web.XSSFilter.processPatternsAndDoFilter(XSSFilter.java:351)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at de.hybris.platform.servicelayer.web.XSSFilter.doFilter(XSSFilter.java:299)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:678)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.097 | 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:810)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 | 	at java.base/java.lang.Thread.run(Thread.java:834)
INFO   | jvm 1    | srvmain | 2020/04/30 15:02:38.098 |

**Comment by ChristophHi** [comment]
Should be fixed with https://github.com/SAP/spartacus/pull/7431
