### ISSUE TITLE
Making the hardcoded container width a sass variable [confirm with Tobias May25]

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7434]
From public slack channel https://spartacus-storefront.slack.com/archives/CD16V16FR/p1587990968350700 :
> Hello everyone, I have a styling related question.
> Right now I see that the value of 1140px has been hardcoded on multiple places to define the width of the content (or specific slots/components). Currently it’s quite difficult/not clean if we want to override just that value, in case we need to modify the width. It would be much better if this value could be defined with a variable.
> Is there something like this already planned? If not, what do you think about it?

Indeed there are some hardcoded values for the container width 1140px, see https://github.com/SAP/spartacus/search?q=1140px .

Let's make it a sass variable. We should also check if other widths or breakpoints are hardcoded. If so, let's consider making them sass variables too. It would be good to make this API consistent.

**Comment by Xymmer** [comment]
let's confirm with Tobias

**Comment by Xymmer** [comment]
not a breaking change, so we'll aim for 2.x and not hold up 2.0

**Comment by developpeurweb** [comment]
**For QA:**
This allows controlling individually most of the page templates' width and some components.

- Go to `projects/storefrontapp/src/styles.scss`
- Add this after Line 8: `.LandingPage2Template {--cx-page-width-max: 100%;}`
- See how Homepage width changes to 100% and other pages won't (e.g. search results page).

**Comment by giancorderoortiz** [comment]
Testing performed as mentioned. 
Width indeed changes as expected. 

![Screen Shot 2020-10-30 at 9 47 51 AM](https://user-images.githubusercontent.com/46171897/97712916-7cbad380-1a95-11eb-838a-efd25001b357.png)
![Screen Shot 2020-10-30 at 9 49 20 AM](https://user-images.githubusercontent.com/46171897/97712928-7fb5c400-1a95-11eb-87a2-8afa8928674c.png)

**Comment by giancorderoortiz** [comment]
Not sure if this small change requires documentation
