### ISSUE TITLE
CMSLinkComponent pointing to either Product Page or Content Page not working

### ISSUE THREAD

**Issue by ibenhar** [SAP/spartacus#7451]
- Spartacus:  1.5.1
- Browser: all browsers
- OS: all OS
- Device: All devices
- Other environment details: angular 8.2.8, SAP Commerce Platform 1905

## Steps to Reproduce
1) Go to smartedit -> navigation 
2) Choose any navigation node
3) Change navigation node Link To attribute to Content and save

## Observed Results

Go to spartacus storefront, the link is inactive (this is also not working for Product link to)

## Expected Results
We should have an active link that once clicked, forward the user to the content page.

**Comment by Xymmer** [comment]
to dev: investigate
fix in 2.1 and 2.0.patch
