### ISSUE TITLE
Disable 'enable' button if parent unit is disabled

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#7457]
Base on: https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Behavior+of+entities%2C+which+parent+is+disabled

@Xymmer please clarify list below:
IMO it should be done: (Bill agrees)
- [x] disable "Enable" button by based on property orgUnit.active for **budget**
- [x] disable "Enable" button by based on property parentOrgUnit.active for **unit**
- [x] disable "Enable" button by based on property unit.active for **cost center**
[backend doesn't return error but no effect]
**Bill says: check what happens if unit, cost center, budget are disabled, if you enable unit, enabling budget is ok? with cost center not enabled**
_Michał says: yes, I tested and it's ok. They are not related as hierarchy._

And this not: (Bill agrees)
~disable "Enable" button by based on property orgUnit.active for **permission**~
[backend allows for that]
~disable "Edit" button by based on property orgUnit.active for **user group**~
[backend allows for that]

**Comment by Xymmer** [comment]
all good from my side!
