### ISSUE TITLE
Adding a new shipping address give an error in the console

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7463]
## Environment Details

On `develop` and maintenance branch `release/2.0.x`

## Steps to Reproduce

1. Create a new account (or use existing one)
1. a If the account doesn't already have an address, add one via the address book
2. Add product to cart and go to checkout
3. (open the browser console) Add a new address
4. The error appears in the console

## Observed Results

An error is visible in the browser console when adding a new address. It is still possible to complete the checkout.

## Expected Results

There shouldn't be an error

**Comment by kacperknapik** [comment]
**QA results**
- works as expected
