### ISSUE TITLE
Release 1.5.4

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#7467]
- [x] create release/1.5.4 from 1.5.x
- [x]  Install from 1.5.4 using spartacus installation script
- [x] ADD `https://dev-com-12.accdemo.b2c.ydev.hybris.com:9002` base url to app/spartacus/src/app.module.ts (E)
- [x] `./spartacus.sh start`
- [x]  run all e2e tests on release branch (source)
    - [x] `yarn e2e:cy:run`
~- [ ]  validate that every merged ticket is server QA (nothing should be left in those column, exceptions - ticket marked as not blocking)~
- [x]  we are sure that release branch is working correctly, everything is passing and it builds
- [x]  generate compodocs `yarn generate:docs` check if new archives created
    (run in ubuntu shell)
- [x]  release libraries with release-it scripts (select Other, please specify... and type manually `1.5.4`)
    (set GITHUB_TOKEN and npm login)
   - [x] `npm run release:assets:with-changelog`
   - [x] `npm run release:styles:with-changelog`
   - [x] `npm run release:lib:with-changelog`
   - [x] `npm run release:core:with-changelog`
   - [x] `npm run release:cds:with-changelog`
   - [x] `npm run release:schematics:with-changelog`
- [x]  check if release-notes are populated on github (if not update)
- [x]  check tags on npm
- [x] Add spartacus sampledata
- [x]  check if everything builds from npm packages (spartacus-installation) script
    (./spartacus.sh install_npm) (add @next to add_spartacus_npm_install function branches for next)

- [x]  merge release branch (PR from release/1.5.4) to 1.5.x (squash and merge)

- [x]  inform Bill about released libraries (for patch releases, you can announce on public slack)
- [x]  announcing on tribe channel

**Comment by marlass** [comment]
Closing as it was merged to 1.5.x branch
