### ISSUE TITLE
B2BCustomer.Active flag is ignored in Spartacus

### ISSUE THREAD

**Issue by hazemfarahat** [SAP/spartacus#7476]
## Environment Details

- Spartacus:  2.0 RC
- Browser: Chrome 81 /Firefox 68.7
- OS: Windows 10
- Hybris 1905.13

## Steps to Reproduce
1. From backoffice go to the customers section
2. Select any b2bcustomer and set its customer.active flag to false
3. use the same customer to login in to Spartacus and in to the accelerator storefront. 

## Observed Results
The customer can normally login in Spartacus while in the accelerator storefront login is not allowed

## Expected Results
An inactive user is not allowed to login to the storefront

**Comment by giancorderoortiz** [comment]
Disabling login in password tab is also required. 
When this is done, user is tagged as disabled by OCC API, and thus prevented from logging into Spartacus. 

![Screen Shot 2021-06-09 at 3 16 20 PM](https://user-images.githubusercontent.com/46171897/121415843-228cc580-c936-11eb-9340-d1d5165b159b.png)

![Screen Shot 2021-06-09 at 3 20 38 PM](https://user-images.githubusercontent.com/46171897/121415992-4f40dd00-c936-11eb-826e-6c0bcee084c2.png)

**Comment by giancorderoortiz** [comment]
@psmul pending verification with 1905. 
Test done with 2011 is successful. 

I leave it up to you to close this ticket.

**Comment by giancorderoortiz** [comment]
@dunqan @hackergil fyi
