### ISSUE TITLE
Coupons not published sampledata issue

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7489]
After server reinitialization not all needed coupons are published.

Eg. `midautumn`, `dragonboat` coupons are not working as expected.

Because of this missing data few e2e tests are failing (my-coupon, coupon, save-for-later)

**Comment by hackergil** [comment]
This will be addressed by #7341

**Comment by Xymmer** [comment]
Lumping all coupon issues into flaky bucket to deal with at once

**Comment by hackergil** [comment]
Sample data PR https://github.tools.sap/cx-commerce/spartacussampledata/pull/165

**Comment by hackergil** [comment]
PR has been merged. Need to update backend server images with it.

**Comment by hackergil** [comment]
Promotions related to test coupons are being updated but not being published. When we import the sample data, we can see some errors like the following

> due to [de.hybris.platform.servicelayer.interceptor.impl.UniqueAttributesInterceptor@71f5f512]:ambiguous unique keys {version=0, code=FreeGiftCouponProm} for model PromotionSourceRuleModel (<unsaved>) - found 1 item(s) using the same keys, 

Need to investigate how to fix this

**Comment by hackergil** [comment]
https://github.tools.sap/cx-commerce/spartacussampledata/pull/178

**Comment by hackergil** [comment]
Sample data fix merged
