### ISSUE TITLE
Avoid unnnecesary emissions from page meta service for PLP

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7490]
There are various issues with the observable returned from `PageMetaService.getMeta()`:
1. When visiting PLP (i.e. http://localhost:4209/electronics-spa/en/USD/Open-Catalogue/Cameras/Webcams/c/577), it emits twice:
   ![image](https://user-images.githubusercontent.com/4001059/81196325-317ca800-8fbf-11ea-9ad0-446bef0a616a.png)
   1. once with incomplete data - only `title` based on the category name
   2. second time complete - also with `breadcrumbs` - when breadcrumbs are loaded in a additional backend call (together with facets)

   *Note: It's debatable whether it's an issue or progressive loading feature.*

1. Then when going from PLP to a cart page (for example) and then to a **different** PLP- it unnecessarily emits the meta for the previous PLP (twice! - once with totally old data and second time with reset breadcrumbs). We shouldn't emit old data at all. Moreover the second emission happens in the same change detection cycle but lately, after the breadcrumb component has been rendered - which causes `ExpressionChangedAfterItHasBeenCheckedError` (see #7413). 

   *Note: The late second emission is caused by the synchronous reset of the search results that is done in `ngOnInit` of the product-list.component, which is rendered after the breadcrumb component. So #7413 should be fixable only be moving the reset of the search results from `ngOnInit` to `ngOnDestroy` of the product-list.component.*

   Then eventually the correct meta are emitted (twice):
   ![image](https://user-images.githubusercontent.com/4001059/81198845-3a22ad80-8fc2-11ea-996c-a0b2a08ddb74.png)

**Comment by bgambocjaviniar** [comment]
breaks `infinite scroll e2e` https://sap-cx.slack.com/archives/GAC8PULNN/p1589489377446400?thread_ts=1589381246.416200&cid=GAC8PULNN

found out from my analysis in https://github.com/SAP/spartacus/issues/7614
