### ISSUE TITLE
Perf: avoid computing meta resolver and its methods for each consumer separately

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#7493]
Currently `PageMetaService.getMeta()` is used in 3 places and for each of them we calculate separately the page meta resolver and calculate the methods with particular meta. We should do it once and share the results for subscribers:

- create a new `private meta$` observable once and return it from `getMeta()` (not to create it separtately for each caller)
- pipe the `shareReplay({ bufferSize: 1, refCount:true})` at the end of the `private meta$` observable to share the result value for each subscriber

**Comment by Xymmer** [comment]
Stan to look into the status of this one
