### ISSUE TITLE
type code 'CustomerCouponForPromotionSourceRule' invalid

### ISSUE THREAD

**Issue by dvenkatsagar** [SAP/spartacus#7500]
## Environment Details

- Spartacus:  1.5.4
- OS: Windows 10 - v1809 - 8 GB ram - 500GB hard disk
- Other environment details: Angular 8/JAVA 1.11 - SAP Commerce Suite 1905.13

## Steps to Reproduce

- Following the documentation to setup the Spartacus along with the SAP Commerce Suite 1905.13 (https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud/) using the sampledataaddon given in this repository for the version 1.5.4. 
- Successfully initialized the spartacus installer recipe (step 13 in the docs).
- I try to do step 14 in the docs. I initially get an error in between saying that `customerCouponCodeValueResolver` bean is not available, like in #5662.
-  Installed the `customercouponoccaddon` as suggested.
- Do an `ant clean all` and try step 14 again.

## Observed Results

A error shows up in between.
```
ERROR [solr indexer thread] [FlexibleSearch] Flexible search error occured...
ERROR [solr indexer thread] [FlexibleSearch] Query translation was not successful.
ERROR [solr indexer thread] [DefaultIndexerWorker] [Indexer worker 0 (UPDATE index operation on electronicsIndex/Product)] failed to process index items due to Failed to index item with PK 8796220293121: Failed to resolve values for item with PK: 8796220293121, by resolver: customerCouponCodeValueResolver, for properties: [customerCouponCode], reason: type code 'CustomerCouponForPromotionSourceRule' invalid
de.hybris.platform.solrfacetsearch.indexer.exceptions.IndexerException: Failed to index item with PK 8796220293121: Failed to resolve values for item with PK: 8796220293121, by resolver: customerCouponCodeValueResolver, for properties: [customerCouponCode], reason: type code 'CustomerCouponForPromotionSourceRule' invalid
```
and also the command keeps on executing without finishing.

## Additional Information
I believe this may be a valid issue, but I can be wrong. Any solution for this is much appreciated.

Thank you

**Comment by Xymmer** [comment]
@dvenkatsagar we triaged your issue. we think this is more backend issue and not Spartacus, can you create a backend support ticket? closing but if you need to discuss further contact me.
