### ISSUE TITLE
[OUT OF DATE, Delete when schematics ticket is created] Handle breaking changes for the whole feature

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#7509]
We will handle the breaking changes for the whole feature in this ticket.

**Comment by WeizhengSap** [comment]
To reviewer:

This is also a breaking change, but we don't have such case in `schematics migration 2.0`. We need build an upgrade mechanism for it. So, I did not add this change in 3.0 data. If we don't have the upgrade mechanism for it, I will revert back this change.

![Screen Shot 2020-06-23 at 2 18 57 PM](https://user-images.githubusercontent.com/44440575/85440876-80c16c80-b55c-11ea-9956-748ffad81511.png)

**Comment by LTiger14** [comment]
PR: #8971

**Comment by LTiger14** [comment]
Doesn't block RC, keeping it open until the schematics ticket is created as the real source of truth.

**Comment by LTiger14** [comment]
Duplicate of #9594
