### ISSUE TITLE
Cart service and CartDataService schematics

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7510]
When using schematics to upgrade from 1.5.2 to 2.0 on a project I ran into the following issue with `CartDataService` and `CartDataService`.

Schematics added these in the imports as expected
```
// TODO:Spartacus - 'CartService' is no longer part of the public API. Instead use 'ActiveCartService'.
// TODO:Spartacus - 'CartDataService' is no longer part of the public API. Instead use methods from 'ActiveCartService' and 'AuthService.'
```

But I would have expected a comment above this use to explain what to replace it with since this is deprecated:
`const hasCart = this.cartDataService.hasCart && this.cartDataService.cartId !== undefined;`

It was also missing for the `getCartMergeComplete()` method.

**Comment by marlass** [comment]
Not worth it imo. We described in migration guide that these 2 doesn't have direct replacement and shouldn't be used.
Closing.
