### ISSUE TITLE
Broken order-history-order-flow-mobile e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7518]
Base the mobile test on desktop version which is flaky (not broken)

**Comment by giancorderoortiz** [comment]
Similar situation as https://github.com/SAP/spartacus/issues/7522.

Issue #7996 blocks this e2e test.

**Comment by giancorderoortiz** [comment]
Date format is wrong. In German should be day first, not month. 

![Screen Shot 2020-07-02 at 9 24 29 AM](https://user-images.githubusercontent.com/46171897/86364389-1b4d3a00-bc46-11ea-9731-7e3bab455fec.png)

**Comment by giancorderoortiz** [comment]
Cypress test "passes", but manual testing clearly indicates an issue. 
So, a false positive.

**Comment by Xymmer** [comment]
passing as of oct2

**Comment by Xymmer** [comment]
This was marked as [BLOCKED by #7996] but #7996 is closed, but the test is still flaky

**Comment by hackergil** [comment]
Fixed already
