### ISSUE TITLE
Flaky mobile asm e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7527]
Evaluate if it is still flaky and fix underlying issue.

**Comment by giancorderoortiz** [comment]
I don't see this test /cypress/integration/mobile/asm-mobile.e2e-spec.ts as flaky anymore. 
Works well with 2005 backend. 🆗 
Ran localhost in headless mode and interactive several ways. No issues found.  🆗 
Checked last runs in CI. Test passes. 🆗 

Only see a random delay when updating personal details, but the test eventually passes. ⚠️

**Comment by giancorderoortiz** [comment]
video here: [asm-mobile.e2e-spec.ts.mp4.zip](https://github.com/SAP/spartacus/files/4836731/asm-mobile.e2e-spec.ts.mp4.zip)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-06-26 at 7 53 41 AM](https://user-images.githubusercontent.com/46171897/85854661-d0817d00-b782-11ea-836b-6891fbe11ccb.png)

![Screen Shot 2020-06-26 at 7 55 40 AM](https://user-images.githubusercontent.com/46171897/85854677-d7a88b00-b782-11ea-87fb-4d5374ff64a0.png)
