### ISSUE TITLE
Flaky smoke outlets e2e test

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7528]
Evaluate if it is still flaky and fix underlying issue.

**Comment by giancorderoortiz** [comment]
I don't see this test failing anymore. It's very consistent. 
Running against 2005 backend. 
No failures seen in CI.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-06-26 at 10 49 34 AM](https://user-images.githubusercontent.com/46171897/85870975-c7e97080-b79b-11ea-8a81-b66e20f10919.png)

![Screen Shot 2020-06-26 at 10 51 16 AM](https://user-images.githubusercontent.com/46171897/85870985-cc158e00-b79b-11ea-8a4a-790550099ee7.png)

**Comment by giancorderoortiz** [comment]
Closing ticket.
