### ISSUE TITLE
[doc] Package '@spartacus/schematics' is not a dependency.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7546]
When following the instructions in the migration doc: https://github.com/SAP/spartacus-docs/blob/v2-develop/_pages/home/updating-to-version-2/updating-to-version-2.md

I ran the command:

`ng update @spartacus/schematics`

And got this error:

`Package '@spartacus/schematics' is not a dependency.`

I read the schematic readme and figured out I needed to install the schematics beforehand.  I used this command to resolve the issue.

`ng add @spartacus/schematics`

Likely many apps have not yet installed the schematics and will run in the same issue.  Perhaps we could update the migration to include this step/prerequisite.

**Comment by znikola** [comment]
PR: https://github.com/SAP/spartacus-docs/pull/593
