### ISSUE TITLE
Schematic insert additional/duplicate/conflicting configs in app.module

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7547]
Installing the upgrade schematics in the bootcamp app had a side effect I wasn't expecting and that doesn't look right to me.  

I ran the command:

`ng add @spartacus/schematics`

And the schematics added this additional config code block in app.module:
```
    B2cStorefrontModule.withConfig({
      backend: {
        occ: {
          baseUrl: 'https://localhost:9002',
          prefix: '/rest/v2/'
        }
      },
      i18n: {
        resources: translations,
        chunks: translationChunksConfig,
        fallbackLang: 'en'
      },
      features: {
        level: '1.5',
        anonymousConsents: true
      }
    }),
```

The app.module file already has this config:

```
   B2cStorefrontModule.withConfig({
      backend: {
        occ: {
          baseUrl: environment.occBaseUrl,
        },
      },
      context: {
        baseSite: ['electronics-spa'],
      },
    }),

    // demonstrate i18n
    ConfigModule.withConfig({
      i18n: {
        resources: translations,
        chunks: translationChunksConfig,
        fallbackLang: 'en',
      },
    }),

```
I removed manually the new configs. I don't expect the schematics installation to mess with the app's configs.  Looks like a bug to me.

**Comment by znikola** [comment]
We have a fix for this issue on 2.x branch, but it's not ported to 1.5.x branch. We can discuss if it's worth porting it to 1.5.x
