### ISSUE TITLE
ng update @spartacus/schematics gives `Package '@spartacus/schematics' is already up to date.`

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7565]
After following updated steps https://github.com/SAP/spartacus-docs/pull/595/files

...running `$ ng update @spartacus/schematics` gives:

```
Using package manager: 'yarn'
Collecting installed dependencies...
Found 51 dependencies.
Fetching dependency metadata from registry...
Package '@spartacus/schematics' is already up to date.
```

**Comment by znikola** [comment]
This command uses the latest stable (1.5.x) schematics from npm. Make sure to append `--next` flag in order to use the _rc1_ schematics.
