### ISSUE TITLE
[Listing page] Buttons collapsed to menu list for Mobile view

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#7576]
![image](https://user-images.githubusercontent.com/8040837/82207843-c611cf00-990a-11ea-80d3-ec969d6ec76d.png)
Look for 'change user roles' and 'new user' example

**Comment by Xymmer** [comment]
still needed given recent refactorings?

**Comment by Pucek9** [comment]
> still needed given recent refactorings?

IMO nope
