### ISSUE TITLE
Schematics pwa duplicating content

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7587]
If you install @angular/schematics with --ssr and then you do the same with --pwa, the following code block for app.module config is duplicated:

>
    B2cStorefrontModule.withConfig({
      backend: {
        occ: {
          baseUrl: 'https://localhost:9002',
          prefix: '/rest/v2/'
        }
      },
      i18n: {
        resources: translations,
        chunks: translationChunksConfig,
        fallbackLang: 'en'
      },
      features: {
        level: '1.5',
        anonymousConsents: true
      }
    }),

**Comment by psmul** [comment]
Hey, @hackergil can you re-test this? I believe fix to this issue was released in recent version

**Comment by hackergil** [comment]
Yup, fixed. Closing.
