### ISSUE TITLE
Default address checkbox should not be displayed on checkout if there are no addresses

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#7617]
**Environment Details**
Spartacus: develop branch
Browser: Chrome/FF Developer
Device: mac
Calydon: disabled

**Details**
If the account has no addresses in his/her address book, the checkbox to set the address as default should not be displayed (Should automatically be default since the user has no addresses to start with)

<img width="729" alt="Screen Shot 2020-05-13 at 4 25 19 PM" src="https://user-images.githubusercontent.com/30666844/81861613-8461dc80-9536-11ea-8948-10afa7c6d212.png">

**Comment by hackergil** [comment]
Is this still on hold? If not, can you update the ticket name?

**Comment by hackergil** [comment]
I did a small rename. You can merge after everything passes.

**Comment by giancorderoortiz** [comment]
Test successful.
Set as default not seen when no previous address present. 

![Screen Shot 2020-06-14 at 1 40 57 PM](https://user-images.githubusercontent.com/46171897/84600061-b8d1fc80-ae44-11ea-920b-976a8c093326.png)
