### ISSUE TITLE
[doc] Blank page error after upgrading bootcamp app to 2.0

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7620]
After updating to 2.0 the storefront doesn't work and displays a blank page.

I tracked down the cause and it's because Spartacus 2.0 defaults to the occ prefix path of `/occ/v2/`.  Probably 99% of the customers will still be using `/rest/v2` and the upgrade will introduce a configuration issue for them.

I worked around/ fixed the config by adding `prefix: '/rest/v2/',`

```
B2cStorefrontModule.withConfig({
      backend: {
        occ: {
          baseUrl: environment.occBaseUrl,
          prefix: '/rest/v2/',
        },
      },
      context: {
        baseSite: ['electronics-spa'],
      },
    }),
```

Do we really want to upgrade to a default config that will break all/most of the storefronts?  Perhaps we leave the default to  `'/rest/v2/'`.  It might be a discussion worth having.

If we stick with  `'/occ/v2/'`, we need to clearly document this and make it obvious in the upgrade guide that this config likely needs to be changed for most people.  Is there otherwise something the schematics could do facilitate the upgrade in this regard?

**Comment by tobi-or-not-tobi** [comment]
Good catch, i think we should indeed fix this. The pre-2005 default is for sure used by 99% customer, as the backend is not updated so fast. I'm in favour of setting the default back to `/rest/v2`. 

@znikola was playing with the idea to add an option in schematics to automate this. That's not mandatory for 2.0, but this adds a bit more priority to it; new (internal) devs will soon face this as an issue, and we offer them the option to automate it, it's likely a better experience.

**Comment by znikola** [comment]
Thank you @tobi-or-not-tobi , I created these two PRs:
- develop - https://github.com/SAP/spartacus/pull/7642
- port - https://github.com/SAP/spartacus/pull/7641

For the schematics part, are you referring to this argument: https://github.com/SAP/spartacus/blob/develop/projects/schematics/src/add-spartacus/schema.json#L22 ?
By default it will be `/rest/v2` for new projects, but customers can specify another value, should they need to.
