### ISSUE TITLE
Implement support for search templates / different search endpoints

### ISSUE THREAD

**Issue by ESchuderer** [SAP/spartacus#7625]
Hybris Documentation: https://help.sap.com/viewer/d0224eca81e249cb821f2cdf45a82ace/2005/en-US/75b25a6113c34682907443e0af68b0b4.html?q=suggestions

Hybris is using search templates to provide different SOLR Index configurations for the general search and the suggestions endpoint. Unfortunately in Spartacus there is currently no way to use two different templates without replacing most of the search related services from the Spartacus library.

It would be great if there was a way to configure different search endpoints for different search components.

**Comment by Xymmer** [comment]
Hey Eschudere! I'm closing this ticket but I've recorded this request into my feature backlog. We'll investigate what's doable with current APIs but indeed we'd want to support this.
