### ISSUE TITLE
Possibility to close tabs in mobile version

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#7629]
## Environment Details

- Angular: Angular 9
- Spartacus:  1.5
- Browser: ALL
- OS: ALL
- Other environment details: MOBILE

## Steps to Reproduce
It is not possible to close the open tab in the mobile version.
When the content is huge, scrolling all to see the next tab is very annoying. It can be nice if in the mobile version, closing the open tab is possible.
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/17834635/81922118-f17b7d80-95db-11ea-83ec-3e8d609bd38a.gif)

## Observed Results

When there is a lot of content, is too long to scroll to see the rest of the content.

## Expected Results
Possibility to close the open tab

## Offer to Fix
I will try.

**Comment by Xymmer** [comment]
@sebastianfdez thanks for reporting this issue! Let me know if you have a fix and we'll bring it into 2.1 (aiming for June/July).

**Comment by temitopeog** [comment]
@sebastianfdez - has this issue been fixed or the bug remains? Could you share more information please? For instance, wher would you suggest to have the minimisation capability? So to open a tab without scrolling all the way to the bottom, can you suggest how this approach would look like

thanks
Temi

**Comment by sebastianfdez** [comment]
Hi @temitopeog. No I didn't have the time to try to code a solution.

Nowadays, when you are in the mobile version you have to always have an opened tab.

So in order to get to the next tab (B) without scrolling all the opened tab (A), you could just click tab A 'header' to close it. The actual behavoir is for closing tab A you have to open tab B.

It can be nice to have the possibility to have all tab closed (on the mobile version)

Sebastian

> @sebastianfdez - has this issue been fixed or the bug remains? Could you share more information please? For instance, wher would you suggest to have the minimisation capability? So to open a tab without scrolling all the way to the bottom, can you suggest how this approach would look like
> 
> thanks
> Temi

**Comment by temitopeog** [comment]
Thanks for the information @sebastianfdez do you have a link to the page / more information on how to reproduce this? I've had a look at the mobile menu & it was not there. So i think its affecting one of the pages I'm unaware of. 

Is this b2b or b2c?

thanks

**Comment by sebastianfdez** [comment]
Hi @temitopeog 

You can reproduce the problem doing this:
- Going to any product page, for example [this one](https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/de/USD/product/1432722/Gigashot%20K80H).
- Inspect element an add an enormous text in the content of the first tab (Product details)
- Make it mobile

You will have to scroll all the content down to reach the second tab. In our B2B the first tab is a huuuge table with plenty of information, so in the web version is OK (just clicking the second tab) but in the mobile version is exhausting.

Hope you get it !

Sebastian

**Comment by temitopeog** [comment]
Hi @sebastianfdez , the solution that I propose is shown on the screenshots. We probably just need to decide on the number of characters that need to be filtered before the text is cut with a ...show more

Please let me know if you have an idea. For now, I'll leave it as 600 characters which works with Mobile & Desktop experience

<img width="484" alt="Screen Shot 2020-06-26 at 12 31 55" src="https://user-images.githubusercontent.com/49304398/85853286-24ec2300-b7aa-11ea-933c-67e87d4b3d30.png">
<img width="558" alt="Screen Shot 2020-06-26 at 12 32 05" src="https://user-images.githubusercontent.com/49304398/85853288-261d5000-b7aa-11ea-8a0c-f87418762247.png">

Thx
Temi

**Comment by sebastianfdez** [comment]
I was thinking more about being able to close an open tab, but if it is the only solution, it's ok.

Thanks !
