### ISSUE TITLE
[retest] Mobile Menu not functioning as designed

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7643]
This issue was originally reported by Carl Eric Lavoie or professional services in the Montreal office during his research with stakeholders.

The design team is creating this bug ticket on his behalf, and we agree completely with his assessment.

Of note: All of our customers are currently fixing this bug immediately upon commencement of their project.

On Mobile Menu (assuming tablet as well), the header greys out when the menu is active. The hamburger menu should change to an 'X' when the menu is open, buyt the other header options (Cart. account, etc...) should be fully visible and selectable by the user when visiting the menu.

The menu items themselves should not scroll unless there are too many to fit in a single screen. If there are too few items, suitably grey color should fill the remaining space below the menu items.

There should be NO visible / greyed out content of any type seen below the menu items, by scrolling or without scrolling. Below the header, only menu items or grey filler space should be viewable.

'Positive example' image to be provided shortly by design team.

**Comment by vekterdude** [comment]
![Tablet – MENU](https://user-images.githubusercontent.com/44620139/81988019-bd6a8180-9608-11ea-9f08-f112a2d18247.png)

**Comment by vekterdude** [comment]
![Mobile – Long MENU](https://user-images.githubusercontent.com/44620139/81988303-38cc3300-9609-11ea-991a-31779e6187f9.png)

**Comment by Xymmer** [comment]
retest as i think tobias spotted this also and did a fix for 3.0

**Comment by giancorderoortiz** [comment]
Update with develop branch (May 17, 2021)

![Screen Shot 2021-05-18 at 7 31 22 AM](https://user-images.githubusercontent.com/46171897/118668968-548d8a80-b7c3-11eb-9558-9fc05efb209e.png)
![Screen Shot 2021-05-18 at 7 31 56 AM](https://user-images.githubusercontent.com/46171897/118668969-55262100-b7c3-11eb-9374-babb7f5aec02.png)
![Screen Shot 2021-05-18 at 7 32 41 AM](https://user-images.githubusercontent.com/46171897/118668970-55262100-b7c3-11eb-924c-1129adbf2361.png)

**Comment by giancorderoortiz** [comment]
Consulted with @vekterdude. Issue is fixed.
