### ISSUE TITLE
PWA style placeholder ghost images

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7644]
In recent research sessions with Expert Services, the design research team asked them to prioritize some of the Mobile First improvements on our roadmap. To our surprise, they indicated that the grey ‘placeholder’ images was something our customers wanted very badly to offset performance issues and that they were surprised this piece was still incomplete.

He described this topic as “an absolute priority!”

UX has been working on standards for this recently and have indicated these parameters should form our guideline standard….

Hex Color: #F2F2F2
 Highlight color: TBD
 (highlight color is the darker color used in the overlay animation)
 Pattern: linear-gradient
Sharpness: 10%
Horizontal vs. Vertical: Vertical
Rate of (Animation) Speed: 1.5 seconds

**Comment by Xymmer** [comment]
added this to my backlog of unplanned features, we'll consider during second half of 2020 or sooner depending on the entire priority list we get from Carl
