### ISSUE TITLE
Spike - Picture Type vs. Source Sets

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7645]
This is a technical issue that may be for UI devs…not sure.

Carl Eric Lavoie from professional services said that our customers are all using Picture Type tags to support or in addition to  Sourcesets <src> and that our ootb product should better support this strategy. (full stop)

**Disclaimer: As a non-technical researcher in this matter I cannot elaborate on what that support entails. Here is a fairly comprehensive explanation of the topic from Smashing magazine:
 https://www.smashingmagazine.com/2014/05/responsive-images-done-right-guide-picture-srcset/**
 
An excerpt:
“Once we tell the browser how many pixels it needs (via a new attribute, sizes) and how many pixels each of the sources has (via w descriptors in srcset), picking a source becomes trivial. The browser picks the smallest source that will still look reasonably crisp within its container.”
 – Smashing magazine

Could we spike this and see if there is something we can do to better support our customers on this emerging best practice?

**Comment by Xymmer** [comment]
added to my backlog but we'll have to spike as you suggested and come back with a set of tickets
