### ISSUE TITLE
Install Spartacus 3 RC on ccv2

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7648]
Update CCv2 instances to CX 2011 and latest spartacus 3.0 RC

**Comment by hackergil** [comment]
2.0 build failed on CCv2. With SSR:

> FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':createJsAppsSSRImageStructure'.
> file /opt/workspace/build/customer-project/js-storefront/spartacus2/dist/server.js doesn't exist!

Without SSR, build just silently fails. Unable to access the logs.

Model T team needs to help us with this one

**Comment by hackergil** [comment]
Created MTD-13540 on Model T project board to follow up

**Comment by hackergil** [comment]
On hold until we get our own CCv2

**Comment by Xymmer** [comment]
was able to get ssr running on our new ccv2; however it uses the workaround as ccv2 builder doesn't understand angular 9 ssr yet. (see https://sap.github.io/spartacus-docs/ssr-ccv2-issue-spartacus-version-2/)


will close this issue when they update

**Comment by janwidmer** [comment]
@Xymmer will that ticket be fixed for upcoming release 3.0.0?

**Comment by giancorderoortiz** [comment]
CX version deployed is 2011.

**Comment by Xymmer** [comment]
this is not super urgent for 3.0 but should be done around same time
