### ISSUE TITLE
No promotion applied on cart total when coupon is applied

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7649]
**Describe the bug**
No promotion applied on cart total when coupon is applied.

**To Reproduce**
1. Go to product 300938
2. Click on Add to cart
3. Go to cart page
4. Apply this coupon "CouponForCart"

**Expected behavior**
There's no "You saved $xx.xx" sentence and the promotion isn't applied to the cart. Is it sample data? Am I missing something?

**Screenshots**
<img width="1436" alt="Screen Shot 2020-05-14 at 10 58 02 PM" src="https://user-images.githubusercontent.com/45409515/82006878-cbcf9200-9636-11ea-9b58-b71c9bad5bcb.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina
 - Browser; Chrome
 - Version 81.0.4044.113
 - Tested locally against dev17 backend.

**Comment by Xymmer** [comment]
Sample data issue. This is a coupon that doesn't have any associated promotion with it.
