### ISSUE TITLE
Inconsistent drop down behaviour in mobile devices (device SDK vs custom Spartacus component)

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7668]
As reported in research interviews with professional services, the following topic was indicated as an issue that has been identified by a large number of customers. (Interview with Carl Eric Lavoie, SAP Professional Services Montreal, Canada.)

Some dropdowns on mobile devices still use the device SDK or browser component instead of the built-in SPA component. Customers would like to perform group actions on all drop downs through a single theme change.

Example:
Go to a product listing page (PLP) and compare the sorting options drop down vs. the language switcher in the header.

**Comment by Xymmer** [comment]
Hey vekterdude! can you provide two examples, one that represents what is good and one that is not doing what we want?

also is there a recommendation to use mobile device for menus for ease of use, readability, etc.? i.e. i click on a menu, i should get the device's menu operation and not reinvent the wheel
