### ISSUE TITLE
Register and stay logged in

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7669]
As reported in research interviews with professional services, the following topic was indicated as an issue that has been identified by a large number of customers. (interview with Carl Eric Lavoie, SAP Professional Services Montreal, Canada.

When user go to register a site, after successful completion of the registration form they are taken to the page where they must 'login' using the password they just created and verified in the last step.

This is not best practices and could result in a poor conversion rate for occasional buyers.

Once buyers have completed a successfully validated registration form they should be returned to the point they requested or where prompted to create an account.

Carl Eric suggested that the correct behaviour in SPA used to be this 'best practices' one, but that recently, the extra need to re-login has appeared as the default experience. In other words, the coding of this may already be done, but turned off, or not set as default.

Please make this the default behaviour for all ootb deliveries.

**Comment by Xymmer** [comment]
closing as we can't do this right now for technical reasons. I have it in my ultimate backlog though under "blocked" to bring back when we can.
