### ISSUE TITLE
Homepage Elements are not showing well in the Mobile view

### ISSUE THREAD

**Issue by vekterdude** [SAP/spartacus#7670]
As reported in research interviews with professional services, the following topic was indicated as an issue that has been identified by a large number of customers. (interview with Carl Eric Lavoie, SAP Professional Services Montreal, Canada.)

Image and font sizes on the homepage are not responding in a responsive way in the Mobile version. This makes the mobile version hard to effectively demo. Customers notice the issue immediately. (See image)

"Text like 'Shop Now' on homepage is too small. It's more of a 'perception' value add – feels like a bug" - Carl Eric Lavoie

**Comment by vekterdude** [comment]
![screenshot_2020-05-14_at_16 20 45](https://user-images.githubusercontent.com/44620139/82086370-6faf5100-96bc-11ea-96c1-68063e6f496a.png)

**Comment by Xymmer** [comment]
added to my mobile revamp backlog, we'll prioritize and create tickets with devs when we start to put people on this project
