### ISSUE TITLE
Does not load newly created content page through SmartEdit

### ISSUE THREAD

**Issue by LiudmilaA** [SAP/spartacus#7708]
**Describe the bug**
After creating a new ContentPage using SmartEdit and after going to this page in SPA there is the following request made:
```
https://localhost:9002/rest/v2/electronics-spa/cms/pages?fields=DEFAULT&lang=en&curr=USD&cmsTicketId=6477945639305488eef5a241-fe5d-4ebb-acb2-c1ca2ecbdaa1&pageLabelOrId=cmsitem_00009000&pageType=ContentPage
```
where cmsitem_00009000 is the uid of the new page.
The request NEVER reaches the backend and it fails with the error:
```
(failed)
net::ERR_FAILED
```

**To Reproduce**
1. Go to SPA Electronics Content Catalog - Staged
2. Create a new Content Page with any name/label.
3. After clicking Done in SmartEdit Generic Editor the new page will start loading
4. See error described above

**Comment by Xymmer** [comment]
@LiudmilaA could you provide details such as backend used, Spartacus library, if you can repro with plain Spartacus?

**Comment by stepan-aleksandrov** [comment]
Hello @Xymmer, 
it was actually me (Stepan from SmartEdit) who opened the ticket (used my wife's account by mistake).
Actually I used latest SmartEdit develop with latest hybris platform. I also used latest Spartacus develop.

**Comment by Xymmer** [comment]
Looks like this is fixed as we discovered that it was a caching issue.
It may or may not have been with @stepan-aleksandrov :) so let me know if you need more information.
