### ISSUE TITLE
Spike B2B Order History list and create tickets [depnds on 7759]

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7710]
Add PO # and potentially cost center to the b2b order history.

See the Listings section here for detailed spec:
https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Listings

Refinement: Do we create a b2b order history component or modify the existing one?

Refinement: Do we have all the available information available from the facade layer and existing interfaces?  ( cost-center seems potentially missing )

**Comment by bgambocjaviniar** [comment]
[GET] /{baseSiteId}/users/{userId}/orders -get a order (history)

1 - can re-use component as we are just using the response to populate values
2 - purchaseOrderNumber (P.O. Number) and costCenter obj property are missing, therefore we can not get them from the order history api
3 - existing interfaces, such as OrderHistoryList and OrderHistory does not contain the property in 2. , therefore, we would need to add it if we want to get it from this api.
4 - missing facade layer to get cost-center or p.o number if can be taken anywhere and associate them with their respective order.
5 - accelerator does not include cost center as a column in the order history

**Comment by Xymmer** [comment]
This ticket is spike
Outcome of this ticket is to create smaller, actionable tickets to get the topic done.

Team [x] agrees / [ ] diagrees to let Brian bring tickets in.

**Comment by bgambocjaviniar** [comment]
## Overview

Team Spartacus is implementing features for b2b/checkout and this ticket tackles whether to display the appropriate columns if it is b2b or b2c. 

## Limitations

To make it work, we need the information in the order history API that will return the property `purchaseOrderNumber` for P.O number and `costCenter for the name of it in columns when it is b2b. However, the current API for order history does not provide these information.

Before that, we need to discuss the architectural part of implementing b2b components into Spartacus, such that we want to create a new component solely for b2b features or re-use existing components and `dirty` them, where we would be coupling logic (if any). Do we want it to be decoupled or coupled?

## More inforation

You can find more information about what this ticket needs to provide in https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Listings

## issues and tickets

- [x] - have the team speak with Tobias on how to approach tackling b2b features (re-use or re-create)
- [x] - speak to Michal Gruca if he has a solution for this problem as Bill mentioned they did not see a problem to work with this situation. ---> Conclusion from the talk is similar to what we decided. Have the backend append these missing information to the API's response or do some hacky thing, where maybe call under the hood, another API like order details to just get the P.O # and cost center
- [ ] - tickets ... (incoming when I get answers to above)

**Comment by plabadie** [comment]
Accelerator assessment:

We investigated how the Powertools accelerator pulls off the po number in the order history list.
The b2b facades extension adds the PO number in the OrderHistoryData object used to return the order history list.  The JSP view uses the facade's OrderHistoryData object directly and is able to display the PO number

The order history list endpoint however uses a WsDTO object that does not contains neither the purchaseOrderNumber  or the cost center.  Therefore the data is not available in the endpoint's response.

Looks like our options for Spartacus are:
- We don't add po number/cost center in the order history list
- We make 1 extra request for order details per order in the order history list to get the missing info. ( bad, very anti-performance )
- We update the backend to provide the extra fields in the order history endpoint.
