### ISSUE TITLE
Spike B2B add payment info in order details [depnds on 7759]

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7711]
The b2b order details need to handle additional information:

Additional details are needed in the details area:
https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-InfoArea

And we need to handle the account payment type in the "ship area"https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-Ship/Paymentarea

Refinement: Do we create new component/page for b2b or we can update the existing ones.
Refinement: Do we have all the available information available from the facade layer and existing interfaces?

**Comment by bgambocjaviniar** [comment]
[GET] /{baseSiteId}/users/{userId}/orders/{code} - get a specific order

**- using card (credit card)**
--> info area
--> payment area
for both:
1. no need to create new component
2. all information is available from the facade layer

**- using cost center**
--> info area
--> payment area
for both:
1. no need to create new component
2. all information is available from the facade layer


for all: only missing a property in the Order interface and a new interface specific to b2b
1. purchaseOrderNumber as string and costCenter as B2BCostCenterB2BCostCenter, 
as properties in the `Order interface`

2. need to include a new interface called B2BCostCenterB2BCostCenter, which has the following properties:
active: string
activeFlag: boolean
assignedBudgets: BudgetShaddow[],
code: string
currency: Currency
name: string
originalCode: string
unit: B2BUnit

with the above 2. follows two new interfaces
BudgetShadow and B2BUnit

**Comment by Xymmer** [comment]
For the question, 
> Do we create new component/page for b2b or we can update the existing ones.

Whoever takes this ticket, talk to [Louis]/Tobias/Stan

**Comment by Xymmer** [comment]
This ticket is spike
Outcome of this ticket is to create smaller, actionable tickets to get the topic done.

Team [x] agrees / [ ] diagrees to let Brian bring tickets in.

**Comment by bgambocjaviniar** [comment]
## Overview

Team Spartacus is implementing features for b2b/checkout and this ticket tackles whether to display the appropriate columns if it is b2b or b2c. 

## Limitations

We need to discuss the architectural part of implementing b2b components into Spartacus, such that we want to create a new component solely for b2b features or re-use existing components and `dirty` them, where we would be coupling logic (if any). Do we want it to be decoupled or coupled?

## More inforation

You can find more information about what this ticket needs to provide in https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-InfoArea (headline component)
https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-Ship/Paymentarea (shipping component)

## issues and tickets

- [x] - have the team speak with Tobias on how to approach tackling b2b features (re-use or re-create)
- [x] - [DEPENDS on above], but CREATE ticket for implementing the missing information is found in GH-7765
- [x] - [DEPENDS on GH-7765] to create the e2e for `b2b-order-history-orders-flow` is found in GH-7766
- [x] - [DEPENDS on GH-7765] to create the e2e for `b2b-order-history-no-orders-flow` is found in GH-7767
