### ISSUE TITLE
Spike B2B login/registration and create tickets

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7713]
There is no registration on B2B. How do we remove the register button?

**Comment by hackergil** [comment]
Here is what we need to do to support this:
* Registration button is embedded on the `login` component. Suggestion from  @WeizhengSap is to create a new CMS component for this and include it in B2C only. Need to discuss with @tobi-or-not-tobi 
* Do not create a registration page on sample data

**Comment by Xymmer** [comment]
We agreed Gil can create 'hide registeration' button and put into sprint right away
anything related to registration itself is stretch and can be put into the B2B priorities board.
