### ISSUE TITLE
Spike: B2B Categories

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7715]
On category list, b2b has its own API. Therefore we have to implement it in OCC module first to make categories work. It needs some investigation to figure out which APIs are b2b specific (replace the b2c ones)

**Comment by bgambocjaviniar** [comment]
https://github.com/SAP/spartacus/issues/6591

relates to this, but from my findings, the response is similar, but b2c (product  /search) does not return the categoryCode when passing it to the fields, whereas b2b categories api does.
Furthermore, b2b requires categoryCode to be passed, which is not a problem, but how does that work for free text searching, for example using the seachbox 

I think once it flattens out, it can work ootb between b2c and b2b. 

https://cxjira.sap.com/browse/C3PO-2371

**Comment by hackergil** [comment]
The B2B API has the following endpoint to get products by Category:

`/{baseSiteId}/categories/{categoryId}/products`

Unlike B2C, which uses the generic `products/search` endpoint.

If a customer only implements B2B (and no B2C) and he wants to use the B2B Categories endpoint to find all of the products by Category, we need to provide support for the given endpoint. Therefore, we need to implement the usage of this endpoint in Spartacus (which will be addressed by #6591)

It is worth to say that at the moment, PLPs and PDPs work fine using the `products/search` endpoint when filtering by Category. The only small caveat is that we are not displaying the right Category name on the PLPs (and we need a fix for it)

To @bgambocjaviniar comment: For generic product search (from the search box for example) we will use the B2B product Search endpoint, which is the same as the B2C one

**Comment by WeizhengSap** [comment]
The comment looks good to me.
