### ISSUE TITLE
Update docs on compodoc usage

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#7718]
Sometimes, when `generate:docs` command is run compodoc fails. It's due to `@compodoc/compodoc` vs `compodoc` but please double-check this and update the docs accordingly.

**Comment by psmul** [comment]
QA steps:
- `rm -rf node_modules && yarn` in spartacus project root
- `yarn generate:docs`

Expected results:
- process should use Compodoc 1.10 and finish without errors

**Comment by giancorderoortiz** [comment]
generate docs ran without errors.
