### ISSUE TITLE
Update user call for B2B

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#7735]
The default user call `users/{userId}` has some issues for B2B. The default call returns the following error when trying to fetch the user after login: "It's not allowed to execute this call from the current channel". The first call using the API returns the error but refreshing the site will result in the call being successful and returning the user.

For B2B we could use the equivalent B2B call: `orgUsers/{userId}` which does not return an error. That said, this call is only allows you to GET the user. The other methods to update the user are not supported. For all the calls that update the user we should still use the default user endpoint `users/{userId}`.

### Acceptance

- See if the default user kept can be used and not return an error for GET

**If not**

- Use the B2B user call for GET and the other one for other calls

**Comment by Xymmer** [comment]
Needs spiking and (small a) architecture decision, best practice on having duplicated endpoint calls needed (e.g. users vs orgusers that do same thing)

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/7870
