### ISSUE TITLE
Discuss how to introduce b2b features into existing components with Tobias/Stan

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7759]
Is it as simple as "if PO# is there, display using this view" and "if not, don't"

e.g. when you place a B2B order that requires approval, the confirmation page does not display the approval (as order just created so no info yet), but later, approval info will be returns.
AND commerce org is supposed to work in b2c anyway (but current api won't work with it)

**Comment by bgambocjaviniar** [comment]
discussion ended with short term solutions, so that we can continue and not be blocked on tickets and long term solutions that are provided by Tobias in a wiki  https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363
