### ISSUE TITLE
1- Implement B2B Order History information

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7765]
We need to add the missing interfaces and missing properties to the existing Order. Afterwards, populate the order details according to the information we get on a b2b storefront, such as cost center, unit, placed by, P.O.# in the headline and shipping component of order details.

Putting the right information can be found below:
https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-InfoArea (headline component)
https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-Ship/Paymentarea (shipping component)

**Comment by bgambocjaviniar** [comment]
~~PR: GH-7822~~ --> old PR which points to checkout, but we want it in 2.1, therefore now in my-company branch

new PR: GH-7909

**Comment by bgambocjaviniar** [comment]
styling will be on in GH-7908 to handle breaking changes

**Comment by bgambocjaviniar** [comment]
*notes* 
- use any dev server that has electronics/powertools, such as dev-7
- use the powertools-acc storefront to place an order or use the APIs

QA steps:
- place two orders: one for credit card and one for cost centers using a b2bcustomer, like mark rivers in accstorefront under the server you are testing with
- use the same server, but with the spartacus storefront/powertools-spa
- login using the same user used to checkout

**visibility**
- verify there are 2 rows in the headline (styling will be done in another ticket). First row is the normal information, and second row only displays if the user has any orgUnits, or if the user is really a orgCustomer. Make sure you can see the second row in powertools and one row in electronics (using a diff user / random user)
- verify info for both cost centers and creditcard using the requirements listed here for the headline area https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-InfoArea
-verify info for both cost centers and creditcard using the requirements listed here for the shipping/billing info area https://cxwiki.sap.com/pages/viewpage.action?pageId=514209363#B2BOrders-DifferenceswithCore/B2C-Details-Ship/Paymentarea

**Comment by giancorderoortiz** [comment]
PO# and Cost Center are missing in b2b order history page. 
Needs work.

![Screen Shot 2020-06-14 at 11 37 30 AM](https://user-images.githubusercontent.com/46171897/84597813-52dd7900-ae34-11ea-840d-45185a96820d.png)

**Comment by giancorderoortiz** [comment]
PO and Cost Center not available in orders endpoint. 
![Screen Shot 2020-06-15 at 11 00 31 AM](https://user-images.githubusercontent.com/46171897/84676068-0c068680-aefb-11ea-959e-f4b5233248a1.png)
