### ISSUE TITLE
e2e test for B2B order-history-no-orders-flow

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7767]
Create and re-use as much functions in the original e2e to make b2b-order-history-no-orders-flow.ts to work in a b2b storefront, such as powertools.

*note: add additional functions / assertions for test specific to b2b order history

**Comment by bgambocjaviniar** [comment]
~~PR: GH-7830~~ old PR branch for b2bcheckout
new PR: GH-7910 towards my-company for 2.1 release.

**Comment by hackergil** [comment]
I'm grabbing this ticket since it's small enough to experiment with multi-store e2es. Also because of suggested changes from @giancorderoortiz

**Comment by hackergil** [comment]
I am closing this ticket because of the following:
* Order history pages that are empty look exactly the same in both powertools and electronics
* A strategy for multi-store testing needs to be put in place
Creating #7985 to address this
