### ISSUE TITLE
Homepage Inconsistent Image Display When Backend Server is Down

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7779]
Spartacus storefront behaves oddly when backend api service is an unstable state. 

- Using public instance I was able to capture what happens when the api service is going down.
(See below images). The layout/skeleton of the storefront is shown, yet images fail to be displayed. The end result is a highly disorganized view to the end-user. 

- A much cleaner strategy is needed for handling spartacus page loads/views with unstable backends.

- This lack of image updates remains while the service is going down and api calls are in limbo. A page refresh doesn't fix the problem. 

- Once the server is completely down, then refresh works, but then you get a white screen with no indication to the user of what is going on. 

- Dev tools show calls to retrieving media fail with 503. 

---

![Screen Shot 2020-05-26 at 7 55 06 AM](https://user-images.githubusercontent.com/46171897/82898301-0387e500-9f27-11ea-96cb-6c54a5ed5d0a.png)
![Screen Shot 2020-05-26 at 7 55 25 AM](https://user-images.githubusercontent.com/46171897/82898303-04207b80-9f27-11ea-9dd5-4ceb479f4322.png)
![Screen Shot 2020-05-26 at 7 57 49 AM](https://user-images.githubusercontent.com/46171897/82899131-72b20900-9f28-11ea-9968-d123afa30751.png)
![Screen Shot 2020-05-26 at 8 07 14 AM](https://user-images.githubusercontent.com/46171897/82899132-734a9f80-9f28-11ea-90a6-55a690c305c8.png)

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
