### ISSUE TITLE
Cancelling order works, but shows error (also in console)

### ISSUE THREAD

**Issue by kacperknapik** [SAP/spartacus#7781]
**Describe the bug**
When cancelling a placed order, we can do it, but we cannot see any success message. We see an error instead. Even though the order is cancelled in the end.

**To Reproduce**
0. Use 2005 server (dev7)
1. Go to `My Account -> My Orders`
2. Cancel any order you placed before
3. You'll get global message with the error + console error
4. After refreshing the order list, the order will be cancelled.

**Expected behavior**
Go back to order list and optionally show success message. Don't show any errors (also in console).

**Additional context**
Problem probably occurs because of the flaky API.

**Comment by Xymmer** [comment]
some questions:
is it just when you cancel all entries in an order? or happens with partial as well?
does it happen if you do it quickly or all the time, like after consignments are created?
did you ask wei about it?

**Comment by plabadie** [comment]
Unable to reproduce on develop branch + dev0 server.
<img width="1680" alt="Screen Shot 2020-11-16 at 4 33 16 PM" src="https://user-images.githubusercontent.com/7065346/99310819-9431e480-2829-11eb-9f84-77b828afc635.png">
