### ISSUE TITLE
Registration component on B2B and hide from storefront

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#7785]
- [x] Create a new CMS component for registration button. Add it to the B2C catalog
- [x] Make sure there is no registration page on B2B sample data
- [x] Deprecate old behavior
- [x] Add version feature flag

**Comment by hackergil** [comment]
Sample addon PR https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/101

**Comment by KateChuen** [comment]
Assigning to Gil to check since I can still register on b2b on my setup on dev3.

**Comment by hackergil** [comment]
@KateChuen I don’t know why but I can’t browse Spartacus on dev3. Can you take a look?

I've updated spa there and the fix should be good to go.

**Comment by KateChuen** [comment]
Tested on dev3. 
✅ On b2c, Registration still works. 
❌ However, the login form is aligned to the left now. Do we need a styling bug ticket to fix it? -> There's already a ticket to fix this issue: https://github.com/SAP/spartacus/issues/8022
<img width="1194" alt="Screen Shot 2020-07-08 at 11 43 21 AM" src="https://user-images.githubusercontent.com/45409515/86940195-80a29e80-c110-11ea-9b71-a035aea7e3e1.png">



✅ On b2b, the Register button is gone now.
<img width="1193" alt="Screen Shot 2020-07-08 at 11 37 45 AM" src="https://user-images.githubusercontent.com/45409515/86940224-8ac49d00-c110-11ea-93c7-86bd3fd2ec8d.png">


❌However, I'm still able to navigate to the registration form through the url: http://dev-com-3.accdemo.b2c.ydev.hybris.com:4200/powertools-spa/en/USD/login/register
And I'm able to register a user. Should this be blocked as well?
<img width="1190" alt="Screen Shot 2020-07-08 at 11 38 06 AM" src="https://user-images.githubusercontent.com/45409515/86940256-931cd800-c110-11ea-8587-8ac6f9ab03e1.png">

**Comment by Xymmer** [comment]
on the surface we should block access to registration page as well through direct access to url.

for full parity with b2b accelerator, registration was configurable. Is there a chance to make access to this page configurable (in general) through a config setting? this was part of secure portal addon.
or, we make it configurable for 3.0

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by saad-mo** [comment]
Local QA was performed by me some time ago by doing the following: 

1. Enable`b2b` in `environment.ts` 
2. Build and open the local Project and in the browser  
3. Click on 'Sign In / Register' 
4. Observe that there is no Register button on the page 
5. Also verify that you cannot navigate directly to the registration page by going to `/login/register` 

Side Note: A Small UX issue was ignored at the time. The 'Sign In / Register'  link in the header should just say 'Sign In' as self-registration is not possible on b2b anymore. 

Side Note 2: Since I already performed this on local and we discussed on team call that sometimes Local QA is sufficient, not sure if we still need to perform Server QA.

**Comment by giancorderoortiz** [comment]
Test successful 👍

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-25 at 11 34 17 AM](https://user-images.githubusercontent.com/46171897/97111619-38ef5500-16b6-11eb-9c04-ba1a30bd2766.png)
![Screen Shot 2020-10-25 at 11 35 15 AM](https://user-images.githubusercontent.com/46171897/97111621-3987eb80-16b6-11eb-9922-fe7373135c7b.png)

**Comment by giancorderoortiz** [comment]
I see that attempt to access registration page directly redirects to login page in b2b. Which is correct 👍 
![Screen Shot 2020-10-25 at 11 38 58 AM](https://user-images.githubusercontent.com/46171897/97111706-c632a980-16b6-11eb-89ed-e0afeb5155a4.png)
