### ISSUE TITLE
SSR memory leak, possibly in i18n related modules

### ISSUE THREAD

**Issue by ESchuderer** [SAP/spartacus#7802]
**Describe the bug**
Dead references are kept in the heap, which prevents the garbage collector to free up space. The application is crashing with an out of memory error.

Taking snapshots it looks like translation related references are kept in the memory.

**To Reproduce**
1. Start the Spartacus SSR Server (express)
2. Take a heap snapshot of the node application
3. Execute a few requests against the node application
4. Manually execute garbage collection
5. Take another heap snapshot and compare it to the first snapshot

**Expected behavior**
The heap is cleaned correctly, the node application does not crash with an out of memory error.

**Screenshots**
<img width="1238" alt="Screen Shot 2020-05-22 at 13 33 18" src="https://user-images.githubusercontent.com/1319416/83133078-9caf2b00-a0e2-11ea-8e86-3d60c6be5f7b.png">
<img width="1224" alt="Screen Shot 2020-05-25 at 10 06 26" src="https://user-images.githubusercontent.com/1319416/83133080-9de05800-a0e2-11ea-9ab3-5e8372eafae4.png">
<img width="971" alt="Screen Shot 2020-05-22 at 13 11 10" src="https://user-images.githubusercontent.com/1319416/83133084-9e78ee80-a0e2-11ea-8013-4ffbf63a3f34.png">
<img width="908" alt="Screen Shot 2020-05-22 at 13 15 54" src="https://user-images.githubusercontent.com/1319416/83133087-9f118500-a0e2-11ea-871f-9d58685c6c4c.png">

**Setup**
- Spartacus 1.5.6 / 2.0.0-rc.3
- Angular 8 / 9
- Angular Universal with express server

**Additional context**
https://spartacus-storefront.slack.com/archives/CD16V16FR/p1590597214191500
https://spartacus-storefront.slack.com/archives/GSC1S305S/p1590146276000100 (private channel)

**Comment by alanktwong** [comment]
Can you let us know if this issue is the same for Spartacus 1.4.2? Whether any forthcoming fix will depend upon Spartacus 1.5.6 or 2.0.0-rc3?

**Comment by ESchuderer** [comment]
I can still reproduce the issue using Spartacus 1.4.2, there does not seem to be much difference when compared to 1.5.6 / 2.0.0-rc.3.

I can also reproduce the issue for the browser version of Spartacus, though it is not as much of an issue on the browser side as it is unlikely that the user will execute enough requests to run out of memory there.

<img width="1081" alt="Screen Shot 2020-05-29 at 10 44 42" src="https://user-images.githubusercontent.com/1319416/83240798-2cfc7700-a19a-11ea-88f5-2a93cfa5fba1.png">

**Comment by dunqan** [comment]
Thank you all for reporting and provided details. The issue was fixed in versions from 1.4 upwards and 1.4.3 hotfix release is already live (1.5 and 2.0 will follow up soon).
