### ISSUE TITLE
Removing active category filter on category page results in weird state

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#7806]
**To Reproduce**
1. Go to category page (eg. canon)
2. Try to remove active filter `canon`
3. Now you will see all products, but you still see canon as an active filter.
Breadcrumb is now broken and the url suggests that you are on canon page, but you see all products.

**Expected behavior**
Either show generic PLP page or don't allow to remove category applied filter

**Comment by kacperknapik** [comment]
Currently waiting for @tobi-or-not-tobi 's input

**Comment by giancorderoortiz** [comment]
Canon category page: http://cx-qa161814921.eastus.cloudapp.azure.com:4200/en/USD/Brands/Canon/c/brand_10
After "attempting to remove applied filter 'Canon' http://cx-qa161814921.eastus.cloudapp.azure.com:4200/en/USD/Brands/Canon/c/brand_10?query=:relevance

It's a bit akward, but works as intended. 
Perhaps the URL could be polished a bit. 

Attempt to remove filter fails, which is correct. 
Unfiltered products are shown.
