### ISSUE TITLE
Schematics: change occ default prefix to 'occ' (but when?)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7808]
The occ prefix default for 2005 is /occ/. For 1905 it's /rest/.
2005 just came out, when should we change it?
Do we have a way of specifying one way or another?

**Comment by tylermac-sap** [comment]
This will depend on whether someone is running >= 2005 or <= 1905. In spartacus 1.5.6 it's defined in default-occ-config.js and it looks like this is different in 2.0RC. Would be nice to have it configured appropriately as part of schematics but worst case it should be documented. For the Git sample repo I ended up with overriding it in the environments*.ts files and this could be a documented workaround (https://github.com/SAP-samples/cloud-commerce-sample-setup/blob/2005-spartacus/js-storefront/spartacusstore/src/environments/environment.ts )

**Comment by znikola** [comment]
Done as part of https://github.com/SAP/spartacus/issues/8286

@Xymmer I think this can be closed.
