### ISSUE TITLE
New config file to include in sample data addon

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7809]
We'd like to include a sample config.properties with some defaults to make it easier to set up a local system for trying out Spartacus.

The file is attached and is named `custom.properties` (as a zip as GitHub doesn't allow .properties extension, but please include not as zip
[custom.properties.zip](https://github.com/SAP/spartacus/files/4702351/custom.properties.zip)

After discussing with Gil, we agreed it should go into a new folder `installer/customconfig` under resources folder:
`https://github.tools.sap/cx-commerce/spartacussampledataaddon/tree/develop/resources/installer/customconfig`

**Comment by plabadie** [comment]
PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/93
