### ISSUE TITLE
Blank Spartacus HomePage When Backend Under Heavy Load

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7810]
**Backend Setup:** 
Commerce Suite 2005 CF RC. 
Deployed Spartacus recipe, based on CX recipe. 
Deployment on Linux dev-server A

**Frontend Setup:** 
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server) 

**Steps to Reproduce:** 
1. Run Gatling load simulation (load homepage and do a simple search) with 700+ users. 
2. Run Cypress e2e smoke/homepage.e2e-spec.ts several times in a loop. 
3. Attempt to load homepage manually by going to browser. 

**Expected Results:** 
2. Spartacus homepage displays some sort of meaningful message indicating homepage cannot be loaded after x number of seconds. 
2.a. Or a "loading, please wait" message. 
2.b. Or a message indicating homepage load took too long and redirect to I.T / administrator. 
3. Same as 2. 

**Actual Results:** 
2. Blank page. No meaningful information given to end user.
2.a. No information in dev-tools console tab, nor network tab. 
3. Same as 2. 

What Homepage looks like: 

![Screen Shot 2020-05-28 at 8 53 54 PM](https://user-images.githubusercontent.com/46171897/83210056-dfdfbd00-a127-11ea-93a0-e827fcd773eb.png)

**Cypress errors:** 

![Screen Shot 2020-05-28 at 10 41 35 AM](https://user-images.githubusercontent.com/46171897/83210091-f84fd780-a127-11ea-84dd-3b73865cc386.png)

(Notice it took about 45 seconds for test to run. It usually runs under 5 seconds)

![Screen Shot 2020-05-28 at 10 41 44 AM](https://user-images.githubusercontent.com/46171897/83210103-fdad2200-a127-11ea-8aab-4f4a101d11c1.png)

**Some Gatling Simulation Details:** 

![Screen Shot 2020-05-28 at 9 03 27 PM](https://user-images.githubusercontent.com/46171897/83210201-38af5580-a128-11ea-8efd-ee071f852a63.png)
![Screen Shot 2020-05-28 at 9 03 16 PM](https://user-images.githubusercontent.com/46171897/83210209-3f3dcd00-a128-11ea-8141-cef58f492259.png)

**Comment by giancorderoortiz** [comment]
Adding video and screenshots for smoke/homepage e2e test
[homepage_cypress_fail.zip](https://github.com/SAP/spartacus/files/4699127/homepage_cypress_fail.zip)

**Comment by giancorderoortiz** [comment]
![Homepage -- should have footer with footer navigation and notice (failed)](https://user-images.githubusercontent.com/46171897/83210335-95ab0b80-a128-11ea-88a7-6c6c79236d43.png)

**Comment by KateChuen** [comment]
We can improve user experience when the server is taking too long to respond, eg: a progress bar.
There will be another ticket for when the server fails.

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
