### ISSUE TITLE
Product Search Failures When Backend Under Heavy Load 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7811]
**Backend Setup:**
Commerce Suite 2005 CF RC.
Deployed Spartacus recipe, based on CX recipe.
Deployment on Linux dev-server A

**Frontend Setup:**
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server)

**Steps to Reproduce:**

1. Run Gatling load simulation (load homepage and do a simple search) with 700+ users.
2. Run Cypress e2e smoke/product-search.e2e-spec.ts several times in a loop.
3. Attempt to do product searches manually by going to browser.

**Expected Results:**
2. Spartacus displays some sort of meaningful message indicating search is ongoing or that it cannot be completed after x number of seconds. 
2.a. Or a "loading, please wait" message.
2.b. Or a message indicating search took too long and redirect to I.T / administrator.
3. Same as 2.

**Actual Results:**
2. Search doesn't do anything. It just sits there. 
3. Same as 1. 

**Cypress Run Failures and Delays:** 

![Screen Shot 2020-05-28 at 9 30 07 PM](https://user-images.githubusercontent.com/46171897/83211220-8a58df80-a12a-11ea-8aae-35d0c5427755.png)
![Screen Shot 2020-05-28 at 9 30 18 PM](https://user-images.githubusercontent.com/46171897/83211224-8b8a0c80-a12a-11ea-82c7-086d6b43a3d5.png)

**Cypress Screenshots**

![Product search -- Pagination -- should navigate to the next page and display results (failed)](https://user-images.githubusercontent.com/46171897/83211085-3817be80-a12a-11ea-90ee-7c2b638a6ccc.png)
![Product search -- Pagination -- should navigate to the previous page and display results (failed)](https://user-images.githubusercontent.com/46171897/83211089-39e18200-a12a-11ea-96e1-6cc985832faf.png)

**Some Gatling Simulation Details:**

![Screen Shot 2020-05-28 at 9 03 27 PM](https://user-images.githubusercontent.com/46171897/83210959-e838f780-a129-11ea-91c3-88aeb4353df4.png)
![Screen Shot 2020-05-28 at 9 03 16 PM](https://user-images.githubusercontent.com/46171897/83210983-ecfdab80-a129-11ea-9954-39a830f996c0.png)

**Comment by giancorderoortiz** [comment]
[product_search_cypress_fail.zip](https://github.com/SAP/spartacus/files/4699173/product_search_cypress_fail.zip)

**Comment by giancorderoortiz** [comment]
related to #7810

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
