### ISSUE TITLE
Introduce Spartacus metadata to understand the application setup without source code

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7814]
To support customers and understand their setup, we're considering to add high-level application data to the HTML output or public JS interface. Various pieces of info could be useful for a support engineer to get a better idea of problems and failures:
- Spartacus version (i.e. `1.5.1`)
- Feature Flag (i.e. `1.4`)
- Spartacus setup (i.e. `enabled: ['pwa', 'ssr', 'b2b', 'cpq']` etc)
- Backend version (ie. `1905` vs `2005`)
- more? 

There are various techniques to expose the data: 
- populate the app root element (not clean, not scalable, not ideal for complex objects)
- populate the console log (always there, too visible)
- expose a global function with the data (only requires documentation)
- expose a global data object in the window object, part of or similar to a `dataLayer` object (`dataLayer` is reserved for GTM and we should combine it)

**Comment by timothy2005** [comment]
This would be very helpful for the supporting work.
