### ISSUE TITLE
Add support for currency and multiple context items in schematics-dev

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#7820]
When installing spartacus using installation script schematics are used to create apps. Currently there is no support for config's `currencies` (ex. `--currencies=GBP,USD`).
Also multiple context items might be helpful (ex. `--baseSite=electronics-spa,apparel-uk-spa`) - up to discussion do we really need them.
Let's add support for currency so we can install apparel using installation script.

**Comment by giancorderoortiz** [comment]
@Xymmer fyi. prevents frontend deployment of multiple stores. May affect b2b/b2c stores running concurrently.

**Comment by psmul** [comment]
After discussion with @znikola, we've decided to include 3 collections within this task:
1. language
2. currency
3. pre-defined apparel spa config (can you please @mirkosoft define what exactly is needed for this config to be completed and self closed config?)

**Comment by mirkosoft** [comment]
Apparel require only `baseSite` to contain `'apparel-uk-spa'` and `currency` to contain `'GBP'`. For example:
```
    context: {
      baseSite: ['apparel-uk-spa'],
      currency: ['GBP'],
    },
```

**Comment by giancorderoortiz** [comment]
Please make sure proposed solution also makes it possible to have b2b powertools storefront. 
So, in the end, we'd have 3 storefronts running in parallel: electronics, apparel, powertools.

**Comment by giancorderoortiz** [comment]
For powertools, following @mirkosoft example, I'd suggest:
  context: {
      baseSite: ['powertools-spa'],
      currency: ['USD'],
    },

**Comment by psmul** [comment]
After some discussion with @znikola, we've decided not to implement small configuration packages, due to implementing fix/upgrade for schematics, allowing to define currency, language and multi base sites. All works were done in: #7827 and PR: #7833
