### ISSUE TITLE
[Retest] Cancel/Returns: Cancel still appears even if there is nothing to cancel, and disappears shortly thereafter

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7835]
If nothing is cancellable, but there are other things shipped, cancel button still visible for a while. Seems to disappear after trying to cancel nothing once.

Using 2.0 RC.4 and 2005 final release, but unsure of the sample data addon I'm using. (I'm having another problem with Returns tab not appearing for Apparel but it's supposed to work).

To replicate this problem, start an order with a few items, cancel something, ship the others through Backoffice. Cancel button is still visible, and clicking it display a blank list.

To fix: either display a message stating nothing is cancellable, or hide the button.

![image](https://user-images.githubusercontent.com/4998145/83459769-0b69ec80-a433-11ea-9b70-7d23c55acf73.png)

Wei implemented this so ask her about it.

**Comment by KateChuen** [comment]
Tested on http://spartacus-dev0.eastus.cloudapp.azure.com:4200/.
Could not reproduce. As soon as the other items change status to "Shipped", the cancel button disappears, and we have a "Request a Return" button instead.
