### ISSUE TITLE
Smoke Product Search e2e Spec Fails Against 2005 Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7849]
**Describe the bug:**
Failure in cypress test execution of https://github.com/SAP/spartacus/blob/develop/projects/storefrontapp-e2e-cypress/cypress/integration/smoke/product-search.e2e-spec.ts

**To Reproduce:**

1. Deploy 2005 CS backend. Spartacus recipe. (i.e. dev-com6)
1.a. Set spartacussampledata version to origin/release/2005/next
2. Adjust taxes in backoffice base store to US.
3. Deploy spartacus in localhost (develop branch or 2.0rc4)
4. Run product search spec in cypress.
4.a. Make sure it uses new api routing /occ/v2

**Expected behaviour**
4. Product search spec succeeds.

**Actual behaviour**
4. Product search spec fails consistently.

Screenshots:
![Screen Shot 2020-06-02 at 9 53 28 AM](https://user-images.githubusercontent.com/46171897/83528991-c0de8380-a4b7-11ea-8492-94e9c65d8f07.png)

![Screen Shot 2020-06-02 at 9 53 17 AM](https://user-images.githubusercontent.com/46171897/83528638-5af1fc00-a4b7-11ea-9706-e919a90493e6.png)

**Comment by giancorderoortiz** [comment]
[product_search_2005_fail.zip](https://github.com/SAP/spartacus/files/4717577/product_search_2005_fail.zip)

**Comment by Xymmer** [comment]
works as of oct2
