### ISSUE TITLE
Implement B2B Order Confirmation information

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7853]
similar to https://github.com/SAP/spartacus/issues/7765

just need to append the data to the confirmation components

- only applies to the shipping information which is the order-confirmation-overview.component
- there is no approval table in this page.

NOTE: no e2e applies to this, therefore no need.

**Comment by bgambocjaviniar** [comment]
PR: GH-7872

**Comment by bgambocjaviniar** [comment]
requirements changes this from 2.1 to 3.0 from the call I had with Bill on June 5th

**Comment by KateChuen** [comment]
Tested on dev3 against dev16 backend. 
B2b Order Confirmation looks ok.
Tested with both credit card and Account Payment.

<img width="920" alt="Screen Shot 2020-06-19 at 9 23 07 AM" src="https://user-images.githubusercontent.com/45409515/85143386-ac202080-b217-11ea-9718-da34ba7847b1.png">
<img width="807" alt="Screen Shot 2020-06-19 at 9 27 09 AM" src="https://user-images.githubusercontent.com/45409515/85143387-ad514d80-b217-11ea-958a-ae15c51fcd30.png">
<img width="791" alt="Screen Shot 2020-06-19 at 10 26 51 AM" src="https://user-images.githubusercontent.com/45409515/85143390-ade9e400-b217-11ea-9b58-569dbf70ed15.png">

Also verified order confirmation page is still on electronics-spa.
<img width="802" alt="Screen Shot 2020-06-19 at 1 52 34 PM" src="https://user-images.githubusercontent.com/45409515/85166338-21e6b500-b235-11ea-96d8-121ab88b8201.png">
