### ISSUE TITLE
Implement approval table under my-account - order details

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7854]
- create an approval table component for order details under my-account

To implement, when GH-7765 is merged as we do not want to cause conflict.

Note: Bill will verify if we have the information available to us

**Comment by bgambocjaviniar** [comment]
PR: GH-7934

**Comment by plabadie** [comment]
**To test:**

The approval details section will only appear if there are approval detail entries.

Pass a 6000$ order with William Hunter.  This should result in an order pending for approval with 2 approval detail entries.

**Comment by WeizhengSap** [comment]
It works:
![Screen Shot 2020-06-18 at 9 25 16 AM](https://user-images.githubusercontent.com/44440575/85025752-c8ec2380-b145-11ea-9eb3-44b7c9763824.png)
