### ISSUE TITLE
Implement the order approval listing page (history) for my-company

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7855]
Information on how the page should be is found in this page https://cxwiki.sap.com/display/spar/B2B+My+Company-+Approval+Dashboard#B2BMyCompany-ApprovalDashboard-ApprovalDashboard

Basically, we need to have an order approval listing page, which is the same as order-history.component with additional data, such as the approval status.

Note:
- look into this endpoint for this ticket 
```
[GET] /{baseSiteId}/users/{userId}/orderapprovals
- Get orders to approve.
- Returns the list of orders the specified user is allowed to approve.
```

**Comment by plabadie** [comment]
Spartacus PR: #8273

Sample data PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/112/files

Known issues:
GH-8284: Data not cleared on logout.
