### ISSUE TITLE
Display order details on the approval details page.

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#7856]
More information can be found here https://cxwiki.sap.com/display/spar/B2B+My+Company-+Approval+Dashboard#B2BMyCompany-ApprovalDashboard-OrderDetailsforApproval

Basically, re-use the components in order-details as they are cms-driven, and create a new component for the approval/reject button and form.

**Comment by plabadie** [comment]
## Pull Requests

Spartacus PR #8091
_**Note**_ : the branch is `feature/GH-7856-B`

Sample Data backend PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/105

## How to test.
### Use the legacy Powertools Accelerator to set things up. 
- Checkout an order fo 10000$ or more with `william.hunter@rustic-hw.com`.  After approx one minute, the order will be pending approval.
- Go to the bottom of the order history page to see which approver is assigned.
- Sign out `william.hunter@rustic-hw.com` and sign in with the approver that will likely be `hanna.schmidt@rustic-hw.com`.
- In the My Account Menu, go to the approval dashboard and select the order to be approved.
- On the approval details page, the end of the url will be the approval code.  You need the approval code to test the approval details page in Spartacus.

### Display the approval details page in Spartacus
- Invoke the Spartacus Powertools store and sign in with the same approver.
- User the approval code previously taken from the accelerator url to create the Spartacus Url like so (for localhost):
`http://localhost:4200/powertools-spa/en/USD/my-account/approval/{approvalCode}`

You should now see the Spartacus order approval details page.  Here is what to expect:
- The page displays the order details as seen on the order history page.

### Out of scope/Known issues:
- The page does not yet have the buttons to approve/reject the order. (GH-8070)
- The order status does not display well.  (GH-7977)
