### ISSUE TITLE
B2B Organisation refactor

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7861]
We're using cost center as a reference for all b2b org areas.

**Testing**
- given the fact that all cost-center / organization tests share the same things, we introduce the `OrganizationTestingModule`
- we introduced a bunch of test modules in the core / component lib, so that we don't need to introduce mocks over and over again

**List page**
- Move the page title outside the interactive table component, and stick to the default page title location. 
- Drop content projection in the interactive table component for the table title. Make it more complex and doesn't add value.
- Drop bootstrap for the table header layout. Use plain flexbox instead.
- Drop bootstrap for create button and use sass extend to leverage bootstrap behind the scene's

**Routing**
- Introduce child routes
- simplify cms, using a single cms page
- simplify cms component mapping, use a single cms component
- make routes relative in the area

**Component**
- use `ChangeDetectionStrategy.OnPush` on all components
- avoid inheriting component logic, use inheritance or composition at services instead

**UI**
- avoid using the code and name in the list. The name would be the logical name to display, the code will only be relevant to use in the link
- add an inactive state to the UI for inactive cost centers
- consider dropping the complexity between mobiel vs desktop UI. I'd argue it's required, and it complicates both development as well as experience in the mobile UI. 
- ensure that links in cell get the full width/height to simplify clicking on it
- add background color for even rows

**Table**
- add style classes based on each column, using the column key

**Comment by Pucek9** [comment]
https://github.com/SAP/spartacus/compare/feature/my-company...feature/costcenter-ui

**Comment by Platonn** [comment]
Closing, becuase it's merged
