### ISSUE TITLE
Error message displayed after logout on Order History page

### ISSUE THREAD

**Issue by arminh** [SAP/spartacus#7865]
## Environment Details

- Angular: 9.1.0
- Spartacus:  2.0.0
- Browser: Google Chrome Version 81.0.4044.138 (Official Build) (64-bit)
- OS: Ubuntu 18.04.4 LTS
- Device: PC
- Used BE Url: https://api.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com

## Steps to Reproduce
1. Log in
2. Go to My Account => Order History
3. Log out (My account => Sign out)

## Observed Results
Error banner "An unknown authorization error occured" is shown

This error is shown, because after the logout a request is sent to "users/anonymous/orders"  which returns an 401 error (since the anonymous user can't have orders). 

The problem is, that the orders state is cleared on logout, before the OrderHistory component is destroyed. Since the order state changed and the component is still subscribed to it, the application trys to load the list again in the "UserOrderService.getOrderHistoryList" method, only that the user is now anonymous.

## Expected Results
No request is sent to "users/anonymous/orders" after the user logs out on the Order History page

**Comment by kacperknapik** [comment]
Removing myself due to upcoming vacation

**Comment by Xymmer** [comment]
Similar to B2B issue #8515? but that's found in mycompany epic branch that doesn't yet have b2b checkout

**Comment by Xymmer** [comment]
- please verify you can repro with 2.0
- if it's easily repro'd let's fix for 2.1
- if it's hard to repro or we can't figure out a fix, we can postpone to after, like 3.0

**Comment by giancorderoortiz** [comment]
Able to reproduce with Spartacus 2.0. 

![Screen Shot 2020-08-17 at 9 41 36 AM](https://user-images.githubusercontent.com/46171897/90405949-7ad69c00-e072-11ea-829e-f8b8b5fd6cfa.png)

![Screen Shot 2020-08-17 at 9 41 45 AM](https://user-images.githubusercontent.com/46171897/90405881-61cdeb00-e072-11ea-9922-13f67041ff0b.png)

![Screen Shot 2020-08-17 at 10 02 59 AM](https://user-images.githubusercontent.com/46171897/90405885-62668180-e072-11ea-8aae-e75d05e2c88e.png)

![Screen Shot 2020-08-17 at 10 04 14 AM](https://user-images.githubusercontent.com/46171897/90405888-62668180-e072-11ea-974f-b00d18471023.png)

Use: http://spartacus-demo.eastus.cloudapp.azure.com:31415/electronics-spa/en/USD/

**Comment by bgambocjaviniar** [comment]
PR: GH-8636


2.0.x PR: GH-8637

**Comment by bgambocjaviniar** [comment]
QA:

- verify logging out from order history page does not fire the `global error message`

**Comment by mszczepaniak** [comment]
Tested successfully.
