### ISSUE TITLE
Anonymous Consents Fails Against 2005 Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7868]
**Describe the bug**
Anonymous consents is not being stored in local storage. 

**To Reproduce**
1. Navigate to Spartacus storefront. 
2. Clear local storage in dev-tools. 
3. Reload
4. In cookies banner that appears click "Allow All" button
5. Navigate to footer. 
6. Click on "Consent Preferences" 

**Expected behaviour**
6. All consents have a checkmark indicating grant. 

**Actual behaviour**
6. In Chrome / Safari: No consents given. In Firefox, 2 consents given instead of 3. Missing CDS. 
6.a. Upon further inspection, local storage in dev-tools shows the consents were not stored. 

**Screenshots**
![Screen Shot 2020-06-03 at 8 43 39 AM](https://user-images.githubusercontent.com/46171897/83640891-c5b83b80-a57a-11ea-81c0-d33831a3df61.png)
![Screen Shot 2020-06-03 at 8 44 27 AM](https://user-images.githubusercontent.com/46171897/83640894-c6e96880-a57a-11ea-8701-5f8a48b284d0.png)
![Screen Shot 2020-06-03 at 8 49 33 AM](https://user-images.githubusercontent.com/46171897/83640904-cc46b300-a57a-11ea-8e9e-2245fffb1632.png)
![Screen Shot 2020-06-03 at 8 56 17 AM](https://user-images.githubusercontent.com/46171897/83640906-ce107680-a57a-11ea-8140-0e1b69c4a40e.png)

**Desktop:**
 - OS: mac OS Catalina
 - Browser: Chrome, Safari, Firefox.

**Comment by bgambocjaviniar** [comment]
added the exposedHeaders to the commerceservices module through the backoffice
will update docs shortly and backend config shortly

**Comment by bgambocjaviniar** [comment]
DOC PR: https://github.com/SAP/spartacus-docs/issues/631

BACKEND PR: https://github.tools.sap/cx-commerce/c3po-legacy-devconfigs/pull/25
