### ISSUE TITLE
Disable the opportunity to order an incomplete configuration

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#7877]
- Add directly into the cart a digital camera. 
- Try to order the product.
-> It is possible to order the incomplete configuration. It shouldn't be the case

**Comment by ChristophHi** [comment]
We first need to figure out the SPA approach to cart validation. I created an issue in our internal board. At the moment even the cart web service does not call our validation logic

**Comment by giancorderoortiz** [comment]
@tobi-or-not-tobi fyi.

**Comment by giancorderoortiz** [comment]
wouldn't the default values kick in as to "complete" the configuration and allow check out?

**Comment by ChristophHi** [comment]
No....A configuration doesn't necessarily have default values

**Comment by giancorderoortiz** [comment]
@Platonn @Larisa-Staroverova to be fixed in 3.3 ?

**Comment by Larisa-Staroverova** [comment]
@ChristophHi, could you take care?

**Comment by ChristophHi** [comment]
Let's close that as duplicate, as it's addressed in #11902
