### ISSUE TITLE
Support consents in B2B (spike needed)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#7882]
See https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/2005/en-US/1152f63eba2b44889f857b160e93eef5.html?q=powertools%20consent

Can we update our sample data to include what's needed for B2B consent support?

**Comment by LTiger14** [comment]
PR: .../cx-commerce/spartacussampledataaddon/pull/99

**Comment by WeizhengSap** [comment]
It works well.
<img width="972" alt="Screen Shot 2020-06-16 at 10 56 31 AM" src="https://user-images.githubusercontent.com/44440575/84791086-25bdd180-afc0-11ea-8c51-e350b350d76b.png">
