### ISSUE TITLE
Update Unit assign roles view to new wireframe

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#7883]
Need wait for Michał and Bill discuss conclusions

**Comment by Pucek9** [comment]
![image](https://user-images.githubusercontent.com/8040837/84776874-2a46b200-afe1-11ea-9b66-0341838dc5c2.png)

```
orgUnitUsers:
  '/users/${userId}/orgUnits/${orgUnitId}/availableUsers/${roleId}', // GET, only for load users (with their selected flag - roleId) - all roles

orgUnitApprovers:
  '/users/${userId}/orgUnits/${orgUnitId}/orgCustomers/${orgCustomerId}/roles', // POST, assignApprover
orgUnitApprover:  '/users/${userId}/orgUnits/${orgUnitId}/orgCustomers/${orgCustomerId}/roles/${roleId}', // DELETE, unassignApprover

orgUnitUserRoles:
  '/users/${userId}/orgCustomers/${orgCustomerId}/roles', // POST, assignRole customer/manager/admin
orgUnitUserRole:
  '/users/${userId}/orgCustomers/${orgCustomerId}/roles/${roleId}', // DELETE, unassignRole customer/manager/admin

b2bUser: '/users/${userId}/orgCustomers/${orgCustomerId}', // GET, PATCH - all roles, designed for edit user view
```
That solution needs use API designed for Update user (PATCH) instead of designed for roles (POST)

So use `orgUnitUsers` with any role to fetch users, and `b2bUser` for modify roles

**Comment by Pucek9** [comment]
1 remove HTML select role stuff and routing param 'roleId' (it will be hardcoded for fetch) - also from other views where are links to that view
1 ask Bill about unit/users view (probably do the same)
2 ignore selected flag (remove it from table column, data mapping) the same with roles
3 update mapping in component - array with roles to flags, like:
```
...
uid: user.orgUnit && user.orgUnit.uid,
customerId: user.customerId,
admin: user.roles.includes('b2badmingroup'),
...
```
add columns:

```
{
  key: 'customer',
  value: 'usersList.customer' | cxTranslate,
  checkBox: true
},
{
  key: 'admin',
  value: 'usersList.admin' | cxTranslate,
  checkBox: true
},
...
{
  key: 'approver',
  value: 'usersList.approver' | cxTranslate,
  checkBox: true
},
```
4 support all checkbox events (recognize actions by event params) and use update (PATCH) method (as edit view)

**Comment by Xymmer** [comment]
still needed?

**Comment by Pucek9** [comment]
> still needed?

IMO it can be helpful (while refactor we will have partial-ready solution)
