### ISSUE TITLE
SSR error on PDP

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#7902]
**Describe the bug**
```
ERROR TypeError: Cannot read property 'history' of undefined
    at TabParagraphContainerComponent.ngOnInit (C:\divante\ssr\pdp-bug\dist\storefrontapp-server\mai
n.js:256855:72)
```

**Comment by dunqan** [comment]
QA steps: 
1, Run SSR server
2. Visit PDP page
3. The bugs mentioned in description should not show up in SSR console

**Comment by giancorderoortiz** [comment]
No issues seen in qa server. 
![Screen Shot 2020-08-20 at 5 47 47 AM](https://user-images.githubusercontent.com/46171897/90755061-bb1f5f80-e2a8-11ea-91bc-917c51f35cbb.png)
