### ISSUE TITLE
e2e test scenarios for MyCompany

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7911]
**Only Admin has access to MyCompany**
- Verify that when you login as admin, you can see MyCompany.
- Verify that when you login as B2B Customer, Manager and Approver, you cannot see MyCompany. 
- Verify going to the url directly as a B2B Customer, Manager and Approver, you cannot see MyCompany. 
- Verify that only Approver and Admin can see Approval Dashboard.

**Can create new 'everything'**
- Create a new unit
- From the unit details page, Create a new cost center
- From the unit details page, create a new child unit
- From the unit details page, create a new address
- From the unit details page, create a new admin, approver, manager, customer
- Create a new budget
- Go to Cost Centers ->  Select the newly created cost center -> Assign the newly created budget to it
- Create a new permission for the newly created parent unit. 
- Create a new user group for the newly created parent unit and assign the newly created permission to it. 
- Verify that the newly created user group is disabled. 
- Add a user to the user group and verify that it's now enabled.
- Delete the newly created user group.
- Future (not 2.1): Verify that you can see the newly created unit under Account Summary

**Updating a unit**
- Select a disabled unit and enable it. 
- Edit the details of the unit and change its parent unit if it has one and verify the change is done.
- Change the name of the unit.
- Add an existing approver, manager, admin & customer to it. 
- Disable the unit.

**Updating a cost center**
Note that if a cost center's unit is disabled, you can't enable the cost center.
- Select a disabled cost center and enable it. 
- Edit the details of the cost center and change its parent unit and verify the new parent unit. 
- Change the cost center name.
- Remove a budget from it, and add another existing budget to it.
- Disable the cost center

**Updating a budget**
- Select a disabled budget and enable it. 
- Edit the details of the budget and change its parent unit and verify the new parent unit. 
- Change the budget name and amount.
- Remove a budget from it, and add another existing budget to it.
- Disable the budget.

**Updating a user group**
User groups don't get "disabled" they just get their users removed. We fixed this UX in Spartacus.
- Add an existing user and an existing permission to it.
- Clear the user group of all its users. Verify that all users have been removed from that user group.

**Updating a user**
- Select a disabled user and enable it.
- Edit the details of the user and change its parent unit and verify the new parent unit. 
- Change the email address of the user.
- Add and remove an existing approver to/from it. 
- Add and remove an existing permission to/from it. 
- Add and remove an existing user group to/from it.
- Reset the password of the user.
- Disable the user.

**Updating a permission**
- Select a disabled permission and enable it.
- Edit the details of the permission and change its parent unit and verify the new parent unit.
- Change the amount threshold of the permission. 
- Disable the permission.

**Disabling a unit also disables its child unit, users, budget, cost center**
- Select an existing unit.
- Disable the unit.
- Go to a child unit of that unit, and verify that the child unit is also disabled. 
- Verify that you cannot enable the child unit.
- Go to a user assigned to that unit, and verify that the user is also disabled.
- Verify that you cannot enable the user.
- Go to a budget assigned to that unit, and verify that the budget is also disabled.
- Verify that you cannot enable the budget.
- Go to a cost center assigned to that unit, and verify that the cost center is also disabled.
- Verify that you cannot enable the cost center.
- Enable the unit.
- Verify that the child unit, user, budget & cost centers are all enabled now.

**Account Summary** - Future (not 2.1)
- Get the account summary of a parent unit.
- Get the account summary of a child unit.
- Play with the search parameters: SHOW, FILTER, DOCUMENT #.

**Comment by giancorderoortiz** [comment]
Usage of sample data for these CRUD tests in My Company may leave sample data in a non-usable state afterwards. @hackergil @WeizhengSap @plabadie  What strategy should be followed? 
Currently is not possible to automate b2b user registration approval as it requires backend approval.
https://help.sap.com/viewer/4c33bf189ab9409e84e589295c36d96e/2005/en-US/8ac2d88f86691014858efbd2faa52a92.html?q=b2b%20registration

**Comment by Xymmer** [comment]
Caine and Michal will use this as reference.

**Comment by Xymmer** [comment]
closing as the task was to create a reference but there will be new tickets for actual test creation
