### ISSUE TITLE
Update Password Page Excessive Delays When Backend Under Heavy Load

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7935]
**Backend Setup:**
Commerce Suite 2005 CF RC.
Deployed Spartacus recipe, based on CX recipe (b2b+b2c)
Deployment on Linux dev-server A

**Frontend Setup:**
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server)

**Steps to Reproduce:**
1. Manually navigate to Spartacus home page and login as registered user
2. Run Gatling load simulation (load homepage and do a simple search) with 400+ users. 
2.a. Wait about 30 seconds so that a significant amount of users are active. 
3. Navigate to My Account -> Password page. 

**Expected Results:**
3. Spartacus displays some sort of meaningful message indicating "loading, please wait" message.
3.a. Or a message indicating page loading took too long and redirect to I.T / administrator.
3.b. Or a message saying "404. page not found. Please try again later"

**Actual Results:** 
3. Skeleton of page loads, but it's not useable. There is no hour-glass, or spinner. The mouse is just not functional. 
3.a. In this particular case, this no-op situation remained for about 1.2 minutes. 

**Password page delay:**
![pwd_page_load_delay](https://user-images.githubusercontent.com/46171897/84253562-1a5d3880-aade-11ea-9eeb-d1795c305128.png)

**Gatling Users:** 
![Screen Shot 2020-06-10 at 5 45 15 AM](https://user-images.githubusercontent.com/46171897/84253671-382a9d80-aade-11ea-8182-e7cf400b54f3.png)
![Screen Shot 2020-06-10 at 5 46 09 AM](https://user-images.githubusercontent.com/46171897/84253676-38c33400-aade-11ea-9870-96421053b8b6.png)

**Comment by giancorderoortiz** [comment]
This requires a generic fix for all My-Account pages.

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
