### ISSUE TITLE
Cart Page Update Delays When Backend Under Heavy Load

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7937]
**Backend Setup:**
Commerce Suite 2005 CF RC.
Deployed Spartacus recipe, based on CX recipe (b2b+b2c)
Deployment on Linux dev-server A

**Frontend Setup:**
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server)

**Steps to Reproduce:**
1. Manually navigate to Spartacus home page and login as registered user
2. Add 4-5 products to cart. 
3. Navigate to cart page. 
4. Run Gatling load simulation (load homepage and do a simple search) with 400+ users.
4.a. Wait about 30 seconds so that a significant amount of users are active.
5. Update quantities in cart for any product n number of times while simulation is running.  

**Expected Results (if no update within 5 seconds):**
5. Spartacus displays some sort of meaningful message indicating "loading, please wait" message.
5.a. Or a message indicating page loading took too long and redirect to I.T / administrator.
5.b. Or a message saying "404. page not found. Please try again later"

**Actual Results:**
5. Delays between 9 and 17 seconds. 
5.a. During this time (which seems eternal), page is not functional, and mouse pointer remains the same. There is no hour glass or spinner. 
5.b. There is no indication of what's going on in background. 

**Delays:**
![cart-delays](https://user-images.githubusercontent.com/46171897/84258390-dde10b00-aae4-11ea-86b6-d00b107299bb.png)

**Gatling:**
![gatling-requests](https://user-images.githubusercontent.com/46171897/84256970-a5403200-aae2-11ea-9942-0d0933f16c43.png)
![gatling-users](https://user-images.githubusercontent.com/46171897/84256971-a5403200-aae2-11ea-826e-0c118e79cc58.png)

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
