### ISSUE TITLE
Unable to Place Order When Backend Under Heavy Load

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7938]
**Backend Setup:**
Commerce Suite 2005 CF RC.
Deployed Spartacus recipe, based on CX recipe (b2b+b2c)
Deployment on Linux dev-server A

**Frontend Setup:**
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server)

**Steps to Reproduce:**
1. Manually navigate to Spartacus home page and login as registered user
2. Add miscellaneous products to cart and continue to checkout. 
3. Complete checkout flow up to Review page. 
4. Run Gatling load simulation (load homepage and do a simple search) with 400+ users.
4.a. Wait about 30 seconds so that a significant amount of users are active.
5. Place order. (Click once "place order" button) 

**Expected Results (if no update within 5 seconds):**
5. Spartacus displays some sort of meaningful message indicating "loading, please wait" message.
5.a. Or a message indicating page loading took too long and redirect to I.T / administrator.
5.b. Or a message saying "404. page not found. Please try again later"
5.c. However, further refinement of requirements are needed by PO at this juncture. 

**Actual Results:**
5. Nothing happens for more than 1 minute. 
5.a. Upon further review of Dev tools -> Network tab, it shows an ERR_CONNECTION_TIMED_OUT error on request /occ/v2/electronics-spa/users/current/orders?cartId=00000045&fields=FULL&lang=en&curr=USD

![Screen Shot 2020-06-10 at 8 06 00 AM](https://user-images.githubusercontent.com/46171897/84267515-2ce26c80-aaf4-11ea-8080-7afe0cfc56f4.png)
![Screen Shot 2020-06-10 at 8 15 51 AM](https://user-images.githubusercontent.com/46171897/84267525-310e8a00-aaf4-11ea-84f3-c933ba8dda20.png)

Gatling: 
![gatling-users](https://user-images.githubusercontent.com/46171897/84259007-d5d59b00-aae5-11ea-8424-672c1e9dc1df.png)
![gatling-requests](https://user-images.githubusercontent.com/46171897/84258999-d4a46e00-aae5-11ea-856a-cd68bbeaa237.png)

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
