### ISSUE TITLE
Confirm Order Status As Complete In Cypress E2E Tests

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7939]
**Is your feature request related to a problem? Please describe.**
Current checkout e2e tests (as of 2.0) do not include a verification of order status. 
Checkout tests only confirm/assert the existence of an order that has been placed. 
However, none of the tests confirm that order status in order history page or order details page is set to "complete" or "placed"

**Describe the solution you'd like**
At least one of the following tests should include the verification listed above. 
https://github.com/SAP/spartacus/tree/develop/projects/storefrontapp-e2e-cypress/cypress/integration/regression/checkout

https://github.com/SAP/spartacus/blob/develop/projects/storefrontapp-e2e-cypress/cypress/integration/smoke/checkout-flow.e2e-spec.ts

Please note the verification I am recommended is not here: 
https://github.com/SAP/spartacus/blob/b9079d9c79ced881760d07f68efed6f10f490d15/projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-flow.ts

**Describe alternatives you've considered**
There are no alternatives. This test would confirm OMS is setup correctly in backend and orders are actually being processed up through completion. 

**Additional context**
E2E / cypress / OMS

**Comment by bgambocjaviniar** [comment]
Please look at the comment on why the PR for this issue was closed in here https://github.com/SAP/spartacus/pull/8203#issuecomment-703804925

Need investigation + feasibility for this issue. Check with Gil @saad-mo

**Comment by hackergil** [comment]
In order for the order to go to `Completed` state, it has to be fulfilled. Do we have APIs for this? Can this be done in an automated fashion? Need help from the team on this one

**Comment by Xymmer** [comment]
There is a management api
https://help.sap.com/viewer/9d346683b0084da2938be8a285c0c27a/latest/en-US/4d7b333423ec46d7b701e3661a12a7bd.html

**Comment by giancorderoortiz** [comment]
Partially fulfilled. Suffices for now. Re-open if necessary.
