### ISSUE TITLE
Unable to Select Delivery Mode When Backend Under Heavy Load

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7941]
**Backend Setup:**
Commerce Suite 2005 CF RC.
Deployed Spartacus recipe, based on CX recipe (b2b+b2c)
Deployment on Linux dev-server A

**Frontend Setup:**
Develop branch
Deployment on Linux dev-server A.
(backend and frontend deployed in same server)

**Steps to Reproduce:**
1. Manually navigate to Spartacus home page and login as registered user
2. Add miscellaneous products to cart and continue to checkout.
3. Complete Shipping Address step. 
4. Run Gatling load simulation (load homepage and do a simple search) with 400+ users.
4.a. Wait about 30 seconds so that a significant amount of users are active.
5. Click on "Continue" in Shipping Address step in order to move to Delivery Mode. 

**Expected Results (if no update within 5 seconds):**
5. Spartacus displays some sort of meaningful message indicating "loading, please wait" message.
5.a. Or a message indicating page loading took too long and redirect to I.T / administrator.
5.b. Or a message saying "404. page not found. Please try again later"
5.c. However, further refinement of requirements are needed by PO at this juncture.

**Actual Results:**
5. Random behaviour.
5.a. Sometimes we get an error page. 
5.b. Sometimes we get a blank page
5.c. Sometimes we get a "not found" page. 

![delivery-mode-mismatch](https://user-images.githubusercontent.com/46171897/84273039-37a0ff80-aafc-11ea-9485-5588ee2f218a.png)
![delivery-mode-not-found](https://user-images.githubusercontent.com/46171897/84273062-3bcd1d00-aafc-11ea-937b-e939dba235ca.png)
![delivery-mode-oops](https://user-images.githubusercontent.com/46171897/84273072-3d96e080-aafc-11ea-9ec8-fd595721b91d.png)

**Gatling:**
![gatling-users](https://user-images.githubusercontent.com/46171897/84273131-4d162980-aafc-11ea-9d86-9159bef92440.png)

![gatling-requests](https://user-images.githubusercontent.com/46171897/84273156-556e6480-aafc-11ea-801f-e56df01c8b1e.png)

**Comment by Xymmer** [comment]
Closing as we grouped a universal fix under this one ticket: #8151
