### ISSUE TITLE
Support multi-site driven Storefinder configuration

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#7947]
The storefinder configuration holds the Google API key. This configuration is not site-aware, which means that customers who run multiple sites on the same application logic cannot easily use a different API key for each site. This is not acceptable for a lot of businesses, which force the project team to customise the `GoogleMapRendererService` in Spartacus. 

This can be seen as a general pattern; various static configuration options in Spartacus are not site aware, and cannot easily been made site aware as the configuration is statically being referenced. We could introduce a configuration service that has site awareness by default, or statically create the site specific configuration up front.

**Comment by peebeebee** [comment]
@Xymmer : Is there any follow up on this?
I ask because we at Elision were also struggling with a good default way to set up site-specific configuration.
See: https://stackoverflow.com/questions/68994951/spartacus-multisite-site-specific-configuration
