### ISSUE TITLE
Add smartedit integration into installation script

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#7949]
Temporarily, outdated smartedit integration function has been removed from the installation script:
https://github.com/SAP/spartacus/commit/33aa2263dc04d33a032162c5228a2c1d48f7199c#diff-e29bb2758c155653e9d9953cd57e96f3L17
Let's update and put back the function in order to have it working with the current installation script and spartacus codebase.

**Comment by mirkosoft** [comment]
@WeizhengSap we need you support here I guess :)

**Comment by janbiasi** [comment]
@mirkosoft Wouldn't it also be an option to provide it via a separate schematic - or even a separate NPM package? :) would be a cleaner way imo.

**Comment by mirkosoft** [comment]
> @mirkosoft Wouldn't it also be an option to provide it via a separate schematic - or even a separate NPM package? :) would be a cleaner way imo.

@janbiasi you mean smartedit integration or installation script as a whole?

**Comment by janwidmer** [comment]
@mirkosoft i guess what @janbiasi meant, and also the original reason for this. ticket is all fulfilled with version 3.2.0, where smartedit can be installed as feature lib together with the normal installation..?

**Comment by mirkosoft** [comment]
Thanks for the heads up @janwidmer. Yes, I think this ticket can be closed (smartedit is already a feature lib), correct me if I'm wrong @marlasak @WeizhengSap.

**Comment by marlass** [comment]
Smartedit lib is indeed installed with installation script
