### ISSUE TITLE
[waiting for schematics] Pending Support of Powertools-Spa for Installation Script

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7965]
https://github.com/SAP/spartacus/issues/7375 installation script should support deploying powertools-spa storefront OOTB in the same way as electronics and/or apparel. 

Ideally, for end of Q2 and Q3, 2020, installation script should deploy 3 storefronts concurrently, with/without ssr.

**Comment by dunqan** [comment]
Should probably wait for #8536

**Comment by kacperknapik** [comment]
Waiting for schematics

**Comment by hackergil** [comment]
This is done by #9990
