### ISSUE TITLE
e2e test scenarios for B2B Checkout

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7970]
**Checkout regular product**

**Checkout regular product & multi-d product together**

**Checkout replenishment order**

**Checkout with credit card**

**Checkout with Account Payment**

---- 
Negative Testing TBD
1. Place an order with a disabled budget. 
2. Place an order above budget's amount. 
3. Place an order with a disabled cost center. 
4. Place an order using an user of a disabled unit.

**Comment by LTiger14** [comment]
Test cases to do:

- [x] Checkout with credit card
- [x] Checkout with account payment

Cases that cannot be done yet:
- Checkout replenishment order (will be done with replenishment order feature)
- Checkout with multi-d products (will be done with multi-d)

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/8912
