### ISSUE TITLE
e2e test scenarios for B2B Order Details

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7975]
To test, either place orders from the old accelerator,
**Order Details of regular products**

**Order Details of regular & multi-d products**

**Order Details with Card Payment**

**Order Details with Account Payment**

**Order Details of order that requires approval**

**Verify Order Confirmation Page**

**Verify Order Details Page under Order History**

**Verify Order replenishment page**

**Reorder from Order Details** (probably not in 2.1)

**Comment by kacperknapik** [comment]
This ticket is not a part of MyCo milestone, moving it to 3.0

**Comment by Xymmer** [comment]
was done
