### ISSUE TITLE
e2e test scenarios for B2B Storefront

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#7976]
**Homepage**
- Make sure homepage is well displayed.

**Product List Page**
- Make sure plp is well displayed. 
- Go to plp by doing a search, auto-complete search, through category. 
- Verify facet search on plp. 

**Product Details Page**
- Make sure pdp is well displayed for both regular product and multi-d product.
- Verify the tabs.
- Verify adding to cart.
- Verify submitting a review.
- Verify going to pdp through plp, search.

**Registration Page** (not for 2.1)
- Verify registration of a new user.

**Login Page**
- Login with different types of users and verify what they see and don't see. (for eg, admin sees MyCompany, Approver sees approval dashboard etc.).

**Forgot Password Page**
- Reset the password of a user.

**MyAccount Pages**
- Verify all myAccount pages. 
- Verify updating all myAccount pages info. 

**StoreFinder Page**

**Order Forms, Quick Order, Saved Forms** - not for 2.1

**Comment by Xymmer** [comment]
closing as the task was to create a reference but there will be new tickets for actual test creation
