### ISSUE TITLE
i18n API does not display order status labels for status with a dot.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#7977]
The order status code for "Pending Approval" is `pending.approval`.  The fact that there is a dot in the status code seems to make it incompatible with the current translation api.

We need to figure out something for the status to display adequately.  One thing we can do is replace dots with underscores in the i18n `context` option.  If we go this way, we need to determine where is the best place to do that.  Possibly, we add some logic in the `translate()` function of the `I18nextTranslationService` to achieve the following: replace any dots `.` by underscores `_` for the value of the `context` option before attempting to match an i18n key.

We could then, following this scenario have:

Translation key passed to the translation api: `statusDisplay`
Options passed with the key:  `{ context: pending.approval}`
Translation key/value in `my-account.ts`: `statusDisplay_pending_approval: 'Pending Approval'`.

Goal of the ticket:
- Apply some fix to allow the  `pending.approval` to display a i18n text.
- Add the i18n key value for additional b2b order status.

Current issue screenshots:
![Screen Shot 2020-06-15 at 2 51 41 PM](https://user-images.githubusercontent.com/7065346/84698042-25202f00-af1d-11ea-8097-8792f210ab1b.png)
![Screen Shot 2020-06-15 at 2 51 31 PM](https://user-images.githubusercontent.com/7065346/84698047-26e9f280-af1d-11ea-9450-4b358cd45ca4.png)

**Comment by znikola** [comment]
In order not to get into a risk of introducing breaking changes, it's might better to play it safe.
The simplest solution for now is to do something like this:

<img width="1412" alt="Screen Shot 2020-06-22 at 09 49 39" src="https://user-images.githubusercontent.com/11561723/85293974-5f01b000-b49e-11ea-9d75-352c74ee9a3f.png">

We might revise this for 3.0.

**Comment by plabadie** [comment]
There are more order statuses than we thought that have a dot in them.  Moreover some of them end with the same word after the dot, which make it impossible to create distinct keys with the planned workaround.

Therefore, we are going to add support for dots in the context within the `I18nextTranslationService`.

**Comment by qjimmy** [comment]
Also happens in approvals list under the `Status` column, not sure if related to the same issue.

<img width="1005" alt="Screen Shot 2020-06-29 at 3 21 12 PM" src="https://user-images.githubusercontent.com/30666844/86047079-4ce2bd00-ba1c-11ea-83f2-018603c76e41.png">

**Comment by plabadie** [comment]
At first glance, it doesn't look like the same issue, but we can get to the bottom of it to make sure.

**Comment by plabadie** [comment]
PR #8130

(See solution update in comment below)

## How to test.
### Use the legacy Powertools Accelerator to set things up. 
- Checkout an order fo 10000$ or more with `william.hunter@rustic-hw.com`.  After approx one minute, the order will be pending approval.
- Got to My Account -> Order History and then also to the Order Details.

The status should now display properly.  Of course, no regression should occur for the other labels.

![Screen Shot 2020-06-30 at 4 46 37 PM](https://user-images.githubusercontent.com/7065346/86176118-79690880-baf2-11ea-9ea6-183efacd92fe.png)

**Comment by plabadie** [comment]
### Solution update

Following the code review, we will apply a new solution from @Platonn. The new solution is more aligned with how we should deal with data driven keys from now on.  The idea is to move away from using the context for data driven keys.


### Propopsed change: 

old:
```
'returnRequestList.statusDisplay' | cxTranslate: { context: status }
```
new:
```
'returnRequestList.statusDisplay_' + status | cxTranslate
```
3. It will allow for adding new keys that contain dot (i.e. APPROVAL.PENDING) in 2.1:
```
statusDisplay_APPROVAL: {
      PENDING: 'Approval Pending', // nesting required due to dot in the value from backend
},
statusDisplay_CANCELED: 'Cancelled',
```


Scope of the change for 2.1:
- The order status ( statusDisplay_* keys ).
