### ISSUE TITLE
SLR category doesn't (initially) populate search results

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#7991]
# Problem

1. Open spartacus on the home page, and navigate to SLR category
<img width="1322" alt="Screen Shot 2020-06-17 at 12 19 32" src="https://user-images.githubusercontent.com/11561723/84886991-6e938a00-b095-11ea-870d-f388aafc3dfc.png">

2. Notice the network - Spartacus issues only one request to get the page data (it doesn't issue the search request at this point)

<img width="1680" alt="Screen Shot 2020-06-17 at 12 20 23" src="https://user-images.githubusercontent.com/11561723/84887135-a0a4ec00-b095-11ea-8db6-f3d72a39bb72.png">

3. Notice the search results slice of the state - it's still empty 

<img width="1680" alt="Screen Shot 2020-06-17 at 12 20 55" src="https://user-images.githubusercontent.com/11561723/84887187-af8b9e80-b095-11ea-92f0-6976abbe008e.png">

4. Navigate to another category (e.g. _film cameras_) and notice the network tab and the search results slice of the state - it's populated with the data from the _film cameras_ category.

<img width="1680" alt="Screen Shot 2020-06-17 at 12 21 21" src="https://user-images.githubusercontent.com/11561723/84887307-d5b13e80-b095-11ea-9028-3005920fcd06.png">

5. go back to the SLR category, and check the network tab - there's a request issued to the _search_ endpoint.

<img width="1680" alt="Screen Shot 2020-06-17 at 12 21 43" src="https://user-images.githubusercontent.com/11561723/84887462-101adb80-b096-11ea-9aa7-62c81db75a78.png">

6. Check the search results state slice - it's populated with the data from the SLR category

<img width="1675" alt="Screen Shot 2020-06-17 at 12 22 55" src="https://user-images.githubusercontent.com/11561723/84887593-40627a00-b096-11ea-8cd0-ae1e40e62f75.png">

## Conclusion

The search results slice of the state _should_ be populated on the initial visit to the _SLR_ category.

This is causing issues for CDS for example, as they do not get notified when the user initially visits this particular category.

**Comment by Xymmer** [comment]
still happening?

**Comment by giancorderoortiz** [comment]
Yes, I still see it in qa server b2c csr: 
http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/Open-Catalogue/Cameras/Digital-Cameras/Digital-SLR/c/578

**Comment by bgambocjaviniar** [comment]
PR GH-9608

Note: SLR was not supposed to fire a search request in this special page.

QA: 
- make sure your network tab is open in dev tools

TEST 1
1) go to slr page
2) use any category nav to navigate to a product list page of category
3) go back to slr page using the category nav under 'digital cameras' and select SLR Cameras
4) make sure no search request happens for this page

TEST 2
- make sure navigating between categories or using the search is still functioning and correctly handled as in the proper data is being sent as a request and received

Jenkins build: looking good
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/454/console
https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/453/console

**Comment by giancorderoortiz** [comment]
ok, I agree with the fix. 
However the description of the ticket and the qa steps are contradictory. 
Search functionality not affected because of this change.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-06 at 2 08 47 PM](https://user-images.githubusercontent.com/46171897/98405062-a0ec5680-2039-11eb-92d0-a929211c3e3e.png)
