### ISSUE TITLE
[Retest] Order Date Format Unchanged in Order History When Switching to German

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7996]
**Describe the bug**
Date format in Order Details Page is expected to change when switching languages from English to German. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to Spartacus storefront and login
2. Place an order. 
3. Navigate to My-Account -> Order History. 
4. (Notice date format of order placed. In English, month comes first -> June 17, 2020)
5. Switch language to German

**Expected behaviour**
5. Order date format changes. Day of the month shown first. (i.e. 17 June, 2020)

**Screenshots**

![Screen Shot 2020-06-17 at 8 43 18 AM](https://user-images.githubusercontent.com/46171897/84916630-4c493e80-b08c-11ea-98f9-2213ed00b7d7.png)
![Screen Shot 2020-06-17 at 8 43 29 AM](https://user-images.githubusercontent.com/46171897/84916640-4f442f00-b08c-11ea-8f0d-4a870182e153.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina. 
 - Browser: Chrome
 - Version 83
- Spartacus 2.0

**Additional context**
Found during investigation of #7522

**Comment by benmarcotte** [comment]
This now works as intended, also works in the other languages.

**Comment by KateChuen** [comment]
Tested with spartacus - develop branch, 2005 backend. Looks like it's working now. 

<img width="1041" alt="Screen Shot 2020-07-22 at 10 42 50 AM" src="https://user-images.githubusercontent.com/45409515/88190358-30473880-cc08-11ea-8629-5689011a5326.png">
