### ISSUE TITLE
[retest] E2E test unable to Access PDP Page With Only Product ID

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#7997]
**Describe the bug**
Unable to access product details page with URL such as follows: 
http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/product/1382080

URL requires product title as well: Such as: http://dev-com-6.accdemo.b2c.ydev.hybris.com:4200/electronics-spa/en/USD/product/1382080/EOS450D%20%2B%2018-55%20IS%20Kit

**To Reproduce (Use a 2005 backend)**
1. Navigate to Spartacus Storefront. 
2. Attempt to access product details page for 1382080 directly. 
2.a. 4200/electronics-spa/en/USD/product/1382080
3. Search for 1382080
4. From product listing page, access product details page for 1382080

**Expected behaviour**
2. Product details page is displayed. 

**Actual behaviour**
2. Page not found displayed. 

**Screenshots**
![Screen Shot 2020-06-17 at 12 54 08 PM](https://user-images.githubusercontent.com/46171897/84931093-4e1cfd00-b0a0-11ea-92d4-d602ac820118.png)
![Screen Shot 2020-06-17 at 11 05 08 AM](https://user-images.githubusercontent.com/46171897/84931125-583efb80-b0a0-11ea-9a4a-7d0396c0090e.png)

**Desktop (please complete the following information):**
 - OS: Mac Os Catalina
 - Browser Chrome
 - Version 83

**Additional context**

- Found during investigation of #7523 
- It seems configuration found in b2c.features.ts is not being applied.

**Comment by Xymmer** [comment]
When the configuration file has product/:productcode, the URL cited in this issue does work (we tried it).
However the question is, does our e2e test configuration add product/:productcode or is it being used properly.

**Comment by giancorderoortiz** [comment]
This issue is now fixed with default configuration. 
Dev branch. Oct 25, 2020

![Screen Shot 2020-10-25 at 2 24 01 PM](https://user-images.githubusercontent.com/46171897/97115572-cee2aa00-16cd-11eb-80db-7583e16b8291.png)
![Screen Shot 2020-10-25 at 2 24 06 PM](https://user-images.githubusercontent.com/46171897/97115573-cf7b4080-16cd-11eb-968b-1da8fcbb109d.png)
