### ISSUE TITLE
Add arrow navigation to search field for accessibility reasons

### ISSUE THREAD

**Issue by TLipphardt** [SAP/spartacus#8010]
Hello colleagues, 

we're leveraging Spartacus for https://www.sapappcenter.com/. 
Among the many great things we were able to use out of the box was the standard search input with its helpful typeahead autocomplete feature. 

Our Business has issued concerns with its accessibility though: I short it would be great if the user could tab and/or navigate with the arrow keys through the autosuggestions. Before we build our own thing we wanted to bring this up to standard development, maybe there is already something planned. 

I confirmed such functionality is also not avaible on the demo electronics store: https://spartacus.c39j2-walkersde1-d4-public.model-t.cc.commerce.ondemand.com/electronics-spa/en/USD/
 
![Search Box](https://user-images.githubusercontent.com/7572465/85148093-050bab00-b250-11ea-8302-45587c4d1a05.PNG)

Best regards, 
Tim

**Comment by tobi-or-not-tobi** [comment]
We've released the keyboarding aspect of accessibility in release 2.0, including the key bindings you'd expect for the type ahead search. 

We've added some generic keyboard-focus features, which are documented at https://sap.github.io/spartacus-docs/keyboard-focus/. The directives documented there are not used everywhere btw. 

The public available site apparently is not on 2.0 yet unfortunately. @hackergil might give an update regarding our plans to update those. 
I trust you can install a local version and test out the new accessibility features – you can use the same backend as it's purely driven in the UI layer. 

I'm closing this issue for now, as we're not going to backport features.
