### ISSUE TITLE
Fix B2C registration display because of B2B new component

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8022]
With the addition of B2B registration component, B2C registration is not being displayed correctly.

Fix CSS display on B2C registration. Introduces a CSS breaking change and it is dependent on how this will be managed in the near future.

![b2b_registration](https://user-images.githubusercontent.com/158500/85319421-78e7c680-b48f-11ea-9d58-8c04afc3f028.png)

**Comment by hackergil** [comment]
@morganm58 to address this change with Theme for Minors

**Comment by morganm58** [comment]
I think the issue was fixed. I pulled the latest from epic/b2b and could not replicate

**Comment by giancorderoortiz** [comment]
which branch?

**Comment by giancorderoortiz** [comment]
Issue no longer seen. B2B or B2C. 

![Screen Shot 2020-08-20 at 5 49 55 AM](https://user-images.githubusercontent.com/46171897/90755495-2a954f00-e2a9-11ea-8fc0-be8ffac0863e.png)
![Screen Shot 2020-08-20 at 5 50 54 AM](https://user-images.githubusercontent.com/46171897/90755497-2b2de580-e2a9-11ea-87bf-4827a480a68f.png)
