### ISSUE TITLE
Image zoom master

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#8032]
Create the image zoom feature inside of the incubator library. This is still meant to be a work in progress even after this ticket and breaking changes can still occur. We should still adhere to our standards of quality.

The image zoom component allows to see a larger view of the product image and to zoom on it. The component also shows thumbnails images and allows to cycle through the various product view.

See image zoom definition: https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Image+Zoom+for+Spartacus+2.1

### Acceptance

- Moving mouse scrolls image left right (arrows)
- Clicking zooms x2
- Thumbnails are visible and allow to switch the "featured" image
Touch interactions:
- Finger drag to move around
- Double-tap to zoom in/out (max and back out)

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/8259

**Comment by Xymmer** [comment]
duplicate of #13315
