### ISSUE TITLE
Qualtrics e2e test failing

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8035]

**Comment by hackergil** [comment]
Qualtrics component is not in our sample data (thanks @bgambocjaviniar!)

**Comment by bgambocjaviniar** [comment]
Fixes in https://github.com/SAP/spartacus/issues/8133
Also, added it manually on dev6 for now as it is already in dev17, but the next initialization and import for the `test-data` will have the cms component in it.

**Comment by hackergil** [comment]
@bgambocjaviniar Fix is good. You can mark this one as done as soon as we close #8133
