### ISSUE TITLE
Wrong config is displayed on overview after displaying overview of order confirmation before

### ISSUE THREAD

**Issue by steinsebastian** [SAP/spartacus#8046]
Wrong configuration is displayed on configuration overview if user has placed an order before and had a look at the overview of the ordered item.

Bug was found on teamserver.

How to reproduce:
+ Sign In: with cpq02@sap.com user
+ search for home theater
+ go to product details page of Home Theater
+ Configure
+ Select: 
    Room Size: 10-24
    Color: White
+ Add to cart
+ continue to cart
+ Proceed through checkout process
+ Place Order
+ On Order confirmation click on "Display Configuration"
  => Overview is displayed with correct values 10-24 and white
+ search for home theater
+ go to product details page of Home Theater
+ Configure
+ Select: 
    Room Size: 41-60
    Color: Titan
+ Add to cart
  => Now on the overview the old configuration with values 10-24 and white is displayed!

**Comment by schuppell** [comment]
We don't clear the State after the order is placed, that is the cause for this error.
Currently we only clear states after add to cart (owner changes from product xyz to cart entry x).
