### ISSUE TITLE
Check whether installation script can handle setup without baseSite given

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8051]
Currently installation script use `baseSite=electronics-spa` param to set up the app as given. However it's a bit tricky to set up multisite app on the same machine (language/currency clash problem appears) so let's check can we utilize autoconfig feature (context not present in the URL) with the script.

**Comment by giancorderoortiz** [comment]
Ideally, via installation script run.sh we should be able to setup both electronics and apparel in config.sh. 
Further manual configuration shouldn't be necessary. 

So, a very simple deployment scenario would be: 

1. git clone spartacus
2. Navigate to spartacus/scripts/install/
3. Create a copy of config.sh file based on config.default.sh. 
4. Add electronics and apparel base sites. 
5. Execute script ./run.sh install
6. Execute script ./run.sh start. 
7. Go to browser in client machine and access apparel and electronics stores.
