### ISSUE TITLE
Run E2Es against Azure dev servers

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8066]
e2e runs against new linux dev-server. East US. 

Smoke tests pass? 
Regression? 
Mobile?

**Comment by giancorderoortiz** [comment]
1905.15 and 2005 backends provided. See internal azure-vm documentation for further details.

**Comment by hackergil** [comment]
Results for 2005 azure here https://dashboard.cypress.io/projects/k3nmep/runs/3057/specs

**Comment by bgambocjaviniar** [comment]
Will be using 
- dev-0 for normal 2005 backend
- dev-3 for b2b 2005 backend
- dev-legacy for 1905 backend

**Comment by bgambocjaviniar** [comment]
truthy PR: GH-8221

**Comment by bgambocjaviniar** [comment]
release 2.0.x PR : GH-8261
support 1905 using develop: PR : GH-8299
