### ISSUE TITLE
Race condition on save for later

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8072]
When saving a product for later, and then returning it to the cart, there is a race condition that it is preventing the cypress e2e tests to click the "back to cart" button to bring the product back to the cart.

This is an error that is only reproducible with an e2e test. If you test it manually, it works fine.

To reproduce, have a look at #GH-7526. There's a feature branch and a PR for it.

**Comment by Xymmer** [comment]
@hackergil are you proposing we fix the race condition or e2e test?

**Comment by Xymmer** [comment]
To dev: Evaluate our code to see if there indeed is a bug
- If so, fix the bug. 
- If not, fix the e2e test so we don't get this error when running e2e.

**Comment by psmul** [comment]
Closing, as refactor along with fixes were done in #11500
