### ISSUE TITLE
Update of numeric multi valued attribute is failing

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#8075]

**Comment by steinsebastian** [comment]
Not an issue on SPA-side but a bug in our mock-implementation. The mock does not allow to set values for multi-valued numeric cstics.
Will be fixed with https://cxjira.sap.com/browse/TIGER-6605.

**Comment by steinsebastian** [comment]
Will be handled in https://cxjira.sap.com/browse/TIGER-6605.
