### ISSUE TITLE
AddToHomeScreenService should be exported

### ISSUE THREAD

**Issue by janrode** [SAP/spartacus#8079]
At the moment it is not possible to overwrite the AddToHomeScreenService because it is not exported in the index.ts:
https://github.com/SAP/spartacus/blob/master/projects/storefrontlib/src/cms-structure/pwa/index.ts

Such an import in a spartacus project should not lead to an error:
`import { AddToHomeScreenService } from '@spartacus/storefront'`

`TS2305: Module '"......../node_modules/@spartacus/storefront/spartacus-storefront"' has no exported member 'AddToHomeScreenService'.`

**Comment by kacperknapik** [comment]
Moving to #8170, since it has more detailed info. Closing
