### ISSUE TITLE
Product image inside AddedToCartDialogComponent  too small

### ISSUE THREAD

**Issue by janrode** [SAP/spartacus#8087]
The product image inside the AddedToCartDialogComponent > cx-cart-item is displayed too small for bigger screens:
![image](https://user-images.githubusercontent.com/5228313/86119662-2c296e80-bad3-11ea-8f5b-e8ff6e4d0750.png)
Chrome  83.0.4103.116

I think this was introduced by this change: 
https://github.com/SAP/spartacus/commit/d5f3dc9b8e0780e492146ec07da43c4188241148#diff-6ad0e3bfdd117d83a4b03c6241a422eeR96

**Comment by Xymmer** [comment]
fix for 3.0 and backport to 2.1
