### ISSUE TITLE
Install auth library

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8096]
https://github.com/manfredsteyer/angular-oauth2-oidc

**Comment by marlass** [comment]
Wait for #8114 before reviewing

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- verify that we have dependency on `angular-oauth-oidc` library
- verify that we list this dependency as peerDependenccy in @spartacus/core
- verify that schematics automatically install this dependency
