### ISSUE TITLE
i18n - remove context usage 

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#8103]
# Description

This ticket is related to https://github.com/SAP/spartacus/issues/7977

We decided to drop the usage of the `context` parameter in cases where the translation key contains an underscore `_`.

This change requires to:
- change the templates that use the `cxTranslate` pipe
- change the components that call the `i18next-translation.service.ts`' `translate()` method with the context being passed
- refactor the translation chunks

## Templates 

To find the usages, search for `cxTranslate: { context:` across html files. At the moment of the creation of this ticket, I found ~20 results.
Due to formatting, and to be sure no cases are missed, please try a variation of the search term, e.g. just `{ context:`.

## Components

Check usages of `projects/core/src/i18n/i18next/i18next-translation.service.ts`'s `translate()` method that pass `context` to the `options` parameter.

## Translation chunks

We should convert all the cases where the translation key contains an underscore `_` to a nested object.

An example from `my-account.ts`:

```ts
{
...
  statusDisplay_cancelled: 'Cancelled',
  statusDisplay_pending_approval: 'Pending Approval'
...
}
```

should become:

```ts
{
...
  statusDisplay: { 
    cancelled: 'Cancelled',
    pending_approval: 'Pending Approval'
 },
...
}
```

**Comment by bgambocjaviniar** [comment]
PR: GH-12399

- Removed all references in the `template` that uses context and updated accordingly
- Removed all references in the `component` that uses context and updated accordingly
- Did not update translation chunks for nested objects when there exist an underscore as it was not created that way. ex: https://github.com/SAP/spartacus/issues/7977#issuecomment-653565158

There were less references to fix as these were fixed throughout the quarters I believe
