### ISSUE TITLE
Breadcrumb overflow destroys the layout

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8104]
When the breadcrumb navigation or page title is to long in the hosted layout, the overall layout is broken. This might  leads to overflow to the next line of the layout, but even leads to unexpected layout issues for devs. 

We like to fix this in the style so that devs don't waste time to analyse the issue. Customers might still want to overflow breadcrumbs, but it's debatable, specifically in mobile where space is limited. On desktop it's often not a problem anyway.

**Comment by tobi-or-not-tobi** [comment]
QA:
- add a very long page title or introduce (multiple) breadcrumbs with long titles. No need to do this in the backend, dev tools is enough
- ensure that the breadcrumbs and page title would not overflow the single line. 
- use `$useLatestStyles: false;` or  to ensure this is only applied when the new style version is used.

**Comment by Platonn** [comment]
Related ticket https://github.com/SAP/spartacus/issues/9105 (1.)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-28 at 7 47 35 AM](https://user-images.githubusercontent.com/46171897/97444497-9d065900-1902-11eb-8c16-a2c620771a58.png)

**Comment by giancorderoortiz** [comment]
Still an issue with Spartacus 3.0

**Comment by Xymmer** [comment]
check 4.x and develop if still happening, fix or close

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn.

Looks fixed now.

<img width="496" alt="Screen Shot 2022-04-14 at 1 56 23 PM" src="https://user-images.githubusercontent.com/45409515/163449542-a9a95c8d-9249-40b7-a362-41d3bc25f069.png">

<img width="449" alt="Screen Shot 2022-04-14 at 1 54 14 PM" src="https://user-images.githubusercontent.com/45409515/163449544-31e8238b-c1ce-4cb1-9e4a-171bea076b36.png">

<img width="488" alt="Screen Shot 2022-04-14 at 1 53 31 PM" src="https://user-images.githubusercontent.com/45409515/163449548-b5fa2d25-1424-47dd-ad39-1578cf4bf443.png">
