### ISSUE TITLE
Missing breadcrumb in apparel UK

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8110]
Breadcrumb is missing in most of the pages of apparel UK. This is making the apparel e2e tests fail.

Breadcrumb is present on the right slot (BottomHeader) of the apparel catalog.

After reinitializing and reimporting the test data, breadcrumb is present on the _staged_ catalog but not the _online_ one. Which means we might have a synchronization problem.

**Comment by bgambocjaviniar** [comment]
Backend PR:
2005 - https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/109
1905. - https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/110
