### ISSUE TITLE
Translation key missing 'TabPanel Container.tabs.TabPanel Container' in the chunk 'product

### ISSUE THREAD

**Issue by raviteja2515** [SAP/spartacus#8123]
We have a custom site running on Azure cloud and I have completed the setup of Spartacus storefront. right now I am facing issues in PDP that tabs are not getting displayed and in the network tab under-console I could see an error message stating: "Translation key missing 'TabPanel Container.tabs.TabPanel Container' in the chunk 'product". As per the below link they are saying need to enable translation key I am not sure what is meant by translation key. If you have any idea about it please help! thanks in Advance!
https://github.com/SAP/spartacus/issues/4990

**Comment by raviteja2515** [comment]
All, 
Any help on this

**Comment by LTiger14** [comment]
This is caused by not using the `spartacussampledataaddon` https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2005/#spartacus-sample-data-addon

**Comment by ramyabharathi-j** [comment]
Im trying to connect powertool store through occ. I want to connect spartacus with backend. I am facing the same issue. Is there any way to resolve this issue instead of using spartacussampledataaddon

**Comment by anu-sinha** [comment]
hi,

I'm getting same error and we are using SAP Commerce Cloud 2011. spartacussampledataaddon is deprecated now hence we have to use spartacussampledata.

Any suggestion please!

**Comment by devzom** [comment]
Look into https://github.com/SAP/spartacus/issues/7079#issuecomment-1049780638
