### ISSUE TITLE
SSR site appears to load twice 1.3

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8128]
Using 1.3.1
When server side rendering is enabled, the site appears to load twice.
i.e.
On first load, you can see content, links, etc but nothing is clickable.
Then after a second, the content disappears and then reloads, at which point you can click links.

Info on what could cause this? Is this a bug in 1.3?

Found #8089 (and previously #6449) but not related apparently.

The request here is, was that an SSR reloading issue like described in 1.3 that we fixed later? As we don't see it now.

**Comment by psmul** [comment]
This issue was fixed in @spartacus/schematics@1.5.2 release, but for earlier versions of an application, there is manual editing action required.
Please make sure to import `BrowserTransferStateModule` in you `app.module.ts` file.
