### ISSUE TITLE
apparel uk: a few minor issues when navigating to some categories

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#8132]
**Environment Details**
Spartacus: develop
spartacussampleaddon: release/1905/next
Browser: Chrome
Device: mac
Happens on: https://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/apparel-uk-spa/en/GBP

**Steps to Reproduce**

Found a few issues while testing #5237. Please verify if it can be fixed in backend sample data or spartacus.
1. Go to Brands -> Billabong. Then go Brands -> Blue Tomato. The applied filter still says "Billabong".
<img width="1065" alt="Screen Shot 2020-07-03 at 10 29 20 AM" src="https://user-images.githubusercontent.com/45409515/86478345-21abe680-bd18-11ea-9208-e355db0c144b.png">

2. Go to Youth -> Tshirts. Then go to Snow -> Shop all snow. You'll see the header of the previous page is still displayed.
<img width="1063" alt="Screen Shot 2020-07-03 at 10 17 17 AM" src="https://user-images.githubusercontent.com/45409515/86478185-e3162c00-bd17-11ea-8828-f0125f1e1849.png">

3. Missing the applied filter for the categories under Youth. For eg, Youth -> Tshirts -> Billabong. Should display applied filter "Billabong".
<img width="1064" alt="Screen Shot 2020-07-03 at 10 32 30 AM" src="https://user-images.githubusercontent.com/45409515/86478677-9e3ec500-bd18-11ea-9950-4ff05c52efa1.png">

**Comment by Xymmer** [comment]
we need to decide if it's better to fix this in core sample data.
does this happen in accelerator?

**Comment by KateChuen** [comment]
Nope it does not happen in accelerator.

In the first case, there's no applied filter in accelerator.
In the second & third case, it does not happen.

**Comment by bgambocjaviniar** [comment]
no longer an issue, so closing



[proof.zip](https://github.com/SAP/spartacus/files/5797008/proof.zip)
