### ISSUE TITLE
Add missing qualtrics component on test sample data

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8133]
From @bgambocjaviniar 

We forgot to add it since it got refactored and we now have an e2e for it. It wasn't in test-data before because we had no e2e for it, but now we have a minimal one

Let's add it so that the e2e test can pass

**Comment by bgambocjaviniar** [comment]
~Backend PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/106~ (develop - shouldn't merge here anymore)

Backend PR:
(1905 release) https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/107
(2005 release) https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/108
