### ISSUE TITLE
Spartacus Smartedit preview, basic edit is not working

### ISSUE THREAD

**Issue by kishorems** [SAP/spartacus#8149]
**Describe the bug**
Smartedit Spartacus custom site is selected and makes the below request automatically and types sends as empty "" therefore it gives 400 error.

"https://localhost:9002/permissionswebservices/v1/permissions/principals/admin/types?permissionNames=create,change,read,remove&types="

Verified the requests with other sites and its been sent as below. Don't know where we can configure types therefore it should be sending types=ContentPage for spartacus.

"https://localhost:9002/permissionswebservices/v1/permissions/principals/admin/types?permissionNames=create,change,read,remove&types=ContentPage"

**Screenshots**
Click the below image of smartedit error
https://answers.sap.com/storage/temp/1822568-ovafh.png

**Comment by Xymmer** [comment]
related personalization issue https://cxjira.sap.com/browse/ECP-5187, not implying it's same bug or problem but wanted to point that out. checking with owners of smartedit and personalization for direction.

**Comment by kishorems** [comment]
Thanks @Xymmer  for the response.

It seems the link https://cxjira.sap.com/browse/ECP-5187 is not accessible and says the post may have been deleted and you don't have permissions.

Could you please enable the link accessible or paste the content what you are tryings say?

Kind Regards
Kishore

**Comment by Xymmer** [comment]
- let's try to repro and gain a better understanding of the problem, @KateChuen 
- Bill to ping SmartEdit PO to see if they know something

**Comment by KateChuen** [comment]
Wasn't able to reproduce it. 
@kishorems Can you please provide more details, what kind of setup do you have? The versions you're using. And a recording perhaps? Thanks.

**Comment by Xymmer** [comment]
Closing as can't repro, we figured it out separately through chat but not sure it was same person who reported this issue.
If this issue is still happening, please contact me.
