### ISSUE TITLE
Anonymous consents - remove deprecated code

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#8158]
Search for `TODO{#8158}` across the code base, and follow the instructions in code comments.

**Comment by bgambocjaviniar** [comment]
PR: GH-9500

QA: 
- verify the big happy path of anonymous consent feature
for example, verify we can still set an anonymous consent, verify that it gets carried over when logging in as a user, verify that we can set consents in the consent page of a user, etc

**Comment by giancorderoortiz** [comment]
Looks good. 
![Screen Shot 2020-11-02 at 6 30 33 AM](https://user-images.githubusercontent.com/46171897/97863423-f42a7600-1cd4-11eb-9e6e-d42397ec5f50.png)
