### ISSUE TITLE
MyCompany preliminary testing

### ISSUE THREAD

**Issue by KateChuen** [SAP/spartacus#8163]
**Environment Details**
Spartacus: feature/GH-cost-center-ui
spartacussampleaddon: feature/my-company
backend: 'https://spartacus-dev3.eastus.cloudapp.azure.com:9002'
Browser: Chrome
Device: mac
Happens on: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/powertools-spa/en/USD

Note: Bill added comments to each of these.

**Issues found:** 
- [ ] Non-admin user can access MyCompany through Url -> Login as mark rivers. Then go to this url: http://dev-com-10.accdemo.b2c.ydev.hybris.com:4200/powertools-spa/en/USD/organization
Bill says: created #8617

- [ ] This console error is displayed when retrieving the cost center I created:
```
core.js:6228 ERROR TypeError: Cannot destructure property 'pagination' of 'undefined' as it is undefined.
    at CostCenterListService.populateCostCenters (cost-center-list.service.ts:55)
    at MapSubscriber.project (cost-center-list.service.ts:47)
```
Bill says: no longer seen.

- I cannot find the budget I created displayed in the list of budgets when accessed through a cost center. 
Bill says: known issue, being fixed.

- Every time I access the list of budgets through a cost center, it's duplicated. So second time I access it, each budget is displayed twice. Third time I access it, each budget is displayed thrice etc... 
Bill says: looks fixed.

-> it takes time for the changes to be applied:

- Cannot edit a cost center. If we change the id and name, it looks successful, but then if we go back to the list of cost centers, we can't see the change. But in backoffice, we can see it. 
Bill says: known issue, being fixed.

- We don't see the newly changes in the list of parents units under cost centers. I changed the name of a parent unit, and it's not reflected when I'm editing a cost center. 
Bill says: known issue, being fixed.

- When we enable a parent unit, its child unit isn't enabled by default.
Bill says: Not a Spartacus bug, as this is a limitation of backend.

**Comment by Xymmer** [comment]
Bill to try it and create tickets
