### ISSUE TITLE
Misleading query argument of Routing Service go() method

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8169]
Routing service has a method `go()` that allows for 2 different ways of providing the query params:
```typescript
  go(commands: UrlCommands, query?: object, extras?: NavigationExtras): void {
                              ☝️              ☝️ (extras.queryParams)
```

because the effect of `RouteGoAction` merges the `query` object into the `extras.queryParams` in the line 20:
https://github.com/SAP/spartacus/blob/a1111d3639d028b1e4b213c8ffbe86fe4e591a1f/projects/core/src/routing/store/effects/router.effect.ts#L14-L22

This is misleading, so we should drop the second `query` parameter of the method go()

This is a BREAKING CHANGE with big consequences:
- `RouteGoAction`
- and `RouterEffect.navigate$`
- and all useges of the method `RoutingService.go` with more than one parameter passed.

This is a BREAKING CHANGE of a very commonly used method. So it would be good to provide convenient schematics.

It may be difficult to write a schematics that merges the value of the second parameter `query` into the third one's `extras.queryParams` property in the customer's code.

~The easiest solution I can see: rename old method `go()` to `deprecatedGo()` (with `@deprecated` notice) in a major version and simply use schematics to rename the occurences of the method in customers' code. At the same time expose a new `go()` method in the service with improved arguments~

### Plan of attack:
- simplify the API (drop the second argument -`query`). It might require also dropping its usages in our codebase and using instead the last argument: `extras.queryParams`.
- describe the change in the migration docs
- use schematics migration helper deprecated-methods-and-properties to insert a code comment in customer's usages of routingService.go() -> describing briefly: 
   ```
   The second argument of the method go() has been removed. Use `extras.queryParams` instead.
   ```

**Comment by ren-tham** [comment]
Pr: https://github.com/SAP/spartacus/pull/12638
