### ISSUE TITLE
Fake page reload while go back

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8181]
While navigation back, we have effect like while page loading, even we don't fetch any data.
It manifests itself through e.g. that cx-storefront is getting class "start-navigating" 
![image](https://user-images.githubusercontent.com/8040837/87165852-ff433b80-c2ca-11ea-857a-c8431ef98f19.png)
What is strange, while navigate to right side (it causes fetch data), that effect doesn't occur - I'm not sure that it should.

**Comment by Pucek9** [comment]
Issue no longer exists

**Comment by tcpraba** [comment]
![image](https://user-images.githubusercontent.com/64828447/216982799-cee495f3-01e9-4ec9-8dfb-9e44c68a7180.png)
How to fix this issue???
