### ISSUE TITLE
Cannot add spartacus schematic with angular 10

### ISSUE THREAD

**Issue by mpern-sap** [SAP/spartacus#8206]
**Describe the bug**

`ng add @spartacus/schematics` fails with angular cli 10.0.2

**To Reproduce**

```
ng new project --style=scss --routing=false --packageManager=yarn
cd project
ng add @spartacus/schematics

```

**Expected behavior**

Can add schematic without any errors

**Screenshots**
```
% ng add @spartacus/schematics                                                                                                                                                             (git)-[master]-
Installing packages for tooling via yarn.
Installed packages for tooling via yarn.
            ✅️ Added '@spartacus/core' into dependencies
            ✅️ Added '@spartacus/storefront' into dependencies
            ✅️ Added '@spartacus/assets' into dependencies
            ✅️ Added '@spartacus/styles' into dependencies
            ✅️ Added '@ng-bootstrap/ng-bootstrap' into dependencies
            ✅️ Added '@ng-select/ng-select' into dependencies
            ✅️ Added '@ngrx/store' into dependencies
            ✅️ Added '@ngrx/effects' into dependencies
            ✅️ Added '@ngrx/router-store' into dependencies
            ✅️ Added 'bootstrap' into dependencies
            ✅️ Added 'i18next' into dependencies
            ✅️ Added 'i18next-xhr-backend' into dependencies
            ✅️ Added '@angular/service-worker' into dependencies
            ✅️ Added '@angular/localize' into dependencies
            ✅️ Added 'ngx-infinite-scroll' into dependencies
            🔍 Installing packages...
UPDATE package.json (1810 bytes)
UPDATE src/app/app.module.ts (871 bytes)
UPDATE src/styles.scss (117 bytes)
UPDATE src/app/app.component.html (32 bytes)
UPDATE src/polyfills.ts (3064 bytes)
Cannot find module '../package-manager/executor'
Require stack:
- /User/somebody/project/js-storefront/b2c/node_modules/@angular-devkit/schematics/tasks/node/index.js
- /User/somebody/project/js-storefront/b2c/node_modules/@angular-devkit/schematics/tools/workflow/node-workflow.js
- /User/somebody/project/js-storefront/b2c/node_modules/@angular-devkit/schematics/tools/index.js
- /User/somebody/project/js-storefront/b2c/node_modules/@angular/cli/utilities/json-schema.js
- /User/somebody/project/js-storefront/b2c/node_modules/@angular/cli/models/command-runner.js
- /User/somebody/project/js-storefront/b2c/node_modules/@angular/cli/lib/cli/index.js
- /User/somebody/.config/yarn/global/node_modules/@angular/cli/lib/init.js
- /User/somebody/.config/yarn/global/node_modules/@angular/cli/bin/ng
```

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

See discussion in Slack:
https://spartacus-storefront.slack.com/archives/CD16V16FR/p1594718783142700

**Comment by znikola** [comment]
We should back-port this to 2.0 as well.

**Comment by mpern-sap** [comment]
FYI, the schematics works with `@angular/cli@v9-lts`

**Comment by znikola** [comment]
@mpern-sap can you please confirm, did you initially try to use Angular v10 libraries with Spartacus v2?

Just to be clear, I'm not asking about the CLI version now. I'm asking about all Angular libraries.

**Comment by mpern-sap** [comment]
I just started with the CLI to bootstrap the project and it failed 🤷‍♂️ 

I haven't installed anything else from Angular

**Comment by znikola** [comment]
If you ran `ng new my-project` using Angular CLI 10, then you had angular v10 libraries specified. Spartacus doesn't support angular v10 at the moment.
Once we move to v10, we'll enable the support for schematics as well.

**Comment by mpern-sap** [comment]
could you be so kind to mention this in the docs

https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries/#front-end-development-requirements

> Front-End Development Requirements
> Your Angular development environment should include the following:
> 
> Angular CLI: 9.1 or later.
> node.js: 10.14.1 or later, < 13.0. The most recent 12.x version is recommended.
> yarn: 1.15 or later

**Comment by znikola** [comment]
Yes, definitely, the docs are misleading.

**Comment by znikola** [comment]
Created https://github.com/SAP/spartacus-docs/issues/715
