### ISSUE TITLE
Hide cx-views which shouldn't be visible

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8208]
Steps to reproduce
open http://localhost:4200/powertools-spa/en/USD/organization/cost-centers/KCostCenter/budgets 

on hover left side, we can see that cursor points on links, which are on listing page, which is out of screen
![image](https://user-images.githubusercontent.com/8040837/87420226-31a7ae00-c5d5-11ea-88f2-bbf95016bce6.png)

we should prepare mechanism which will setup `visibility: hidden;` for all cx-views, which shouldn't be visible now

**Comment by tobi-or-not-tobi** [comment]
fixed with #8924
