### ISSUE TITLE
End to end tests for approval dashboard

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8220]
Needs to test
- cancel functionality
- reject functionality
- approve functionality 

as approver

* note make sure each `it` are idempotent and does not rely to previous state. Meaning each `it` should pass without depending on the previous state.

**Comment by bgambocjaviniar** [comment]
moved back to do for someone to pick up as priorities changed

**Comment by bgambocjaviniar** [comment]
moving to do because owner for the Issue finished their internship,
**therefore**, anyone can pick up or create a new PR.

**Comment by plabadie** [comment]
PR  #9362

Regular e2e and accessibility e2e are in this PR.

To test, you can use:

```
yarn e2e:cy:run --spec cypress/integration/b2b/order-approval/b2b-order-approval.e2e-spec.ts
```
and

```
yarn e2e:cy:run --spec cypress/integration/b2b/accessibility/tabbing-order.e2e-spec.ts
```
(you could add `describe.only` to test the approval section )

**Comment by kacperknapik** [comment]
Should we continue working on that?

**Comment by giancorderoortiz** [comment]
for further consideration https://github.com/SAP/spartacus/issues/9636
