### ISSUE TITLE
ProductReferenceComponent: reference products are not updated and displayed correctly

### ISSUE THREAD

**Issue by matheb** [SAP/spartacus#8223]
**Describe the bug**
ProductReferenceComponent is not updated correctly once we click on one of the referenced products:

When I'm on the PDP of a specific product and then click on a Crosselling product, then I get navigated to the new PDP but the new product also has the same Upselling/Crosselling products as the previous one, even if the newly opened one doesn't have any product references. Refreshing the page reloads the product details page and then the wrong references are not shown anymore.

**To Reproduce**
1. Add Cross- or Upselling products and add the ProductReferenceComponent to PDP
2. Click on some of the reference products
3. Scroll down to the Product references
4. See error: the same products are shown as on the previous PDP

**Comment by marlass** [comment]
@Xymmer I think it's quite important one.

Things to fix:
- merging of lists in reducer
- mergeMap in effects
- current product code should be fetched in a different way in the component (maybe new property in product reference service)
- load references only after component data are loaded

**Comment by Xymmer** [comment]
moving to 3.0, has many changes

**Comment by bgambocjaviniar** [comment]
PR: GH-9433

to answer Marcin's concerns, please read the PR's description

QA: 

1 - go to a product with references, such as `DSC-N1` or `EasyShare Z915 red`
2 - click on a product reference and make sure that the old product with its references is not shown in that `new` product detail page

**Comment by hackergil** [comment]
I tested this using the QA server with the product mentioned above.
* Go to PDP from product 3470545 (red camera). It shows 2 product references
* Click on the blue camera (3470545). It still shows the old 2 product references from the previous product. Calls to product references are returning an empty array
> {
   "references" : [ ]
}

**Comment by hackergil** [comment]
@bgambocjaviniar Change looks good and it works. I made a few changes to the unit tests. Please check the latest commit and lmk your comments

**Comment by giancorderoortiz** [comment]
Test successful. 

Main product: 
![Screen Shot 2020-11-02 at 6 42 27 AM](https://user-images.githubusercontent.com/46171897/97864667-f55ca280-1cd6-11eb-8880-2af5eac7660f.png)

Suggestion1: 
![Screen Shot 2020-11-02 at 6 43 02 AM](https://user-images.githubusercontent.com/46171897/97864677-fd1c4700-1cd6-11eb-9400-7e15d89648a1.png)

Suggestion2: 
![Screen Shot 2020-11-02 at 6 43 27 AM](https://user-images.githubusercontent.com/46171897/97864691-03122800-1cd7-11eb-8bb4-808bc11226c9.png)
