### ISSUE TITLE
No variant images in the response's variantMatrix

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8238]
When you do a following call:
https://powertools.spartacus-dev4.eastus.cloudapp.azure.com:9002/occ/v2/powertools-spa/orgProducts/26038000?fields=name,categories,multidimensional,variantMatrix(FULL)&lang=en&curr=USD
or
https://powertools.spartacus-dev4.eastus.cloudapp.azure.com:9002/occ/v2/powertools-spa/orgProducts/26038000_2?fields=name,categories,multidimensional,variantMatrix(FULL)&lang=en&curr=USD

variant matrix element's `variantOption.variantOptionQualifiers.image` is always empty (no matter `parentVariantCategory.hasImage` is true or false):
![image](https://user-images.githubusercontent.com/788092/87669257-f7254900-c76d-11ea-84bd-6a3b9f0b6381.png)

I believe there should be image data for variant elements.  Accelerator pages (same backend, same products) contains images:
![image](https://user-images.githubusercontent.com/788092/87669913-153f7900-c76f-11ea-8b7b-bb8e823f153b.png)
however they're get there by some java logic (by product code) which I don't understand.

Otherwise please correct me if I'm doing it wrong (for example if we need to get those images in a separate call or from somewhere else).

**Comment by Xymmer** [comment]
Created https://cxjira.sap.com/browse/C3PO-2412 to continue investigation
We'll keep this one to verify when fixed in a patch

**Comment by hackergil** [comment]
I've added my response to C3PO-2412. Please go and have a look.

**Comment by mirkosoft** [comment]
Actual/new CLC ticket for this backend issue is here: https://cxjira.sap.com/browse/CLC-2412 and it's about merging `/orgProducts` into `/products` (apart of original bugfix for missing images data in the response's `variantMatrix`).

So at the end, complete `variantMatrix` should be present in the `/products` endpoint when called respectively (more details on this to come).

**Comment by mirkosoft** [comment]
Please also see the other ticket with similar issue, the cart one: https://cxjira.sap.com/browse/CLC-2495

**Comment by dydome** [comment]
The problem looks resolved with the newest hybris version.
