### ISSUE TITLE
Move login/revoke endpoint from occ endpoints to auth configuration

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8243]
Those endpoints are not related to occ, but to auth server. It should be kept together with rest of authorization configuration.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- verify that occ endpoints configuration no longer have login and revoke endpoints (also the default config)
- check if you can configure revoke and login endpoint in auth config (`authentication`) and if this configuration is used for token (login with Resource Owner Password Flow) and revoke token calls.
