### ISSUE TITLE
Fix kyma to work with the library by using different scopes

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8247]
Previously kyma was working by using different client and passing the same credentials. This have limitation to be used only with password flow. Better to use openid client for OAuth server and define correct scopes to get the idtoken along with access_token. That will work with different flows as well.

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- use OpenId OAuth client
- configure scope, responseType and customTokenParameter in `authentication` config
```
authentication: {
        client_id: 'client4kyma',
        client_secret: 'secret',
        OAuthLibConfig: {
          responseType: 'id_token',
          scope: 'openid',
          customTokenParameters: ['token_type', 'id_token'],
        },
      },
```
- verify that after login you can access id token with `OAuthLibWrapperService.getIdToken` method
- check that id token is synchronized to localStorage with rest of the token state
- verify that whole `KymaModule` is removed from the codebase
