### ISSUE TITLE
Remove user/csagent token from ngrx and keep them in AuthStorageService

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8252]

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by marlass** [comment]
QA steps:
- verify that we don't store any tokens in ngrx store (for user or for cs agent). Does not apply to client token!
- verify in auth code that we don't have actions/effects/reducers that were previously responsible for that
- check that those tokens are handled by `AuthStorageService`
