### ISSUE TITLE
Recognize and store semantic route (cxRoute) in ngrx route state

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8253]
Routing configuration is indexed by semantic routes' names and allow for:
- generating links with URLs 
- programatically navigating to an URL
- filling empty (`null`) paths in the Angular Routes (that contain the semantic name in the `data.cxRoute` property)

However sometimes there is a need, when visited an URL, to know on which semantic route we are. Such an information may be essential for CDS/tag manages to build routing events like 'search page visited' or 'product page visited'.

The plan is to expose in the ngrx routing state (so in routing facade) the information about currently activated semantic route:
1. [DONE] Since https://github.com/SAP/spartacus/pull/7974 , we already expose it, but only for product page, product listing page and brand page
2. [TODO] We should also expose Angular Route's `data.cxRoute` containing the semantic route name in the route state.
3. [TODO] For cases when the Angular Routes' `data.cxRoute` is undefined (most likely, because the URL was matched by a generic `**` CMS route https://github.com/SAP/spartacus/blob/53a1880/projects/storefrontlib/src/cms-structure/routing/cms-route/add-cms-route.ts#L7), then we need to guess the semantic route name. To achieve it, we'll lookup the routing configuraiton trying to find a path that exactly matches current URL (including homepage).

**Comment by Platonn** [comment]
### QA steps:
1. Console log the whole routing config and every time when curren URL changes, print it's semantic route name, by adding a `constructor` to your `AppModule` class in app.module.ts:
```typescript
constructor(actions$: ActionsSubject, configInit: ConfigInitializerService) {
    // print config
    configInit
      .getStableConfig('routing')
      .then((config) => console.log('config: ', config.routing.routes));

    // print current route
    actions$
      .pipe(ofType<RouterNavigatedAction>(ROUTER_NAVIGATED))
      .subscribe((action: any) => {
        console.log(`cxRoute: '${action.payload.routerState.semanticRoute}'`);
      });
  }
```
2. Run storefront, visit various pages and verify that in the console is printed `cxRoute: '<semantic name of the route>'`. Do it for:
- home
- category
- search 
- product (PDP)
- login
- register
- checkout (and the checkout steps)
- order history
- order details
- ... (any page that is defined in the routing config)


3. Visit some page that doesn't have routing configuration, i.e. `/store-finder`. Verify that in console there is printed `cxRoute: 'undefined'`

**Comment by mszczepaniak** [comment]
@Platonn I think it should be also merged to 2.0.x, right?

**Comment by giancorderoortiz** [comment]
Following compilation error in develop branch seen when adding constructor: 
ERROR in projects/storefrontapp/src/app/app.module.ts:68:53 - error TS2304: Cannot find name 'ConfigInitializerService'.

68   constructor(actions$: ActionsSubject, configInit: ConfigInitializerService) {

**Comment by kacperknapik** [comment]
**QA results:** works as expected
