### ISSUE TITLE
Product references not clearing history and has old and new data

### ISSUE THREAD

**Issue by dydome** [SAP/spartacus#8262]
Product references component is not showing correctly items in carousel, calling api many times and doing action in ngrx lts of time. Problem is that if I'm on one product with references and navigating to another product with references the new reference carousel has new reference items and also items from previous product, as clearing is not working fine.

1. Go to product with references
2. Open developer tools and go to network tab
3. Click on one product from references
4. Scroll down to references carousel
5. See new references products and also products from previus product
6. Check network tab and see many calles to api, and see that there was even call for references for previous product code

**Expected behavior**
Fresh product references carousel data

**Screenshots**
Here we can see 3 call and 1 call is for previous product.
![image](https://user-images.githubusercontent.com/18736434/87901787-326a9500-ca58-11ea-83ac-25a0a8a0ae9f.png)

 - Windows 10
 - Chrome
 - 83.0.4103.116 

In my opinion there is a problem with ProductReferencesComponent, at first once it is getting info about currentProductCode$ it is getting info from even product before navigation. Because of combineLates for items$, api is calling on each component data change and product change so it is more than expected one call. In ProductReferenceService get method should always call another method - cleanReferences, also doing that pipe probably should be rebuild.

**Comment by KateChuen** [comment]
Will be fixed by #8223.
