### ISSUE TITLE
Approval list data not cleared from the state upon user sign out.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#8284]
When a user signs out, the approval list data should be cleared from the state, but it's not.

Note: at the time of writing this ticket, the approvals feature is in branch `epic/order-approvals`.  It will then be merged in `feature/my-company`.

* To repro, sign in as an approver, display the order approval list
* Assess the data is present in the state tree under `organization > order-approval`
* Sign out the user.
* Assess that the data is still present in the state tree under `organization > order-approval`

<img width="1099" alt="Screen Shot 2020-07-21 at 4 07 44 PM" src="https://user-images.githubusercontent.com/7065346/88103731-6b495d80-cb6f-11ea-90ee-5d79e1b7ab5c.png">

**Comment by plabadie** [comment]
The organization state as a whole needs to be cleared upon logout with a meta reducer,

See an example for the `user` state slice data:

https://github.com/SAP/spartacus/blob/develop/projects/core/src/user/store/reducers/index.ts#L114-L126

**Comment by qjimmy** [comment]
PR #8310
