### ISSUE TITLE
Add occ/rest note in app.module.ts when spartacus built using schematics

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8286]
The default prefix for sap commerce 1905 is rest, but for 2005 and later, it's 2005.
To help people figure this problem out, can we add a comment in the app.module.ts, when we build the config using schematics? E.g.

          prefix: '/rest/v2/' // 'occ/v2' if 2005 or later, 'rest/v2' if 1905

**Comment by tobi-or-not-tobi** [comment]
I'd prefer the following: 
- schematics installer should not add the prefix unless specifically been requested (using `--occPrefix`)
- default the prefix value to the new prefix `/occ/v2` (new since 2005)

**Comment by znikola** [comment]
PR: #9725

The default OCC prefix is now `/occ/v2`.
The schematics will now generate the `occPrefix` option _only_ if the option is specified by the user.
