### ISSUE TITLE
Missing contextual menu on the CMS component level in SmartEdit

### ISSUE THREAD

**Issue by viktorsap** [SAP/spartacus#8288]
**Describe the bug**
SmartEdit attaches a contextual menu to each CMS component. This contextual menu allows triggering different actions on the CMS component. These actions can be for example editing, moving, cloning. In some cases this menu is missing in SmartEdit on Spartacus although there are no obvious errors related to this.

**To Reproduce**
1. Go to SmartEdit
2. Click on a staged catalog version
3. Switch to the advanced edit
4. Hover with the mouse over a component, the contextual menu should appear displaying actions available on this particular component.

**Expected behavior**
Contextual menu should be displayed on each component.

**Screenshots**
![spartacusadvancededit](https://user-images.githubusercontent.com/66991121/88131753-0c442100-cc21-11ea-9a32-6f8eb31a1a8d.JPG)
![spartacuscomponents](https://user-images.githubusercontent.com/66991121/88131747-09e1c700-cc21-11ea-852e-29f2c6e91287.JPG)

**Comment by KateChuen** [comment]
@viktorsap can you provide more information about your setup please? Which version of spartacus and backend are you using?

**Comment by Xymmer** [comment]
it's been a few months, closing, please reopen if it's still an issue

**Comment by pdziwoki** [comment]
Hello, I am experiencing exactly the same issue on version 3.3+, contextual menu is not visible at all. I launched clean Spartacus instance with the same version and connected it to my backend and it is visible there. I cannot localize what is causing the issue on customized Spartacus. Anyone has any suggestions?
