### ISSUE TITLE
Fix transferState reducer after auth removal from store

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8289]
Removed in #8252

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- run app with SSR
- login on client
- verify in redux devtools that on `INIT` action state send from server is not restored in ngrx store when user is logged in (state is empty after this action)
- verify that state is restored in ngrx when user is not logged in (state is not empty after this action, eg. CMS state should have some data)
