### ISSUE TITLE
Console error while open disable dialog

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8296]
![image](https://user-images.githubusercontent.com/8040837/88187517-e9bd0280-cc36-11ea-8d82-5dbf57d51d54.png)

**Comment by kacperknapik** [comment]
Problem not showing on the latest `feature/my-company`. Closing

**Comment by Pucek9** [comment]
Cost center modal is ok. Reopen for other features

**Comment by Pucek9** [comment]
- [x] budget disable
- [x] user disable
- [x] permission disable
+ if you can look why after close delete address modal, page is scrolling down

**Comment by Zeyber** [comment]
Cannot replicate the page scrolling myself
