### ISSUE TITLE
Backport fix for infinite loop in cart - #7209

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8316]
Spartacus Jira: https://github.com/SAP/spartacus/issues/7209
Spartacus fix in April 2020: https://github.com/SAP/spartacus/pull/7292/files
Backpor to latest 1.4.x and 1.5.x branches

**Comment by LTiger14** [comment]
PR 1.4.x: https://github.com/SAP/spartacus/pull/8317
PR 1.5.x: https://github.com/SAP/spartacus/pull/8318
