### ISSUE TITLE
Order Approval Master Ticket

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#8319]
Order approval feature epic: 
https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=B2B+My+Company-+Approval+Dashboard

Merge epic branch `epic/order-approval` into `feature/my-company` when all the tickets are done.

**Comment by plabadie** [comment]
PR Spartacus: #8196 
PR Sample data: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/111


To test:
- You need the server to be on the `feature/my-company` branch, both for spartacus and the sample data.
- Create orders that require approval, see steps to do so:  https://github.com/SAP/spartacus/issues/7856#issuecomment-648245941
- *Update: Instead of the accelerator, you can also now use b2b checkout to create orders to be approved.
- Sign in as the approver, likely `hanna.schmidt@rustic-hw.com`
- The approval feedback for the customer is in `My Account -> Order History` in the order details.
- The approval dashboard is accessible via `My Account -> Approval Dashboard`

**Comment by plabadie** [comment]
https://github.com/SAP/spartacus/issues?q=is%3Aopen+is%3Aissue+label%3Amy-company%2Fapproval-dashboard

**Comment by kacperknapik** [comment]
Should this ticket be closed already?

**Comment by plabadie** [comment]
This ticket is needed as a placeholder to QA the feature when all related tickets are merged.

**Comment by giancorderoortiz** [comment]
Some screenshots of the work completed: 

![Screen Shot 2020-11-03 at 7 44 30 AM](https://user-images.githubusercontent.com/46171897/97992618-ed713100-1db0-11eb-90bb-96b263d9ec04.png)
![Screen Shot 2020-11-03 at 7 44 45 AM](https://user-images.githubusercontent.com/46171897/97992620-ed713100-1db0-11eb-8cb9-ee0b01f20c15.png)
![Screen Shot 2020-11-03 at 7 46 24 AM](https://user-images.githubusercontent.com/46171897/97992622-ee09c780-1db0-11eb-85a4-5b7fd4b1f142.png)
![Screen Shot 2020-11-03 at 7 27 49 AM](https://user-images.githubusercontent.com/46171897/97992640-f5c96c00-1db0-11eb-9217-a80720a4d248.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-03 at 7 21 31 AM](https://user-images.githubusercontent.com/46171897/97992666-011c9780-1db1-11eb-973a-34b0d6ea1f09.png)
![Screen Shot 2020-11-03 at 7 19 10 AM](https://user-images.githubusercontent.com/46171897/97992682-0679e200-1db1-11eb-9262-3b84b16f77ec.png)
![Screen Shot 2020-11-03 at 7 19 10 AM](https://user-images.githubusercontent.com/46171897/97992708-10034a00-1db1-11eb-9b3b-cc0804190981.png)

**Comment by giancorderoortiz** [comment]
Extensive manual testing done. 
Able to approve, reject orders as expected (by both approver and admin, depending on condition) 
Order status updated for buyer and also in backoffice. 
Closing.

**Comment by giancorderoortiz** [comment]
For future consideration: 
https://github.com/SAP/spartacus/issues/9636
