### ISSUE TITLE
Reorganize B2B checkout steps

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#8331]
The B2B checkout steps were modified following UX reviews. The new source of truth can be found at https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=B2B+Checkout+Source+of+Truth+for+2.1.

### Changes to be done

- Update CMS in Spartacus sample data addon
- Update Spartacus components to reflect the changes

**Comment by bgambocjaviniar** [comment]
PR: GH-8397
Backend PR: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/113

**Comment by LTiger14** [comment]
### For review/QA

- Make sure to use the latest updates from the Spartacus sample data addon. (found in the PR above)
- Turn on `b2b` flag in your environment ts file
