### ISSUE TITLE
SSO for Spartacus

### ISSUE THREAD

**Issue by zebercut** [SAP/spartacus#8336]
So far two customers requested SSO for Spartacus.
We do have SSO in Accelerator and it is a crucial feature for customers to implement SSO in their project implementation.

**Comment by the-x-man** [comment]
@zebercut is there a reference implementation available for SAML authentication ?

**Comment by Pranavbhartia** [comment]
@Xymmer, @zebercut, 
since this is closed, could you please provide a reference to the implementation/documentation for this please.

**Comment by nicolabeghin** [comment]
@Xymmer I see you added the `before-5.0` tag: does this mean it's planned to have this available with Spartacus 5.x? thanks a lot.
