### ISSUE TITLE
State not resetting in store when on a page with a CMSPageGuard

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8345]
When you are on a page that has a CMSPageGuard like order-details, the user-order state is not completely removed when signing out, which leaves information on the store when it was supposed to be wiped. 

Other cases can be found from what I have mentioned in `Additional Context` below.

**To Reproduce**
- log in any user that has orders placed already
- open redux devtools
- look at the user > order state slice
- go to any order detail page from order history
- sign out when on an order detail page

**Expected behavior**
- State should be cleared with no information pertaining to the user that just signed out.

**Screenshots**
<img width="502" alt="Screen Shot 2020-07-28 at 8 42 11 AM" src="https://user-images.githubusercontent.com/29099466/88666763-84419980-d0ae-11ea-9bab-c4d5184ce2f9.png">

**Additional context**
As I believe it is related to the CMSPageGuard functionality, you can find this behaviour in other places, such as  organization > approval > entities and list or any organization feature that uses that `guard`.

found when resetting the organization state in #8284

**Comment by Xymmer** [comment]
to dev: validate and then fix

**Comment by bgambocjaviniar** [comment]
closing as I don't see this behavior anymore
