### ISSUE TITLE
Date Time Picker max/min params incur the offset into the limit when they shouldn't in budget form

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#8359]
The max and min parameters on the `cx-date-time-picker` components in the `budget-form` template are set depending on the start date and end date element counterparts. If you set start and end dates within boundaries of the timezone offset (ie. in CEST+2 and start/end dates are set 1 hour apart) the form becomes invalid and displays the message that max/min is breached.

This is happening because the picker components are incurring the default offset when they set their limits for max/min params when they should use no offset and truncate the date value as UTC-0. 

Example in CEST+2:

![image](https://user-images.githubusercontent.com/11735817/88805821-ed5d0600-d1af-11ea-863b-8e7ca63262cd.png)

![image](https://user-images.githubusercontent.com/11735817/88805904-05cd2080-d1b0-11ea-9018-6b165f636d24.png)

**Comment by Pucek9** [comment]
@Zeyber Still needed?

**Comment by Pucek9** [comment]
Caine confirmed that no longer needed.
