### ISSUE TITLE
Product reducerToken is not exported to the public API to allow extend-ability 

### ISSUE THREAD

**Issue by hazemfarahat** [SAP/spartacus#8360]
**Describe the bug**
The product ngrx store as well as other default stores are implemented using injection tokens. this is the correct way to allow extend-ability. But the tokens are not exported to the public API. making it impossible to extend the reducers/meta-reducers.

I am trying to clear the stored Product state when the authenticated user is modified. I found out that a meta reducer is already created for currency/language changes in the productStoreModule. I could extend that meta-reducer and re-register the store module:
`StoreModule.forFeature(PRODUCT_FEATURE, reducerToken ,{ myMetaReducers }),`

`myMetaReducers` will contain my new logic for clearing the state when action: Login/Logout happens.

the problem here is that `reducerToken` must be imported from the public api, currently it is under: `@spartacus/core/src/product/store/reducers` and is not public.

**To Reproduce**
try importing `reducerToken` from `@spartacus/core/src/product/store/reducers` 

**Expected behavior**
I believe the reducers and reducerTokens should be exported to the public api in order to allow for extend-ability, the issue also affect all other Ngrx reducers in the Spartacus libraries. 

**Suggested fix**
for the ProductStore:
add `export * as ProductReducers from './store/reducers/index` to `projects\storefrontapp\node_modules\@spartacus\core\src\product\index.d.ts`

but it should be done for other stores as well

**Comment by hazemfarahat** [comment]
@Xymmer will this issue be considered? Or is there a different approach that I should be taking to extend reducers?

**Comment by Xymmer** [comment]
@hazemfarahat will consider this proposal but we'd have to think about it.
One alternative approach is to use meta-reducer on top of the whole store, but we realize that is much work.

**Comment by Xymmer** [comment]
to Stan to comfirm whether we would take this approach, or we would try to solve this a different way
if different maybe close this one, but create a new one for future consideration

**Comment by dunqan** [comment]
After some discussion, we agreed that an ideal solution should be possible to implement above the facade layer (without the need of changing ngrx reducers, which we consider an implementation detail, that might be deprecated in future). 
For your specific case, I can see two solutions:
1. Implementing global meta reducer (on top of the store) that can take care of clearing this state for you action without the need of modifying existing reducers
2. Implementing an additional facade method which you can call to discard current product data.

The first one is doable without any changes, the second one would require an additional ticket (and some prioritization).

**Comment by hazemfarahat** [comment]
@dunqan How can I create a global meta reducer?

If I used StoreModule.forRoot(...),, Some states gets broken,, for example: siteContext.

**Comment by dunqan** [comment]
@hazemfarahat You can  provide meta reducers in NgRx using `USER_PROVIDED_META_REDUCERS` or `META_REDUCER` injection token:
https://ngrx.io/api/store/USER_PROVIDED_META_REDUCERS
https://ngrx.io/guide/store/recipes/injecting#injecting-meta-reducers
