### ISSUE TITLE
Add Current<feature>Service to avoid accessing routing in components

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8363]
Opt out of `this.activatedRoute.parent.parent.parent...` similar like in https://github.com/SAP/spartacus/issues/8308, but this time not for Cost Center but for UserGroup, Budgets and Permissions

- [x] budget
- [x] cost center
- [x] permission 
- [x] unit
- [x] user
- [x] user group @Platonn

**Comment by Pucek9** [comment]
We have more features to update
- [ ] budgets
- [x] cost centers
- [ ] permission 
- [x] unit
- [x] user
- [ ] user group
