### ISSUE TITLE
Missing translation for key userGroup.permission.per.QUARTER

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8369]
How to reproduce:
1. Go to `organization/user-groups/standardPermissions/purchase-limits`
2. Verify that i18n key `userGroup.permission.per.QUARTER` is not translated property

(by the way we should ensure if all other possible enum values are translated)
![image](https://user-images.githubusercontent.com/4001059/88831626-e2b26900-d1cf-11ea-8a47-3b5b44370563.png)

**Comment by Pucek9** [comment]
Fixed while refactor

**Comment by Matejk00** [comment]
Let's check other places, maybe we missing translations somewhere.

**Comment by Pucek9** [comment]
Please then open a  new ticket / PR
