### ISSUE TITLE
[do not merge until after 2.1] Fixing CSS layer to move from RTL to logical properties

### ISSUE THREAD

**Issue by morganm58** [SAP/spartacus#8379]
This is the first step in improving the css for directionality from the ticket #837 

Instead of using physical direction in CSS, we move the entire style library to logical properties. This is mainly about 2 changes: 
- use logical properties for margins
- use logical properties for paddings

Based on this work we will have a list of edge cases where we see issues.

**Comment by tobi-or-not-tobi** [comment]
@morganm58 We've moved this work to 3.0 milestone to avoid the long list of breaking changes. This means that we can continue on this ticket, but will only merge it when we've released 2.1.
