### ISSUE TITLE
Assign / unassign multiple items quickly, causes that previous requests are cancelled.

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8380]
Steps to reproduce: 
1. Open eg. http://localhost:4200/powertools-spa/en/USD/organization/cost-centers/Rustic_Global1/budgets/assign
2. Assign 2 items with a as little as possible time delay
3. Refresh the page

Observed results:
We can see only last checked item has been assigned successfully.

The same with unassign and with other features than cost-centers/budgets.

Possible solution: use mergeMap instead of switchMap in effects

Exception: Assign roles in Unit/Users uses PATCH (edit) flow, there can be differences.

**Comment by Pucek9** [comment]
Moved to hold for avoid conflicts with #8423

**Comment by kacperknapik** [comment]
Already done
