### ISSUE TITLE
Spartacus does not serve a Content Security Policy

### ISSUE THREAD

**Issue by meeque** [SAP/spartacus#8389]
### **NOTE: Spartacus team is not working on this ticket, but it's an important placeholder.** 

When running Spartacus, the server does not send a `Content-Security-Policy` header.

**To Reproduce**
1. [Install Spartacus](https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries/)
2. Run Spartacus with `yarn start`
3. Request Spartacus in a web-browser, or any other HTTP client, e.g. curl:
   `curl -v http://localhost:4200`
4. No `Content-Security-Policy` response header is present.
    (Nor is there a corresponding HTML meta tag.)

**Expected behavior**
Spartacus should send a `Content-Security-Policy` header with a restrictive [Content Security Policy (CSP)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy).
 A CSP should be sent with all responses that yield an HTML document (or similar), be it via hosting of static files, or via server-side-rendering (SSR). 

**Additional context**
CSP provides several directives that can improve the security of a web application. Some directives are primary defenses, while others serve as a second line of defense. Spartacus should use a restrictive CSP, because it helps prevent XSS attacks. The impact of XSS in Spartacus would be rather severe, because Spartacus holds security tokens in session/local store, which is accessible via JavaScript.

**Comment by meeque** [comment]
Here are some suggestions for the directives to use in a default CSP:

* `default-src`:
  * Should only contain the scheme source `https:`
  * May also contain the scheme source `http:`, if the current request is served via plain http. 
   (The latter may be useful for local testing.)

* `script-src`:
  * Should contain the keyword source `'self'`
  * Must not contain the keyword sources `'unsafe-inline'` or `'unsafe-eval'`
   (If that leads to compatibility problems with Spartacus, this needs to be addressed by reengineering Spartacus code that make use of inline scripts or eval. Please raise separate bugs for that, if necessary.)
  * May contain additional host-sources for 3rd-party JS libraries that Spartacus dynamically links from the web. E.g. `https://maps.googleapis.com/` for using Google Maps.

* `object-src`:
  * Should be `'none'`

* `child-src`:
  * Should be `'self'`

* `block-all-mixed-content`:
  * The directive should be present.

* `frame-ancestors`:
  * Should contain `'self'`
  * May contain additional host-sources, if this Spartacus instance is supposed to be run inside frames from other domains.
   For example use of SmartEdit with Spartacus will require the SmartEdit domain to be listed here.

The above directives should be reasonable defaults that Spartacus should serve out-of-the-box. However, this must be tested thoroughly, and adjustments can be discussed.

Also, developers who build applications with Spartacus should be enabled to adjust the default CSP. E.g. developers may want to add their own `script-src` entries if they dynamically load JS code from other sources in their custom components. Or the may want to add `frame-ancestors` if their application needs to be integrated into other sites. This should be as easy as possible and should be documented clearly.

**Comment by tobi-or-not-tobi** [comment]
@meeque Spartacus itself does indeed not provide a CSP. While most of the policy can be added with the HTML meta tag, the `frame-ancestors` directive must be ignored according to the specs, when it is declared via a meta element. This is why Spartacus does not provide the CSP. We've start working with the commerce cloud team to provide default headers as part of the deployment.

If customers still like to add the CSP headers through an html meta tag, they can add it in the index.html (which btw is  not Spartacus as well).

That being said, you make good points. We start drafting a documentation around best practice. While i'm closing this ticket, I do link it to the docs draft, so that we can validate our ideas against your input. 

Thanks!

**Comment by meeque** [comment]
How about we leave this issue open until both of these conditions are met:
* [Documentation on Security Headers](/SAP/spartacus-docs/pull/640/) is done.
* The commerce team has actually provided "default headers as part of the deployment".

Frankly, even then I think the solution may be incomplete. As you pointed out, specifying a CSP via HTML meta tags has some drawbacks. On the other hand, CSPs can be highly application-specific, so a solution provided by SAP Commerce only may not be ideal. Developers that work on a Spartacus storefront may not always have the privileges to do configuration changes on SAP Commerce hosting.

Why not provide a means to configure the CSP in `app.module.ts`? If such configuration is present, it could then be served in HTTP headers from `server.ts`. I guess that would only cover Spartacus users that use server-side-rendering, but that is recommended anyway. Or, would such solution have other gaps?

**Comment by tobi-or-not-tobi** [comment]
@meeque there is basically no control from a JS application to influence the web server setup on a deployment server, unless the deployment process would do some specific tricks to read from the JS application. I don't see this happening through the app module, but we (SPA/MTD) discussed a similar approach to use the manifest (or a similar config) to handover web server configurations. An alternative approach - control this through the cloud portal - has been discussed as well.

For now, this idea is not highest priority for MTD team. Individual tickets to mitigate specific risks are being worked on in between. 

I do leave this ticket open to keep awareness of this being an open point.

**Comment by Xymmer** [comment]
Hey all, we're moving our tickets to an internal Jira system.
I've copied this ticket to hosting team's jira for reference.
