### ISSUE TITLE
How to provide style for slots inside the template in sap Spartacus

### ISSUE THREAD

**Issue by SelvaAjithaBaby** [SAP/spartacus#8399]
I have a new template LandingPage3Template.

layoutSlots: {
        LandingPage3Template: {
          pageFold: 'Section2B',
          slots: [
            'Section2A',
            'Section2B',
            'Section2C',
            'Section1',
            'Section3',
            'Section4',
            'Section5'
          ],
        }
      }

I just wanted to give styles for the slots. Can someone help me to write a custom CSS style to align it properly?

I am using the below mentioned code but it is not working.

 %cx-page-layout{
//my code here
E.g  width: 10%;
        }

**Comment by tobi-or-not-tobi** [comment]
Please open a question at https://stackoverflow.com/questions/tagged/spartacus-storefront so you get help at the right channel.
