### ISSUE TITLE
Update libraries reported by dependabot

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8403]
See https://github.com/SAP/spartacus/network/alerts
We didn't have automatic PRs on. We decided to leave it off for now.

Dev task: Review the alerts and update the libraries (recommended one at a time), so that we have no alerts.

Some are more urgent than others, do them by severity first.
For develop only, don't backport.

**Comment by Xymmer** [comment]
This ticket will take care of all alerts, but also for 3.0 we're updating Angular, which means all libraries will be updated (as necessary).
