### ISSUE TITLE
Cleanup impexes

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#8419]
We should leave only configuration for main feature components like manage cost centers (organization/cost-centers)

We can remove routes to all specified paths like 
organization/cost-centers/create
organization/cost-center/
organization/cost-center/edit/
etc.

branch name - feature/my-company

Scope:
- [ ] budgets
- [ ] cost centers 
- [ ] users
- [ ] user groups
- [ ] units 
- [ ] purchase limits (permissions)

**Comment by Xymmer** [comment]
we also need to update the impex for the menu
- remove "My Company" entry completely
- add "My Company" as entry that points to Home page, in My Account

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledataaddon/pull/117
