### ISSUE TITLE
Exporting of TranslationChunksConfig model

### ISSUE THREAD

**Issue by artem-zur** [SAP/spartacus#8439]
## Problem overview

Model `TranslationChunksConfig` does't available from any Spartacus packages

## Environment Details

- Spartacus: *-2.0.5

## Solution

Need to export model `TranslationChunksConfig` to provide availability for using inside custom Storefront application

## Temporary solution

Duplicate TranslationChunksConfig model inside custom Storefront where we need it:

```
interface TranslationChunksConfig {
  [chunk: string]: string[];
}
```

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by kacperknapik** [comment]
**QA results:** `TranslationChunksConfig` available for import correctly
