### ISSUE TITLE
.make-container-max-widths() no longer available as of bootstrap 4.5.1

### ISSUE THREAD

**Issue by nderise** [SAP/spartacus#8444]
**Describe the bug**
With the 4.5.1 version of bootstrap, `yarn start` fails when installing Spartacus using schematics with the following error
`ERROR in ./src/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--13-1!./node_modules/postcss-loader/src??embedded!./node_modules/sass-loader/dist/cjs.js??ref--13-3!./src/styles.scss)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined mixin.
  ╷
7 │   @include make-container-max-widths();
  │   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**To Reproduce**
1.$ ng new mystore --style=scss
2.$ cd mystore
3.$ ng add @spartacus/schematics
4.$ yarn start

**Expected behavior**
Server starts, listening on port 4200

**Desktop (please complete the following information):**
 - OS: darwin x64
 - Browser : cli
 - Version 2.0.6

**Additional context**
One of the commits ([#30969](https://github.com/twbs/bootstrap/pull/30969)) in the 4.5.1 bootstrap release, removes the mixin mentioned above which is called explicitly in `container.scss` within @spartacus/styles.
Specifically requesting 4.5.0 in `package.json` circumvents the problem for now

**Comment by Xymmer** [comment]
related to #8498?

**Comment by nderise** [comment]
Yes. Same issue. Bootstrap has fixed it and doesn't plan to remove this mixin for version 4. I think this should probably be closed unless some action needs to be taken to document that specifically version 4.5.1 of bootstrap will cause build errors in Spartacus

**Comment by Xymmer** [comment]
thanks! W recommend 4.2.1 (not 4.5.1) and it looks like they fixed this in 4.5.2. we're reverting our hard-coding of 4.2.1 for future releases, and we also will remove our use of deprecation function (see #8498).
