### ISSUE TITLE
Store basesites in state

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8459]
The loading of the baseSites and selecting of the active baseSite is not following the default architecture:
- the data is not stored in the ngrx store
- the endpoint configuration isn't leveraged
- the connector/adapter pattern is not used

Moreover, the loading of baseSites and selecting of the baseSite is done twice, once to support multi-site and once for the SmartEdit integration. 

We should fix this, for several reasons: 
- better code
- more performant code (skipping duplicate calls)
- better extensibility
- unblocking features (mainly dynamic theming)

Proposal:
- Store baseSites entities and active baseSite in ngrx
- Align SmartEdit / multi-site approach
- Use standard layers (facade, connector, adapter)
- Use configurable endpoints (consider using scopes for various data)
- Consider reusing (active) language and currencies from the baseSite 
- Prepare the new architecture to be available for site landing page or site context selector

**Comment by tobi-or-not-tobi** [comment]
When having this refactor in place, we can also start using the baseesite.channel in spartacus to distinguish b2b vs b2c.

**Comment by Xymmer** [comment]
does the api return the base site theme name, and so customer can name the theme they want to use?

**Comment by WeizhengSap** [comment]
To QA: it can be tested in smartedit. You should be able to open the product details page in smartedit.
