### ISSUE TITLE
Drop B2BSearchConfig and use SearchConfig instead

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8463]
Drop custom model `B2BSearchConfig` and use the standard `SearchConfig`.

**Comment by Platonn** [comment]
OCC endpoints often allow for only 3 properties:
```
    pageSize?: number,
    currentPage?: number,
    sort?: string
```
which is a common for all listing endpoints (storefinder, myinterests, etc.)

So it's tempting to reuse `PaginationModel`. But it's a type for the response, which contains also `totalPages` and `totalResult` properties which is wrong to put in the search param request.

That's why I propose adding one common model with only those 3 properties:
```
    pageSize?: number,
    currentPage?: number,
    sort?: string
```

Yet another argument to make it consistent type - add a serializing function to group parallel requests with the same params:
But to `group` calls with the same options we need to group them by some key. And the key would likely contain not only the id of the resource, but also the sort/pagination options. When we have one common type for pagination options, it makes a lot of sense to have one common serialization function to transform them into a string part of the grouping key.

**Comment by wangzixi-diablo** [comment]
Hi @Platonn 

This issue is already fixed by Marcin Lasak via his commit: https://github.com/SAP/spartacus/commit/359956f3cf4452a919d02fc437091cf7916afe17

I have got his confirmation from slack, that this issue could be closed.

Best Regards,
Jerry
