### ISSUE TITLE
Better abstraction on auth config

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8477]
Make use of `AuthConfigService` in more places. Handle OAuth config from the AuthConfig.

Do after exploration of implicit/authorization code flows as we will have more common configuration cases discovered.

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- check if you can access all options from authentication config with `AuthConfigService`.
- check if changes in config are also reflected in results from service methods
- check if in spartacus code we access auth config through `AuthConfigService`. No direct access to config.
- check if `AuthConfigService` returns sensible defaults when some properties are not set in auth config.
