### ISSUE TITLE
Guard improvements

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8479]
Return url tree instead of redirecting inside of them. Applies to auth guards and checkout guards.

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- validate that all guard behavior is exactly the same as before (AuthGuard, CartNotEmptyGuard, CheckoutGuard, OrderReturnGuard and rest)
- check if guards return UrlTree instead of invoking `routingService.go`
