### ISSUE TITLE
Update token storage to only work on one token

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8484]
We no longer have to keep 2 tokens at the same time (for cs agent and user). Instead we have only one token always and only have info for who it is.

It is required to implement different flows (such as implicit flow and authorization code)

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- validate that is no longer possible to be logged in at the same time as CS agent and user
- when login as CS agent during user session this user should be instantly emulated (logout should restore user session - only applies if cs agent doesn't stop emulation)
- when CS agent is logged in user should not be possible to login (errors should popup for user)
