### ISSUE TITLE
Test Authorization code flow with the new architecture

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8485]
Try hybris auth if it already supports authorization code flow. If so then configure to use it. Otherwise test on external OAuth provided Auth2, Okta.

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- validate if authorization code flow works (login, test common user path, logout) with new auth module and OAuth server (add authorization_code for OAuth client in backoffice and configure redirect url to match the app url).

Configuration needed in app:
```
authentication: {
        client_id: 'client4kyma',
        client_secret: 'secret',
        OAuthLibConfig: {
          responseType: 'code',
        },
      },
```
