### ISSUE TITLE
Deprecate storageSync mechanism

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8489]
Deprecate storageSync configuration and reducer.

Inspect the code for anythign related to it and create tickets for `4.0` release to remove those occurances.

Try to deprecate the config option in a way that the deprecation is visible for end developers.

Keep the transfer state mechanism!

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by kacperknapik** [comment]
**QA steps**
1. create a variable
2. add `StateConfig` type to it (look at the screenshot below)
3. add `state` object, within it try to use `storageSync`

**Expected**
1. `storageSync` prop should be shown with a strikethrough (look at the screenshot below)
2. `storageSync` prop (when used) on hover, should show `@deprecated` info

![image](https://user-images.githubusercontent.com/22354613/98234992-83e45480-1f61-11eb-88e7-b28baee994db.png)
