### ISSUE TITLE
Introduce breadcrumb API

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8490]
The current breadcrumbs are driven by CMS page data. The page data can be resolved by pageResolvers, so that a specific breadcrumb is build whenever the page CMS data is changing. 

There are scenario's where this approach is limited. We've introduced nested child components and whenever they're used, the page is no longer fully backed by a CMS page. The UX however requires to introduce additional crumbs for those nested components. 

This is why we need a solution to add breadcrumbs dynamically. Some ideas that we discussed to solve this:
- Introduce dynamic breadcrumbs in the router; i.e. breadcrumb data in router data
- allow to resolve the breadcrumb data; we might have dynamic data, i.e. page title
- Allow for multiple levels; we can build the breadcrumbs based on all routes
- Allow for i18n keys to resolve static breadcrumbs.

**Comment by Platonn** [comment]
Closed by commit https://github.com/SAP/spartacus/commit/aec889f60acf1a0382e5562f61b266f02b545423

**Comment by Platonn** [comment]
QA steps:
1. Login as Linda Wolf
2. Visit some My Company page and verify its breadcrumbs:
  - For example visit http://localhost:4200/powertools-spa/en/USD/organization/units/Services%20East/addresses/8796098920471/edit
  - and verify the breadcrumbs are `Home / Organization / All units / Services East / Shipping addresses / 700 E 50th Street, New York, 10022`
  - then click some links in breadcrumbs and verify you're navigated to the correct page
  - then walk around the whole Organization feature, traverse into the child routes and verify all the child routes's breadcrumbs are correct

**Comment by psmul** [comment]
QA steps done. Breadcrumbs work correctly:

`http://localhost:4200/powertools-spa/en/USD/organization/units/Services%20East/addresses/8796098920471/edit`
![image](https://user-images.githubusercontent.com/10993491/95315627-04e0fb00-0893-11eb-82ff-5663e39aa13f.png)

`http://localhost:4200/powertools-spa/en/USD/organization/units/Custom%20Retail/addresses/8796098986007/edit`
![image](https://user-images.githubusercontent.com/10993491/95315826-4d001d80-0893-11eb-883d-b9d75d17afea.png)

`http://localhost:4200/powertools-spa/en/USD/organization/budgets/Weekly_2_5K_USD/edit`
![image](https://user-images.githubusercontent.com/10993491/95315891-60ab8400-0893-11eb-826a-bd0d50c06320.png)

`http://localhost:4200/powertools-spa/en/USD/organization/purchase-limits/Rustic_3K_USD_MONTH/edit`
![image](https://user-images.githubusercontent.com/10993491/95315949-70c36380-0893-11eb-807c-60f1b0f35012.png)
