### ISSUE TITLE
Auth and ASM version of AuthStorageService

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8493]
Provide simple version of AuthStorageService for `AuthModule` and more complex for ASM

**Comment by marlass** [comment]
This PR also covers the scope of #8494

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- verify that auth (login, refresh page, logout) works when `AsmModule` is not included in `StorefrontModule`
