### ISSUE TITLE
Improve the OccUserId

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8495]
No `current` usage of occ in AuthService

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
This ticket is no longer valid.
We don't have better idea for abstraction on top of UserIdService to accomodate different user id solutions, because we lack information about real world usage of user id.
We kept the usage of `current` in auth services.
However the number of files touching this topic is much smaller and it is feasible to override each service working on it and adjust to specific scenario.

No need to QA.
