### ISSUE TITLE
Remove the bootstrap mixin dependency

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8498]
Since bootstrap 4.5.1 `make-container-max-widths` mixin is not present anymore which cause build error as spartacus make use of it. Let's check if we can remove it and remove if yes.

related to #8460

**Comment by mirkosoft** [comment]
However they've already brought it back and marked as deprecated:
https://github.com/twbs/bootstrap/pull/31438
So if we can't remove the mixing we can revert the #8460 as 4.5.2 whould be the latest version (which shouldn't break the build).

**Comment by Xymmer** [comment]
Let's also check if #8444 is same issue as this one, and close other as dupe if so

**Comment by Xymmer** [comment]
We have ^ in our yarn but when installing bootstrap can update 4.x.x

**Comment by Xymmer** [comment]
bug triage team agrees:
- don't depend on this function as it's deprecated
- unfreeze bootstrap after we don't depend on this function

can be done by miguel/mikel, but not urgent, setting to 3.x

**Comment by Xymmer** [comment]
can be 3.x or sooner depending on capacity
