### ISSUE TITLE
Move B2B models from core to feature lib

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8499]
Our very core model like `Order` were lately (in last 2 months) polluted with b2b-related properties (i.e. order.costCenter) . This prevents us from moving b2b-related types (i.e. CostCenter) from core to the feature lib, because core would depend then on the feature lib (Order would depend on CostCenter).

We see a hope in the ongoing ticket for _Extensible types_ (aka _Types augmentation_) https://github.com/SAP/spartacus/issues/7940

This will allow for keeping thin `Order` in the core lib, but in the my-account lib import this TS interface and _re-declare_ it with adding new properties (like `costCenter: CostCenter`). Then the core lib  won't depend on the my-account lib.

It's a follow up of https://github.com/SAP/spartacus/issues/8423
~Blocked by https://github.com/SAP/spartacus/issues/7940~

**Comment by marlass** [comment]
Actually `Order` is more of an checkout lib responsibility so it should not be moved to `my-account`. However this task still applies for other models that are primarly used in `my-account` and also needed in B2B Checkout. Then the `my-account` properties of those models should be moved there utilizing type augmentation.
