### ISSUE TITLE
Can't see focused item when tabbing through too many split view menus

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#8510]
Open a deep split view menu item such as unit/addresses/details (3/4 menus deep). Once there are menus offscreen, start pressing tab. The offscreen menu items will get focused by the tab key but we are unable to see them.

**Comment by Zeyber** [comment]
Hold while we wait for #8535. Check again after it is finished.

**Comment by kacperknapik** [comment]
Fixed by #8535
