### ISSUE TITLE
Unknown auth error when logging in or out of b2b

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8515]
Might be similar to #7865
Might already be taken care of in other B2B Branch

when using mycompany-main branch from Aug8, log in as linda.wolf, and there is nothing in the cart, was getting unknown auth errors for both log in and log out. However Aug 10, I cannot repro. Tried with mark, linda, and hanna.

**Comment by Xymmer** [comment]
GC wil try to repro and add feedback here

**Comment by Matejk00** [comment]
Tried to reproduce by log in as linda.wolf, but error not showing up. The same during logout. 

Let's wait for GC's feedback.

**Comment by Matejk00** [comment]
Will be fixed in #9091
