### ISSUE TITLE
Display note when editing root unit, about not changing parent

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8519]
When editing root unit, the parent unit field is not displayed.
That's fine, but add a note:

"This unit is the top-level unit for your organization. It cannot be assigned to another unit."

**Comment by KateChuen** [comment]
Tested on develop branch, using yarn. 

OK now.
<img width="506" alt="Screen Shot 2022-05-06 at 1 39 12 PM" src="https://user-images.githubusercontent.com/45409515/167188014-56003e8c-9791-401d-93a0-70ec4a72f122.png">
