### ISSUE TITLE
Fix language for titles "Assign x for x"

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8521]
Generally, for assignment titles, use "for" or "to"
(If confused by my list, let's do a call.)
e.g.
![image](https://user-images.githubusercontent.com/4998145/89843433-b17a5700-db46-11ea-9730-e5224448464c.png)
should be "Assign budgets to <cost center>"

Here's a list:
- Change user roles [don't write anything else]
- General assignment of many things to one thing
Assign budgets **to** <cost center>
Assign approvers **to** <unit>
Assign approvers **to** <user>
- When assigning things to any user groups
Assign <user> to user groups
Assign <purchase limits> to user groups
- When assigning things to a user group
Assign users to <user group>
Assign purchase limits to <user group>

- New shipping address for <unit> (already correct)

**Comment by tobi-or-not-tobi** [comment]
Outdated, titles have change after UX changes
