### ISSUE TITLE
Updated texts for disabling things

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8525]
Do these come from backend? or they are in Spartacus?

Disable cost center:
Title: Confirm disble cost center
Body text:
You are about the disable the cost center:
  *Cost Center 1*
  ID: cost-center-id
*Warning! Disabling this Cost Center will make it unavailable when placing orders.* Existing orders are not affected.

**Comment by Matejk00** [comment]
Duplicate of #11322
