### ISSUE TITLE
Preference to click row and not name when clicking MyCo lists

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8526]
When displaying a list of things e.g. users, I had a tendancy to try to click anywhere in the row, not the name.
Wold be a good improvement to allow the row to be active.

In the following example, i can only click the name link.
![image](https://user-images.githubusercontent.com/4998145/89844657-4468c080-db4a-11ea-9b02-608fa7353658.png)

**Comment by Matejk00** [comment]
Already done.
