### ISSUE TITLE
When displaying unit tree, clicking parent unit, not obvious something happened

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8527]
Go to units tree
Click a sub-unit, details appear at right
Click the parent unit of the sub-unit
Something happens, but it's not obvious.
Maybe need some kind of animation here to indicate something new is being shown.

**Comment by Pucek9** [comment]
@Xymmer 
While click parent in details, we can see change selection on tree. Could you verify that is ok for you now?
