### ISSUE TITLE
Nice little lines between sub-things

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8528]
See screenshot
A nice light grey line would show some difference between the rows of sub-things
![image](https://user-images.githubusercontent.com/4998145/89844853-d40e6f00-db4a-11ea-8846-28a5c230d975.png)

**Comment by Pucek9** [comment]
Seems as already done
![image](https://user-images.githubusercontent.com/8040837/109652578-41720380-7b60-11eb-81d5-83f502abf78b.png)

**Comment by Pucek9** [comment]
Seems as already done
![image](https://user-images.githubusercontent.com/8040837/109652578-41720380-7b60-11eb-81d5-83f502abf78b.png)
