### ISSUE TITLE
When displaying last list, the icon that is used usually means "pop out"

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8530]
See screenshot. We need another icon to show you are "breaking out" of the panes. This is not an improvement but a visual bug, as we show one thing that means something else.
However it's also weird that you can't click the names. Maybe we should just allow that and forget the icons. To be discussed.

![image](https://user-images.githubusercontent.com/4998145/89844897-ff915980-db4a-11ea-957f-76568020e233.png)

Also, should the icon always be right next to the word, like in this example? This further confusers things.
![image](https://user-images.githubusercontent.com/4998145/89844977-3cf5e700-db4b-11ea-8735-dc3f1dc40bcf.png)

**Comment by Pucek9** [comment]
> Also, should the icon always be right next to the word, like in this example? This further confusers things.

Unit details -> parent unit icon has been fixed in #8546
