### ISSUE TITLE
Expand/Collapse in tree listing should be positioned same as other commands

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8531]
Our system of commands is:
Title
Commands
Data

So Expand/Collapse should be like Edit Details, outside the box.
![image](https://user-images.githubusercontent.com/4998145/89845058-73336680-db4b-11ea-9ceb-5db335f36bbf.png)

**Comment by cmanciero** [comment]
@Xymmer Where is this screen located in the Spartacus application?

**Comment by cmanciero** [comment]
<img width="1155" alt="Screen Shot 2022-04-01 at 3 08 43 PM" src="https://user-images.githubusercontent.com/664825/161326556-eac6a848-0b2a-45f4-ab22-e28034efb2cc.png">

Is this still an issue? The screens look different now from the issue.

**Comment by Xymmer** [comment]
looks like it doesn't exist anymore, closing as old
