### ISSUE TITLE
When showing tree for first time, select top unit

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8532]
When I go to units first time, I see a tree a lots of white space.
As a post-get step, figure out the root unit and display that.
![image](https://user-images.githubusercontent.com/4998145/89845138-a4ac3200-db4b-11ea-8bf1-f88afc541158.png)

If this isn't part of the api, fake it and create a CLC issue.

**Comment by tobi-or-not-tobi** [comment]
We're not going down this root as we've merged the tree with the table component. we have a consistent view as well as we no longer have massive whitespace.
