### ISSUE TITLE
Improve and style up the My Co home page

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8533]
powertools-spa/en/USD/organization/home
- [x] Dev: reorder chunks. Also order approvals won't show up here:
<table>
<tr><td>Units</td><td>Users</td></tr>
<tr><td>Cost Centers</td><td>Budgets</td></tr>
<tr><td>Purchase Limits</td><td>User Groups</td></tr>
</table>

- [x] Dev to change this so the box highlights on hover and clicking anywhere in the box goes to that section. (#8621)

- [x] Suleem to provide some colors/shading and new icons
(see https://cxwiki.sap.com/display/spar/B2B+Home for both)

- [x] Update icons according to new UX (done in sample data PR 102)

- [x] Bill to provide new texts (on a wiki)
https://cxwiki.sap.com/display/spar/B2B+My+Company+Texts

Here's the home page as of creation of this ticket:
![image](https://user-images.githubusercontent.com/4998145/89845273-040a4200-db4c-11ea-9520-2c12507948e4.png)

**Comment by Pucek9** [comment]
PR for update banner texts and order -> https://github.tools.sap/cx-commerce/spartacussampledata/pull/137
