### ISSUE TITLE
Facets - exception after expanding facet

### ISSUE THREAD

**Issue by mtchorz-sap** [SAP/spartacus#8565]
**Describe the bug**
Exception is being thrown when I try to expand facet which has't been expanded initially.

**To Reproduce**
1. Go to any category (Film-Cameras on screnshot).
2. Click on megapixels
3. Exception is being thown
`vendor.js:12407 ERROR TypeError: Cannot read property 'nativeElement' of undefined
    at FacetComponent.get isExpanded [as isExpanded] (vendor.js:127524)
    at FacetComponent.toggleGroup (vendor.js:127515)
    at FacetComponent_ng_container_0_Template_button_click_1_listener (vendor.js:109342)
    at executeListenerWithErrorHandling (vendor.js:22625)
    at wrapListenerIn_markDirtyAndPreventDefault (vendor.js:22660)
    at HTMLButtonElement.<anonymous> (vendor.js:47353)
    at ZoneDelegate.invokeTask (polyfills.js:621)
    at Object.onInvokeTask (vendor.js:35346)
    at ZoneDelegate.invokeTask (polyfills.js:620)
    at Zone.runTask (polyfills.js:389)`
4. Megapixels node is not being expanded

**Expected behavior**
Megapixels node should be expanded.

**Screenshots**
<img width="1965" alt="Screenshot 2020-08-12 at 11 13 35" src="https://user-images.githubusercontent.com/4405725/90019142-4ba8df00-dcae-11ea-8dc5-0c1b34cc2ace.png">

**Desktop (please complete the following information):**
 - Spartacus: 2.0
 - Browser: Chrome
 - OS: Mac OS Catalina
 - Device: MacBook Pro

**Additional context**
Problem appears when topValues collection is empty (https://github.com/SAP/spartacus/blob/adb901bf44da5806662465a1c8c39916c3829f51/projects/storefrontlib/src/cms-components/product/product-list/product-facet-navigation/facet/facet.component.ts#L76).

**Comment by tobi-or-not-tobi** [comment]
Different approaches to tackle this if topValues is an empty list (`topValues: []`):
- threat is an error and replace the topValues with the default number
- take it serious and avoid topValues by default. Only the "show more" button would appear

**Comment by diegomaradona21** [comment]
@tobi-or-not-tobi  if there is not topValues you should show all the values. If you want to limit it then you should configure topValuea

**Comment by tobi-or-not-tobi** [comment]
QA:
- Ensure that facet `topValues` are driven by the backend.
- Ensure that the lack of facet `topValues` will result in a default topValues (default is 6).
