### ISSUE TITLE
Run regression against a 2011 backend for e2e testing

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8570]
Please ask Bill or GC for a server, and verify the current status of running the e2e suite against a 2011 backend after it is properly setup with the necessary configs, such as e2e impex, users, and no missing breadcrumbs.

Basically, we need to verify if no current implementation is breaking against the new backend version, therefore please create a list if there are any.

**Comment by giancorderoortiz** [comment]
See https://github.com/SAP/spartacus/issues/9371 for server details

**Comment by giancorderoortiz** [comment]
@hackergil fyi

**Comment by Xymmer** [comment]
was done by Louis, now we will set up automated recurring

**Comment by giancorderoortiz** [comment]
What are the results? All tests passed? 
This ticket is being used by @hackergil as well for trials with CI.

**Comment by hackergil** [comment]
@LTiger14 can you share the test results or a link to the cypress dashboard for this?

**Comment by giancorderoortiz** [comment]
https://github.com/SAP/spartacus/issues/9576
