### ISSUE TITLE
implement the UI/UX for viewing the replenishment order list (history page)

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8577]
master ticket: GH-8202

Scope of this ticket is to:

- make the page cms driven by verifying the components in the b2b-accelerator module, and implement it
- Take a look at the order history component as they are similar. Keep it consistent.

**Comment by saad-mo** [comment]
Sample data PR - https://github.tools.sap/cx-commerce/spartacussampledata/pull/129
