### ISSUE TITLE
NullInjectorError is thrown in the console

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#8582]
This exception is thrown in the console. When one goes to the home page.
R3InjectorError(AppModule)[MessageConfig -> MessageConfig -> MessageConfig]: 
  NullInjectorError: No provider for MessageConfig

![image](https://user-images.githubusercontent.com/61147963/90105056-8c076c00-dd45-11ea-87a7-32aa5d431e85.png)

**Comment by ChristophHi** [comment]
Fixed with https://github.com/SAP/spartacus/pull/8434
