### ISSUE TITLE
Clarify what happens with the product after clicking on "Save for later"

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#8586]
**Current situation:**
After clicking on the **Save for later** link the product disappears. Is it **removed** or **saved** somewhere? The question is where the product is.

**Comment by ChristophHi** [comment]
This is explained in SAP internal ticket https://cxjira.sap.com/browse/TIGER-6572.
At the moment we don't support this and need to disable this feature.
