### ISSUE TITLE
Clarify what setup is missing for cpq02 user

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#8587]
After log in the cpq02 has to input the **coupon code** in order to do anything in the cart, for example, **remove**, **edit configuration** and so on.

**Comment by ChristophHi** [comment]
This is not related to the user but to our setup w.r. to the selective cart. It seems that the selective cart is active while the respective component is not available (so no errors in console, but still the system expects a selective cart to be loaded and therefore sets cart to be 'loading').
See CartDetailsComponent, onInit

**Comment by ChristophHi** [comment]
I wasn't 100% correct with my first comment.
The issue has been clarified, see https://sap-cx.slack.com/archives/GMSL1MGUR/p1598621095006800.
We can either de-activate selective carts or enrich cpq02 with the customer ID => team to decide
