### ISSUE TITLE
MyCo doesn't handle users who don't have customer IDs

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8607]
I created a new admin manually in Backoffice, with a new root unit, for testing.
marinoadmin@sap.com
I didn't create a customer ID though, which normally would be created if you register or if created through My Company (samdownson@sap.com).

Everything seemed to work until I tried to edit myself. Clicking my own account displayed the home page. I later added a second admin with no ID, and the same one was showing up twice:
![image](https://user-images.githubusercontent.com/4998145/90298115-e0523f00-de5e-11ea-9361-771620adf4d9.png)
As soon as i added an ID, all worked ok.
![image](https://user-images.githubusercontent.com/4998145/90298130-f52ed280-de5e-11ea-9db0-49060336773b.png)

I'm not sure we want to try to fix this, but we should display a warning maybe? Or at least document.
Discuss with backend devs to be sure.

**Comment by Pucek9** [comment]
@Xymmer 
This is really hard stuff to handle, as we chosen customerId as universal ID (accepted by all endpoints). If there are no functions (business sense) to have users without customerId, IMO it should be obligatory to avoid cross-platform issues.
