### ISSUE TITLE
[closing won't fix] Need apply/cancel for calendar widget

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8612]
When i was choosing a date/time for budget, i was looking for Apply/Cancel buttons. I was afraid clicking outside of the calendar, I'd lose my selection.

**Comment by Pucek9** [comment]
@Xymmer I'm affraid that it's not possible. That is not widget - we uses default browser datetimepicker.

**Comment by kacperknapik** [comment]
To confirm with Bill

**Comment by kacperknapik** [comment]
Related to #9333

**Comment by kacperknapik** [comment]
Moving to stretch, since it's an improvement

**Comment by Xymmer** [comment]
we'd need to do calendar picker ourselves from scratch, so this ticket as an improvement will be part of that design when we do it
