### ISSUE TITLE
When changing sub-somthing, auto-select parent unit, but allow changing

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8614]
While setting up my organization, i realized i would have liked to be able to change the parent unit of something, if i started creating a unit while inside a parent unit.
e.g.
Click root unit HHH
Click Child units
Click New Child Unit
The parent unit is automatically selected, but I can't change it.

This is the way it worked in Accelerator, but I was in a situation where I wanted to change it (partially due to how our UI works).

Are we technically able to auto-select here, but still allow changing it? It's up to the user to go find it later.

**Comment by Pucek9** [comment]
@Xymmer 
IMO This is against the assumptions of nested views (UX).
We had to chose it before:
- `create unit` redirecting to route `units/create` with pre-selected (potentially changeable) unit
OR
- `create unit` redirecting to route `units/:code/children/create` with selected (hardcoded) unit

As we have second option now, mixing approaches doesn't seems transparent
