### ISSUE TITLE
Reasonably long names get truncated in listings

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8616]
When creating my organization, i created some long-ish names, but they are not absurdly long.
Unfortunately our listing doesn't accomodate these well.
The simple solution is to allow the name to go onto two lines.
![image](https://user-images.githubusercontent.com/4998145/90299218-4fca2d80-de63-11ea-9f8d-6720e65eabc2.png)

It is very useful to be able to name and identify all the different "things" in my company, so although we have truncation with ... in another ticket, i'd rather see this improvement in the future.

**Comment by Pucek9** [comment]
Issue created for previous version of UI, now it's solved.
