### ISSUE TITLE
Non-admin user can access MyCompany through Url

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8617]
Login as mark rivers. Then go to this url: .../powertools-spa/en/USD/organization
Can see the units page, but it's blank
![image](https://user-images.githubusercontent.com/4998145/90299513-54dbac80-de64-11ea-8496-bcf73ccae360.png)

**Comment by Pucek9** [comment]
Actual result:
![image](https://user-images.githubusercontent.com/8040837/104027327-88c6be00-51c7-11eb-9d5a-40e74811dcaa.png)
