### ISSUE TITLE
Admin creates user with email with + symbol, doesnt work for login

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8618]
Created user with email sam+downson, but when i went to log in, it wouldn't work.
 i had to remove the +.
If we know this doesn't work, prevent + in email forms.

**Comment by mirkosoft** [comment]
Seems backend doesn't decode/handle properly the `username` if it's URI encoded. Checked locally and bad credentials received when trying to login with encoded username (used `encodeURIComponent` as @tobi-or-not-tobi suggested in #4260 ).
Waiting for the outcome of the PLAIN ticket:
https://cxjira.sap.com/browse/PLAIN-272

**Comment by Pucek9** [comment]
I was able to create user plused+user@domain.com and login
