### ISSUE TITLE
Browser Back from order (confirm) display navigates to order search

### ISSUE THREAD

**Issue by Uli-Tiger** [SAP/spartacus#8628]
**repo:**
- configure a product and proceed through checkout.
- on order confirm screen, navigate to the configuration details of an order item
- navigate back using browser back

**Issue:**
- you end up on the order search result.

**expected:**
- you navigate to order display page

**Comment by ChristophHi** [comment]
This also happens for other navigations from orderConfirmation. As we are simply using browser back for this navigation, SPA resolves the target to the order history overview.
Fixing this would force us to introduce a specific link or button for the back navigation, seems too much effort (@JayEmKay-8 correct me if you see this differently)

**Comment by JayEmKay-8** [comment]
I talked to Anthony, our UX designer, and here is what he said: This is not a bug, this is industry-wide standard. There's no reason to go back to the order confirmation once you leave the page. The page is quickly generated and quickly discarded. Once you navigate away from it, it's gone. This is an industry-wide thing. The only shot of seeing it is if you finish the transaction. You get an email and that is your hard copy. That is understood behaviour by the users.
