### ISSUE TITLE
fix the styling on the replenishment order card at the review step of checkout

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8642]
**master ticket: GH-8202**

The styling for the schedule replenishment looks okay, except when the clicking `Week(s)` from the dropdown

Please take a look at https://fi0yed.axshare.com/#id=3z1ax7&p=d_final_review_replenishment&g=1 for the wires on checkout review step page on the `Auto replenish order` card.

Note: 
* in `environment.ts` set it to https://spartacus-dev4.eastus.cloudapp.azure.com:9002. Moreover, make sure the config is set to true for `b2b`, and `yarn start` as usual. 
* branch: `epic/b2b-scheduled-repl`

Goal: 
- make it look like the mocks for the `card`, where it is currently like this when `Week(s)` is chosen. 
- fix the whole styling if it is not good enough
- disregard all the other components in the checkout's layout as we just want to focus specifically on the schedule replenishment card. 
- No need to change the default value as said in the mocks

Current implementation's screenshot:

Daily:
![Screen Shot 2020-08-19 at 4 58 49 PM](https://user-images.githubusercontent.com/29099466/90689136-8c1fd400-e23d-11ea-9587-d91bc70a127c.png)

Weekly: 
![Screen Shot 2020-08-19 at 4 55 59 PM](https://user-images.githubusercontent.com/29099466/90689174-9cd04a00-e23d-11ea-902c-b9c74d30a1a6.png)

Monthly:
![Screen Shot 2020-08-19 at 4 59 38 PM](https://user-images.githubusercontent.com/29099466/90689194-a5c11b80-e23d-11ea-9ba7-4b7e7f14d7d9.png)

**Comment by giancorderoortiz** [comment]
New styling seen. 
Good.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 8 03 53 AM](https://user-images.githubusercontent.com/46171897/92385959-d380de00-f0e0-11ea-9d2b-08489b76063a.png)
![Screen Shot 2020-09-07 at 8 04 06 AM](https://user-images.githubusercontent.com/46171897/92385961-d4b20b00-f0e0-11ea-9ba9-67ae841abd57.png)
![Screen Shot 2020-09-07 at 8 04 28 AM](https://user-images.githubusercontent.com/46171897/92385962-d54aa180-f0e0-11ea-9635-a49da779c1dc.png)

**Comment by bgambocjaviniar** [comment]
@morganm58 

re-opening because mobile wasn't done

when in `tablet` and in `mobile` view. 

For example provided screenshot below

when `tablet` -ish, the width of the dropdown for every 'number' and 'string' (days/weeks/months)
![Screen Shot 2020-09-14 at 1 09 21 AM](https://user-images.githubusercontent.com/29099466/93046157-239ef980-f627-11ea-87f2-b100f04b4844.png)

when `mobile`, the weeks view looks off
![Screen Shot 2020-09-14 at 1 09 31 AM](https://user-images.githubusercontent.com/29099466/93046267-64970e00-f627-11ea-9583-6bbb228c25fc.png)

**Comment by morganm58** [comment]
Added some styling changes to the mobile view on small screens. The changes were approved by Jeanne and Manu.
The dates are now stacked in the mobile view and the labels for the inputs are now above the inputs at all screen sizes.
<img width="442" alt="Screen Shot 2020-09-17 at 10 34 38 AM" src="https://user-images.githubusercontent.com/2947470/93491029-36d7f080-f8d7-11ea-8c80-fe91ef31a353.png">

**Comment by bgambocjaviniar** [comment]
picture above looks fine

however, I am wondering if it is supposed to look like the following (mobile/tablet view, a bit noticeable in desktop)
![Screen Shot 2020-09-17 at 5 04 49 PM](https://user-images.githubusercontent.com/29099466/93528863-01e49180-f909-11ea-9b0e-1024f9fa1d5d.png)
![Screen Shot 2020-09-17 at 5 04 55 PM](https://user-images.githubusercontent.com/29099466/93528864-027d2800-f909-11ea-804e-602b17e2c6a7.png)

I noticed this new styling makes it look like it's aligning left of the container and having the empty spaces at the right

**It's fine as long everyone is fine with it**

![Screen Shot 2020-09-17 at 5 21 36 PM](https://user-images.githubusercontent.com/29099466/93529682-54727d80-f90a-11ea-9d4c-519cb6798b4e.png)

![Screen Shot 2020-09-17 at 5 51 40 PM](https://user-images.githubusercontent.com/29099466/93532187-81c12a80-f90e-11ea-887a-fd51427ae2cf.png)
