### ISSUE TITLE
Add unit tests for organization ngrx reducers

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8646]
`b2b-user.reducer.ts` and its neighbour files from the the `/reducers` folder don't have unit tests yet.

blocked by https://github.com/SAP/spartacus/pull/8458

TODO LIST:
- [x] `b2b-user.reducer.ts`
- [x] `budget.reducer.ts`
- [x] `cost-center.reducer.ts`
- [x] `order-approval.reducer.ts`
- [x] `org-unit.reducer.ts`
- [x] `permission.reducer.ts`
- [x] `user-group.reducer.ts`

**Comment by kacperknapik** [comment]
We could probably think about renaming these reducers, and maybe come up with a unified names, eg. `b2b-budget`, `b2b-cost-center`
