### ISSUE TITLE
Rename http params CustomEncoder and expose in public API

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8658]
1. rename `CustomEncoder` class to `HttpParamsURIEncoder` (and analogicaly the file name too)
2. move it to `projects/core/src/utils`
3. export this util in public API

Reason to rename: to have more meaningful name
Reason to expose: I expect sooner or later it will be useful in some granular feature lib or for some customer

**Comment by wangzixi-diablo** [comment]
* original name: CustomEncoder
* original class file path: projects\core\src\occ\adapters\cart\custom.encoder.ts: 
* new name: HttpParamsURIEncoder
* new proposed file name & path: projects\core\src\utils\http-params-uri.encoder.ts

Two references before change:

* projects\core\src\occ\adapters\checkout\occ-checkout-payment.adapter.ts
* projects\core\src\occ\services\occ-endpoints.service.ts

* in file \projects\core\src\util\index.ts:

append one line to file end:

export * from './http-params-uri.encoder.ts'

* replace all references which uses the old name "CustomEncoder" with name "HttpParamsURIEncoder"
