### ISSUE TITLE
[MASTER] B2B Reorder feature

### ISSUE THREAD

**Issue by qjimmy** [SAP/spartacus#8674]
# B2B Reorder

[Wiki page with all details here](https://cxwiki.sap.com/pages/viewpage.action?spaceKey=spar&title=Feature%3A+B2B+Reorder)

## To do

- [ ] Implement the facades (+ unit tests)
- [ ] Implement the button that reorders (+unit tests)
- [ ] e2e maybe, if applicable

**Comment by bgambocjaviniar** [comment]
closing because owner of issue is done with their internship and has no work done for it
Someone else will work on the feature
