### ISSUE TITLE
Upgrade Cypress to 5.0 and Enable Failure Retries (3x)

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8679]
Cypress has recently announced that version 5.0 has been released (Aug 19). 
This version includes test failure retries. 

Please upgrade our Cypress version to 5.0 and enable failure retries in pipeline. 
Suggestion: retry 3 times after test failure. 

Yes, I understand this may slow down e2e regression or smoke run. In conjunction, we could enable parallelism if not already done.

**Comment by giancorderoortiz** [comment]
See https://www.cypress.io/blog/2020/08/19/introducing-test-retries-in-cypress-5-0/

**Comment by giancorderoortiz** [comment]
See also https://docs.cypress.io/guides/guides/test-retries.html#Introduction

**Comment by giancorderoortiz** [comment]
Implement parallelization if needed https://github.com/SAP/spartacus/issues/8700

**Comment by Xymmer** [comment]
reopened by mistake, need new tickets for new issues
