### ISSUE TITLE
Set styles version with schematics

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8680]
Starting with spartacus 2.1 schematics apart from including spartacus styles in app scss file should also set the `$styleVersion` version to the current spartacus version.

End result for @spartacus/schematics 2.1:

``` scss
$styleVersion: 2.1;
@import '@spartacus/styles';
```

**Comment by psmul** [comment]
Also within this issue migration will be provided. We need to ensure that this change got applied for all customers with versions below current state/fix.
