### ISSUE TITLE
Page styles not applied to <2.1 versions.

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8681]
Applies to spartacus 2.1 releases.

When you have feature level set to version `< 2.1` and style version also set to version `< 2.1` the page styles are not applied. You generally see something like the mobile view on all viewports. 

![image](https://user-images.githubusercontent.com/6259079/90758100-ca210480-e2de-11ea-9944-f415bd4e25c6.png)

**Comment by tobi-or-not-tobi** [comment]
QA steps:
- remove `$useLatestStyles: true;` or `$styleVersion` from `styles.scss`
- use feature level `2.0`
- verify that the page layout works as usual.
