### ISSUE TITLE
Run Cypress E2E Smoke And Regression Tests in Parallel

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8700]
New azure infrastructure allows the deployment of more reliable, dependable VMs. 

In order to detect failures faster, we could parallelize the execution of e2e tests. 
Instead of running in only one VM. 

See guide here: 
https://docs.cypress.io/guides/guides/parallelization.html#Overview

**Comment by Xymmer** [comment]
duplicate
