### ISSUE TITLE
Implement implicit auth flow with the new AuthModule and configuration.

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8738]
Implement implicit auth flow with the new AuthModule and configuration.

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- validate if implicit flow works (login, test common user path, logout) with new auth module and OAuth server (add implicit for OAuth client in backoffice and configure redirect url to match the app url).

Configuration needed in app:
```
authentication: {
        client_id: 'client4kyma',
        client_secret: 'secret',
        OAuthLibConfig: {
          responseType: 'token',
        },
      },
```
