### ISSUE TITLE
header's click listner collapseMenuIfClickOutside should check event.currentTarget

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#8763]
**Describe the bug**
header's click listner collapseMenuIfClickOutside throw error if clicked by svg

**To Reproduce**
1. I have SVG icon in `<cx-icon class="search fas fa-search">` in <header>
2. Click by the icon
3. See error `TypeError: e.target.className.includes is not a function`

**Expected behavior**
I expected in click handler `collapseMenuIfClickOutside` `event.currentTarget.className.includes('is-expanded')` instead of `event.target`

**Screenshots**
![image](https://user-images.githubusercontent.com/17045072/91642804-f5ba9200-ea36-11ea-8c91-e3421afc7c73.png)
![image](https://user-images.githubusercontent.com/17045072/91642809-02d78100-ea37-11ea-998b-1372053dc5c9.png)

**Additional context**
I see the problem in any devices

**QA steps**

1. In search-box.component.html, replace search cx-icon (around line 27) with the SVG element below.
(copy the following div tag and replace with the cx-icon)

```
<div
    aria-label="search"
    (mousedown)="avoidReopen($event)"
    (keydown.enter)="avoidReopen($event)"
    tabindex="0"
  >
    <svg height="100" width="100">
      <circle
        cx="50"
        cy="50"
        r="40"
        stroke="black"
        stroke-width="3"
        fill="red"
      />
    </svg>
</div>`
```

2. Run the application and click the SVG (red circle), to open the search textbox.

3. Click outside of it, to collapse the menu.

4. Click on the hamburger menu to ensure it opens and collapses.

5. Check dev tool console log, to ensure the TypeError is not thrown.

**Comment by alvteren** [comment]
Resolve problem to #8673

**Comment by hackergil** [comment]
This fix was reverted since:
* It does not work on mobile (breaks hamburger menu)
* Does not have unit tests
* Makes corresponding e2e test fail.

**Comment by ren-tham** [comment]
PR: #9154 

Recap of problem: collapseMenuIfClickOutside would throw an exception when mouseEvent passed by SVGElement.

QA - steps

1. In search-box.component.html, replace search cx-icon (around line 27) with the SVG element below. 

(copy the following div tag and replace with the cx-icon)

```
<div
    aria-label="search"
    (mousedown)="avoidReopen($event)"
    (keydown.enter)="avoidReopen($event)"
    tabindex="0"
  >
    <svg height="100" width="100">
      <circle
        cx="50"
        cy="50"
        r="40"
        stroke="black"
        stroke-width="3"
        fill="red"
      />
    </svg>
</div>`
```

2. Click SVG (red circle), to open the search textbox.

3. Click outside of it, to collapse the menu. 

4. Click on the hamburger menu to ensure it opens and collapses.

5. Check dev tool console log, to ensure the TypeError was not thrown.

**Comment by Parthlakhani** [comment]
Tested on local, It works as expected.
