### ISSUE TITLE
Update the way cards are displayed when selected

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#8782]
Update the way the cards look. Changes to be done (view screenshots):

-  The default text is at the bottom at the bottom
-  When a card is selected is is reflected in the border-color
-  Name is bold
- Text a bit lighter
- Zip is now in one line

**Ignore the blue color**

### Before:
<img width="738" alt="Screen Shot 2020-08-31 at 2 22 08 PM" src="https://user-images.githubusercontent.com/10605724/91876697-03e0fc00-ec4b-11ea-9285-150f18fd9da0.png">

### After:

![Screen Shot 2020-08-31 at 2 22 19 PM](https://user-images.githubusercontent.com/10605724/91876878-3ee32f80-ec4b-11ea-90a6-bd5e412d7517.png)

**Note:** This is a breaking change.

**Comment by cmanciero** [comment]
Is there any styling information available for this change? Font size, blue color value, etc.

**Comment by cmanciero** [comment]
Does clicking the address tile fire the selection of the address to ship to?

**Comment by bit172** [comment]
@Xymmer Are there any details for these changes?

**Comment by Xymmer** [comment]
closing as this ticket is now in jira, https://jira.tools.sap/browse/CXSPA-352
