### ISSUE TITLE
Launching start Spartacus problem

### ISSUE THREAD

**Issue by ChristopherBi** [SAP/spartacus#8783]
**Describe the bug**
When i start the command: ./install.sh -r b2c_for_spartacus -A local_property:initialpassword.admin=******** start

The console shows the following error: IndexerException: Failed to index item with PK 8796095938561: No bean named 'customerCouponCodeValueResolver' available

I saw the issue is already been reported but following the procedure in response (removing solr.impex and solr_en.impex files) the error persists.

how can i fix it?

Thank you in advance

**Comment by Xymmer** [comment]
@christopherBi, this isn't Spartacus but backend SAP Commerce, could you contact SAP Commerce support?
