### ISSUE TITLE
SSR is incompatible with automatic multi-site configuration

### ISSUE THREAD

**Issue by guiliguili** [SAP/spartacus#8788]
**Describe the bug**
SSR is broken with [automatic multi-site configuration](https://sap.github.io/spartacus-docs/automatic-context-configuration/) with Spartacus 2.0.8 and SAP Commerce 2005.

**To Reproduce**
1. Follow installation steps described in [Installing SAP Commerce Cloud 2005 for use with Spartacus](https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2005/) and [Building the Spartacus Storefront using 2.x Libraries](https://sap.github.io/spartacus-docs/building-the-spartacus-storefront-from-libraries/).
2. Remove static site configuration by removing the `baseSite` configuration element in `app.module.ts`
3. Edit your `/etc/hosts/` to add the following line : `127.0.0.1	electronics-spa.local`
3. Build SSR using `yarn build:ssr`
4. Run SSR using `yarn serve:ssr`
5. Open browser and go to http://electronics-spa.local:4000/

**Expected behavior**
The electronics site homepage is displayed in browser.

**Actual behavior**
An Internal Server Error message is displayed in browser (c.f. screenshot) and error stack trace is output in the server log (c.f. attached log)

**Screenshots**
<img width="487" alt="image" src="https://user-images.githubusercontent.com/3276366/91954407-0eaa9800-ed02-11ea-9730-f29c3dfe0dd3.png">

**Logs**
[ssr-server-error.log](https://github.com/SAP/spartacus/files/5160841/ssr-server-error.log)

**Desktop**
 - OS: macOS 10.15.6
 - Browser : chrome 
 - Version 84.0.4147.135 (Official Build) (64-bit)

**Additional context**
http://electronics-spa.local:4000/ does not raise any error with CSR.

With [static multi-site configuration](https://sap.github.io/spartacus-docs/static-context-configuration/), SSR does work.

**Comment by Platonn** [comment]
As discussed offline, the problem was a missing valid SSL certificate on the local development server. We need to document how to mitigate it, by setting `NODE_TLS_REJECT_UNAUTHORIZED=0`.

Clarification: SSR with static multi site partially worked (it didn't throw errors in server console, but displayed a blank page in the browser when JS was disabled). With enabled JS in the browser, the JS Spartacus kicked in and showed a page (but the initial SSR rendered page was blank anyway).

**Comment by timothy2005** [comment]
Add below config to **package.json**

```
"scripts": {
    "dev:ssr": "cross-env NODE_TLS_REJECT_UNAUTHORIZED=0 ng run mystore:serve-ssr",
},
[...]
"devDependencies": {
    [...]
    "cross-env": "^7.0.0"
}
```

Then run following to start Spartacus

`yarn dev:ssr`
