### ISSUE TITLE
[ON HOLD] B2B homepage /organization can be accessed even by unathorized users. Should be only available to Admins

### ISSUE THREAD

**Issue by psmul** [SAP/spartacus#8801]

**Comment by psmul** [comment]
Solution might not be that simple here, because we would need to apply roles restrictions, which is not available for now. After talks with @tobi-or-not-tobi there are alternative propositions:
- providing alternative content / component for unauthorized users on /organization route
- adding RequiresLogin component to the page, that will be shown only to unathorized users

Might need some agreements on approach for this one with @Xymmer

**Comment by tobi-or-not-tobi** [comment]
we're limited here with an out of the box solution as:
- the CMS backend API doesn't take CMS page restrictions into account; we would like the OCC CMS api to returns a proper http status based on these restrictions (see https://cxjira.sap.com/browse/CMSX-8491)
- this is a generic content page which we don't like to make special with a hardcoded route and guards, we render it as any content page. 
- the components on the page are generic components and cannot be restricted

Ideally this is implemented with the CMS backend. Alternative ideas:
- introduce cms component restrictions to the banners, and add a paragraph describing admin permissions are required
- leave it as-is; the user would not be able to access the data, and after navigating to the underlying pages, it will be restricted by the AdminGuard

**Comment by kacperknapik** [comment]
Should this be a part of MVP? Ask Bill

**Comment by Pucek9** [comment]
Close for not making duplication
