### ISSUE TITLE
SonarC. Reliability Rating. Use forEach Instead of Map

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8823]
This issue affects our overall Reliability Rating in Sonar Cloud. 
Visible to CX. 

**Reliability Rating:** 
C

**Link**
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&view=list

**Files:** 
1. projects/core/src/occ/services/occ-fields.service.ts
2. feature-libs/my-account/src/test.ts
3. feature-libs/product/test.ts
4. integration-libs/cdc/src/test.ts

**Issue:** 
Consider using "forEach" instead of "map" as its return value is not being used here.

**Explanation:** 
When the call to a function doesn't have any side effects, what is the point of making the call if the results are ignored? In such case, either the function call is useless and should be dropped or the source code doesn't behave as expected.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 6 18 05 AM](https://user-images.githubusercontent.com/46171897/92377453-2b641880-f0d2-11ea-97b5-ca19e8257699.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 6 29 22 AM](https://user-images.githubusercontent.com/46171897/92378297-96621f00-f0d3-11ea-9c15-97abd13c3af6.png)
![Screen Shot 2020-09-07 at 6 29 37 AM](https://user-images.githubusercontent.com/46171897/92378298-96fab580-f0d3-11ea-915a-9a6ceebc1345.png)
![Screen Shot 2020-09-07 at 6 29 53 AM](https://user-images.githubusercontent.com/46171897/92378301-96fab580-f0d3-11ea-8fa5-468ed73623f3.png)

**Comment by giancorderoortiz** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fcore%2Fsrc%2Focc%2Fservices%2Focc-fields.service.ts

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Fmy-account%2Fsrc%2Ftest.ts

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aintegration-libs%2Fcdc%2Fsrc%2Ftest.ts

**Comment by giancorderoortiz** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Fproduct%2Ftest.ts

**Comment by Xymmer** [comment]
Fix ...projectscoresrcoccservicesocc-fields.service.ts (change from map to for-each)
Set other files to be ignored in sonarscans (talk to Gil how to do this).

**Comment by Parthlakhani** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_reliability_rating&pullRequest=9833&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fcore%2Fsrc%2Focc%2Fservices%2Focc-fields.service.ts

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_reliability_rating&pullRequest=9833&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Forganization%2Ftest.ts

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_reliability_rating&pullRequest=9833&selected=sap_cloud-commerce-spartacus-storefront%3Afeature-libs%2Fproduct%2Ftest.ts

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_reliability_rating&pullRequest=9833&selected=sap_cloud-commerce-spartacus-storefront%3Aintegration-libs%2Fcdc%2Fsrc%2Ftest.ts

<img width="1675" alt="Screen Shot 2020-11-17 at 4 27 58 PM" src="https://user-images.githubusercontent.com/72991814/99452682-df172f00-28f1-11eb-9b6a-ac0815376f8d.png">

**Comment by Parthlakhani** [comment]
Talked to @hackergil about setting files to ignore in sonarscans, he suggested that changes should be made as suggested by sonar.

**Comment by giancorderoortiz** [comment]
Eager to see this fixed.

**Comment by giancorderoortiz** [comment]
Issue fixed. Thanks. 
![Screen Shot 2020-12-07 at 7 42 50 AM](https://user-images.githubusercontent.com/46171897/101352266-dade9180-385f-11eb-8cbf-77036778d66a.png)

**Comment by apurvageete** [comment]
@giancorderoortiz  can u please paste the screenshot for this issue again .. I cannot see the last line in this screen shot

**Comment by shobha-source** [comment]
Can you please any one help here consider using foreach instead of map as it's return value is not being used here.
