### ISSUE TITLE
[solution possible?] SonarC. Reliability Rating. Add 'Alt' Attribute to Image

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8824]
This issue affects our overall Reliability Rating in Sonar Cloud.
Visible to CX.

**Reliability Rating:**
B

**Link**
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&view=list

**Files:**
1. projects/storefrontlib/src/shared/components/media/media.component.html
2. projects/storefrontlib/src/cms-components/product/product-variants/variant-style-icons/variant-style-icons.component.html

**Issue:**
Add an "alt" attribute to this image

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 6 39 45 AM](https://user-images.githubusercontent.com/46171897/92379165-01602580-f0d5-11ea-9826-44f6caff13ac.png)
![Screen Shot 2020-09-07 at 6 39 57 AM](https://user-images.githubusercontent.com/46171897/92379168-01f8bc00-f0d5-11ea-9b9b-4f568879b21e.png)

**Comment by giancorderoortiz** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fstorefrontlib%2Fsrc%2Fshared%2Fcomponents%2Fmedia%2Fmedia.component.html

https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fstorefrontlib%2Fsrc%2Fcms-components%2Fproduct%2Fproduct-variants%2Fvariant-style-icons%2Fvariant-style-icons.component.html

**Comment by dunqan** [comment]
False positive, as we are setting alt in those examples

**Comment by Xymmer** [comment]
False positive. Can we turn this off in sonar?

**Comment by giancorderoortiz** [comment]
Please provide a more detailed explanation if considered a false positive. 
Would like to discuss internally to turn off this rule and need a good argument :-)

**Comment by giancorderoortiz** [comment]
Issue no longer present. Closing.
