### ISSUE TITLE
SonarC. Reliability Rating. Variable Usage

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8825]
This issue affects our overall Reliability Rating in Sonar Cloud.
Visible to CX.

**Reliability Rating:**
B

**Link**
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&view=list

**Files:**
projects/core/src/occ/adapters/user/converters/anonymous-consents-normalizer.ts

**Issue:**
Introduce a new variable or use its initial value before reassigning "target".

**Comment:** 
While it is technically correct to assign to parameters from within function bodies, it reduces code readability because developers won't be able to tell whether the original parameter or some temporary variable is being accessed without going through the whole function. Moreover, some developers might also expect assignments of function parameters to be visible to callers, which is not the case, and this lack of visibility could confuse them. Instead, all parameters, caught exceptions, and foreach parameters should be treated as constants.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 6 44 55 AM](https://user-images.githubusercontent.com/46171897/92379554-a975ee80-f0d5-11ea-8534-599e02132d5b.png)

**Comment by giancorderoortiz** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=reliability_rating&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fcore%2Fsrc%2Focc%2Fadapters%2Fuser%2Fconverters%2Fanonymous-consents-normalizer.ts

**Comment by Xymmer** [comment]
Good improvement, let's fix

**Comment by Parthlakhani** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=new_reliability_rating&pullRequest=9919&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects%2Fcore%2Fsrc%2Focc%2Fadapters%2Fuser%2Fconverters%2Fanonymous-consents-normalizer.ts

<img width="1592" alt="Screen Shot 2020-11-18 at 4 26 57 PM" src="https://user-images.githubusercontent.com/72991814/99590086-e35b4f00-29ba-11eb-8150-d77100bffaf8.png">

**Comment by giancorderoortiz** [comment]
ok. Thanks.
