### ISSUE TITLE
Missing Test Coverage of Schematics in SonarCloud

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8828]
No test coverage seen in Sonarcloud for Schematics. 

Is it an error in configuration or actual coverage is missing? 

See: https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=line_coverage&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects&view=treemap

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 7 28 51 AM](https://user-images.githubusercontent.com/46171897/92383861-0d4fe580-f0dd-11ea-9543-efd25fbbbc96.png)

**Comment by giancorderoortiz** [comment]
https://sonarcloud.io/component_measures?id=sap_cloud-commerce-spartacus-storefront&metric=coverage&selected=sap_cloud-commerce-spartacus-storefront%3Aprojects

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-07 at 7 38 42 AM](https://user-images.githubusercontent.com/46171897/92383921-2fe1fe80-f0dd-11ea-9fa6-43eb835dbcbe.png)

**Comment by Xymmer** [comment]
Tests are in schematics, we don't have config to run them.
Need to add config.
