### ISSUE TITLE
Display feature unit in product spec if it is absent

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#8845]
In product details page -> spec tab, we can see that feature values are displayed without feature unit.
For example:
![Screen Shot 2020-09-08 at 3 25 18 PM](https://user-images.githubusercontent.com/44440575/92519270-a834e680-f1e7-11ea-9aad-a23181cc2b19.png)
Rear camera resolution (numeric) is: `3.15 MP`. We only can see `3.15`. It is better to display the unit
![Screen Shot 2020-09-08 at 3 20 48 PM](https://user-images.githubusercontent.com/44440575/92519393-e29e8380-f1e7-11ea-97e1-79fd25cc7c1b.png)

**Comment by ren-tham** [comment]
PR: (#9463 )
Solution proposed, for now I only display the unit symbols. Please send back the ticket if more information is required.

Before: 

<img width="340" alt="Before" src="https://user-images.githubusercontent.com/71661414/96751250-f1598800-139a-11eb-87b8-42a9d3cd3a29.PNG">

After: 

<img width="395" alt="After" src="https://user-images.githubusercontent.com/71661414/96751275-fa4a5980-139a-11eb-9bc1-fd016a2c70cd.PNG">

**Comment by giancorderoortiz** [comment]
Still visible in http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/product/553637/NV10

**Comment by LTiger14** [comment]
@giancorderoortiz when was this server deployed and what branch? The PR is not merged yet.

**Comment by giancorderoortiz** [comment]
Last Monday afternoon

**Comment by Parthlakhani** [comment]
Tested on local while pointing to DEV-0 backend, works as expected.
