### ISSUE TITLE
Translation key missing 'storeFinder.clickBack'

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#8856]
**Describe the bug**

**To Reproduce**
1. Go http://localhost:4200/powertools-spa/en/USD/store-finder/country/US/Hybris%20Powertools%20El%20Cajon
2. Open the console
3. See the warning: _Translation key missing 'storeFinder.clickBack' in the chunk 'storeFinder._

**Expected behavior**
No warning. Text is properly translated.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/4001059/92616036-0cc27500-f2be-11ea-86db-497ef643d18a.png)

**Additional context**
We need to add this missing key to translation assets.

**Comment by ren-tham** [comment]
Hi, it looks like this problem doesn't exist on develop. The button is being rendered properly when I tried running it. There may be an issue with the key you are referencing. Develop uses 'backToList' key instead of 'ClickBack'.

**Comment by Platonn** [comment]
Hey. You're right. I've observed this issue on MyOrg epic branch and I assumed it's originated from develop. My bad. Closing.

Btw. It's strange MyOrg branch contains changes with the store finder's translations... 🤔
