### ISSUE TITLE
Direct Access to MyCompany Components by Non-Admin Users Must Redirect to Login Page

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8866]
**Steps to Reproduce:**

1. As an anonymous user navigate directly to b2b storefront my company units page. 
1.a URL: http://spartacus-dev4.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/units

2. Login as a non-admin user.
2.a. (i.e. mark.rivers from sample data)
3. Navigate directly to b2b storefront my company units page.

**Expected Results:** 
1. An error message or warning is shown indicating user doesn't have access to this page, or login is needed first. 
1.a. User is redirected to login page. 👎 
3. Similar to step 1. 

**Actual Results:** 
1. Error/warning message shown as expected. 
1.a. User is redirected to organization page. 👎 
3. Non-admin user should be redirected to homepage

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-10 at 6 16 59 AM](https://user-images.githubusercontent.com/46171897/92717581-6f535980-f32e-11ea-9c8c-9cbfdb7adaa6.png)

**Comment by giancorderoortiz** [comment]
Same principle applies to all others within mycompany: 
1. Budgets
1.a. http://spartacus-dev4.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/budgets
1.b. http://spartacus-dev4.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/budgets/Monthly_20K_USD

2. Cost Centers
3. Users
4. Purchase limits
5. User Groups

**Comment by kacperknapik** [comment]
Should this be a part of MVP? Ask Bill

**Comment by Xymmer** [comment]
giancarlo to double check: what happens if i'm:
- not an admin (or not logged in)
- i go directly to /costcenter/

**Comment by giancorderoortiz** [comment]
Retest with develop branch in qa server. 
(Server may be down when you click on links)

These direct access links redirect to login page with anonymous user:

http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/units/BURRITOSORGGLOBAL0001

http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/cost-centers/Rustic_Global

http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/budgets/Monthly_50K_USD

http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/users/b38eb920-73e5-4567-97c6-5d9a8d8efd84

http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/organization/purchase-limits/Rustic_20K_USD_MONTH

Once user logs in, with a non-admin user, then this page is shown: 

![Screen Shot 2020-10-19 at 12 19 10 PM](https://user-images.githubusercontent.com/46171897/96478203-68f5ae80-1205-11eb-8035-11db31bbd7a1.png)

**Comment by giancorderoortiz** [comment]
When user is logged in as non-admin, and attempts to access direct links listed above, user is shown an empty MyCompany page with error "no sufficient permissions to access this page".

**Comment by giancorderoortiz** [comment]
For anonymous users, this issue is solved. 
For non-admin users, @Xymmer , @tobi-or-not-tobi should decide whether to redirect to homepage or organization page.

**Comment by Xymmer** [comment]
Closing. #8865 will be reverted. Assuming there is no security issue, the user is trying to hack his way in and for now we will let them see the org page.
