### ISSUE TITLE
My Account 404 for Quotes and Returns (sample data)

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8869]
Minor cosmetic issue. 
 404 not found page is being shown for b2b features not implemented yet. 

**Steps to Reproduce.** 
1. Navigate to B2B powertools spartacus storefront. 
1.a. (i.e. http://spartacus-dev3.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/)
2. Login as mark.rivers
3. From my account, navigate to quotes. 
4. From my account, navigate to returns. 

**Expected Results:** 
3. Empty blank body in page. 
4. Same as step 3. 

**Actual Results:** 
3. 404 not found page is shown. 
3. Same as step 3. 

Just would like to see consistency. Replenishments feature, currently under development, shows a blank page.

**Comment by giancorderoortiz** [comment]
Replenishments: 

![Screen Shot 2020-09-08 at 8 22 08 AM](https://user-images.githubusercontent.com/46171897/92724793-2ead0d80-f339-11ea-8d0b-36214b629799.png)

Quotes: 

![Screen Shot 2020-09-08 at 8 22 16 AM](https://user-images.githubusercontent.com/46171897/92724794-2ead0d80-f339-11ea-8fbc-cb9fc14070d1.png)

Returns:
![Screen Shot 2020-09-08 at 8 22 27 AM](https://user-images.githubusercontent.com/46171897/92724795-2f45a400-f339-11ea-9b9f-ebb6114c40ea.png)

**Comment by Xymmer** [comment]
Ensure that the returns and quotes links don't show up in sample data for b2b.
However there was a ticket where Wei removed all My Company links and kept one 'Home' link.

**Comment by kacperknapik** [comment]
Not a part of MyCo milestone. Moving to 3.0

**Comment by Xymmer** [comment]
make sure sample data going out for 3.0 doesn't include quotes and returns

**Comment by bgambocjaviniar** [comment]
Backend SAMPLE PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/144/files

**Comment by bgambocjaviniar** [comment]
QA: 
- re-initialize backend with latest `release/2005/next` branch
- verify in b2b storefront that quotes and returns are gone from my account dropdown

**Comment by giancorderoortiz** [comment]
Expensive testing.

**Comment by giancorderoortiz** [comment]
quotes and returned removed from myCompany menu

![Screen Shot 2020-11-15 at 3 33 50 PM](https://user-images.githubusercontent.com/46171897/99196080-1225bb00-2758-11eb-9be5-eaa3904f69ba.png)
