### ISSUE TITLE
B2B Checkout. Minor Misalignment in Shipping Address Step -> Cost Center Dropdown List

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8870]
**Steps to Reproduce.**

1. Navigate to B2B powertools spartacus storefront.
1.a. (i.e. http://spartacus-dev3.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/)
2. Login as mark.rivers
3. Add items to cart and checkout up to Shipping Address step. 
4. Select cost center

**Expected results**
4. Vertical and horizontal alignment of cost centre dropdown list. 

**Actual results**
4. A minor misalignment compared to other elements on screen
4.a. Chevron too close to edge.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-08 at 8 47 52 AM](https://user-images.githubusercontent.com/46171897/92725042-864b7900-f339-11ea-9481-6ca05d75d8aa.png)
![Screen Shot 2020-09-08 at 8 48 54 AM](https://user-images.githubusercontent.com/46171897/92725043-864b7900-f339-11ea-9b04-54a615065019.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-10 at 7 58 13 AM](https://user-images.githubusercontent.com/46171897/92726540-ba279e00-f33b-11ea-8229-896515939d6c.png)
![Screen Shot 2020-09-10 at 7 58 33 AM](https://user-images.githubusercontent.com/46171897/92726541-bac03480-f33b-11ea-8457-4c93ec133c64.png)

**Comment by bgambocjaviniar** [comment]
Might want to point out this is most likely for all 'html select' tag that we use in Spartacus. I believe it may be a global styling issue

**Comment by morganm58** [comment]
@bgambocjaviniar that is correct. @giancorderoortiz This is a global styling issue with selects.

**Comment by Xymmer** [comment]
won't fix for now then, closing
