### ISSUE TITLE
Remove not needed B2B stuff from `develop`

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8873]
With B2B Checkout we now have some of the B2B code that is not needed for the checkout.

**Comment by kacperknapik** [comment]
Does it need QA? If so, QA steps? @marlass

**Comment by marlass** [comment]
QA steps:
- Check if B2C and B2B checkout works correctly

**Comment by psmul** [comment]
QA steps done. Both B2B and B2C results in successful order checkout.
![image](https://user-images.githubusercontent.com/10993491/95314493-a7987a00-0891-11eb-9cd6-a7da7e576037.png)
![image](https://user-images.githubusercontent.com/10993491/95315158-6eacd500-0892-11eb-80c9-35eccaf4ef12.png)
