### ISSUE TITLE
Check if we could avoid ChangeDetectorRef in progress components

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#8879]
With the B2B Checkout progress components are now use the ChangeDetectorRef. Maybe we could use observables instead?

**Comment by LTiger14** [comment]
PR: #8998

**Comment by LTiger14** [comment]
For QA/Review:
- Go through B2B checkout on mobile and desktop. See that when changing payment method the number of steps changes. Make sure when moving from one step to the other the checkout progress looks good.
- Do the same for B2C (except the payment method)

**Comment by psmul** [comment]
QA done. Steps numbers change properly when switching payment methods.
