### ISSUE TITLE
console error when logging out from order confirmation page

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#8881]
**Note: this bug was verified on develop pre-b2bcheckout merge**

As shown in the screenshot below, you can see that it throws a console error when logging out from the order confirmation page.

**To Reproduce**
1. place an order 
2. get to the order confirmation page
3. logout, which shows console error in devtools 

**Expected behavior**
- should not throw any console error when logging out

**Screenshots**

![Screen Shot 2020-09-09 at 3 52 18 PM](https://user-images.githubusercontent.com/29099466/92755680-113c6b80-f35a-11ea-87e2-d8456745af8c.png)

**Comment by ren-tham** [comment]
PR: #9236 

Solution proposed. TypeError is no longer thrown.
