### ISSUE TITLE
Load Balancer for Spartacus CI 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#8895]
Deploy an azure load balancer to add stability, replication and 99%+ availability to dev0. 
Avoid blocking CI when dev0 is down. 

3 different VMs at least.

**Comment by giancorderoortiz** [comment]
Load balancer deployed. 
See details in server list page. 
e2e ran successfully against load balancer. Equivalent results obtained as with dev0. 
Should consider stop using dev0 now and use load balancer instead. @hackergil 

E2e against load balancer:  https://dashboard.cypress.io/projects/k3nmep/runs/3967
E2e against dev0 https://dashboard.cypress.io/projects/k3nmep/runs/3977

**Comment by giancorderoortiz** [comment]
related to: https://github.com/SAP/spartacus/issues/8960

**Comment by giancorderoortiz** [comment]
6 vms added. 
Details in wiki.

**Comment by psmul** [comment]
Hi @giancorderoortiz any way to test it? Some QA steps or source to log in to?

**Comment by giancorderoortiz** [comment]
Requires further discussion with @hackergil as to how to move forward and replacement strategy for dev0. 
Please hold for a few days.

**Comment by giancorderoortiz** [comment]
Decision made on Oct 16:
1. Update US load-balancer and VMs thereof with 2005.2 latest sample data. 
2. Once VMs are updated, switch backend used by CI from dev0 to US-load balancer. (need ticket). 
3. Dismantle European load-balancer. Repurpose VMs for generic feature development.

**Comment by giancorderoortiz** [comment]
US load balancer upgraded successfully.
