### ISSUE TITLE
Unneeded loading of checkout data

### ISSUE THREAD

**Issue by ChristophHi** [SAP/spartacus#8898]
**Describe the bug**
In case the checkout has been entered once, checkout data is loaded unnecessarily on every cart interaction.

**To Reproduce**
Run from develop. 
- Add a product to the cart
- Login
- Enter checkout
- Go back to cart
Now any cart interaction (addToCart on PDP, catalog, change quantity in cart, remove cart entry) leads to a call for checkout data (https://localhost:9002/occ/v2/electronics-spa/users/current/carts/0000019000?fields=deliveryAddress(FULL),deliveryMode,paymentInfo(FULL)&lang=en&curr=USD). Cart details are loaded in addition.

**Expected behavior**
Checkout details should not be loaded if not needed. 

**Additional context**
This is a performance issue on its own, but also because synchronization of cart accesses gets even more complex, as multiple parallel cart requests lead to 400'er exceptions, caused by promotions.
When e.g. a cart entry configuration is read, this call needs to be delayed until the cart is ready _and_ until checkout details have been loaded.

The checkout calls are triggered through observable getCheckoutDetailsLoaded$ in checkout-details.service.ts

**Comment by Platonn** [comment]
Looks fishy, it seem to be a long living subscription. It doesn't have to cause memory leak in SSR (if the subscription depends only on ngrx state), but it migth be the case. Definitely needs investigation,

**Comment by Xymmer** [comment]
Although variant config team can work around this, we feel strongly we should fix this soon. Marking as 3.0.

**Comment by giancorderoortiz** [comment]
Issue fixed. 
Calls made upon quantity change: 
![Screen Shot 2021-05-18 at 6 58 32 AM](https://user-images.githubusercontent.com/46171897/118640068-90662700-b7a6-11eb-9ed0-c3c39ba37f9f.png)

**Comment by giancorderoortiz** [comment]
See additional improvements done here: https://github.com/SAP/spartacus/issues/10379
