### ISSUE TITLE
Migrate regressions suites out of Jenkins

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#8902]
Regression suites are still running on Jenkins. We need to find an alternative for this since our Jenkins will be decommissioned soon.

**Comment by mirkosoft** [comment]
@hackergil in the PR regressions are added as a third suite. However it runs more than 50 mins and there is a time limit for a job in travis for public repos:
https://docs.travis-ci.com/user/customizing-the-build/#build-timeouts

Afaik we have 2 options: go to paid plan (not an option probably) and divide regressions to a smaller chunks (which may be good anyways). @marlass mentioned parallelization ~but not sure what's this about~ - what stops us from implementing it? Lack of machines?

**Comment by hackergil** [comment]
Once we can run all e2e tests in parallel, regression suites won't be required anymore

**Comment by hackergil** [comment]
Cypress Parallelization is running. Closing this one.
