### ISSUE TITLE
[retest after feature/GH-8704-nextgen merged] Country region is not shown in edit form for unit addresses

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8906]
When you open the unit address edit form, you won't see the region for the given country. Only if the country is changed inside  the edit form, the state might show up (depends on country).

**Comment by tobi-or-not-tobi** [comment]
fixed in `feature/GH-8704-nextgen`

**Comment by kacperknapik** [comment]
Already done

**Comment by Pucek9** [comment]
Issue solved. Found new one: #9396
