### ISSUE TITLE
Address data is not refreshed after saving + looped unit data calls after address update

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8908]
After updating an existing unit address, the address details are not refreshed in the address details as well as in the list.

**Comment by Xymmer** [comment]
This is likely fixed by effort by Patryk for invalidating org data, check with him first. @psmul is there a ticket for that?

**Comment by kacperknapik** [comment]
@psmul retest this please

**Comment by psmul** [comment]
QA steps:
- go to any units address
- open dev tools
- edit any field & save

Expected result:
- After save action, view should be back on address details
- In dev tools, Network tab, no looped requests for unit entity are present
