### ISSUE TITLE
Improve styling for the Replenishment Order history page

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#8935]
master ticket: GH-8202

Improve styling for the Replenishment Order history page. Column widths need to be adjusted to accommodate the data/labels. 

- Wires: https://fi0yed.axshare.com/#id=lcud9d&p=d_page_replenish_orders&g=1
- environment config settting 
  - `occBaseUrl: https://spartacus-dev4.eastus.cloudapp.azure.com:9002'`
  - `b2b: true,`
- branch: `feature/8577`

current display:
![Screen Shot 2020-09-16 at 12 58 58 PM](https://user-images.githubusercontent.com/15215400/93375512-e05aab80-f81d-11ea-9486-f9293d3884ae.png)

**Comment by bgambocjaviniar** [comment]
closing as this was done directly on the branch GH-8577
