### ISSUE TITLE
Update sample data release tools

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#8936]
The backend extension `spartacussampledataaddon` its now called `spartacussampledata`
It is not an addon anymore.

This change is only for 2005+ and the 1905 sample data is still `spartacussampledataaddon`

So here are the changes required for the release tooling:

1) The repo url changed to: https://github.tools.sap/cx-commerce/spartacussampledata

2) The name of the zip released for 2005 needs to change and the one for 1905 needs to stay the same.

So currently, the files we release look like:

<img width="1128" alt="Screen Shot 2020-09-16 at 3 38 22 PM" src="https://user-images.githubusercontent.com/7065346/93384918-7220e380-f833-11ea-946c-4e472c03308d.png">

We need to update the 2005 version so the release looks like:

<img width="1115" alt="Screen Shot 2020-09-16 at 3 39 11 PM" src="https://user-images.githubusercontent.com/7065346/93384985-8bc22b00-f833-11ea-9d58-54b0b9a68a6e.png">

**Comment by psmul** [comment]
QA done, script work as intended.
