### ISSUE TITLE
[bill check] Places where we must disable editing due to disabled parent unit

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#8941]
For My Company, if something is disbled, or its parent unit is disabled, we don't allow editing. A few attributes are not yet blocked; we'll list them here and disable editing for them.

**Comment by Xymmer** [comment]
bill to check with michal/tobias if this was already done

**Comment by mikeharington812** [comment]
If a parent unit is disabled, preventing edits to related records helps avoid inconsistencies and unexpected changes. Identifying the remaining editable attributes and blocking them as well should make the behavior more predictable for users. Just like a reliable [Bill Check Online](https://onlinebillgepco.pk/) system, consistency and clear restrictions help create a smoother user experience.
