### ISSUE TITLE
[Fixed in #8231] Error in OccProductSearchPageNormalizer when there is no facet

### ISSUE THREAD

**Issue by ghost** [SAP/spartacus#8956]
**Describe the bug**
Spartacus 2.x
Undefined error happens in `OccProductSearchPageNormalizer` when there is no facet

**To Reproduce**
1. Create a category or search keyword that would result in OCC returning empty facet `productSearchPage.facets = []`
2. Go to that category's PLP or search page
3. Page is not displayed

**Expected behavior**
No error and page is displayed

**Additional context**
In `OccProductSearchPageNormalizer`, there is a null check for `target.facets` in `normalizeFacetValues` but not in `normalizeUselessFacets`.

**Comment by Xymmer** [comment]
fix in 3.0 and backport to 2.1

**Comment by LTiger14** [comment]
Fixed in #8231
