### ISSUE TITLE
Explicit cart validation on checkout [from sept 2020]

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8962]
With commerce 2011, we're getting a new API to invalidate the cart (`/{cartId}/validate`). Validating the cart before checkout is best practice since other activities might have cause a change on the cart or any related items. Therefor, cart validation before checkout should be the default behaviour. 

Customers who do need cart validation before checkout could benefit from not using this standard. To that reason, it would be a nice to have to use a configuration flag to turn it off. 

We must only use this validation when the API supports this. < 2011 there will be no support for this API.

**Comment by Xymmer** [comment]
1. explore what the api offers
2. create wiki with behavior we can implement, talk to bill
3. Verify with tobias

**Comment by WeizhengSap** [comment]
This new API is not done yet. So, have to wait it merged.

**Comment by Platonn** [comment]
Things to consider in UX:
- the the button [Proceed to checkout] appears not only on the cart page, but can appear also in the "Added to cart" modal or in custom places in customers code
- user can enter any checkout step page via a deep link

So in the implementation it would be good to implement a guard for every checkout page (or one main checkout orchestrator?), to redirect to the cart page in case of invalid cart.

**Comment by psmul** [comment]
All sugestion will be taken into account while implementing cart validation. For progress please follow board:
https://github.com/SAP/spartacus/projects/135#card-58698035
