### ISSUE TITLE
Add unit tests for schematics new workspace-utils methods

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8964]
Angular cli 10 has dropped some function Spartacus used in schematics. They has been moved to our code base but more unit test are needed:
https://github.com/SAP/spartacus/pull/8820/files?file-filters%5B%5D=.ts#diff-295dce7c1970d35050a70d2cd00ad966R101

Related to: #8930

**Comment by Xymmer** [comment]
quality improvement
