### ISSUE TITLE
Remove EntryComponents from spartacus code

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#8965]
As of Angular 9 they're not needed anymore, hence it's recommended to get rid of them:
https://update.angular.io/?l=3&v=9.0-10.0

Let's check the `NgModule`'s for usage and remove them.

https://angular.io/guide/deprecations#entryComponents

**Comment by Xymmer** [comment]
we didn't do this for 3.0, let's make sure to do this for 4.0
we weren't sure if this was a breaking change, but documentation says it shouldn't be

**Comment by bgambocjaviniar** [comment]
Since this is a breaking change and only can be done for 4.0, let's remove it from the board. @Parthlakhani

**Comment by dydome** [comment]
latest version https://github.com/SAP/spartacus/pull/12263
