### ISSUE TITLE
Auth guards introduce global warnings that cannot be closed

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8972]
The new auth guards for my company introduce a warning in case the item cannot be find or accessed. This warning cannot be closed manually by the user. This might be an issue with the global message component.

**Comment by tobi-or-not-tobi** [comment]
we can postpone this one if we pick up #8973

**Comment by Pucek9** [comment]
The issue is related to GlobalMessageType.MSG_TYPE_WARNING
