### ISSUE TITLE
Active state update on facade

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8976]
Most of the entities in my company can be disabled / enabled. While we have a method to patch the entity, there's not way to receive an update on wether the item was activated or deactivated. 

The UI has introduced a specific update for enabling/disabling the status, but it's done in an ugly way. We need to come up with precise updates instead.

**Comment by Xymmer** [comment]
Do this one first, talk strategy approach with Tobias.
Then we can do these 3 others:
- #8977
- #8999
- #8978
