### ISSUE TITLE
Distribute scss code in feature library

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8982]
With the creation of feature library, we've moved feature specific styling to the feature library. We have not yet finalised the distribution of the feature styles, which is why the styles do not end up in the package on npm. 

With this ticket we add the scss files including the entry index.scss file to the package.

**Comment by marlass** [comment]
**QA steps**

- build all libraries
- copy `dist/my-account` into `node_modules/@spartacus/my-account` to simulate downloaded package from npm
- change styles import in storefrontapp from `@import 'my-account';` to `@import '@spartacus/my-account';`
- test if the app builds correctly and if the styles are present in the application
