### ISSUE TITLE
Install feature lib css while installing feature library

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#8983]
After the feature CSS is added to the feature libraries (see #8982), we must automatically import it to the customer application. 

This should be done inside the feature schematics. There are various approaches to do this, but this would be ideal: 
1. generate a feature style file in the application
2. import the feature styles inside the generated file
3. link the generated file in the `angular.json`

This will allow for:
- further customising the feature styles in the generated file.
- lazy load the file in a future version

Lazy loading is not mandatory for this ticket.

**Comment by znikola** [comment]
The prerequisite is this ticket: https://github.com/SAP/spartacus/issues/9029
