### ISSUE TITLE
Fix infinite loop when loading consents

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#8987]
In cases when consents can't be loaded (due to various reasons: back-end misconfiguration,  network issues, etc.) Spartacus enters an infinite loop where it's re-retrying to load the consents.

**Comment by znikola** [comment]
# PR

#8989

# QA

To repro: in the back-end configuration, removing the `corsfilter.commercewebservices.exposedHeaders` property will trigger the infinite loop. This fix should prevent it, and print a warning message in the browser's console.

**Comment by psmul** [comment]
QA done. Working as intended. Console is throwing proper warning:
`anonymous-consents.effect.ts:45 No consents were loaded. Please check the Spartacus documentation as this could be a back-end configuration issue.`
