### ISSUE TITLE
Cleanup CheckoutConfigService

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#8996]
Most methods in `CheckoutConfigService` seem to have been duplicated in the `CheckoutStepService`. 

See if this class can be removed and remove it.

### Acceptance
- Remove duplicate code
- Add to deprecation

**Comment by hackergil** [comment]
Fixed as part of #8996

**Comment by LTiger14** [comment]
PR for both this and #8995 is #9024

**Comment by LTiger14** [comment]
QA Steps:

1. Go through B2B and B2C checkout happy path. Make sure you can checkout successfully.

**Comment by psmul** [comment]
QA steps done. Both B2B and B2C results in successful order checkout.
![image](https://user-images.githubusercontent.com/10993491/95314493-a7987a00-0891-11eb-9cd6-a7da7e576037.png)
![image](https://user-images.githubusercontent.com/10993491/95315158-6eacd500-0892-11eb-80c9-35eccaf4ef12.png)
