### ISSUE TITLE
[ON HOLD] Fix e2e regression/wish-list.e2e-spec.ts

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9006]
https://dashboard.cypress.io/projects/k3nmep/runs/4183/test-results?browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22regression%2Fwish-list.e2e-spec.ts%22%2C%22value%22%3A%22%5B%5C%222e491552-a9ed-426b-a462-93a96e940c86%5C%22%5D%22%7D%5D&statuses=%5B%5D

**Comment by LTiger14** [comment]
Test hasn't failed since it was reported so let hold on this.
