### ISSUE TITLE
Show errors on login attempt when CS agent is already logged in [merge to #9034]

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9010]
With changes to how user login interacts with CS agent login we need to prevent user login when CS agent is currently logged in. Then we should show error message. It should say something like `Cannot login as a normal user when there is CS agent session. Please either emulate user or logout CS agent.`

Look for `// TODO: Show the warning that you cannot login when you are already logged in` in code to find places where we have to add global message dispatch.

**Comment by kacperknapik** [comment]
Proposed solution:

![image](https://user-images.githubusercontent.com/22354613/95733892-0f303a00-0c83-11eb-8b0f-02793202152c.png)

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps identical as for #8484
