### ISSUE TITLE
Prepare CMS data for quick order [was in progress]

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#9013]
We need prepare the cms data for quick order, which may include: quick order link (navigation node) and CMS page.

**Comment by plabadie** [comment]
PR: https://github.tools.sap/cx-commerce/spartacussampledata/pull/132

To test: 
- Initialize with spartacussampledata
- Inspartacus, add to `b2c-layout-config.ts` and `b2bb-layout-config.ts` the TopContent slot positions to the `ContentPage1Template` template config like so:
```
    ContentPage1Template: {
      slots: ['Section2A', 'Section2B', 'TopContent'],
    },

```
- In all the storefronts you should see a drop down menu near the minicart with a Quick Order link.
- The quick order page should display with a title under the breadcrumb small text paragraph in the middle.

**Comment by hackergil** [comment]
@plabadie I tried this with develop and there are no layouts for B2B and B2C anymore. I updated the config on `layout-config.ts` and I am not able to see the dropdown menu. Maybe testing steps need to be updated?

**Comment by dydome** [comment]
We can close this ticket as it is already resolve.
