### ISSUE TITLE
[EPIC] More extendibility of Spartacus classes

### ISSUE THREAD

**Issue by ghost** [SAP/spartacus#9022]
A lot of functions in Spartacus classes cannot be overwritten because of private modifiers.
Likewise, many - e.g. reducers - are not exported as public API (`index.ts`).
Due to this, we are forced to copy-paste many lines of code only to extend a few lines.
Please export all classes and use protected/public over private.

Lastly, it is difficult to merge `enum`'s, which makes it difficult for us to add a new `ICON_TYPE` as an example.

**Comment by Xymmer** [comment]
Hi @jongyunchoi-sap! Some comments on your topics:
- For enums/ICON_TYPE, we're starting to address that issue.
- Reducers: We're likely not going to export these because we consider it internal implementation detail, and due to wanting to maintain compatibile between releases.
- Generally if we are not exposing something, we considered it and decided not to. However, if you give us specific examples, we will consider them for sure.

Let us know

**Comment by ghost** [comment]
Hi @Xymmer 

These are what we'd like 
1.	Public API:
Cart, Cart Entry, Product, Checkout effects/actions/selectors/reducers

2.	Access Modifier:
ActiveCartService

**Comment by ghost** [comment]
## For Cart domain
### What to do
For every class (`*.ts` except for `*.spec.ts` and `*.module.ts`) in
- core/cart
- storefrontlib/cms-components/cart
​
1a. every function's access modifier is protected or higher
1b. every field's access modifier is protected or higher, or getter & setter functions are provided
​
2a. every dependency class (classes injected in constructor) are public
2b. every class is exposed through public API (`index.ts`) all the way to the top of the package (`cart/index.ts`)
​
### Verification
1. Verify the extensibility by writing a custom app that imports and extends Spartacus classes.
2. No Spartacus class should be imported from `/src`.
3. It must be possible to build the custom app with production profile (i.e. without Spartacus source)
​
Example: Given a Spartacus class as following
```typescript
export class DefaultService {
    myField: any;
​
    constructor(depA: DependencyA, depB: DependencyB) {
    }
​
    myFunc1() {
    }
​
    myFunc2(params) {
    }
}
​
export function defaultReducer() {
}
```
​
Write a class as such
```typescript
import 'defaultReducer' from '@spartacus/core';
​
export class CustomService extends DefaultService {
    constructor(depA: DependencyA, depB: DependencyB) {
        super(depA, depB);
        defaultReducer();
    }
​
    myFunc1() {
        console.log(this.myField);
    }
​
    myFunc2(params) {
    }
}
```

**Comment by boli-sap** [comment]
As Jongyun mentioned above, here are some example of Changing Cart domain

### Example
For instance in `core/src/cart/facade/active-cart.service.ts`
**1a. every function's access modifier is protected or higher**

There are several methods with private modifier
```
private initActiveCart();
private loadOrMerge(cartId: string, userId: string, previousUserId: string): void;
private load(cartId: string, userId: string): void;
private addEntriesGuestMerge(cartEntries: OrderEntry[]): void;
private requireLoadedCartForGuestMerge(): Observable<ProcessesLoaderState<Cart>>;
private isCartCreating(cartState: ProcessesLoaderState<Cart>, cartId: string): boolean;
private isEmail(str: string): boolean;
private guestCartMerge(cartId: string): void;
private isEmpty(cart: Cart): boolean;
private isJustLoggedIn(userId: string, previousUserId: string): boolean;
```

Change the modifiers from private to protected

```
protected initActiveCart();
protected loadOrMerge(cartId: string, userId: string, previousUserId: string): void;
protected load(cartId: string, userId: string): void;
protected addEntriesGuestMerge(cartEntries: OrderEntry[]): void;
protected requireLoadedCartForGuestMerge(): Observable<ProcessesLoaderState<Cart>>;
protected isCartCreating(cartState: ProcessesLoaderState<Cart>, cartId: string): boolean;
protected isEmail(str: string): boolean;
protected guestCartMerge(cartId: string): void;
protected isEmpty(cart: Cart): boolean;
protected isJustLoggedIn(userId: string, previousUserId: string): boolean;
```

**1b. every field's access modifier is protected or higher, or getter & setter functions are provided**

The field `activeCart$, activeCartId$, cartSelector$` has private modifier
Change them into protected

```
protected activeCart$: Observable<Cart>;
protected activeCartId$: Observable<string>;
protected cartSelector$: Observable<ProcessesLoaderState<Cart>>;
```

**2a. every dependency class (classes injected in constructor) are public**
All classes injected in constructor are available from outside.

**2b. every class is exposed through public API (index.ts) all the way to the top of the package (cart/index.ts)**
the ActiveCartService is export with `core/src/cart/facade/index.ts` -> `core/src/cart/index.ts`


Another instance in `core/src/cart/store/reducers/multi-cart.reducer.ts`
no changes for 1a, 1b and 2a.
for **2b**: all the reducers are included in `core/src/cart/store/reducers/index.ts`, but it hasn't been export with `core/src/cart/index.ts`

old version of `core/src/cart/index.ts`
```
...
export * from './store/actions/index';
export * from './store/multi-cart-state';
export * from './store/selectors/index';
...
```
change it to 
```
export * from './store/index';
```
Thereby, the method **getMultiCartReducers()** in `core/src/cart/store/reducers/index.ts` can be accessable in outside of Spartacus.


### Verification
Step for Verification, 

1. build spartacus source code

- In the spartacus project. run `yarn build:libs`
- package the source code
```
cd dist/core
# or cd dist/storefrontlib
npm pack
```
A **spartacus-core-xxx.tgz** file will be availble under `spartacus/dist/core`

2. A angular application is provided from: https://github.com/boli-sap/cart-api-demo/tree/master
- clone it, and goto **cart-api-demo** folder
- copy the .tgz mentioned before into `cart-api-demo/spartacus`
- install the package with `npm install ./spartacus/spartacus-core-xxx.tgz`


3. Create custom class for Verification
For instance: 
- create **customActiveCartService** which extends **ActiveCartService**
```
@Injectable({
  providedIn: 'root',
})
export class CustomActiveCartService extends ActiveCartService {
  ...
}
```
Add constructor, Override all the methods in **ActiveCartService** and try to access all attributes
```
export class CustomActiveCartService extends ActiveCartService {

  constructor(
    protected store: Store<StateWithMultiCart>,
    protected multiCartService: MultiCartService,
    protected userIdService: UserIdService
  ) {
    super(store, multiCartService, userIdService);
  }
}


// override all methods of ActiveCartService
initActiveCart(): void {
  // access attributes
  this.activeCart$ = of(null);
  this.activeCartId$ = of('activeCartId');
  this.cartSelector$ = of(null);
  ...
}

loadOrMerge(cartId: string, userId: string, previousUserId: string): void {
  ...
}

load(cartId: string, userId: string): void {
  ...
}
...
```

- Make sure **no** Spartacus class should be imported from **@spartacus/xxx/src**
e.g.

`import {ProcessesLoaderState} from '@spartacus/core/src/state/utils/processes-loader';` is incorrect

it should be `import {ProcessesLoaderState} from '@spartacus/core';`

another example: try to invoke getMultiCartReducers() in initActiveCart()
```
initActiveCart(): void {
  const reducerMap = getMultiCartReducers();
}
```
the import should like `import {getMultiCartReducers} from '@spartacus/core'`

* build the custom app with production profile
```
ng build --prod
```


There are some changes made in: https://github.com/boli-sap/spartacus/pull/1/files; and some customClass can get in: https://github.com/boli-sap/cart-api-demo/tree/master

### The rest of tasks is:
Create customized Class for each the class in 
- `core/src/cart`
- `storefrontlib/cms-components/src/cart`

with add construction, access all field and override all method in parent class.
make sure all the class of Spartacus are imported from `@spartacus/core` or `@spartacus/storefront`

### Checkout domain
Check(change) and Verify every class (`*.ts` except for `*.spec.ts` and `*.module.ts`) in 
- `core/src/checkout`
- `storefrontlib/src/cms-components/checkout`

**Comment by marlass** [comment]
Sub tickets finished. Marking as done
