### ISSUE TITLE
Refreshing window in guest checkout redirects to login page

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9037]
**Seen on** `release/2.1.x` & `develop` & `2.0`

**Describe the bug**
When doing a checkout as guest if you refresh the page on any of the checkout steps you are redirected to the login.
Also during checkout as guest, when going back to a "Shipping Address" during checkout, not modifying the address information will lead to an infinite loading spinning when you click continue.

**To Reproduce**
1. Turn guest checkout on
```
      checkout: {
        guest: true
      }
```
2. Add product to cart and click proceed to checkout
3. Select guest checkout and enter an email
4. Go to checkout
5. On any step refresh the window

(Infinite Spinner)
6. Go back to "Shipping Address" while checking out as a guest.
7. Enter shipping info and click "continue".
8. On the next panel click "back" to revisit the "Shipping Address" panel.
9. Do not modify address information and click "continue".
10. You will notice an infinite spinner while on "Delivery Mode" panel.

**Expected behavior**
Should stay on the same page when refreshing on "Shipping Address" as a guest.
Switching back and forth between checkout panels shouldn't lead to infinite spinners.

**My guess**
Inspecting the logic it seems that there is some funky asynchronous issue happening and this check happens before the cart is loaded.

Just add a check to make sure the cart is stable before validating the user.

**Comment by Xymmer** [comment]
fix for next release (3.0) but don't backport

**Comment by ren-tham** [comment]
PR #9436 
Solution proposed.

**Comment by LTiger14** [comment]
### QA

1. Turn guest checkout on
```
      checkout: {
        guest: true
      }
```
2. Add product to cart and click proceed to checkout
3. Select guest checkout and enter an email
4. Go to checkout
5. On any step refresh the window -> **You should still be on that step**

**Comment by giancorderoortiz** [comment]
Able to confirm fix. Cool.

**Comment by giancorderoortiz** [comment]
Tested extensively looking for spinner. Couldn't reproduce after fix.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-05 at 5 51 02 AM](https://user-images.githubusercontent.com/46171897/98243795-74064980-1f3c-11eb-9684-c43a914c0ea8.png)
![Screen Shot 2020-11-05 at 5 58 55 AM](https://user-images.githubusercontent.com/46171897/98243797-74064980-1f3c-11eb-80d9-bacad1e58089.png)
