### ISSUE TITLE
Allow data passing to `launched` components using the launch dialog service

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#9041]
As we are moving away from ngModal, we now have the launch dialog service.

However, one drawback is that there is no data passing when `launching` a component.

We need to make the launch dialog service enable data passing in a way that it allows any kind of data to be passed to a launched component.

**Comment by bgambocjaviniar** [comment]
PR: GH-9042

**Comment by bgambocjaviniar** [comment]
QA:

- Make sure you're an anonymous user
- open dev tools and make sure the console view is open
- go to the footer and click `consent preferences` and when opening / closing / opening / closing, etc that the dialog behaves the same as what it did before.

**Comment by psmul** [comment]
QA done. Working as expected. No logs/errors related to modal behavior.
![image](https://user-images.githubusercontent.com/10993491/95312266-00b2de80-088f-11eb-92a2-d13da58c377c.png)
