### ISSUE TITLE
Remove `forVersion` usage in 3.0

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9044]
We should remove all usage of `forVersion` in each major.
Those should be revised in the whole codebase with 3.0 major release.

**Comment by developpeurweb** [comment]
**For QA:**

- Go to `projects/storefrontapp/src/styles.scss`
- Add this on Line 1: `$page-template-blacklist: LandingPage2Template, ProductDetailsPageTemplate;`
- See how the layout breaks on the **Homepage** and **PDP** and not the other pages.
- Remove Line 1 to see layout back to normal
- Additionally, there was only one visual change to unwrap, QA to verify that NO visual change should be perceived. The **added-to-cart image** should keep looking as per the screenshot below.

![Screen Shot 2020-10-29 at 12 13 57 PM](https://user-images.githubusercontent.com/15113219/97601418-88988e00-19e0-11eb-8533-6f0fd53b46bd.png)

**Comment by giancorderoortiz** [comment]
I see the removal of 'forVersions' as specified in description.

**Comment by giancorderoortiz** [comment]
Homepage and PDP indeed broken, per change, as mentioned above. 
All other pages ok. 

![Screen Shot 2020-10-30 at 11 55 40 AM](https://user-images.githubusercontent.com/46171897/97729066-ab8e7500-1aa8-11eb-8aed-2fb5f15c815c.png)
![Screen Shot 2020-10-30 at 11 56 07 AM](https://user-images.githubusercontent.com/46171897/97729068-acbfa200-1aa8-11eb-802c-d95f230d1baa.png)
![Screen Shot 2020-10-30 at 11 56 20 AM](https://user-images.githubusercontent.com/46171897/97729070-ad583880-1aa8-11eb-9c43-834a03f78acb.png)
![Screen Shot 2020-10-30 at 11 57 11 AM](https://user-images.githubusercontent.com/46171897/97729071-ad583880-1aa8-11eb-98ff-0261da7dbbed.png)
