### ISSUE TITLE
Clicking [x] in the my org card, hides it, but doesn't change the route

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9047]
**Describe the bug**

**To Reproduce**
1. Go to http://localhost:4200/powertools-spa/en/USD/organization/cost-centers/Custom_Retail/budgets
2. Click on [x] button in the `MANAGE BUDGETS` card

3. Observe the card `MANAGE BUDGETS` is closed
3. BUG: Observe that URL didn't change
4. BUG: You can't open `Budgets >` link again in the card `DETAILS COST CENTER`

**Expected behavior**
a) After clicking [x] in `MANAGE BUDGETS` cart, the url is shortened to `organization/cost-centers/Custom_Retail` (without `/budgets` at the end)
b) clicking `Budgets >` link opens again the bugets route

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/94280372-9d02ea00-ff4d-11ea-85b5-1ee433827472.png)
![image](https://user-images.githubusercontent.com/4001059/94280744-0daa0680-ff4e-11ea-9d34-e54cd2a60bc7.png)

**Additional context**
Similar problem occurs also when closing cards in other places. It's worth reviewing whole myorg against this problem.
Exapmle: http://localhost:4200/powertools-spa/en/USD/organization/units/Services%20East/addresses/8796098920471

**Comment by kacperknapik** [comment]
Needs checking if still exist

**Comment by Pucek9** [comment]
Closed by #9189
