### ISSUE TITLE
Unit name 'TODO' when editing unit address

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9051]
**To Reproduce**
1. Go to http://localhost:4200/powertools-spa/en/USD/organization/units/Services%20East/addresses/8796098920471/edit
2. Observe `Unit: (TODO)` in the `EDIT ADDRESS` card

**Expected behavior**
The  real unit name (in this case `Services East`)

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/94295433-82d30700-ff61-11ea-944c-c3f30644c679.png)

**Comment by Pucek9** [comment]
fixed as part of #10039
