### ISSUE TITLE
Strange animation when closing Unit Address Edit form 

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9052]
**Describe the bug**
After closing Edit unit address form, the animation goes back and forth once (instead of simply one step back).

**To Reproduce**
1. Go to http://localhost:4200/powertools-spa/en/USD/organization/units/Services%20East/addresses/8796098920471/edit
2. Click on `Cancel` button
3. Observe strange animation step back and forth once

**Expected behavior**
Animation 1 step back

**Screenshots**
![image](https://user-images.githubusercontent.com/4001059/94295692-eb21e880-ff61-11ea-9a90-7af642cfbdae.png)

**Comment by kacperknapik** [comment]
Doesn't need to be a part of MVP, moving to stretch

**Comment by Pucek9** [comment]
Closed by other PR and improved by #9621
