### ISSUE TITLE
SSL Certificate for training server

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9053]
Security certificate required to avoid blank screen when loading Spartacus. 

Current behaviour as follows: 
1. Load Spartacus first time. 
2. White screen is displayed in browser. 
3. Open dev tools. 
4. In Console, open backend server link shown in new tab or window. 
5. Accept security exception. 
6. Reload Spartacus page.

**Comment by giancorderoortiz** [comment]
@hackergil  fyi

**Comment by LTiger14** [comment]
This server is looking mighty fine. I was able to checkout and didn't see any problems while browsing around.
