### ISSUE TITLE
Enable Solr Search Indexing By Default in Backend

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9054]
Backend deployment requires the following manual step after initialization and startup so that product search works in Spartacus: 

1. Navigate to backoffice and login. 
2. System -> Search and Navigation
3. Solr Facet Search Configuration -> Facet Search Configuration
4. Click on Solr Config for Backoffice
5. Click on "Index" button (to the right of trash button)
6. In Indexer Operation Wizard, select "full" from Operation values dropdown. 
7. Click on Start button. 

This Solr indexing needs to be enabled by default in Spartacus recipe so that this manual step can be avoided and have an easier backend deployment. 

![Screen Shot 2020-09-25 at 5 20 02 PM](https://user-images.githubusercontent.com/46171897/94322890-d5acbe80-ff61-11ea-93bb-97c83364b5bc.png)
![Screen Shot 2020-09-25 at 5 19 55 PM](https://user-images.githubusercontent.com/46171897/94322888-d5acbe80-ff61-11ea-9398-244abccece40.png)

**Comment by giancorderoortiz** [comment]
This issue blocks automated deployment

**Comment by plabadie** [comment]
After an out of the box initialization, the product search works for me without any manual indexing steps.

**Comment by giancorderoortiz** [comment]
2005 or 2011? 
Did you have any properties setup for enabling OOTB ?

**Comment by plabadie** [comment]
2005 and below I'm sure search works ootb.  Which version do you have this issue with?

**Comment by reji6174** [comment]
Spartacus sample data 2011 with CX Commerce 2011 is having issue.
This did not happen with CX Commerce 2011 and Spartacus sample data 2005
![image](https://user-images.githubusercontent.com/73132457/126928518-3f09f8b6-edf6-43c3-a18f-b8de441f8d94.png)
