### ISSUE TITLE
Manual CMS Configuration Needed in Backoffice. Blocks Automated Deployment. 

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9055]
This additional manual step is required so that Spartacus storefronts of the following routing path can be accessed: storefront/language/currency

1. Navigate to backoffice and login. 
2. Navigate to WCMS -> Website -> 
3. For each of the "spa" websites, do the following: 
3.a. Select spa storefront
3.b. In Properties tab, scroll down to URL patterns
3.c. Add the following pattern: (?i)^https?://[^/]+/electronics-spa(|/.*|\?.*)$
3.c.i. replace 'electronics' for the appropriate storefront name. 
3.d. Scroll down to URL Encoding Attributes. 
3.e. Add "storefront"
3.f. Sort them in the following order: storefront, language, currency. 
3.g. Click on Save button. 

This manual step should be avoided. URL pattern and URL encoding attributes should be added in impex or sample data directly.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-09-25 at 5 24 43 PM](https://user-images.githubusercontent.com/46171897/94323456-df372600-ff63-11ea-8355-6d2bf735bb7b.png)
![Screen Shot 2020-09-25 at 5 25 00 PM](https://user-images.githubusercontent.com/46171897/94323457-dfcfbc80-ff63-11ea-9220-0f1cc235d705.png)

**Comment by giancorderoortiz** [comment]
This manual step slows down backend deployments. 
@gladius-mtl , @zebercut please prioritize.

**Comment by WeizhengSap** [comment]
PR is here: https://github.tools.sap/cx-commerce/spartacussampledata/pull/148

**Comment by giancorderoortiz** [comment]
This works! 👍 
Thanks so much :-)
![Screen Shot 2020-12-08 at 3 22 56 PM](https://user-images.githubusercontent.com/46171897/101539307-5463a600-396c-11eb-916d-261bb7192923.png)
![Screen Shot 2020-12-08 at 3 23 04 PM](https://user-images.githubusercontent.com/46171897/101539309-5463a600-396c-11eb-9e0b-68c73ce07448.png)

**Comment by giancorderoortiz** [comment]
@hackergil this fix will remove manual step in backend server deployment. 
Easier to automate now.
