### ISSUE TITLE
Upgrade Angular to the latest patch 10.1.x (>=10.1.3)

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9063]
In Angular 10.1.0 introduced false-positive console warnings saying:
_A router outlet has not been instantiated during routes activation. URL Segment...._
They show up in my-company feature (using dynamic nested routes), which can confuse customers.

It was fixed recently in Angular 10.1.3 patch.

So we should bump the minimal required version of Angular to 10.1.3 before we ship Spartacus 3.0, to avoid confusing console warnings in customers' app.

Note: the warning appears only in dev mode.

**Comment by mirkosoft** [comment]
related to #8930
