### ISSUE TITLE
Update to bootstrap 4.3.1 or higher

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9066]
We should update bootstrap to cope with vulnerability warning (XSS), see  https://github.com/SAP/spartacus/network/alert/package.json/bootstrap/open

Higher version would not hurt actually. Let's aim for latest bootstrap.

**Comment by morganm58** [comment]
@giancorderoortiz Can you also test this one with bootstrap 4.0 as well?

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-25 at 11 45 19 AM](https://user-images.githubusercontent.com/46171897/97111872-96d06c80-16b7-11eb-8a9f-f0ae07ac3ff8.png)

**Comment by giancorderoortiz** [comment]
e2e test run successful.
