### ISSUE TITLE
B2b Checkout failling on develop

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9079]
Following the merge of my-company b2b checkout has been failing on develop.

### Issues
- No Payment type step
- Arriving on Shipping adress step throws an error
- When trying to choose an address, it throws error
<img width="1440" alt="Screen Shot 2020-09-28 at 12 57 11 PM" src="https://user-images.githubusercontent.com/10605724/94463209-957c5480-018a-11eb-8923-b04a0048d030.png">

### Acceptance

- Fix b2b checkout and make sure b2c checkout is still working
-  Use the convenient and very stable b2b e2e tests to validate

**Comment by psmul** [comment]
@LTiger14 Could you provide QA steps?

**Comment by psmul** [comment]
QA done. B2B and B2C checkout working properly. E2E for checkout passing correctly.
