### ISSUE TITLE
Drop B2bAddress all together

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9084]
There's no such thing as a `B2bAddress`. We should replace the B2bAddress with the common Address model.

**Comment by bit-dragon** [comment]
Is it related to the following typescript errors? 

```js
node_modules/@spartacus/my-account/organization/components/unit/links/addresses/services/unit-address-item.service.d.ts:1:10 
- error TS2305: Module '"../../../../../../../core/spartacus-core"' has no exported member 'B2BAddress'.
```

I'm doing a setup with the latest Spartacus version (^3.0.0-next.3) and I'm not able to run the application.

**Comment by tobi-or-not-tobi** [comment]
This is fixed and merged already.
