### ISSUE TITLE
Major Release checklist

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9088]
With 3.0, we like to come up with a general checklist for major Spartacus releases. This includes: 

- Align specific version notation (caret vs tilde) for deps. 
  - do this cross all package.json files (both shell app and libraries)
  - For angular and ngrx we use caret
  - Use CLI generated notation for all  other packages
- Add a note to docs about supported versions and add a note to @gladius-mtl 
- update the installation docs (Angular CLI version, specific commands used, dependency list and versions, ... ) https://github.com/SAP/cloud-commerce-spartacus-storefront/blob/develop/docs/setupandinstallation.md
- Summarise the steps in `docs/libs/update-dependencies.md`
- Come up with a note / ticket on the schematic part of this; 

Spartacus 3.0 will use Angular `^10.1.0`.

**Comment by mirkosoft** [comment]
docs repo ticket: https://github.com/SAP/spartacus-docs/issues/771
