### ISSUE TITLE
Use DatePickerFormatterService in Replenishment Order, and also fix the logic if it applies.

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#9103]
master ticket: GH-8202

* This will be worked on after merging epic/b2b-scheduled-repl into develop

Similarly, replenishment was using `toISOString` to convert the date into date format of ISO 8601.
Therefore, replenishment should start using DatePickerFormatterService services

---
Additionally, the logic for both is not the correct one as it is converting the local date time (your current timezone) into the general UTC+0 date. I noticed sometimes when ordering a replenishment order that the date did not match as the conversion from local date to UTC broke it. --> To verify with any others

**Comment by Zeyber** [comment]
Posted in a code review comment what I believe is going on here:
https://github.com/SAP/spartacus/pull/9234#discussion_r503218703

**Comment by giancorderoortiz** [comment]
I see no side effects. 
Tested with Chrome v86.
![Screen Shot 2020-11-02 at 7 01 45 AM](https://user-images.githubusercontent.com/46171897/97866121-4a99b380-1cd9-11eb-8084-6a31a8925e56.png)
