### ISSUE TITLE
Update installation script for new libraries

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9104]
Add publishing for new libs `@spartacus/my-account` and `@spartacus/setup`

In install commands also add for each (`&& ng add @spartacus/my-account && ng add @spartacus/setup`)

Then when someone would like to test B2B they only have to import `B2BStorefrontModule` instead of `B2CStorefrtonModule` and that should be enough to run B2B storefront.

When we add schematics for B2B then we could add new configuration option in installation script to also install from `@spartacus/setup` schematics.

**Comment by mirkosoft** [comment]
Reopening as small fix is needed (install after release: wrong version installed using npm).
