### ISSUE TITLE
Add SSL Certificate for demo server

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9111]
Install SSL Security certificate to avoid a blank screen when loading Spartacus.

**Comment by hackergil** [comment]
CSR: https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/
SSR: https://spartacus-demo.eastus.cloudapp.azure.com:2743/electronics-spa/en/USD/

**Comment by giancorderoortiz** [comment]
Replicate to qa, dev2,dev3 servers. 
dev0? @hackergil
