### ISSUE TITLE
Split the Occ endpoints config interface in between feature libs

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9112]
The core config interface `OccEndpoints` (`projects\core\src\occ\occ-models\occ-endpoints.model.ts`) contains a complete list of endpoints, including endpoints needed only by the feature libs. The file is already very busy. For readability and scalability it would be good to split this interface in between the feature libs.
Currently it contains list of endpoints used in the `@spartacus/my-company/organization` lib. See the part of the file:
https://github.com/SAP/spartacus/commit/bc69ae2e86bbe45e17df67f8081a92e60f0923ea#diff-5798d8e2470ec95ac89c9df1309b3b6dR375

It's going to be similar case for the upcoming configurable product feature.

In the end of the day the main purpose of this interface is to provide intellisense code suggestions for customers when configuring Spartacus app.

We need to investigate how to achieve splitting this interface. Maybe _type augmentation_ can help.

**Comment by Xymmer** [comment]
@marlass fyi, for next major
to consider for 4.0

**Comment by dunqan** [comment]
We should also consider some `OccEndpointService` refactor, especially;
- ability to get the raw endpoint without baseSite
- clean-up the logic (as it grown over time and become quite ugly)
- support prefix without preceding slash (to make life easier for Windows people using schematics)

**Comment by giancorderoortiz** [comment]
how to qa?
