### ISSUE TITLE
[retest] Error during install of @spartacus/schematics on Windows 10

### ISSUE THREAD

**Issue by CharlesDeJager** [SAP/spartacus#9115]
**Describe the bug**
There is an error during the installation of @spartacus/schematics on windows 10

Error:

> [1/4] Resolving packages...
> warning @angular-devkit/build-angular > less > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> warning @angular/compiler-cli > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> [2/4] Fetching packages...
> error https://registry.yarnpkg.com/@spartacus/styles/-/styles-1.5.9.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "EPERM: operation not permitted, mkdir 'C:\\Users\\chdejager\\AppData\\Local\\Yarn\\Cache\\v6\\npm-@spartacus-styles-1.5.9-7793f21fc20f897e750514268dca64ba2fbeb607-integrity\\node_modules\\@spartacus\\styles\\scss\\components\\checkout\\steps\\payment'"

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Xymmer** [comment]
- repro 1.5.*
- if you can repro, ask release master to rerelease if needed (looks like broken package)
- if not repro comment here and ask for more info

**Comment by giancorderoortiz** [comment]
no access to Windows 10 device. Another team member will need to take a look

**Comment by Xymmer** [comment]
we retested 3.0 on windows 10, it's working, closing
