### ISSUE TITLE
Terms And Conditions - Hyperlinks not working

### ISSUE THREAD

**Issue by ivan-ilic** [SAP/spartacus#9116]
**Describe the bug**
Terms and conditions page consists of 3 paragraph components. In those components, ID attributes are added for hyperlinks. Since cx-paragraph component uses "[innerHTML]" to display component content, ID attributes are not rendered, and hyperlinks are not working. 

**To Reproduce**
To to Terms and Conditions page, hyperlinks in menu are not working so anchors cannot be used to navigate

**Comment by Xymmer** [comment]
dupe of #3506 which depends on #915
