### ISSUE TITLE
Mixin for page template

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9117]
As we no longer have styles in one library we need to change page layout whitelist/blacklist mechanism to be a mixin which can be used from every library.

Currently we have hardcoded page template in `@spartacus/my-account` and we would like to steer it the same way we do it with `$page-template-whitelist` and `$page-template-blacklist`.

**Comment by tobi-or-not-tobi** [comment]
FYI the implementation that we provide here is not coming with a generic mix-in that we leverage from a single place. I'm actually fine with this for now, as it would requires a dependency on our core style lib, which is not a nice thing for customers who will not use our style library.

**Comment by developpeurweb** [comment]
**For QA:**
This might need redeployment to test in a server, but to test locally do the following:

- Login as `linda.wolf@rustic-hw.com` in B2B
- Go to My Company > Budgets
- Go to `feature-libs/organization/administration/styles/_page-template.scss`
- Move `CompanyPageTemplate` to the blacklist
- See how `My Company > Budgets`'s layout breaks
- Put `CompanyPageTemplate` back in the whitelist and the layout should go back to normal.

**Alternative test:**
- Go to `projects/storefrontapp/src/styles.scss`
- Add this on Line 1: `$page-template-blacklist-organization: CompanyPageTemplate;`
- See how `My Company > Budgets`'s layout breaks
- Remove Line 1, see how layout goes back to normal.

**Comment by giancorderoortiz** [comment]
Before change to _page-template.scss: 

![Screen Shot 2020-10-30 at 9 34 14 AM](https://user-images.githubusercontent.com/46171897/97711227-34021b00-1a93-11eb-8aba-c3a311becdac.png)

---
After change to _page-template.scss:

![Screen Shot 2020-10-30 at 9 33 08 AM](https://user-images.githubusercontent.com/46171897/97711267-4419fa80-1a93-11eb-9d3a-8c5b69b634fe.png)
![Screen Shot 2020-10-30 at 9 32 33 AM](https://user-images.githubusercontent.com/46171897/97711295-4d0acc00-1a93-11eb-9fca-258e4bd8b23c.png)

**Comment by giancorderoortiz** [comment]
ok

**Comment by giancorderoortiz** [comment]
Not sure if this change requires documentation
