### ISSUE TITLE
Get OAuth flow in auth config service

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9145]
Get which flow we are currently using, so we can change behavior of some components (no auto redirect from register to login component on implicit or authorization code flow).

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
QA steps:
- `getOAuthFlow` should return correct flow based on `responseType` option in auth config. If it contains `token` then Implicit flow, if `code` then Authorization Code and for rest of the cases Resource Owner Password Flow
