### ISSUE TITLE
Demo app for implicit flow with hybris

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9148]
Demo app for testing implicit flow with hybris server

Legend:
🔲 - not yet checked
🟦 - some improvements needed
❌ - broken core functionality
✅ - everything is ok

Use cases:

- 🅰️ test app without AsmModule
- 🅱️ test app with AsmModule
	- 🔲 when user is logged in and we login as cs agent previous session should be remembered (after cs agent logout user session should be resumed)
	- 🔲 when no one is logged in nothing should change after cs agent login
	- 🔲 CSAgent can use password flow
	- 🔲 CSAgent can use implicit flow
	- 🔲 when there isn't currently any emulated session on agent logout he should be redirected to logout page
	- 🔲 user should not be able to login when there is ongoing asagent session (warning shown)
	- 🔲 user logout when he is emulated should not end cs agent session
	- 🔲 after each csagent logout (expired token, normal logout) LogoutCsAgent action should have been dispatched
	- 🔲 cart merging should work with on user emulation

Tests for both use cases:
- 🅰️ 🅱️  can login
- 🅰️ 🅱️  can logout (token in revoked)
- 🅰️ 🅱️  supports logout endpoint (third party server?)
- 🅰️ 🅱️  test the CDC lib
- 🅰️ 🅱️  anonymous consents still work
- 🅰️ 🅱️  test if session in persisted after page refresh
- 🅰️ 🅱️  user should be redirected to previous page after login
- 🅰️ 🅱️  after each user session end (emulation end, logout, expires session) Logout action should have been dispatched
- 🅰️ 🅱️  register and other endpoints requiring client token should still work as before
- 🅰️ 🅱️  accessing non login routes (login, register, forgot password) should redirect to homepage
- 🅰️ 🅱️  user should not be automatically redirected to login page on email change and reset password actions
- 🅰️ 🅱️  auth errors interceptor should work as before (for expired access token try to refresh token and retry call, for expired refresh token logout)
- 🅰️ 🅱️  cart merging should still work
- 🅰️ 🅱️  SSR still works (SSR is session less, but redirect from OAuth server works on client side after SSR)

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
Demo apps were prepared for testing on branch `feature/auth-demo`

Different configuration is provided in root configuration that can be switched by commenting/uncommenting code and adjusting configuration in backoffice.

This branch doesn't have to be used. It can be tested on normal app. However in comments in this branch there are infromation about required changes in backoffice.

Thanks to this different flows can be enabled as well as open id token.

Hard to defined precise QA steps ad this is just demo app. Testing different auth flows will verify that everything works as intended and not only resource owner password flow which is used normally. Each auth functionality is decribed in other tickets done in session management effort.
