### ISSUE TITLE
Demo app for authorization code flow with hybris

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9149]

**Comment by giancorderoortiz** [comment]
how to qa/validate?

**Comment by marlass** [comment]
Demo apps were prepared for testing on branch `feature/auth-demo`

Different configuration is provided in root configuration that can be switched by commenting/uncommenting code and adjusting configuration in backoffice.

This branch doesn't have to be used. It can be tested on normal app. However in comments in this branch there are infromation about required changes in backoffice.

Thanks to this different flows can be enabled as well as open id token.

Hard to defined precise QA steps ad this is just demo app. Testing different auth flows will verify that everything works as intended and not only resource owner password flow which is used normally. Each auth functionality is decribed in other tickets done in session management effort.
