### ISSUE TITLE
b2b checkout cost center not kept when going back

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9155]
**Describe the bug**
When doing a b2b checkout using an account the selected cost center is not kept if you go back.

**To Reproduce**
1. Start b2b checkout, select account payment
2. Choose a cost center
3. Go to review step
4. Go back to shipping address step, the cost center is now the first one in the list

**Expected behavior**
The selected cost center and shipping address should be the one selected before

**Comment by LTiger14** [comment]
PR: https://github.com/SAP/spartacus/pull/9156

1. Create a new user on dev0 using postman (same way as for b2c)
2. Login with your new user
3. Do a b2b checkout as account, select a cost center (not the first one)
4. Go to review page
5. Go back to shipping address, make sure your address and cost center are selected

BONUS: go to backoffice take a cost center (pronto something) and add an other address
- Do the flow again

Make sure happy flow for both b2b and b2c are also working.

**Comment by LTiger14** [comment]
QA:
1. Run Spartacus in b2b mode
2. Add product to cart and checkout
3. Select account payment
4. Select Cost Center and address and click continue
5. Go back, the same CC and address should be selected
6. Finish checkout
7. Do a happy path for B2b credit card and B2c checkout

**Comment by saad-mo** [comment]
Tested happy patch on latest develop on local and it works as expected.
