### ISSUE TITLE
Update e2e Tests with Generic Backend Password

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9170]
Check all e2e tests that use backend specific user accounts. 
Update where applicable to generic password. 

Depends on https://github.com/SAP/spartacus/issues/9169
Strong impact on B2B tests. 

@hackergil, @Xymmer , this may mean that a few e2e tests will break while upgrade is in process.

**Comment by plabadie** [comment]
It was discussed with the team that this should be done post 3.0 release in order not to impact the release.

**Comment by giancorderoortiz** [comment]
Already done: 
See projects/storefrontapp-e2e-cypress/cypress/sample-data/shared-users.ts or https://github.com/SAP/spartacus/blob/2e07e10a4bcd8c0e3634e69fa9f0fb51aa090b77/projects/storefrontapp-e2e-cypress/cypress/helpers/asm.ts
