### ISSUE TITLE
Subsection stay selected even close it

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9174]
Steps to reproduce:
Cost centers > choose any cc > Budgets > close > Budgets

Link stay as selected and is not openable again. It occurs on all subsections with assign functionality.

![image](https://user-images.githubusercontent.com/8040837/95071694-6033b180-070a-11eb-9735-4a369c6d4690.png)

**Comment by tobi-or-not-tobi** [comment]
This is related to the fact that either angular routing or our routing logic cannot work with the empty route path, with child routes. @Platonn is investigating.

**Comment by Pucek9** [comment]
duplice of #9047
