### ISSUE TITLE
Inclusive Language In Spartacus Project

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9175]
Pursuant to SAP's Open Source Program Office directive, undertake a comprehensive and thorough review of Spartacus project (documentation, source code, etc) to remove insensitive terms and replace them with inclusive language. 

Additional details here: 
[Inclusive Language](https://jam4.sapjam.com/groups/fpVjPTHoZVTjFIbqxZSK6s/overview_page/mKndpOcF66U1zFsy6uyYB9)

**Comment by Xymmer** [comment]
- our master is now called 'main'
- old master deleted

but
- we still have terms like whitelist and blacklist
- Bill to review the faq and come up with list of things to check (https://jam4.sapjam.com/groups/fpVjPTHoZVTjFIbqxZSK6s/overview_page/slC3Df1qamKevuJmaoKNRO)

**Comment by giancorderoortiz** [comment]
Thanks for the progress on this.

**Comment by Xymmer** [comment]
dupe of https://github.com/SAP/spartacus/issues/11340
