### ISSUE TITLE
Move configurator html out from storefront lib

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9176]
A majority of code was moved from libs `core` & `storefront` to the `product` lib for the product configurator feature. A few things that were problematic to move and need a second pass. Including this one:

Configurator html was added to `cart-item.component`, `product-(list|grid)-item.component`. Then some services also are trapped in the `storefront` lib as dependencies of those components.
   - Idea how to move out: add dedicated `cxOutlet`s for configurator additions in html templates.
   - Open ends:
      - We still need to investigate how to pass the context to the outlet components registered in the `product` lib. 
      - Outlet components need to be registered eagerly. Therefore we need to place the outlet components in a separate entry point of the `product` lib, to be loaded eagerly (not to break lazy laoding of the rest of the components). How to name the entry point?

**Comment by ChristophHi** [comment]
Was done in #9740
