### ISSUE TITLE
Update public instance URL

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9181]
Let's update the public instance URL to a working/up to date one: search project for `c39j2` and replace urls with:
https://spartacus-training.eastus.cloudapp.azure.com/electronics-spa/en/USD/

related to https://github.com/SAP/spartacus-docs/issues/774

**Comment by Xymmer** [comment]
should be demo server
https://spartacus-demo.eastus.cloudapp.azure.com/electronics-spa/en/USD/
