### ISSUE TITLE
Save cart state and facade

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9190]
Create the inner working required for the "save cart" behavior.

### Scope
- Save cart actions (normal, success, fail) - in cart actions
- Save cart effect (calls the occ function that already exists) - in cart effect
- Save cart function in facade - in active cart service > calling multi-cart

### Acceptance
- Able to dispatch the save cart request to the sever
- Once a cart is saved it is no longer active

**Comment by bgambocjaviniar** [comment]
OLD ~~PR: GH-11268~~

new PR: GH-11390
