### ISSUE TITLE
Core functionality for Saved Cart List

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9193]
Create the inner workings required to the load the saved carts for the listing page.

### Scope
- Actions, effect, reducer that allow to load all saved carts
- Facade method to allow to load saved carts
- facade method to update saved carts

### Acceptance
- Should be able to fetch saved carts for a user and see them in the store. **Think about pagination and ordering**.

**Comment by bgambocjaviniar** [comment]
PR: GH-11230
