### ISSUE TITLE
Add items from saved carts to active cart functionality

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9200]
After #9199 & #9197.

### Scope
- Create the functionality that allows to add all items or add selected items
- Wire the check-boxes from the list to allow the user to select items (to be considered: shared service between the components or use the state to have an item "selected")
- Create the actions, effects, adapters, facades, etc. to make this possible
- Handle success and quantity checks

### Acceptance
- Should be able to add selected items to active cart
- Should be able to add all items to active cart
- If I have no active cart one is created for me
- Success and errors are handled

**Comment by bgambocjaviniar** [comment]
will be done in #9193
