### ISSUE TITLE
E2e tests for Saved cart

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9201]
Minimum test cases:

#### Happy path

Add items to cart > save cart > Check cart is saved > Edit item quantities in cart > Delete items from saved cart > Restore certain items (validate & delete from active cart) > Add all items to cart (validate)

#### Restore with items in cart

Add items to cart > save cart > Check cart is saved > Add other items to active cart (including one that is the same as in the saved cart) > Go to saved cart > Restore certain items (validate & delete restored from active cart) > Restore all items to cart (validate)

#### Listing page

Add items to cart > save cart > [repeat multiple times] > test listing order in saved carts listing page

**Comment by bgambocjaviniar** [comment]
PR: https://github.com/SAP/spartacus/pull/11618


- tested against dev3 (has latest sample data, but with the saved cart cms components)
- b2b = true
- don't forget to update appropriate cypress.json (depends how you run the command to open/run cypress)

<img width="333" alt="Screen Shot 2021-03-23 at 12 12 56 AM" src="https://user-images.githubusercontent.com/29099466/112091965-e0d95380-8b6c-11eb-8716-b55c1ccb49f2.png">
