### ISSUE TITLE
a11y e2e tests for saved carts

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9202]
**Also validate the tabbing actually works**

Validate tabbing for:
- [x] cart page,
- [x] cart dialog form
- [x] saved carts listing page
- [x] saved carts details page.

**Comment by bgambocjaviniar** [comment]
PR: https://github.com/SAP/spartacus/pull/11618


- tested against dev3 (has latest sample data, but with the saved cart cms components)
- b2b = true
- don't forget to update appropriate cypress.json (depends how you run the command to open/run cypress)

<img width="333" alt="Screen Shot 2021-03-23 at 12 12 56 AM" src="https://user-images.githubusercontent.com/29099466/112091980-ea62bb80-8b6c-11eb-91fa-edcb72e083a1.png">
