### ISSUE TITLE
UX for B2B Registration (XS)

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9207]
Fields: https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Registration
SOT: https://cxwiki.sap.com/display/spar/B2B+Registration+SoT

**Comment by jeannewalters** [comment]
Manu - Finish by 11/06. This will include a review.

**Comment by Manurod2018** [comment]
See visuals on Zeplin: https://zpl.io/bArENyq
