### ISSUE TITLE
Verify directionality in My company

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9211]
Check that my company features have implemented directionality properly

**Comment by tobi-or-not-tobi** [comment]
A few misses: 
- [x] notification message close button is showing up weird. The close icon is positioned on the left hand side and doesn't flip on rtl mode
- [x] list icon is not flipping in rtl mode
- [ ] form error icon is displayed incorrectly (but that's outside my company)
- [x] breadcrumb is not following rtl direction (but that's outside my company) (#9217)
