### ISSUE TITLE
Unit change user roles issues

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9216]
- [ ] Missing selection class
- [ ] subtitle should contains user name, not unit name
- [ ] changing user shouldn't trigger notification - probably will be solved by #8978
![image](https://user-images.githubusercontent.com/8040837/95204201-0bfd0000-07e4-11eb-994e-c9f11690680b.png)

**Comment by tobi-or-not-tobi** [comment]
fixed partially, and will be done with #9050
