### ISSUE TITLE
UX for B2B Saved Carts (M)

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9223]
Requirements:
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Saved+Carts

SOT:
https://cxwiki.sap.com/display/spar/B2B+Saved+Carts+Source+of+Truth

**Comment by Manurod2018** [comment]
For visuals please see "Saved Cart" section on Zeplin:
https://zpl.io/2ENnmAY

**Comment by medzneel** [comment]
https://sapse.invisionapp.com/share/HKYHZ8KF4EP#/screens

Invision updated.

**Comment by jeannewalters** [comment]
This is done.

**Comment by Xymmer** [comment]
back to medha for update of source of truth

**Comment by medzneel** [comment]
The UX Spec will be delivered by Nov 20,2020
