### ISSUE TITLE
Error with installing Spartacus addon

### ISSUE THREAD

**Issue by joelCX-sap** [SAP/spartacus#9226]
Hello, I'm having a problem when I want to install the add-on for local commerce.  (i'm new in Spartacus)

I'm following this guide https://sap.github.io/spartacus-docs/installing-sap-commerce-cloud-2005/ but when I try to install the recepi i have the below error: 

![error](https://user-images.githubusercontent.com/65038154/95243977-bf1b2880-07e7-11eb-9eed-ca352a2b08c7.jpg)

Thanks!

**Comment by Xymmer** [comment]
@joelCX-sap : Make sure you have copied spartacus sample data to your extensions folder; also uncommented the right addons in the recipe according to what addons you are installing. Maybe add complete logs for better answers :)

If it still doesn't work, check for wro4j errors; use this to disable in your local.properties if that might help.
storefront.wro4j.enabled=false

**Comment by joelCX-sap** [comment]
Hello! Xymmer, how are you?? Ok, I didn't copied the sampledata into the extenssion folder. The uncomment was done. 

I'll find the extension folder and will try againg! Thanks in advance.
