### ISSUE TITLE
'ErrorPageTemplate' class added to the app-root (backport to 2.1)

### ISSUE THREAD

**Issue by sebastianfdez** [SAP/spartacus#9239]
**Describe the bug**
Since I upgraded to the last version of Spartacus 2.1, I've been experimenting this bug.

![image](https://user-images.githubusercontent.com/17834635/95440508-505ddc80-0959-11eb-82d6-c3516cb6fe3f.png)

Randomly this class is added to the root component, making everything look twisted by adding unwanted CSS everywhere. Sometimes it appears and then refreshing the page, is no more there.

**To Reproduce**
Its happens totally randomly

**Expected behavior**
The expected behavior is only having the `ErrorPageTemplate` class when we are directed to this page. Sometimes I have it in the Basket page or in the Product List page which alters our UX.

**Screenshots**
Those are some examples of unwanted CSS we receive in our pages

![image](https://user-images.githubusercontent.com/17834635/95440105-c9a8ff80-0958-11eb-9a19-db825fe9d5d0.png)

![image](https://user-images.githubusercontent.com/17834635/95440143-d9284880-0958-11eb-88cb-419c55890cb7.png)

**Desktop (please complete the following information):**
 - Browser: Chrome, Safari

**Additional context**
Since Spartacus@2.1 that we've been experimenting this.
I believe that the PageTemplateStyleService is doing something wrong. Instead of adding those classes to the `cx-storefront` is adding it to the `app-root`

```
/**
 * Service that adds the page template as a className to the application root element. If the root
 * element is cx-storefront, the resulting DOM would look like:
 *
 * ```html
 * <cx-storefront class="LandingPageTemplate">
 *  [...]
 * <cx-storefront>
 * ```
 */
@Injectable({ providedIn: 'root' })
export class PageTemplateStyleService implements OnDestroy {
  ...
}
```

Thanks to everyone

**Comment by tobi-or-not-tobi** [comment]
This is a bug actually, and should be considered a breaking change in a minor release. 

Bug: 
- we pollute the root application element, and this could be an element outside spartacus, used for other sub applications

Breaking: 
- we add a style class on an element outside Spartacus that could be used for other reasons
- the css class is not prefixed (but in control of customers data), and could conflict with customer style rules

**Comment by tobi-or-not-tobi** [comment]
Reopening as we also want to do a backport to 2.1 (likely dropping it all together).

**Comment by morganm58** [comment]
@sebastianfdez is this still an issue?
