### ISSUE TITLE
Remove references to HttpClientModule and import it via schematics

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9243]
We should drop all NgModule imports of `HttpClientModule` from our library modules, because it provides under the hood http interceptors handler. It should be rather imported by the customer in his app.module. It can be automated using schematics.

The main issue occurs, when the handler is provided in lazy-loaded module (by importing HttpClientModule there). Since the lazy loaded module has it's own isolated injector, then the http interceptors provided in the root injector are not visible.

See Angular code:
https://github.com/angular/angular/blob/956b25a1000c1e4d88597cef60f0bb0fb946fe78/packages/common/http/src/module.ts#L159

EDIT: We don't need schematics for that. We can put import of `HttpClientModule` just in the crecipes B2b & B2cStorefrontModule.

See Angular ticket:
See https://github.com/angular/angular/issues/20575

--
Removing stuff from our modules is a braking change, so must be implemented in major version

**Comment by dunqan** [comment]
We can move those imports to recipes, so schematics will work as before.
