### ISSUE TITLE
UX for potential promotions and review of existing promotions display (XS)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9259]
https://cxwiki.sap.com/display/spar/Feature%3A+Potential+Promotions

- Where and how potential promotions should appear
- Revisit updating how potential promotions appear now

In the following locations:
- Product Details
- Cart
- Cart entries

**Comment by medzneel** [comment]
Hi Bill,
Whats the priority date for this ticket?

**Comment by jeannewalters** [comment]
Manu will complete this by 11/06.

**Comment by Manurod2018** [comment]
See visuals on Zeplin:
https://zpl.io/aNrKpMv
