### ISSUE TITLE
UX for B2B Export Products (CSV) (S)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9260]
https://cxwiki.sap.com/display/spar/Feature%3A+Export+Products

**Comment by Manurod2018** [comment]
See visuals on Zeplin:
Desktop: https://zpl.io/adgWRl5
Mobile: https://zpl.io/V1XmME5

**Comment by Xymmer** [comment]
back in progress, would like source of truth with example screenshots and links to ux/visuals as needed

**Comment by medzneel** [comment]
Below are the links to the visuals.
Mobile
https://app.zeplin.io/project/5f062d700cf6485b7607df80/screen/5f91a40c2842628a84fb349b

Desktop
https://app.zeplin.io/project/5f062d700cf6485b7607df80/screen/5f91a4119751d10b9dc28bfb

**Comment by vekterdude** [comment]
To be delivered by Nov. 20, 2020.

**Comment by medzneel** [comment]
Visuals are done, UX Spec by 12/01/2020

Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  **"# 9260"** which is the ticket number of that feature to see all related screens.

**Comment by medzneel** [comment]
UX Spec - https://teams.microsoft.com/l/file/C6B0F040-7C9C-4883-85BA-0DB1FB562A74?tenantId=42f7676c-f455-423c-82f6-dc2d99791af7&fileType=pdf&objectUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy%2FShared%20Documents%2FGeneral%2FUI%20Specifications%2FPDFs%2FExport%20CSV_ux%20specs.pdf&baseUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy&serviceName=teams&threadId=19:3a55d585369544fc8f416d6d6d2fc546@thread.tacv2&groupId=600c4631-f350-4d6e-8de1-44b49c7dd4ac
