### ISSUE TITLE
UX for B2B Import Products (M)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9261]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Import+Products

**Comment by jeannewalters** [comment]
@Xymmer assigning to Bill for requirements.

**Comment by jeannewalters** [comment]
@Xymmer The feature wiki page has no requirements yet. It appears to be one of the next based on priority too.

**Comment by jeannewalters** [comment]
Medha will be handoff to Manu by 11/11

**Comment by medzneel** [comment]
Links to the wireframes
https://sapse.invisionapp.com/share/A4ZBRHW79SP#/437377408_M_Saved_Cart_List

**Comment by vekterdude** [comment]
Expected to be finished visuals by Nov. 20, 2020.

**Comment by Manurod2018** [comment]
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9261" which is the ticket number of that feature to see all related screen
![Zeplin](https://user-images.githubusercontent.com/37299626/99592820-b741cd00-29be-11eb-93e7-2b9fa98d87fd.png)
s.   (see screenshot attached)
