### ISSUE TITLE
UX for B2B Bulk Price Table (M)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9262]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Bulk+Pricing

**Comment by Manurod2018** [comment]
Bulk pricing visuals:
Desktop: https://zpl.io/beRY3Jz
Mobile: https://zpl.io/a7M4P0p

**Comment by jeannewalters** [comment]
@Xymmer Should I close this ticket since it's ready to go?

**Comment by jeannewalters** [comment]
Visual complete. Assigning to Bill.

**Comment by Xymmer** [comment]
you can assign to me first and i'll give feedback

**Comment by Xymmer** [comment]
Back to Anthony for source of truth and links to wires/diagrams

**Comment by Xymmer** [comment]
Source of truth is https://cxwiki.sap.com/display/spar/Bulk+Pricing+Source+of+Truth+Nov+2020
Back to 'to do' as search/category visuals/wires missing

**Comment by vekterdude** [comment]
To be delivered by Nov. 20, 2020.

**Comment by vekterdude** [comment]
Wireframe Delivery expected: December 4th, 2020

**Comment by vekterdude** [comment]
Prototype: https://sev4qm.axshare.com
Link to Design Spec: https://teams.microsoft.com/l/file/2CFA2464-BA82-48FC-B6D9-9D35AF6EA4A2?tenantId=42f7676c-f455-423c-82f6-dc2d99791af7&fileType=docx&objectUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy%2FShared%20Documents%2FGeneral%2FUI%20Specifications%2FWord%20and%20PPTs%2FBulk_Pricing.docx&baseUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy&serviceName=teams&threadId=19:3a55d585369544fc8f416d6d6d2fc546@thread.tacv2&groupId=600c4631-f350-4d6e-8de1-44b49c7dd4ac
