### ISSUE TITLE
UX for B2B Re-Order (XS)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9263]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Reorder

**Comment by jeannewalters** [comment]
The wireframes and wire images have been linked into the feature wiki above.

**Comment by jeannewalters** [comment]
@Manurod2018 Can you create visuals for the wires (if needed) and link to the feature above? Thanks

**Comment by jeannewalters** [comment]
@Manurod2018 Manu will review and give estimated date.

**Comment by Manurod2018** [comment]
Manu will finish by 11/11.

**Comment by Manurod2018** [comment]
See visuals on Zeplin: https://zpl.io/bLy0DEG

**Comment by jeannewalters** [comment]
@Xymmer I added the UI Spec link to the SOT page.
