### ISSUE TITLE
UX for B2B Quick Order (XL)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9268]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Quick+Order

**Comment by medzneel** [comment]
UX is done.

**Comment by medzneel** [comment]
https://sapse.invisionapp.com/share/ESYWVX1Q68B

UX is done.

**Comment by jeannewalters** [comment]
Manu will be done with this (including reviews) by 10/03.

**Comment by Manurod2018** [comment]
See visuals on Zeplin:
Quick Order version A: https://zpl.io/2ZZqWWl
Quick Order version B: https://zpl.io/VKrEMrR

**Comment by medzneel** [comment]
UX Spec will be provided on Nov 20,2020
