### ISSUE TITLE
UX for Pickup in Store (XL)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9270]
https://cxwiki.sap.com/display/spar/Feature%3A+Pickup+in+Store

**Comment by jeannewalters** [comment]
Anthony will handoff to Manu on 11/06.

**Comment by vekterdude** [comment]
To be delivered by Nov. 19, 2020

**Comment by vekterdude** [comment]
Design Spec in Read-only Microsoft Word:
https://teams.microsoft.com/l/file/67FC6A05-B4E2-4088-B2EB-547308AB4C66?tenantId=42f7676c-f455-423c-82f6-dc2d99791af7&fileType=docx&objectUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy%2FShared%20Documents%2FGeneral%2FUI%20Specifications%2FWord%20and%20PPTs%2FPickup_in_Store.docx&baseUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy&serviceName=teams&threadId=19:3a55d585369544fc8f416d6d6d2fc546@thread.tacv2&groupId=600c4631-f350-4d6e-8de1-44b49c7dd4ac

**Comment by vekterdude** [comment]
Manu expecting to be done visuals by Friday, December 4th, 2020

**Comment by Manurod2018** [comment]
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9270" which is the ticket number of that feature to see all related screens.

**Comment by saad-mo** [comment]
We have new wires/designs in Figma. This issue is no longer relavent
