### ISSUE TITLE
UX for Bundles (L)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9272]
https://cxwiki.sap.com/display/spar/Feature%3A+Bundles

**Comment by vekterdude** [comment]
To be delivered by Nov. 18, 2020

**Comment by vekterdude** [comment]
Design Spec in read-only MS Word file:

https://teams.microsoft.com/l/file/234A7742-2EF1-4C75-A539-582C5FC61455?tenantId=42f7676c-f455-423c-82f6-dc2d99791af7&fileType=docx&objectUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy%2FShared%20Documents%2FGeneral%2FUI%20Specifications%2FWord%20and%20PPTs%2FParity_Bundles_2.docx&baseUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy&serviceName=teams&threadId=19:3a55d585369544fc8f416d6d6d2fc546@thread.tacv2&groupId=600c4631-f350-4d6e-8de1-44b49c7dd4ac

**Comment by vekterdude** [comment]
This ticket is awaiting review by the Design Team.

**Comment by Manurod2018** [comment]
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9272" which is the ticket number of that feature to see all related screens.
