### ISSUE TITLE
UX for My Account Home (S)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9273]
https://cxwiki.sap.com/display/spar/Feature%3A+Account+Home

**Comment by jeannewalters** [comment]
@Xymmer The feature wiki page has no requirements yet. It appears to be one of the next based on priority too.

**Comment by Xymmer** [comment]
Ready
if you recall Amy did designs for this a while back

**Comment by jeannewalters** [comment]
Anthony will be handing it off to Manu on 11/2.

**Comment by vekterdude** [comment]
UX to be done by Nov.17th, 2020.
Assigned to Visuals immediately after.
Visuals to be done by Nov. 20th, 2020.

**Comment by vekterdude** [comment]
Link to Read-only MS Word Design Spec:

https://teams.microsoft.com/l/file/F54A1521-7C4D-4A40-8746-39586B9BCA00?tenantId=42f7676c-f455-423c-82f6-dc2d99791af7&fileType=docx&objectUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy%2FShared%20Documents%2FGeneral%2FUI%20Specifications%2FWord%20and%20PPTs%2FAccount_Home.docx&baseUrl=https%3A%2F%2Fsap.sharepoint.com%2Fteams%2FSPAMobileStrategy&serviceName=teams&threadId=19:3a55d585369544fc8f416d6d6d2fc546@thread.tacv2&groupId=600c4631-f350-4d6e-8de1-44b49c7dd4ac

**Comment by Manurod2018** [comment]
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9273" which is the ticket number of that feature to see all related screens.
