### ISSUE TITLE
UX for Added-to-Cart Toast (S)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9274]
https://cxwiki.sap.com/display/spar/FEATURE%3A+Added-to-Cart+Toast

**Comment by medzneel** [comment]
Need to talk to developer to finalize the design. I had given recommendations to the intern who was working on it.

**Comment by medzneel** [comment]
UX spec due - 12/04/2020

**Comment by Manurod2018** [comment]
Visuals are on Zeplin: https://zpl.io/2ENnmAY
Please select the tag  "#9274" which is the ticket number of that feature to see all related screens.
