### ISSUE TITLE
UX for B2B Future Stock (S)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9275]
https://cxwiki.sap.com/display/spar/Feature%3A+B2B+Future+Stock

**Comment by jeannewalters** [comment]
@Xymmer Assigned to you until features are ready.

**Comment by Xymmer** [comment]
ready

**Comment by jeannewalters** [comment]
Manu will finish by 11/06. Will include review on Friday.

**Comment by Manurod2018** [comment]
See visuals on Zeplin: https://zpl.io/aBrNX1O

**Comment by medzneel** [comment]
Spec will be done by nov 20,2020

**Comment by medzneel** [comment]
UX Spec will be done by 20,2020
