### ISSUE TITLE
Search field does not disappear on mobile

### ISSUE THREAD

**Issue by PascalAOMS** [SAP/spartacus#9284]
**Describe the bug**
Viewport: XS
Component: Search field
Issue: When having text in the search input field, resetting it via the X button and typing in something new, the search field does not disappear when clicking outside of the component.

**To Reproduce**
1. Go to the start page in XS mobile view.
2. Click on the search icon.
3. Type in some text.
4. Delete the text by using the X button in the input field.
5. Type in some new text.
6. Click outside the component.

**Expected behavior**
The search field disappears again.

**Desktop**
 - OS: Windows
 - Browser: Chrome
 - Version: 85

**Comment by LTiger14** [comment]
PR #9380

QA: 
1. Open spa in mobile view (real phone is best)
2. Type some text
3. Click the reset button
4. **The focus should remain on the input**
5. Click away, the searchbox should be closed
6. The clear and search should still work as before on all screen sizes
