### ISSUE TITLE
“Continue" button in Delivery Mode can lead to duplicate http requests when clicked multiple times

### ISSUE THREAD

**Issue by wangzixi-diablo** [SAP/spartacus#9294]
**Environment Details**
Spartacus: develop branch
Browser: Chrome
Device OS: Windows 10 desktop
Happens on: https://spartacus-dev0.eastus.cloudapp.azure.com:9002

**Steps to Reproduce**
- On chrome, login as a customer. 
- Add a product to cart and trigger checkout process
- Proceed to Delivery Mode step
- Open Chrome development tool, switch to Network tab.
![image](https://user-images.githubusercontent.com/58975336/95735965-289fa900-0cb8-11eb-8fbc-fa62b0783aee.png)
- Press "Continue" button repeatedly in a short time, you can observe there're multiple http requests fired and sent to backend.
![image](https://user-images.githubusercontent.com/58975336/95736222-846a3200-0cb8-11eb-963e-911e78e325f0.png)

This issue only exists in the "continue" button in Delivery Mode step. In Shipping Address and payment details page, the continue button could only be pressed once. 

**Expected Behavior**

Continue button in Delivery Mote page should behave consistently with the one in shipping address page and payment detail pages.

**Comment by giancorderoortiz** [comment]
Retest on qa server done. 
http://cx-qa16181492.eastus.cloudapp.azure.com:4200/electronics-spa/en/USD/

I see a few deliverymode calls being made. However, this may be due to intermittent issues we'd had with this page not loading properly. 

Retried a few times.  Found no errors. 👍

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-25 at 11 23 47 AM](https://user-images.githubusercontent.com/46171897/97111394-cc278b00-16b4-11eb-9b94-01cf5ea8cf0c.png)
