### ISSUE TITLE
Create new banners for electronics home

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9329]
- [x] devs need to provide size info to Manu
- [x] Manu needs to provide the images (getting approvals)

**Comment by Manurod2018** [comment]
Banners are here on Teams: 
https://teams.microsoft.com/_#/files/Visual%20Refresh%20Fall%202020?threadId=19%3Aa6d5899054a044bcb194911edae0819d%40thread.tacv2&ctx=channel&context=Visual%2520Refresh%2520Fall%25202020&rootfolder=%252Fteams%252FSPAMobileStrategy%252FShared%2520Documents%252FVisual%2520Refresh%2520Fall%25202020
Or Sharepoint:
https://sap.sharepoint.com/teams/SPAMobileStrategy/Shared%20Documents/Visual%20Refresh%20Fall%202020

**Comment by Xymmer** [comment]
task of adding to sample data is #9517

**Comment by giancorderoortiz** [comment]
@Manurod2018 please grant me access to sharepoint to view these files.
