### ISSUE TITLE
[Med] Group status not correct after solving conflict

### ISSUE THREAD

**Issue by MichaelBoeser** [SAP/spartacus#9330]
Server: team server
Configure WEC_COLOR_TEST.
Cause two conflicts in group general:
select color: blue and object type 1: traffic light.
Select Cause Restriciton Conflict: true.
Navigate to conflict group Conflict for Object Type 1.
Resolve the conflict by selecting rainbow.
Issue: group general is shown as completed, although it still contains an issue.
when you click on general in the menu, the staus switches to error.

**Comment by ChristophHi** [comment]
Still not intuitive.
Select Color: blue
Select Object Type 1: Traffic Light
Click 'Next' and 'Previous'
Select Object Type 1: Rainbow
-> Icon for group 'General' changes to attention while it should be completed
Select Object Type 1: Traffic Light
-> Icon for group 'General' changes to completed while it should be attention

**Comment by steinsebastian** [comment]
Seems to be independent from the change. I'll look into it.
