### ISSUE TITLE
(my-comp) Creating a user without any roles leads to issues when using said user

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9332]
**Describe the bug**
In my-company/users, it's possible to create a user with no roles. When you log is with this user the "my-account" drop down is missing.

**To Reproduce**
1. Login as administrator
2. Go to my-company -> users
3. Click add
4. Create a user without roles
5. Login as user
6. See error

**Expected behavior**
No errors when using the user.

**Screenshots**

<img width="235" alt="image" src="https://user-images.githubusercontent.com/10605724/96017642-3bc98a80-0e18-11eb-8d77-4d239df1a2b4.png">

<img width="134" alt="image" src="https://user-images.githubusercontent.com/10605724/96017657-41bf6b80-0e18-11eb-8b3a-eb0ee11e57a1.png">

**Desktop (please complete the following information):**
 - Mac os
 - Firefox 82

**Comment by Xymmer** [comment]
Let's improve the user experience when a non-roled user logs in; however we won't prevent users from not having roles. If we were to do so, it would be at api level.
i.e. can we identify these circumstances and provide a better message? like 'contact your admin', only b2b, etc.

**Comment by Pucek9** [comment]
@Xymmer Could you verify that it's ok now?
![image](https://user-images.githubusercontent.com/8040837/109651747-39659400-7b5f-11eb-9787-b998ddcc5a3f.png)
![image](https://user-images.githubusercontent.com/8040837/109654174-286a5200-7b62-11eb-880c-ba189e67d52c.png)
