### ISSUE TITLE
Can't create a budget on Firefox [due to date/time picker?]

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9333]
**Describe the bug**
On Firefox the date pickers are inputs, inputting any value in these inputs gives many errors in the console and the budget cannot be created.

**To Reproduce**
1. On Firefox
2. Login as Administrator
3. Go to my-company -> budgets
4. Click "Add"
5. Fill form with the console open

**Expected behavior**
I can add a budget on Firefox

**Screenshots**
<img width="200" alt="image" src="https://user-images.githubusercontent.com/10605724/96018654-88fa2c00-0e19-11eb-83f3-a31e1619c2de.png">
<img width="164" alt="image" src="https://user-images.githubusercontent.com/10605724/96018662-8ac3ef80-0e19-11eb-89c4-18935330a7b0.png">
<img width="495" alt="Screen Shot 2020-10-14 at 12 36 40 PM" src="https://user-images.githubusercontent.com/10605724/96018996-edb58680-0e19-11eb-839a-11f729f2eba5.png">

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Firefox 82

**Comment by tobi-or-not-tobi** [comment]
Unfortunately we haven't checked the browser support for the usage of the datetime picker. 
See:
- https://caniuse.com/?search=datetime
- https://caniuse.com/?search=datetime-local

**Comment by Xymmer** [comment]
"should" work but maybe needs tweaking for Firefox pecularity.
Then test other browsers.
If it looks like we need to use a library instead of built-in picker, talk to Tobias.

**Comment by tobi-or-not-tobi** [comment]
We've discussed this issue:
- we should fallback to text field(s) in case of a lack of browser support. We won't introduce a external lib for this feature. 
- we should try to avoid 2 text fields, one for date, one for time. Ideally we drop time altogether, but we see the potential conflict with timezone differences. @Xymmer can you make the decision regarding time zone here? 

Option 1: no timezones
- the user will not input a time, we fallback to a default time. The default time will differ from region to region, which could mean that if 2 users create a budget, they might have various results. It's not necessarily a blocking issue. 
- the user will input the time, next to the date. The time represents his time, but if another user opens it, it will translate to his timezone. The main disadvantage is complexity (ux and dx)

**Comment by Xymmer** [comment]
Decision:
- don't ask user for time
- default to midnight from user's timezone, if you can guess his timezone
