### ISSUE TITLE
Form is frozen while getting error response (e.g. conflict) (general fix)

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9351]
**Describe the bug**
Error Message “Already Exists” when adding a new user with an email address that was already used by a previous user. The alert message does not indicate which information “Already Exists” and the whole form is disabled.

**To Reproduce**
1. Go to My Company > Users
2. Try to add a new user with an email that was already used by another user.
3. Observe the Alert, form state 

**Expected behavior**
The alert message should be more descriptive “A User Already exists with the email address used. Please provide a different email address”

The form should still be editable so that the user can change the email address and try to save it again. The only way to move forward from here is to cancel out of the create user form and start again by reentering all the information again

**Screenshots**
<img width="1222" alt="Screen Shot 2020-10-12 at 10 22 38 AM" src="https://user-images.githubusercontent.com/15215400/96150434-f6689400-0ecf-11eb-9d3a-9118751cee95.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 85.0.4183.121

**Comment by Xymmer** [comment]
1. Fix the bug where if an email already exists, the form should remain editable - unfreeze the form when receiving fail error.
2. If there is a way to improve the message, do so; otherwise that's improvement.

Real improvement would come when we tackle error handling refactoring.

**Comment by Pucek9** [comment]
For edit form, changing purchase limit type should be disabled.

**Comment by Pucek9** [comment]
> 1. Fix the bug where if an email already exists, the form should remain editable - unfreeze the form when receiving fail error.
>
Confirmed. It should be unfreezed for every form and any backend error, not only that case.
> 2. If there is a way to improve the message, do so; otherwise that's improvement.
> 
I checked and we recognizes http errors without context, it uses only code from response as key (`httpHandlers.conflict`) so that could be really problematic. Lets descope that issue and create that part as stretch improvement
