### ISSUE TITLE
[dupe] No Active state when updating user roles 

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9352]
**Describe the bug**
When editing USER ROLES of ASSIGNED USERS for a given Unit, The UI does not indicate which user is selected, and minor Styling issue with overflow text.

**To Reproduce**
1. Go to My Company > Units and click on "+" Create a unit 
3. Add multiple users to a unit 
Go to My Company Home > Units > Unit with multiple users > User > Click on roles of any user from the list to reveal the "USER ROLES" panel  
4. Switch between users and observe no active/selected state is set on a user that is being clicked on 

**Expected behavior**
ASSIGNED USERS panel should indicate which user is selected by setting an active state on the selected row

Text overflow should be truncated with ellipses (...) 

**Screenshots**
<img width="1136" alt="Screen Shot 2020-10-12 at 10 19 56 AM" src="https://user-images.githubusercontent.com/15215400/96151605-3b40fa80-0ed1-11eb-97eb-2e87a714be75.png">

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 85.0.4183.121

**Comment by Xymmer** [comment]
1. Fix highlight that is missing from left panel

2a. Check with the team if someone is fixing the "text too long" b2bmanager... etc. (might already be a bug reported)
2b. Check if we can display actual role names instead of "b2bmanager, b2badmin" etc. in left column.

**Comment by Pucek9** [comment]
> 1. Fix highlight that is missing from left panel
> 
ticket created here: #9399
> 2a. Check with the team if someone is fixing the "text too long" b2bmanager... etc. (might already be a bug reported)
> 2b. Check if we can display actual role names instead of "b2bmanager, b2badmin" etc. in left column.
>
Out od date + #9214
![image](https://user-images.githubusercontent.com/8040837/96462715-2c867a80-1226-11eb-986f-5c764dca3ceb.png)

**Comment by Pucek9** [comment]
Assigning issue will be solved in #8999

**Comment by Pucek9** [comment]
Closed as we have tickets for that already.
