### ISSUE TITLE
Sort lists by name if possible, otherwise by code

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9353]
**Is your feature request related to a problem? Please describe.**
The unit list order is random even though they were added in sequence unit 1, unit 2, unit 3 ...

**Side note:** There is a related issue with sorting by the unit on the Budgets list view where when you sort the list by Unit, nothing happens 

**Describe the solution you'd like**
Unit order should be sorted by date added 

**Steps to recreate**
1. add multiple Units and use a number in Unit Name to keep track of the order in which they were added 
2. notice the list is not sorted correctly 

**Additional context**
<img width="277" alt="Screen Shot 2020-10-12 at 11 58 40 AM" src="https://user-images.githubusercontent.com/15215400/96152475-3466b780-0ed2-11eb-8e6c-fbfb5bcedaee.png">

**Comment by Xymmer** [comment]
sort alphabetically would be nice but i think we display just what we get from backend
if it's work on spartacus side, make this stretch

**Comment by Pucek9** [comment]
@Xymmer 
It is possible, but not nicely. Should we sort by code or name? We display it as we received from backend. All other lists are sorted on backend side (API allows for that) so ideally that improvement will be done on backend side.

**Comment by Xymmer** [comment]
by name
