### ISSUE TITLE
Purchase limit update not working

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9354]
**Describe the bug**
When updating a purchase limit's details, only code values are saved. Type and Parent Unit changes are not being saved. 

No alert indicating if the update was completed successfully. 

**To Reproduce**
1. Go to My Company > Purchase Limits
1. Add a Purchase Limit if there is none
2. Edit, update all values, and save the Purchase Limit
3. Observe only the code value was saved and Type did not update. Also, there was no success/error message that was displayed.

**Expected behavior**
When updating a purchase limit, all values should be saved including Code, Type, and Parent Unit.

An alert should be displayed with the proper state (success/error) 

**Screenshots**
![Screen Shot 2020-10-15 at 10 50 20 AM](https://user-images.githubusercontent.com/15215400/96154448-6e38bd80-0ed4-11eb-825a-66cbd1be72db.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  85.0.4183.121

**Comment by Xymmer** [comment]
Please repro and fix if needed

**Comment by Pucek9** [comment]
Permission type should be disabled in edit form
