### ISSUE TITLE
Still able to checkout with a disabled account

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9358]
**Describe the bug**
Still able to checkout with a disabled account

**To Reproduce**
1. Login as b2b admin (i.e. linda.wolf)
2. Go to Users 
3. Click on an existing user and disable the account
4. In a browser's private mode login with the disabled account and checkout 
5. Observe that there are no warnings or alerts indicating that the account is disabled and you are still able to place orders. 

**Expected behavior**
Should not be able to checkout with a disabled account
GC -> User shouldn't be able to login with a disabled account. 

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  85.0.4183.121

**Comment by giancorderoortiz** [comment]
Unable to reproduce with b2c. After account is closed, user is not able to login anymore.

**Comment by giancorderoortiz** [comment]
Able to reproduce with b2b! 
Changing priority to blocker.

**Comment by giancorderoortiz** [comment]
Account is in fact disabled by Spa powertools. Using Marie Dubois account. 
Spa view: 

![Screen Shot 2020-10-16 at 7 35 55 AM](https://user-images.githubusercontent.com/46171897/96254866-0477ec80-0f84-11eb-8c6f-3945e0ebf87b.png)

Old Acc View: 
![Screen Shot 2020-10-16 at 7 46 03 AM](https://user-images.githubusercontent.com/46171897/96254995-325d3100-0f84-11eb-92e9-a40919ba9412.png)

**Comment by giancorderoortiz** [comment]
Old Accelerator blocks login to disabled account: 

![Screen Shot 2020-10-16 at 7 53 46 AM](https://user-images.githubusercontent.com/46171897/96255378-d2b35580-0f84-11eb-84b2-61084fde9e9b.png)

**Comment by giancorderoortiz** [comment]
Spartacus allows login of disabled account: 

![Screen Shot 2020-10-16 at 7 56 33 AM](https://user-images.githubusercontent.com/46171897/96255734-684ee500-0f85-11eb-8dbc-5a2866d560b8.png)

![Screen Shot 2020-10-16 at 7 56 23 AM](https://user-images.githubusercontent.com/46171897/96255752-6f75f300-0f85-11eb-8c60-224d10994b1f.png)

**Comment by giancorderoortiz** [comment]
@hackergil, @Xymmer , @zebercut fyi.

**Comment by giancorderoortiz** [comment]
@meeque fyi

**Comment by Xymmer** [comment]
1. Dev, please check if this is front-end or backend issue. Could be that it's a non-b2b user using powertools endpoint? or b2b user using core/b2c endpoint? (talk to Stan)
2. If backend, create jira ticket in CLC project (Zeppelins), make sure Bill knows
3. If confused, arrange meeting with Stan, GC, Bill, Tobias

**Comment by LTiger14** [comment]
This is a backend issue. A meeting is schedule to propose a solution; will keep this issue up to date.

**Comment by LTiger14** [comment]
The back-end ticket is https://cxjira.sap.com/browse/CLC-2219. Once back-end change is done, this Spartacus issue can be worked on #9516.

Removing myself as this is a future issue.

**Comment by giancorderoortiz** [comment]
Recheck with 3.0

**Comment by giancorderoortiz** [comment]
Unable to reproduce with Spartacus 3.0
![Screen Shot 2021-06-08 at 1 27 18 PM](https://user-images.githubusercontent.com/46171897/121230813-b50d6600-c85d-11eb-96b7-813d112cc6d8.png)


User is not able to login after it's disabled. 
Hence, he can't checkout.
