### ISSUE TITLE
Approval action buttons are not semantic in style

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9359]
**Describe the bug**

**To Reproduce**
1. Login as an approver
2. Go to approval Dashboard and open a pending order 
3. Observe that both Reject and Approve action buttons are the same color. 

**Expected behavior**
Action Buttons should be semantic. 
 - Red for Reject Order 
 - Green for Approve Order 

**Screenshots**
![Screen Shot 2020-10-13 at 3 45 32 PM](https://user-images.githubusercontent.com/15215400/96159656-86134000-0eda-11eb-8f4a-aaea5b364592.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version:  85.0.4183.121

**Comment by plabadie** [comment]
One element to consider in this case is that the "main" buttons are red everywhere in the storefront as defined in the theme.

**Comment by plabadie** [comment]
The approval/rejection form has 3 states, this might be considered when planning a potential change:

<img width="1226" alt="Screen Shot 2020-10-19 at 12 23 41 PM" src="https://user-images.githubusercontent.com/7065346/96479015-6051a800-1206-11eb-883d-94b681fef9f0.png">

<img width="1217" alt="Screen Shot 2020-10-19 at 12 23 36 PM" src="https://user-images.githubusercontent.com/7065346/96479032-6778b600-1206-11eb-9f04-d1ebb7bf90d1.png">

<img width="1261" alt="Screen Shot 2020-10-19 at 12 23 27 PM" src="https://user-images.githubusercontent.com/7065346/96479043-6a73a680-1206-11eb-94c6-c86232fcb9cf.png">

**Comment by developpeurweb** [comment]
@Manurod2018 based on Patrick's previous comments, this doesn't seem to me like a bug since we don't have "green buttons", in fact, we only have 3 types of buttons:

![Screen Shot 2020-10-19 at 12 50 39 PM](https://user-images.githubusercontent.com/15113219/96482226-bd9b2880-1209-11eb-84c6-df59ddb0eff5.png)

I think both primary buttons are needed because they're part of the following alternative steps as explained by Patrick.
Can we please have a designer's final say on this issue?

**Comment by Manurod2018** [comment]
Correct, both buttons are primary here, we don't have green or red buttons. Attached is the styling for buttons on the B2B storefront.

![buttons](https://user-images.githubusercontent.com/37299626/96505786-a0278800-1224-11eb-9073-8cce5e790bfe.png)

**Comment by developpeurweb** [comment]
@Xymmer closing ticket, since this is not an issue. 
Nothing to QA.
