### ISSUE TITLE
Replenishment Styling (Checkout)

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9363]
WIthin the replenishment order area inside checkout, the following styling issues will reduce the height of the area and bring the Place Order up on the page:
- when Every Month is selected, move "On this day <Field>" up next to Every Month
- When Repeat on the following days is displayed, tighten up the spacing between days.

**Comment by morganm58** [comment]
The text "On this Day" has been changed to "On Day" 
Before fix
<img width="431" alt="Screen Shot 2020-10-29 at 2 33 19 PM" src="https://user-images.githubusercontent.com/2947470/97617306-f9957100-19f3-11eb-8222-e36ba2523029.png">

<img width="391" alt="Screen Shot 2020-10-29 at 2 32 33 PM" src="https://user-images.githubusercontent.com/2947470/97617478-35303b00-19f4-11eb-8009-c674d7230f43.png">

After fix
<img width="409" alt="Screen Shot 2020-10-29 at 1 56 26 PM" src="https://user-images.githubusercontent.com/2947470/97617616-5b55db00-19f4-11eb-8d35-4d084b266da0.png">
<img width="400" alt="Screen Shot 2020-10-29 at 2 58 02 PM" src="https://user-images.githubusercontent.com/2947470/97619948-3e6ed700-19f7-11eb-88a5-90facf71b209.png">

**Comment by morganm58** [comment]
For QA:

Login as william.hunter@rustic-hw.com
Add item to the cart and start the check out process
On Review Order page in the check out process "Auto Replenish Order" is where you will find the changes that were made
Select month(s) and week(s) in the drop down to see the changes.

**Comment by giancorderoortiz** [comment]
Changes seen.
![Screen Shot 2020-10-30 at 8 53 21 AM](https://user-images.githubusercontent.com/46171897/97707359-8dffe200-1a8d-11eb-9c83-f6c4c780f024.png)
![Screen Shot 2020-10-30 at 8 54 05 AM](https://user-images.githubusercontent.com/46171897/97707361-8f310f00-1a8d-11eb-92b9-82d4bd1a40c1.png)

ok

**Comment by giancorderoortiz** [comment]
With Firefox:

![Screen Shot 2020-10-30 at 9 00 25 AM](https://user-images.githubusercontent.com/46171897/97707966-6e1cee00-1a8e-11eb-953d-78686bc6f6a7.png)
![Screen Shot 2020-10-30 at 9 00 40 AM](https://user-images.githubusercontent.com/46171897/97707971-6f4e1b00-1a8e-11eb-819d-a80c9adf8413.png)
