### ISSUE TITLE
Replenishment Order Table and Replenishment Order History (Detail) Styling

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9364]
Replicate the styling from the My Company lists to the Replenishment Order table and Replenishment Order History table on the Details page.
This includes:
- hover state of the line
- styling of links

**Comment by Xymmer** [comment]
we need more specific info,
often we break tasks into smaller tickets for must-do now vs later
also replicating my company style to everywhere else is not something we will do just to replenishment but i assume everywhere, unless i'm misunderstanding

**Comment by jeannewalters** [comment]
On hover of the line in the table in My Company, there is a state on it that shows you can click it. Also styling of links is different as well within the My Company section. To your point, this would apply to all tables/lists in My Account to align with My Company. Brian mentioned Order History because that is what he used to create Replenishment Orders.
