### ISSUE TITLE
Details page load action firing when navigating outside of the page.

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#9367]
Found when working around with Replenishment.

Basically, when entering a detail page, we have a subscription, where we get the router state for it's params. However, when leaving the page by clicking anything like going to a product category page, we can see a load action for the detail page being fired, therefore re-populating the details state.

As an example,
- go to replenishment history and go to any replenishment order details
- go to a product category of your choice using the navbar
- go back to replenishment history
- go back to a a product category of your choice using the navbar
- go to order history page, and you will find the replenishment history header because the state valu for replenishment details which was supposed to be cleaned.

Same case for order details.

**Comment by bgambocjaviniar** [comment]
PR: GH-9379

QA:

use dev0-azure and set your environment b2b property to true

below is to check replenishment details but you can also check order details
1st test:
1 - open redux tool, and keep an eye on the actions
2 - navigate to a replenishment detail
3 - verify when navigating out of the page by going to homepage or anywhere else, it won't fire a `load replenishment order details` action

2nd test:
1 - navigate to a replenishment detail
2 - navigate to order history page
3 - verify that the header displays `order history` and not `replenishment history`

**Comment by giancorderoortiz** [comment]
ok. Fix seen. 

![Screen Shot 2020-10-30 at 12 31 05 PM](https://user-images.githubusercontent.com/46171897/97731773-f067db00-1aab-11eb-9efb-ec1da3fdb3ff.png)
![Screen Shot 2020-10-30 at 12 31 12 PM](https://user-images.githubusercontent.com/46171897/97731775-f1007180-1aab-11eb-9247-e3622c784769.png)
![Screen Shot 2020-10-30 at 12 31 40 PM](https://user-images.githubusercontent.com/46171897/97731776-f1007180-1aab-11eb-96b0-0e3bddcce245.png)
![Screen Shot 2020-10-30 at 12 31 48 PM](https://user-images.githubusercontent.com/46171897/97731777-f1007180-1aab-11eb-9cda-0c8978c64324.png)
