### ISSUE TITLE
My Company - Wrapping issue for users with more than one user group assigned

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9369]
When user has more than one user group, we need to better accomodate for the display of more than one user group. Options below:
1)  the line height must grow to accommodate one user group per line
2)  display as Usergroupname, # more 
3) display as Usergroupname, ...

![image](https://user-images.githubusercontent.com/24274321/96183332-59702000-0efc-11eb-8d20-974590632892.png)

**Comment by tobi-or-not-tobi** [comment]
duplicate, fixed with #9050. We've also changed the approach (we basically now align with UX screens), where this screen would have a link "roles" that links you to the page where you can control those roles.
