### ISSUE TITLE
My Company - Breadcrumbs

### ISSUE THREAD

**Issue by jeannewalters** [SAP/spartacus#9370]
The following breadcrumb styling should be updated to have the first letter capitalized for each word and there should be a "/" after the last link.

Home / Organization / All Budgets /
Home / Organization / All User Groups /
Home / Organization / All Users
Home / Organization / All Purchase Limits /
Home / Organization / All Cost Centers /

![image](https://user-images.githubusercontent.com/24274321/96183990-6a6d6100-0efd-11eb-8331-0a1178ec0be5.png)

**Comment by tobi-or-not-tobi** [comment]
@jeannewalters 
Agreed on the capitalizing the first letter of each breadcrumb. 
I'm just surprised about the trailing slash. I do not see as a standard approach on storefronts, nor on other apps. I always thread the slash as a delimiter, not as a directory system. Often the breadcrumbs are shown as `Home > Organization > Cost centers`, where the delimiter visualizes the navigation flow.

**Comment by jeannewalters** [comment]
@tobi-or-not-tobi If the page is the current page, it wouldn't have a slash, but our case, where it's the previous page, it should have the / and then the title of the page acts as the next level.
