### ISSUE TITLE
My Company - Units screens styling

### ISSUE THREAD

**Issue by Manurod2018** [SAP/spartacus#9378]
Styling work is needed, please refer to the Zeplin links: 
https://zpl.io/aXB96P8
https://zpl.io/bPe3kvm

**Comment by Xymmer** [comment]
@Manurod2018 could you work with Miguel on defining exactly what changes are must-do vs stretch?

**Comment by developpeurweb** [comment]
@Xymmer if dev work is needed they can start, although the final look and feel (mainly colors) won't kick-in until the "blue theme" is ready. 
Please advise and label accordingly.

**Comment by Manurod2018** [comment]
just adding the current screenshot as reference

![Units screens styling](https://user-images.githubusercontent.com/37299626/96470629-7eb2a600-11fc-11eb-923d-82b0a8ff3c57.png)

**Comment by morganm58** [comment]
![Screen Shot 2020-10-26 at 1 21 00 PM](https://user-images.githubusercontent.com/2947470/97205774-4546e100-178e-11eb-921a-b5f28210a1db.png)

**Comment by morganm58** [comment]
@Manurod2018 I just took a look at this. I looks fine in develop.
