### ISSUE TITLE
B2B config file for cypress

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9381]
We need to create a b2b config file, so that we can just pass in this config instead of passing cypress environment variables as params in the package script.

**Comment by bgambocjaviniar** [comment]
PR: GH-9969

QA:
- make sure you're pointing to dev0-azure
- make sure the environment is set to true for B2B

*** note: technically there shouldn't be any errors when running it but I took a quick glance and noticed there are some errors which is related to 'tokens'/'access_tokens', therefore some of these e2es were not updated with our session management. --> should be addressed in another ticket
**- verify results for the b2b tests. Make sure the result is the same/similar from develop and in this branch using `yarn e2e:cy:run:b2b` on both**

**Comment by plabadie** [comment]
22 vs 21 errors between develop and the feature branch.  There does not seem to be a big regression.
