### ISSUE TITLE
[On hold] Switch Backend used by CI. Dev0 -> US Load Balancer

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9395]
Stop the usage of Dev0 as sole backend used by CI to run e2e smoke and regression tests. 
Instead switch to a new load balancer already deployed. 
Load balancer has at least 3 VMs deployed in different availability zones (i.e. data centers). 
(https://github.com/SAP/spartacus/issues/8895)

**Phase 1:** 
To do for each VM in back-pool before switching (GC)
1. Disable from load-balancer. 
2. Confirm update has been done in each VM with latest sample data. 
3. Run e2e smoke tests pointing directly to VM.  
4. Re-enable in load-balancer. 

**Phase 2:** 
1. Run e2e smoke, regression and mobile tests using load balancer.  (GC)
1.a. Results MUST be equivalent to dev0. (i.e. not 100% equal, but at least 95% the same results. Counts for some minor variations in tests execution). 

**Phase 3:**  (Gil)
1. Switch in CI. Remove dev0. Use load balancer IP. 
2. Force running smoke and regression tests. 

VM Details in wiki page.

**Comment by giancorderoortiz** [comment]
A 4-6 hour downtime is possible during this switch. @Xymmer, @zebercut

**Comment by giancorderoortiz** [comment]
Updated cxci1,2,3 ✅

**Comment by giancorderoortiz** [comment]
Smoke test results:
cxci1  https://dashboard.cypress.io/projects/k3nmep/runs/5336

cxc2 https://dashboard.cypress.io/projects/k3nmep/runs/5337

cxc3 https://dashboard.cypress.io/projects/k3nmep/runs/5338

Load - balancer:
https://20.55.3.176/occ/v2/swagger-ui.html

https://dashboard.cypress.io/projects/k3nmep/runs/5340


Checkout test fails. however, this is an internal issue, not related to deployments per-se

**Comment by zebercut** [comment]
Closing the ticket. It is related to schematics which is in progress: https://github.com/SAP/spartacus/issues/7965

**Comment by hackergil** [comment]
Reopening. This is different than #7965

**Comment by giancorderoortiz** [comment]
:-)

**Comment by hackergil** [comment]
I created a PR to run the e2es using the new cluster as backend. I found a couple things:
- New passwords are being used for our test users (asagent, cypress users). This fixes asm and consignment tracking orders e2e tests)
- My interests e2e test is still broken

**Comment by plabadie** [comment]
Run form the feature branch is green https://jkmaster.test.c3po.b2c.ydev.hybris.com/job/spartacus-regression-tests-for-branch/455/

**Comment by hackergil** [comment]
I am seeing a couple of inconsistencies with the LB. First of all, I can’t make the tests pass but locally I can’t make them fail. Second, I’ve had an inconsistent error with checkout where the SOP mock does not respond

We have to review each one of the cluster instances configuration. Also, let's make sure that the load balancer manages sticky sessions correctly.

Let's hold off the switch for now and revisit after 3.0.

**Comment by hackergil** [comment]
In the end we did not use the LB so closing this one
