### ISSUE TITLE
My company Accesibility check

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9398]

**Comment by kacperknapik** [comment]
### Pages
- [x] main organization page
  - improvement - fix transition on the elements for focus #9526
- [x] organization/budgets page
- [x] organization/cost-centers
- [x] organization/units
  - improvement - fix top right buttons being too close #9527
  - improvement - fix focus border in rows with accordion #9528
- [x] organization/users
- [x] organization/user-groups
- [x] organization/purchase-limits

### General
- improvement - focus newly opened section in table component #9531
- bug (mvp) - focus trap on shift-tab inside the table #9532
