### ISSUE TITLE
Powertools add to cart with quantity > 1 does not work.

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#9409]
Steps to repro:
* Use the b2b Powertools store
* Go to the product details page of one product
* increase the qty to more than one
* add product to cart

expected result: the desired qty is added to cart
observed result: qty 1 is added to cart, regardless of the qty chosen on the pdp

**Comment by plabadie** [comment]
PR #9429

To test:
- see the description for the use case to test
- Also, make sure add to cart in b2c still works well for quantities.

**Comment by giancorderoortiz** [comment]
This is indeed the case. Wow.

**Comment by giancorderoortiz** [comment]
Easily reproducible in QA server here: 
http://cx-qa16181492.eastus.cloudapp.azure.com:4201/powertools-spa/en/USD/

**Comment by giancorderoortiz** [comment]
Added an e2e test improvement ticket for this: https://github.com/SAP/spartacus/issues/9525

**Comment by giancorderoortiz** [comment]
I see the fix. 

Before: 
![Screen Shot 2020-10-30 at 12 47 06 PM](https://user-images.githubusercontent.com/46171897/97733366-1bebc500-1aae-11eb-952e-21647751dd37.png)

---
After: 
![Screen Shot 2020-10-30 at 12 47 15 PM](https://user-images.githubusercontent.com/46171897/97733394-24dc9680-1aae-11eb-9adc-c7509d6b7b4b.png)
