### ISSUE TITLE
Move order-approval from administration one level up

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#9423]
In https://github.com/SAP/spartacus/issues/9340 we renamed the my-account library to organization.

In this ticket we should:

- move the order-approval up, as it's not an administrative task.
- This implies creating an entry point for the _order-approval_ - `@spartacus/organization/order-approval`.
- Check if `RouterModule.forChild` can be dropped from `feature-libs/organization/administration/root/organization-root.module.ts`.
- Check if it's easy enough to lazily load the _order-approval_ feature. This can be tackled in a follow up ticket (please create it so that we don't forget about it).

At the end, the library structure should look like this:

```text
- organization
   - administration
   - order-approval
```

**Comment by plabadie** [comment]
PR #9499

For tests, this is a refactoring, so no regression should happen on the approvals feature.
The goal of the ticket is to crate an entry point for approvals to either run my company without approvals or vice versa.
So 2 tests that could be done are:
- Test my-company without approvals loaded in the app.
- Test approvals without my-company loaded in the app.
