### ISSUE TITLE
Close added-to-cart modal using modal directive

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9428]
Currently the Added-to-cart modal needs to be closed explicitly using its dismissModal() method. It's now required when:
1. item counter goes down to 0 (item removed) OR
2. any navigation link is clicked (even in nested components like cart-item.component or its children)

But the cart-item.component and deeply-nested children have no business to know they are projected in a modal or not. Therefore they shouldn't be obligated to explicitly close a modal when clicking some link inside those components.

~Instead, we should automatically detect router navigation and close the added-to-cart modal when the router event happens.~

It's a breaking change required in 3.0. It will help get rid of unnecessary outputs (public-api) from cart-item.component, which cause problems when adding outlets inside cart-item.component for Product Configurator feature (which is likely coming in next minor releases).

**Comment by Platonn** [comment]
### QA steps:
1. go to any PDP. i.e. http://localhost:4203/electronics-spa/en/USD/product/1981415/PL60%20Silver
2. add product to cart
3. observe opened modal
4. verify the modal is closing when:
   a) clicking `View cart`
   b) clicking `Proceed to checkout`
   c) clicking `Remove` button in the left-botom corner of the modal
   d) clicking `x` icon of modal or the general gray overlay
   e) clicking the product name or image (which are links to PDP)

**Comment by Platonn** [comment]
> Instead, we should automatically detect router navigation and close the added-to-cart modal when the router event happens.

QA showed that it doesn't work for links to PDP, when you're already on PDP (due to angular avoiding re-load of navigation when link points to the current page).
So implemented a new `cxModal` directive for closing modals on links explicitly.

**Comment by giancorderoortiz** [comment]
Test successful. 
Tested with Chrome, FF, Edge. 
Behaves as expected after fix.
