### ISSUE TITLE
Broken page template styles

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9440]
After fixing #9239 for the next release, we've introduced a bug; the `cxPageTemplateStyle` directive that is introduced to control the page template driven css class is interacting with the native `el.classList` and is therefor missing out on change detection.

There is btw a good reason to not use HostBinding in this case (which would have bring change detection for free).

**Comment by tobi-or-not-tobi** [comment]
still happening.

**Comment by bit-dragon** [comment]
My organization section is still broken.

@spartacus v3.0.0-next.6
Browser: Chrome 86.0.4240.111

 ![section](https://user-images.githubusercontent.com/1533108/97042214-4f6ea280-1536-11eb-8830-b8188eb2adf4.PNG)
