### ISSUE TITLE
[HOLD] Run regression tests on CCv2

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9461]
Run regression tests on CCv2 to make sure everything is working on 3.0-RC running on PM2

We already have a Jenkins job for it. It needs to be updated to use the new CCv2 once it's ready to go.

Depends on #7648

**Comment by Xymmer** [comment]
we can't do this yet
- ccv2 needs our special sample data
- we probably want the tests to run as a js app in ccv2, we haven't done that yet
- we need a dedicated ccv2 server for this or another environment within our spartacus ccv2

**Comment by giancorderoortiz** [comment]
No plans to do this yet. 
CCV2 not configured for regression testing. 
Revisit for 4.0 if necessary
