### ISSUE TITLE
Lazy loading causes SSR flickering

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#9468]
When lazy loaded feature exists on a page, SSR may flicker.

We should reproduce this behavior and fix it if possible.

**Comment by giancorderoortiz** [comment]
@dunqan  Please provide me with steps to reproduce. Interested.

**Comment by dunqan** [comment]
QA steps:
It's best to use customizations from `qa-9468` brach
(https://github.com/SAP/spartacus/compare/qa/gh-9468?expand=1)

In case the page contained lazy loaded components from lazy loaded feature modules, there was noticable flickering when transitioning from SSR to CSR.

1.  Run the customized app 
2. Test if there is a fickering (full repaint with white screen)
3. It's possible to use performance monitor tab from chrome dev tools to record the view and examine it

**Comment by giancorderoortiz** [comment]
Blocked pending successful deployment of B2B in SSR mode in Linux dev servers.

**Comment by giancorderoortiz** [comment]
No flickering observed after fix. 👍 
SSR loading very fast.
