### ISSUE TITLE
Fix cypress configurations to let smoke/checkout-flow.e2e-spec.ts pass

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9477]
In https://github.com/SAP/spartacus/commit/13fb92afdd44b38e6953b5f47eae2e048d0ba0ac we introduced  2 env variables which became mandatory for `smoke/checkout-flow.e2e-spec.ts` to pass:
```
"OCC_PREFIX_USER_ENDPOINT": "users",
"OCC_PREFIX_ORDER_ENDPOINT": "orders",
```
They are required to pass the test for checking if the order was succesfully placed.

The envs were added only in `cypress.2005.ci.json`. But we need to also introduce them in standard `cypress.json`.

To be verified: I believe it's needed also in other 2 CI configurations:
```
cypress.ci.ccv2.json
cypress.ci.1905.json
```

**Comment by bgambocjaviniar** [comment]
PR GH-9478

**Comment by giancorderoortiz** [comment]
This is good. Merci
