### ISSUE TITLE
Revise naming of things in public API of organization lib

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9484]
In the public API of the organization lib we have many things exported which have pretty general names compared to how specific they are. For example `unit-form.component` (`cx-unit-form`) - unit can be something very general in various contexts. This should be prefixed with `organization` (like the library name): `cx-organization-unit-form`.

Unit-form.component is just an example. It would be good to revise and fix general names before publishing a next stable release (3.0). Ideally all the component selectors in the `@spartacus/organization/administration` library are prefixed with word `cx-org` for consistency.

Note: changing the selectors of components should be followed by:
- updating css selectors
- updating e2e selectors

We should to it before relasing RC (no to introduce breaking changes later in RC).

We can start investigation now. But many developers are working simultanously on fixing bugs now. So we should merge the renaming lately before RC, when other PRs are mostly done - to avoid big (hard to resolve) conflicts with other PRs.

**Comment by tobi-or-not-tobi** [comment]
As long as we haven't done #9466, we should not have a lot of selectors that need to be changed. Currently we have these selectors:

- cx-cost-center-form
- cx-order-approval-detail-form
- cx-order-approval-list
- cx-organization-card
- cx-toggle-status
- cx-organization-form
- cx-organization-list
- cx-message
- cx-confirmation
- cx-notification
- cx-organization-sub-list
- cx-unit-form
- cx-unit-list
- cx-user-form

**Comment by Platonn** [comment]
As discussed offline, we should:
1. add new file `tslint.json` in `organization/administration` folder to enforce prefixing components and directives:
   ```tsconfig
    {
      "extends": "../tslint.json",
      "rules": {
        "directive-selector": [true, "attribute", "cx-org", "camelCase"],
        "component-selector": [true, "element", "cxOrg", "kebab-case"],
      }
    }
   ```
2. prefix accordingly all components' selectors in `organization/administration` folder with prefix `cx-org`
   1. the feature components (inside folders `/unit`, `/permission`, `/budget`, ...) don't have prefix yet. Let's add it, i.e. `cx-org-unit-form`
   1. To keep class names and file names simple, let's **omit** the `org-` prefix in **filenames** and `Org` in **class names**. Therefore we have concise and consistent filenames with class names. But we treat `cx-org` selector only as namespace for the component selector, according to https://angular.io/guide/styleguide#component-custom-prefix. 
   1. the shared components (inside folder `/shared`) are already prefixed with `cx-organization`. Let's change it to `cx-org` for consistency. Then drop the prefix `organization-` from file names and `Organization` from class names (due to reasons mentioned in `ii)` )
