### ISSUE TITLE
Long usernames broken UI in subsections with users

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9490]
Need to verify all subsection tables contains users (or approvers) in organization after fix.
![image](https://user-images.githubusercontent.com/8040837/96997332-dec58700-1531-11eb-9c93-77d017acec9b.png)

**Comment by Platonn** [comment]
### QA steps:

1. add entities with very long display names in various places. And verify they are truncated well with ellipsis: For example here:
   - [ ] http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Retail/users
        ![image](https://user-images.githubusercontent.com/4001059/97201308-97016280-17b2-11eb-9db7-4bcf3726270a.png)
   - [ ]    http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Retail/approvers
        ![image](https://user-images.githubusercontent.com/4001059/97201354-a5e81500-17b2-11eb-98ed-ef93e15b8dd6.png)
   - [ ]    http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Retail/addresses
        ![image](https://user-images.githubusercontent.com/4001059/97201430-ba2c1200-17b2-11eb-9d11-9201987f5025.png)
   - [ ]    http://localhost:4200/powertools-spa/en/USD/organization/units/Rustic%20Retail/cost-centers
         ![image](https://user-images.githubusercontent.com/4001059/97201461-c7e19780-17b2-11eb-9d14-d7bb71997345.png)

2. regression test if the main tables look as before and long texts are truncated with ellipsis there too:
   - [ ] http://localhost:4200/powertools-spa/en/USD/organization/users
        ![image](https://user-images.githubusercontent.com/4001059/97201566-e2b40c00-17b2-11eb-8c38-c8ca508984ac.png)
   - [ ] http://localhost:4200/powertools-spa/en/USD/organization/units
        ![image](https://user-images.githubusercontent.com/4001059/97201629-f2cbeb80-17b2-11eb-8ae9-fdf7d3c7a347.png)

3. repeat above testing for browsers:
   - [x] chrome
   - [x] firefox
   - [x] edge
   - [ ] safari
4. repeat above testing in mobile view
