### ISSUE TITLE
Move leftovers of order approval to organization lib from other libs

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9493]
- [x] `OrderDetailsApprovalDetailsComponent` in `storeferont` lib and its cms mapping:
https://github.com/SAP/spartacus/blob/bc69ae2e86bbe45e17df67f8081a92e60f0923ea/projects/storefrontlib/src/cms-components/myaccount/order/order-details/order-details.module.ts#L76-L78

- [x] translations in `assets` library
   https://github.com/SAP/spartacus/blob/bc69ae2e86bbe45e17df67f8081a92e60f0923ea/projects/assets/src/translations/en/my-account.ts#L82-L95

**Comment by WeizhengSap** [comment]
It depends on the ticket #9423, but still can be reviewed.

**Comment by WeizhengSap** [comment]
PR: https://github.com/SAP/spartacus/pull/9575
