### ISSUE TITLE
[Wait for CLC-2219] Remove workaround for disabled user

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9516]
After https://cxjira.sap.com/browse/CLC-2219 is done.

Remove the workaround from #9456 and use the regular disable logic.

**Comment by giancorderoortiz** [comment]
@LTiger14 is it technically feasible now to remove the workaround?

**Comment by Xymmer** [comment]
moved to https://jira.tools.sap/browse/CXSPA-305
