### ISSUE TITLE
Replace banners for Electronics Homepage

### ISSUE THREAD

**Issue by saad-mo** [SAP/spartacus#9517]
Update Electronics with new banners on the homepage.

1. Investigate how `smart` banners (the live text on image) work. 
2. Banners to match the new design provided by Manu 
3. Any sample date updates go in the `product-data` branch 
4. Ideally, new banners should work in conjunction with the blue theme. 

Tasks 
- [x] Update product carousel headings to "Top Selling TVs" and "What's New In Mobile Phones"
-  [x] Update products in product carousels to TVs and Phones 
- [x] Update banners with Impex statements 

PR - https://github.tools.sap/cx-commerce/spartacussampledata/pull/145

QA Steps - See PR description

**Comment by giancorderoortiz** [comment]
New visuals deployed here: 
http://spartacus-praca5.westeurope.cloudapp.azure.com:4200/electronics-spa/en/USD/ (CSR). 
http://spartacus-praca5.westeurope.cloudapp.azure.com:4100/electronics-spa/en/USD/ (SSR). 

Looks good. 
This ticket can be moved to done.

**Comment by giancorderoortiz** [comment]
@Manurod2018 fyi.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-19 at 5 23 47 AM](https://user-images.githubusercontent.com/46171897/99653781-79c55a00-2a27-11eb-9608-caec2736f627.png)
![Screen Shot 2020-11-19 at 5 24 01 AM](https://user-images.githubusercontent.com/46171897/99653783-7a5df080-2a27-11eb-80a6-14346250691f.png)
