### ISSUE TITLE
UI: Search box is visible when hamburger menu is on display. (Mobile View)

### ISSUE THREAD

**Issue by ren-tham** [SAP/spartacus#9520]
**Describe the bug**

While in mobile view, when hamburger menu is expanded, if the screen size is >=768 pixels, the search box will be visible. 
I'm not sure if this behaviour is expected.

**To Reproduce**
1. Enter mobile view.
2. Expand hamburger menu. 
2. Expand screen width so it is more than 768 pixels wide.

**Expected behavior**
Please verify if this is an expected bahaviour.

**Screenshots**

<img width="441" alt="issue" src="https://user-images.githubusercontent.com/71661414/97212855-50523f00-1797-11eb-8d04-3b1767a7ab10.PNG">

**Comment by Xymmer** [comment]
Shouldn't appear, well recheck and fix if so

**Comment by hackergil** [comment]
PR is approved but this is a breaking change. Please document it on the CSS doc [on the `v3-develop` branch](https://github.com/SAP/spartacus-docs/blob/v3-develop/_pages/home/updating-to-version-3/css-changes-in-version-3.md)

**Comment by giancorderoortiz** [comment]
Issue fixed. 

![Screen Shot 2020-11-19 at 11 18 47 AM](https://user-images.githubusercontent.com/46171897/99693299-32f05800-2a59-11eb-8c10-e2f7de4f2e11.png)
![Screen Shot 2020-11-19 at 11 19 08 AM](https://user-images.githubusercontent.com/46171897/99693300-34218500-2a59-11eb-8927-a675c3fb5cdb.png)
![Screen Shot 2020-11-19 at 11 19 52 AM](https://user-images.githubusercontent.com/46171897/99693301-34218500-2a59-11eb-86c8-7c855bcccfac.png)
