### ISSUE TITLE
Improvement. B2C/B2B WIth Miscellaneous SKU Quantities

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9525]
Upon further inspection, I can see that e2e checkout tests for b2b and b2c are done with single quantities for a particular SKU. 

As an improvement, E2E tests for b2b and b2c should include having multiple quantities of same SKU as follows: 

- [ ] 1. From Product Details Page, increase quantity to a random value before adding to cart. 
  - [ ] 1.a. Confirm Added-To-Cart Dialog includes the correct SKU quantity.
  - [ ] 1.b. Confirm cart contains the correct SKU quantity and correct $ amount
- [ ] 2. From Added-To-Cart Dialog, increase product quantity to a random value. 
   - [ ] 2.a. Confirm Total amount $ increases correctly. 
   - [ ] 2.b. Confirm cart contains the correct SKU quantity and correct $ amount. 
- [ ] 3. From Cart Page, increase product quantity of an SKU (obviously already in cart page). 
  - [ ] 3.a. Confirm SKU quantity increases correctly and subtotal amount for SKU is updated, as-well-as overall total amount.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-27 at 6 53 10 AM](https://user-images.githubusercontent.com/46171897/97292871-30b42880-1822-11eb-855e-b590a5c8cf71.png)
![Screen Shot 2020-10-27 at 6 53 33 AM](https://user-images.githubusercontent.com/46171897/97292875-314cbf00-1822-11eb-88e3-9651089a11a7.png)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-10-27 at 7 01 50 AM](https://user-images.githubusercontent.com/46171897/97292946-504b5100-1822-11eb-9c7b-ae559f683b81.png)

**Comment by giancorderoortiz** [comment]
In projects/storefrontapp-e2e-cypress/cypress/helpers/checkout-as-persistent-user.ts addProductToCart(), we only qty = 1

**Comment by giancorderoortiz** [comment]
Perhaps partially covered in projects/storefrontapp-e2e-cypress/cypress/helpers/product-details.ts.verifyQuantityInCart() method.

**Comment by KateChuen** [comment]
Moved to https://jira.tools.sap/browse/CXSPA-335
