### ISSUE TITLE
Manually test certain MyCo features after RC and at final release

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9530]
- [x] Check that non-admins are not able to access admin pages (besides MyCo Home)

Units
- [x] Disabling (and check that child units, the unit's cost centers and users are also disabled)
- [x] Enabling (no child units etc should be enabled automatically)
- [x] Change user roles in user subpanel
- [x] Edit/Delete addresses in address subpanel

Users
- [x] User entity can disabled/deleted (and disabling user causes remove all roles)
- [x] User password can be changed
- [x] No tests for any of sub category

Spend Permissions
- [x] Disabling

Cost Centers
- [x] Disabling

Budgets
- [x] Disabling

User Groups
- [x] Delete

**Comment by Matejk00** [comment]
Reopening for RC.4
