### ISSUE TITLE
Breakpoint size is 1px off

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9535]
The breakpoint service validates the window size against a configurable breakpoint size. The default configuration of the breakpoints is based on Bootstraps breakpoints. While the screen sizes have been copied over from the bootstrap docs/code, the comparison was actually off.

**Comment by giancorderoortiz** [comment]
how to qa?

**Comment by giancorderoortiz** [comment]
test ok. 
Test on actual mobile devices not done. 
Browser test doesn't yield errors. 
Firefox / Edge show a temporary misalignment in header/search box. But it goes away after a second or so.
