### ISSUE TITLE
Update Electronics home page carousels to show TVs and Phones

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9541]
To replace the two carousels on home:
![image](https://user-images.githubusercontent.com/4998145/97370864-5a06a000-1886-11eb-8c0b-15cfa5f3e4a8.png)

For first one, pick from all the new TVs
For the second one, pick from all the phones

**Comment by saad-mo** [comment]
- [PR](https://github.tools.sap/cx-commerce/spartacussampledata/pull/143)
- [QA steps](https://github.tools.sap/cx-commerce/spartacussampledata/pull/143#issue-258532) noted in PR description
