### ISSUE TITLE
Cds deprecations

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9547]
- [x] `projects/cds/src/merchandising/cms-components/directives/attributes/attributes.directive.ts` - params type changed, dc288ae695e724854cb377e52f4e6118cd328494
- [x] `projects/cds/src/profiletag/services/profile-tag.injector.service.ts` - constructor changed, 5780697702e8417715ab335a459048265264d7cf, d2fa40b0366b9169c1a51b459c93891b1603855e
- [x] `projects/cds/src/profiletag/services/spartacus-event.service.ts` - removed
- [x] `integration-libs/cds/src/merchandising/cms-components/merchandising-carousel/merchandising-carousel.component.ts` https://github.com/SAP/spartacus/pull/9503, new property in component, new feature config entry **(see note)** --> [Brian] **not deprecated as it's just a new property added and there was no deprecation in that component**

**Comment by bgambocjaviniar** [comment]
PR: GH-9641

**Comment by bgambocjaviniar** [comment]
The changes above were not exposed by the public api before the change, therefore closing
