### ISSUE TITLE
Check/handle deprecations for improved config providing

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9550]
Check wheter we should handle deprecations related to Improved providing of configurations:

- [x]  https://github.com/SAP/spartacus/pull/7327

- [x] https://github.com/SAP/spartacus/pull/7597

- [x] https://github.com/SAP/spartacus/pull/8789

- [x] e1066ff35be34f8ed44814f78f6d60bac6771d1b

- [x] 69d066ff80352a90d0b5abdbcecd43af8e09b301

- [x] https://github.com/SAP/spartacus/pull/9076 - not exact related to the above but related to default config which has been changed

- [x] https://github.com/SAP/spartacus/pull/7756 - same as above, related to env based variables

and how to do it (schematics/update migration docs) if yes.

Handle deprecations accordingly if check results say so.

**Comment by WeizhengSap** [comment]
Created a follow-up tickets: #9690 and #9697
