### ISSUE TITLE
Handle deprecations for ProductListComponentService

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9562]
According to #7987 and #8874 some breaking changes were introduced. Please check both PRs and either enchance schematics migrations script or update the migration docs.

**Comment by plabadie** [comment]
PR #9623 
Unit tests ran locally:
<img width="1177" alt="Screen Shot 2020-11-03 at 11 15 27 AM" src="https://user-images.githubusercontent.com/7065346/98038273-db13e900-1dea-11eb-94f3-3850f5cb142f.png">
<img width="937" alt="Screen Shot 2020-11-03 at 3 35 59 PM" src="https://user-images.githubusercontent.com/7065346/98038289-e0713380-1dea-11eb-88e8-2c910c039009.png">
