### ISSUE TITLE
Check outlets deprecations

### ISSUE THREAD

**Issue by mirkosoft** [SAP/spartacus#9563]
According to PRs #9431, #8662, #8200, #8224, #8117 some breaking changes were introduced since 2.0.x. They're already/mostly covered by #8116 and #8201 but let's double check everything was tackled either in the migration docs or schematics.

**Comment by Platonn** [comment]
Double checked all work is planned in other tickets. Closing.

- #9431 - no breaking changes. added deprecation. to be removed in 4.0 in https://github.com/SAP/spartacus/issues/9656
- #8662 - no breaking changes, no migration
- #8200 - breaking changes and migration handled in #8201
- #8224 - no breaking changes, no migration
- #8117 - breaking changes and migration handled in #8116
