### ISSUE TITLE
Why doesn't use "protected" methods & properties instead of "private" in classes

### ISSUE THREAD

**Issue by alvteren** [SAP/spartacus#9581]
Often I need extend any service or component for changing logic in one method. But I can't do this without "hack".

Last few cases:

Firstcase, our backend developer add few fields to cart items. Spartacus model is
```typescript
export interface Item {
  product?: any;
  quantity?: any;
  basePrice?: any;
  totalPrice?: any;
  updateable?: boolean;
}
```
my model:
```typescript
export interface CustomItem extends Item {
 weight: number;
 volume: number;
}
```
but property _items is private
![image](https://user-images.githubusercontent.com/17045072/97605544-ce287b80-1a1f-11eb-9f41-0a7c7ca59054.png)

Second case, I want to extend ProductListComponentService and I want to add in method getQueryFromRouteParams my custom condition

![image](https://user-images.githubusercontent.com/17045072/97605920-468f3c80-1a20-11eb-9b02-f7f730f50e2b.png)

if this method was protected, I would do
```typescript
protected getQueryFromRouteParams({
    brandCode,
    categoryCode,
    promoCode,
    query,
  }: ProductListRouteParams) {
    if (query) {
      return query;
    }
    if (categoryCode) {
      return this.RELEVANCE_ALLCATEGORIES + categoryCode;
    }
    if (brandCode) {
      return this.RELEVANCE_ALLCATEGORIES + brandCode;
    }
    if (promoCode) {
      return this.RELEVANCE_ALLCAMPAINGS + promoCode;
    }
  }
```
But I have to replace whole class

**Comment by Xymmer** [comment]
This is mostly by design, @dunqan to provide more info.

**Comment by Platonn** [comment]
The extensibility of the `ProductListComponentService` has been improved in v2.1. See PR https://github.com/SAP/spartacus/pull/7987
