### ISSUE TITLE
Don't check status of revoke request in e2e tests

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9590]
It does not matter which status code server responds with to revoke call. We should only check in e2e tests that the call happened (not the status code).

This causes random failure in login e2e

**Comment by Platonn** [comment]
More details from our conversation:
> In normal logout from OAuth server, we make one call to revoke `refresh_token` and second one with `access_token`. Nornally when the token already has been revoked, the endpoint shouldnt return 400 error. But it's not the case for the Commerce auth server endpoints.
> 
> Therefore our current test is now flaky. Sometimes we get from backend 2x 200, but sometimes combo of 200 and 400.
> To fix the e2e, we should check only if request was made, not its status.

**Comment by giancorderoortiz** [comment]
Please detail the flakiness from backend so I can research further.

**Comment by giancorderoortiz** [comment]
If you don't check the response code, how do you actually know the token was revoked?

**Comment by kacperknapik** [comment]
> If you don't check the response code, how do you actually know the token was revoked?

We test if we sent the request. We cannot test if the backend did something correctly. It's enough to check if we sent the request.

**Comment by kacperknapik** [comment]
How is this a security issue? It's an E2E test. Not a feature.

**Comment by kacperknapik** [comment]
> Please detail the flakiness from backend so I can research further.

It is already mentioned above:

> Sometimes we get from backend 2x 200, but sometimes combo of 200 and 400.

**Comment by giancorderoortiz** [comment]
Is it possible to add screenshots or HAR files please? The intermittence described here is rather worrisome. Backend issue, not frontend.

**Comment by giancorderoortiz** [comment]
I label issues with "security" regardless of their type when it requires further review/clarification or threat-modelling.  This labeling shouldn't interfere with the work at hand described in ticket.
