### ISSUE TITLE
Broken refreshing page after adding CDC Module

### ISSUE THREAD

**Issue by PrzemyslawBrambor** [SAP/spartacus#9597]
**Describe the bug**
After adding CDC Module every refreshing page on any site as logged user redirect to homepage. For non-logged user refreshing working as well.

`    CdcModule.forRoot({
      cdc: [
        {
          baseSite: 'NAME',
          javascriptUrl: 'URL',
          sessionExpiration: 120,
        }
      ],
    }),`

**To Reproduce**
1. Add CDCModule to spartacus project.
1. Log in
2. Go to any site for ex: product site.
3. Refresh page (F5)
4. You will be automatically redirected to homepage.

**Expected behavior**
Successfully refreshed page 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: any browser (Chrome, Firefox).

**Comment by Xymmer** [comment]
@marlass to review and maybe bring it to CDC devs

**Comment by marlass** [comment]
Problem is the subscription in `registerEventListeners` method.

This error clear mechanism and redirect should be moved to more appropiate place which is invoked after user login.

**Comment by temitopeog** [comment]
Thanks again @marlasak for looking into this!

**Comment by PrzemyslawBrambor** [comment]
@temitopeog @marlass any new status relating to this issue?

**Comment by marlass** [comment]
We are currently busy with preparation of 3.0 release. I can't promise any deadline with the fix for this issue.
