### ISSUE TITLE
Duplicated carts after login an anonymous user with products in cart (merge carts error)

### ISSUE THREAD

**Issue by daniel-z** [SAP/spartacus#9599]
**Describe the bug**
When you have are an anonymous users with products in your cart and before checkout you make a login, you get duplicated carts for the same user in backoffice. Also if you finish the checkout, in the UI you immediately get a new cart with the same items than the one before (because a duplicated was created on login).

**To Reproduce**
1. As an anonymous user get products in your cart
2. Register a new user or Login, If you login is important that the existent user has no cart created yet
3. You can see in the console duplicated calls to merge the same old cart, (you can see OldId parameters in the cart requests ) some of them have error response from the backend.
5. If you go to back office you can see 2 carts for the exact same user
4. If you finish your checkout looks like normal, but if you see your cart you still have items after order complete, (you get displayed the second cart)

**Expected behavior**
The items from the anonymous cart should get merged well and juts one time, the UI is calling the createCart function multiple times.

**Desktop (please complete the following information):**
 - OS: 10.15.5
 - Browser Chrome Version 86.0.4240.111 (Official Build) (x86_64)

**Additional context**
I'm still researching but I noticed that the **active-cart.seervice.ts** constructore code gets executed multiple times after login ...
**LINE 62:**
```
    this.authService.getOccUserId().subscribe((userId) => {
      this.userId = userId;
      if (this.userId !== OCC_USER_ID_ANONYMOUS) {
        if (this.isJustLoggedIn(userId)) { <<<<<<<< THIS IS TRUE MULTIPLE TIMES, MAKES SENSE JUST THE FIRST
          this.loadOrMerge(this.cartId);  <<<<<<<< THIS IS EXECUTED MULTIPLE TIMES
        }
      }
      this.previousUserId = userId;
    });
```

...
Then...
...
**LINE 187:**
```
      this.multiCartService.mergeToCurrentCart({   << ALSO EXECUTED MULTIPLE TIMES
        userId: this.userId,
        cartId,
        extraData: {
          active: true,
        },
      });
```

**Comment by Xymmer** [comment]
@daniel-z: Could you tell us which version of Spartacus libraries or repo you are using? then we can try to repro.

**Comment by arelsirin** [comment]
@Xymmer this issue took place in 2.0.2 and it was related to the same issue reported in https://github.com/SAP/spartacus/issues/9644 (it took place in the same project).

We believe it can be closed for the same reason stated in 9644.
