### ISSUE TITLE
Handle breaking changes for BaseSiteService

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#9601]
According to #9308, some breaking changes were introduced. Please check this PR and either enchance schematics migrations script or update the migration docs.

**Comment by WeizhengSap** [comment]
The test result:
![Screen Shot 2020-11-05 at 1 20 03 PM](https://user-images.githubusercontent.com/44440575/98281187-68ca1280-1f6a-11eb-9391-4b3b105d8970.png)

**Comment by bgambocjaviniar** [comment]
moved it back in code review as it requires a schematic owner's approval
