### ISSUE TITLE
Not able to extend UserAuthenticationTokenService 

### ISSUE THREAD

**Issue by Abi1234-git** [SAP/spartacus#9607]
**Describe the bug**

Spartacus version : 1.4.4

While extending UserAuthenticationTokenService I am getting error **Type '<T>(winRef: WindowRef, config?: StateConfig) => MetaReducer<T, Action>' is not a constructor function type**

We have a custom implementation of sso in which a separate call is made to refresh the token. We would like to stop the refreshToken call being made from spartacus to hybris.

**To Reproduce**

Try to extend the class UserAuthenticationTokenService.

**Expected behavior**

Able to extend UserAuthenticationTokenService in the custom code.

**Comment by Xymmer** [comment]
@Abi1234-git: To make a determination, we'd need to see your custom code. There's a feeling maybe it's something to do with how it's being used. That being said, we support only latest 1.x right now, so that would be 1.5.x. Can you upgrade and let us know if the problem still exists?

**Comment by marlass** [comment]
I tested this and for me everything is working correctly and I was able to extend this service in 1.4.4.

Example I tested on:
``` ts
import { Injectable, NgModule } from "@angular/core";
import { BrowserModule } from "@angular/platform-browser";
import { translationChunksConfig, translations } from "@spartacus/assets";
import { ɵbl as UserAuthenticationTokenService } from "@spartacus/core";
import { B2cStorefrontModule } from "@spartacus/storefront";
import { AppRoutingModule } from "./app-routing.module";
import { AppComponent } from "./app.component";

@Injectable({
  providedIn: "root",
})
class MyExtends extends UserAuthenticationTokenService {
  loadToken(userId, password) {
    console.log("extended class");
    return super.loadToken(userId, password);
  }
}

@NgModule({
  declarations: [AppComponent],
  imports: [
    BrowserModule,
    AppRoutingModule,
    B2cStorefrontModule.withConfig({
      backend: {
        occ: {
          baseUrl: "...",
          prefix: "/occ/v2/",
        },
      },
      i18n: {
        resources: translations,
        chunks: translationChunksConfig,
        fallbackLang: "en",
      },
      features: {
        level: "1.4",
        anonymousConsents: true,
      },
    }),
  ],
  providers: [
    {
      provide: UserAuthenticationTokenService,
      useExisting: MyExtends,
    },
  ],
  bootstrap: [AppComponent],
})
export class AppModule {}
```

Console log appeared on login and the app was fully functional.

**Comment by Abi1234-git** [comment]
Below is the code we were tried

import { ɵn as UserAuthenticationTokenService } from '@spartacus/core';
import { Injectable } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import {
  AuthConfig,
  OccEndpointsService,
  UserToken,
} from '@spartacus/core';
import { Observable, of } from 'rxjs';
@Injectable({
  providedIn: 'root',
})
export class CustomUserAuthenticationTokenService extends UserAuthenticationTokenService {
    constructor(http: HttpClient, config: AuthConfig,
        occEndpointsService: OccEndpointsService) {
        super(http, config, occEndpointsService);
    }
    refreshToken(refreshToken: string): Observable<UserToken> {
        return of(null);
    }
}

**Comment by marlass** [comment]
In version 1.4.4 `UserAuthenticationTokenService` is not available under `ɵn`. You should use `ɵbl`.

Under `ɵn` there is `getStorageSyncReducer` and that's why you probably have that error.

**Comment by Abi1234-git** [comment]
My code is working fine after changing the import to ɵbl. Thanks
