### ISSUE TITLE
UX for Image Zoom (review only)

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#9614]
Feature description (no SoT): https://cxwiki.sap.com/display/spar/Feature%3A+Image+Zoom
The goal is to contact Louis and go over the image zoomUI as is and make important suggestions and what we might do ino the future. This will allow us to finish this one off quickly.

**Comment by medzneel** [comment]
Had a meeting with Louis yesterday. Walked him over the wireframes. Moved it to code review.

**Comment by LTiger14** [comment]
Had a chat, everything looks good SOT updated.
