### ISSUE TITLE
PDP for Inexistent Product Missing Header Components/SAP Logo and Footer

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9617]
**Steps to Reproduce:** 
1. Navigate to Spartacus Electronics homepage.
1.a. Dev branch (Nov 2, 2020)
2. Navigate to any product's detail page. 
3. Change the URL to a non-existent product and load page.
3.a. (/product/1978440_md/norealproduct)

**Expected Behaviour:** 
3. Page shown shows SAP logo, and all components of header. If logged in, shows my account. Footer is shown as well. 

**Actual Behaviour:** 
3. Page shown shows header without language and currency drop-downs, no main navigation, no SAP logo.  There is no footer either. Only the consent link.

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-02 at 8 18 16 AM](https://user-images.githubusercontent.com/46171897/97875001-cf8bc980-1ce7-11eb-91e4-ee4804d7d471.png)
![Screen Shot 2020-11-02 at 8 22 34 AM](https://user-images.githubusercontent.com/46171897/97875002-cf8bc980-1ce7-11eb-807a-8f99fd8b1eb7.png)
![Screen Shot 2020-11-02 at 8 43 54 AM](https://user-images.githubusercontent.com/46171897/97875003-d0246000-1ce7-11eb-92b1-3ab1917d2edb.png)
![Screen Shot 2020-11-02 at 8 44 44 AM](https://user-images.githubusercontent.com/46171897/97875006-d0246000-1ce7-11eb-9754-557b187f1c6f.png)

**Comment by plabadie** [comment]
The problem seems worse now.  We see a blank page for a nonexistent product, but also for a non existing category and a non existing regular CMS content page

<img width="1279" alt="Screen Shot 2020-11-09 at 11 43 37 AM" src="https://user-images.githubusercontent.com/7065346/98570209-2c0b5d80-2281-11eb-9873-47e64788f555.png">
<img width="1281" alt="Screen Shot 2020-11-09 at 11 44 06 AM" src="https://user-images.githubusercontent.com/7065346/98570213-2d3c8a80-2281-11eb-94ee-a4bd961dc48e.png">
<img width="1277" alt="Screen Shot 2020-11-09 at 11 44 35 AM" src="https://user-images.githubusercontent.com/7065346/98570215-2f064e00-2281-11eb-9413-bee744dca976.png">

**Comment by plabadie** [comment]
We could redirect to the notFound page and it seems to fix the PDP not found issue, however, redirecting to the notFound page if not the experience we want to provide so far.  We want the not found url to stay in the browser address bar.

It appears the issue with the PDP not found is caused but the fact that all the components on the each page are rendered using the page context in the router state.  In cases like the not found page, the page context is the router state is the page context of the page not found.  This creates error when the components provide this context to the CMS api.

It looks like changing this logic would have a big impact on all the good pages rendering which we would not want to break to accommodate an edge case. 

This issue would benefit from an architecture investigation to align the proper solution.

**Comment by giancorderoortiz** [comment]
@tobi-or-not-tobi, @hackergil please seek comments above by Patrick. What is your opinion?

**Comment by Xymmer** [comment]
@dunqan to take care of it

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-12-04 at 10 39 21 AM](https://user-images.githubusercontent.com/46171897/101183165-20f7e300-361d-11eb-98a0-edbf6518c25c.png)
![Screen Shot 2020-12-04 at 10 39 30 AM](https://user-images.githubusercontent.com/46171897/101183169-20f7e300-361d-11eb-8135-109cb03efe8a.png)

**Comment by giancorderoortiz** [comment]
Test successful 👍
