### ISSUE TITLE
Approval Dashboard E2E Improvements

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9636]
Additional test cases to be considered for automation in cypress: 

1. Attempt to approve an order already approved. 
2. Attempt to reject and order already approved. 
3. Attempt to approve an order already rejected. 
4. Attempt to reject and order already rejected. 
5. Reject direct access to approval dashboard URL 
5.a. powertools-spa/en/USD/my-account/approval-dashboard
5.b. By non-admin. By non-approver. 
5.c. By an user that is no longer an approver. 
6. Cancel order approval attempt. 
7. Cancel order rejection attempt. 
8. Confirm order status in buyer's order history. (need to wait a few minutes after approve/reject).

**Comment by plabadie** [comment]
Closing this ticket for these reasons:
1-5 are covered in existing e2e tests.
6 and 7 are not features afaik.
8: We have mocking the order approval, therefore this is not possible.
