### ISSUE TITLE
Register user after guest checkout does not merge cart

### ISSUE THREAD

**Issue by arelsirin** [SAP/spartacus#9644]
**Describe the bug**
After performing a successful guest checkout, if you add an item to cart, then register a user, and log in, the cart is lost.

**To Reproduce**
1. Add an item to the cart, and complete the checkout process as guest.
2. After successful checkout, add a new item to cart and proceed to checkout.
3. This time, do not continue as guest, but register a user instead.
4. Log in with the registered user.
5. The user is redirected to homepage and the cart is empty.

**Expected behavior**
User should be redirected to checkout page and cart should contain the item added in step 2.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version:  86.0.4240.111

**Additional context**
It looks like there is a problem when merging the cart after the new user logs in.
There's a request to create a new cart but if fails because the `oldCartId` no longer exists:

<img width="1276" alt="Screen Shot 2020-11-03 at 6 40 04 PM" src="https://user-images.githubusercontent.com/2131732/98056175-de1bd300-1e04-11eb-8045-5b6339a161bf.png">

<img width="727" alt="Screen Shot 2020-11-03 at 6 39 41 PM" src="https://user-images.githubusercontent.com/2131732/98056139-c3e1f500-1e04-11eb-8aff-1f5695d4951d.png">

Also noticed that in the method:

```
private addEntriesGuestMerge(cartEntries: OrderEntry[]) {
    const entriesToAdd = cartEntries.map((entry) => ({
      productCode: entry.product.code,
      quantity: entry.quantity,
    }));
    this.requireLoadedCartForGuestMerge().subscribe((cartState) => {
      this.multiCartService.addEntries(
        this.userId,
        getCartIdByUserId(cartState.value, this.userId),
        entriesToAdd
      );
    });
  }
```

`this.multiCartService.addEntries` method is not being executed as `requireLoadedCartForGuestMerge` is not emitting values.

**Comment by Xymmer** [comment]
@arelsirin: can you tell us what version of Spartacus libraries you are using? We have a feeling this is a backend limitation but we will verify.

**Comment by arelsirin** [comment]
@Xymmer  Sure thing, sorry, it is version 2.0.2.

One more thing I noticed is that the same issue takes place if a user just logs in (no need for registering) after performing a guest checkout.

**Comment by arelsirin** [comment]
After digging deeper into the issue we noticed that it was a custom extension of the ActiveCartService that was causing the issue. The ActiveCartService constructor was being executed twice and this was making the cart merge intent to be executed 2 times. Problem was solved by creating a separate service instead of extending ActiveCartService.
