### ISSUE TITLE
Warning after page refresh on MyCompany pages

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#9647]
**Steps to reproduce:**
1. Login as Linda Wolf
2. Go to My Company and click"Budgets" for example from My Company homepage.
3. When  budget list will load just refresh the page.

**Current behaviour:**
After page refresh user is redirected back to My Company homepage and warning message shows up:
"No sufficient permissions to access this page".

![warning](https://user-images.githubusercontent.com/6958810/98086876-a3a34c00-1e7f-11eb-9e3d-2bb96b82b024.png)

**Expected result:**
Should back to active route after page refresh and warning message should not be displayed.

**Comment by tobi-or-not-tobi** [comment]
I've also noticed that if you're on a non-related storefront page, you will be randomly redirected to the login page. This might be related to one of the new "guards".

**Comment by Pucek9** [comment]
That change in adming guard should help, but IMO better to investigate why userService.get emits empty object
![image](https://user-images.githubusercontent.com/8040837/98112467-90ee3e80-1ea2-11eb-8a0a-65999c7bc130.png)
