### ISSUE TITLE
Shipping address cannot be created for my-company unit

### ISSUE THREAD

**Issue by Matejk00** [SAP/spartacus#9667]
**Steps to reproduce:**
1. Login as Linda Wolf
2. Go to My Company and select Units from my-company homepage
3. Select random unit from the list/tree then go to "Shipping addresses"
4. Click Create from top right to create new shipping address
5. Fill a form with valid data and click save

**Current behaviour:**
Address is not created, error message shows up

![image (12)](https://user-images.githubusercontent.com/6958810/98244643-0bd15b00-1f70-11eb-9325-6c6899b7ec57.png)

**Expected result:**
Recently created address shows up on a list with no errors

Similar to: #9572

**Comment by Pucek9** [comment]
Created and updated too
