### ISSUE TITLE
DoD update

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9673]
Add the following requirements and their descriptions for new features to our Definition of Done doc:

- [x] Lazy loading

- [x] Sample data

- [x] Schematics deprecations

**Comment by hackergil** [comment]
[Doc PR](https://github.com/SAP/spartacus-docs/pull/856)

**Comment by gladius-mtl** [comment]
PR merged https://github.com/SAP/spartacus-docs/pull/856
