### ISSUE TITLE
Deferred loading causes flickering with SSR

### ISSUE THREAD

**Issue by dunqan** [SAP/spartacus#9677]
When deferred loading is used, there's a flickering issue caused when the page is initially served by SSR. Since the SSR generated page will ignore deferred loading, all DOM will land initially in the browser. When, however, the CSR kicks in, the DOM will be replaced by the CSR rendered DOM. The CSR app will respect the deferred loading configuration, which leads to some elements being cleared initially. 

We must avoid flickering to ensure a seamless transition from SSR to CSR.

**Comment by dunqan** [comment]
QA steps:

- enable deffered loading:
```
  deferredLoading: {
    strategy: DeferLoadingStrategy.DEFER,
    intersectionMargin: '50px',
  },
```
- check, if there is no flivker with SSR enabled

**Comment by giancorderoortiz** [comment]
No flickering detected when enabling deferred loading and using SSR. 
Looks very good.
