### ISSUE TITLE
Handle constructor deprecation for 'CmsComponentsService'

### ISSUE THREAD

**Issue by WeizhengSap** [SAP/spartacus#9690]
https://github.com/SAP/spartacus/blob/develop/projects/storefrontlib/src/cms-structure/services/cms-components.service.ts#L28-L36

We need schematics to support it (`Object` type in parameter)

**Comment by LTiger14** [comment]
Support for this will be added to schematics in #9670 & #9643

**Comment by plabadie** [comment]
We'll document these changes instead in order not to delay the release.
