### ISSUE TITLE
Handle contructor deprecation migration for 'BreakpointService'

### ISSUE THREAD

**Issue by LTiger14** [SAP/spartacus#9691]
The constructor in `BreakpointService` got a new dependency in 3.0. This dependency is :

`@Inject(PLATFORM_ID) protected platform: any`. Schematics does not support `@Inject(PLATFORM_ID)` yet nor does it support the `any` type in constructors.

Once #9670 and #9643 are done, create the constructor migration for `BreakpointService`.

**Comment by ren-tham** [comment]
Ticket was already done for deprecation 2.0 => 3.0.
