### ISSUE TITLE
Breaking change on storefront component that was introduced in 8763

### ISSUE THREAD

**Issue by bgambocjaviniar** [SAP/spartacus#9695]
https://github.com/SAP/spartacus/pull/9154

`projects/storefrontlib/src/layout/main/storefront.component.ts`

1 - need to mention in the `md` that the behavior for this method only gets fired when it's a header
2 - method param changed from MouseEvent to any so it's worth mentioning in the method-and-deprecation

**Comment by ren-tham** [comment]
Pr (#9699 )

**Comment by Matejk00** [comment]
Please provide QA steps

**Comment by ren-tham** [comment]
QA steps can be found here: https://github.com/SAP/spartacus/issues/8763#issuecomment-700943051
