### ISSUE TITLE
Handle breaking change for constructor in ConfigInitializerService

### ISSUE THREAD

**Issue by plabadie** [SAP/spartacus#9697]
See https://github.com/SAP/spartacus/blob/develop/projects/core/src/config/config-initializer/config-initializer.service.ts#L23

Depends on schematics support for the `any` type in parameter.

**Comment by LTiger14** [comment]
Support for this will be added to schematics in #9670 & #9643

**Comment by plabadie** [comment]
We'll document these changes instead in order not to delay the release.
