### ISSUE TITLE
Handle CSS deprecations for Scheduled replenishement

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9701]
Replenishments PR #9114

Example from previous major version (V2) [here](https://sap.github.io/spartacus-docs/css-changes-in-version-2/)

**Comment by hackergil** [comment]
Docs PR [here](https://github.com/SAP/spartacus-docs/pull/852)

**Comment by gladius-mtl** [comment]
Doc PR merged: https://github.com/SAP/spartacus-docs/pull/852
