### ISSUE TITLE
Fresh look at order details page statuses

### ISSUE THREAD

**Issue by Xymmer** [SAP/spartacus#971]
Was playing with states in Backoffice. Need to map out all the states we want to display to make sure we have proper test coverage. @KateChuen will need some help here.

**Comment by KateChuen** [comment]
Statuses available in backoffice that we'll need to test to make sure they are displayed correctly:
Cancelled
Tax Not Committed
Shipped
Ready
Payment Not Captured
Pickup complete
Pickpack
Waiting
Ready for pickup

**Comment by KateChuen** [comment]
Reference: https://wiki.hybris.com/display/docsap/Order+and+Consignment+Status+Flow

There are 
- Order Status (a lot seems to happen in the background; do we have control over these? Or all done by OMS?) 
Statuses: Checked_invalid, checked_valid, Fraud_checked, Wait_fraud_manual_check, cancelled, ready, suspended, cancelling, payment_not_captured, payment captured, completed)
- Consignment Status
Statuses: Ready, ready_for_pickup, Picked, pickup_complete, cancelled, ready_for_shipping, shipped, rejected. 
Statuses not used: waiting, pickpack
