### ISSUE TITLE
Auth/session management deprecations - guards

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9711]
Ticket created based on #9622
That one contained a lot of work and I splitted the part that is not tightly related to auth module, but changed with the `epic/auth` merge.

- [x] `projects/storefrontlib/src/cms-components/cart/cart-not-empty.guard.ts` - changed constructor
- [x] `projects/storefrontlib/src/cms-components/checkout/guards/checkout-auth.guard.ts` - changed constructor --> **EDIT: Brian:** this was already resolved in #9640
- [x] `projects/storefrontlib/src/cms-components/checkout/guards/not-checkout-auth.guard.ts` - changed constructor
- [x] `projects/storefrontlib/src/cms-components/myaccount/order/amend-order/cancellations/order-cancellation.guard.ts` - changed constructor
- [x] `projects/storefrontlib/src/cms-components/myaccount/order/amend-order/returns/order-return.guard.ts` - changed constructor
- [x] `projects/storefrontlib/src/cms-components/product/product-variants/guards/product-variant.guard.ts` - changed constructor
- [x] `projects/storefrontlib/src/cms-components/user/login-route/login.guard.ts` - new file **EDIT: Brian:** new file and was never in 2.0, therefore not a deprecation
- [x] `projects/storefrontlib/src/cms-components/user/logout/logout-guard.ts` - removed file
- [x] `projects/storefrontlib/src/cms-components/user/logout/logout.guard.ts` - new file

**Comment by bgambocjaviniar** [comment]
PR: GH-9717
