### ISSUE TITLE
Schematics - generate the Spartacus configuration in a separate file

### ISSUE THREAD

**Issue by znikola** [SAP/spartacus#9727]
As our configuration grows bigger every day, we don't want to pollute customers' `app.module.ts`.
Therefore, the goal of this issue is to generate the Spartacus configuration in a separate file (e.g. `spartacus-configuration.ts` and just import it in the `app.module.ts`.

However, the whole schematics code base assumes that the Spartacus configuration is _always_ present in the `app.module.ts`. In order to support the extracted configuration, we have to go through our schematics code base, and perform checks where the customers' configuration is stored.

Probably the best way to do it is to create a common utility function which will do this check and return the path to the configuration file (the separate file or the app.module.ts). If the configuration is not detected at all, we will throw an error, and the schematics will not be able to run.

**Comment by tobi-or-not-tobi** [comment]
Additionally, we could import the configuration in a provider, to demonstrate more flexibility to customers to add smaller pieces of configurations in various places. The `provideConfig` is a nice utility function that we could demonstrate for this purpose.

**Comment by znikola** [comment]
After [this conversation](https://sap-cx.slack.com/archives/GQF7UGB8Q/p1605515794020400) it was decided to park this issue for now.

**Comment by marlass** [comment]
Issue resolved with new app structure and schematics update
