### ISSUE TITLE
Unauthorized users that try to access the approval dashboard should be redirected to the home page

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9738]
When this is fixed, please remember to unskip the corresponding test case on `order-approval.e2e-spec.ts`

**Comment by giancorderoortiz** [comment]
Really good works. Merci 👍 
I can see anonymous user is redirected to home page. 
Call to users/current/orderapprovals?pageSize=5&lang=en&curr=USD is not made, which is where the content is.
I do see that the cms components for the approval page are downloaded in other calls, but this is not shown to end user. 
Eventually user only sees login page. 

Anonymous user redirect: 

![Screen Shot 2020-11-24 at 7 42 58 AM](https://user-images.githubusercontent.com/46171897/100096200-b202d900-2e29-11eb-9a20-b7f57e0900fd.png)
![Screen Shot 2020-11-24 at 7 47 43 AM](https://user-images.githubusercontent.com/46171897/100096201-b29b6f80-2e29-11eb-8720-93e813ca7777.png)

Admin user: 
![Screen Shot 2020-11-24 at 7 48 22 AM](https://user-images.githubusercontent.com/46171897/100096255-c3e47c00-2e29-11eb-8488-8cbc0478744b.png)
