### ISSUE TITLE
Global Messages with different text reset timer for all (can't repro?)

### ISSUE THREAD

**Issue by PascalAOMS** [SAP/spartacus#9741]
**Describe the bug**
When triggering multiple global messages with different text contents one after the other, the last one resets the timer of the previous one.

Issue for custom implementation:
On the cart page a global message is displayed when a product is removed from the cart to show the product name.
Since all product have a different name, global messages are collected one after the other and stay for a long period of time cluttering the UI.

**Tell us the version of Spartacus**
- Library version: 2.0.3

**To Reproduce**
1. Trigger the GlobalMessagesService multiple times with different text content and the same type (success/error).

**Expected behavior**
Each instance of a global message should have its own timer and disappear not dependend on other global messages.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: current Chrome

**Comment by Xymmer** [comment]
timeout should be per message but also we want to refactor how global messages appear... putting to future for now

**Comment by Xymmer** [comment]
moving this into consideration for a short-term fix.
can we eliminate the problem of messages piling up i.e. new messages don't reset the timer?

**Comment by Pucek9** [comment]
It was designed as you expect. I tried reproduce your issue and it works well: https://github.com/SAP/spartacus/compare/feature/GH-9741?expand=1#diff-8a5ec88f9f213e6ce9f4ea31c0326161310ebeabf9d738a7fbad217725139ba7R258

@PascalAOMS
Please provide more details about your implementation

**Comment by giancorderoortiz** [comment]
Is this issue still considered a bug? There appears to be disagreements.

**Comment by Pucek9** [comment]
So far I have not received a reply from @PascalAOMS. I know only they updated to Spartacus 3 and don't observe this bug anymore.

**Comment by giancorderoortiz** [comment]
Closing per dev comments above. 
@PascalAOMS please re-open if necessary. 
@hackergil, @dunqan fyi
