### ISSUE TITLE
B2C Storefront Deployment Via Schematics Fails

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9745]
Objective: Deploy latest develop branch with Schematics (Using run.sh script)

**Steps to Reproduce in a Linux Server:** 

1. Clone spartacus repo. 
2. Navigate to /script/install folder
3. Copy config.default.sh to config.sh
4. Update backend_url to a 2005 configured server. 
5. Leave spartacus version as 'latest'
6. Execute ./run.sh install command
7. Execute ./run.sh start
8. Open spartacus storefront and navigate through storefront. 

**Expected Results:** 
6. No need to keep entering credentials. 
6.a. Verdaccio process starts correctly. 
7. No failures .
8. Spartacus B2C storefront renders without problems. 

**Actual Results:** 
6. Have to keep entering credentials, or pressing enter several times. 
6.a. Verdaccio process fails the first time around. Second time is ok. 
7. No failures. 
8. Empty page shown. Spartacus B2C storefront is empty. 
8.a. There is no security exception link in dev-tools console.

**Comment by giancorderoortiz** [comment]
Configuration file: 

![Screen Shot 2020-11-10 at 7 16 24 PM](https://user-images.githubusercontent.com/46171897/98822872-5b47d900-23ff-11eb-9b9a-07debb15d4ff.png)


Results obtained: 
![Screen Shot 2020-11-10 at 7 14 35 PM](https://user-images.githubusercontent.com/46171897/98822868-5aaf4280-23ff-11eb-8deb-6e9e13b74275.png)
![Screen Shot 2020-11-10 at 7 14 55 PM](https://user-images.githubusercontent.com/46171897/98822871-5b47d900-23ff-11eb-92c1-a07fc0bdf9ca.png)

**Comment by mirkosoft** [comment]
Prompt for credentials is probably caused by not present auth token for the localhost. According to [README](https://github.com/SAP/spartacus/blob/develop/scripts/install/README.md):

> before running the main script, please ensure that line
> `//localhost:4873/:_authToken="VNOlucnBmPrXVjzHVEHtWQ=="`
> is added to the `~/.npmrc` file

**Comment by mirkosoft** [comment]
Was able to reproduce (blank screen) but only when providing incorrect `BACKEND_URL`. Therefore I think it's related to wrong config for the application. Please re-check with working backend (like https://spartacus-dev0.eastus.cloudapp.azure.com:9002)

UPDATE: Unfortunately I was able to reproduce it (the blank page issue with no errors in the console; no problems with Verdaccio) using installation script. I suggest to try reproduce it by creating new fresh app and adding Spartacus using schematics.

**Comment by giancorderoortiz** [comment]
FYI. 
This was working on Thursday Nov 5. Broken on Nov 6.

**Comment by hackergil** [comment]
Fixed CSR. SSR is still failing (it hangs). Created #9768 to address it.

**Comment by giancorderoortiz** [comment]
Issue solved. 
Good. Thanks.
