### ISSUE TITLE
Make star rating disabled by default

### ISSUE THREAD

**Issue by tobi-or-not-tobi** [SAP/spartacus#9782]
Customers using the star rates to show the product rates would not expect to explicitly set the disabled input to true. There's literally one place where we need the enable the rating (in the create review component).

**Comment by tobi-or-not-tobi** [comment]
QA steps:
the product review rating component should work as before:
- showing the rating anywhere
  - should not have any in enabled interaction (means; change star rating on hover/click)
  - only when you create a review, you should be able to add the rate

**Comment by giancorderoortiz** [comment]
ok
