### ISSUE TITLE
Extendability of multi-provided classes - interation 2

### ISSUE THREAD

**Issue by Platonn** [SAP/spartacus#9797]
Same as https://github.com/SAP/spartacus/issues/5129. Since the previous ticket was implemented, a year passed and we've added in the codebase a lot of new multi-provided tokens with property `useClass`. This prevents extendability of those classes for customers. We should change it to `useExisting` for tokens provided with `multi: true`.

Optionally, we could try to avoid it happen in future - research or create custom TSLint rule that could prevents having multi-provided tokens with `useClass` property.

Not a breaking change.

**Comment by wangzixi-diablo** [comment]
in develop branch, totally 161 multi: true in 81 files need to be manually checked:

<img width="386" alt="clipboard" src="https://user-images.githubusercontent.com/58975336/100302685-ce437900-2fd5-11eb-99fc-e68d72400fb8.png">
