### ISSUE TITLE
[Med] Enhance test coverage

### ISSUE THREAD

**Issue by Larisa-Staroverova** [SAP/spartacus#9809]
The list of the files that have a low test coverage
- [x] configurator-group-menu.component.ts
- [x] configurator-attribute-drop-down.component.ts
- [x] configurator-attribute-input-field.component.ts
- [x] configurator-attribute-numeric-input-field.component.ts
- [x] configurator-attribute-radio-button.component.ts
- [x] configurator-form.component.ts
- [x] configurator-group-title.component.ts
- [x] configurator-overview-form.component.ts
- [x] configurator-product-title.component.ts
- [x] configurator-storefront-utils.service.ts
- [x] configurator-groups.service.ts
- [x] configurator.reducer.ts
- [x] variant-configurator-occ.adapter.ts
- [x] occ-configurator-variant-normalizer.ts
- [x] occ-configurator-variant-serializer.ts
- [x] occ-configurator-textfield.adapter.ts
- [x] configurator-textfield-form.component.ts
- [x] configurator-textfield-input-field.component.ts

**Comment by steinsebastian** [comment]
numeric-input-field.component.ts already has coverage of 98,51%/97,14% (statements/branches). Missing branches are devMode: true/false and getLocale to return a value. 
occ-configurator-textfield.adapter.ts: Not clear how to test the missing parts
