### ISSUE TITLE
My Company E2E Pipe Checks in table

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#9810]
When data is transformed through a pipe. the text is different to what are likely to predict so we need to include the transformation in the tests. The current `useDataPipe` in `my-company-list.ts` implementation is not the proper way to do this. Marked with `// TODO: Think of a way to use some sort of tranformation function/config`.

**Comment by mszczepaniak** [comment]
On hold due to 3.0 priorities.

**Comment by Xymmer** [comment]
closing as not important and/or taking care o by refactoring
