### ISSUE TITLE
Refactor My Company E2E Configs

### ISSUE THREAD

**Issue by Zeyber** [SAP/spartacus#9811]
Current configuration is a bit rigid when scaling or adding new features to the implementation (new sorts of checks). We could alleviate this by having configs be more catered to respective pages as opposed to sharing values between them (eg. `createValue` is checked in details and form but may not necessarily be the same in both. Marked in `my-company-row.config.ts` as `// TODO: move configs into table: { ... }, details: { ... }, form: { ... }  format`.

**Comment by kacperknapik** [comment]
After conversation with @Zeyber I'm unassigning myself from this ticket. Will review it though
