### ISSUE TITLE
[IN EPIC] Missing migrations for checkout connector/adapter

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9842]
New param:
![image](https://user-images.githubusercontent.com/6259079/99514650-48e41700-298c-11eb-8878-7017052ef11a.png)
![image](https://user-images.githubusercontent.com/6259079/99514708-54cfd900-298c-11eb-90ad-eca17cbb1848.png)

**Comment by Platonn** [comment]
Note: Same for OccCheckoutAdapter
