### ISSUE TITLE
Deploy previews with Netlify

### ISSUE THREAD

**Issue by hackergil** [SAP/spartacus#9918]
- [ ] Test the CLI to do a preview deployment
- [ ] Test Travis Netlify deploy target
- [ ] Incorporate way of deployment into travis build (after unit tests)
- [ ] Get the URL of the deploy preview to run e2es against it
- [ ] Figure out how to make spartacus work in Netlify site (site/currency/lang)

**Comment by marlass** [comment]
Could you also validate if we can deploy with SSR and have multiple deployments per PR (eg. B2C, B2B)?
