### ISSUE TITLE
Navigation Node CMSLinkComponents do not render style classes

### ISSUE THREAD

**Issue by janwidmer** [SAP/spartacus#9948]
**Describe the bug**
When adding a style class within the CMSLinkComponent of a navigation node, the class does not get rendered.

**Tell us the version of Spartacus**
3.0.0-next.3

**To Reproduce**
1. Go to smartedit on e.g. the Electronics Spartacus Demo Instance
2. Click on Navigation Management
3. Edit a Category Navigation node of the first level category navigation
4. Edit the Navigation Node Entry
5. Edit the CMSLinkComponent
6. Add a custom Class to the `Style Classes` field
7. Save and sync the catalogue
8. Open the storefront

**Expected behavior**
The link of the respective navigation node contains the custom class

**Screenshots**
CMS Link Component Dialog:
![image](https://user-images.githubusercontent.com/3381820/99677651-3e07b000-2a7a-11eb-8f47-a37455acc30f.png)

Navigation UI Component Template:
![image](https://user-images.githubusercontent.com/3381820/99677922-89ba5980-2a7a-11eb-9f53-c964a4e617a7.png)

Component json Request:
![image](https://user-images.githubusercontent.com/3381820/99679940-cf782180-2a7c-11eb-9fa3-8fb54083484d.png)

Link rendered in the Frontend:
![image](https://user-images.githubusercontent.com/3381820/99677689-4a8c0880-2a7a-11eb-89c9-cc5beeffa9e2.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser All
 - Version All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser All
 - Version All

**Additional context**
It seems, that the class get sent within the compoent json request but then it is not passed to the generic-link component in the component template markup. By the way, the same (wrong?) behaviour happens for the "Open In External Window" option, which also just get's ignored (not set in the code and not working).

There seems to be a general discrepancy between the CMSLinkComponent and the Generic-Link (which is used on a lot of places) regarding their data model..

**Comment by tobi-or-not-tobi** [comment]
@janwidmer thanks again for reporting, I can confirm that this is both buggy and unexpected. 
- the target (`_blank`) link is not working, as the API response is a string "true" vs "false", where a boolean primitive is expected
- the styleAttributes are actually being rendered on generic link component, but the navigation UI component doesn't populate the styleAttributes from the store
- the styleClasses are not being rendered, nor populated. 

A few changes got me here: 

![image](https://user-images.githubusercontent.com/4745807/99792318-3520e800-2b27-11eb-9bf6-1b2cd048f55f.png)

- cms link components pass the style attributes and style classes to the generic link component
- navigation ui component passes the style attributes and style classes to the generic link component
- generic link component correctly uses the `target` attribute (the previously used `attr.target` is ignored by the router logic


I'll do a PR to add the fixes

**Comment by janwidmer** [comment]
Hey @tobi-or-not-tobi, 

Thanks for analysing. I know, it's an annoying question, but as our project is subjected to go live end of january, I have to ask, will the fix be available in version 3.0.0 which I guess is planned to be released sometimes in dezember?

Depending on that, we need to override the navigation component or not, as we need those style classes for a feature wanted by the client..

**Comment by tobi-or-not-tobi** [comment]
@janwidmer yes i'm going to threat it as a bug, so it's either in 3.0.0 or patched soon after.

**Comment by janwidmer** [comment]
@tobi-or-not-tobi ok cool thanks.

**Comment by tobi-or-not-tobi** [comment]
QA:
- Validate that router navigation nodes will open in _blank window, if you configure in backend to do so
- Add style attributes to navigation node components in backend, and validate that the storefront renders the style attributes in the `style=""` property of the navigation anchor links
- Add style classes to navigation node components in backend, and validate that the storefront adds the class names to the anchor links

**Comment by janwidmer** [comment]
@tobi-or-not-tobi question about the target logic, currently the target is not listed as a property when calling the generic-link here: https://github.com/SAP/spartacus/pull/9965/files#diff-f4ef6080c5d132ac1b1c039a82f475637a7ef12f8db23b55cdbec8207606ab63

Shouldn't that also be added here to have a working "target" property at the end in the `generic-link`?

**Comment by bgambocjaviniar** [comment]
Testing for below are good 🟢 

1 )`Add style attributes to navigation node components in backend, and validate that the storefront renders the style attributes in the style="" property of the navigation anchor links`
2) `Add style classes to navigation node components in backend, and validate that the storefront adds the class names to the anchor links`


Testing for below is not working as intended (does not open new window) 🔴 
1) `Validate that router navigation nodes will open in _blank window, if you configure in backend to do so`

---------------

### _Using 'latest' develop and dev2-azure (left the properties as shown in the screenshots)_

- **CMS Link components properties being properly updated** 🟢 
<img width="1151" alt="1" src="https://user-images.githubusercontent.com/29099466/101089325-02450e00-3583-11eb-87b7-8b5116ffbbf3.png">

- **style and class changes showing up in the dom** 🟢 
<img width="609" alt="2" src="https://user-images.githubusercontent.com/29099466/101089358-0f61fd00-3583-11eb-92a2-1e3fe2f72dc8.png">
<img width="597" alt="3" src="https://user-images.githubusercontent.com/29099466/101089366-11c45700-3583-11eb-9b27-6f91cce1f8b2.png">

- **style and class applying to the affected elements** 🟢 
<img width="551" alt="4" src="https://user-images.githubusercontent.com/29099466/101089427-230d6380-3583-11eb-8d13-d71c8510bb72.png">

- **Again, however, it does not redirect to a new blank page even when the target is true meaning it should open a new page.** 🔴 
- backoffice has it set to newWindow for the `external window` property
--> contact us node has target="_blank" accordingly to the logger outputting the end object node, which still does not open a new window
<img width="489" alt="Screen Shot 2020-12-03 at 4 28 50 PM" src="https://user-images.githubusercontent.com/29099466/101090524-c8750700-3584-11eb-81ca-5a48b6bd8788.png">

**Comment by tobi-or-not-tobi** [comment]
@janwidmer i'm sure this was part of the original fix, but it somehow got lost. My bad. A fix is on its way.

**Comment by janwidmer** [comment]
@tobi-or-not-tobi perfect, thanks
