### ISSUE TITLE
Add validation of ng version for spartacus 3.0 migrations.

### ISSUE THREAD

**Issue by marlass** [SAP/spartacus#9959]
Validate before running migrations if customer have update to ng10.

**Comment by LTiger14** [comment]
Spartacus schematics runs `@angular/core` update on it's own, which means no error is thrown. Afterwards, a user simply needs to run `ng update @angular/cli@10` after the schematics migration.

Alternatively, `ng update @angular/cli@10` can be run before `ng update @spartacus/schematics`.

Both of these cases will be documented.
