### ISSUE TITLE
Missing information about reason of impossibility to Edit/Enable

### ISSUE THREAD

**Issue by Pucek9** [SAP/spartacus#9991]
Previously we displayed information about why `Edit` or `Disable` buttons are disabled. 

![image](https://user-images.githubusercontent.com/8040837/104495561-34ad4680-55d8-11eb-8e8b-c55b43c4432d.png)
![image](https://user-images.githubusercontent.com/8040837/104495610-4393f900-55d8-11eb-8294-7df5e2e14860.png)

In the newest UI it's missed. 

My proposal is to add some generic popup/tooltip component which can be triggered by click on info icon (hover would not work on most of mobile devices)

![image](https://user-images.githubusercontent.com/8040837/104497591-e3eb1d00-55da-11eb-83fa-d445f0902f32.png)
![image](https://user-images.githubusercontent.com/8040837/104498609-37aa3600-55dc-11eb-8816-8026131b5d50.png)

**Comment by Pucek9** [comment]
Additional question: do we want to display icon if there is no any important message available now? Should we disable it or hide if empty?

**Comment by Pucek9** [comment]
My new proposal mock which uses existing local message component instead of popover.
![image](https://user-images.githubusercontent.com/8040837/104753822-cb087600-5758-11eb-86a1-fd05fa5e2ab8.png)

**Comment by developpeurweb** [comment]
@Manurod2018 can we please get your feedback on this?

**Comment by vekterdude** [comment]
![ticket_10717](https://user-images.githubusercontent.com/44620139/104785450-8bda2500-5758-11eb-8999-e1a7254d0040.png)

**Comment by vekterdude** [comment]
![ticket_10717](https://user-images.githubusercontent.com/44620139/104785555-c3e16800-5758-11eb-89cf-2b2b2a08b597.png)

**Comment by vekterdude** [comment]
Hi Xymmer,

This is not a good idea. '?' icons in this context are never about principle site functionality, but more to explain the meaning of nouns "What is a Budget?" "What is a Cost Center?"
What a user would expect to see by clicking on that info circle would be the meaning of disabling and editing.
So this would be an opportunity to say: 'Disabling a unit will also disable all of it's child units' but that is proactive information and not resolving an immediate blockage.
Hiding these info banners behind that icon would create a problem of discoverability and frustrate users - imo.
Cheers,
Anthony

**Comment by Manurod2018** [comment]
![D - B2B - Cost Centers 01](https://user-images.githubusercontent.com/37299626/104961855-334b9780-59a5-11eb-885a-c1e3ac12f05a.png)
![D - B2B - Cost Centers 02](https://user-images.githubusercontent.com/37299626/104961858-347cc480-59a5-11eb-9bc2-2e57ea2327f7.png)

I agree, most users will never click on the info icon, as they have no idea that this icon would provide information enabling them to activate the EDIT action. Having this type of information always visible is good practice. If we want to save screen real estate, we can combine both information under one box.
