### ISSUE TITLE
Login as B2B Admin in B2C Shows a "My Groups" Option Under My Account

### ISSUE THREAD

**Issue by giancorderoortiz** [SAP/spartacus#9992]
**Steps to Reproduce:** 
1. Navigate to Spartacus Electronics storefront
2. Login as b2b admin. (i.e. linda.wolf)

**Expected Results:** 
1. Only MyAccount shown in header.

**Actual Results:** 
2. MyAccount and MyGroups shown. 
2.a. Links available through MyGroups redirect to page-not-found. (Spending Limits, Groups, Spending Accounts, Members, Member Permissions, Thresholds)

**Comment by giancorderoortiz** [comment]
![Screen Shot 2020-11-24 at 8 00 39 AM](https://user-images.githubusercontent.com/46171897/100098384-f8593780-2e2b-11eb-8ddd-0a08ea374178.png)
![Screen Shot 2020-11-24 at 8 04 50 AM](https://user-images.githubusercontent.com/46171897/100098390-fa22fb00-2e2b-11eb-9b76-1136200b15c4.png)
![Screen Shot 2020-11-24 at 8 04 57 AM](https://user-images.githubusercontent.com/46171897/100098392-fa22fb00-2e2b-11eb-95ba-cf50d6514d13.png)
![Screen Shot 2020-11-24 at 8 05 06 AM](https://user-images.githubusercontent.com/46171897/100098393-fabb9180-2e2b-11eb-86c9-e40a213e06f7.png)

**Comment by Xymmer** [comment]
not supported in Electronics, not sure we can do anything about it at the moment

**Comment by Xymmer** [comment]
- Can we remove 'my groups' entry from b2c (electronics, apparel) sample data and see what happens
- Make sure to document that b2b my company is only supported for b2b backend

There's a b2b / b2c flag but probably not useful here.

**Comment by bgambocjaviniar** [comment]
* Note this is just waiting for Parth to create the PR in the backend sample data repo as he does not have the write permission yet, however we fixed the issue at hand when we paired

**Comment by Parthlakhani** [comment]
PR for sample data repo: https://github.tools.sap/cx-commerce/spartacussampledata/pull/149

**Comment by Parthlakhani** [comment]
> PR for sample data repo: https://github.tools.sap/cx-commerce/spartacussampledata/pull/149

Merged

**Comment by bgambocjaviniar** [comment]
closed as it was merged as mentioned above
